### ISSUE TITLE
Question regarding request stream

### ISSUE THREAD

**Issue by Bondifrench** [request/request#1009]
Using a callback we do

```
request(url, function(err, resp, body) {
     console.log(body);
     }
```

I just want to do the same but using streams and pipe
doing:

```
request(url).pipe(process.stdout)
```

gives me the entire stream including headers and other things, how can I pipe just the body of the request? Should I use a transfrom stream? or is there an option I can use?

**Comment by chshouyu** [comment]
x is writeable stream or readable stream?
