### ISSUE TITLE
Support for getHeaders removed

### ISSUE THREAD

**Issue by mllrjb** [request/request#1061]
Broken by the fix for #1001

**Comment by calibr** [comment]
Is this still an issue? I would like to submit a pull request to caseless if it is

**Comment by mastermatt** [comment]
I don't see where `getHeaders` existed before the [commit](https://github.com/request/request/pull/1006/files#diff-ccc0734f65dd7a299409ff07d35be095L1106).
`setHeaders` was removed and instead `setHeader`, which proxies to `caseless.set`, can take an object as a single first param with key-value pairs.

Other than that getting all the headers can be done by simply accessing the object at `request.headers`.

I think this issue should be closed to avoid confusion.
