### ISSUE TITLE
ECONNREFUSED when connecting locally

### ISSUE THREAD

**Issue by clintandrewhall** [request/request#108]
I've enjoyed using request on a number of projects, but this problem has me stumped.

When attempting to use request to access a data-serving endpoint on my local machine on, say, port 3000, I get a ECONNREFUSED.  Yet if I use a simple function using the http module, it processes normally.

Perhaps there is something wrong with my server code that would deny some header or agent set by this module, but I'm just not sure.  I'm using Connect, which is pretty standard out of the box... any insight?

**Comment by MichaelTaylor3D** [comment]
I get this same error, my node is running on 8081 and Im trying to POST to another service that is running on my local machine on 8080. I can post to external websites fine it seems. Any ideas?

**Comment by vkhvst** [comment]
are you binding to `0.0.0.0`?
here's what worked for me for rails/puma:
`rails s -b 0.0.0.0`
https://github.com/puma/puma/issues/782
