### ISSUE TITLE
straight serialize / deserialize cookie jar?

### ISSUE THREAD

**Issue by coolaj86** [request/request#1085]
I want to transfer a session to another instance of request and I need to serialize the jar.

The example shows formats of stringifying and arrayifying cookies that don't seem to be compatible with setting them.

For example, none of these work:

``` javascript
cookiestr = j.getCookieStringSync(uri)
j.setCookie(cookiestr, uri);
```

``` javascript
cookiestr = j.getCookieStringSync(uri)
cookie = request.cookie(cookiestr, uri)
j.setCookie(cookie, uri);
```

``` javascript
cookies = j.getCookiesSync(uri)
j.setCookie(cookies, uri);
```

**Comment by icodeforlove** [comment]
I don't think that FileCookieStore solves the base problem of why this is a complicated thing to do from the get go. I posted a way of doing this in #760, but it really feels like this could be something that request supports on its JAR.

**Comment by arcman77** [comment]
function saveThoseCookies( jar, host){
  //jar is an object returned from request.jar()
  //host is the host/domain of the url you used to make earlier api calls from that made the cookies
  var cookieStr = jar.getCookieString( host );
  return cookieStr.split('; '); //yes, you want the space
}

function putCookiesInJar( cookies, host ){
  var jar  = request.jar();
  cookies.forEach( function( cookieStr ){
    jar.setCookie( cookieStr, host);
  });
  return jar;
}

var loginOptions = {
    url: loginUrl,
    json: {
        email: email,
        password: password
    },
    jar: request.jar()
};
//make your api call
request.post(loginOptions, function(){
  window.myCookies = saveThoseCookies( loginOptions.jar, loginOptions.url );
  window.hostURL   = loginOptions.url;
});
//sometime later...
var newJar = putCookiesInJar( myCookies, hostURL );
// make oauth calls with this jar!

**Comment by icodeforlove** [comment]
@arcman77 this way is very brittle if you're using the jar for multiple things. Please refer to my post in #760.

**Comment by arcman77** [comment]
Hi Chad,

I understand your concerns, however your solution requires that you install
the tough cookies package again in addition to request requiring it.
Request does not expose tough cookie methods or api's, and so you are
forced to do what I did. If you could offer insight into a safer, more
stable way to do this directly with the request package, I'm all ears!

Cheers!
Andrew

**Comment by lalitkapoor** [comment]
you could use the file store. From the docs:

```javascript
var FileCookieStore = require('tough-cookie-filestore');
// NOTE - currently the 'cookies.json' file must already exist!
var j = request.jar(new FileCookieStore('cookies.json'));
request = request.defaults({ jar : j })
request('http://www.google.com', function() {
  request('http://images.google.com')
})
```

**Comment by lalitkapoor** [comment]
You could pass in a memory cookie store and use that same store for new instances:
https://github.com/SalesforceEng/tough-cookie/blob/master/lib/memstore.js
