### ISSUE TITLE
Let's spend this money :)

### ISSUE THREAD

**Issue by mikeal** [request/request#1122]
A while back there was a bountysource campaign that brought in over $1,700 for request.

https://www.bountysource.com/teams/request/fundraiser

I haven't been able to figure out the best way to spend this and so far haven't done any bounties. It's probably best to hand this over to all the contributors since I'm a giant bottleneck on this.

**Comment by nylen** [comment]
Hey guys.  Let's spend this money :)

I have access to our Bountysource account now.  I do want us to discuss our process for accepting and paying out changes pretty thoroughly first though.  I am thinking that collaborators should have the option to vote on bounty amounts.  I have not done something like this before, so any suggestions are welcome.

We'll also need to get in touch with our major donors and see what features they'd like, but we want to be wary of letting people buy influence over the direction of the project.

What features are worth paying for?  Some initial ideas:

- $x per % of increased test coverage (to me, this is a no-brainer; it's a very objective measure of our code quality and how well we understand our codebase)
- Browser test suite (hey look @eiriksm :)
- Modularization and refactoring
- Preparing for 3.0 release with streams2

**Comment by seanstrom** [comment]
@nylen I think you outlined some of the big ones that users will really want.
This one may be covered by the 3.0 release or future releases, but what about major API changes that users would want. Perhaps Promise support is something users would like, or just other integrations in general.

**Comment by seanstrom** [comment]
Also Documentation refactoring should be added.
https://github.com/request/request/issues/1340

**Comment by nylen** [comment]
Ok.  What amount do you think is appropriate for test coverage increases?  We're at 88% right now.

I propose that collaborators can vote on issue bounties by saying so in the issue, and we'll take the average if everybody is around the same range.  I'll start with #1366 (I would have done the same for your proxy refactoring too, if we had had this discussion yet).

I'm certainly not opposed to documentation refactoring being added, but I'm not comfortable doing much given that I'm planning on doing the work.  Want to wait until I send the PR (should be sometime this week...) then propose an amount there?

Major new features are good too, but -1 on promise support **specifically** in request (it would probably have to break streams, and there are pretty nice wrapper libraries for it).  We just have to avoid breaking compatibility until we're ready for 3.0.

**Comment by seanstrom** [comment]
Mmm, Well even though its at 88% I would like there to be tests around more of the modules we have been refactoring, and maybe even some clean up and maintenance of the existing test files.
I think that's a good amount of work and could be approximately priced at maybe $100 - $150.
Maybe more if the PR does more than what I just mentioned.

The promises idea is more of an example of something that could be apart of our plugin ecosystem.
It would be nice if we officially supported one. It probably shouldn't be apart of request-base though.

Perhaps we should come up with a quick tier list of what type of things get a general amount.
Like we have Milestones, Features, Bugs, and Tasks.

$100+ - Milestones

$50+ - Features

$10+ - Bugs

$5+ - Tasks

**Comment by nylen** [comment]
I like the tiered structure as a guideline, that will help give some objectivity.  Though I guess I was thinking higher amounts in general, we programmers are valuable after all :p  Don't forget, too, features or bugs often require a lot of research and test writing.

I suggested $30 for the OAuth refactoring, seems like that would roughly make sense if we double all the amounts in your list, so that's what I propose.  Also I don't really want to bother with anything less than $10 or so.  I'm hoping that if some of our backers see that we're making good use of bounties, more will come.

---

[`request-promise`](https://github.com/tyabonil/request-promise) looks pretty good, but won't work for large files because they always add a callback, which buffers the response.  I don't see any problem with linking to it if we include that caveat.  We should think about outreach to other plugin authors too, anything we link to should be really well tested and documented.

**Comment by seanstrom** [comment]
Yeah I we should be able to tweak our money tier however we want, at least this way we can settle on a fair amount and I'm glad we error on the side of more money :)

I saw you mention request-promise in another PR, so I'm going to look over the library and get familiar with it. In general I think reaching out to other authors would be awesome. And I completely agree that any library we recommend should be well vetted.

I guess all thats left is to payout for the OAuth refactoring and just set the pace.
