### ISSUE TITLE
request form-data error:  Missing Content-Type on busboy

### ISSUE THREAD

**Issue by bluecenter** [request/request#1125]
Follow this link: https://github.com/mscdex/busboy to create a server and the multipartFormData test case fails. Tried to add the headers manually, however still not works.

```
---------------------------------------------------------------------------------------------------------
    throw new Error('Missing Content-Type');
          ^
Error: Missing Content-Type
    at new Busboy (\node_modules\busboy\lib\main.js:23
:11)
    at Server.<anonymous> (\tests\bench\busboy.js:9:18
)
----------------------------------------------------------------------------------------------------------
multipartFormData.my_field = 'my_value';
multipartFormData.my_buffer = new Buffer([1, 2, 3]);
multipartFormData.my_file = fs.createReadStream(__dirname +  '/avatar2.jpg');
multipartFormData.remote_file = request('http://nodejs.org/images/logo.png');

var req = request.post({
  url: 'http://localhost:8000/',
  formData: multipartFormData
}, function () {
  console.log(' -------------  done')
})
```

**Comment by bluecenter** [comment]
@scaret yes, the issue is gone.

**Comment by Waqas-Ali-Azhar** [comment]
Hi, I am getting the same error, could not resolve it, here is my code
` busboy.on("file", (fieldname, file, filename, encoding, mimetype) => {
    // console.log(fieldname);
    // console.log(filename);
    // console.log("start");
    // console.log(mimetype);
    // console.log("vicky end");

    const imageExtension = filename.split(".")[filename.split(".").length - 1];
    imageFileName = `${Math.round(Math.random() * 100000)}.${imageExtension}`;
    const filepath = path.join(os.temdir(), imageFileName);
    imageToBeUploaded = { filepath, mimetype };
    file.pipe(fs.createWriteStream(filepath));
  });
  busboy.on("finish", () => {
    admin
      .storage()
      .bucket()
      .upload(imageToBeUploaded.filepath, {
        resumable: false,
        metadata: {
          metadata: {
            contentType: imageToBeUploaded.mimetype
          }
        }
      })
      .then(() => {
        const imageUrl = `https://firebasestoreage.googleapis.com/v0/b/${
          firebaseConfig.storageBucket
        }/o/${imageFileName}?alt=media`;
        return db.doc(`/users/${req.user.handle}`).update({ imageUrl });
      })
      .then(() => {
        return res.json({ message: "Image uploaded successfully" });
      })
      .catch(err => {
        console.error(err);
        return res.status(500).json({ error: err.code });
      });
  });
  busboy.end(req.rawBody);`

**Comment by Waqas-Ali-Azhar** [comment]
Hey, I am getting the same error, missing content type at Bus Boy main.js line 23, i tried npm update but of no use.
below is the code for file uploading
`
busboy.on("file", (fieldname, file, filename, encoding, mimetype) => {
    const imageExtension = filename.split(".")[filename.split(".").length - 1];
    imageFileName = `${Math.round(Math.random() * 100000)}.${imageExtension}`;
    const filepath = path.join(os.temdir(), imageFileName);
    imageToBeUploaded = { filepath, mimetype };
    file.pipe(fs.createWriteStream(filepath));
  });
  busboy.on("finish", () => {
    admin
      .storage()
      .bucket()
      .upload(imageToBeUploaded.filepath, {
        resumable: false,
        metadata: {
          metadata: {
            contentType: imageToBeUploaded.mimetype
          }
        }
      })
      .then(() => {
        const imageUrl = `https://firebasestoreage.googleapis.com/v0/b/${
          firebaseConfig.storageBucket
        }/o/${imageFileName}?alt=media`;
        return db.doc(`/users/${req.user.handle}`).update({ imageUrl });
      })
      .then(() => {
        return res.json({ message: "Image uploaded successfully" });
      })
      .catch(err => {
        console.error(err);
        return res.status(500).json({ error: err.code });
      });
  });
  busboy.end(req.rawBody);

`
