### ISSUE TITLE
File uploaded through request is corrupt on the other end

### ISSUE THREAD

**Issue by gCurtisCT** [request/request#1160]
See here:

http://stackoverflow.com/questions/26350068/corrupt-files-when-uploading-from-node

This could be an issue with node-form-data, though. I'll cross-post this there.

**Comment by yushaUzumo** [comment]
I have a similar issue. I tried doing `fs.createReadStream('./Statement.odt').pipe(req).pipe(process.stdout);` My issue is that I don't know how to retrieve the piped file. I tried `this.request.body` but I get `[object Object]`. When I do `JSON.strigngify(this.request.body)` I get `{}`. My question is how do I access the `[object Object]` that I am getting on the other end?

On the other end I am using meteor.js restivus package for my api. Please help.

**Comment by yushaUzumo** [comment]
I found the answer. I am posting the file in the body itself with json option set to true. Here is the client code:

```
	url = 'http://localhost:3000/api/v1/images/';
	fs.readFile('./Statement.odt', function read(err, data) {
		if (err) {
			throw err;
		}
		console.log(data);
		//var file = new Buffer(data).toString('base64');
		var file = data;
		//var file = fs.readFileSync('./Statement.odt',{ encoding: 'base64' });
		
		var req = request.post({
		  uri: url, 
		  headers:	 {
			'X-User-Id': userId,
			'X-Auth-Token': authToken
		  },
		  /*form: { //Post to the body instead of the form
			  file: file,
			  name:"Statement.odt",
		  },*/
		  body: file, //Post to the body instead of the form
		  json:true  //Set json to true
		  //encoding: null
		}, function(err, httpResponse, body) {
		  if (err) {
			return console.error('post failed:', err);
		  }
		
		  console.log('Get successful!  Server responded with:', body);
		});
	});
```

Here is how I access the json in the body on the server-side:

```
var buf = JSON.stringify(this.request.body);
var buf1 = JSON.parse(buf).data
var bufferOriginal = Buffer.from(buf1)
```

Please also see [stackoverflow question](https://stackoverflow.com/questions/51476981/how-do-i-post-a-plain-file-buffer-instead-of-binary-encoded-file-when-posting-wi/51536849#51536849)
