### ISSUE TITLE
ECONNRESET when requesting URLs over HTTPS (POODLE related?)

### ISSUE THREAD

**Issue by lwansbrough** [request/request#1175]
I'm trying to access an endpoint: `https://user.auth.xboxlive.com/user/keys` which is usually accessible (try it using Postman, or any client that uses TLS - you'll need to set `Accept: application/json` too) but I get an ECONNRESET when trying to access it using Node.js (specifically, using `request`)

**Comment by mediafreakch** [comment]
For me the following (also described in the [docs](https://github.com/request/request#using-optionsagentoptions) ) worked:

```
request.get({
    url: 'https://api.some-server.com/',
    agentOptions: {
        secureProtocol: 'SSLv3_method'
    }
});
```
