### ISSUE TITLE
accented characters? � � �

### ISSUE THREAD

**Issue by phstc** [request/request#118]
Hi!

I'm trying to scrap a web page with accented characters á é ó ú ê ã etc. I tried `encoding: utf-8`, but I'm still getting this ��� characters in the result.

```
 request.get({
      uri: url,
      encoding: 'utf-8'
      // ...
```

**Comment by vickygill69** [comment]
request({url: "www.example.com", **encoding: "latin1"**}, function (error, response, html) {
	console.log('error:', error);

**Comment by edujr1** [comment]
@vickygill69 Thanks, your answer resolv my problem

**Comment by ricardovf** [comment]
setting encoding to null and then using the response buffer with iconv worked for me. Thanks!
