### ISSUE TITLE
Request with interval() eventually produces ESOCKETTIMEDOUT and ECONNRESET

### ISSUE THREAD

**Issue by doapp-ryanp** [request/request#1231]
I have a persistent process that goes off and crawls urls every X minutes. 

```
node v0.10.33
request 2.44.0
ubuntu 14.04 on EC2
uname -a
Linux ip-myip 3.13.0-37-generic #64-Ubuntu SMP Mon Sep 22 21:28:38 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```

I get into this state periodically where all my requests get ESOCKETTIMEDOUT and ECONNRESET errors. Also when it gets into this state, my tcp connections for node process is stuck at only 13 established (these are my mongodb connections):

```
lsof -p 9514 | grep TCP | wc -l
13
```

If I restart node things go back to normal (for a while).  The lsof command goes up and down as expected, until issue is hit again.

This is the block of code that is called via `interval()`

```
var separateReqPool = {maxSockets: 100},
      reqObj = {
            pool: separateReqPool,
            uri: feed.feedUrl,
            headers: {"User-Agent" : "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_6_8) AppleWebKit/537.13+ (KHTML, like Gecko) Version/5.1.7 Safari/534.57.2"},
            timeout: 5000,
            jar: false,
            maxRedirects: 5,
            strictSSL: false
      };

    request(reqObj, function(error){
        if(error){
            cfg.logger.error("ERR: bad request: "+error, error);
        }
    })
        .on('response', function(response){
            ...
        })
        .on('error', function(error){
            cfg.logger.error("ERR: "+error, error);
        })
        .on('end', function(){
            cfg.logger.info("feed pull complete - "+feed.feedUrl);            
        });
```

Any ideas? thanks in advance.

**Comment by tsirolnik** [comment]
@doapp-ryanp Sorry for bumping, but just to make it clear as I'm having this problem too - Are you passing agent:false in Request's options?

As in - 
```js
new Request({agent:false}, (error, response, body) => {
         ....
        });
```

Or is it something internal?

**Comment by nanocent** [comment]
@doapp-ryanp 
Any references for how it works? 
> I was not super familiar with how pooling worked in node, but now I am.

**Comment by Duncan00** [comment]
https://nodejs.org/api/http.html#http_agent_maxsockets

if agent:false, it means every request we will create a new agent and so establishing a new connection to server, would it make any performance issue if setting it?

**Comment by nanocent** [comment]
I think so. if we set `agent:false` the things move down to pooling moves down to OS level and number of open sockets by the process will increase if the number of requests are very high. That's the thing pooling tries to solve. You may get ESOCKETTIMEDOUT but you are protected from OS failures due to too many open sockets.

**Comment by cancerberoSgx** [comment]
@tsirolnik The solution I've found is setting this options to request(): 
```
agent: false, pool: {maxSockets: 100}
```
Notice that after that, the timeout can be lying so you might need to increase it.

**Comment by soubhikchatterjee** [comment]
What would be the difference between 

1. using the global agent with `maxSockets = Inifinity` 
2. using a new agent for each request (so called `agent: false` to request package)

Why is 2 a fix and not 1?
