### ISSUE TITLE
Can't handle InvalidUri when on streaming mode

### ISSUE THREAD

**Issue by mcortesi** [request/request#1264]
When I do a request on streaming mode. That is, i don't pass a callback to the request function, it doesn't seem possible to handle InvalidURI errors.

By code inspection, of the Request.init method, you can see:

``` javascript
  if (!self.uri.host && self.uri.protocol !== 'unix:') {
    // Invalid URI: it may generate lot of bad errors, like "TypeError: Cannot call method 'indexOf' of undefined" in CookieJar
    // Detect and reject it as soon as possible
    var faultyUri = url.format(self.uri)
    var message = 'Invalid URI "' + faultyUri + '"'
    if (Object.keys(options).length === 0) {
      // No option ? This can be the sign of a redirect
      // As this is a case where the user cannot do anything (they didn't call request directly with this URL)
      // they should be warned that it can be caused by a redirection (can save some hair)
      message += '. This can be caused by a crappy redirection.'
    }
    // This error was fatal
    return self.emit('error', new Error(message))
  }
```

The code detects the error and does an emit() of it. But, since this is part of the initialization process, we haven't yet had the possibility to register an on('error') handler. Something like this:

``` javascript
request('a bad uri').on('error', errorHandler)
```

Our errorHandler won't be registered since the error emision happens before the .on() call. So, the default error handler takes control and it crashes.

The only error handler present at that moment, is the one is set within the Request.init method for the callback sent on the request() call. So this, works ok:

``` javascript
request('a bad uri', callback)
```

The problem is, that if i do this, the response body will be buffered, and that's not desirable in my case.

My diagnosis, might be incorrect, and I might be missing something here, sorry about that. But if I'm correct, this problem is also true for every detected error within the `init()` method, before the process.nextTick at the end.

A Probable fix would be to delay all error emision to the process.nextTick at the end of init(). I can do that and send the pull request, but i'm not sure if it would break something else. Let me know

**Comment by FredKSchott** [comment]
Taking a look at this now

**Comment by FredKSchott** [comment]
On second thought, this will definitely be a backwards incompatible change. Currently, the init function does this:

```javascript
  if (!self._callback && self.callback) {
    self.on('error', self.callback.bind())
    self.on('complete', self.callback.bind(self, null))
  }

  // ... do some stuff ...

  if (!self.uri) {
    return self.emit('error', new Error('options.uri is a required argument'))
  }
```

Because a listener for the "error" event is always added when a callback is present, these errors have never been thrown in the call-back case.

**Comment by carlosvillademor** [comment]
Hi guys, 

I bumped into this issue too. What is the current situation with it?

Kudos for your work on this library!

**Comment by fiznool** [comment]
@carlosvillademor wrap the call to `request` in a try-catch block. This will catch the error.
