### ISSUE TITLE
v2.46.0 can't open as many parallel requests

### ISSUE THREAD

**Issue by GUI** [request/request#1284]
After upgrading to v2.46.0, I noticed that the request library can't open as many requests in parallel as before. The issue appears to stem from the change in #1168 to change the `process.nextTick` call into a `setImmediate` call. This change seems like it will generally make the request library less aggressive in hogging the event loop, which is probably a good thing, but if you're actually trying to achieve high levels of request concurrency, it seems to prevent that. Now, despite the lower concurrency, there isn't a huge performance difference between the approaches, although it does seem like the library is marginally slower when using `setImmediate` with a bunch of parallel requests.

My use-case might not be very common, but why I care about the request concurrency is that I'm using the request library inside an integration test that performs parallel requests against a server. The test is trying to check rate limits and concurrency limits on the HTTP server, so this is why I noticed the reduced concurrency (since the tests are no longer able to achieve the levels of concurrency we're trying to test).

I'm not sure what the best solution is here, but would there be any interest in a pull request to make this configurable (so you could pick whether you wanted to use `setImmediate` or `process.nextTick` for the `defer` behavior)? Because it seems like `setImmediate` might be the right call in most cases, but if you're actually trying to achieve higher levels of concurrency, then it seems like you have to use `process.nextTick`. Or is there maybe some other way I'm missing to achieve high concurrency levels with `setImmediate`?

I've put together a little example of a server and client to demonstrate the changes in behavior caused by this between v2.45.0 and v2.46.0:

**server.js**

``` js
var http = require('http');
var server = http.createServer(function(req, res) {
  res.writeHead(200, { 'Content-Type': 'text/plain' });
  res.end('Hello World\n');
});
server.listen(8099, '127.0.0.1');

var openConnections = 0;
var maxOpenConnections = 0;
server.on('connection', function(socket) {
  openConnections++;
  if(openConnections > maxOpenConnections) {
    maxOpenConnections = openConnections;
  }

  socket.on('close', function() {
    openConnections--;
  });
});

setInterval(function() {
  console.info('maxOpenConnections: ' + maxOpenConnections);
}, 1000);
```

**client.js**

``` js
var async = require('async'),
    request = require('request');

var options = {
  pool: {
    maxSockets: 500,
  },
};

var start = Date.now()
async.times(250, function(index, callback) {
  request.get('http://127.0.0.1:8099/', options, function(error, response) {
    callback(error);
  });
}, function() {
  console.info('Finished. Took: ' + (Date.now() - start) + 'ms');
});
```

Steps to reproduce:
- Run the server.js file. This server just keeps track of the maximum number of concurrent open connections and prints it out every second.
- While the server is running as a separate process, run the client.js. This attempts to open 250 parallel requests to the server and prints how long it took to execute all of them.

Prior to #1168:
- The server reports `maxOpenConnections: 250` meaning that all 250 of the parallel requests were at least connected to the server at one time.
- On 3 test runs, the client reports execution times of 210ms, 214ms, and 212ms

After #1168:
- The server reports `maxOpenConnections: 17` meaning at no point were more than 17 concurrent connections actually established to the server.
- On 3 test runs, the client reports execution times of 232ms, 233ms, and 236ms

**Comment by dmiddlecamp** [comment]
Just tested this on the latest 2.61.0, and I'm not seeing this issue when using

```
		var requester = request.defaults({
			pool: {
				maxSockets: 100
			}
		});
```

I've been able to easily hit that consecutive socket count or higher.  However I am spreading these requests over a few seconds, so I'm not trying to open all the same connections in the exact same instant.
