### ISSUE TITLE
client side certificate doc mistake

### ISSUE THREAD

**Issue by OferE** [request/request#1290]
There is a mistake in the documentation on how to use client side certificate.
The cert, key and passphrase should be given to the "options" object and not to the agentOptions.

I also created a pull request for this:
https://github.com/request/request/pull/1289

I didn't touch the SSLV3 paramters inside the agentOptions, so please also verify if this is the correct place for it.

I hope this helps.

**Comment by nylen** [comment]
Fixed by #1585.
