### ISSUE TITLE
Disable HTTP tunneling for all protocols

### ISSUE THREAD

**Issue by danypype** [request/request#1293]
From the docs:
- **tunnel** - If `true`, then **always** use a tunneling proxy. If `false` (default), then tunneling will only be used if the   destination is https, or if a previous request in the redirect chain used a tunneling proxy.

What if I need to use a proxy that doesn't support tunneling to make a **https** request?

Shouldn't this module have an option to completely disable tunneling for all protocols?

**Comment by twolfson** [comment]
+1 I have the same issue. I use a local proxy for mocking HTTP responses during testing:

https://github.com/uber/eight-track

It is the same setup; make a request on behalf of the user but handle all HTTPS from the proxy server to target server. It would be nice if I didn't have to set up an HTTPS server/certificate to acheive the same result.

**Comment by twolfson** [comment]
I spent the last hour looking into this. My last statement was invalid, an HTTPS server is not necessary. However, it looks like I need to reconstruct the remainder of the parsing of the HTTP data after accepting the `connect` event.

https://github.com/joyent/node/blob/v0.10.35/lib/http.js#L1976-L1984

This seems like a huge undertaking as the `node` source doesn't seem to expose this outside of its parser and I cannot/do not want to restart parsing after it has already started.

I am going to fork, use the fork, and submit a PR to patch.

**Comment by danypype** [comment]
@twolfson, Have you considered something like [nock](https://github.com/pgte/nock) as an alternative to achieve what you need? It's a nice module to mock HTTP responses on testing. It might save you some time.

**Comment by twolfson** [comment]
Yep, `nock` has a few drawbacks and lacks the same set of benefits as `eight-track`:

- `nock` is in-process which does not allow for reuse on distributed systems (e.g. child processes)
- `nock` requires setting up responses for every endpoint, `eight-track` is usually a one-time setup
    - This also plays into maintenance; if an external API signature changes, `nock` fixtures need to be manually updated whereas we can delete saved `eight-track` HTTP responses and re-run the tests.

**Comment by nylen** [comment]
@twolfson thanks for pointing us to `eight-track`, I've been looking for a library like this.

**Comment by twolfson** [comment]
Does this mean the PR is going to get landed? It is #1344 fwiw.
