### ISSUE TITLE
Post file in Body has issue: Fixed

### ISSUE THREAD

**Issue by git-neelesh** [request/request#1296]
Hi Team,

I found an issue when you posting file into Body(json) its converting Buffer data into String, so I have fixed that issue, Below is the code:

```
Request.prototype.json = function (val) {
  var self = this
  if (!self.hasHeader('accept')) {
    self.setHeader('accept', 'application/json')
  }

  self._json = true
  if (typeof val === 'boolean') {
    if (typeof self.body === 'object') {
      self.body = safeStringify(self.body)
      if (!self.hasHeader('content-type')) {
        self.setHeader('content-type', 'application/json')
      }
    }
  } else {
    //Neelesh Fix
    if(Buffer.isBuffer(val))
      self.body = val;
    else
      self.body = safeStringify(val);
    if (!self.hasHeader('content-type')) {
      self.setHeader('content-type', 'application/json')
    }
  }

  return self
}
```

**Comment by usmanimtiaz** [comment]
i'm getting this error there's no explanation for this 
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
<title>Error 500 x-nuance-sessionidd65178ba-8c70-49ee-bd22-ac1789c49a56
Received QueryRetry: 1 AUDIO_INFO</title>
</head>
<body><h2>HTTP ERROR 500</h2>
<p>Problem accessing /NMDPAsrCmdServlet/dictation. Reason:
<pre>    x-nuance-sessionidd65178ba-8c70-49ee-bd22-ac1789c49a56
Received QueryRetry: 1 AUDIO_INFO</pre></p>
</body>
</html>

**Comment by gnogueira-daitan** [comment]
@usmanimtiaz did you fixed your issue? getting same response here.
