### ISSUE TITLE
Retry on ECONNRESET

### ISSUE THREAD

**Issue by yaronyg** [request/request#1300]
I'm working on a [PR](https://github.com/pouchdb/pouchdb/pull/3015) for PouchDB to enable PouchDB in node.js to make replication GET requests in parallel. But in testing this code under duress with a pool of 15 connections I inevitably run into a situation where one of the connections fails with a ECONNRESET. This then causes request.js to throw a failure and ends up causing all of PouchDB to quit.

At first I thought this was because I wasn't using the forever-agent (whose existence I knew nothing of and learned about by accident). Eventually I passed in 'forever : true' and confirmed that the forever-agent is being used. But that didn't fix things. I was still failing occasionally on ECONNRESET.

I did find [the code](https://github.com/request/request/blob/ce705147036b57e5b4c91d2f0ff7b48c7512b561/request.js#L960) that handles this error but it depends on _reusedSocket which is always undefined in my tests and so the test always fails.

Question 1 - should the _reusedSocket test be removed?

Question 2 - Even if the answer to question 1 is 'yes' it seems like the retry logic is more than a little fragile in these cases (there would be exactly one retry and no way to configure more). Is the intent that one is required to use something like [node-request-retry](https://github.com/FGRibreau/node-request-retry)?

Question 3 - Why does node-request-retry need to exist? Isn't this the sort of functionality that should be in request? Or is there some line in the sand that says these are separate issues? Sorry if this is a silly question but I'm new to all of this.

Thanks!

**Comment by aggied** [comment]
Bump here -- I am not using forever-agent, but it's not uncommon for me to get the ECONNRESET error when making lots of requests to the same host.

**Comment by aggied** [comment]
Update -- pulled in `node-request-retry` and it seems to be a great solution. If `request` decides to support this I think there is a use case there, but after a little bit of testing I think other solutions on top might do just fine as previously noted.

**Comment by nono** [comment]
@nylen FYI, curl has `--retry=<number>` and wget has `--tries=<number>`.

**Comment by TjlHope** [comment]
Apologies for the necro, but I've just stumbled on this issue myself in trying to add connection pooling to some legacy code (which uses a mix of `request` and `request-promise-native`), so I'm leaving this comment just in case it helps someone else.

Having dived into the internals more than I intended, I found that the existing `onResponseError` retry code is out of date, presumably written for `ForeverAgent` which is only used for node <=0.10 : https://github.com/request/request/blob/3c0cddc7c8eb60b470e9519da85896ed7ee0081e/request.js#L474

It seems like `http.ClientRequest._reusedSocket` has been exposed as the public field `reusedSocket` in later node versions: https://nodejs.org/docs/latest-v16.x/api/http.html#requestreusedsocket

I was able to get the pooled connection retry logic working by monkey-patching the `onResponseError` method:

```
  request.Request.prototype.onRequestError = function fixedOnRequestError(error) {
    var self = this
    if (self._aborted) {
      return
    }
    if (self.req && (self.req._reusedSocket || self.req.reusedSocket) &&
        error.code === 'ECONNRESET') {
      self.debug('ECONNRESET on reusedSocket, retrying', self.uri.href)
      if (self.agent.addRequestNoreuse) { // node <= 0.10 only
          self.agent = { addRequest: self.agent.addRequestNoreuse.bind(self.agent) }
      }
      if (!self.src) {    // i.e. we're not a stream dest
        self._started = false
        self.init()
        return
      }   // else we can't replay an already started stream, so fall through
    }
    self.clearTimeout()
    self.emit('error', error)
  }
```
