### ISSUE TITLE
how to replace default agent

### ISSUE THREAD

**Issue by anklos** [request/request#1319]
Say I want to use https://github.com/node-modules/agentkeepalive to replace default agent.

Shall I just do `http.globalAgent = myNewAgent`, so `request` module can pick it up when doing http requests? If not, how shall I set it?

Thanks a lot!

**Comment by benuts** [comment]
@Raynes I want to replace the default agent to go through the proxy I declared in ``request`` :
```
var proxy = request.defaults({'proxy':'http://login:pwd@proxy:port'});
```
I'm quite new using Node (and Node-Webkit in this case) is there a way to tell the app to only use this proxied settings for requests ? I mean even requests from the DOM like iframe, etc.

Sorry if it is a little off topic but I can't find any solutions..

Thanks
