### ISSUE TITLE
How to properly configurate pool

### ISSUE THREAD

**Issue by dg3feiko** [request/request#1324]
simply I tried with a snippet below in a ubuntu 14.04 box

``` js
setInterval(function(){
    request({
        url: "http://www.google.com",
        method: "GET"       
    },function(err, resp,body){
        if(err)
        {
            console.log(err);
        }else
        {
            console.log('sent');
        }
    })
},1000);
```

I observed that as time going, `TIME_WAIT` connections are growing until it ate up all socket resources.

I know that this is because of `http Agent` create sockets with`keep-alive` enabled. WIth `require({pool:false})`, which effectively set `agent = false` for underlying `http.request` can eliminate this problem.

But I want to take the benefit of connection pool while keep the amount of them under control. 

I tried with 3rd-party agents, e.g. `agentkeepalive` and `keep-alive-agent` with `request({agent: 3rd_party_agent})` which work with raw `http.request`, but no luck with `request`. I saw the amount of `TIME_WAIT` connection growing with such combination.

My question is that, how can I properly apply pool (agent) implementations to `Request` so that I can both limit my connections in a reasonable amount and enjoy the advantages of pools?

**Comment by aterreno** [comment]
Same here, I'd like to keep the connection alive to save time.. https://www.npmjs.com/package/keep-alive-agent

**Comment by ashelley** [comment]
Hello,  this is what i do maybe this will help (only tested on node 10.) aka 0.2 series of agentkeepalive
```
...
var	agentkeepalive = require('agentkeepalive'),
	HttpsAgent = agentkeepalive.HttpsAgent,
	agent = new HttpsAgent({keepAlive: true, keepAliveMsecs: 10000});
...
request(url, {agent: agent, headers: {"Connection":"Keep-Alive"}});
```

**Comment by aterreno** [comment]
thanks @ashelley

**Comment by nylen** [comment]
Custom pool and agent handling is one of the pieces of this library that I don't understand very well, we need tests and docs for it.  @mikeal thoughts?
