### ISSUE TITLE
Wrong encoding for basic authentication

### ISSUE THREAD

**Issue by sbrinkmann** [request/request#1334]
The _request_ module provides an option to authenticate requests via basic authentication. The method wich is applied to encode the user credentials is described in RFC2617 https://www.ietf.org/rfc/rfc2617.txt 

It states:

```
To receive authorization, the client sends the userid and password,
   separated by a single colon (":") character, within a base64 [7]
   encoded string in the credentials.

      basic-credentials = base64-user-pass
      base64-user-pass  = <base64 [4] encoding of user-pass,
```

But the RFC doesn't state the encoding which has to be applied before the strings get converted to base64. The _request_ module in it's current implementation uses _ASCII_ encoding (https://github.com/request/request/blob/master/lib/helpers.js#L77). This leads to wrong base64 encodings when it's getting towards string which are only defined in ISO-8859-1 or even UTF-8

The problem is discussed over here in detail, with the result that ISO-8859-1 instead of ASCII or UTF-8 should be used for the encoding
http://stackoverflow.com/questions/7242316/what-encoding-should-i-use-for-http-basic-authentication

**Comment by nylen** [comment]
Related to #1333 (its first commit, at least).

Thanks for the additional info @sbrinkmann.  According to http://stackoverflow.com/a/9056877/106302:

> Also relevant, no current browser does this. They use utf-8 (Chrome, Opera), iso-8859-1 (Safari), the system code page (IE) or something else (like only the most significant bit from utf-8 in the case of Firefox).

There's a JavaScript ISO-8859-1 encoder here:  https://github.com/mathiasbynens/windows-1252 (we'd want that one instead of `node-iconv` so people don't have to compile stuff to use `request`).  Thoughts on whether we should use it, or just use `utf8` encoding for now?

**Comment by simov** [comment]
I think `utf8` would do it for now.

**Comment by sbrinkmann** [comment]
@nylen first of all sorry for the inconvenience, I didn't knew that both commits where part of the merge request. I will create a separate branch for the merge request and I'll open it again.

The encoding problem is a real mess. You've found the right part which states quite clear that each browser does something different. But the real interesting question is how the Apache webserver decodes. Since this is the most commonly used web server, we have to use the same encoding. When this it is UTF-8 we can use the change which I've already prepared https://github.com/sbrinkmann/request/commit/291a9b42f9c601756a603bc53086b8de07a15eee

**Comment by simov** [comment]
I think it's better to set `utf8` explicitly, even though it might be the default value.

**Comment by sbrinkmann** [comment]
@simov Do you want to apply the fix with explicit encoding or shall I do it and open a merge request?

**Comment by simov** [comment]
@sbrinkmann just open up a new PR from the latest master and make the change, you can add a reference to this issue. Other than that I really can't think of any tests for that line of code.

**Comment by nylen** [comment]
it still needs to be tested, but that can be as simple as putting a euro sign in a password and adding it to [`tests/test-basic-auth.js`](https://github.com/request/request/blob/master/tests/test-basic-auth.js).
