### ISSUE TITLE
process.env.no_proxy is ignored / not working correctly

### ISSUE THREAD

**Issue by murphyj** [request/request#1347]
I'm unfortunate enough to have to work behind a corporate proxy. Mostly it works but I have issues when working on `localhost` or `127.0.0.1` or basically anything where I need to ignore the proxy for development purposes - otherwise proxy will map my http requests to corporate urls.

I set as required all the following env variables:

`HTTPS_PROXY`, `HTTP_PROXY`, `NO_PROXY`, `https_proxy`, `http_proxy` and `no_proxy`.

However, when making calls using the `request` library it doesn't work.

We instantiate the request library using our own wrapper library that does the following:

```
var defaultOptions = _getDefaultOptions();
this.request = request.defaults(defaultOptions);
```
Where `_getDefaultOptions()` is as follows:
```
function _getDefaultOptions() {
    var options = {};

    _checkProxies(options);
    _checkCertificates(
        ['/etc/pki/certificate.pem'],
        options
    );

    if (!options.cert) {
        var defaultClientCertificatePair = {
            certLocation: '/etc/pki/tls/certs/client.crt',
            keyLocation: '/etc/pki/tls/private/client.key'
        };
        _checkCertificateKeyPair([defaultClientCertificatePair], options);
    }

    options.rejectUnauthorized = false;

    return options;
}
```

Further debugging revealed that the issue is because the method `getProxyFromUri` is never entered (https://github.com/request/request/blob/master/request.js#L170)

This is because the block (https://github.com/request/request/blob/master/request.js#L427) 
```
if(!self.hasOwnProperty('proxy')) {
   self.proxy = getProxyFromURI(self.uri)
}
```

To invoke the above method is never entered is set. I'm just wondering why self.hasOwnProperty('proxy') needs to be false for it to `getProxyFromURI`. Are we instantiating the client incorrectly or is there a bug here?

**Comment by nylen** [comment]
You didn't post the code for your `_checkProxies` function, but I suspect it is setting `options.proxy`.  This line in [the proxy documentation](https://github.com/request/request#controlling-proxy-behaviour-using-environment-variables) is key:

> When `HTTP_PROXY` / `http_proxy` are set, they will be used to proxy non-SSL requests that do not have an explicit `proxy` configuration option present.

Meaning that if the `proxy` option is specified then environment variables will be ignored.

**Comment by nylen** [comment]
Related discussion at #1096, #1195.  Closing, feel free to reopen if this doesn't address your issue.
