### ISSUE TITLE
Custom FormData instance

### ISSUE THREAD

**Issue by arcanis** [request/request#1348]
How can I feed my own FormData instance?

If it's not yet possible, I think that `formData : new FormData()` should work (it doesn't for now). Passing the FormData instance as parameter of the `.form([form])` api call send it urlencoded.

**Comment by simov** [comment]
What do you mean by _custom_ FormData instance? Is the [multipart/form-data](https://github.com/request/request#multipartform-data-multipart-form-uploads) documentation of any help?

**Comment by arcanis** [comment]
Not really; I'd like to create myself the FormData instance. For example:

```js
var formData = new FormData( );
formData.append( 'foo', new Buffer( [ ] ), { filename : 'foo.bin' } );

request( { formData : formData, ... } );
```

**Comment by simov** [comment]
What's the difference between your example and this one:

```js
var formData = {
  foo: {
    value: new Buffer( [ ] ),
    options: { filename : 'foo.bin' }
  }
}

request( { formData : formData } );
```

**Comment by arcanis** [comment]
I haven't seen that it was possible to specify the filename using an option object - it solves my use case.

However, from a API point of view, I still think it would be better to be able to pass a custom FormData instance, if possible : it doesn't really make sense that the formData instance doesn't actually support FormData.

Anyway, this issue can be closed as far as I'm concerned. Thanks!

**Comment by simov** [comment]
From an API point of view we wanted to be able to pass FormData options directly to request, without knowing the internal details of the implementation.

The FormData module is just an implementation detail that eventually may change in future, where the input options format is what the request's formData implementation expects.

I'm glad it works for you @arcanis . I'm closing this.
