### ISSUE TITLE
Promises

### ISSUE THREAD

**Issue by franleplant** [request/request#1359]
Why does this package does not use the Promise API?

**Comment by simov** [comment]
@franleplant you can try this package https://www.npmjs.com/package/request-promise I think most of the people that want promises are happy with that.

As for why exactly request doesn't use promises by default, you can find out some info about it in the issue tracker I think.

**Comment by nylen** [comment]
1. There isn't one standard "Promise API".  Node.js is standardized on callbacks, and libraries like `bluebird` wrap callback-based APIs.
2. This would conflict with `request`'s streaming features.

For prior discussion see #796, #910.

**Comment by franleplant** [comment]
@simov thanks!

@nylen `.then(...)` is in all Promise implementations.

**Comment by topaxi** [comment]
Promises are actually an ECMAScript standard, supporting them would be nice.
Most, if not all, Promise implementations follow the standard, I don't see the issue here :)
To not interfere with the old api, one could implement an method which returns the promise.

```request('http://example.com').promise() instanceof Promise```
