### ISSUE TITLE
when I access local web server, why it very slowly (macBook air)

### ISSUE THREAD

**Issue by sundq** [request/request#1363]
when I access local web server(node js implement ) through 127.0.0.1, it very fast, but when I bind 127.0.0.1 with www.zw.lcoal in /etc/hosts, then access web server through www.zw.local, it very slowly.

**Comment by nylen** [comment]
This looks like a DNS issue.  Try these commands:

```sh
curl -v www.zw.local
host www.zw.local
dig www.zw.local
```

I'm closing this since it's not a request issue, but if someone with more time than me wants to help troubleshoot then that's fine.

**Comment by sundq** [comment]
But when I access server through brower, why it very fast.
