### ISSUE TITLE
The page is chaos crawling from the remote server

### ISSUE THREAD

**Issue by Birdflying1005** [request/request#1364]
I am using this module to crawl html pages from a server.

I encounter an issue, the issue is as below:

1. I am using the Async module to crawl these thousands of pages.
2. Thousands of pages, but one page A.html is more bigger (  almost 5 MB) than others.  When I finished crawling task, I find the issue.  A.html 's name is A, but the content is B.  Some of page's name is not A.html, but the content is A.html.
3. If I did not crawl this page, there is no this problem.

Code is here:
-----------------------------------------------------------------

    
    this.requestPMRsByURLs = function(pmrUrls, cookieJar) {
    	console.log("Being to extract the PMR information, pmrUrls.length=" + pmrUrls.length);
		async.each(pmrUrls, function(pmrUrl, callback) {
    		_self.requestPMRInfo(pmrUrl, cookieJar);
    		callback();
    	}, function(err) {
            if(err) {
                console.error(err);
            }
        });
    };
    
    this.requestPMRInfo = function(pmrUrl, cookieJar) {
    	
    	(function(url, jar) {
    		 var localRepsPath = config.pmrRepository;
         	request.get({url : url, encoding: null, jar : jar}, function(err, res, body) {
                 if(err) {
                 	console.trace();
                 	return console.error("Error2:" + "\nURL=" + url + "\nReason:" + err);
                 } else {
                     // parse the body for the information
                	 var data = iconv.decode(body, 'ISO-8859-1');
                	 var htmlstr = data.toString();
                	 var pmrInfo = PMRAnalyzer.analyzeHTML(url, htmlstr);
                     pmrProxy.save(pmrInfo);
                     var fileName  = localRepsPath + path.sep + pmrInfo.pmrNumber + ".html";
                     fs.exists(fileName, function(exists) {
                  	   if( (!exists) || (exists && config.redownloadPMRHtml)) {
                             fs.writeFile(fileName, htmlstr, function(error){
                                 if(error){
                                     console.log(error);
                                 }
                             });
                  	   }
                     });
                 }
             });
        } (pmrUrl,cookieJar));
    };
};

**Comment by simov** [comment]
```js
async.each(pmrUrls, function(pmrUrl, callback) {
        _self.requestPMRInfo(pmrUrl, cookieJar, callback());
    }, function(err) {
        if(err) {
            console.error(err);
        }
    });
```

```js
this.requestPMRInfo = function(pmrUrl, cookieJar, callback) {
```

Then after your last async operation, somewhere after `fs.exists` you should call that `callback`

Not related to request in any way, closing.
