### ISSUE TITLE
URI Malformed

### ISSUE THREAD

**Issue by OKNoah** [request/request#1365]
When I do this, I get the exception "URL Malformed". The response is 200 and there's no error, though.

	  request( "http://news.bbcimg.co.uk/media/images/80408000/jpg/_80408441_022059218.jpg", function ( err, response, body ) {
	  // some code
	  })

It _seems_ to only affect images.

**Comment by nylen** [comment]
Cannot reproduce this:

```js
var request = require('request');

request('http://news.bbcimg.co.uk/media/images/80408000/jpg/_80408441_022059218.jpg', function(err, res, body) {
    console.log(err, res && res.statusCode, body && body.length);
});
```

prints `null 200 14321`.

Can you confirm?

**Comment by OKNoah** [comment]
Actually, this looks like it was an error with something else.

This, if interested: https://github.com/pvorb/node-md5/issues/13
