### ISSUE TITLE
Proxy settings with "\" not supported on Mac OSX

### ISSUE THREAD

**Issue by KempfCreative** [request/request#1377]
I have worked with npm on Windows at my office and there was never any issues with setting my corporate proxy. This proxy has a domain, which must be resolved like this: `http://domain\password:username@proxy.address.com:9999`

In Windows, the proxy works when I escape the "\" as "%5C" like so: `http://domain%5Cpassword:username@proxy.address.com:9999`, but on OSX, that will not resolve the proxy properly.
When I try to npm install, I get the following error: `npm ERR! network getaddrinfo ENOTFOUND proxy.address.com`

I have tried various ways of encoding the "\" on OSX, but none of them work, and Googling this problem leads me to a bunch of dead ends, and all the normal encoding methods are not working.

The NPM team recommended I open a ticket here, as `request` is used to make this connection. You can see the NPM ticket here: [Proxy Settings with "\" not supported on Mac OSX - Issue 7150](https://github.com/npm/npm/issues/7150).

If this is NTLM login, is that functionality planning on being added in `request`, or is this a bug in the current implementation?

**Comment by simov** [comment]
Just because you mentioned NTLM, could that be of any help https://www.npmjs.com/package/request-ntlm ?

**Comment by KempfCreative** [comment]
@simov Becuase the `npm install` command itself is where this issue presents, it cannot be a package based solution.

**Comment by simov** [comment]
Got it, I assume they use the `proxy` option of request, if that's the case you lose the `\` character after a call to `url.parse` which in turn might be platform specific? That would explain why it works on Windows.

**Comment by KempfCreative** [comment]
Exactly. Windows parses automatically to %5C, and that works for Windows. Mac just changes it to a forward slash or uses it as an escape character.

**Comment by simov** [comment]
@KempfCreative I just tried with your `.npmrc` settings

```bash
https-proxy=http://domain%5Cpassword:username@proxy.address.com:9999
proxy=http://domain%5Cpassword:username@proxy.address.com:9999 registry=http://registry.npmjs.org strict-ssl=false
```

I'm getting identical results on both Linux and Windows, can't say for OSX but I guess it should work much like the Linux version.

```diff

self.proxy
http://domain%5Cpassword:username@proxy.address.com:9999/

tunnelOptions
{ proxy:
   { host: 'proxy.address.com',
     port: 9999,
     proxyAuth: 'domain\\password:username',
     headers:
      { 'accept-encoding': 'gzip',
        accept: 'application/json',
        referer: 'install deep-copy',
-        'user-agent': 'npm/2.4.1 node/v0.10.30 win32 ia32',
+        'user-agent': 'npm/2.4.1 node/v0.10.30 linux x64',
        host: 'registry.npmjs.org:443' } },
  rejectUnauthorized: undefined,
  headers:
   { 'accept-encoding': 'gzip',
     version: '2.4.1',
     accept: 'application/json',
     referer: 'install deep-copy',
     'npm-session': 'a9921e40ab41bd82',
-     'user-agent': 'npm/2.4.1 node/v0.10.30 win32 ia32',
+      'user-agent': 'npm/2.4.1 node/v0.10.30 linux x64',
     'if-none-match': '"5J608ALIS9925CKMIHNTISPJ0"' },
  ca: null,
  cert: null,
  key: null }

self.proxy
{ protocol: 'http:',
  slashes: true,
  auth: 'domain\\password:username',
  host: 'proxy.address.com:9999',
  port: '9999',
  hostname: 'proxy.address.com',
  hash: null,
  search: null,
  query: null,
  pathname: '/',
  path: '/',
  href: 'http://domain%5Cpassword:username@proxy.address.com:9999/' }

```

Is that your exact `.npmrc` configuration that works on Windows?

**Comment by nylen** [comment]
Are you sure that your OS X error `npm ERR! network getaddrinfo ENOTFOUND proxy.address.com` is actually related to the backslash?  Try a proxy username/password with no backslash and see if you get the same error.

**Comment by KempfCreative** [comment]
@simov Yes, that is almost the exact same configuration that works on windows. I didn't pass `strict-ssl` into config, which is the only difference.

@nylen That will take me a few days to validate, as I will have to check with corporate security to see if there is a non-domain based proxy that I can use.

**Comment by nylen** [comment]
I meant just try it with the existing proxy.  It will fail, but I think it's really odd that you're getting a DNS error.  If you still get the DNS error, that will tell us there's another issue on OS X other than the backslash.

Another thing that would be helpful is to start `npm` like `NODE_DEBUG=request,tunnel npm install`.  If that doesn't tell us what we need to know, then the next step beyond that is to edit the `npm` code to include `require('request-debug')(request)` at the appropriate spot.

**Comment by KempfCreative** [comment]
@nylen I tried both attempts, here is what happens:
1. Used the wrong proxy, without a domain, got the same error:
```
MyComputer:folder username$ npm install
npm ERR! network getaddrinfo ENOTFOUND
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network 
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! System Darwin 13.1.0
npm ERR! command "node" "/usr/local/bin/npm" "install"
npm ERR! cwd /Path/to/my/local/workspace
npm ERR! node -v v0.10.35
npm ERR! npm -v 1.4.28
npm ERR! syscall getaddrinfo
npm ERR! code ENOTFOUND
npm ERR! errno ENOTFOUND
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Path/to/my/local/workspace/logfile.log
npm ERR! not ok code 0
```
2. I tried with the `NODE_DEBUG=request,tunnel npm install`
```
MyComputer:folder username$ NODE_DEBUG=request,tunnel npm install
REQUEST { proxy: 'http://username:PassWord@proxy.address.com:port/',
  headers: 
   { 'npm-session': 'd0592a8478500b14',
     version: '1.4.28',
     referer: 'install',
     accept: 'application/json',
     'accept-encoding': 'gzip',
     'user-agent': 'npm/1.4.28 node/v0.10.35 darwin x64' },
  strictSSL: false,
  key: null,
  cert: null,
  localAddress: undefined,
  ca: null,
  encoding: null,
  method: 'GET',
  url: 
   { protocol: 'http:',
     slashes: true,
     auth: null,
     host: 'registry.npmjs.org',
     port: null,
     hostname: 'registry.npmjs.org',
     hash: null,
     search: null,
     query: null,
     pathname: '/grunt',
     path: '/grunt',
     href: 'http://registry.npmjs.org/grunt' },
  callback: [Function],
  uri: undefined,
  tunnel: false }
REQUEST make request http://registry.npmjs.org/grunt
REQUEST { proxy: 'http://username:PassWord@proxy.address.com:port/',
  headers: 
   { 'npm-session': 'd0592a8478500b14',
     version: '1.4.28',
     referer: 'install',
     accept: 'application/json',
     'accept-encoding': 'gzip',
     'user-agent': 'npm/1.4.28 node/v0.10.35 darwin x64' },
  strictSSL: false,
  key: null,
  cert: null,
  localAddress: undefined,
  ca: null,
  encoding: null,
  method: 'GET',
  url: 
   { protocol: 'http:',
     slashes: true,
     auth: null,
     host: 'registry.npmjs.org',
     port: null,
     hostname: 'registry.npmjs.org',
     hash: null,
     search: null,
     query: null,
     pathname: '/grunt-contrib-copy',
     path: '/grunt-contrib-copy',
     href: 'http://registry.npmjs.org/grunt-contrib-copy' },
  callback: [Function],
  uri: undefined,
  tunnel: false }
. . .
REQUEST make request http://registry.npmjs.org/grunt-bless
REQUEST make request http://registry.npmjs.org/grunt-contrib-mincss
REQUEST make request http://registry.npmjs.org/grunt-contrib-sass
REQUEST make request http://registry.npmjs.org/grunt-contrib-cssmin
REQUEST make request http://registry.npmjs.org/grunt-recess
REQUEST make request http://registry.npmjs.org/grunt-regex-replace
npm ERR! network getaddrinfo ENOTFOUND
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network 
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'
npm ERR! System Darwin 13.1.0
npm ERR! command "node" "/usr/local/bin/npm" "install"
npm ERR! cwd /Path/to/my/local/workspace
npm ERR! node -v v0.10.35
npm ERR! npm -v 1.4.28
npm ERR! syscall getaddrinfo
npm ERR! code ENOTFOUND
npm ERR! errno ENOTFOUND
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Path/to/my/local/workspace/logfile.log
npm ERR! not ok code 0
```
 Seems like the issue is still there.

Let me know what else I can do to diagnose this issue.

Thanks!

**Comment by nylen** [comment]
You used a proxy username with no backslash and got the same error, correct?  So that means the backslash is not causing the problem.

Can you ping/resolve the proxy?  Try these commands (not sure if all of these are available on OS X):

```sh
ping proxy.address.com
host proxy.address.com
dig proxy.address.com
```

**Comment by KempfCreative** [comment]
@nylen I have used all three of the commands as above with my actual proxy address. Here is the responses, but with the actual proxy address changed:
``ping proxy.address.com``:
``ping: cannot resolve proxy.address.com: Unknown host``

``host proxy.address.com``
``Host proxy.address.com not found: 3(NXDOMAIN)``

``dig proxy.address.com``
```
; <<>> DiG 9.8.3-P1 <<>> proxy.address.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 8790
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 0

;; QUESTION SECTION:
;proxy.address.com	IN A

;; AUTHORITY SECTION:
.			900	IN	SOA	a.root-servers.net. nstld.verisign-grs.com. 2015020201 1800 900 604800 86400

;; Query time: 23 msec
;; SERVER: 10.170.60.70#53(10.170.60.70)
;; WHEN: Mon Feb  2 16:23:25 2015
;; MSG SIZE  rcvd: 154

COMPUTER:folder $ dig proxy.address.com

; <<>> DiG 9.8.3-P1 <<>> proxy.address.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 38408
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 0

;; QUESTION SECTION:
;proxy.address.com. IN A

;; AUTHORITY SECTION:
.			710	IN	SOA	a.root-servers.net. nstld.verisign-grs.com. 2015020201 1800 900 604800 86400

;; Query time: 11 msec
;; SERVER: 10.170.60.70#53(10.170.60.70)
;; WHEN: Mon Feb  2 16:24:18 2015
;; MSG SIZE  rcvd: 157
```

**Comment by nylen** [comment]
Your computer can't resolve the proxy address at all, it looks like you may have incorrect DNS settings but this is an issue that you need to take up with your IT department.
