### ISSUE TITLE
Refactor OAuth into separate module

### ISSUE THREAD

**Issue by nylen** [request/request#1379]
See #1366

**Comment by simov** [comment]
OK, I'm closing it so that I can claim the bounty ..

**Comment by nylen** [comment]
hold off on that, we're still having issues with Bountysource...

**Comment by simov** [comment]
Oh well, np

**Comment by nylen** [comment]
Still don't have access to pay out bounties :( ping @mikeal

**Comment by nylen** [comment]
@simov bounty is set, let me know if you're able to log in on Bountysource and claim it.

**Comment by simov** [comment]
There is no claiming option in this case, in the email I received they say:

> The bounty will be awarded to the developer who successfully closes out this issue.

So I'm closing it.

**Comment by simov** [comment]
OK, I actually claimed it, no idea if that was needed, but just in case :)

**Comment by simov** [comment]
@nylen :beers:
