### ISSUE TITLE
Save array of a json object?

### ISSUE THREAD

**Issue by SmashKazu** [request/request#1384]
Hey guys,

I'm currently working on a Twitch IRC Bot where users can earn points for being in the chat.
But I don't know how I can get the "viewers" out of https://tmi.twitch.tv/group/user/kazutode/chatters
and save them, so they will be insert into the database.

Would someone help me?
I never worked with json before.

**Comment by nylen** [comment]
In JavaScript you use [`JSON.parse`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/parse) to turn a JSON string into an object that you manipulate as normal.

`request` can do this for you if you use the `json` option:

```js
request({
  url  : 'https://tmi.twitch.tv/group/user/kazutode/chatters',
  json : true
}, function(err, res, body) {
  // check err, res.statusCode
  // insert body.viewers into db
})
```
