### ISSUE TITLE
It seems a bug for a url which is consist of utf8 strings

### ISSUE THREAD

**Issue by mike442144** [request/request#1385]
When I use node-crawler to fetch page of urls, I find the request module got different page from which of the browser did. So I try to use `request` module to see if it's root issue, but I ran into this in request module too. Below is the case:

`http://www.yichemall.com/car/detail/c_112938_2015款 2.5HQ E-CVT 旗舰版/`

if I use browser to visit this page, I'll get correct result, but server said error if I do with `request` module. I think it is `encoding` things because `utf8` strings in url. 

Anyone happened to this and anyone helps? 
Thanks first.

**Comment by mike442144** [comment]
BTW, I can get correct result just use `http.request` in nodejs, and I read some code in request.js but I cannot find any problems since `request` use url.parse and url.format and then pass to httpModule.request directly, that's the same as using http.request. I'm confused.

**Comment by simov** [comment]
This works:
```js
request.get('http://www.yichemall.com/car/detail/c_112938_2015款 2.5HQ E-CVT 旗舰版/', function (err, res, body) {
  if (err) console.log(err)
  console.log(body)
})
```
If you have any other problems, paste your exact request configuration here.

**Comment by mike442144** [comment]
@simov Thanks for your msg. But it does not work because I have checked the response message, last request has been redirected to 

`/Home/Error?aspxerrorpath=/car/detail/c_112938_2015%e5%a8%86?2.5HQ%20E-CVT%20%e9%8f%83%e6%a5%84%e5%9f%8c%e9%90%97?`

but use `http.request` won't

**Comment by simov** [comment]
Ok just paste your request configuration, as I already mentioned above.

**Comment by mike442144** [comment]
@simov 
`request("http://www.yichemall.com/car/detail/c_112938_2015款 2.5HQ E-CVT 旗舰版/",function(error,response,body){
    console.log(body);
    console.log();
    console.log(response);
});`

That's all, Thanks.

**Comment by simov** [comment]
What exactly is your goal, do you want to be redirected to that page or not. Request redirects by default, pass `followRedirect:false` to the request options object if you don't want the redirect enabled.

**Comment by mike442144** [comment]
@simov Thanks, what I need is quite simple, just the browser display is what I want , but in request, it redirect to error page which is not the same page with browser shows.

**Comment by simov** [comment]
There are probably some parameters that needs to be sent with your request. You should inspect that request in your browser's developer tools.

At least you can try to store the cookies during that redirect.

```js
request.get('http://www.yichemall.com/car/detail/c_112938_2015款 2.5HQ E-CVT 旗舰版/', {
  jar: request.jar()
},function (err, res, body) {
  if (err) console.log(err)
  console.log(body)
})
```

**Comment by mike442144** [comment]
@simov I've tried to do that, but nothing change. I'm wondering if there is way to print the url string before sending request.

**Comment by simov** [comment]
Of course you can use https://github.com/request/request-debug for that.

**Comment by nylen** [comment]
You say it works with `http.request` so post that code too.  Whenever you report a bug, code snippets (self-contained, with everything we need to execute them) are the most helpful thing you can provide.

**Comment by mike442144** [comment]
@nylen 
`https://github.com/mike442144/spider/blob/master/src/auto/yichemall.js`
Thanks. In this file line No.218, call the file `https://github.com/mike442144/spider/blob/master/helpers/webhelper.js` of request_data, that just call http.request in line 185

**Comment by nylen** [comment]
post a **standalone** / **self-contained** example that we can run, please (this should be <10 lines of code with a call to `http.request` that has everything we need to paste it in and run it)

**Comment by mike442144** [comment]
@nylen @simov I find the key point, I should encode `url` before request. Thanks you guys for attention.
