### ISSUE TITLE
Ability to switch on wire logs

### ISSUE THREAD

**Issue by guy-mograbi-at-gigaspaces** [request/request#1391]
Hi, 

not sure if you already have it or not, but it would be great if i could get a trace print of every request/response communication made by request. 

currently i simply wrap your api and the callback from the parameters and delegate.

**Comment by nylen** [comment]
[Use `request-debug`](https://github.com/request/request#debugging) :)

**Comment by rlidwka** [comment]
I wrote [this](https://github.com/rlidwka/expose_curl) module, which might help you as well.

**Comment by guy-mograbi-at-gigaspaces** [comment]
Thanks! didn't see that
