### ISSUE TITLE
Where is an IP in headers?

### ISSUE THREAD

**Issue by denisx** [request/request#1393]

**Comment by froatsnook** [comment]
```javascript
var request = require("request");

request("http://example.com", function(err, res) {
    console.log(res.connection.remoteAddress);
});
```

**Comment by denisx** [comment]
try to load http://www.gazprom.ru/ and get empty result of res.connection.remoteAddress :(

**Comment by froatsnook** [comment]
If the connection has already been closed, then the connection is destroyed (`res.connection.destroyed` is `true`).  In your example, I get the IP when I check it during the "response" event.  But I'm not sure how fool-proof this is.

```javascript
var request = require("request");

request("http://gazprom.ru", function(err, res, body) {
}).on("response", function(response) {
    console.log(response.connection.remoteAddress);
});
```

**Comment by denisx** [comment]
Tnx!

**Comment by nylen** [comment]
+1 to using the `response` event, thanks @froatsnook.
