### ISSUE TITLE
content is empty while a file putting to a website

### ISSUE THREAD

**Issue by tsingphone** [request/request#1394]
The following scripts can be well done:
	1)request.get(strUrl1).pipe(request.put(strUrl2))
	2)fs.createReadStream(oldFileName).pipe(fs.createWriteStream(newFileName))
But, the following script,
	fs.createReadStream(fileName).pipe(request.put(strUrl))
, which creates an empty file on the web.

**Comment by nylen** [comment]
It does send the file body, it just doesn't set a `content-length` header.

It may be possible to set it automatically for streams where the length is already known, but for now, try this:

```js
var r = request.put(strUrl)
fs.createReadStream(fileName).pipe(r)
r.setHeader('content-length', fs.statSync(fileName).size)
```

Also, use backticks to format code on GitHub:


    `code here`
    or
    ```js
    code here
    ```
