### ISSUE TITLE
JSON POST body URI encoded (RFC3986)

### ISSUE THREAD

**Issue by chacal** [request/request#1395]
Due to pull request [#1315](https://github.com/request/request/pull/1315) all POSTed JSON content is  URI encoded in 2.52.1.

Is there some way to avoid this? The server I'm POSTing to does not expect JSON data to be encoded, but instead sent as is.

Anyhow, is it OK to encode JSON content at all as the format itself allows the usage of e.g. '!' and '*' without any encoding? `{"key": "value !"}` is a very different JSON than `{"key": "value %21"}`

**Comment by nylen** [comment]
Thanks for reporting, I agree that we should not pass JSON POST bodies through `rfc3986`.  @simov want to take a look so we can release a fixed version quickly?

**Comment by simov** [comment]
That was the reason I proposed this change as an option (first commit). If Twitter allows json post bodies (not sure) then there it should be rfc3986 encoded. So what's the expected behavior exactly?

**Comment by nylen** [comment]
Encoding regular `application/x-www-form-urlencoded` POST bodies is transparent: if we encode too much, the server will decode it.

I didn't think about this until now, but encoding JSON in this way is **not** transparent.  I'd be surprised if there were any servers that will decode JSON in this way.

Propose deleting [this line](https://github.com/request/request/blob/v2.52.0/request.js#L1432), let me know what you think.

**Comment by simov** [comment]
OK, I'll take a look, and submit PR (the tests should be changed a bit)

**Comment by chacal** [comment]
Shouldn't the encoding be removed also on line 1439? There we are setting JSON request body as well, I believe.

**Comment by simov** [comment]
I'm just looking at it :)

**Comment by nylen** [comment]
Version `2.53.0` is on npm with this fix.

**Comment by chacal** [comment]
Thanks for the very fast response on this! Version 2.53.0 works like a charm! :)

**Comment by nylen** [comment]
glad to hear it, that was a nasty bug :sweat:

**Comment by crobinson42** [comment]
Hey @chacal @nylen I'm running into this using `request` to post to github using the github api. It's encoding my JSON and I can't seem to understand a way around it. Any help?

I send this `{ "title": "Test Bug Title..Kaboom"}` and github receives this `{ "title": "Test Bug Title..Kaboom%21" }`

```
request
				.post({
					url: "https://api.github.com/repos/crobinson42/therms-public/issues",
					form: JSON.stringify(githubIssueObj),
					headers: {
						'User-Agent': 'App Auto Bug Filing',
						'Authorization': 'Basic yaDaYadA...YadaYada',
						'Content-type': 'application/json; charset=utf-8'
					}
				},...
```

Using `v2.74.0`

Thanks!

**Comment by simov** [comment]
@crobinson42 you are not supposed to send URL encoded JSON. If you really do need to send JSON then use the `json` option instead. For URL encoded body pass a regular object to the `form` option (without `JSON.stringify`).

**Comment by crobinson42** [comment]
@simov Ahh, THANK you for pointing that out! I added the option flag `json:true` and moved my JSON to the `body: myJSON` instead of `form: myJSON` and that did the trick.

```
request.post({
  url: "my url...",
  json: true,
  body: myJSON
});
```
