### ISSUE TITLE
Publish v2.53.1 to NPM

### ISSUE THREAD

**Issue by droppedoncaprica** [request/request#1398]
The current version published on npm is `2.53.0`, which is semi-broken (it breaks talking to one of our REST API's).

Any chance we could get the latest version pushed out to NPM?

@nylen @mikeal @FredKSchott

**Comment by droppedoncaprica** [comment]
Actually, weird.  Looks like there isn't any changes between the two other than a changelog file.  INTERESTING.

Sorry guys!

**Comment by FredKSchott** [comment]
No worries, this comes up a lot (I had the same question at one point) 
See: https://github.com/request/oauth-sign/issues/10#issuecomment-58917018

**Comment by simov** [comment]
@droppedoncaprica it was a hot fix :fire: good you have tests for that :+1:

**Comment by droppedoncaprica** [comment]
@FredKSchott Sweet, thanks for the clarification!  

When I'd looked at the version numbers, I'd assumed 2.52.1 was the version that had included the encoding fix without looking at the commit logs.  Thanks again!
