### ISSUE TITLE
supplying both a URI object and QS object can cause unexpected behaviour

### ISSUE THREAD

**Issue by sandfox** [request/request#1399]
This might be more of a thing to document than a bug but anyway.

I "hand built" an object like the one produced by `url.parse` and supplied that as the `uri` | `url` argument along with an object for `qs` to the `request()` function and watched most of the objects settings get nulled out...

```js
var myHandBuiltUriObject = { 
  protocol: 'http:',
  slashes: null,
  auth: null,
  hash: null,
  search: null,
  query: null,
  pathname: '/timers/test-zz',
  path: '/timers/test-zz',
  href: '/timers/test-zz',
  hostname: '::ffff:127.0.0.1',
  port: 8899 }

var requestOpts = {
  uri: myHandBuiltUriObject,
  qs: {page:10},
  method: 'GET'
}

request(requestOpts);

// Error: Invalid protocol: null
//    at Request.init (/Users/sandfox/code/tmp/node_modules/biws/node_modules/request/request.js:594:31)
//    at new Request (/Users/sandfox/code/tmp/node_modules/biws/node_modules/request/request.js:264:8)
//    at request (/Users/sandfox/code/tmp/node_modules/biws/node_modules/request/index.js:50:10)

var myUriObjectAfterBeingMangledByRequestInternally = { 
  protocol: null,
  slashes: null,
  auth: null,
  host: null,
  port: null,
  hostname: null,
  hash: null,
  search: '?state=on',
  query: 'state=on',
  pathname: '/timers/test-zz',
  path: '/timers/test-zz?state=on',
  href: '/timers/test-zz?state=on' }

```

After some digging around inside request it appears that if you supply both the URI object and the QS object, request will use just the `uri.href` key and ignore all the `host`, `port`, `protocol` etc when bodging on the querystring and making a new uri.

```
 self.uri = url.parse(self.uri.href.split('?')[0] + '?' + rfc3986(qs))
 self.url = self.uri
 self.path = self.uri.path
```
https://github.com/request/request/blob/f0acc0b3e0bbc8a57d3418ab93eadbf162089514/request.js#L1328

I'm not really sure quite what the solution to this or what I really expect to happen but at the least I suppose that document how `request` uses the `uri` object might be useful?

If anyone is wondering why I have a hand constructed uri object, it's because I have one library that wraps request and does a form of load balancing by supplying the port/hostname/protocol for each http request made.

**Comment by simov** [comment]
I personally think that's a bug in request in case we allow parsed object for the uri option. We should assign only the properties of the parsed object that we expect to change in `qs` (the last 5 I guess). Probably there is no test for that case, so the first thing would be to add one.

**Comment by simov** [comment]
@sandfox the easiest way to get around this is to pass the port as part of the `uri` string like this

```js
request({uri:'http://dummy.com:8899/timers/test-zz', qs:{page:10}})
```
Which effectively means that you'll have the whole data in the `self.uri.href` key

```js
url.parse('http://dummy.com:8899/timers/test-zz')
{ protocol: 'http:',
  slashes: true,
  auth: null,
  host: 'dummy.com:8899',
  port: '8899',
  hostname: 'dummy.com',
  hash: null,
  search: null,
  query: null,
  pathname: '/timers/test-zz',
  path: '/timers/test-zz',
  href: 'http://dummy.com:8899/timers/test-zz' }
```

Actually you are not building your parsed url object correctly, that's why it's never a good idea to make such things by hand.

**Comment by sandfox** [comment]
@simov I agree, (with hindsight) this is easily avoided by running my object through `url.format` to make the string. I just wanted to avoid `url.parse`-ing and `url.format`-ing something a lots of times for a single http request, and building urls via string concatenation is ugly/error prone.

I still think this quite an opportunity to footgun oneself and the cause for this lies somewhere in the mix of the ugly object `url.parse` makes and how it then ends up being used. I suppose that ideally the object from `url.parse` should be treated as being mostly an opaque value.

I don't know what a good resolution to this is, apart from maybe just having this issue as warning to others incase they come across. (maybe something should go into node/iojs's docs but thats outside the scope of `request`)

**Comment by simov** [comment]
I don't think `url.parse/stringify` is that heavy operation, unless you have tests to prove it :)

I'm leaving this issue open for now, in cause anyone else wants to add something.

**Comment by nylen** [comment]
> Actually you are not building your parsed url object correctly, that's why it's never a good idea to make such things by hand.

This is the key point here: `url.parse` always puts the entire URL in the `href` property.

We say `url` is a "fully qualified uri **or a parsed url object from `url.parse()`**" in the docs, which implies that if you're going to build a URL object you need to do it the same way as `url.parse`.  I think that's good enough.

> footgun oneself

:laughing:

**Comment by sandfox** [comment]
yeah, thats cool. Thanks for your time :-)
