### ISSUE TITLE
Cookies from domain aren't being sent to subdomain

### ISSUE THREAD

**Issue by MadaraUchiha** [request/request#1405]
I wrote a piece of code that uses cookies and multiple requests for authentication purposes, the requests span over two domains, example.com and subdomain.example.com.

I noticed that cookies from example.com aren't available on subdomain.example.com.

That behavior is, if I read it correctly, against HTTP specs which specifies that if no domain was set, the cookie should be available to this domain and every subdomain under it.

**Comment by benperez** [comment]
I have been banging my head against the wall all day on this one but there is actually an option hidden down in tough-cookie called `hostOnly` that you're going to want to explicitly set to false to get the [expected behavior](https://github.com/goinstant/tough-cookie/blob/c66bebadd634f4ff5d8a06519f9e0e4744986ab8/lib/cookie.js#L970-L978). I can't quite piece together why it's not currently the [default behavior](https://github.com/goinstant/tough-cookie/blob/c66bebadd634f4ff5d8a06519f9e0e4744986ab8/lib/cookie.js#L857-L870)

**Comment by MadaraUchiha** [comment]
@benperez That's an option you set on a specific cookie? How does that come in play with request? Just iterate the cookies in the cookie jar and set `hostOnly = false on each of them?

**Comment by lalitkapoor** [comment]
I think we might need to consider exposing the tough-cookie options. I'll look more into what's a sensible default for hostOnly. It should be what most browsers do I believe.

**Comment by MadaraUchiha** [comment]
@lalitkapoor Again, per HTTP specs, if no domain is defined, the expected behavior is to allow the cookie one subdomain level down. AFAIK, all browser do this (mainly because the specific action I'm trying to do with request doesn't fail in any browser I've tried, and I've tried them all).

As an addendum, documentation is seriously lacking in that field. Benjamin ended up finding it, but both of us had to scourge the source of both request and tough-cookie to get any sort of information as to why it happens.

Worth noting that the c.hostOnly option is documented in tough-cookie, but it doesn't explain what sort of effect it has on the cookie.

**Comment by lalitkapoor** [comment]
@MadaraUchiha Thanks for the details. I'll investigate this further. Sorry the documentation wasn't helpful. Will look into addressing that as well.

**Comment by MadaraUchiha** [comment]
Thank you! And if there's anymore information that you need, feel free to hit me (figuratively) :)

**Comment by lalitkapoor** [comment]
@MadaraUchiha I'm taking a look at the spec: http://tools.ietf.org/html/rfc6265#section-4.1.2.3

    The Domain attribute specifies those hosts to which the cookie will
    be sent.  For example, if the value of the Domain attribute is
    "example.com", the user agent will include the cookie in the Cookie
    header when making HTTP requests to example.com, www.example.com, and
    www.corp.example.com.  (Note that a leading %x2E ("."), if present,
    is ignored even though that character is not permitted, but a
    trailing %x2E ("."), if present, will cause the user agent to ignore
    the attribute.)  If the server omits the Domain attribute, the user
    agent will return the cookie only to the origin server.

        WARNING: Some existing user agents treat an absent Domain
        attribute as if the Domain attribute were present and contained
        the current host name.  For example, if example.com returns a Set-
        Cookie header without a Domain attribute, these user agents will
        erroneously send the cookie to www.example.com as well.

My understanding of this is that if you don't specify a domain attribute then it should not work with subdomains (will only work the current domain).

**Comment by lalitkapoor** [comment]
It's also articulated more clearly here - http://en.wikipedia.org/wiki/HTTP_cookie#Domain_and_Path (which references the same RFC 6265 section)

**Comment by MadaraUchiha** [comment]
Indeed. It would appear as though I've read it wrong at some point. I will check again and make sure that the cookies I'm receiving behave the way I expect them to, and see why it works in the browser.

It's entirely possible that browser just don't give a damn about that point in the specs, and will still send to subdomains if no Domain field was specified.

**Comment by lalitkapoor** [comment]
@MadaraUchiha I'm going to close this ticket, please add a comment if you feel this is unresolved. Thanks.
