### ISSUE TITLE
Redirect is loosing Authorization

### ISSUE THREAD

**Issue by AmedeeBulle** [request/request#1409]
After a page redirect, authorization data is lost.

This is because we have an unconditional 'new Auth' in init() at this line: https://github.com/request/request/blob/master/request.js#L498

The following hack works for 'Basic', but we probably need something more elaborate for the other authorization schemes.
```diff
--- request.js.orig	2015-02-05 14:58:12.401690494 +0100
+++ request.js	2015-02-05 14:57:24.809909090 +0100
@@ -495,6 +495,7 @@
   }
 
   // Auth must happen last in case signing is dependent on other headers
+if(!self._auth ) {
   self._auth = new Auth()
 
   if (options.oauth) {
@@ -528,7 +529,7 @@
       options.auth.bearer
     )
   }
-
+}
   if (self.gzip && !self.hasHeader('accept-encoding')) {
     self.setHeader('accept-encoding', 'gzip')
   }
```
(This feature is needed for single sign on, when authorization is done by a third party through redirects)

**Comment by simov** [comment]
I think `self._auth = new Auth(self)` and the rest of the new modules should be called in the `Request` ctor in this case, I wonder how the tests passed on this one.

**Comment by simov** [comment]
@nylen and anyone else can you review https://github.com/request/request/pull/1407 first, as it touches a lot of places in the code base, so that we can add the fix on top of it? I was really trying to keep these PRs as small as possible, but apparently it doesn't go that way always. Also I'm going to figure out a failing test, I haven't looked at all of the tests really.

**Comment by nylen** [comment]
@AmedeeBulle a failing test case would be really helpful here.  I have been swamped lately (just accepted a job with Automattic!) so I'll need at least a few days to do a proper review.  @mikeal @FredKSchott @seanstrom etc. any help appreciated.

**Comment by mikeal** [comment]
@nylen congrats! you working with @rauchg?

**Comment by nylen** [comment]
Thanks!  Looks like not directly at first, hopefully at some point though.

**Comment by AmedeeBulle** [comment]
Here is a very simple failing testcase:
```
var request = require('request');
var user = 'test',
  pass = 'test',
  url = 'http://www.e-bulles.be/redir/p1.html';
request({
  uri: url,
  auth: {
    user: user,
    pass: pass,
    sendImmediately: false
  },
  jar: true
}, function (error, response, body) {
  if (!error && response.statusCode === 200) {
    console.log('Request was OK!');
  } else {
    console.log('ERROR:' + response.statusCode + ':' + error);
  }
});
```
On the server side, I have configured Apache to do the following:
- p1 redirects on p2
- p2 authenticate
- p2 redirects on p3

**Comment by simov** [comment]
Great I'll it to the test suite.
