### ISSUE TITLE
maxSockets per host?

### ISSUE THREAD

**Issue by stevenvachon** [request/request#1410]
I've written [this](https://github.com/stevenvachon/concurrent-host) to accomplish the goal, but is there a way to do it out of the box with request?

I'd tried using `pool:{ maxSockets:1 }`, but it appeared to be maximum sockets regardless of host. I want to blast out requests, but never more than one on each host.

**Comment by stevenvachon** [comment]
I don't want to modify any global settings such as
```js
require('http').globalAgent.maxSockets = 1;
```
```js
require("request").httpModule.globalAgent = new http.Agent({ maxSockets: 1 });
```

**Comment by stevenvachon** [comment]
Or maybe?:
```js
var myAgent = new http.Agent({ maxSockets: 1 })
request({ agent: myAgent })
```

**Comment by stevenvachon** [comment]
Nevermind. :smile: Heheh.

**Comment by nylen** [comment]
Did you find a solution to this?  Not something I've dealt with yet, but would be good to know.

**Comment by stevenvachon** [comment]
It turned out that my tests were faulty and request's `pool:{maxSockets:1}` works just fine in a per-host basis.
