### ISSUE TITLE
Passing options to the QS module

### ISSUE THREAD

**Issue by cycomachead** [request/request#1411]
Is there a way pass different options to `qs`?

**Comment by simov** [comment]
The only thing you can specify is whether to use the `querystring` or the `qs` module, via the `useQuerystring` option

**Comment by nylen** [comment]
If you're trying to pass `{ indices : false }` then `useQuerystring : true` will do what you want.  Otherwise let us know, you'll probably have to stringify it yourself though.

I want this behavior to be the default in the next major version.

**Comment by cycomachead** [comment]
Thanks!

Yeah I found the `useQuerystring` option which does work fine for now, though I have a feeling the API I'm using will require another option later on.
