### ISSUE TITLE
Digest authentication fails if http method is provided via options

### ISSUE THREAD

**Issue by dbellavista** [request/request#1412]
I'm building a client/server application with nodejs. The server uses express and passport and has API protected with Diget authentication. The client uses request.

The following operation is unable to authenticate:

```javascript
  request({
    method: 'get',
    uri: 'http://127.0.0.1:8066/api/test',
    auth: {
      user: 'myuser',
      pass: 'mypass',
      sendImmediately: false
    }
  }, function(err, resp, body) {
    console.log(resp.statusCode);
    console.log(body);
  });
```

However, the following code works:

```javascript
  request.get({
    uri: 'http://127.0.0.1:8066/api/test',
    auth: {
      user: 'myuser',
      pass: 'mypass',
      sendImmediately: false
    }
  }, function(err, resp, body) {
    console.log(resp.statusCode);
    console.log(body);
  });
```

I was expecting the operations to be equivalent. Am I doing something wrong?

**Comment by simov** [comment]
This might be related to #1409 so I'm going to test this case as well.

**Comment by dbellavista** [comment]
If you need a code snippet let me know
