### ISSUE TITLE
Is request support with nodejs 0.12

### ISSUE THREAD

**Issue by stableShip** [request/request#1414]
update nodejs to 0.12 from 0.10.36 .  request -v: 2.53.0 . This Error occur:
![image](https://cloud.githubusercontent.com/assets/2979404/6091684/1338b580-aef3-11e4-837f-171bcd271b0d.png)

**Comment by timmckenzie** [comment]
Confirmaiton, all tests passed in node 0.10.36, but failed in 0.12.0.  Running on OSX.

```
ok test-agentOptions.js ............. 4/4
ok test-basic-auth.js ............. 19/19
ok test-bearer-auth.js ............ 14/14
ok test-body.js ................... 13/13
ok test-cookies.js ................ 17/17
ok test-defaults.js ............... 23/23
ok test-digest-auth.js ............ 11/11
ok test-emptyBody.js ................ 9/9
ok test-errors.js ................... 8/8
ok test-event-forwarding.js ......... 4/4
ok test-follow-all-303.js ........... 3/3
ok test-follow-all.js ............... 3/3
ok test-form-data-error.js .......... 1/1
ok test-form-data.js .............. 40/40
ok test-form-urlencoded.js ........ 12/12
ok test-form.js ................... 18/18
ok test-gzip.js ................... 17/17
ok test-hawk.js ..................... 3/3
not ok test-headers.js ............ 20/22
ok test-http-signature.js ........... 4/4
ok test-httpModule.js ............. 50/50
not ok test-https.js .............. 10/20
ok test-isUrl.js .................. 15/15
ok test-json-request.js ........... 27/27
ok test-localAddress.js ............. 5/5
ok test-multipart.js .......... 1136/1136
ok test-node-debug.js ............. 20/20
ok test-oauth.js .................. 47/47
ok test-onelineproxy.js ............. 3/3
ok test-option-reuse.js ........... 10/10
ok test-params.js ................. 12/12
ok test-piped-redirect.js ........... 2/2
ok test-pipes.js .................. 27/27
ok test-pool.js ..................... 4/4
not ok test-proxy-connect.js ........ 4/5
ok test-proxy.js ................ 104/104
ok test-qs.js ..................... 16/16
ok test-redirect-auth.js .......... 18/18
ok test-redirect-complex.js ....... 40/40
ok test-redirect.js ............... 67/67
ok test-rfc3986.js ................ 22/22
ok test-timeout.js .................. 9/9
```

**Comment by jspavlick** [comment]
I can confirm that this also happened to me, upgrading from Node.js 0.10.36 to 0.12.0 on OS X.

**Comment by chenchaoyi** [comment]
For me it looks this commit causing the failure https://github.com/joyent/node/commit/f34757398fcc393685b4dfbcbdc692fb38332d6c

```
Uncaught TypeError: msecs must be a number
      at Object.exports.enroll (timers.js:156:11)
      at Socket.setTimeout (net.js:329:12)
      at ClientRequest.<anonymous> (_http_client.js:558:10)
      at ClientRequest.g (events.js:199:16)
      at ClientRequest.emit (events.js:129:20)
      at tickOnSocket (_http_client.js:486:7)
      at _http_client.js:497:7
      at process._tickCallback (node.js:355:11)
```

**Comment by nicolasmccurdy** [comment]
This has been fixed with #1468.

**Comment by raitucarp** [comment]
could you upgrade request npm package?

**Comment by murataka** [comment]
i installed nodejs from scratch and the  output in my source is

**Comment by froatsnook** [comment]
@murataka I'm using request on node 0.12, so it must be another problem.  Can you post the code that produced the error?

**Comment by murataka** [comment]
//// here begins function //////
downloadfile = function (file, to, myfun) {


    var options = {
        url: file
    };
   
// here it raises the error   
 get.get(options, "public/img/user/" + to, function (error, result) {
        if (error) {
            console.error(error);
        } else {
			
            if (myfun) myfun(result.file);
            //  console.log('File downloaded at: ' + );
        }
    });

}
////////// here ends function ////////////

var dtid="murataka";

 downloadfile("https://graph.facebook.com/" + dtid + "/picture","/root/public/destination.jpg", function (image) {
                                     
                                    });

**Comment by murataka** [comment]
I have solved the problem modifying the options parameter. In older version , options did have a default value i think. 

-----------------------

  var options = {
        url: file,
        timeout:1000
    };

----------------------------
