### ISSUE TITLE
Content-Type header incomplete for "multipart/related" requests

### ISSUE THREAD

**Issue by pronvit** [request/request#1416]
From RFC:

```
3.1.  The Type Parameter

   The type parameter must be specified and its value is the MIME media
   type of the "root" body part.  It permits a MIME user agent to
   determine the content-type without reference to the enclosed body
   part.  If the value of the type parameter and the root body part's
   content-type differ then the User Agent's behavior is undefined.

3.2.  The Start Parameter

   The start parameter, if given, is the content-ID of the compound
   object's "root".  If not present the "root" is the first body part in
   the Multipart/Related entity.  The "root" is the element the
   applications processes first.
```

**Comment by simov** [comment]
That citation is nice, but can you give us an example, also you can set your multipart header by yourself (if that works for you)

```js
request({headers:{'content-type':'multipart/related; something=else'}})
```

**Comment by pronvit** [comment]
In my case it has to be

```
Content-Type: multipart/related; boundary=XXX; type=text/xml; start="<root>"
```

Where `text/xml` and `<root>` are content-type and content-id of the main part (it's a soap request with attachment).

According to https://github.com/request/request/blob/master/request.js#L1386 if I pass content-type myself, it will take only substring before the first ';', which is effectively `multipart/related` only, so it won't help. I don't understand the purpose of that line completely, actually.

**Comment by simov** [comment]
Got it, it's a bug. I will add a failing test case and a fix once https://github.com/request/request/pull/1413 got in.

**Comment by pronvit** [comment]
Thanks.

**Comment by nylen** [comment]
that link should be https://github.com/request/request/blob/v2.53.0/request.js#L1386 (links to specific lines in master tend to break quickly)
