### ISSUE TITLE
PUT request works with Postman but not with Request

### ISSUE THREAD

**Issue by marincode11** [request/request#1417]
```javascript
var options = {
    url: 'some url',
    headers:{
       'Authorization':  'some auth'
       'Content-Type': 'application/json'
    },
    body: JSON.stringify(req.body),
    json: true
};

var callback = function(err, response, body){
    ///...some nice stuff
};

request.put(options, callback)
```
The status code in the response is 400. 
If I make the same request using postman everything works fine.
Anyone knows what is the problem?

**Comment by simov** [comment]
> body - entity body for PATCH, POST and PUT requests. Must be a Buffer or String, unless json is true. If json is true, then body must be a JSON-serializable object.

Try not stringifying the body.

**Comment by marincode11** [comment]
Still the same response

**Comment by simov** [comment]
Actually are you specifying the http method used?

**Comment by marincode11** [comment]
yes, PUT. I found the problem. It was a typo in my authorization header. Sorry :(
