### ISSUE TITLE
Request truncates large response body

### ISSUE THREAD

**Issue by watsontom100** [request/request#1418]
We're using the latest version of the request lib and are experiencing an issue that when the response body hits a certain size it is truncated.

Because of this it often results in malformed JSON as the object is cut off mid string. 

Have tried explicitly concatenating the chunks using .on('data') however it still stops at a certain size (~ <700000 bytes). The expected response size is itself around 700000 bytes.

I don't believe this is an issue with the endpoint itself as we have fixed it by using Node's lower level http.request:

```
        var responseBody = '';
        var statusCode;
        var options = {
            host: services.django.endpoint.replace('https://', ''),
            path: '/api/buildings/',
            headers: {
                'Authorization': services.django.token
            }
        };
        http.request(options, function(response) {
            response.on('data', function(chunk) {
                responseBody += chunk;
            });
            response.on('end', function() {
                res.status(response.statusCode).json(JSON.parse(responseBody));
            });
        }).end();
```

**Comment by nylen** [comment]
Any chance you can create a self-contained test case?

**Comment by watsontom100** [comment]
Could you expand a bit? A dummy endpoint? Original code? All of the above?..

**Comment by nylen** [comment]
Both?  Something I can run to reproduce the issue.

**Comment by mancvso** [comment]
Be sure to set a higher timeout.

**Comment by sumukhanand** [comment]
I'm seeing this issue as well (JSON response ~<700kb), although it doesn't seem 100% reproducible. One thing I noticed is that JSON.parse fails silently, so in the case of an issue like this, we expect a JSON object, but the truncated string results parse failure. In that case, the returned body is actually the truncated string object, which then causes errors on our side.

As a follow up, is there a reason JSON.parse() fails silently? Since this isn't a consistent issue, at least throwing an error would produce a consistent behavior for us to know that something as failed in the request pipeline.

Reference: https://github.com/request/request/blob/master/request.js#L1043

**Comment by simov** [comment]
@sumukhanand that may brake existing clients that are trying to parse the results on their own, for example when the server is returning JSONP. You can wrap the callback, and add your own logic to be executed on each response.

```js
function response (cb) {
  return function (err, res, body) {
  // throw some error if you want
  }
}
request.get('http..', {...}, response(function (err, res, body) {
  // continue with your app logic
}))
```

**Comment by sumukhanand** [comment]
@simov thanks for pointing out a use case, that makes sense!

**Comment by mediafreakch** [comment]
Any news on this? Same issue here... 
What is the expected behaviour anyway? That `request` only streams complete objects when `content-type` is set to `application/json` ?

**Comment by qvaqvaboo** [comment]
Had similar issue: a chunked response was truncated.
Solved it by disabling buffering on nginx reverse proxy: 
`proxy_buffering off`

Looks like nginx tried to buffer chunks and at some point emitted an empty chunk, which triggered an 'end' event on 'request' module side.

**Comment by tkarls** [comment]
@qvaqvaboo 
Thanks. I had the same problem. But postman worked all the time. Looks like request and nginx proxy_buffering doesn't play well...

**Comment by niralmunjariya** [comment]
Please make sure that gzip is enabled at your server side otherwise you've to pass gzip true in the request options to get a large response data otherwise it'll return an empty string.

e.g. 
```
const options = {
  url: 'apiURL',
  gzip: true,
  method: 'GET'
}
```

**Comment by AlexKalopsia** [comment]
@qvaqvaboo you are my hero

**Comment by hiberabyss** [comment]
Have the same problem, while there is no truncation when use curl.

**Comment by jkldv** [comment]
I see this problem also. The truncation only happens in responses that take over 10 seconds when gzip is specified in the accept-encoding header. Using Postman, downloading a 6MB javascript (ceph dashboard main.js) from France to US, with gzip in Accept-Encoding, the transfer cuts off at ~10 seconds. The size varies and the size is specified in the Content-Length header even though the text content is always truncated. If I disable the Accept-Encoding header (in Firefox or Postman or just using curl) then the file successfully downloads (it takes around 1m 20s on my connection).
