### ISSUE TITLE
Why one connection per request?

### ISSUE THREAD

**Issue by thejh** [request/request#142]
I've looked at the network traffic of a nodejs program I'm currently working on, and it immediately closes couchdb HTTP connections after getting the response (although it sends a `Connection: keep-alive` header, which IMO doesn't fit together with that). Is there a way to turn on connection pooling or so? I think I didn't change any of the related settings.

```
[jann@Jann-PC node-forum master]$ node -v
v0.6.6
[jann@Jann-PC node-forum master]$ npm ls
forum@0.1.0 /home/jann/gitty/node-forum
├─┬ couchapp@0.9.0 
│ ├── request@2.2.9 
│ └── watch@0.5.0 
├── hat@0.0.3 
├── marked@0.1.4 
├── password-hash@1.1.3 
├─┬ ram-static@0.1.0 
│ ├── hat@0.0.3 
│ └── mime@1.2.4 
├─┬ relax@0.1.1 
│ └── request@2.2.9 
└── vacuum@0.1.1 -> /home/jann/gitty/node-vacuum
```

**Comment by Gr1dd** [comment]
The fuck.........
