### ISSUE TITLE
Lingering requests after a ETIMEDOUT

### ISSUE THREAD

**Issue by amosk** [request/request#1433]
I have a periodic loop that checks a DB every second for unsent documents to send to a receiving API built with Node + Express running on Windows Server 2008. The device sending the data is an Ubuntu 14.04 laptop running Node + Request 2.53.0 which roams about moving in and out of a WiFi connection. 

Today the loop tried to send the same document 183 times and each time the loopback passed an error: { [Error: ETIMEDOUT] code: 'ETIMEDOUT' } but the receiving API still received the request 183 times. Its like the request IS timing out after 10000ms but ISN'T and are getting sent anyway. Even Linux TCP should timeout after 20 seconds. Do I need to manually abort the request or what's happening here?

The sending request looks like... 

``` js
var request = require("request");
var url = require("url");
var submit_url = 'http://' + argv.server + '/apiv1/submit_move';

// Begin periodic loop
// when an unsent doc is found mark the doc as "sending" so its not re-sent
setDocStatus.sending(doc)

request({
    uri: submit_url,
    method: "POST",
    timeout: 10000,
    form: {
        original_id: doc.id,
        moveCode: doc.moveCode,
        opID: doc.opID,
    }
}, function(error, response, body){
    if (!error){ // handle response, mark doc as sent if appropriate }
         else {// mark the doc as unsent}
```

**Comment by SethHamilton** [comment]
I'm having the exact same problem. I have a long running daemon that connects to a web service several times per minute or so, there are multiple request objects requesting data from the service for multiple customers. Every week or so I will start getting ETIMEDOUT messages until the process runs out of memory. How do I handle the ETIMEDOUT error properly. I'm using node v0.12

**Comment by pajtai** [comment]
:+1: on hearing how timeouts should be handled / error handlers attached.
