### ISSUE TITLE
Is it possible to proxy a request with multipart/formdata and add Digest auth?

### ISSUE THREAD

**Issue by MartijnR** [request/request#1434]
I'd like to add authentication to a proxied multipart/formdata request. The following one line proxy code works for Basic authentication but not for Digest (I'm guessing because Digest requires an additional request):

```js
function submit(req, res, next){
    var submissionUrl = 'https://some.thirdparty.com/submission';
    var submissionRequest = request( submissionUrl ).auth('username', 'password', false);

    req.pipe( submissionRequest ).pipe( res );
}
```

Is there a way to pipe the request and add Digest authentication? My main goal is to avoid a solution that requires parsing the request body and re-adding the form data to a new request.

**Comment by MartijnR** [comment]
One of the many methods I tried was this one (hacking around, using request's own /lib/auth module) and then add the header to the request above before it is piped to the third party.

```js
var Auth = require('request/lib/auth').Auth;

function getAuthHeader( url, credentials ) {
    var deferred = Q.defer(),
        options = {
            url: url,
            method: 'head',
            headers: {
                'X-OpenRosa-Version': '1.0'
            }
        };

    var req = request( options, function( error, response ) {
        if ( response.statusCode === 401 ) {
            var authHeader,
                  auth = new Auth( req );

            auth.hasAuth = true;
            auth.user = credentials.user;
            auth.pass = credentials.pass;
            auth.method = 'post';

            authHeader = auth.response( auth.method, req.uri.path, response.headers );

            deferred.resolve( authHeader );
        } else {
            deferred.resolve( null );
        }
    } );

    return deferred.promise;
}
```

It creates an Digest authHeader when required. However, the credentials are not accepted, so I must be missing something (credentials are definitely correct).

**Comment by simov** [comment]
Can you try with latest master? There the `response` method is replaced with `onResponse` which actually modifies the request instance. I guess that's your problem here.

**Comment by MartijnR** [comment]
Thanks. I tried with the latest master but it seems to have the same result. I used the code below:

```js
var Auth = require('request/lib/auth').Auth;

function getAuthHeader( url, credentials ) {
    var auth, authHeader,
        deferred = Q.defer(),
        options = {
            url: url,
            method: 'head',
            headers: {
                'X-OpenRosa-Version': '1.0'
            }
        };

    var req = request( options, function( error, response ) {
        if ( response.statusCode === 401 ) {
            auth = new Auth( req );
            auth.hasAuth = true;
            auth.user = credentials.user;
            auth.pass = credentials.pass;
            authHeader = auth.onResponse( response );
            deferred.resolve( authHeader );
        } else {
            deferred.resolve( null );
        }
    } );

    return deferred.promise;
}
```

Also tried the original code (my first post).

**Comment by MartijnR** [comment]
Got it to work (in the latest npm-published version). Turns out auth.method should be 'POST' and not 'post'....

During my troubleshooting experience and after seeing an old PR from @randymized, I compared the Digest Auth header created with the function above using Request's Auth module with one using https://github.com/randymized/www-authenticate. There are some significant differences (but both work). FWIW:

1. The `response` part is different (same length)
2. The `cnonce` part is different and half the length in www-authenticate
3. The algorithm value is surrounded by quotation marks in www-authenticate

**Comment by simov** [comment]
That's great, just keep in mind that we just recently moved the `auth` logic into separate module, and as you can see it may change. As it's not considered a public API yet, you should have tests for that, and run them each time you upgrade the request's version.

**Comment by MartijnR** [comment]
Thanks! Very good to know and a great suggestion.
