### ISSUE TITLE
Ability to clone Cookie Jar

### ISSUE THREAD

**Issue by RafaelVidaurre** [request/request#1438]
I needed this badly so I created it myself, if this is needed by any other members I can submit a PR with the implementation

**Comment by simov** [comment]
Hi @Narzerus you can always submit a PR

**Comment by Narzerus** [comment]
Sure just want to make sure this is something of use for other request users, as my use case is very uncommon at least, will give it a try on my spare time

**Comment by toyg** [comment]
Well, I could use that PR right now, really :) in short, my use-case is parallelizing an authenticated session without the risk of finding out whether Session *really* is thread-safe - I'm reading a lot of ambiguity on that subject and it makes me nervous. Cloning cookies after authenticating would enable me to make thread-safe self-contained calls.

**Comment by chillitom** [comment]
Please, just had to implement this myself also
