### ISSUE TITLE
Should have possibility to set global defaults

### ISSUE THREAD

**Issue by mikkotikkanen** [request/request#1441]
Fe. having to be able to force timout globally (ie. anyone who just requires request will get it with that default setting) would be greatly appreciated. Just had an issue where requests didn't have timeouts and they started piling up on the internal API load balancer, which then caused other issues.

In order to have correct settings set, having to call defaults with correct optiosn every time you use request is a bit on the dangerous side, especially on diverse teams.

On app.js, just being able to call something like...
```js
require('request').globalDefaults({
  timeout: 10*1000
});
```
...could be hugely beneficial. Or even setting custom headers etc.

In this case, I ended up fixing the issue by duckpunching `.get`, `.post` etc. shorthand methods with logic that adds timeout to the requests. Not a pretty solution but works for now.

**Comment by nylen** [comment]
I think I'm -1 on setting global defaults in this way, you don't know what other code may be running using the same `request` module.  Here's what I'd recommend instead:

In `lib/request.js`

```js
exports.request = require('request').defaults({
    timeout : 10000
});
```

In your other files:

```js
var request = require('./lib/request');
```

**Comment by mikkotikkanen** [comment]
Alright, fair enough, but would it at least be possible to have reasonable defaults on it? Since now by default it's effectively creating requests with infinite timeouts, which should be only needed in few very special cases.

In any normal case, having ~20 second timeout is more than enough, since if there is no response in that time, something has gone wrong. And if someone has long running requests they can opt-in to set the timeout to infinite. Ie. the default behavior would have reasonable defaults with opt-in for really long running requests.
