### ISSUE TITLE
Clarify documentation on strictSSL

### ISSUE THREAD

**Issue by dantman** [request/request#1449]
The README says "`strictSSL` - If true, requires SSL certificates be valid.".

This gives the impression that it's false by default and request has a bad security practice that has to be overridden explicitly every time you use it.

However looking at [the actual code](https://github.com/request/request/blob/a60482bf06b7e16d3cdbabcdee7f0b62d93117c2/request.js#L388-L390) strictSSL is compared `=== false` so its default is to verify certificates.

**Comment by dantman** [comment]
Hmm, however [line 984](https://github.com/request/request/blob/a60482bf06b7e16d3cdbabcdee7f0b62d93117c2/request.js#L984) doesn't compare `=== false` so I'm unsure if I'm right or wrong.

**Comment by sdiemert** [comment]
I would also like this clarified. I, like @dantman read the docs and assumed the the default was false.

**Comment by ametaireau** [comment]
Hi. It's very unclear from the documentation if strictSSL is set to true by default, and what the behaviour is.

Does anyone has an insight?

**Comment by dfLloyd** [comment]
Hi Guys, Its more than a year for this quesion and still there is no clear documentation for this feature. Can someone please throw some light on this question. I would also like to know the ramification of turning this off. Thanks in advance.

**Comment by drasive** [comment]
This is still an issue and should be reopened.

**Comment by aryehb** [comment]
I ran a quick test with Node v14 and request v2.88.0.

```javascript
const request = require('request');

const options = {
  url: 'https://self-signed.badssl.com/',
  // strictSSL: false,
};

request.get(options, err => {
  if (err) return console.error(err);
  console.log('Successfully made a request with bad SSL.');
});
```
Running the above code outputs the following error:
```
Error: self signed certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1321:34)
    at TLSSocket.emit (events.js:223:5)
    at TLSSocket._finishInit (_tls_wrap.js:794:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:608:12) {
  code: 'DEPTH_ZERO_SELF_SIGNED_CERT'
}
```
Uncommenting the `strictSSL` line causes the other message to be logged instead of the error.

So it seems that `strictSSL` is set to `true` by default, at least in these versions.
