### ISSUE TITLE
Implement progress events

### ISSUE THREAD

**Issue by dantman** [request/request#1450]
It would be nice to have (optional) progress events that would fire for progress (against content-length if available) on the raw entity body.

There are 2 libraries that do progress events for request, [request-progress](https://www.npmjs.com/package/request-progress) and [progress-stream](https://www.npmjs.com/package/progress-stream).

However both of them fail when you use `gzip: true`. `Content-Length` describes the length of the entity body (compressed) but both of these libraries only have access to the inflated (uncompressed) stream request gives out.

It doesn't seem possible for these libraries to dig themselves into request's internals to access the raw stream and watch the data that streams through it. So support for progress events looks like something that can only be implemented correctly from within request.

**Comment by mikeal** [comment]
what is the format of the progress event?

**Comment by dantman** [comment]
progress-stream's format is:
```js
{ percentage: 0.9421764873591874,
  transferred: 1421,
  length: 150821,
  remaining: 149400,
  eta: 210,
  runtime: 95,
  delta: 1421,
  speed: 710.5 }
```

request-progres' format is:
```js
{ total: 150821, received: 1421, percent: 1 }
```

How you want to implement it in request is up to you.

You could implement a high level event like progress-stream does with all the data like eta and speed (with the help of [speedometer](https://www.npmjs.com/package/speedometer)) and provide a a sample rate option to `request()` to decide how fast to fire the event.

Or you could implement a low level event with just `length` and `received` (or even just `received` since that's the only data these libraries are actually missing) and fire it for every data chunk. If this is the case I would recommend doing something like _ prefixing it so the higher level libraries can be responsible for the `progress` event.

**Comment by dantman** [comment]
If you want to do a low level event basing property names on standards instead of picking a side on how properties in the progress event should be named.

XHR2's `ProgressEvent` interface (which is used in `xhr.upload.onprogress` and `onprogress` events in html for tags like `<img>`) is `e.lengthComputable` (if the size is known and `e.total` can be specified), `e.total`, and `e.loaded`.

**Comment by michahell** [comment]
Is this somehow already possible with request? seems like a very basic feature, and it is already possible with just using node's ```http``` or ```https``` modules:

https://gist.github.com/falkolab/f160f446d0bda8a69172

**Comment by goya** [comment]
just listen to the "data" event.  as obviously all data going in and out causes this. right. right.

**Comment by dantman** [comment]
> just listen to the "data" event. as obviously all data going in and out causes this. right. right.

That is exactly what the existing progress modules do and that is why they are broken. When you get a gzipped response `request` passes uncompressed data to the `data` event. Which means the length of data the event is given and the actual lenght of data that has been read from the network are different.

**Comment by goya** [comment]
oh im doing an upload, we get no events at all.

**Comment by goya** [comment]
has there been any progress to grab upload progress past using bytesWritten from the socket object?

**Comment by pietrovismara** [comment]
+1

**Comment by scotttrinh** [comment]
Is the `request` team open to PRs on this issue? I'm currently implementing this feature for my own purposes and would be happy to submit a PR for review if the team is interested.
