### ISSUE TITLE
response body serialization

### ISSUE THREAD

**Issue by james075** [request/request#1455]
Hi,

My point is maybe stupid but I would like to avoid doing this in all my request responses:

```js
	request(url, function (error, response, body) {
		var result = JSON.parse(body);
	});
```

Questions:
- Is that possible to automatically serialize response? 
- If so, is there an option that I can set once, to actually do that?

**Comment by chenchaoyi** [comment]
Probably `json: true`

**Comment by james075** [comment]
@chenchaoyi thanks
