### ISSUE TITLE
Abort request client side

### ISSUE THREAD

**Issue by ErikOrjehag** [request/request#1457]
I'd like to abort a request before it resolves. There's a built in method for this in the node core:
http://nodejs.org/api/http.html#http_request_abort

The above method triggers an error event on the request which I don't like. If an error event can be avoided I'd prefer it.

I haven't been able to find a similar abort method in request. Is this something that already exists or would you be interested in implementing something like this?

My use case for this is to abort a request to a long poll endpoint, add more data to the request, and then establish a long poll again.

**Comment by rogierschouten** [comment]
I did find the abort() method in the code but it throws an exception because it tries to call a non-exisitng abort() function on an http.IncomingMessage if you're unlucky. Currently trying the destroy() method

**Comment by ErikOrjehag** [comment]
I should have looked at the source before posting. It's interesting that you get an error because my small test seems to work.

```js
var http = require('http');
var request = require('request');

http
  .createServer(function (req, res) {
    console.log('server: got request');
    req.on('close', function () {
      console.log('server: closed connection');
    });
  })
  .on('error', console.log)
  .listen(3000, makeRequest);


function makeRequest () {
  
  console.log('client: making request');

  var req = request
    .get('http://localhost:3000')
    .on('data', console.log)
    .on('error', console.log)
    .on('abort', function () {
      console.log('client: aborted request');
    });

  setTimeout(function () {
    req.abort();
  }, 1000);
}
```

**Comment by rogierschouten** [comment]
As far as I can see, it will go wrong when you've already received the headers but not the body of the response. In that case the request module will try to call abort() on a http.IncomingMessage and that doesn't have an abort() function.  I did get a TypeError in practice. After that I switched to destroy() which has worked for me so far.
I agree that it would be nice if it were documented. I'm also left wondering what the difference between abort() and destroy() is meant to be.

**Comment by laggingreflex** [comment]
+1 Should be mentioned in the docs.

**Comment by ahutchings** [comment]
I think this might be the same issue as https://github.com/substack/http-browserify/issues/79. abort() is not implemented in the http Request object used by browserify. An exception is also thrown when using the `timeout` option, which calls abort() internally.
