### ISSUE TITLE
Allow configuring a default base url

### ISSUE THREAD

**Issue by giladbeeri** [request/request#1464]
It will be useful for REST clients to be able to do something like this:

```js
var request = require('request').defaults({
    baseUrl: 'http://api.domain.com:9999/api/v1'
});
request('/objects'); // GET http://api.domain.com:9999/v1/objects

```

**Comment by simov** [comment]
You can check out [Purest](https://github.com/simov/purest) which is a very thin wrapper around request that does exactly that, though it might be a good idea to have `baseUrl` here as well.

**Comment by froatsnook** [comment]
Hi @giladbeeri @simov, I had a go at this.

* What to do when baseUrl has a path component, like `http://example.com/base/path`? Append path or ignore?
* What to do when baseUrl has query parameters? Ignore or append/replace?

**Comment by simov** [comment]
I saw your PR and I will take a look at it a bit later.

**Comment by froatsnook** [comment]
@simov OK thank you :)

**Comment by giladbeeri** [comment]
Hi @froatsnook, definitely when there's  a path component it should be included (appended). Regarding query parameters - it feels for me a bit odd, I think it is more natural to put default query parameters in another configurable variable. Query parameters aren't part of the URL.
Thanks for the PR!

**Comment by froatsnook** [comment]
Hello @giladbeeri , I just added 2 more commits to the PR with path handling.  It works like:

```
request("def", { baseUrl: "http://example.com/abc" }, ...) // => http://example.com/abcdef
request("def", { baseUrl: "http://example.com/abc/" }, ...) // => http://example.com/abc/def
request("/def", { baseUrl: "http://example.com/abc" }, ...) // => http://example.com/abc/def
request("/def", { baseUrl: "http://example.com/abc/" }, ...) // => http://example.com/abc/def
```

Does that make sense to you?

**Comment by giladbeeri** [comment]
@froatsnook thanks.
The 3 bottom examples make sense. The first one does not - I expect this feature to be used as base URLs for REST APIs, for example: `http://www.domain.com/api/v1`. So I think the first example is counter intuitive. baseUrl should always be followed by a '/' (i.e., if it's given like in the first example, the lib should add the /.

From that reasoning I think that the 3 other examples are a must.

**Comment by froatsnook** [comment]
@giladbeeri I felt the same way at first, but then I thought it might be confusing if this happened:

```
request("-create", { baseUrl: "http://example.com/user" }, ...) // => http://example.com/user/-create
request("-delete", { baseUrl: "http://example.com/user" }, ...) // => http://example.com/abc/-delete
```

Likely people wouldn't use it like this anyway, but to me it seems a bit clearer to say "we append the uri's path to the baseUrl's path" and not "we append the uri's path to the baseUrl's path unless you forgot to put a slash somewhere in which case we put one there for you".

P.S. any ideas on a clear way to document this baseUrl feature in the README?

**Comment by giladbeeri** [comment]
@froatsnook I think the reasoning for my suggestion is stronger. It should work as the popular `path.join()` from NodeJS & Python (but without the caveat of using '\' on Windows, because URLs always use '/'). Also see the NPM package `url-join` as a reference.
And even though `url-join` does treat query parameters to the URL, I think it is wrong in that. Query parameters are exactly that - parameters, data. Another way to represent data, analogous to data in the request body. They are not part of the URL but just additional data to the server.
Also, if you append query parameters, you need to decide how you handle conflicts with the `qs` parameter in `request`, and there I don't see a clear decision.

So my opinion - learn from `url-join`, but without the query parameters.

re docs, I think that the best documentation will be using examples, you can also refer to `url-join` (maybe even use it). Use the example I gave, I think it is clear (a URL which is a base URL for a REST API). I don't think it should be considered confusing if you write something like "the `baseUrl` will be prepended to the path".

**Comment by simov** [comment]
Lets keep this conversation under the PR in question https://github.com/request/request/pull/1469
