### ISSUE TITLE
Cache for GET requests?

### ISSUE THREAD

**Issue by apsavin** [request/request#1470]
What about cache for `GET` requests?
Request is an HTTP Client, but for now, as I understand, it doesn't cache any `GET` requests, even if the appropriate headers are set.
Should we add cache logic to the `request` module? May be, it would be better to create other module for that?

**Comment by benkroeger** [comment]
take a look at [oniyi-requestor](https://www.npmjs.com/package/oniyi-requestor). It implements rfc 2616 compliant caching on top of request

**Comment by apsavin** [comment]
Well, I think that the caching logic should be definitely in separate module.
@benkroeger your requestor looks interesting, thanks.
