### ISSUE TITLE
I get xml from server, then transform it to json by xmlreader, how can I modify the json.

### ISSUE THREAD

**Issue by Melvin-Wu** [request/request#1471]
I get xml from server, then transform it to json by xmlreader, how can I modify the json, and save it as xml.

**Comment by lalitkapoor** [comment]
out of the scope of this library, but you may consider something like the following: https://github.com/estheban/node-json2xml

**Comment by Melvin-Wu** [comment]
thanks, I just use xml2json, it can transfrom xml between json,

**Comment by lalitkapoor** [comment]
Cool. Can I close this issue then please? Thanks! @Melvin-Wu

**Comment by Melvin-Wu** [comment]
but I have a new problem,you see my config xml is:
<?xml version="1.0" encoding="UTF-8"?><domain xmlns:xs="http://www.xx.org/2001/XMLSchema" xmlns:xxx="http://xxx.xxx.xx.com/extension/xhtml"><domain-id>11111</domain-id><domain-name>p3.pstatp.com</domain-name><service-type>web</service-type><cname>y88lu6tjd86r5o.xxxxxx.com</cname><status>Deployed</status><enabled>true</enabled><comment>p3.pstatp.com</comment><service-areas>cn</service-areas><origin-config><origin-domain-name>0793cc9d.src.ucloud.com.cn</origin-domain-name></origin-config></domain>
 I transform it to jsonobj:
{ domain: 
   { 'xmlns:xs': 'http://www.w3.org/2001/XMLSchema',
     'xmlns:cloudcdn': 'http://cloudcdn.chinanetcenter.com/extension/xhtml',
     'domain-id': 210787,
     'domain-name': 'p3.pstatp.com',
     'service-type': 'web',
     cname: 'y88lu6tjd86r5o.wscloudcdn.com',
     status: 'Deployed',
     enabled: true,
     comment: 'p3.pstatp.com',
     'service-areas': 'cn',
     'origin-config': { 'origin-domain-name': '0793cc9d.src.ucloud.com.cn' } } }

then i add an element in it and transform it back to xml,but i the result is ：
<domain xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cloudcdn="http://cloudcdn.chinanetcenter.com/extension/xhtml" domain-name="p3.pstatp.com" service-type="web" cname="y88lu6tjd86r5o.wscloudcdn.com" status="Deployed" comment="p3.pstatp.com" service-areas="cn" origin-ips="1.2.3.4"><origin-config origin-domain-name="0793cc9d.src.ucloud.com.cn"></origin-config></domain>、

where are the other '<' and '>'? thanks.@lalitkapoor

**Comment by lalitkapoor** [comment]
@Melvin-Wu that's a question that's better suited for the library you are using, and is out of the scope for request. I'd recommend opening up a ticket there and closing this one. Thanks!

**Comment by Melvin-Wu** [comment]
Thanks.
