### ISSUE TITLE
forever-agent does not work with Node 0.12

### ISSUE THREAD

**Issue by akshayp** [request/request#1472]
Moving https://github.com/request/request/issues/1421#issuecomment-74371413 since this technically doesn't block request from working unless the forever option is enabled

I'm using the forever option with request. Starting 0.12 this option leads to ENOTSOCK and ECONNRESET errors. This never works presumably because the HTTP Agent API changed quite a bit with node 0.12. eg:

```js
var request = require('./index').forever({maxSockets: 1});
request('http://www.yahoo.com', function (error, response, body) {
    if (error) {
        console.log(error);
    } else {
        console.log(response.statusCode);
    }
});
```
 leads to

```
{ [Error: connect ENOTSOCK] code: 'ENOTSOCK', errno: 'ENOTSOCK', syscall: 'connect' }
```

vs on node 0.10 it logs

```
200
```

**Comment by nicolasmccurdy** [comment]
It seems like it would help to write a test for this functionality.

**Comment by akshayp** [comment]
@nicolasmccurdy Added a test in the linked PR
