### ISSUE TITLE
relative URLs with the request library

### ISSUE THREAD

**Issue by the1mills** [request/request#1476]
please see this SO question:

http://stackoverflow.com/questions/29026346/relative-uri-for-node-js-request-library

is it possible to use relative URLs with the request library?

**Comment by simov** [comment]
What exactly do you expect to happen? Request doesn't know anything about your relative url.

**Comment by simov** [comment]
Actually this might be related to https://github.com/request/request/pull/1469 with this new feature you will be able to set one `baseUrl` to use for all of your requests.

**Comment by the1mills** [comment]
thanks let me check that #1469 out
