### ISSUE TITLE
Add a note to the readme about the current stable release not having Node 0.12/io.js support

### ISSUE THREAD

**Issue by nicolasmccurdy** [request/request#1478]
The master branch has recently been fixed on Node 0.12 and io.js (and the tests run on those versions along with 0.10), though it may not be obvious to some users that the current stable version does not support this yet.

**Comment by simov** [comment]
Hi @nicolasmccurdy the only fixes made regarding node 0.12 and io.js so far were on the test suite. What exactly isn't working for you?

**Comment by seanstrom** [comment]
I think @nicolasmccurdy is saying that Master is passing but the npm module isn't up to date.
Right?

**Comment by nicolasmccurdy** [comment]
@simov There isn't anything specific that I have noticed as being broken on Node 0.12/io.js yet. I have noticed that you made minor edits to `request.js` in some of your recently merged pull requests. Would the current stable release of request work fine on Node 0.12/io.js without these updates?

**Comment by simov** [comment]
Yes, nothing specific to node 0.12/io.js that I can remember https://github.com/request/request/search?utf8=%E2%9C%93&q=is%3Apr+merged%3A%3E2015-02-03&type=Issues though a few other bugfixes were made as usual, so probably it would be good to have a new release soon.

**Comment by nicolasmccurdy** [comment]
Ah, thank you for clarifying. I'm sorry for the confusion, I'll close this now.
