### ISSUE TITLE
encoding: null is a hard-to-find trick when response body is not utf-8

### ISSUE THREAD

**Issue by kapouer** [request/request#1479]
Hi,
i am requesting some xml file encoded in iso-8859-1 and have to go through this

```
var icon = require('iconv-lite');
request({url: myurl, encoding: null}, function(err, res, body) {
  var str = iconv.decode(body.toString('binary'), 'Latin1');
  // do stuff with utf-8 string
});
```

to convert it to utf-8.
The `encoding: null` thing is particularly tricky !
Don't you think request API should be more explicit ?

**Comment by simov** [comment]
Definitely, it's not user friendly IMO. Any suggestions on improving it are greatly appreciated.
