### ISSUE TITLE
Weird JSON.parse() issue on Node v0.12.0

### ISSUE THREAD

**Issue by mightwork** [request/request#1480]
The JSON you receive on a GET call from https://api.github.com/repositories is a perfectly valid one. But JSON.parse() on the body gives a `SyntaxError: Unexpected token u` error.
The body variable has string type.
eval() fixes it but eval() is evil.
Performing .toString() on body and then `JSON.parse(body)` works fine.

**Comment by nicolasmccurdy** [comment]
I created a simple example to see if I would have issues, and the code below works for me with Node 0.12.0. It sounds like the value you're getting in the body isn't an Array or Object at the top level (which would make it invalid JSON). Also, make sure that you're giving a `User-Agent` header (GitHub requires it), using HTTPS, and staying under your rate limit. If this doesn't solve your issue, please post your code.

```javascript
var request = require('request');

request('https://api.github.com/repositories', {
  headers: {
    'User-Agent': 'request'
  }
}, function (error, response, body) {
  if (error) {
    console.error(error);
  } else {
    console.log(JSON.parse(body));
  }
});
```

**Comment by simov** [comment]
@nicolasmccurdy actually anything except `undefined` is a valid JSON, and that is the exact error, @singhkushagra 

```js
> JSON.parse('{}')
{}
> JSON.parse('[]')
[]
> JSON.parse('null')
null
> JSON.parse('0')
0
> JSON.parse('true')
true
> JSON.parse('undefined')
SyntaxError: Unexpected token u
    at Object.parse (native)
    at repl:1:6
    at REPLServer.defaultEval (repl.js:132:27)
    at bound (domain.js:254:14)
    at REPLServer.runBound [as eval] (domain.js:267:12)
    at REPLServer.<anonymous> (repl.js:279:12)
    at REPLServer.emit (events.js:107:17)
    at REPLServer.Interface._onLine (readline.js:214:10)
    at REPLServer.Interface._line (readline.js:553:8)
    at REPLServer.Interface._ttyWrite (readline.js:830:14)
> 

```
