### ISSUE TITLE
facebook login problem

### ISSUE THREAD

**Issue by itsmylife** [request/request#1482]
Hi. 
I have an issue about facebook login. When I try to login facebook send me this error:
`{ '{"error":{"message":"Missing client_id parameter.","type":"OAuthException","code":101}}': '' }`

I double check my code. There is not error I think. Here is my code. Maybe request has got a bug or something else. Am I missing something?

```js
var request = require('request'),
	qs = require('querystring'),
	createSendToken = require('./jwt.js'),
	config = require('./config.js'),
	User = require('../models/User.js');


module.exports = function(req, res) {
	var accessTokenUrl = 'https://graph.facebook.com/oauth/access_token';
	var graphApiUrl = ' https://graph.facebook.com/me';

	var params = {
		client_id: req.body.cliendId,
		redirect_uri: req.body.redirectUri,
		client_secret: config.FACEBOOK_SECRET,
		code: req.body.code
	};
/* I check the req.body. All data is correct. */
	request.get({
		url: accessTokenUrl,
		qs: params
	}, function(err, response, accessToken) {
		/*there is where I got the error */
		accessToken = qs.parse(accessToken);

		request.get({
			url: graphApiUrl,
			qs: accessToken,
			json: true
		}, function(err, response, profile) {
			console.log(profile.id);
			User.findOne({
				facebookId: profile.id
			}, function(err, existingUser) {
				if (existingUser){
					return createSendToken(existingUser, res);
				} 

				var newUser = new User();
				newUser.facebookId = profile.id;
				newUser.displayName = profile.name;
				newUser.save(function(err){
					createSendToken(newUser, res);
				});
			});
		});
	});
};
```

**Comment by itsmylife** [comment]
And for information: 

I search this error on the google. redirect_uri must have a "/" at the end. I check that double. Everything is fine. But I still got error.

**Comment by simov** [comment]
Your code looks correct, so is the error `Missing client_id parameter` or `redirect_uri must have a "/" at the end` ?

**Comment by itsmylife** [comment]
Hi simov. Thanks for your reply. redirect_uri has "/" at the end. I checked it.

**Comment by simov** [comment]
You are probably using express, but whatever web framework it is, you can check out [grant](https://www.npmjs.com/package/grant) which will handle the OAuth business for you.

You only have to put your `https://graph.facebook.com/me` call and database handling logic inside the final callback.

**Comment by itsmylife** [comment]
Yes I use express. I will check grant. I will inform you when I review my code. Thank you simov.

**Comment by itsmylife** [comment]
Problem continues. I stopped grunt. I used wamp to serve my frontend files. I use nodemon for backend btw. I tried again and it failed. I stopped nodemon. I tried with classic way. It failed again. I do not know where the problem is.

**Comment by simov** [comment]
Certainly not a problem with request, the module that I showed uses request internally, also there are plenty of examples in that repository to figure out how to configure it and use it.

Here, I'll click a few links for you [example](https://github.com/simov/grant/blob/master/example/profile/app.js) Essentially you are trying to achieve exactly that - get access token and user profile.
