### ISSUE TITLE
Impossible to write response text in file.

### ISSUE THREAD

**Issue by FlamesoFF** [request/request#1484]
It's possible somehow to write response text in a file? For example I wanna get script. This code isn't working:

``` javascript
request.get("https://samplesite/sample_script.js")
        .pipe(fs.createWriteStream("sample_script.js"))
        .pipe(gulp.dest("/scripts/"));
```

Result is error:  **Error: Cannot pipe. Not readable.**

**Comment by froatsnook** [comment]
```
request("http://github.com")
    .pipe(fs.createWriteStream("TEST.txt"));
```

will write the result to TEST.txt.  I think the problem is that `fs.createWriteStream` writes to file directly, whereas you probably want to use `gulp.dest` or something.
