### ISSUE TITLE
request module can get iframe??

### ISSUE THREAD

**Issue by YooJaSung** [request/request#1487]
now iam using request and get some website html code.

some sites use iframe tag.. run request callback after request.post, console.log(html) didn't show 

iframe tag,,

request module can not scrap ifram tag ??

if possible, how can i access iframe tag contents ??

**Comment by nicolasmccurdy** [comment]
It sounds like you're looking for the HTML inside of an iframe. If so, you will probably need a browser (or a fake DOM implementation) running to load the iframe. The source of an HTML page with an iframe does not include the iframe's source (if the iframe is loading external content).

**Comment by YooJaSung** [comment]
thank you for your answer!!

i have one more question..

when i test website develop tool,  respose and preview data show some tags ,, but after request

that tag cannot see in my console.. 

i add images.. it's really make me crazy... 
![2015-03-16 4 13 36](https://cloud.githubusercontent.com/assets/6368241/6661911/83d26a2c-cbf7-11e4-91ce-4a208b27d130.png)
this is website response

and  next is my console
![2015-03-16 4 13 51](https://cloud.githubusercontent.com/assets/6368241/6661915/907f460a-cbf7-11e4-92f9-0311ccf81221.png)
