### ISSUE TITLE
Catch URI errors

### ISSUE THREAD

**Issue by temsa** [request/request#149]
Invalid URI are no checked and raises a synchronous Error we have to either `try/catch` or use `process.on('uncaughtException', ...)` which is a pretty bad idea.

Current code has to be :

``` javascript
try {
  request.post({uri: "my invalid uri", body:"my content"}, mycallback)
} catch(e) {
  mycallback(e)
}
```

I guess this can be done in request itself to avoid providing both a callback which handles asynchronous errors and a try/catch for synchronous errors

**Comment by saper** [comment]
Cross referencing https://github.com/request/request/issues/1318#issuecomment-97374120 discussion  - not everything goes to the `on(error)` event handler; most things can be caught using the callback; but there are still few cases that may throw an exception.

**Comment by ncrichards** [comment]
Need help: This url is valid and can open in any web browser, but it throws Error: Invalid URI in request API.
http:/g.alicdn.com/kissy/k/1.4.0/??node-min.js,dom/base-min.js,event/dom/base-min.js,event/base-min.js,event/dom/shake-min.js,event/dom/focusin-min.js,anim-min.js,anim/base-min.js,promise-min.js,anim/timer-min.js,anim/transition-min.js,io-min.js,event/custom-min.js,event-min.js,xtemplate-min.js,xtemplate/runtime-min.js,xtemplate/compiler-min.js,cookie-min.js,base-min.js?t=4056852921.js

**Comment by saper** [comment]
Please double check: after "http:" you need two slashes // not just one. Also double check question marks, there should be only one "?" separating the path "/1.4.0/" from what looks like URL variables. Also before "ts=" it might be "&" instead of "?". Your URL is invalid; browser try to do everything possible to load invalid addresses, but that does not make them valid.

**Comment by ncrichards** [comment]
Thanks @saper , I didn't notice the missing slash. Problem solved

**Comment by lazyboywu** [comment]
saved

**Comment by ggiacomo** [comment]
Not clear which is the solution for this issue. Thanks
