### ISSUE TITLE
https proxy fails with ECONNRESET, and "unknown header (&)"

### ISSUE THREAD

**Issue by npiguet** [request/request#1491]
Hi,

I've been trying to install tnode-sass on my machine and I keep hitting problems with my proxy server. I've raised the issue sass/node-sass#768, and it appears that this may be an issue with request, or a misuse of request.

Anyway, here is the case: 

I've got a proxy (cntlm) that can be accessed through both HTTP and HTTPS. When I specify the proxy url using `http:` things work as expected. When I specify the proxy url using `https:` nothing works at all.

Basically, whenever I use `https` as proxy url I get the same root cause for the error: The script returns an `ECONNRESET` error (with no more information about what was wrong), and the proxy debug logs show the following:

```
******* Round 1 C: 21 *******
Reading headers (21)...
HEAD: &headers_recv: Unknown header (&).
headers_recv: fd 21 error -4
Joining thread 140418809730816; rc: 0
```

This error message seems to indicate that the headers part of the request contains a `&` character that the proxy does not understand. It also seems that this `&` character is not followed by a line break.

The same thing happens whether I set `tunnel` to `true` or `false`.

The `options` object passed to request is the following:

``` javascript
{ 
  rejectUnauthorized: false,
  proxy: 'https://127.0.0.1:3129',
  tunnel: true,
  ca: null,
  strictSSL: false 
}
```

Note that in my situation, I don't have many possible workarounds (such as setting the proxy URL to http) because the script must run without extra configuration on all the computers of my organization, which has a very heterogenous setup.

**Comment by kittycatbytes** [comment]
This is also happening to me - very frustrating that I've done lots of research on this and there is no solution.  Node-sass is the only one that causes me issues - I've installed hundreds of other modules with a proxy configuration with no issue.
