### ISSUE TITLE
Empty response detected as Connection refused

### ISSUE THREAD

**Issue by steelbrain** [request/request#1492]
Chrome gives me ERR_EMPTY_RESPONSE for Web1 and ERR_CONNECTION_RESET for Web2.
Request gives me ECONNRESET for both of them.

**Comment by froatsnook** [comment]
What are Web1 and Web2?  Can you provide a reproducible example?

Under the hood, `request` is calling `http.request` or `https.request`, which is generating the `ECONNRESET` error.  In other words, you probably need to go upstream!

**Comment by steelbrain** [comment]
Web1 is a bitcoind port 3333, the full address would be "localhost:3333"
and Web2 would be any external port declined by the firewall.

**Comment by steelbrain** [comment]
Closing this issue as I am not pursuing this any longer. Feel free to re-open if anyone else is.
