### ISSUE TITLE
Unable to pass in an object to formData

### ISSUE THREAD

**Issue by joshuamcginnis** [request/request#1495]
It seems that whenever I add an object (such as the `to` object below) to formData, I get an error. If I remove the `to` object or change it to a string, I no longer get an error.

Why is this?

```javascript
var fs      = require('fs');
var request = require('request');
var file    = './test/assets/test.pdf';

var opts = {
  url: 'my_service',
  method: 'POST',
  auth: { user: 'username', password: 'password' },
  json: true,
  formData: {
    front: fs.createReadStream(file),
    to: {
      name: 'joe bob',
      address_1: '123 main st',
      ...
    }
  }
};

request(opts, function(err, resp, body) {
  console.log(err, body);
});
```

Error:

```console
/sandbox/project/node_modules/request/node_modules/combined-stream/node_modules/delayed-stream/lib/delayed_stream.js:33
  source.on('error', function() {});
         ^
TypeError: undefined is not a function
    at Function.DelayedStream.create (/Users/me/sandbox/project/node_modules/request/node_modules/combined-stream/node_modules/delayed-stream/lib/delayed_stream.js:33:10)
    at FormData.CombinedStream.append (/Users/me/sandbox/project/node_modules/request/node_modules/combined-stream/lib/combined_stream.js:43:37)
    at FormData.append (/Users/me/sandbox/lproject/node_modules/request/node_modules/form-data/lib/form_data.js:43:3)
    at appendFormValue (/Users/me/sandbox/project/node_modules/request/request.js:466:21)
    at Request.init (/Users/me/sandbox/project/node_modules/request/request.js:477:11)
    at new Request (/Users/me/sandbox/project/node_modules/request/request.js:264:8)
    at request (/Users/me/sandbox/project/node_modules/request/index.js:50:10)
    at Object.<anonymous> (/Users/me/sandbox/project/test.js:30:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
```

**Comment by joshuamcginnis** [comment]
This works for now ...

var opts = {
  url: 'my_service',
  method: 'POST',
  auth: { user: 'username', password: 'password' },
  json: true,
  formData: {
    front: fs.createReadStream(file),
    'to[name]': 'joe bob',
    'to[address_1]': '123 main st'
  }
};

**Comment by kruchone** [comment]
That is the correct way to handle this, as the library `form-data` which request uses does not have support for appending anything but strings to the data.

**Comment by kengz** [comment]
Hey there just tried to do the same thing,
Since the right way pointed above is probably not the most efficient,
I've written a method in my library for this; it flattens the JSON for formData.
Just putting this out for anyone to use it: [flattenJSON](http://kengz.github.io/lomath/#flattenJSON)

**Comment by simov** [comment]
I don't think that there is a standard way to handle object parameters outlined in the spec, although the `flattenJSON` method seems to be really nice for such cases.

**Comment by funkyLover** [comment]
how about this situation
i got a formdate like that
```
var formData = {
  body: {
    header: {
      token: token,
      username: username
    },
    pageUrl: pageUrl
  }
  file: fs.createReadStream(self.file)
};
```

**Comment by fdefitte** [comment]
The [flattenJSON ](http://kengz.me/lomath/#flattenJSON) works great for me too, thanks @kengz !
`formData : _.flattenJSON(formData)` does the trick

**Comment by arshadkazmi42** [comment]
This Options structure worked for me for POST request

```
var opts = {
  			url: url,
  			method: method,
  			headers: headers,
  			json: true,
	  		body: formData
		};
```

**Comment by DylanPiercey** [comment]
You can checkout [q-flat](https://github.com/DylanPiercey/q-flat) for converting nested objects to valid form data objects.

**Comment by xseignard** [comment]
What about arrays of arrays? 
Such as the `guide` parameter on the facebook video api: https://developers.facebook.com/docs/graph-api/reference/user/videos/#Creating (chapter Parameters > `source`param)

It expects something like:
```
formData: {
	guide_enabled: 1,
	guide: [[2, -90, 0], [4, 0, 180], [6, 90, -180]],
	description: opts.message,
	source: fs.createReadStream(videoPath),
},
```
So I try to send the following:
```
formData: {
	guide_enabled: 1,
	'guide.0.0': 2,
	'guide.0.1': -90,
	'guide.0.2': 0,
	'guide.1.0': 4,
	'guide.1.1': 0,
	'guide.1.2': -180,
	'guide.2.0': 6,
	'guide.2.1': 90,
	'guide.2.2': 180,
	description: opts.message,
	source: fs.createReadStream(videoPath),
},
```

But it's not working. Any idea?

**Comment by dylanh724** [comment]
This really not intuitive -- is there a reason why this doesn't work? I encountered the same issue.

```
var formData {
  thisWorksFine: "foo",
  doesntWorkWithAwfulErrCatching: {
    ping: "pong"
  }
};
```
The error is **"TypeError: source.on is not a function"**

I searched for hours to find this was the reason D:

**Comment by bobby-brennan** [comment]
The `custom_file` example [in the documentation](https://github.com/request/request#multipartform-data-multipart-form-uploads) implies that this should work. Would suggest removing that example from the README if this is no longer supported.

**Comment by lushang** [comment]
This does work, but if you pass a JSON into the formData, you shoud `stringify` it:

``` javascript
var fs      = require('fs');
var request = require('request');
var file    = './test/assets/test.pdf';

var jsonData = {
  name: 'joe bob',
  address_1: '123 main st',
  ...
}
var opts = {
  url: 'my_service',
  method: 'POST',
  auth: { user: 'username', password: 'password' },
  json: true,
  formData: {
    front: fs.createReadStream(file),
    to: {
      value : JSON.stringify(jsonData),
      options : {
        contentType: 'application/json'
      }
    }
  }
};

request(opts, function(err, resp, body) {
  console.log(err, body);
});
```
