### ISSUE TITLE
redefined headers in form

### ISSUE THREAD

**Issue by ponyspy** [request/request#1499]
``` js
var opts = {
    'url': 'http://example.net,
    'method': 'PUT',
    'form': form_data,
    'headers': {
        'Content-Type': 'application/atom+xml;type=entry'
    },
}

request(opts, function(err, res, body) {
    ...
});
```

"headers" option does not redefined form prototype, form set default header:
Content-Type: application/x-www-form-urlencoded

**Comment by simov** [comment]
Yes, we have a test for that, so it's expected behavior, and most probably part of the specification (I haven't searched for it)

You can submit a PR with a test and a fix for it :+1:
