### ISSUE TITLE
Cookies lost during multiple redirects

### ISSUE THREAD

**Issue by nijikokun** [request/request#1502]
1. Put a cookie on a 302
2. Do another 302
3. View headers, cookie from the first 302 does not exist.

**Comment by lalitkapoor** [comment]
Hey Niji, can you give me more details. What were the domains and protocols of the redirects? Thanks.

**Comment by lalitkapoor** [comment]
Hey @Nijikokun can you give me more details. What were the domains and protocols of the redirects? Thanks.

**Comment by Nijikokun** [comment]
Can't give the domains as they are internal, should work with any, https.

Cookie type was: `http-only; secure`

**Comment by lalitkapoor** [comment]
thanks! Will look into it. If it's not too much trouble could you create a failing test?

**Comment by anklos** [comment]
I tried with node `https` module, it does not preserve cookie from first redirect either.

**Comment by lalitkapoor** [comment]
@anklos you could set request to not follow redirects and do the redirect manually, in which case you could get the first response.

**Comment by anklos** [comment]
@lalitkapoor thanks. I set `followRedirect` to false in the option. It seems that I could reach the first response, as the statusCode is 302, however, the header is the same as after redirects response's header, it does not contain `set-cookie` content from the first redirect.

![image](https://cloud.githubusercontent.com/assets/530145/6777142/bab3d244-d19a-11e4-9c15-4cbc9af23316.png)

**Comment by Nijikokun** [comment]
Cookies are not passed with redirects

**Comment by lalitkapoor** [comment]
@anklos can you tell me if the domains are different?

**Comment by lalitkapoor** [comment]
I don't need the exact domains, just need to know if they're the same...if one is a subdomain, etc.

**Comment by anklos** [comment]
they are on the same subdomain.

**Comment by lalitkapoor** [comment]
@anklos are you able to modify the cookie on the servers? or do you not have access to do that. I'd like to try something: setting the domain value on the cookie to the hostname (w/subdomain).

@Nijikokun do your cookies have the domain value set on them?

**Comment by anklos** [comment]
@lalitkapoor no I dont. but I can try to set up a https server myself to test the cookie behavior.

**Comment by anklos** [comment]
although still not make sense to me why browser could get the cookies but not my node.js program?

**Comment by anklos** [comment]
Just find that I can get `set-cookie` by setting redirect option false. Originally I did not get it because I send request to the first redirect url, not the destination url. 

Also tried other language http libraries to do the same test, the results are the same as nodejs

**Comment by lalitkapoor** [comment]
@Nijikokun does the above satisfy the concern?

**Comment by Nijikokun** [comment]
For me yes

**Comment by jazarja** [comment]
Having similiar problem with redirection cookie, I use the following code to extract cookie on first redirection:

```javascript
var httpreq = {
                    ...
                    jar: cookieJar
                };

               

request(httpreq, function (error, response, body) {                   
                    if (typeof response.headers["set-cookie"]!='undefined') {
                        response.headers["set-cookie"].forEach(function(aCookie)
                        {
                            cookieJar.getCookieString(aCookie);
                        });
                    }
});
```

**Comment by Freyert** [comment]
I seem to be having this issue on 2.61.

1. I pick up a cookie from my original request.
2. Head to the endpoint in the same domain which starts a chain of redirects.
3. During the automatically followed redirects no cookies are ever used.

When I turn on `NODE_DEBUG=request`, I see this pattern on all redirects:
```
REQUEST redirect <url>
REQUEST redirect to <url>
REQUEST {}
```

I imagine that the third log output should have my cookies in them.

**Comment by lalitkapoor** [comment]
@Freyert Thanks for the details. I'm traveling this week, but will be able to look at it this weekend, please feel free to remind me.

**Comment by Freyert** [comment]
@lalitkapoor Thanks! I'll keep taking notes as I explore.

**Comment by Freyert** [comment]
As an extra note:

It seems odd that the third `debug` statement should be empty on redirects. At a minimum I would expect it to contain `followAllRedirects`.

**Comment by leonardean** [comment]
Hi @lalitkapoor, I have a very similar issue when dealing with requests that contains redirection in response. I have set `followRedirect ` to `false` btw. below is the difference of calling the API using Postman when testing and using Request:

when testing in Postman
===
![yb j_ a 0c 9ev rrap88 8](https://cloud.githubusercontent.com/assets/2738010/12032106/7e551384-ae4f-11e5-9450-b6e09b82ce23.jpg)

when using Request
===
so I use this code to do the request:
~~~javascript
var request = require("request");
require('request-debug')(request);

var options = { method: 'POST',
  url: 'something hidden',
  qs: 
   { 
      //something hidden
    },
  followRedirect: false,
  jar: true,
  headers: 
   { 'postman-token': '48a42acc-3fa4-3c3e-e826-34e6deb26b09',
     'cache-control': 'no-cache',
     host: 'hidden again',
     referer: 'hidden, sorry' } };

request(options, function (error, response, body) {
  if (error) throw new Error(error);

  console.log(body);
  console.log(response.headers)
});
~~~
and the console log of `response.header` only shows this:
```
{ server: 'Cowboy',
  connection: 'close',
  date: 'Tue, 29 Dec 2015 08:59:07 GMT',
  status: '302 Found',
  'x-frame-options': 'SAMEORIGIN',
  'x-xss-protection': '1; mode=block',
  'x-content-type-options': 'nosniff',
  location: 'https://developer.kii.com/',
  'content-type': 'text/html; charset=utf-8',
  'cache-control': 'no-cache',
  'x-request-id': '255fb857-95fa-4aea-8f9e-17036f166083',
  'x-runtime': '0.009318',
  'strict-transport-security': 'max-age=31536000',
  via: '1.1 vegur' }
```
so you see, the `set-cookie` header is missing somewhere. May I know your suggestion. If you need any more info, please let me know

**Comment by jeffreyleeon** [comment]
+1

**Comment by patricknn** [comment]
+1, once the website that I need to access blocks the connection once you don't have the cookies from the redirect, I can't access :(

**Comment by lalitkapoor** [comment]
@leonardean @jeffreyleeon @patricknn Can you look at `tests/test-redirect.js` and create a failing scenario?

**Comment by bryonbean** [comment]
+1

**Comment by MartinGao** [comment]
+1

**Comment by akaNightmare** [comment]
+1

**Comment by Shiggiddie** [comment]
+1, from my investigations, this is only relevant when a `request.jar()` object is passed in for the `jar` attribute in the request options object.

**Comment by SerjoPepper** [comment]
+1

**Comment by RayBB** [comment]
Has anyone found a  fix or workaround for this yet? It still seems to be an issue.

**Comment by jeremyml** [comment]
+1

**Comment by verog** [comment]
+1

**Comment by melassa** [comment]
+1

**Comment by bnned** [comment]
+1

**Comment by Kelvne** [comment]
+1

**Comment by ceremcem** [comment]
+1 (set-cookie is missing in the response headers)

**Comment by rahulbir** [comment]
+1

**Comment by rodw** [comment]
+1 - this seems to be a problem with other headers (e.g., `authorization`) as well.

Is the only current workaround to set `followRedirects` to `false` and handle the redirects "manually" ?

**Comment by melassa** [comment]
AFAIK yes

**Comment by ezzygemini** [comment]
+1

**Comment by illumimari** [comment]
+1

**Comment by avadhpatel** [comment]
I found a workaround by using `.on('redirect', function() {})` event handler on your request object. Use it to copy the cookie jar and save it for later.  Its much easier than handling all the redirects manually.

**Comment by jmmclean** [comment]
@avadhpatel can you add some psuedocode on how you would handle the callback?

**Comment by avadhpatel** [comment]
Sure:

```
request.get('http://google.com/')
   .on('redirect', function() {
       // collect the cookies from 'this' object.
    });
```

**Comment by jmmclean** [comment]
@avadhpatel yea, that doesn't work too well because to follow redirects, you should be stripping out the 'set-cookie' header in the response headers. As you can see in your example, there is no object passed to the callback. I don't think the 'this' object is referring to the response....seems weird to me.

**Comment by avadhpatel** [comment]
@jmmclean 'this' object in the function is actually the request object. 

The `this.response` refer to the response that has 'set-cookie' header set. I copy my cookies from that.

**Comment by delijati** [comment]
A 2 year old comment from @jazarja worded for me.

**Comment by saknarak** [comment]
+1

**Comment by ccgagnon** [comment]
+1

**Comment by drcrack** [comment]
not fixed

**Comment by tylinux** [comment]
not fixed yet

**Comment by eliothxchan** [comment]
+1

**Comment by rocifier** [comment]
+1 I can't use postman for our cross-domain authentication because of this, it's a showstopper for me.

**Comment by parveenoodles** [comment]
I have the same issue , i didn't get all of the cookies from request module.
But as i set the jar attribute to true, then it returned me all of the Cookies.
I used **"request-promise"** module for http request.
Below is my code:-
`  var reqOpt = {
        url: url,
        method: 'GET',
        timeout: 20000,
        qs: { 'token': token },
        form: null,
        jar: true,
        headers: {
            'User-Agent': 'Request-Promise'
        },
        resolveWithFullResponse: true
    }`

As you can see i have set 

> jar : true

and it worked for me.
Hope this will help.

**Comment by Kamikadze4GAME** [comment]
+1

**Comment by Royalgamer06** [comment]
Can I make a suggestion? Why not return an array of responses when using `followRedirect: true` or `followAllRedirects: true`. The array contains the responses of each redirect. This way, we can access all intermediate headers (including cookies).

**Comment by AshokChava** [comment]
I have multiple redirects in my case (not just one redirect, there are 3 redirects happen when I access a URL). I have tried all the suggestions above, but without success. Can anyone share manual handling of redirects code and retrieving the cookies? Thanks.

**Comment by jonmifsud** [comment]
@lalitkapoor was this ever tackled? And is it being worked on?

I think this looks similar to what's being done with the authorization header in line 72 for 401 redirects. Haven't done too much nodejs patching; but would be happy to send up a PR if I manage to fix it.

**Comment by lalitkapoor** [comment]
@jonmifsud Hi! I would gladly accept a PR for this. Looking forward to it.

**Comment by esco** [comment]
@jonmifsud  👍 using `request.jar()` result instead of `true` works for me, thanks!

**Comment by ofekp** [comment]
@AshokChava I can suggest to you:
* Set `maxRedirects: 0` in the options
* Then use `try` `catch(error)` to catch the redirect (I use` await` so try catch is my way to go)
* Each time you can get the cookie/s from the redirect using `error.response.headers['set-cookie']`
* You then add this to next request header using `'Cookie': error.response.headers['set-cookie']`
Might need to do that last one multiple times for each 🍪.

It is far from perfect but it worked for me. I hope this helps someone.

**Comment by alzubaidi** [comment]
As proposed above, can use 'redirect' event.
```
  const cookiesJar = request.jar();

  request(options)
  .on('redirect', function() {
    this.jar(cookiesJar);
  })
```
