### ISSUE TITLE
Accept nested objects as form data

### ISSUE THREAD

**Issue by binarykitchen** [request/request#1503]
Currently I cannot do something like this

```coffee
      request(
        method: 'post'
        uri:    "xxx"
        json: false
        form:
          groupName: 'Test Distributor'
          partyBillings:
            0:
              defaultCurrency: 'NZD'
          primaryPostalAddress:
            address1:   'Test Address 1'
            city:       'Test City'
            countryGeo: 'NZ'
        , (err, data) ->
          ...
      )
```

but when I change the form part to this:

```coffee
        form:
          'groupName': 'Test Distributor'
          'partyBillings.defaultCurrency':   'NZD'
          'primaryPostalAddress.address1':   'Test Address 1'
          'primaryPostalAddress.city':       'Test City'
          'primaryPostalAddress.countryGeo': 'NZ'
```

then it works. Do you think this package could become a bit smarter and turn nested objects into plain arrays when necessary?

**Comment by sim642** [comment]
If you really need to pass nested objects why not just JSON.stringify it and send that?

HTTP has no default notion of such nested objects so I don't know why the way you described would be preferred to any other possible way (e.g. JSON-ing), so why should request implement your way not any other one? Also the flattening of a nested object like that isn't too efficient for any larger object so it barely generalizes.

**Comment by binarykitchen** [comment]
you are right, this was rather a dumb question of mine ;) thanks for the clarification!
