### ISSUE TITLE
Node 0.12 keep-alive?

### ISSUE THREAD

**Issue by aseemk** [request/request#1514]
Hey folks,

Node 0.12 (and presumably io.js, but I'm less familiar there) added `keepAlive` and `keepAliveMsecs` options to the native `http.request`:

https://nodejs.org/api/http.html#http_http_request_options_callback

Is there a way to specify or set those options with Request? If not, what's the recommendation with Node 0.12 in general?

Thanks!

**Comment by aseemk** [comment]
Just checking again if any work is needed for Request to support native Node 0.12 Keep-Alive. Thanks!

**Comment by aseemk** [comment]
Okay, looks like the docs are extremely misleading there, and those options are actually for the `http.Agent` constructor! The docs have been fixed in io.js.

https://iojs.org/api/http.html#http_http_request_options_callback
https://iojs.org/api/http.html#http_class_http_agent

See <https://github.com/nodejs/io.js/issues/1300>.

So I think no new work is needed here, but feel free to re-open if I'm wrong.

**Comment by lalitkapoor** [comment]
thanks for keep this updated @aseemk
