### ISSUE TITLE
Get request.post content from response

### ISSUE THREAD

**Issue by 2128** [request/request#1519]
Hello. I am using a for loop to send 100 requests to another server. Some of them return errors but I cannot identify which client ID got problem. How can I print the client ID in the "Error log"?

I tried to print *row['push']* in the "Error log" but it always showing the last item in *row* array..I can't figure a way to identify the client ID in the *response* object..

Thanks

```js
for( var i in tokens ) {
	var row = JSON.parse( tokens[i] );
	request.post(
		URL_HERE,
		{
			json:{
				"clientId": row['push']
			}
		}, function (error, response, body) {
			if ( !error && response.statusCode == 200) {
				console.log( body );
			} else {
				// How can I identify the client ID in the 100 logs inside console?
				console.log( error );
			}
		}
	);
}
```

**Comment by simov** [comment]
Hi, @2128, use https://github.com/caolan/async#each. Any HTTP request is asynchronous operation, where the for loop is synchronous.
