### ISSUE TITLE
reading cookies from jar

### ISSUE THREAD

**Issue by cauburtin** [request/request#1523]
I've the following jar:

	{ _jar: 
	   { store: 
	      { idx: { 'stackoverflow.com': 
		 { '/': 
		    { prov: Cookie="prov=ba733743-f457-41c5-9a32-d4027d46ff12; Expires=Fri, 01 Jan 2055 00:00:00 GMT; Domain=stackoverflow.com; Path=/; HttpOnly; hostOnly=false; aAge=438ms; cAge=2807ms",
		      gauth: Cookie="gauth=GGWFaQWKueJQl8eTMAzNpsygAhDcIt18FAmBtIMJnwxk2Ziras5E2a7wgPPeyBKJrEIkLRF3Zy+Suchjxfvc2sxKKSIWDelA6gBfd+dU9yFDRi4IJkVsTuWbU3tXK5Qbpi5/Ar+/4vDaRFbFNo11CuMaBnal/7jorJtE8b0qM2n0P+8Wib420i9jcAI/fiviAu9U+kxBLXRTnxeSp4SsPMqkplU+DoIFl4b3w9Gp9x0zEsl2276LpEwHCpuiHcAw8Upp04j2n1/g5pBRf1grF89fUnIDM9Hn3/qBSnslnDg=:/ZAcVQAAAADdVRGsMJmT4g==; Expires=Thu, 02 Apr 2015 00:59:45 GMT; Domain=stackoverflow.com; Path=/; hostOnly=false; aAge=438ms; cAge=1824ms",
		      usr: Cookie="usr=t=V2mW6MD0a064&s=NNcW4QZ5W0Gk; Expires=Fri, 02 Oct 2015 00:44:45 GMT; Domain=stackoverflow.com; Path=/; HttpOnly; hostOnly=false; aAge=438ms; cAge=1824ms",
		      acct: Cookie="acct=t=%2fD934TKvgMqP1ttEiY0UXs301ezsAqfz&s=2tZiD7DNJYo0EFCsvHzbgpkOzO1Dv0kE; Expires=Fri, 02 Oct 2015 00:44:45 GMT; Domain=stackoverflow.com; Path=/; HttpOnly; hostOnly=false; aAge=438ms; cAge=1824ms" } },
		'chat.stackoverflow.com': 
		 { '/': 
		    { csr: Cookie="csr=t=atC7xlUMrEaN; Expires=Fri, 02 Oct 2015 00:44:45 GMT; Path=/; HttpOnly; hostOnly=true; aAge=438ms; cAge=1329ms",
		      '.ASPXBrowserOverride': Cookie=".ASPXBrowserOverride=; Expires=Wed, 01 Apr 2015 00:44:46 GMT; Path=/; hostOnly=true; aAge=2ms; cAge=2ms" } } } } } }

I've tried

	j.getCookieString('stackoverflow.com')
	j.getCookieString('stackoverflow.com/')
	j.getCookies('stackoverflow.com')
	j.getCookies('stackoverflow.com/')

They return empty string and empty arrays respectively, what's wrong?

**Comment by cauburtin** [comment]
![pic](http://i.imgur.com/dWay9Qw.png?1)

**Comment by lalitkapoor** [comment]
@cauburtin please take a look here for examples - https://github.com/request/request/blob/master/tests/test-cookies.js It looks like you might be forgetting the protocol.

**Comment by cauburtin** [comment]
Yes indeed,  `j.getCookies('http://stackoverflow.com')`, `j.getCookieString('http://stackoverflow.com')` works, thanks
