### ISSUE TITLE
request.post fails in 2.54

### ISSUE THREAD

**Issue by rehia** [request/request#1526]
Actually, this fails in 2.54 version:
```javascript
var post = require('request').post;
post('http://localhost:3000', {body: 'param=true'});
```
I get this issue
```bash
TypeError: undefined is not a function
    at request.(anonymous function) (/Users/jerome/AffilyOne/dev/api/node_modules/request/index.js:64:16)
```

It appears that this commit fixes the issue https://github.com/request/request/commit/c43477eb0484c328d9734ad1809a4a2ff18615d3.
Is it possible to get it in a 2.54.n version ?

**Comment by simov** [comment]
2.55 with the fix is coming very soon

**Comment by simov** [comment]
2.55 is published on NPM
