### ISSUE TITLE
response.request.redirects gone in 2.54.0

### ISSUE THREAD

**Issue by Janpot** [request/request#1534]
this used to return the redirect chain in `<2.54.0`

``` js
var request = require('request');
request.get('https://google.com', function (err, res) {
  if (err) return console.error(err.stack);
  console.log(res.request.redirects);
});
```

since `2.54.0` it is `undefined`.

**Comment by froatsnook** [comment]
It looks like this happened in 604c0ab0b822300a2cc9ae3341dd36aa7d37732d.  You'll find it now in `res.request._redirect.redirects`.  Pinging @simov

**Comment by simov** [comment]
Good call @froatsnook that might be the case. All variables related to the redirect logic are now scoped under their own namespace, which happens to be the `_redirect`  variable on the request object.

**Comment by Janpot** [comment]
`<rant>`
I hate to be this guy but it's the third time in a few months that request breaks a project for me on a minor version change ([#1210](https://github.com/request/request/issues/1210) and [#1054](https://github.com/request/request/issues/1054)). If you're now saying I should use a private member, how do I know it's not going to break in the future? I mean, I love how active this project is at the moment but I kind of expected the versioning to be semantic.
`</rant>`

Anyway, @simov, my question is: will this be the official way to retrieve the redirect chain or will the old way be restored?

**Comment by simov** [comment]
@Janpot the redirect logic is going to be accessed via the `_redirect` property for the forseeable future.

Here are a few things to note:
- The `redirects` property is not documented anywhere in the readme, because it's not a public API.

- If you take a look at the tests we don't have that `request.redirects` behavior documented there. In other words that was purely a refactoring.

- Having tests in your app about using undocumented dependency code and stricter dependency version is a good idea too, but I'm pretty sure you already have that.

**Comment by Janpot** [comment]
* when both members with and without underscores exist, I don't think it's that far fetched from me to think one is public and one is private API, and I don't think it's that strange that I don't always double check this with the docs.

* My tests only cover what happens inside my app, I mock the responses. I assume a public API is covered by the tests of its own module, again, I don't always go check the tests of modules I use to see whether everything I use from it is 100% covered by tests.

Anyway, you're probably right, so can this be a feature request then instead for a public (documented) API to retrieve the redirect chain of a request?

**Comment by simov** [comment]
Yes I understand the source of this confusion. For example `redirects` was without _ prefix where `_redirectsFollowed` was using it, and we still have some vars on the request object with or without _ prefix for just about everything you can imagine.

And without having tests we can't be sure what was the intent of the author or rather the collective authors of that code.

My idea was to isolate all vars specific to a smaller more meaningful chunks of code, plus right now `_redirect` is clearly a private API.

As for having a public API for that I'll have to think about it, as we don't have anything like it atm.

**Comment by reezer** [comment]
A public API would be really great, because it make the automatic redirection way more useful.

**Comment by Janpot** [comment]
FWIW, I now use something like this:

```js
var request = require('bluebird').promisifyAll(require('request'));

function getRedirectChain(url) {
  var chain = [];
  return request.headAsync({
    uri: url,
    followRedirect: function (res) {
      chain.push(urlUtil.format(res.request.uri));
      return true;
    }
  }).get(0)
    .then(function (res) {
      chain.push(urlUtil.format(res.request.uri));
      return chain;
    });
}
```
