### ISSUE TITLE
Proxying requests leaks connections when client timeouts when using the default node v0.10 Agent

### ISSUE THREAD

**Issue by hvrauhal** [request/request#1535]
Using the default Agent for proxying requests by piping leaks connections when the clients timeout. Combined with the default outgoing connection pool size of 5 this causes pool exhaustion quickly.

Reproduce with https://github.com/hvrauhal/requestjs-proxy-leaks-agents.

**Comment by jmandel** [comment]
It looks like from node >= `0.11.0`  this is no longer a problem (i.e. the test case no longer reproduces). I think we can close this issue?

**Comment by hvrauhal** [comment]
@jmandel, yes, I hope time and node releases have taken care of this issue.
