### ISSUE TITLE
regression with `request.defaults({})` since version 2.54.0

### ISSUE THREAD

**Issue by jmonster** [request/request#1537]
I just upgraded from `2.53.0` to `2.55.0` and noticed some parts of my codebase have stopped working. I've looked at the Change Log and see that `2.55.0` specifically mentions fixes here -- but unfortunately I'm seeing issues regardless.

In particular, `json: true` is not being propagated and I end up with a string rather than an object in the `body` [probably nothing is, but that's the one that stands out]. Here is an example of how my code is laid out:

```js
var Request = require('request').defaults({
  'gzip':       true,
  'json':       true
});
```

```js
function _request(method, extraOpts) {
  var request = Request.defaults({
    foo: 'bar'
  });

  return Promise.promisify(request[method])('https://foo.bar', extraOpts);
}
```

As is, this fails to include the defaults specified above:
```js
_request('get');
```

But if I explicitly specify it again things come back all JSONy:
```js
_request('get', {json: true});
```

Request v0.53.0 works :v:

**Comment by simov** [comment]
@jmonster fixed here https://github.com/request/request/pull/1540 can you give it a try?
