### ISSUE TITLE
Posting Arrays in Form

### ISSUE THREAD

**Issue by pon** [request/request#1538]
I am attempting to consume an API and am unable to make the following request: 
```bash
curl https://api.stripe.com/v1/customers/{id}/bank_accounts/{id}/verify \
   -d amounts[]=14 \
   -d amounts[]=26
```

The below code doesn't work because having two keys of the same name the second overwrites the first. Is this type of request supported here? 
```javascript
request({
  method: 'POST',
  url: '...',
  form: {
    'amounts[]': 14,
    'amounts[]': 26
  }
})
```

**Comment by froatsnook** [comment]
Since `form` in your example is a regular javascript object, you can't have two of the same key.  Instead you should make `amounts` itself an array, like:

```js
request({
  method: 'POST',
  url: '...',
  form: {
    'amounts': [14, 26]
  }
})
```

That will make `amounts[0]=41&amounts[1]=26`.  If you need `amounts[]=41&amounts[]=26`, then use `qsStringifyOptions` like so:

```js
request({
  method: 'POST',
  url: '...',
  form: {
    'amounts': [14, 26]
  },
  qsStringifyOptions: { arrayFormat: 'brackets' }
})
```

**Comment by pon** [comment]
Thanks! I misread the documentation - I thought that only applied to the query string
