### ISSUE TITLE
request.js can't seem to handle many levels of subdomains (3+)

### ISSUE THREAD

**Issue by hayksaakian** [request/request#1545]
I get non-stop 404's using request.js with this url:

http://xjudge-judyx.api.channel.livestream.com/2.0/widgetinfo.json?cachebuster=1429393784212

but when i use node's http.get, it just works and I only get 404s when I should (invalid names, bad endpoints, etc.)

I don't get unexpected 404s on any other endpoints.

I suspect that this might have to do with all those sub-domains but that's entirely conjecture.

**Comment by simov** [comment]
You need to supply this `host` header manually

```js
request({
  uri: 'http://xjudge-judyx.api.channel.livestream.com/2.0/widgetinfo.json',
  headers: {Host:'xjudge-judyx.api.channel.livestream.com'}
}, function (err, res, body) {})
```

request sets the header names in lower case which is allowed per RFC spec. Apparently this server doesn't allow lower cased header names.

**Comment by hayksaakian** [comment]
Oh that's odd, so you're saying livestream's servers are not following the RFC spec, so I need to work around it by explicitly specifying a Host header.

**Comment by simov** [comment]
Yes, this isn't going to be changed in request. You can use [url.parse](https://nodejs.org/api/url.html) to parse your url beforehand and pass the host name to the host header.
