### ISSUE TITLE
See the whole raw request/response message like "verbose" mode.

### ISSUE THREAD

**Issue by CMCDragonkai** [request/request#1546]
Is there a way to acquire the full request and response raw HTTP message that is sent and retrieved, similar to how httpie has --verbose mode?

**Comment by Ratnesh-Github** [comment]
var request1 = require('request'); 
require('request-debug')(request1);

If you are willing to use request-debug module.

**Comment by monolithed** [comment]
`request-debug` is not the same as required, it more like `NODE_DEBUG=request `
