### ISSUE TITLE
https proxy tunnelling not working

### ISSUE THREAD

**Issue by mdamien** [request/request#1548]
When using an `https://` proxy with `request`, it gives me this error:

    Error: tunneling socket could not be established, cause=139879276619648:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:s23_clnt.c:795:

But there is no problem with the proxy if I use the `http:///`protocol when defining the proxy.

I had the same problem with python `urllib` making the same error but not `urllib2` and python `requests`. I'm gonna look at their code to see how they handle it compared to you.

Only thing, you can't reproduce it if you're not in my network I think. But you can try:

       export https_proxy="https://proxyweb.utc.fr:3128" => fail with any request
       export https_proxy="http://proxyweb.utc.fr:3128" => ok with any request

(gonna remove them later)

So, if you have a way for me to do dump a whole stacktrace and everything that can help you, you can tell me

For now, just filing an issue. :smile:

**Comment by simov** [comment]
Hi, @mdamien, a code to reproduce this bug will definitely help.

**Comment by mdamien** [comment]
Of course, I would need to setup the proxy exactly as the one I have the problem with.

I'm gonna dump a wireshark capture stream comparing the same request with urlib,urlib2,requests and request, it would help maybe.

**Comment by mdamien** [comment]
You can close the issue for now, I don't have much time to do the analysis at the moment
