### ISSUE TITLE
Array is sent as object?

### ISSUE THREAD

**Issue by irfaan** [request/request#1550]
Not entirely sure that this is the fault of the request module, but it has been suggested that request is passing an array ```['some_state']``` (as an object parameter's value) to an object itself ```{\"0\":\"some_state\"}```.

Relevant discussion: https://github.com/wit-ai/node-wit/issues/7
Relevant code:
```js
// Params
    var options = {
        context: {
            state: ['some_state']
        }
    }

    var query_params = _.extend({'q': text}, options);

// Request options
    var request_options = {
        url: 'https://api.wit.ai/message',
        qs: query_params,
        json: true,
        headers: getHeaders(access_token)
    };

// Make the request
    request(request_options, function (error, response, body) {
        if (response && response.statusCode != 200) {
            error = "Invalid response received from server: " + response.statusCode
        }
        callback(error, body);
    });
```

**Comment by simov** [comment]
@irfaan did you tried using the [qsStringifyOptions](https://github.com/request/request#requestoptions-callback) option? Take a look at the [arrayFormat](https://github.com/hapijs/qs#stringifying) option.

**Comment by irfaan** [comment]
@simov yes, I have (despite request defaulting to indices). Still no luck. Is there somewhere in request.js that I can check what is being sent?

**Comment by simov** [comment]
Here is what I'm seeing in my console, this is what request is doing internally
```
> qs.stringify({q: 'test', verbose: false, context: { state: [ 'some_state' ] }})
'q=test&verbose=false&context%5Bstate%5D%5B0%5D=some_state'
```

`context%5Bstate%5D%5B0%5D=some_state` is `context[state][0]=some_state`

The other available options are `context[state][]=some_state` and `context[state]=some_state`

How exactly do you expect that part to be encoded?

**Comment by irfaan** [comment]
Thanks @simov! Are you able to shed some light on this @l5t?

**Comment by irfaan** [comment]
Resolved. I hadn't JSON.stringify()'d the context object that was being sent over. No fault of request. Thanks for your help @simov.
