### ISSUE TITLE
Cookies with ; symbols

### ISSUE THREAD

**Issue by Ubitso** [request/request#1553]
I need to create request to the server with cookie value like 
```
86877e91f43b718fa15ef866f0362d815b2bb5e5a:4:{i:0;s:24:
```
problem is request splits cookie value by ;
How exactly i can send this cookie?

**Comment by lalitkapoor** [comment]
that's not a valid cookie according to the RFC 6265 Spec (notice the exclusion list in the cookie-octet:

    set-cookie-header = "Set-Cookie:" SP set-cookie-string
     set-cookie-string = cookie-pair *( ";" SP cookie-av )
     cookie-pair       = cookie-name "=" cookie-value
     cookie-name       = token
     cookie-value      = *cookie-octet / ( DQUOTE *cookie-octet DQUOTE )
     cookie-octet      = %x21 / %x23-2B / %x2D-3A / %x3C-5B / %x5D-7E
                           ; US-ASCII characters excluding CTLs,
                           ; whitespace DQUOTE, comma, semicolon,
                           ; and backslash
