### ISSUE TITLE
webservice not accepting uri notation

### ISSUE THREAD

**Issue by shotlom** [request/request#1554]
I'm querying a webservice which, for some reason works with 

```js
http.request({host:"www.myhost.com",path:"/some/path?{query:options}", method:"GET"});
````
But when I use the 

```js
var someURI = "http://www.myhost.com/some/path?{query:options}";
request(someURI) 
```

syntax, the webservice hates it and won't return any data for exactly the same request.

Is it possible to make the URI notation optional? ... apologies if this has been asked previously.

**Comment by simov** [comment]
You can try to encode it first

```js
var someURI = "http://www.myhost.com/some/path?"
  + encodeURIComponent(JSON.stringify({query:options}));
request(someURI)
```

**Comment by shotlom** [comment]
Thanks @simov, but this doesn't seem to work. 

There appears to be something going on with the specific server. I say this because other organisations have the same webservice and I can use both http.request(), and request() and they both work. However with this one agency http.request() works and request() doesn't for exactly the same call. Here are the working and not working calls.

Any help on using the request() for streaming rather than the old http.request->response  would be fantastic.

### Parameters
```
var query = {
    "function":"get_site_list",
    "version":"1",
    "params":{
        "site_list":"11000*"
    }
}

var options = {
          "host":"watermonitoring.dnrm.qld.gov.au",
          "path":"/cgi/webservice.server.pl?",
          "method":"GET"
      }


```
### Not Working
```
var request = require('request');

//Either:
1. options.path = options.path + JSON.stringify(query);
//Or
2. options.path = options.path + encodeURIComponent(JSON.stringify(query));

var uri = 'http://'+options.host + options.path;

request.get(uri)
        .pipe(process.stdout)

```

### Working

``` javascript

var http = require('http');

options.path = options.path + JSON.stringify(query);

http.request(options,function(res){
        res
        .pipe(process.stdout)
    })
    .on('error', function(err) {
        console.error('Error with the request:', err.message);
        cb(err);
    })
    .end();
```

**Comment by shotlom** [comment]
I was looking at implementing my own stream of http.request() as a fork of request(), however it looks complicated.

Maybe I've found an edge case which should be covered with request() itself.

**Comment by shotlom** [comment]
Ok so on further investigation the particular service doesn't like the encodeURI which request() appears to do internally.  

Put the following addresses into a Google Chrome address bar:

### Un-encoded Works
```javascript
http://watermonitoring.dnrm.qld.gov.au/cgi/webservice.server.pl{"function":"get_site_list","version":"1","params":{"site_list":"11000*"}}
```

### request()'s Encoded Output Doesn't Works
```javascript
http://watermonitoring.dnrm.qld.gov.au/cgi/webservice.server.pl%7B%22function%22:%22get_site_list%22,%22version%22:%221%22,%22params%22:%7B%22site_list%22:%2211000*%22%7D%7D
```

**Comment by shotlom** [comment]
Confirmed.  

If I do the following decode in request.js it works.

So the question is, how do I check for whether the webservice wants a coded or decoded path?

``` javascript
(starting at around line 960 in request.js)

// We have a method named auth, which is completely different from the http.request
  // auth option.  If we don't remove it, we're gonna have a bad time.
  var pat = self.path;
  self.path = decodeURIComponent(pat);

  var reqOptions = copy(self)
  delete reqOptions.auth
  
  console.log('self path',self.path);
  debug('make request', self.uri.href)
  self.req = self.httpModule.request(reqOptions)
```

**Comment by shotlom** [comment]
The thing is that with these webservices, if you don't get the query right, it doesn't return an error. It returns a valid html document telling you how to access the webservice & wsdl.

So what's the best way to handle this edge case? Fork?

**Comment by shotlom** [comment]
rfc3986() seems to be the culprit.

**Comment by simov** [comment]
Thanks for the thorough bug report.

Request uses the standard [url](https://nodejs.org/api/url.html) module to parse the url, but you can pass your own pre-parsed object

```js
var request = require('request')
var url = require('url')

var query = {function:'get_site_list', version:1, params:{site_list:'11000*'}}
var uri = url.parse('http://watermonitoring.dnrm.qld.gov.au/cgi/webservice.server.pl?' 
  + JSON.stringify(query))
uri.path = decodeURIComponent(uri.path)

request({
  uri: uri
}, function (err, res, body) {})
```

```
{"buff_required": 351, "buff_supplied": 50000, "error_num": 0, "_return": {"sites": ["11000056A", "11000060A", "11000062A", "11000064A", "11000066A", "11000068A", "11000104A", "11000138A", "11000146A", "11000147A", "11000148A", "110001A", "110001B", "110001C", "110001D", "110002A", "110003A", "110004A", "110004B", "110005A", "110006A", "110006B", "110006C", "110007A", "110009A"]}};
```

No idea if that's the correct result, but at least it's not HTML :)

**Comment by shotlom** [comment]
@simov - that's the correct result. 

Brilliant. The pre-parsed option seems to work. I'll close this one. 

Thanks - much appreciated.
