### ISSUE TITLE
Error handling - if statements should change in examples

### ISSUE THREAD

**Issue by nicely** [request/request#1556]
Hi ,because of the response timeout  sometimes response can undefined and we gets this error;

TypeError: Cannot read property
'statusCode' of undefined at Request._callback

because of this if statements should change like this;
```if (!response (error && response.statusCode != 200)) console.log("Error")```

after that there is no problem

**Comment by simov** [comment]
Where is this code, can you give us the exact line?

**Comment by nicely** [comment]
Ah okay , there is no problem i dont know that "error" controls response is undefined or not. So we do not need to control !response
