### ISSUE TITLE
How do I set a socket timeout without setting a request lifetime timeout?

### ISSUE THREAD

**Issue by jeffcharles** [request/request#1559]
When I set the timeout option, I notice that the timeout can trigger before the the socket is opened. Looking at the code, it looks like a `setTimeout` is used before the request is opened. This is a problem for a project of mine since I want to launch concurrent requests but only apply a timeout to the opened socket and not to the entire lifetime of the request (e.g., I don't want to time out waiting for a connection in the connection pool to become available). How can I set a timeout on the socket without enforcing a timeout on the entire request lifetime?

**Comment by evanderkoogh** [comment]
You can not do that @jeffcharles. Not sure if this is still a problem, but it was for me as well. I have submitted a PR to move the setup of the timeout code to the 'socket' event of the underlying request. Which gets us the behaviour we want (and is documented).

PR: https://github.com/request/request/pull/1984
