### ISSUE TITLE
formData: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by IGZangelsanchez** [request/request#1561]
Hey guys,

We are using your library in a project which sends a multipart body with an array of recipients.
If the number of recipients is higher than 500 aprox, an exception is thrown. Check it out:

``` js
var request = require('request');

var array = [];
for (var i = 0; i < 500; i++) {
    array.push('data-' + i);
}

var data = {
    'array' : array
};

request.post({
  url: 'http://localhost:3000/example',
  formData: data
}, function (err, response, body) {
    if (err) console.error(err);
    console.log('All done.');
});
```

This returns the following error: `RangeError: Maximum call stack size exceeded`

We have been debugging the code and we think that the problem comes from  `request.js` lin. `509`:

``` js
   var appendFormValue = function (key, value) {
      if (value.hasOwnProperty('value') && value.hasOwnProperty('options')) {
        requestForm.append(key, value.value, value.options)
      } else {
        requestForm.append(key, value)
      }
    }
    for (var formKey in formData) {
      if (formData.hasOwnProperty(formKey)) {
        var formValue = formData[formKey]
        if (formValue instanceof Array) {
          for (var j = 0; j < formValue.length; j++) {
            appendFormValue(formKey, formValue[j])
          }
        } else {
          appendFormValue(formKey, formValue)
        }
      }
    }
```

If you have any doubt, do not hesitate to let us know.
Thanks in advance :)

**Comment by simov** [comment]
I'm not sure about the internals of the [form-data](https://github.com/felixge/node-form-data) module, but you can build the multipart body by yourself. Just use the more generic multipart API

```js
request.post('https://', {
  headers: {'content-type':'multipart/form-data'},
  multipart: [
    {
      'content-disposition': 'form-data name="[FIELD_NAME]"',
      'content-type': 'text/plain',
      body: '[VALUE]'
    }
  ]
}, function (err, res, body) {})
```

Use [request-debug](https://github.com/request/request-debug) with one or two form-data values to better understand what exactly you need to send in your case. Then just loop through all of your recipients.

**Comment by guumaster** [comment]
@simov what you are suggesting is a good workaround. But, the problem seems to be the recursive calls of `appendFormValue` ([line 520-521](https://github.com/request/request/blob/d79ce9704d76a9801d2697dafb8212d82f4bbc8b/request.js#L520-L522)) when the array is too long.
 Maybe there is a better solution than changing the format of the multipart depending on the length of the object to be sent.

**Comment by simov** [comment]
@guumaster I'm not seeing a recursion there, this loop iterates over all of the values inside the array and passes each value separately to the [form-data](https://github.com/felixge/node-form-data) module (because that's how it expects to receive the data).

form-data have some additional magic in it that may cause that overhead I guess, where the multipart API in request is a more generic one, but it also checks for the data type of the passed value, so it can opt out from using streams if that's not explicitly specified and not needed - in short I guess that makes it a lighter solution in such cases when you have huge amount of multipart values.

**Comment by guumaster** [comment]
@simov The recursion is clear, the function is declared in [line 509](https://github.com/request/request/blob/d79ce9704d76a9801d2697dafb8212d82f4bbc8b/request.js#L509) and its called inside itself in lines [521](https://github.com/request/request/blob/d79ce9704d76a9801d2697dafb8212d82f4bbc8b/request.js#L521) and [524](https://github.com/request/request/blob/d79ce9704d76a9801d2697dafb8212d82f4bbc8b/request.js#L524).

**Comment by simov** [comment]
Nope `appendFormValue` is defined before the `for` loop, so the `for` loop calls it outside of it.

One more thing to add to my previous comment - the multipart/form-data type is a specific multipart sub type. Multipart itself can contain anything, that's why you can build it through the `multipart` option and it will be perfectly valid.

**Comment by guumaster** [comment]
@simov oh, you are right. Totally my bad. I've read it with my bad eye, sorry! :laughing:

**Comment by simov** [comment]
@alexindigo @DylanPiercey I thought you may be interested in this one.

**Comment by harryi3t** [comment]
@simov [The line 528](https://github.com/request/request/blob/master/request.js#L528) is throwing the error

```js
self._form.pipe(self)
```

If I put a `try-catch` block around it and return the error in the `options.callback`, it fixes the issue
```js
try {
  self._form.pipe(self)
} catch (err) {
  if (options.callback) {
    return options.callback(err)
  }
}
```
Is this the right fix?

**Comment by harryi3t** [comment]
I am facing the same issue for large form-data sizes (around 2-3k)
The [following line](https://github.com/request/request/blob/master/request.js#L528) throws exception
```js
// Request.js#528
self._form.pipe(self) // Throws RangeError: Maximum call stack size exceeded
```
`self._form` is an instance of [form-data](https://www.npmjs.com/package/form-data), which uses the module [combined-stream](https://www.npmjs.com/package/combined-stream) to make itself streamable.

`combined-stream` is [using recursion](https://github.com/felixge/node-combined-stream/blob/master/lib/combined_stream.js#L68) to continuously write data which causes this exception


@simov I am not sure where the fix should go.
Wrapping the above line in `try-catch` works (Again, not sure if this is the right fix)

```js
try {
  self._form.pipe(self)
} catch (err) {
  if (options.callback) {
    return options.callback(err) // Bubble-up the error
  }
}
```

**Comment by mikemfleming** [comment]
I'm having the same issue as above when I attempt to upload a photo as a buffer to AWS in a multipart/form-data request and getting the following error:

```
[2018-02-09T17:44:10.296Z] INFO (35071 on xyz-Macbook.local): SENDING POST REQUEST FOR AWS UPLOAD
    file: "..."
    url: "https://s3.amazonaws.com/xyz"
    method: "POST"
_http_outgoing.js:245
function _writeRaw(data, encoding, callback) {
                  ^

RangeError: Maximum call stack size exceeded
    at ClientRequest._writeRaw (_http_outgoing.js:245:19)
    at ClientRequest._send (_http_outgoing.js:240:15)
    at write_ (_http_outgoing.js:670:15)
    at ClientRequest.write (_http_outgoing.js:620:10)
    at Request.write (xyz/node_modules/request/request.js:1501:27)
    at FormData.ondata (internal/streams/legacy.js:16:26)
    at emitOne (events.js:116:13)
    at FormData.emit (events.js:211:7)
    at FormData.CombinedStream.write (xyz/node_modules/combined-stream/lib/combined_stream.js:118:8)
    at FormData.CombinedStream._pipeNext (xyz/node_modules/combined-stream/lib/combined_stream.js:106:8)
    at FormData.CombinedStream._getNext (xyz/node_modules/combined-stream/lib/combined_stream.js:79:10)
    at FormData.CombinedStream._pipeNext (xyz/node_modules/combined-stream/lib/combined_stream.js:107:8)
    at FormData.<anonymous> (xyz/node_modules/combined-stream/lib/combined_stream.js:91:10)
    at FormData.<anonymous> (xyz/node_modules/form-data/lib/form_data.js:285:5)
    at FormData.CombinedStream._getNext (xyz/node_modules/combined-stream/lib/combined_stream.js:84:3)
    at FormData.CombinedStream._pipeNext (xyz/node_modules/combined-stream/lib/combined_stream.js:107:8)
``` 

The only solution I see at the moment is trying another request library but I'd rather not. Any suggestions?

my versions:
request: "^2.83.0"
node: v8.9.0

Thanks!

**Comment by alexindigo** [comment]
@harryi3t @mikemfleming I think I have idea how to combat that – if we wrap that recursion into async calls, it won't trigger `Maximum call stack`.

**Comment by alexindigo** [comment]
@harryi3t @michalstanko I updated combined-stream with "always async" piping. And pulled it into form-data. Please try updated form-data with your local request and see if it solves the issue for you.
Thank you.

New form-data version: form-data@2.3.2-rc1

**Comment by harryi3t** [comment]
@alexanderGugel Thanks for the fix. It does not crash anymore 👍

**Comment by alexindigo** [comment]
@harryi3t I'll publish it via proper channels. Thanks for checking.

**Comment by mikemfleming** [comment]
@alexindigo thanks! 🎉✨🚀

**Comment by alexindigo** [comment]
Still waiting for windows tests to finish :)

**Comment by alexindigo** [comment]
@harryi3t @mikemfleming @simov 
Fixed in https://github.com/request/request/pull/2871
