### ISSUE TITLE
In case of errors, can the user expect res to be defined?

### ISSUE THREAD

**Issue by oliversalzburg** [request/request#1563]
I was experiencing an issue where I was requesting a document from a server with a faulty HTTPS configuration, resulting in UNABLE_TO_VERIFY_LEAF_SIGNATURE.

In that case, the software I was using was still relying on `res` to be defined. Is that a valid assumption (meaning it's an issue with request) or isn't it (meaning it's an issue with the software I was using).

Original issue: https://github.com/Strider-CD/strider/issues/767

**Comment by simov** [comment]
How is this supposed to be a request bug, if the error is firstly thrown in strider-gitlab?

**Comment by knownasilya** [comment]
The error comes from `res` being undefined, which is the result of request. Although it seems like the error isn't being handled, so there might be an error in which case it would be a strider-gitlab issue.

**Comment by oliversalzburg** [comment]
@simov If part of the design of request was that `res` is always defined, then it would be a bug, because in this case, it isn't.

**Comment by knownasilya** [comment]
@simov this is more of a question: "Is `res` expected to always be defined, or can it be `undefined` sometimes?"

**Comment by simov** [comment]
`res` can be undefined, for example with errors that happen during initialization (like invalid url), that's why you should handle the `err` argument.
