### ISSUE TITLE
Does request uses keep-alive by default?

### ISSUE THREAD

**Issue by filipedeschamps** [request/request#1565]
I can't find this anywhere.

**Comment by mikeal** [comment]
request defaults to what node core's http client does by default so the answer is: sometimes and sort of :)

in pre-0.12 the answer is "it always sends the keep-alive header but only keeps the connection open if you've exhausted the connection pool" and post 0.12 is "yes"

**Comment by filipedeschamps** [comment]
@mikeal awesome!

Is there any way to disable it?

**Comment by mikeal** [comment]
just set the connection header to "close"

**Comment by filipedeschamps** [comment]
Perfect! Thanks :)
