### ISSUE TITLE
Response stream closing doesn't stop the request (input) stream.

### ISSUE THREAD

**Issue by tmeasday** [request/request#1566]
Reproduction: https://github.com/tmeasday/npm-request-hang, instructions contained.

Tested on 0.10.x (a few recent versions) and 0.12.2 w/ request 2.47.0 and 2.55.0.

We are streaming a request to a http server response almost verbatim like the proxy documented here: https://github.com/request/request#streaming

On AWS Ubuntu machines, if a client drops the request before it's finished, the input stream (`request.get`) never closes, eventually filling up the socket pool (with default settings on 0.12.x it never runs out but it's a leak).

**Comment by tmeasday** [comment]
Note a workaround is to do (following the doc example): 
```
http.createServer(function (req, resp) {
  if (req.url === '/doodle.png') {
    var x = request('http://mysite.com/doodle.png')
    req.pipe(x)
    var output = x.pipe(resp);
    output.on('close', function() { x.abort(); });
  }
})
```

**Comment by CodingAspect** [comment]
This one is serious. I can't believe it's not being taken care of.
+1

**Comment by herlon214** [comment]
It's happening with me too
+1

**Comment by CodingAspect** [comment]
I'd like to clarify that there's no workaround for this. The workaround above doesn't work.

**Comment by wildlyinaccurate** [comment]
I've just run into this as well. Weirdly it doesn't hang when I make a request for the same file to a local `SimpleHTTPServer`.

**Comment by r4j4h** [comment]
Can report that `.abort()` closed my request while .end(), .close(), and the like did nothing.
