### ISSUE TITLE
OAuth parameters are not refreshed following a 302 redirect

### ISSUE THREAD

**Issue by marshall007** [request/request#1573]
After following a 302 Redirect, it appears the subsequent request is signed using the same OAuth parameters as the original request.

**Comment by simov** [comment]
Is that an actual bug? Can you point us to the exact part of the RFC regarding this behavior?

**Comment by marshall007** [comment]
@simov the RFC does not outline behavior for this case specifically, but from [Section 3.3](https://tools.ietf.org/html/rfc5849#section-3.3):

> The nonce value MUST be unique across **all requests** with the same timestamp, client credentials, and token combinations.

I would assume "all requests" would include redirects. Here's a real-world example of where this becomes an issue with the Bitbucket API: [this endpoint](https://confluence.atlassian.com/display/BITBUCKET/pullrequests+Resource#pullrequestsResource-getDiffGETthediffforapullrequest) responds with a 302 and after following the redirect using the same credentials I get a 401.

**Comment by marshall007** [comment]
@simov I was working on a PR for this, do you agree it warrants a fix?

When `request.init()` is called from `Redirect.prototype.onResponse` it doesn't pass any parameters, so `self.oauth()` on [`request.js#L630`](https://github.com/request/request/blob/880d9a078665ee8d7dbda6cc26d58d7bebc2700d/request.js#L630) which would have refreshed the credentials doesn't get called. I think the solution is to either change that `if` statement to include the case where options are already set on `self._oauth` or to handle it in `Redirect.prototype.onResponse`. Do you have a preference?

**Comment by marshall007** [comment]
I also just realized that none of the OAuth params are stored on the `self._oauth` object, so it's going to be kind of tricky to "refresh" them either way.

**Comment by simov** [comment]
@marshall007 I was able to reproduce the bug and submitted a PR https://github.com/request/request/pull/1574 (I hope you don't mind)

Hopefully we're interpreting the specification correctly. I can't remember having that issue before, but I can't say if I had any redirects when making oauth requests either.

**Comment by marshall007** [comment]
@simov looks good, thanks! I'm pretty confident in our interpretation given that there are APIs in the wild that implement this behavior.
