### ISSUE TITLE
Caching / TTL

### ISSUE THREAD

**Issue by BrandonCopley** [request/request#1576]
Do ya'll currently support a TTL or cache control within request? Are there any plans to or are there NPM modules that do caching with this?

**Comment by phillipj** [comment]
No, `request` does not handle caching. There has been some opened issues about this over the years. The consensus by the authors / contributors seems to be having a separate module handle caching.

https://github.com/request/request/issues/1470 and https://github.com/request/request/issues/573 to name a few of the aforementioned issues which also links to some of the caching modules created so far.

**Comment by BrandonCopley** [comment]
That's an interesting decision. It seems very common in HTTP libraries to
include some sort of caching. A coworker of mine built this (since I asked
this question), and we've been using it, based on LRU -
https://www.npmjs.com/package/request-again

I do not know how to close the issue, but let's close it for now, since the
decision is a no caching in Request, thanks!

On Wed, May 27, 2015 at 12:22 PM, Phillip Johnsen <notifications@github.com>
wrote:

> No, request does not handle caching. There has been some opened issues
> about this over the years. The consensus by the authors / contributors
> seems to be having a separate module handle caching.
>
> #1470 <https://github.com/request/request/issues/1470> and #573
> <https://github.com/request/request/issues/573> to name a few of the
> aforementioned issues which also links to some of the caching modules
> created so far.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/request/request/issues/1576#issuecomment-106003241>.
>



-- 
[image: Giftnix]

Brandon Copley

Founder & CEO

t: 512.784.6060

e: copley.brandon@gmail.com

**Comment by phillipj** [comment]
Would agree there's certainly room for **the** cache module to use in combination with `request`. I would really appreciate any thoughts from you related to caching in my newly opened issue https://github.com/request/request/issues/1604

Thanks for linking to `request-again`!
