### ISSUE TITLE
Cannot view source on Coveralls

### ISSUE THREAD

**Issue by eugirdor** [request/request#1577]
When you try and view the source of a file on Coveralls you see the following error instead:

```
The owner of this repo needs to re-authorize with Github; their OAuth credentials are no
longer valid so the file cannot be pulled from the Github API.
```

https://coveralls.io/builds/2561958/source?filename=request.js

**Comment by simov** [comment]
@nylen can you first Revoke the access to Coveralls from here https://github.com/settings/applications and then login again here https://coveralls.io/ (you might as well delete the coveralls cookies from the Resources tab before that). And this might fix the GitHub status API reporting on the PRs.

**Comment by simov** [comment]
Actually there might some other issue with coveralls because I'm not seeing the code for my own projects either. Still the above procedure can fix the GitHub's status API at least.

**Comment by nylen** [comment]
It was working fine for me, but I remoked Coveralls access from GitHub.  I did not re-add it again, @simov I'll let you do that.  One more thing to try later would be to do "delete repo" in Coveralls - I didn't do it because then we would lose all of our build history.

**Comment by simov** [comment]
@nylen that's the thing, there is some weird logic in coveralls that you have to be the one initially added the project to be able to delete it, also your login token will be used for calls to the GitHub API, not mine, so without you re-authenticating it won't work.

**Comment by nylen** [comment]
Hmm.. want me to delete the repo from coveralls and see if that helps?

**Comment by simov** [comment]
Deleting anything sounds scary, but if that's an option, after that I can try to add it myself.

**Comment by nylen** [comment]
Well.. I tried twice, and got this ClouldFlare 504 message both times:

![screen shot 2015-05-17 at 1 43 13 pm](https://cloud.githubusercontent.com/assets/227022/7671401/7dd1e50a-fc9c-11e4-9048-56bce0ff0d23.png)

Then, the repo is still up at https://coveralls.io/r/request/request .  Looks like there are some things broken with @coveralls.

**Comment by simov** [comment]
@eugirdor currently we have two coverage badges in our readme - [codecov](https://codecov.io/github/request/request?branch=master) and [coveralls](https://coveralls.io/r/request/request) Currently coveralls file coverage for request is still broken for some reason, although it magically started to work for my personal projects, but you can see the actual file coverage in codecov. Also the GitHub's status API is finally working.

**Comment by eugirdor** [comment]
Excellent, thank you.
