### ISSUE TITLE
GET request returns malformed characters

### ISSUE THREAD

**Issue by matisoffn** [request/request#1578]
I've written the snippet below, and it returns odd/malformed/incorrect characters.  I've tried changing the encoding parameter and using iconv-lite (and Buffer), but it still continued to return bad data.

Ex:

```javascript
var api = 'https://api.stackexchange.com/2.2/questions/no-answers?order=desc&sort=activity&tagged=rails-api&site=stackoverflow';

request({url: api, json: true}, function(error, response, body) {
	if (!error && response.statusCode == 200) {
		console.log(body);
	}
});
```

**Comment by qwemaze** [comment]
Have exact same issue, any news?

**Comment by matisoffn** [comment]
Haven't found a solution yet, if I do i'll post back.

**Comment by simov** [comment]
Hi @matisoffn you have to pass the `gzip:true` option because the response from stackexchange is gziped.

**Comment by matisoffn** [comment]
Thanks!
