### ISSUE TITLE
Moving Request-Promise to the Request Org

### ISSUE THREAD

**Issue by analog-nico** [request/request#1579]
Hi Request Org maintainers!

Sorry for all other watchers. This is kinda off-topic.

@mikeal You once offered to move https://github.com/tyabonil/request-promise to the request org. If you are still up to it we would like to make the move. @tyabonil and I will continue to maintain this project. So it won't add any workload to the request org. However, with 2500 downloads/day and growing it becomes somewhat important to request itself and maybe one day an urgent bugfix due to a breaking chance is necessary - who knows - and then you all could make use of your repo access rights if we are currently sitting at the beach drinking Margaritas.

Thoughts?

Cheers,
Nico

**Comment by mikeal** [comment]
+1

**Comment by simov** [comment]
I'm fine with it too. @analog-nico I guess you can transfer the repo, personally I haven't done that before. @mikeal do we need another team for that, or the Contributors one is just fine? Currently it gives access to the request and request-debug repositories.

Also @analog-nico we have [promise tests](https://github.com/request/request/blob/master/tests/test-promise.js) so the promise support is a first class citizen in request already. I guess these covers the request-promise use cases as well, though I tested locally with es6-promise and your module as well.

**Comment by analog-nico** [comment]
Awesome @mikeal & @simov !

Indeed, the promise tests are covered by Request-Promise as well - of course adding convenience not having to promisify everything.

I just tested the transfer of a repo with two user accounts etc. **First step** is that you need to create a new team or use an existing one and add @tyabonil and @analog-nico to it. It is important that the team grants admin rights. Otherwise the transfer will fail. So it is best you create a new team so we can't screw up the other repos. ;) Once you added us to the team we will get an email so we can then take it from there.

**Comment by mikeal** [comment]
@analog-nico team created, invites sent.

**Comment by analog-nico** [comment]
Thank @mikeal ! Ty will transfer the repo shortly. AFAIK there is nothing to do for you anymore. Only activating Travis CI maybe. But I will let you know.

I just added @mikeal @nylen @simov as collaborators on NPM. Just in case if you really need to publish a fix one day. But assume this day won't come.

**Comment by tyabonil** [comment]
Initiated the transfer - should be done shortly. @mikeal @simov thanks for the invitation to be a part of request.

**Comment by analog-nico** [comment]
Move completed. All done. Thanks everyone!

Feel free to open an issue for `request/request-promise` if you have some requirements for request-promise in order to comply with certain standards of this organization or anything.

Cheers!
