### ISSUE TITLE
When `uri` option is a parsed url object, other options don't work

### ISSUE THREAD

**Issue by prolificeric** [request/request#1580]
The `jar` and `qs` properties will not work in this example:

```javascript
request({
  uri: {
    protocol: ‘http:’,
    hostname: ‘prolificinteractive.com’,
    port: 80,
    pathname: ‘/team’
  },
  qs: {
    foo: ‘bar’
  }
}, function (err, response, body) {
  // etc.
});
```

**Comment by simov** [comment]
@prolificeric most probably your parsed object is malformed. This option is intended for cases where you have your url [parsed](https://nodejs.org/api/url.html#url_url_parse_urlstr_parsequerystring_slashesdenotehost). If you have properties missing from that object it may fails to work.

**Comment by simov** [comment]
Closing @prolificeric us know if you have any other issues with this.
