### ISSUE TITLE
Global handlers

### ISSUE THREAD

**Issue by lgomez** [request/request#1590]
Hi all,

Is there a way to add a global error and response handlers? I'm using .defaults to set a number of global defaults and would like to let request handle connection errors so my code can focus on other types of errors but I'm having a hard time figuring out how to do this. Particularly because I really would like to extend request after applying some defaults to it.

Can anyone point me to where I may be able to read more about this? Perhaps an example or the section of the code I need to understand to figure this out? I've tried to go through the source but still can't figure it out.

Is it even appropriate to use `util.inherit(MyClass, request)` or `util.inherit(MyClass, request.defaults(...))`? So I can later do `myClassInstance.get()....`

Thank you!

**Comment by simov** [comment]
The `defaults` method is essentially a closure, which calls `request`. The `request` function returns a new instance of `Request`, so you can't really inherit anything useful from `request` alone. Also you can register `on` events only after your `Request` instance have been initialized, which happens after you initiate the request, not when you called the `defaults` method.

In other words - there is no global request instance, only static default options that get merged in on each request through that wrapper. The actual request class is exposed through `request.Request` if that may be of any help to you.

**Comment by lgomez** [comment]
@simov Thank you for the quick reply. That's what I suspected. Too bad. I'll look for alternatives before hacking my way around this.

**Comment by matthewdean** [comment]
:+1:

It would be extremely useful to set a response handler which would take care of retry logic such as fixing a header and then re-sending the request. Is this currently possible with `request`?

**Comment by simov** [comment]
@lgomez @matthewdean you can always do something like this

```js
function handleResponse (err, res, body) {}
function onError (err) {}
request(handleResponse).on('error', onError)
```
