### ISSUE TITLE
calling `.defaults()` a second round loses all the things

### ISSUE THREAD

**Issue by jmonster** [request/request#1592]
```js
var headers;
var Request = require('request');
var baseRequest = Request.defaults({ baseUrl: 'http://localhost:3000/' });

// 1 level of defaults
headers = baseRequest('/foo').headers;
console.log('ok?: ', headers.host === 'localhost:3000'); // true

// 2 levels of defaults
var blahRequest = baseRequest.defaults({ anything:123 });
headers = blahRequest.get('/foo').headers;
console.log('ok?: ', headers.host === 'localhost:3000'); // false
```

**Comment by simov** [comment]
@jmonster I think this issue is related to your previous bug report here https://github.com/request/request/issues/1537 unfortunately that's not published to NPM yet. Can you test out with the latest master? I'm getting

```
ok?:  true
ok?:  true
```

**Comment by jmonster** [comment]
Ah I'm sorry about that, I ran into this in an entirely different context -- I just assumed the prior change had been deployed at this point. I will follow up shortly!

**Comment by jmonster** [comment]
it's s'all good, man!

![allgoodman](https://p1cdn01.thewrap.com/images/files/2013/Jul/02/101091/main_image/breakingbadsaul.jpg)\


any chance of this being published to npm? :)

**Comment by simov** [comment]
Yep, new release is coming up in the next few days.
