### ISSUE TITLE
multipart file upload - boundry key is treated as file body

### ISSUE THREAD

**Issue by alekbarszczewski** [request/request#1594]
I am trying to upload file to Filepicker.io. Their docs say that it can be done using CURL:

```
curl -X POST -F fileUpload=@filename.txt https://www.filepicker.io/api/store/S3?key=MY_API_KEY
```

So I am trying to perform same request using request.js (`2.55.0`):

```coffeescript
options =
  url: 'https://www.filepicker.io/api/store/S3'
  preambleCRLF: true # also tried with false
  postambleCRLF: true # also tried with false
  qs: # just some filepicker-related params
    key: 'XXX'
    store: 'S3'
    mimetype: 'text/csv'
    path: key
    container: 'my-bucket'
    access: 'public'
    policy: creds.policy
    signature: creds.signature
  multipart: [
    {
      body: "content"
    }
  ]
  method: 'post'

request options, (err, res, body) ->
  # 200 OK
```

And it generally works, however contents of uploaded file look as follows:

```

--5de8c03d-200f-4406-a54a-a4078fb441c2

content
--5de8c03d-200f-4406-a54a-a4078fb441c2--

```

and if I set both `preambleCRLF` and `postambleCRLF` to false then content is (same as above but without new line at the beginning and at the end):

```
--af9c4636-9200-4157-90ac-42bd165be0e9

content
--af9c4636-9200-4157-90ac-42bd165be0e9--
```

Any idea why "boundry" is treated as a part of file content?

**Comment by simov** [comment]
Hi @alekbarszczewski 

From the curl docs

> -F, --form <name=content> - (HTTP) This lets curl emulate a filled-in form in which a user has pressed the submit button. This causes curl to POST data using the Content-Type multipart/form-data according to RFC 2388. This enables uploading of binary files etc...

So what they are saying is that's a `multipart/form-data` content-type and that will translate to using the `formData` key instead:

```coffeescript
options =
  url: 'https://www.filepicker.io/api/store/S3'
  qs: # just some filepicker-related params
    key: 'XXX'
    store: 'S3'
    mimetype: 'text/csv'
    path: key
    container: 'my-bucket'
    access: 'public'
    policy: creds.policy
    signature: creds.signature
  formData: {
    fileUpload: 'the file contents'
  }
  method: 'post'

request options, (err, res, body) ->
  # 200 OK
```

**Comment by alekbarszczewski** [comment]
Thanks it works!
