### ISSUE TITLE
Request Throws Invalid URI Error

### ISSUE THREAD

**Issue by ncrichards** [request/request#1597]
Need help: This url is valid and can open in any web browser, but it throws Error: Invalid URI in request API.
http:/g.alicdn.com/kissy/k/1.4.0/??node-min.js,dom/base-min.js,event/dom/base-min.js,event/base-min.js,event/dom/shake-min.js,event/dom/focusin-min.js,anim-min.js,anim/base-min.js,promise-min.js,anim/timer-min.js,anim/transition-min.js,io-min.js,event/custom-min.js,event-min.js,xtemplate-min.js,xtemplate/runtime-min.js,xtemplate/compiler-min.js,cookie-min.js,base-min.js?t=4056852921.js

![request](https://cloud.githubusercontent.com/assets/12530206/7784652/09b3d65c-01a0-11e5-9c70-81c2fa08c436.JPG)

**Comment by simov** [comment]
Add one additional `/` here `http:/g.alicdn.com` and you'll get it working.

**Comment by ncrichards** [comment]
Thanks @simov That solved the problem
