### ISSUE TITLE
inconsistent emit end event. 

### ISSUE THREAD

**Issue by martingg88** [request/request#1602]
I have issued 10 requests and get back 10 response as well. however i do have an issue that the "end" event may be emitted less than 10. Any idea how to fix this issue?

**Comment by martingg88** [comment]
anyone can help?

**Comment by froatsnook** [comment]
Hey @martingg88 

```javascript
var request = require("request");

var responseCount = 0;
var endCount = 0;

for (var i = 0; i < 10; i++) {
    request("http://localhost:4080/", function(err, res) {
        console.log("responseCount=%s", ++responseCount);
    }).on("end", function() {
        console.log("endCount=%s", ++endCount);
    });
}
```

I made this sample program and I get 10 responses and 10 ends.  It will be hard to help you unless you can provide a lot more info.  Where and what are you requesting?  What options are you using?  Are you using forever-agent?  Can you post an example or a failing test?

**Comment by martingg88** [comment]
i just issue a simple request with default option to download large file like video. Meanwhile we may issue 100 request to download the file in chunks at the same time. we get the 100 well-defined response and data event but less than 100 for end event. 

can you try to issue 100 request to download any file from anywhere rather than localhost to see you whether get 100 end event?

may be you can stream this url http://nodejs.org/dist/v0.10.28/x64/node-v0.10.28-x64.msi

**Comment by martingg88** [comment]
is it possible request can't handle  many parallel requests?

**Comment by froatsnook** [comment]
> can you try to issue 100 request concurrently to download any file from anywhere rather than localhost to see you whether get 100 end event?

If you post some sample code, I'll take a look.

> is it possible request can't handle many parallel requests?

Works fine with 1000 parallel requests:

```javascript
var http = require("http");
var request = require("request");

var reqCount = 0;
var server = http.createServer(function(req, res) {
    reqCount++;

    (function waiter() {
        if (reqCount === 1000) {
            res.statusCode = 200;
            res.end("OK");
        } else {
            setTimeout(waiter, 1000);
        }
    })();
});

server.listen(6767);

var errCount = 0;
var resCount = 0;
var endCount = 0;
for (var i = 0; i < 1000; i++) {
    request.get("http://localhost:6767", function(err, res) {
        if (err || res.body !== "OK") {
            errCount++;
        } else {
            resCount++;
        }
    }).on("end", function() {
        endCount++;
        if (endCount === 1000) {
            setTimeout(function() {
                console.log("errCount=%s resCount=%s endCount=%s", errCount, resCount, endCount);
                process.exit(0);
            }, 500);
        }
    });
}
```

**Comment by martingg88** [comment]
here we go. you may need this async library. 

https://github.com/caolan/async


var max_try = 1000;

var tasks = [];

for(i; i < max_try; i++){
  tasks.push(function(cb){
       send(cb);      
  });
}

var end_count = 0;
var response_count = 0;
function send(cb){

    var req = request('http://localhost:6767');
    req.on('error', function(error){return cb(error});
    req.on('end', function(){
	    //end_count may not be equal to max_try
		//here may not run the callback because end event is not emitted.
	    end_count++;
		return cb();
    });
	req.on('response', function(response){
		//response_count will always be equal to max_try
		response_count++;
	});
	 
    self._req.on('data', function(data){
	    //here could be possible the data is not received in complete for request in parallel
    });

}

// here will run tha tasks concurrently up to max_try at a time.
async.parallelLimit(tasks, max_try, function(error, result){
	
	if (error){
		return cb(error);
	}
	
	return cb();
});

**Comment by martingg88** [comment]
@froatsnook are you manage to reproduce the issue?

**Comment by froatsnook** [comment]
Nope!  Can you post some code that runs and fails?  Are you using the `RANGE` header?

**Comment by martingg88** [comment]
sure.

here are the steps to track the issue. 

1. first get youtube url as follows: 

a. visit to http://en.savefrom.net/ and paste the following link into text box.
https://www.youtube.com/watch?v=cFP4QFDG3vE
b. after that, right click "download" button can copy the link address and put it in text file file

2. download the fast-download to track the request issue. try to put focus on //comment: in    FastDownload.js file.
    a. here is the link to npm download fast-download library. 
    https://github.com/martingg88/node-fast-download.git
   
    b. use the script to run the download.  after run this script, you should be able to see output in console that show number of end events is not equal to "chunksAtOnce" size here.

var youtube_encoded_url = ''paste your encode url here";

var dl = new fast_download(youtube_encoded_url, {resumeFile: true, chunksAtOnce: 100});

dl.on('start', function(dl){
	console.log('start: ');
})

dl.on('error', function(err){
	console.log('error: ');
})

dl.on('end', function(){
	console.log('end: ');
})

dl.on('finish', function(){
	console.log('finish: ');
});

**Comment by martingg88** [comment]
in between, do you have skype to discuss this issue?

**Comment by martingg88** [comment]
i realized that some requests in batch will only emit data event half way and hang there forever. feel strange on this issue.

**Comment by froatsnook** [comment]
> in between, do you have skype to discuss this issue?

No, sorry.  Maybe someone with a little more knowledge will chime in.

> feel strange on this issue.

What do you mean?

**Comment by martingg88** [comment]
ok. i just checked that http.request may not support many request like 100 requests in parallel. in between do you able to reproduce the issue based on steps i provided?

**Comment by martingg88** [comment]
any update on this?
