### ISSUE TITLE
Thoughts on a cache wrapper

### ISSUE THREAD

**Issue by phillipj** [request/request#1604]
Hi!

I'm been thinking about creating (yet another) cache wrapper around `request`. Before jumping into coding something, I would really appreciate some thoughts from you on this as I'm guessing you have done some thinking around caching more than once over the years.

In comparison to the other caching modules I have found so far, I want to do a slightly different approach by literally wrapping instead of being a drop-in-replacement. Somewhat inspired by the wrapping/interceptors done in the [rest](https://github.com/cujojs/rest) module.

``` js
// something similar to
var cache = require('request-cache');
var request = cache(require('request'));

// not drop-in such as
var request = require('a-request-cache-module');
```

In my mind **actually** wrapping like that looks more like actual composition which I'm a big fan of.

Any thoughts on this? Is there room for another cache module or does it already exist a good enough cache module out there?

**Comment by BrandonCopley** [comment]
I have not seen great caching modules out there currently. I think wrapping is a far better solution to drop-in.

The challenge I've seen is that every request may need a different cache setting and this can be difficult when implementing with something like LRU I believe.

**Comment by czheo** [comment]
I tried to make a cache wrapper, but find out that we need a mechanism to get the original URL and params from the request object in order to generate keys for the cache. https://github.com/request/request/issues/1447

**Comment by simov** [comment]
@czheo that can be stored somewhere on the instance, if you need only the original URL and the original params it will be trivial to add it.

**Comment by phillipj** [comment]
Thanks for sharing your thoughts guys! I have barely started with the cache wrapper, much left to do before having something usable. 

Appreciate you sharing challenges you have met, keep 'em coming :)

**Comment by mikeal** [comment]
having to wrap the entire API is pretty annoying.

ideally we would have enough events and internal methods exposed that you could do something like:

```javascript
var cache = require('request-cache')
  , request = require('request').defaults({json:true})
  ;
cache(request)
request.get('http://www.google.com')
```

**Comment by phillipj** [comment]
Tried with events and internals a couple of weeks ago. Remember I met some obstacles on the way, but I could investigate if further and come back to you with concrete challenges to discuss.

**Comment by pyhedgehog** [comment]
Let me add some thoughts. It would be usable (i.e. for testing) to allow some offline mode:
==== cache-filler.js
```JavaScript
var cache = require('request-cache'),
    request = require('request');
request = cache(request, {cache:'cachefile.sqlite'});
request.get('http://www.google.com');
request.get('http://www.yahoo.com');
request.get('https://github.com');
```
==== testcase.js
```JavaScript
var cache = require('request-cache'),
    request = require('request');
request = cache(request, {cache:'cachefile.sqlite', offline:true});
request.get('http://www.google.com'); // OK
request.get('http://www.yahoo.com'); // OK
request.get('https://bitbucket.org'); // Exception: not cached and offline mode enabled
```

**Comment by phillipj** [comment]
Ahhh, thanks for sharing @pyhedgehog! Havent thought about "offline mode" before, its an interesting feature.

**Comment by phillipj** [comment]
What would you expect of the result from a cached response?

Is it only the response body which interests you or should it be completely transparent to the end-user? The latter meaning the complete response with headers and one should still be able to use it as a readable stream for `.pipe()`-ing.

**Comment by BrandonCopley** [comment]
I am only interested in the response body. Nothing different I can think of.

**Comment by mcollina** [comment]
@pyhedgehog we can think about using [levelup](http://npm.im/levelup) for the offline cache, it's much easier to work with than sqlite, and can be even distributed (on redis, mongo, dynamo or others).

API-wise, I think I prefer:

```js
var cache = require('request-cache')
  , request = cache(require('request').defaults({json:true}))
  ;
request.get('http://www.google.com')
```

Just because I would tried to avoid changing the behavior of a module that might be used by some other piece of code (that maybe does not want caching to happen).

**Comment by pyhedgehog** [comment]
@mcollina I'm not insisting on sqlite. It's just my personal choice as single-file db can be easier committed to GIT and used by test-cases on CI servers.

@phillipj For my current use-case only `body` is needed. Also `response.headers` could be usable in future (i.e. to parse `Link:` header). But full support of `.pipe()` is overkill from my point of view.

**Comment by BrandonCopley** [comment]
IMO each request needs different caching, certain types of caching for some
requests, different than others.

On Wednesday, August 26, 2015, PyHedgehog <notifications@github.com> wrote:

> @mcollina <https://github.com/mcollina> I'm not insisting on sqlite. It's
> just my personal choice as single-file db can be easier committed to GIT
> and used by test-cases on CI servers.
>
> @phillipj <https://github.com/phillipj> For my current use-case only body
> is needed. Also response.headers could be usable in future (i.e. to parse
> Link: header). But full support of .pipe() is overkill from my point of
> view.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/request/request/issues/1604#issuecomment-135031646>.
>


-- 
[image: Giftnix]

Brandon Copley

Founder & CEO

t: 512.784.6060

e: copley.brandon@gmail.com

**Comment by phillipj** [comment]
@mcollina very good point about not changing the request module globally!

@pyhedgehog @BrandonCopley thanks for your thoughts about what you expect to be cached.

@BrandonCopley *each* request or a group of requests? Pseudocode of the what I think is the difference:

```js
// option 1 : different cache per request

var cache = require('request-cache')
  , request = cache(require('request'))
  ;

var sqlCache = {cache:'cachefile.sqlite'}
  , redisCache = {cache:'redis'}
  ;

request.get('http://www.google.com', sqlCache)
request.get('http://www.facebook.com', redisCache)

// option 2 : different cache per group

var cache = require('request-cache')
  , request = require('request'),
  , searchRequest = cache(request, {cache:'cachefile.sqlite'}),
  , socialRequest = cache(request, {cache:'redis'})
  ;

searchRequest.get('http://www.google.com')
socialRequest.get('http://www.facebook.com')
```

**Comment by BrandonCopley** [comment]
I think both should be doable. I have had a few instances while using my
own cache where all requests share the same cache, and other times where
each request uses different cache's. I would imagine a good way to think of
this is more of an option unique to each request whether to use a cache
setting you have stored or be able to create your own cache setting on a
request by request basis.

I would do something like this:

cacheSettings1 = {...}

request1 - cache : cacheSettings1

request2 - cache : cacheSettings1

request3 - cache : {...}

request4 - cache : {...}

On Wed, Aug 26, 2015 at 1:19 PM, Phillip Johnsen <notifications@github.com>
wrote:

> @mcollina <https://github.com/mcollina> very good point about not
> changing the request module globally!
>
> @pyhedgehog <https://github.com/pyhedgehog> @BrandonCopley
> <https://github.com/BrandonCopley> thanks for your thoughts about what
> you expect to be cached.
>
> @BrandonCopley <https://github.com/BrandonCopley> *each* request or a
> group of requests? Pseudocode of the what I think is the difference:
>
> // option 1 : different cache per request
> var cache = require('request-cache')
>   , request = cache(require('request'))
>   ;
> var sqlCache = {cache:'cachefile.sqlite'}
>   , redisCache = {cache:'redis'}
>   ;
>
> request.get('http://www.google.com', sqlCache)
> request.get('http://www.facebook.com', redisCache)
> // option 2 : different cache per group
> var cache = require('request-cache')
>   , request = require('request'),
>   , searchRequest = cache(request, {cache:'cachefile.sqlite'}),
>   , socialRequest = cache(request, {cache:'redis'})
>   ;
>
> searchRequest.get('http://www.google.com')
> socialRequest.get('http://www.facebook.com')
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/request/request/issues/1604#issuecomment-135129363>.
>



-- 
[image: Giftnix]

Brandon Copley

Founder & CEO

t: 512.784.6060

e: copley.brandon@gmail.com

**Comment by mcollina** [comment]
Just a quick question, what about:

```js
var cache = require('request-mem-cache')()
  , request = cache(require('request'))
  ;

request.get('http://facebook.com', { cache: cache })
request({
    method: 'get'
  , url: 'http://facebook.com'
  ,  cache: cache
})
request.get('http://facebook.com').cache(cache)
```

**Comment by BrandonCopley** [comment]
Matteo, all 3 look like worthwhile solutions to me.

On Thursday, August 27, 2015, Matteo Collina <notifications@github.com>
wrote:

> Just a quick question, what about:
>
> var cache = require('request-mem-cache')()
>   , request = cache(require('request'))
>   ;
>
> request.get('http://facebook.com', { cache: cache })request({
>     method: 'get'
>   , url: 'http://facebook.com'
>   ,  cache: cache
> })
> request.get('http://facebook.com').cache(cache)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/request/request/issues/1604#issuecomment-135344222>.
>


-- 
[image: Giftnix]

Brandon Copley

Founder & CEO

t: 512.784.6060

e: copley.brandon@gmail.com

**Comment by mcollina** [comment]
@BrandonCopley they are quite different implementation-wise. My last one requires `request` to be aware of the cache, and ask it what to do. The others are wrappers, which might be implemented on top of the third thing.

How should we proceed to move this further?

**Comment by BrandonCopley** [comment]
Oh I know implementations are very different, but I believe all 3 will
solve the cache problem.

On Thu, Aug 27, 2015 at 7:38 AM, Matteo Collina <notifications@github.com>
wrote:

> @BrandonCopley <https://github.com/BrandonCopley> they are quite
> different implementation-wise. My last one requires request to be aware
> of the cache, and ask it what to do. The others are wrappers, which might
> be implemented on top of the third thing.
>
> How should we proceed to move this further?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/request/request/issues/1604#issuecomment-135409191>.
>



-- 
[image: Giftnix]

Brandon Copley

Founder & CEO

t: 512.784.6060

e: copley.brandon@gmail.com

**Comment by lerouxb** [comment]
Have you considered gitter's [request-http-cache](https://github.com/gitterHQ/request-http-cache/)? It uses [request-extensible](https://github.com/suprememoocow/request-extensible). I've also started on [thunderbatch](https://github.com/lerouxb/thunderbatch) which extends it further and tries to get around the thundering herd problem by grouping together all concurrent identical requests across all processes sharing the same redis backend into one.

**Comment by BrandonCopley** [comment]
I believe that's what I'm using currently, I just don't love the
implementation because it doesn't allow you to set the cache on a request
by request basis.

On Thursday, August 27, 2015, Le Roux Bodenstein <notifications@github.com>
wrote:

> Have you considered gitter's request-http-cache
> <https://github.com/gitterHQ/request-http-cache/>? It uses
> request-extensible <https://github.com/suprememoocow/request-extensible>.
> I've also started on thunderbatch
> <https://github.com/lerouxb/thunderbatch> which extends it further and
> tries to get around the thundering herd problem by grouping together all
> concurrent identical requests across all processes sharing the same redis
> backend into one.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/request/request/issues/1604#issuecomment-135457129>.
>


-- 
[image: Giftnix]

Brandon Copley

Founder & CEO

t: 512.784.6060

e: copley.brandon@gmail.com

**Comment by lerouxb** [comment]
@BrandonCopley Could you elaborate on what you mean?

Can't you just add more middleware to do things with requests before and/or after that middleware and if you want to change what goes into the cache and can't fit it in there, then perhaps the best thing to do is to fork that and add what you need?

**Comment by phillipj** [comment]
I'll elaborate my concerns about the current drop-in request cachers out there that I have seen so far, also answering your question @lerouxb, atleast from my perspective.

### Wrapping vs drop-in

As I mentioned initally wrapping and composability has alot of benefits IMO.

How awesome would it be if we could compose more wrappers together?

```js
// disclaimer: this doesnt work today because 
// co-request isnt written for composability (yet?)

const cache   = require('request-cache')
    , co      = require('co')
    , coReq   = require('co-request')
    , request = coReq(cache(require('request')))
    ;

co(function* () {
  // generator based request *with* caching
  let result = yield request('http://google.com')
})
```

Now whats the difference between this and say [request-extensible](https://github.com/suprememoocow/request-extensible) with friends? There's one crucial thing: its a drop-in package exposing a different API than `request` has, e.g. `.post()` `.get()` `.del()` `.defaults()` ++ are missing.

To me this feels like I'm suddently not using `request` anymore, but a different ecosystem all together. I'm not saying the `request-extensible` ecosystem isnt good, I'm just not dealing with `request` anymore which puts me off.

By wrapping I'm suddently alot more explicit and I feel much more in control of what's going on. Even the version of request itself is totally up to me. The API stays *exactly* the same as using `request` directly.

### Other considerations

Besides wrapping, I've had some criterias when going through the cachers out there:
- maintained
- uses HTTP headers for caching, not manual TTL
- follows [RFC7234](https://tools.ietf.org/html/rfc7234)

### Going forward

Very glad you asked that question @mcollina! I guess we've gotten enough thoughts to start hammering something out. I'm ready to start working on this next week. This is supposed to be an open open source project, so no need to say contributions are more than welcome! I'll fill the readme with some initial thoughts and we could go from there.

So far there's nothing more than a couple of cache POCs up-n-running by (1) simply wrapping functions around request and (2) using the events emitted from request. Initially it seemed like option 1 would be the best way to go, but I have by no means given up on the idea of using events. It needs more digging into request's internals to find the best solution.

And a big thanks to @jpstevens for donating the one and only `request-cache` package name :smiley:
