### ISSUE TITLE
support binary XHR via browserify?

### ISSUE THREAD

**Issue by wjordan** [request/request#1606]
I'm trying to get a library making a binary GET request working in Node and also via XHR when bundled in Browserify (the appropriate CORS headers are set on the server). I can set binary mode in Node using the provided `encoding` option, but this option does not work when bundled in Browserify, and I couldn't find any way of setting Browserify-http's XHR response type to binary (setting  `opts.responseType on the request object) through this project.

(Not sure if this project or [http-browserify](https://github.com/substack/http-browserify) is the appropriate project for this issue, but since this is the project I tried including in my project I'm reporting it here)

As a workaround, I've been able to use [jBinary#loadData](https://github.com/jDataView/jBinary/wiki/Loading-and-saving-data#jbinaryloaddatasource-callback) successfully, but I'd ideally like to do the same using this library. Any ideas?

**Comment by simov** [comment]
Can you provide a short code example enough to reproduce that behavior + the workaround one?

**Comment by wjordan** [comment]
using request (returns proper byte length with `node index.js`, returns invalid byte length with `browserify index.js -o build/index.js && phantomjs build/index.js`):
```
var url = 'https://s3.amazonaws.com/wjordan/example.zip';
var request = require('request');
request.get(url, {encoding: null}, function (error, response, body) {
  if (!error && response.statusCode == 200) {
    console.log("Got " + body.length + " bytes"); // should be 293586
  }
});
```

Workaround using jbinary (works in node and browserify):
```
var url = 'https://s3.amazonaws.com/wjordan/example.zip';
var request = require('jbinary');
request.loadData(url, function (error, body) {
  if (!error) {
    console.log("Got " + (body.length || body.byteLength) + " bytes"); // should be 293586
  }
});
```
