### ISSUE TITLE
Url as stream input

### ISSUE THREAD

**Issue by erf** [request/request#1608]
Have you considered url's as input stream for generating a output stream of bodies / responses ?

**Comment by simov** [comment]
@erf you can make request and pipe it to another stream, is that your goal?

**Comment by erf** [comment]
I was thinking piping urls as input to request. I have s custom solution now where i have wrapped request inside through2

**Comment by simov** [comment]
Can you supply an example code for your use case? Closing for now.

**Comment by erf** [comment]
instead of doing:
.pipe(collect)
.pipe(parse)

function collect = through2(function(chunk, enc, cb){
   var url = chunk.toString()
   console.log('get ', url)
   request(url, function (error, response, body) {
      cb(null, body)
   })
})

i could to:
.pipe(request)
.pipe(parse)



2015-06-03 16:50 GMT+02:00 simo <notifications@github.com>:
