### ISSUE TITLE
Bearer token should not require user

### ISSUE THREAD

**Issue by tracend** [request/request#1613]
This is the same issue as #923 from last year 

It appears that after [this commit](https://github.com/request/request/commit/139fcc0648459916986abbb3a5b3097b1af1aee6) that went live as of v2.54.0 the user is set as required with the bearer token.

https://github.com/request/request/blob/master/lib/auth.js#L117

There is no such requirement in the [official spec](https://tools.ietf.org/html/rfc6749#section-7.1) that I'm aware of and the [example in the readme](https://github.com/request/request#http-authentication) doesn't include it.

**Comment by simov** [comment]
Hi, @tracend, can you provide a failing test or a short code example to reproduce that bug?

Linking the PR in question https://github.com/request/request/pull/1500

**Comment by tracend** [comment]
I looked through the tests and they seem to be complete. 

After further investigation I noticed that my problem was related with the server not responding, and thus the bearer missing. 

Having said that, I'm closing this issue with my apologies.
