### ISSUE TITLE
invalid uri error on relative path request

### ISSUE THREAD

**Issue by Morriz** [request/request#1614]
Request throws this error:
```
Uncaught Error: Invalid URI "/api/Todos"
```
And debugging I find that Request fails on this line:
```
if (!(self.uri.host || (self.uri.hostname && self.uri.port)) && !self.uri.isUnix) {
```
since we only call with a relative path.

Should it be necessary to make requests with an absolute uri? That would be silly for browsers, but if must for now, so be it...

**Comment by simov** [comment]
You can use the `baseUrl` option for that:

```js
var r = request.defaults({baseUrl:'http://web.com'})
r.get('/api/relative')
```

**Comment by Morriz** [comment]
But I don't know it when I am deploying on a paas with dynamic domain names. I just wish Request to detect it's in browser mode and infer the host scheme, uri, and port from document.location.

**Comment by simov** [comment]
Request have nothing to do with the browser, but you can write that detection logic yourself. It shouldn't be that hard I think.

**Comment by Morriz** [comment]
Oh, I thought it would work by detecting in which environment it would be, and inferring as much as possible. Wouldn't that be preferable? How many environments are there? isUnix is already supported, so why not isBrowser?

**Comment by simov** [comment]
@Morriz feel free to submit a PR about this, closing for now.
