### ISSUE TITLE
Write after end error while attempting to proxy POST requests

### ISSUE THREAD

**Issue by Voidsheep** [request/request#1616]
I'm using Express and Request as a way to proxy /api/* requests from a local development server to a remote server and add authentication parameters to them on the fly.

GET requests seem to work absolutely fine, but POST requests crash the server with the following error:

    Error: write after end at ClientRequest.OutgoingMessage.write (_http_outgoing.js:413:15)

Here's my code:

```javascript
app.use('/api/*/', function(req, res) {
  var url = apiUrl + req.baseUrl + req.url;
  req.pipe(request(url, {
  	auth: {
  		user: apiUser,
  		pass: apiPass
  	},
  	form: req.body
  })).pipe(res);
});
```

If I omit the form option, the request is never made and there's a timeout.

This is probably more of an user error, but I couldn't find any examples of the correct way to do this for all types of requests, nor anyone else struggling with this particular error.

**Comment by simov** [comment]
I don't think you have to set the `form` parameter as you are already piping it. Also if you are expecting a `POST` request you should make `POST` request again `request[req.method-or-something]()`

```js
app.use('/api/*/', function(req, res) {
  var url = apiUrl + req.baseUrl + req.url;
  req.pipe(request.post(url, {
    auth: {
        user: apiUser,
        pass: apiPass
    }
  })).pipe(res);
});
```

**Comment by Voidsheep** [comment]
I tried with explicit method definition like you suggested, as well as giving the method in the configuration object.

Both result in the same behavior: GET requests work great, but POST request stalls for exactly one minute, after which the request to remote server is finally made, but no POST parameters seem to be available.

Trying to pass the parameters with the form property results in "Write after end" immediately.

Here's the current full code, in case it might be something else entirely causing this weirdness.

```javascript
var express = require("express");
var request = require("request");
var proxy = require("http-proxy");

var parser = require("body-parser");
var strftime = require("strftime");
var app = express();
var path = require("path");
var port = 80;
var apiUrl = "http://example.com/foo/";
var apiUser = "***";
var apiPass = "***";

app.use(express.static(path.join(__dirname, "/dist")));
app.use(parser.json());
app.use(parser.urlencoded({extended: true}));

app.use('/api/*/', function(req, res) {
  console.log(strftime("%H:%M:%S") + " | " + req.method + " -> " + req.baseUrl + " -> " + JSON.stringify(req.query));
  var url = apiUrl + req.baseUrl + req.url;
  req.pipe(request(url, {
    auth: {
      user: apiUser,
      pass: apiPass
    }
    //,form: req.body
  })).pipe(res)
});

app.listen(port);
console.log("Development server started, listening to localhost:" + port);
console.log("Proxying /api/* -> " + apiUrl + "/api/*");
```

**Comment by simov** [comment]
Your `app.use` middleware should be placed before any other middlewares, namely the body-parser. Also you really do need `request[req.method.toLowerCase()]()` in case you expect different http verbs.

**Comment by Voidsheep** [comment]
I still need the body parser to actually read the POST parameters and re-send them to the remote server, right?

I've modified the code a little, but it seems the json parser is getting stuck for a minute, timing out and then the request is sent without any data.

```javascript
var jsonParser = parser.json();
app.use('/api/*/', jsonParser, function(req, res) {
  console.log(strftime("%H:%M:%S") + " | " + req.method + " -> " + req.baseUrl + " -> " + JSON.stringify(req.query));
  var url = apiUrl + req.baseUrl + req.url;
  console.log(req.body);
  req.pipe(request[req.method.toLowerCase()](url, {
    auth: {
      user: apiUser,
      pass: apiPass,
    }
  })).pipe(res)
});
```

With this configuration I can see the parameters correctly logged, but they never make it to the remote server. GET params still make it through.

**Comment by simov** [comment]
No you don't need the `jsonParser` middleware that's the point, you need the raw `req` stream.

**Comment by Voidsheep** [comment]
Yeah, turns out the data reached the remote server all along, I just didn't see it due to the post data retrieval function returning only multipart/form-data encoded stuff. Sorry and thanks for the help :+1:

**Comment by hkchakladar** [comment]
@eemelisoderholm can you show your corrected code sample?

**Comment by nguyen124** [comment]
> I don't think you have to set the `form` parameter as you are already piping it. Also if you are expecting a `POST` request you should make `POST` request again `request[req.method.toLowerCase()]()`
> 
> ```js
> app.use('/api/*/', function(req, res) {
>   var url = apiUrl + req.baseUrl + req.url;
>   req.pipe(request.post(url, {
>     auth: {
>         user: apiUser,
>         pass: apiPass
>     }
>   })).pipe(res);
> });
> ```

This works for my case. Thanks for your hint. 
This is my code invoke from local server to google firebase

` router.post('/svc/uploadFile', middleware.isValidUser, function (req, res) {
        var newUrl = 'https://us-central1-architect-c592d.cloudfunctions.net/uploadFile';
        req.pipe(request(newUrl)).pipe(res);
    });`
