### ISSUE TITLE
How to detect end of response with chunked transfer encoding

### ISSUE THREAD

**Issue by gdraganic** [request/request#1617]
Is there a convenient way to detect an successful end of the chunked response? I can not detect the zero length chunk (terminating chunk) on the 'data' event.

**Comment by froatsnook** [comment]
You can use the `"end"` event.

**Comment by gdraganic** [comment]
Already tried that, but the "end" event fires in the situation when the response is incomplete. I tried to intentionally kill the server service in the process of delivering the chunked response and in the client app the "end" event is fired.

**Comment by froatsnook** [comment]
In that case, is there an error in the first parameter of the callback you pass to request?

```javascript
request({ ... }, function(err, res, body) {
    console.log(typeof err);
});
```

**Comment by gdraganic** [comment]
No, there is not an error in case when the callback is passed (null printed in the console). The "end" event is still fired before the callback.

**Comment by gdraganic** [comment]
Any suggestions on this?
