### ISSUE TITLE
how to post file with gzip compression to server

### ISSUE THREAD

**Issue by martingg88** [request/request#1618]
can i have an example to show how to post file with gzip compression to server?

**Comment by simov** [comment]
`{body:'https://nodejs.org/api/zlib.html'}`

**Comment by simov** [comment]
@martingg88 I just updated my previous comment with two examples.

**Comment by martingg88** [comment]
can i do it with this way?

request({
	'url' : url,
	'method' : 'PUT',
	'headers' : headers,
	'gzip' : true,
	'body' : fs.createReadStream(source_file_path, {start : file_start_position, end : file_end_position}).pipe(zlib.createGzip())
}, function(err, res, body){

});

**Comment by simov** [comment]
No, this form is not currently supported. `body` must be `Buffer` or `String`
