### ISSUE TITLE
Missing unescape() from self._qs breaks requests with authentication

### ISSUE THREAD

**Issue by andornaut** [request/request#1619]
GET requests with http basic authentication credentials such as "http://user:pass@example.com" fail with error "self._qs.unescape is not a function".

This error occurs in request.js:
```
  if (self.uri.auth && !self.hasHeader('authorization')) {
    var uriAuthPieces = self.uri.auth.split(':').map(function(item) {return self._qs.unescape(item)})
    self.auth(uriAuthPieces[0], uriAuthPieces.slice(1).join(':'), true) 
  }
```
Changing ``Querystring.prototype.unescape`` to use the global ``unescape()`` or ``decodeURIComponent`` appears to resolve this issue.

Environment: Electron 0.27.2 (chrome 43)

**Comment by simov** [comment]
That might be related to https://github.com/request/request/pull/1600 but tbh I don't see how's that possible. I need more context, can you provide a short code example that reproduces that bug?

**Comment by andornaut** [comment]
It seems that the "querystream" library supplied by Browserify does not include ``querystring.unescape`` and therefore [this assignment](https://github.com/request/request/blob/master/lib/querystring.js#L49) doesn't work as expected.

Refs:
https://github.com/substack/node-browserify/issues/826
https://github.com/mike-spainhower/querystring/issues/4
https://github.com/Gozala/querystring/issues/6

I'm closing this issue as it does not appear to be caused by a bug in this library.

**Comment by sagivo** [comment]
@andornaut did you find how to fix it on electron?

**Comment by dotbloup** [comment]
I note that unescape is deprecated: ([reference](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/unescape))
consequently self._qs.unescape(item) should be replaced by decodeURI(item)
