### ISSUE TITLE
attach extra data into request of req.pipe(request.(...))

### ISSUE THREAD

**Issue by zyf0330** [request/request#1621]
How can I use req.pipe(request.(...)) and attach some extra data into request? if I put it by form,error occurs with info 'write after end'.

<code>
var form;
req.pipe(request.post(URL,{form:form},...));
</code>

like this,but this word will occur error.
form is the extra data I want to attach to original req

**Comment by simov** [comment]
Just create a new request in this case `request.post(URL,{form:form},...).pipe(res)`. Also there is no need to open up a second issue for the same problem. Use the other one.
