### ISSUE TITLE
Cannot call method 'split' of undefined

### ISSUE THREAD

**Issue by franza** [request/request#1622]
Having this error while performing a request using an object for `uri` parameter. 

```
c:\Users\me\node_modules\request\request.js:1328
  self.uri = url.parse(self.uri.href.split('?')[0] + '?' + rfc3986(qs))
                                     ^
TypeError: Cannot call method 'split' of undefined
    at Request.qs (c:\Users\me\node_modules\request\request.js:1328:38)
    at Request.init (c:\Users\me\node_modules\request\request.js:484:10)
    at new Request (c:\Users\me\node_modules\request\request.js:264:8)
    at request (c:\Users\me\node_modules\request\index.js:50:10)
    at Object.<anonymous> (c:\Users\me\request\app.js:12:1)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.runMain (module.js:492:10)
```

I am not specifying the URL itself in href parameter because I need it to be built by request module. Here're the sources:

```javascript
var request = require('request');
var http = require('http');

http.createServer(function (req, res) {
    res.end('ok');
}).listen(6666);

request({
    uri: {
        protocol: 'http',
        host: 'localhost',
        pathname: '/a/b/c'
    },
    qs: {
        a: 1,
        b: 2
    }
}, function (err, res, body) {
    if (err) {
        console.log('ERROR: ', err.message);
    } else {
        console.log(body);
    }
});
```

**Comment by simov** [comment]
Passing `uri` object is intended to be used for passing `url.parse`d object, it's not intended to be used with hand made object with missing properties. So you either pass a string and let request `url.parse` it internally, or you `url.parse` it yourself and pass it to request.

**Comment by franza** [comment]
Thanks for your answer. But what's the point to pass already parsed object then? I thought that it's done for convenience like with `url.format` - it supports objects with missing properties and still builds proper URL.

**Comment by simov** [comment]
You can at least try to:

```js
var uri = url.parse('')
uri.protocol = 'http'
uri.host = 'localhost'
uri.pathname = '/a/b/c'
```

or extend it with some lib, if you prefer one line statement. I still have no idea if it's going to work, but at least you won't get `undefined` errors all the way.

**Comment by franza** [comment]
I don't think that it looks like a good solution for me. I thought the point in passing an object is to avoid URL formatting. I intended to use that because it's easier to test properties of request object instead of properties of URL string.

It looks like an overhead for me to pass formatted URL as property of the object when you can use URL string itself. What's the point of having `uri` object then?

**Comment by simov** [comment]
Here is an example using the [extend](https://www.npmjs.com/package/extend) module:

```js
var request = require('request');
var http = require('http');
var extend = require('extend');
var url = require('url');

http.createServer(function (req, res) {
    res.end('ok');
}).listen(6666);

request({
    uri: extend(true, url.parse(''), {
        protocol: 'http',
        host: 'localhost',
        pathname: '/a/b/c'
    }),
    qs: {
        a: 1,
        b: 2
    }
}, function (err, res, body) {
    if (err) {
        console.log('ERROR: ', err.message);
    } else {
        console.log(body);
    }
});
```

If you don't like extending, pass the properties as by hand:

```js
{ protocol: 'http',
  slashes: null,
  auth: null,
  host: 'localhost',
  port: null,
  hostname: null,
  hash: null,
  search: null,
  query: null,
  pathname: '/a/b/c',
  path: null,
  href: '' }
```

**Comment by franza** [comment]
How do you consider and idea of RP that generates `href` upon passed properties using `url.format` if `href` is empty?

**Comment by simov** [comment]
To me using internally something like `util._extend(url.parse(''), self.uri)` in those cases would be enough. I don't see how using the `url.format` method could make the implementation shorter and easier to understand.

This behavior should be tested of course, and yes PRs are always welcomed.

**Comment by franza** [comment]
I thought about smth like this:

```javascript
if (typeof options.url === 'object' && self.href === undefined) {
  self.href = url.format(options);
}
// then the line in my comment above won't fail
self.uri = url.parse(self.uri.href.split('?')[0] + '?' + rfc3986(qs))
```
This way `request` will support situations when `href` wasn't defined in `options.url` and it will be constructed automatically.

**Comment by simov** [comment]
OK, that might work, however we need tests to make sure.

**Comment by simov** [comment]
Closing for now, thanks for the feedback @franza :+1:
