### ISSUE TITLE
how to pass POST request arguments required by the url ?

### ISSUE THREAD

**Issue by saru95** [request/request#1625]
for example if i need to pass some parameters along with the link in the POST request. Like we acheive in curl requests. How do i pass those arguments ?

**Comment by simov** [comment]
Use the [qs option](https://github.com/request/request#requestoptions-callback)

**Comment by saru95** [comment]
could you give an example ?

**Comment by simov** [comment]
`request.post('url', {qs:{required:'by', the:'url'}, form:{post:'parameters'}})`

**Comment by saru95** [comment]
Ill check it out !

**Comment by saru95** [comment]
My url goes like `'http://api.compilers.sphere-engine.com/api/v3/submissions?access_token=b11bf50b8a391d4e8560e97fd9d63460'` . my parameters are one:1 , two:2, three:3  . How would the above statement look . Sorry, but im new to node .

**Comment by simov** [comment]
Well that's not node related, nor request itself. You should read about [querystring](http://en.wikipedia.org/wiki/Query_string) and [post request](http://en.wikipedia.org/wiki/POST_(HTTP))

```js
# choose one
request.post('http://api.compilers.sphere-engine.com/api/v3/submissions?access_token=b11bf50b8a391d4e8560e97fd9d63460', {qs:{one:1, two:2}})
# or
request.post('http://api.compilers.sphere-engine.com/api/v3/submissions', {qs:{access_token:'b11bf50b8a391d4e8560e97fd9d63460', one:1, two:2}})
# or
request.post('http://api.compilers.sphere-engine.com/api/v3/submissions?access_token=b11bf50b8a391d4e8560e97fd9d63460&one=1&two=2')
# or use form for POST
```

**Comment by saru95** [comment]
thank you !
