### ISSUE TITLE
self._qs.unescape is not a function

### ISSUE THREAD

**Issue by rouflak** [request/request#1627]
I'm trying to execute a POST request with the following code:
```
request(
    {
        method: "POST",
        data: {
            code: "mycode",
            grant_type: "authorization_code"
        },
        uri: "https://some_identifier:some_secret@my-host-name.com/some/part"
    },
    function(error, response, body) {
        console.log(error, error);
        console.log(response, response);
        console.log(body, body);
    }
);
```

But I'm having the following error:
`Uncaught TypeError: self._qs.unescape is not a function`

corresponding to these lines:
```
// request.js

if (self.uri.auth && !self.hasHeader('authorization')) {
    var uriAuthPieces = self.uri.auth.split(':').map(function(item) {return self._qs.unescape(item)})
    self.auth(uriAuthPieces[0], uriAuthPieces.slice(1).join(':'), true)
}
```
Maybe I'm doing something wrong but there's something weird with this error.

The `_qs` attribute of request is an instance of Querystring function localized in `./lib/querystring`

Moving to this file I can see the following code:
```
// ./lib/querystring.js

var qs = require('qs'),
     querystring = require('querystring');
```
... and then this one
```
// ./lib/querystring.js

...
Querystring.prototype.unescape = querystring.unescape
```

When I log in the console the `querystring` object, I can't find any function called `unescape`.

Well, I hope I'm not wasting your time with this. Am I misusing the request package or is it really a bug ?

**Comment by simov** [comment]
@rouflak this might be related to the environment you're using request in, check this issue https://github.com/request/request/issues/1619

**Comment by rouflak** [comment]
Ok, thanks a lot. Closing it as it isn't relevant.

**Comment by stevage** [comment]
I have just run into this as well, bundling an app using Parcel. It's possible that bundlers don't include it because it seems to be deprecated: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/unescape (decodeURI is recommended instead).
