### ISSUE TITLE
Error in example

### ISSUE THREAD

**Issue by raine** [request/request#1632]
https://github.com/request/request#oauth-signing

The `qs` var defined in the last `post` callback is not used.

**Comment by simov** [comment]
Yep, it's for this API endpoint https://dev.twitter.com/rest/reference/get/users/show. Either `user_id` or `screen_name` is required, but sending both should work too. My point with this one was to show that the OAuth flow for Twitter returns extra data, that can be used later on.

```js
{
  "oauth_token": "...",
  "oauth_token_secret": "...",
  "user_id": "1234",
  "screen_name": "abcd",
  "x_auth_expires": "0"
}
```

You can submit a PR about it if you want.
