### ISSUE TITLE
Version 2.50 introduced odd JSON behavior

### ISSUE THREAD

**Issue by toddself** [request/request#1635]
We are having a problem interacting with a server written in GO when we update request from 2.49.0 to 2.50.0. (This issue still exists in the latest 2.x release)

The issue is that the JSON being sent when `json: true` is set in the options is wrapped as a string.

Here is a request body from v2.49.0:
```
POST / HTTP/1.1
host: 192.168.1.8:8755
accept: application/json
content-length: 102
Connection: keep-alive

{"directory":"","filename":"6-8-2015.DAT","body":"6-8-2015\t8/6/2015 7:00:00 PM\t8/6/2015 7:21:00 PM"}
```

Here is the same exact request body from v2.50.0
```
POST / HTTP/1.1
host: 192.168.1.8:8755
accept: application/json
content-type: application/json
content-length: 118
Connection: keep-alive

"{\"directory\":\"\",\"filename\":\"6-8-2015.DAT\",\"body\":\"6-8-2015\\t8/6/2015 7:00:00 PM\\t8/6/2015 7:21:00 PM\"}"
```

The latter causes the Go `json.Unmarshal` method to choke with: 
`json: cannot unmarshal string into Go value of type main.ServerMessage`

Looking through the changelog.md file the only change that seems to be relevant was the addition of an optional "reviver" -- however undoing that change doesn't seem to solve this problem.

**Comment by toddself** [comment]
`ServerMessage` is a struct defined as:

```go
type ServerMessage struct {
	Directory string `json:"directory"`
	Filename  string `json:"filename"`
	Body      string `json:"body"`
}
```

**Comment by simov** [comment]
@toddself are you sure this doesn't work with the latest version of request. 2.50 had a really nasty bug and you shouldn't use it. If the problem persists using the latest version, can you give me an example code that reproduces the bug (using `request` options) as you are using them in your app.

**Comment by toddself** [comment]
It persists in 2.57.0

However, upon further examination this is mostly my fault!

I was calling `JSON.stringify` on the object and then passing it into the opts object as a string even though I'm setting `json: true`:

```js
'use strict';

var request = require('request');

module.exports = function(url, directory, filename, file, cb){
  if(typeof cb !== 'function'){
    cb = function(){};
  }

  var payload = JSON.stringify({
    directory: directory,
    filename: filename,
    body: file
  });

  var opts = {
    url: url,
    body: payload,
    json: true,
    method: 'POST',
    followRedirect: false
  };

  console.log('Sending to prompter', opts);

  request(opts, function(err, res, body){
    if(err || res.statusCode === 500){
      err = err || new Error('Prompter returned a 500 '+body);
      console.log('Unable to write to prompter ' + url, err);
      return cb();
    }
    cb(null, res);
  });
};
```

In 2.49.0 and lower though this worked even with my error.  Apparently 2.50.0 fixes this issue.

**Comment by simov** [comment]
Yep, that might be the case. I think this change is related to https://github.com/request/request/pull/1310 where I fixed a previous change in that logic (not reverted).
