### ISSUE TITLE
Response with charset ISO-8859-1 is malformed

### ISSUE THREAD

**Issue by gajus** [request/request#1636]
Example:

Request to http://m.cinemasgaumontpathe.com/cinemas/  special French characters, such as "é" come back as unicode replacement character, e.g. "Pathé Chamnord" is "Path� Chamnord".

**Comment by gajus** [comment]
Reading this https://github.com/request/request/issues/118, it appears that I need to listen to the buffer and use iconv to convert ISO-8859-1 to UTF-8. But why is that not done automatically?

**Comment by gajus** [comment]
Ok, I understand that recognising encoding is a challenge. However, I do not understand why request does not integrate `iconv` to at support custom encoding when it is provided, e.g.

```js
let encoding,
    iconv = require('iconv-lite');

if (options.encoding) {
    encoding = options.encoding;

    options.encoding = null;
}

request(options, (err, incomingMessage, body) => {
    if (encoding) {
        body = new Buffer(body);
        body = iconv.decode(body, encoding);
    }

    // ..
});
```

**Comment by simov** [comment]
Thanks for the heads up, @gajus. There might be a clever way to add this feature to the core, but I'm not sure. We'll have to implement it for the streaming API as well.

**Comment by gajus** [comment]
I am not familiar with `request` code base, though implementing extended encoding support using `iconv-lite` would be as simple as adding `decodeStream` to the existing pipe, https://github.com/ashtuchkin/iconv-lite#streaming-api-node-v010.

**Comment by simov** [comment]
That's the thing, it may not be as simple as that, as request overrides all of the stream methods. I'm definitely not saying that it won't be possible, but currently there are far more urgent things like migrating to streams2. So for the time being it might be easier to just pipe it yourself like it's been suggested in #118

**Comment by Polooo2** [comment]
Stumbled upon the same problem. Would be nice to have a note about this in the readme in the encoding part?

**Comment by gajus** [comment]
> Thanks for the heads up, @gajus. There might be a clever way to add this feature to the core, but I'm not sure. We'll have to implement it for the streaming API as well.

request still doesn't make it easy to handle this case.

**Comment by Natanael1234** [comment]
Gajus, by using 

```
body = new Buffer(body);
iconv.decode(body, encoding);
```
 the word "Informações" becames ''Informaï¿½ï¿½es"

I'm opening a webpage with:

`<meta charset="iso-8859-1">`
