### ISSUE TITLE
Update form-data

### ISSUE THREAD

**Issue by dgsunesen** [request/request#1641]
Hi, could you please update the form-data dependency to newest version.. See this: https://github.com/felixge/node-form-data/issues/111

**Comment by simov** [comment]
Sure, although it doesn't seems to be a stable release https://david-dm.org/request/request

**Comment by dgsunesen** [comment]
Living on the edge ;-)

**Comment by dgsunesen** [comment]
Let me know when it has been updated.. I have a project that depends a bit on it :)

**Comment by simov** [comment]
Version bumped here https://github.com/request/request/commit/012577f36b31edf0371d855a7371d82ae71d8f0b as for the new release it's coming very soon.

**Comment by dgsunesen** [comment]
Thanks! :)

**Comment by simov** [comment]
2.58 is released https://github.com/request/request/issues/1643
