### ISSUE TITLE
How to execute curl operation using request with authorizaion: bearer token? 

### ISSUE THREAD

**Issue by naveensf** [request/request#1642]
I am using cloudfoundary in that curl operations having authorization:bearer xxxxx token. How can i include authorization:bearer in request module can you help me plz

**Comment by simov** [comment]
`request({auth:{bearer:'[ACCESS_TOKEN]'}})`

**Comment by naveensf** [comment]
I'm using this code for bluemix space quote definations but get this result
request({
    url: 'https://api.ng.bluemix.net/v2/space_quota_definitions',
    method: 'POST',
    headers: {
        'Authorization': 'bearer eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiI0ODkyYjk4OS0zNjVkLTQ5MjAtODhhYi1jYzBjNTMW5_e3IU',
        'Content-Type': 'application/x-www-form-urlencoded',
        'Cookie': ''
    },
    form:{
        "name": "gold_quota",
        "non_basic_services_allowed": true,
        "total_services": 5,
        "total_routes": 10,
        "memory_limit": 5120,
        "organization_guid": "dbcc866a-87e9-4ae7-8769-e655a6a8468a"
    }
}

result:
{
  "code": 1001,
  "description": "Request invalid due to parse error: lexical error: invalid string in json text.\n                                       name=gold_quota&non_basic_servi\n                     (right here) ------^\n",
  "error_code": "CF-MessageParseError"
}

**Comment by simov** [comment]
This API might expect JSON body instead of url-encoded one. Try usin the `json` option instead of `form` and remove that `content-type` header - you don't need to specify it explicitly.

**Comment by naveensf** [comment]
yes its working thank you very much
