### ISSUE TITLE
Form content-type lost the charset somewhere >2.40.0

### ISSUE THREAD

**Issue by jkrems** [request/request#1644]
Headers using `request@2.40.0`:

```js
{ 'content-type': 'application/x-www-form-urlencoded; charset=utf-8',
  'content-length': '14' }
```

Headers using `request@2.57.0`:

```js
{ 'content-type': 'application/x-www-form-urlencoded',
  'content-length': '14' }
```

This causes problems with services that default to a different charset.

**Comment by jkrems** [comment]
Guess this was caused by https://github.com/request/request/pull/1159. Confused why some stacks are apparently not affected by this since it does look like the form parameters are encoded as utf-8. So a decoder on the other hand trying to read it as something else *should* break afaict.

**Comment by jkrems** [comment]
Would it be acceptable to have an option (e.g. `forceFormEncoding: true`) to restore the old behavior? Or at least honor existing `content-type` headers in `req.form(x)`? If so, I'd be happy to create a PR. :)

**Comment by simov** [comment]
Request should honor any user defined header. According to this https://github.com/request/request/issues/701#issuecomment-68066642 it seems that this was working back then, but I just tested and it's not, so probably something changed along the way. I'm going to investigate that. As for `forceFormEncoding` option, I don't think that would be necessary if the `content-header` can be overriden by the user (like it should).

**Comment by jkrems** [comment]
Sounds good! For clarity: We are currently using a [delayed `setHeader` in gofer](https://github.com/groupon/gofer/issues/43) to restore the old behavior. But it would be great if `options.headers['content-type']` would work as well (since the current workaround code looks pretty ugly).

**Comment by simov** [comment]
@jkrems just pushed the fix https://github.com/request/request/pull/1650 also I just noticed that the example here https://github.com/request/request/issues/701#issuecomment-68066642 is using `body` instead of `form`.

**Comment by jkrems** [comment]
@simov Thanks for the update! :)
