### ISSUE TITLE
where to put a callback when pipe is finished?

### ISSUE THREAD

**Issue by calidion** [request/request#1645]
for example:
  
    request.get({url:url, form: data}).pipe(fs.createWriteStream(file));

this code can executed perfectly.
but where can we get a callback when it is ready?

**Comment by simov** [comment]
request.get({url:url, form: data}).pipe(fs.createWriteStream(file)).on('end', function() {?})

**Comment by calidion** [comment]
not work. won't get there.

**Comment by simov** [comment]
request.get({url:url, form: data}).pipe(fs.createWriteStream(file).on('end', function() {?}))

typo

**Comment by mscdex** [comment]
Writable streams have a `finish` event, not `end`, which is for Readable streams.

**Comment by calidion** [comment]
@mscdex 

works now.
thanks.

**Comment by calidion** [comment]
@simov 

is it possible for me not to get the content type and treat the responses separately?

for in this example, if i don't know what result would be, i would like to test the content type.

**Comment by simov** [comment]
@calidion use the `on('response')` event

```js
var response_stream = request('http://example.org')
//also works with request.get, request.post, etc …

response_stream.on('error', function(err) {
  //handle the error
})

response_stream.on('response', function (response) {
  if (response.headers['Content-Type'] === '...') {
    response_stream.pipe(fs.createWriteStream('some/file/path'))
    response_stream.on('end', function () {
      // all done
    })
  }
})
```

**Comment by tcstory** [comment]
@mscdex finish event is not work for me...........

**Comment by mmrxia** [comment]
thx

**Comment by catcher-in-the-try** [comment]
If anyone needs the same thing, but for `async-await` syntax, here it is: 

```
await new Promise(resolve =>
    request(url)
      .pipe(fs.createWriteStream(filename))
      .on('finish', resolve));
```

**Comment by danielecr** [comment]
thank you for discuss, I wrote code that print out events in the sequence those occur, here:
https://gist.github.com/danielecr/f6dc09d7e5ad083540f618927c969fc4
it is more verbose, but maybe it is useful for showing every case

**Comment by justicejoe** [comment]
@anton-bot You superrrrrrr save my day. Thanks

**Comment by AnasQiblawi** [comment]
```js
request.get({ url: url, form: data })
  .pipe(fs.createWriteStream(file))
  .on('finish', function () {
    // code here
  });
```
