### ISSUE TITLE
docs appear to be incorrect for a simple request

### ISSUE THREAD

**Issue by jcollum** [request/request#1653]
The docs say request should be called like: 

```js
var request = require('request');
request('http://www.google.com', function (error, response, body) {
  if (!error && response.statusCode == 200) {
    console.log(body) // Show the HTML for the Google homepage.
  }
})
```

When I use `request` like: 

```js
// (this is just some prototype code) 
      for (i = 0, len = urls.length; i < len; i++) {
        url = urls[i];
        result = [];
        logger = this.logger; 
        request(url, function(error, resp, body) { // url is a string, not an object or array
          console.log("status:" + resp.statusCode);
``` 

It's getting routed to: 

`function request (uri, options, callback) {` (line 44) and my callback is being passed in the options position, causing my callback to not be called. No errors are thrown though. 

It looks like the docs may be incorrect.

**Comment by simov** [comment]
@jcollum can you paste the exact error message you are getting here?

**Comment by jcollum** [comment]
Why was this closed?

**Comment by simov** [comment]
Well, I was requesting more feedback from you, but didn't received any.

**Comment by jcollum** [comment]
You need to wait more than 10 hrs for someone to give  you feedback. I will try and show a screenshot of what I'm seeing today.

**Comment by simov** [comment]
I agree, but your bug report looked really vague to me, also trust me - the simple request example is working, around 9k modules depend on it.

Just try to give a complete code example that reproduces the bug and probably the error message as well.

**Comment by jcollum** [comment]
Here's a couple of screenshots of the callback being empty. I see what's happening now, the code in `initParams` places the options into the params  object as the callback if options is a function. It just threw me off -- I had placed this lib into some code and was getting a failure in my code. It looked odd but I see it now. 

![screen shot 2015-06-23 at 10 02 04 am](https://cloud.githubusercontent.com/assets/704514/8312182/0eee11a2-1990-11e5-97ec-d61a181746eb.png)
![screen shot 2015-06-23 at 10 01 35 am](https://cloud.githubusercontent.com/assets/704514/8312183/0eef4b44-1990-11e5-97d3-3741f7aca5f2.png)
