### ISSUE TITLE
PUT request is adding some extra tokens into the body

### ISSUE THREAD

**Issue by activatedgeek** [request/request#1655]
Here is my request options object
```js
{
  method: 'PUT',
  url: 'http://someurl/upload/myfile.txt',
  headers: { Authorization: 'Bearer <token>' },
  preambleCRLF: false,
  postambleCRLF: false,
  multipart: [ { body: 'this is a sample text file' } ] 
}
```

When I download the file from the link, here is the file content I get:
```text
--d3d207cc-023e-465c-bf05-592352ee6f2d

this is a sample text file
--d3d207cc-023e-465c-bf05-592352ee6f2d--
```

I have tried sending the same plain text body via `Postman`, I don't face this issue. I get the exact file uploaded. I have turned off the CRLF tokens yet this thing is done. Can somebody help here?

**Comment by simov** [comment]
Can you provide the service endpoint that you are using (if it's public)? or probably create a test request to http://requestb.in/ and post the code you are using here.

**Comment by activatedgeek** [comment]
Hi, unfortunately, it is a new API that I am building and hence not deployed. But,
Here is the request bin link: [http://requestb.in/v38qt7v3?inspect](http://requestb.in/v38qt7v3?inspect)

Here is the code I used:
```nodejs
var request = require('request');

// a simple callback function
function callback(req, response, body) {
  console.log(req);
  console.log(response);
  console.log(body);
}

// all the options
var options = {
  method: 'PUT',
  url: 'http://requestb.in/v38qt7v3',
  preambleCRLF: false,
  postambleCRLF: false,
  multipart: {
    chunked: false,
    data: [{ body: "this is my sample text file." }]
  }
};

request(options, callback);
```

**Comment by activatedgeek** [comment]
The API upload endpoint that I am using simply takes the whole body of the PUT request and dumps it as a file (it happens after `OAuth2` header which is working fine hence the API is returning appropriate response).

**Comment by simov** [comment]
Parsing the multipart body is the server's responsibility. You should add a multipart middleware on your server. Otherwise you can just pass your file's contents via the `body` option, instead of using multipart.

**Comment by activatedgeek** [comment]
Yes sending the `body` parameter directly works. :+1:
