### ISSUE TITLE
accepting url objects in request constructor

### ISSUE THREAD

**Issue by ORESoftware** [request/request#1657]
I am creating a url object like so:

```javascript
var url = require('url');
var $url = url.parse(serverURL.concat(':').concat(serverPort));
```

it doesn't look like this library accepts a url object as a parameter to request like so:

```javascript
request($url).post('/event')
                .send('test')
                .expect(400)
                .end(function (err, res) {
                    if (err) {
                        //TODO: handle this error
                        return done(err);
                    } else {
                        res.statusCode.should.equal(400);
                        done();
                    }

                });
```

is this right? is there a good reason for this?

**Comment by simov** [comment]
`request.post('/event', {uri:$url})`

**Comment by ORESoftware** [comment]
thanks, that's just great, can someone fix this lib so that request($url) also works? thanks

**Comment by simov** [comment]
I don't think this is going to happen, because request uses the passed object for [options](https://github.com/request/request#requestoptions-callback), not just the url.
