### ISSUE TITLE
Ability to distinguish connect timeouts and read timeouts

### ISSUE THREAD

**Issue by kevinburkeshyp** [request/request#1660]
This request times out because the `connect` socket call fails:

```javascript
var request = require('request');
request.get('http://google.com:81', {timeout: 3000}, function(err, response, body) {
    console.log(err.code === 'ETIMEDOUT');
    process.exit(0);
});
```

This request times out because the `read` socket call doesn't see any response in 3 seconds:

```javascript
var request = require('request');
request.get('http://localhost:5501', {timeout: 3000}, function(err, response, body) {
    console.log(err.code === 'ETIMEDOUT');
    process.exit(1);
})
```

(I'm using [hamms](https://github.com/kevinburke/hamms) in the second test)

It would be nice to be able to distinguish these. Particularly, requests to a third party provider are failing and it would be good to distinguish whether the request actually made it to their server (their problem) or not (our problem).

It would also be neat because you could figure out whether or not the request made it to the server - a connection timeout is always retry-able, a read timeout on a POST is not.

**Comment by matteocontrini** [comment]
Up

**Comment by simov** [comment]
Fixed in https://github.com/request/request/issues/1711
