### ISSUE TITLE
Collision with Babel.js

### ISSUE THREAD

**Issue by yan-foto** [request/request#1661]
I cannot figure out why, but running a simple one liner application as the following

```js
var request = require('request');
```
using [`babel-node`](https://babeljs.io/docs/usage/cli/#babel-node) throws a rather strange error:

```
/usr/share/javascript/node-uuid/uuid.js:225
  if (_global.define && define.amd) {
             ^
TypeError: Cannot read property 'define' of undefined
```

Any ideas why that might be the case?

**Comment by paulohp** [comment]
@yan-foto What are you trying to do? Here it's working.
Which version of Babel and Request?

**Comment by simov** [comment]
Seems to be working for me, also quick look at the node-uuid's [code](https://github.com/broofa/node-uuid/blob/master/uuid.js) showed me that there is no such line there. You are probably using an older version or something?

**Comment by yan-foto** [comment]
I use node `v0.10.25`, It might be the problem. I will test it with the latest version and get back to you if the problem persists. I will close the issue for the moment.

**Comment by mmahalwy** [comment]
@yan-foto did you find the problem?

**Comment by yan-foto** [comment]
@mmahalwy I did not go after at. I suppose it was a local porblem.

**Comment by shubham2102** [comment]
Any update on this?????? I am getting the same error.
