### ISSUE TITLE
Accept req of http server directly

### ISSUE THREAD

**Issue by steelbrain** [request/request#1672]
Everytime I create a minimal proxy thingy, I have to parse the urls and stuff myself.
It'd be nice to have request parse them automatically. this is what I have in mind
```js
http.createServer(function (req, resp) {
  var x = request(req)
  x.pipe(resp)
})
```
so it automatically checks for it's http method and pipes the req to itself and other normal stuff that we do each time.

**Comment by simov** [comment]
Hi, @steelbrain, can you provide a more thorough example on what manipulation you have to make exactly?

**Comment by steelbrain** [comment]
@simov I have a personal proxy that automatically minifies the images and gzips the contents and does that sort of optimizations, I am using this module to serve http requests and have some middlewares that do the optimizations. I am in a remote area where the internet quality isn't what it was like back home, so that proxy delivers me http websites faster, on the same bandwidth :)

**Comment by simov** [comment]
That's nice! I guess you can (pseudo code):

```js
http.createServer(function (req, res) {
 req.pipe(someGzip()).pipe(request[req.method.toLowerCase()](req.url)).pipe(res)
})
```

Of course this might or might not work for your needs.

**Comment by steelbrain** [comment]
I am actually doing something similar at the moment, I am creating a request instance passing url and headers of `req`, then piping `req` to that request instance, in case it's a PUT request. Then creating gzip streams depending on accept-encoding header, then piping request instance's into that and that into the `res`.
but I haven't been able to make it work with POST yet. It would require some more digging in the docs, but I was thinking if request could just accept the `req` object itself and do the extraction itself, that would be super-nice.

**Comment by simov** [comment]
It should work for POST requests too. Also that *extraction* logic you are talking about is related to your use case specifically, which is implementing a proxy server for your needs. So this feature request looks like out of scope for this module. I'm still open for suggestions though. Also you can publish your own proxy server implementation, I'm sure it will be helpful for a lot of people.

**Comment by steelbrain** [comment]
I will, very soon, and I get your point. Thanks!
