### ISSUE TITLE
Auto detect gzip content-encoding in response

### ISSUE THREAD

**Issue by jianxinss** [request/request#1680]
I  try use request to crawl zhihu.com, at first time , the request module is done well, but at on the second day , I found that the response return messy code （html）.  At the same time baidu.com  weibo.com  dribble.com are still OK. They all return the correct code(html).

At the end I check the websites  ,the response like this.
![image](https://cloud.githubusercontent.com/assets/1265292/8738990/9efcdbe4-2c68-11e5-908f-d3c4b5ce0a33.png)

but request  module did not detect this and  lead a messy code .

I  check the code in  request.js
![image](https://cloud.githubusercontent.com/assets/1265292/8739029/1fbabb8e-2c69-11e5-8c95-ad5c97df55b7.png)
and  change the code， and it did well.

Above all ,I  want to know, is this a bug or  had I  miss something.

Thanks a lot.

**Comment by simov** [comment]
Currently request does not make response headers auto detection. So you should either use the `gzip` option upfront, or detect the headers yourself in the `callback` and unzip it yourself.

**Comment by simov** [comment]
@jianxinss also note that setting up `gzip:true` doesn't try to decompress the response if it doesn't have the `content-encoding` header set to `gzip` so it's safe to have that option enabled in your requests.
