### ISSUE TITLE
Content-Type is not set when using req.form()

### ISSUE THREAD

**Issue by eddiezane** [request/request#1684]
It looks like v2.59.0 and #1650 broke the [sendgrid](https://github.com/sendgrid/sendgrid-nodejs) library by making it so `Content-Type` is not set when using `req.form()`. A refactor is probably in order on our end, but just wanted to share https://github.com/sendgrid/sendgrid-nodejs/issues/178.

**Comment by simov** [comment]
Thanks for the feedback @eddiezane, can you show me the relevant code on your end? #1650 should set the `content-type` header always if it's missing.

**Comment by marcbachmann** [comment]
I can confirm this bug:
Here's a request with request@2.58.0: http://requestb.in/17m0u4a1?inspect
And one with request@2.59.0: http://requestb.in/15c7kfd1

**Comment by simov** [comment]
Wow, ok, that's the bug https://github.com/request/caseless/commit/93d11f0d7da429d39579d9d5b8bfd836da2e5e23 in the latest version of *caseless*, @mikeal any background info on this change?

Code to reproduce it (but I suspect that this potentially might have side effects in other places as well):

```js
var request = require('request')
request({
  method: 'post',
  url: "http://requestb.in/15c7kfd1",
  formData: {
    file: "something"
  }
}, function(err, res, body) {
  if (err) return console.error(err);
  console.log(res.request.headers);
  console.log(body)
})
```

**Comment by tonylukasavage** [comment]
Also seeing this bug as described, specifically in my case:

```js
var form = req.form();
form.append('file', fs.createReadStream('/path/to/file'));
```

would attach the appropriate {{Content-Type}} in 2.58.0, but now with 2.59.0 no {{Content-Type}} is in the headers.

**Comment by simov** [comment]
Thanks for the feedback everyone, the fix is pushed here https://github.com/request/request/pull/1687 and it will be published shortly (read today).

**Comment by simov** [comment]
[2.60](https://github.com/request/request/issues/1688) is published.

**Comment by eddiezane** [comment]
Thanks for working through this so quickly!
