### ISSUE TITLE
Requests are slow after latest MacOS Yosemite upgrade

### ISSUE THREAD

**Issue by arvsr1988** [request/request#1689]
Wherever I'm using request, the requests are really slow after the latest MACOS Yosemite upgrade. I upgraded to the latest request package but i'm still getting the issue. Is there anything I need to check?

Direct requests to node or any other web application are working fast as usual.

**Comment by simov** [comment]
> Direct requests to node or any other web application are working fast as usual.

Which requests are slow exactly?

**Comment by arvsr1988** [comment]
I'm doing a request from my node application to another web application (behind an nginx web server). When i hit my own machine using the ip within network it works fast. Using localhost makes it slow. Thisi the same problem i had when i was using the needle library also.

**Comment by simov** [comment]
Check your `hosts` file, it may be misconfigured.

**Comment by arvsr1988** [comment]
closing the issue as its not an issue with the library.
