### ISSUE TITLE
Clarify error handling in documentation

### ISSUE THREAD

**Issue by ynohat** [request/request#1690]
More information should be provided about the "err" argument in request callbacks. None of the examples seem to describe it properly.

The documentation should probably also specify possible error conditions. Is the err argument only for transport errors, or does it have semantics for HTTP 4xx/5xx codes?

**Comment by simov** [comment]
No `err` does not have semantics for HTTP codes. Also I'm not aware of logic in request that tries to fix bad responses. The `res` and `body` arguments contains data that you should process, as application that consumes request.

As for improved documentation 2 x :+1:

**Comment by simov** [comment]
@ynohat I'm closing this issue, feel free to submit a PR docs improvements.
