### ISSUE TITLE
error importing request

### ISSUE THREAD

**Issue by barbalex** [request/request#1691]
I have installed request-promise via npm

    npm i --save request

Then I import it into a file:

    import request from 'request'

Now I get this message:

    ERROR in ./~/request/lib/har.js
    Module not found: Error: Cannot resolve module 'fs' in C:\Users\alex\ae\node_modules\request\lib
     @ ./~/request/lib/har.js 3:9-22

    ERROR in ./~/request/~/forever-agent/index.js
    Module not found: Error: Cannot resolve module 'net' in C:\Users\alex\ae\node_modules\request\node_modules\forever-agent

     @ ./~/request/~/forever-agent/index.js 6:10-24

    ERROR in ./~/request/~/forever-agent/index.js
    Module not found: Error: Cannot resolve module 'tls' in C:\Users\alex\ae\node_modules\request\node_modules\forever-agent

     @ ./~/request/~/forever-agent/index.js 7:10-24

    ERROR in ./~/request/~/tough-cookie/lib/cookie.js
    Module not found: Error: Cannot resolve module 'net' in C:\Users\alex\ae\node_modules\request\node_modules\tough-cookie\
    lib
     @ ./~/request/~/tough-cookie/lib/cookie.js 32:10-24

    ERROR in ./~/request/~/tunnel-agent/index.js
    Module not found: Error: Cannot resolve module 'net' in C:\Users\alex\ae\node_modules\request\node_modules\tunnel-agent
     @ ./~/request/~/tunnel-agent/index.js 3:10-24

    ERROR in ./~/request/~/tunnel-agent/index.js
    Module not found: Error: Cannot resolve module 'tls' in C:\Users\alex\ae\node_modules\request\node_modules\tunnel-agent
     @ ./~/request/~/tunnel-agent/index.js 4:10-24

    ERROR in ./~/request/~/har-validator/~/is-my-json-valid/~/jsonpointer/jsonpointer.js
    Module not found: Error: Cannot resolve module 'console' in C:\Users\alex\ae\node_modules\request\node_modules\har-valid
    ator\node_modules\is-my-json-valid\node_modules\jsonpointer
     @ ./~/request/~/har-validator/~/is-my-json-valid/~/jsonpointer/jsonpointer.js 1:14-32

This is my package.json, just in case:

    {
      "name": "ae",
      "version": "1.0.0",
      "description": "arteigenschaften.ch",
      "main": "index.js",
      "scripts": {
        "start": "webpack-dev-server",
        "prebuild": "gulp cleanPublic",
        "build": "set NODE_ENV=production&& webpack",
        "test": "standard"
      },
      "author": "Alexander Gabriel",
      "license": "ISC",
      "dependencies": {
        "ampersand-app": "1.0.4",
        "ampersand-router": "3.0.2",
        "autolinker": "0.18.1",
        "autoprefixer-core": "5.2.1",
        "babel": "5.6.23",
        "babel-loader": "5.3.2",
        "bootstrap": "3.3.5",
        "classnames": "2.1.3",
        "css-loader": "0.15.5",
        "del": "1.2.0",
        "file-loader": "0.8.4",
        "gulp": "3.9.0",
        "hjs-webpack": "2.10.0",
        "jquery": "2.1.4",
        "json-loader": "0.5.2",
        "local-links": "1.4.0",
        "lodash": "3.10.0",
        "node-libs-browser": "0.5.2",
        "postcss-loader": "0.5.1",
        "pouchdb": "3.6.0",
        "pouchdb-all-dbs": "^1.0.1",
        "pouchdb-load": "^1.4.0",
        "react": "0.13.3",
        "react-bootstrap": "0.23.7",
        "react-favicon": "0.0.3",
        "react-hot-loader": "1.2.8",
        "react-json-inspector": "5.1.0",
        "react-textarea-autosize": "2.4.0",
        "react-typeahead": "^1.1.1",
        "reflux": "0.2.10",
        "request": "2.60.0",
        "require-dir": "0.3.0",
        "style-loader": "0.12.3",
        "stylus-loader": "1.2.1",
        "surge": "0.14.3",
        "url-loader": "0.5.6",
        "webpack": "1.10.1",
        "webpack-dev-server": "1.10.1",
        "yeticss": "7.0.1"
      },
      "standard": {
        "ignore": [
          "public/*"
        ]
      }
    }

**Comment by simov** [comment]
Works for me with latest `babel`

```js
// file.js
import request from 'request'

request.get('http://google.com', function (err, res, body) {
  if (err) console.log(err)
  console.log(res.statusCode)
})
```

```
$ babel file.js > ./build/file.js && node ./build/file.js
```

Prints `200`

**Comment by barbalex** [comment]
I tried again and the same error still occurs.

Sorry for mentioning request-promise in the first sentence. The error occured first when I installed request-promise and I created an issue in the request-promise repository. Then I realized that it probably was a request issue and copied the issue here, forgetting to remove the -promise.

I wouldn't know why but could the error be caused by me using webpack (configured by hjs-webpack) to build the project?

**Comment by simov** [comment]
TBH I have no idea, I just showed you that `babel+import` works with request. It's always easier to debug  from bottom to top.

In case you suspect `webpack` you can check out https://github.com/request/request/issues/1529 and https://github.com/request/request/pull/1629

**Comment by barbalex** [comment]
your link https://github.com/request/request/issues/1529 had the solution: I needed to add polyfills for node stuff in webpack.config.js, like this:

    config.node = {
      console: 'empty',
      fs: 'empty',
      net: 'empty',
      tls: 'empty'
    }

Thanks a lot!

**Comment by eqielb** [comment]
the better solution is
use  target: 'node' in webpack.config.js

**Comment by ir-fuel** [comment]
Is that a better solution when building client-side code?

**Comment by eqielb** [comment]
no, but will u import fs, net, tls on the client-side.

**Comment by cheart-gh** [comment]
@barbalex it works! thanks a lot.

**Comment by hakankaraduman** [comment]
I'm using webpack 4 and having the same issue when it tries to import request package

**Comment by IAMtheIAM** [comment]
Likewise I cannot get request or any of its variants to work in the browser using webpack 4. is `request` not compatible with the browser?
