### ISSUE TITLE
Send valid JSON as parameter name via POST request

### ISSUE THREAD

**Issue by Shtirlits** [request/request#1692]
I need to perform such request using the library:
![json](https://cloud.githubusercontent.com/assets/1741779/8829264/5337c478-309e-11e5-855a-a78890528100.jpg)
The problem is I'm not sure how to send valid JSON as the parameter name.
I tried sending params as

    params = 
        '{"userName":"username","password":"password","rememberme":"on"}': ""
and

    params = 
        "{\"userName\":\"username\",\"password\":\"password\",\"rememberme\":\"on\"}": ""

Each time server told me my JSON is invalid (in the browser everything is perfect): 
    
    org.springframework.web.util.NestedServletException: Request processing failed; nested exception is net.sf.json.JSONException: Invalid JSON String

In each case `console.log` shown, that parameters were sent as

    { '{"userName":"username","password":"password","rememberme":"on"}': '' }

while in browser it was something like

    {"{"userName":"username","password":"password","rememberme":"on"}": '' }

what is obviously is not possible without escaping the double quotes.

So, is it possible to perform such request using this libtrary or am I doing something wrong?

Request version is 2.40.0

**Comment by simov** [comment]
I'm not sure about version *2.40* but if you want to send JSON, just use the `json` property:

```js
request.post('http://...', {json:{some:'json'}})
```

**Comment by Shtirlits** [comment]
I don't need to post JSON, I need to insert JSON into parameter name

    {form: {VALID_JSON_AS_PARAMETER_NAME: ""}}

**Comment by simov** [comment]
That's weird, try this:

```js
request({
  body:JSON.stringify({obj})+'='
})
```

**Comment by simov** [comment]
@Shtirlits any update on this one? Closing for now.

**Comment by Shtirlits** [comment]
Hey @simov, sorry for such a late response. Unfortunately, what you've suggested did not work.
Here is representation of the request:
Chrome console:
![request](https://cloud.githubusercontent.com/assets/1741779/10189883/af170704-6771-11e5-8748-a93b5fb40642.jpg)
Chrome network tab:
![request2](https://cloud.githubusercontent.com/assets/1741779/10189892/b8235ad2-6771-11e5-8e79-f9f881f0881d.jpg)

I've tried sending parameters as:

        method: 'POST'
        json: true
        body: JSON.stringify(start_date:272, end_date:10)

        method: 'POST'
        json: true
        body: JSON.stringify(start_date:272, end_date:10)+'='

        method: 'POST'
        json: JSON.stringify(start_date:272, end_date:10)

        method: 'POST'
        form: 
          "{\"start_date\":272,\"end_date\":10}": ""

        method: 'POST'
        form: 
          "#{JSON.stringify(start_date:272, end_date:10)}" : ""

        method: 'POST'
        form: 
          "{start_date:272, end_date:10}" : ""

        method: 'POST'
        form: 
          '{"start_date":"272", "end_date":"10"}' : ""

and nothing worked.

At the same time, request, that is sent within browser (see images) works as expected.

Any ideas of what else I should try?
