### ISSUE TITLE
Error when boolean value is sent to multipart/form-data upload

### ISSUE THREAD

**Issue by sahilsk** [request/request#1693]
Hi,

I tried different combination for uploading image with form fields. I can only get either of them working. If i remove all fields leaving image only , then my request upload files successfully.  If i put fields along with image, like i did below, it doesn't work. 

I tried different combination. None worked for me.

At server side i'm using mutler with expressjs. 

Any help here would be great.

``` js
	var formParam = {
			 	title: "testing single image"
			  , caption: "Caption of image to test"
			  , tags:"spa, saloon"
			  , trademark: "la saloon trademark"
			  , is_cover_photo: false
			  , image: fs.createReadStream(__dirname + '/fixtures/images/services/SpaSalon.jpg')

			};
			var r = request({
//				  preambleCRLF: true
  // 				, postambleCRLF: true
   				 method: 'POST'
   				, url: "/services/" + serviceFix.id + "/photos" 
   		//		, body: formParam
   				, formData: formParam
   				, json: true
			}, function(err, res, body){
				console.log("body ", body);
				expect( body.errors.length ).to.be(0);
				expect(res.statusCode).to.be(200);
				serviceFix.photos.push(body.data);
				done();
			});
```

**Comment by simov** [comment]
Your options looks correct. Can you post the output from `request-debug` here?

**Comment by sahilsk** [comment]
```
REQUEST { baseUrl: 'http://localhost:3500/v1',
  method: 'POST',
  url: '/services/21/photos',
  formData:
   { title: 'testing single image',
     caption: 'Caption of image to test',
     tags: 'spa, saloon',
     trademark: 'la saloon trademark',
     is_cover_photo: false,
     image:
      { _readableState: [Object],
        readable: true,
        domain: null,
        _events: [Object],
        _maxListeners: undefined,
        path: '/Users/dragonaider/pwkspce/bloom_wkspace/api-server/test/fixtures/images/services/SpaSalon.jpg',
        fd: null,
        flags: 'r',
        mode: 438,
        start: undefined,
        end: undefined,
        autoClose: true,
        pos: undefined } },
  json: true,
  callback: [Function] }
REQUEST make request http://localhost:3500/v1/services/21/photos
```

**Comment by sahilsk** [comment]
One more thing, i'm getting following error when i put form fields with image:

``` js
     Uncaught TypeError: first argument must be a string or Buffer
      at ClientRequest.OutgoingMessage.write (_http_outgoing.js:433:11)
      at FormData.ondata (stream.js:51:26)
      at FSReqWrap.oncomplete (fs.js:95:15)
```

**Comment by simov** [comment]
Make sure you are using request version **2.60**, and use [request-debug](https://github.com/request/request-debug) for debug logging.

**Comment by sahilsk** [comment]
@simov  i made changes. Bump my version to 2.60

output from `request-debug`.  I see all my fields lost :(
```
{ request:
   { debugId: 6,
     uri: 'http://localhost:3500/v1/services/12/photos',
     method: 'POST',
     headers:
      { Authorization: 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwiZW1haWwiOiJEdW1teVZlbmRvcjAwNzZAbWFpbGluYXRvci5jb20iLCJpYXQiOjE0Mzc2NjE5MDEsImV4cCI6MTQzODI2NjcwMX0.Nh-_Xqgcc30uT0WFrkPKLwHGgL_eaGo4sqr0vV1-JwA',
        host: 'localhost:3500',
        accept: 'application/json',
        'content-type': 'multipart/form-data; boundary=--------------------------585004130791572633331848',
        'content-length': 80419 } } }
```

**Comment by simov** [comment]
Your fields are in the body, not in the headers + that's not the whole log.

Try to create a simple example separately, that reproduces the bug, then post it here along with the whole output, just don't put image in the `formData` fields because it will be huge.

**Comment by sahilsk** [comment]
@simov  that was the entire log.

if i remove the `formdata` and replace it with `body`, i get the entire log which you are talking about. However, i don't see huge data here.

I am just trying to upload a file with text parameters. 

``` js
{ request:
   { debugId: 6,
     uri: 'http://localhost:3500/v1/services/17/photos',
     method: 'POST',
     headers:
      { Authorization: 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwiZW1haWwiOiJEdW1teVZlbmRvcjAwNzZAbWFpbGluYXRvci5jb20iLCJpYXQiOjE0Mzc2NjgzNzcsImV4cCI6MTQzODI3MzE3N30.QukCwcKBGWMTCnEbCFu_1kfSzumTm0j_eZXlJzbh5Kw',
        host: 'localhost:3500',
        accept: 'application/json',
        'content-type': 'application/json',
        'content-length': 718 },
     body: '{"title":"testing single image","caption":"Caption of image to test","tags":"spa, saloon","trademark":"la saloon trademark","is_cover_photo":false,"image":{"_readableState":{"objectMode":false,"highWaterMark":65536,"buffer":[],"length":0,"pipes":null,"pipesCount":0,"flowing":null,"ended":false,"endEmitted":false,"reading":false,"sync":true,"needReadable":false,"emittedReadable":false,"readableListening":false,"defaultEncoding":"utf8","ranOut":false,"awaitDrain":0,"readingMore":false,"decoder":null,"encoding":null},"readable":true,"domain":null,"_events":{},"path":"/Users/dragonaider/pwkspce/bloom_wkspace/api-server/test/fixtures/images/services/SpaSalon.jpg","fd":null,"flags":"r","mode":438,"autoClose":true}}' } }
{ response:
   { debugId: 6,
     headers:
      { 'x-powered-by': 'Express',
        'content-type': 'application/json; charset=utf-8',
        'content-length': '55',
        etag: 'W/"37-38f23274"',
        date: 'Thu, 23 Jul 2015 16:19:37 GMT',
        connection: 'close' },
     statusCode: 400,
     body: { status: 400, data: [], errors: [Object] } } }
body  { status: 400, data: [], errors: [ 'No image provided' ] }
```

**Comment by simov** [comment]
If you create a *gist* of your entire configuration, including the server (just the bare minimum to reproduce it), I'll take a look at it.

**Comment by sahilsk** [comment]
@simov 

Here is the minimum code required to produce the case. 

https://github.com/sahilsk/request-file-upload-test


With postman(chrome extension) i can upload file along with other form text fields like (title name etc).
However when i try to upload file with form text fields only then it doesn't work.  Though i can upload single or multiple file.

**Comment by simov** [comment]
Thanks for taking the time to create that example.

The problem is with `is_cover_photo: false` parameter, that should be `is_cover_photo: 'false'` string instead.

I just posted a question in https://github.com/felixge/node-form-data/issues/137 take a look if you're interensted in.

**Comment by sahilsk** [comment]
Thank you so much for helping me solve this issue. I"m surely interested in getting that bug solved.  (:

**Comment by simov** [comment]
It seems like a better [error message](https://github.com/felixge/node-form-data/issues/137#issuecomment-124559015) is going to be thrown in `form-data`. Once the new version is out we'll update our dependency if needed.

**Comment by alexindigo** [comment]
I'm wondering how `formData: formParam` and  `json: true` meant to work together.

**Comment by simov** [comment]
`json:true` sets the `accept-encoding` header, and also tries to `JSON.parse` the response body.

**Comment by alexindigo** [comment]
Oh, so they unrelated. Thanks :)

**Comment by simov** [comment]
Well they are related, but only in this case:

> `body` - entity body for PATCH, POST and PUT requests. Must be a Buffer or String, unless  json` is true. If `json` is true, then body must be a JSON-serializable object.

That's only valid when the user sets the body manually using the `body` option.

In case of a `multipart/form-data` the body is set internally. We also have a more generic `multipart` option that can be used to manually construct any `multipart/[type]` body, including a `multipart/form-data` one (of course we're using the `form-data` module for that multipart type, because it's more polished solution).
