### ISSUE TITLE
Emit event when request leaves connection pool?

### ISSUE THREAD

**Issue by juesato** [request/request#1694]
Hi,

I'm trying to open a duplex connection to a server with simultaneous GET and POST requests. However, since I am sending many requests at once, I think that sometimes the corresponding GET and POST requests aren't sent together. Is there any way I can monitor when each request is actually sent out?

Thanks!

**Comment by simov** [comment]
I'm not sure what your actual setup is, but you can open two separate persistent sockets, and send requests to both of them at the same time. Then you just have to sync them on response.

**Comment by juesato** [comment]
Thanks! Got it worked out.

I also ended up using the `on.('socket')` event to help debug my issue.
