### ISSUE TITLE
Get bytes_sent for logging from response?

### ISSUE THREAD

**Issue by nodesocket** [request/request#1695]
What is the best way to get "bytes_sent" from a response object? For example?

```js
    request('http://www.google.com', function (error, response, body) {
         console.log(response.bytesSent);
    });
```

I assume doing the following is not best practice:

```js
    request('http://www.google.com', function (error, response, body) {
         console.log(body.length);
    });
```

Neither is:

```js
    request('http://www.google.com', function (error, response, body) {
         console.log(response.headers['content-length']);
    });
```

**Comment by simov** [comment]
I think checking the `content-length` header would be the right thing to do. In case the response is `chunked` you should count the received bytes in the `on('data')` event handler.

**Comment by simov** [comment]
@nodesocket any new update on this? Closing for now.
