### ISSUE TITLE
rejectUnauthorized, requestCert, agent

### ISSUE THREAD

**Issue by mike-aungsan** [request/request#1697]
Can anyone explain me what exactly these three options does? 

  rejectUnauthorized: false,
  requestCert: true,
  agent: false

Many Thanks

**Comment by pyhedgehog** [comment]
1. cert, agent, rejectUnauthorized and some others derived from [https](https://nodejs.org/api/https.html#https_https_request_options_callback) module.
2. requestCert documented in [tls](https://nodejs.org/api/tls.html#tls_tls_createsecurepair_context_isserver_requestcert_rejectunauthorized) module.
