### ISSUE TITLE
Bad autodocumentation

### ISSUE THREAD

**Issue by djshapiro** [request/request#1698]
The "All Available Options" link under the table of contents points to "https://www.npmjs.com/package/request#requestoptions-callback" when it should actually point to "https://www.npmjs.com/package/request#request-options-callback".

**Comment by simov** [comment]
Yep, that's a known issue https://github.com/request/request/pull/1624

Unfortunately this breaks them here (GitHub). I think there were a couple of issues reported in https://github.com/npm/newww, feel free to open up another there, and let them know that's still an issue.
