### ISSUE TITLE
Use fork of tough-cookie-filestore to fix its issues

### ISSUE THREAD

**Issue by vladh** [request/request#1699]
Hi, I noticed that in mitsuru/tough-cookie-filestore#3 @nylen mentioned you would like to use a fork of `tough-cookie-filestore` as it has a number of issues that aren't being fixed.

I created a fork for my own use at [vladh/tough-cookie-filestore](https://github.com/mitsuru/tough-cookie-filestore/compare/master...vladh:master) — let me know if you'd like to use it and whether or not I can help with this. The fork includes fixes for:

* mitsuru/tough-cookie-filestore#2
* mitsuru/tough-cookie-filestore#3
* mitsuru/tough-cookie-filestore#8

If you've already resolved this issue, sorry for not searching enough.

**Comment by simov** [comment]
Hi, @vladh, I'm not entirely sure what the `use a fork of tough-cookie-filestore` sentence means in the context of this module.

There is no cookie-store specific tests added in https://github.com/request/request/pull/1213 either. So you are free to use any `tought-cookie` compatible store as long as it works for you :)

@nylen @lalitkapoor ?

**Comment by lalitkapoor** [comment]
@vladh thanks for addressing issues in mitsuru's store. In the request library we allow people to choose any 3rd party store to store their cookies. If a store is not passed into the jar function then by default it uses the in-memory store. We don't actually bundle any cookie stores with request.

That said, People are often looking for ways to persist their cookies and providing options in a readme would help find a solution faster. It might make sense to link to your repo in the tough-cookie readme or the request readme as a 3rd party cookie store option.

**Comment by vladh** [comment]
I see — integrating something like this into the documentation makes sense and I can make a short pull request based on that. (Unless @nylen had something else in mind?)

**Comment by simov** [comment]
Closing for now, thanks for the feedback. @vladh fell free to submit PR about the docs.

**Comment by bchr02** [comment]
@vladh Thanks for creating your own updated fork of [tough-cookie-filestore](https://github.com/mitsuru/tough-cookie-filestore). It's a shame that @mitsuru is not able to review and merge all those [open PR](https://github.com/mitsuru/tough-cookie-filestore/pulls). It would be awesome if you could submit a PR [here](https://github.com/request/request) to update [README.md](https://github.com/request/request/blob/master/README.md) with [your fork](https://github.com/mitsuru/tough-cookie-filestore/compare/master...vladh:master) of tough-cookie-filestore. Any chance you could do this? Thanks.

**Comment by bchr02** [comment]
basically, one would need to:

```
npm install https://github.com/vladh/tough-cookie-filestore.git --save
```

instead of:

```
npm install tough-cookie-filestore --save
```

But I don't want to send a PR with these changes unless you are willing to support your fork.

**Comment by vladh** [comment]
@bchr02 I would not be able to support the fork at this point, I think the repo should just be handed over to anyone who is willing to do that, and the README updated with that repo. Thanks for the comment.
