### ISSUE TITLE
Request working inconsistently between 0.10 and 0.12 on Docker

### ISSUE THREAD

**Issue by Priyanky** [request/request#1701]
I am using node request module for calling Docker stats APIs (REST over HTTP).
But the request module is behaving wierd 
Call sequence is as follows
a) Call the docker apis to get containers
b) get the container name to get further details

 1. In my local mac the call sequence is working fine
 2. When I containeraise it into a centos system and run from boot2docker, The first call succeeds but second call get hung permamently  
    see the strace below. Any one encountered this wierd behaviour?.
    I downgraded my node to v0.10.32 ans the request module version is request@2.58.0
    
 

        futex(0x7f66fc0008c8, FUTEX_WAKE_PRIVATE, 1) = 1
        futex(0x7f66fc0008c8, FUTEX_WAKE_PRIVATE, 1) = 1
        write(2, "Error: connect ECONNREFUSED\n    "..., 125Error: connect ECONNREFUSED
            at errnoException (net.js:904:11)
            at Object.afterConnect [as oncomplete] (net.js:895:19)
        ) = 125
        futex(0x7f6704590a64, FUTEX_WAKE_OP_PRIVATE, 1, 1, 0x7f6704590a60, {FUTEX_OP_SET, 0, FUTEX_OP_CMP_GT, 1}) = 1
        futex(0x7f6704590a20, FUTEX_WAKE_PRIVATE, 1) = 1
        futex(0x7f66fbfff9d0, FUTEX_WAIT, 241, NULL) = 0
        exit_group(8)                 
        
              = ?

Code is as follows

```js
var options = {};
var agentOptions ={};


console.log('Collecting Docker Statistics');
logger.info('Collecting Docker Statistics');

options.url ="http://<IP>:<port>/somepath";

options.method = 'GET';
options.tunnel = false;
options.timeout = 80000;


console.log('calling API!');
logger.info('calling API!');

request(options,  function (error, response, body) {

    if (error) {
       
        logger.info("Error Getting details %e ", error);
        callback(error, null);
    }
    else {
       
        logger.info("Success Getting details: %s", response);
        callback(null, body);
       
    }

}).on('error', function(err) {
// Handle error
logger.info("Error Getting Container details %e ", err);
```

**Comment by simov** [comment]
Add [request-debug](https://www.npmjs.com/package/request-debug) to your project and paste the debug log here. Alternatively this may help you figure out the problem on your own.
