### ISSUE TITLE
First call to HTTPS causes hanging in Electron

### ISSUE THREAD

**Issue by DerNivel** [request/request#1702]
I'm using **request** in my Electron application and the first request to an HTTPS-API causes the application to hang, a HTTP request not! It seems that something blocks the thread ...

**Comment by simov** [comment]
I just used the [quick start example](http://electron.atom.io/docs/v0.29.0/tutorial/quick-start/) and pasted this code there:

```js
var request = require('request')

request.get('https://github.com', function (err, res, body) {
  console.log(res.statusCode)
})
```

Seems to be working for me. Can you provide a short code example or gist to reproduce the bug?

**Comment by DerNivel** [comment]
With your code example the rendering of the applications hangs (css animation hangs, hover event handlers react after the hanging) for about 2 seconds.

**Comment by simov** [comment]
Ok, can you make a test request using the core `https` module and see if it hangs with it?

**Comment by DerNivel** [comment]
Sorry, I had problems with my Windows 10 Upgrade.
With the core `https` module the same happens ...
That's strange that it seems to happen only on my computer. On Win 8 as well as on Win 10
