### ISSUE TITLE
Maximum parallel pipes to fs

### ISSUE THREAD

**Issue by ChiefORZ** [request/request#1703]
I've created a Question on Stackoverflow.

Maybe it has something to do with the request Library

If you could take a look at it, thanks!
http://stackoverflow.com/questions/31707842/maximum-parallel-pipes-to-fs

**Comment by LoicMahieu** [comment]
Not related to `request`. Your code sample is broken and the user "Bergi" has highlight this is in his comment.
Please use issues only for reporting bugs and for feature discussion.
