### ISSUE TITLE
IPv6 :: is misinterpreted 

### ISSUE THREAD

**Issue by Munter** [request/request#1705]
I ran across this problem in a test scenario. I create an ad-hoc express server and tell it to listen on port 0, then get the servers info about address and port in order to request data from it. Pretty standard for test setups. However in node 0.12 (0.12.2 in my case) an express server returns IPv6 address info where localhost is represented as `::`. The request module seems to interpret this in a way where any request goes to `/::/path` instead of `/path`.

Example setup:
```js
var express = require('express');
var request = require('request');

var serverInfo = express().use(function (req, res) {
    console.log('URL', req.url);

    res.end('Hello World');
  })
  .listen(0)
  .address();

var url = 'http://' + serverInfo.address + ':' + serverInfo.port;

console.log('requesting', url);

request(url);
```

Console output:
```
$ node index.js 
requesting http://:::44596
# using node request module
URL /:: 

# using curl
URL /
```

**Comment by Munter** [comment]
When I manually request `http://127.0.0.1:44596` I get the expected `URL /`

**Comment by msiebuhr** [comment]
Loopback on IPv6 is `::1`, and I'm pretty sure `::` doesn't work. At least I've yet to see it in the wild... Ping6 also fails to find anything on that address.

Anyway, IPv6's in URLs has to be bracketed, ex `http://[::1]:44596/path`, so the embedded : doesn't not get confused with the port number. See [IPv6 adresses](https://en.wikipedia.org/wiki/IPv6_address#Literal_IPv6_addresses_in_network_resource_identifiers) on wikipedia.

**Comment by Munter** [comment]
Ah! You learn every day. When I follow the above insructions, aka doing it right, it works as expected. Closing :)
