### ISSUE TITLE
nodejs sends different request from the browser (binary data)

### ISSUE THREAD

**Issue by novellizator** [request/request#1707]
Is that somehow possible?
I'm running the same code on both nodejs and browser and from node.js everything works fine, 
from browser (extension) I receive 400 Bad Request error.

```js
    function SendSyncRequestWithAccessToken(accessToken, db, cb) {
      let syncRequest = new Uint8Array(request.toArrayBuffer());
      request.post({
        url: MY_URL
        qs: {
          'client': 'Google Chrome',
          'client_id': config.clientId
        },
        headers: {
          'Content-Type': 'application/octet-stream',
          'Authorization': 'Bearer '+ accessToken
        },
        encoding: null, //  if you expect binary data
        body: syncRequest
      }, (error, response, body) => {
        console.log('error', error,'body', body);
        if (!error) {
          readSyncRequest(body, cb);
        }
      });
    }
```

Plus issue 2, I believe: when im currently at "chrome-extension://EXTENSION_CODE/popup.html"
and MY_URL :=  'http://localhost'
Then it actually sends a request to "chrome-extension://localhost:80/chrome-sync/command?client=Google%20ChromeBLHABLAHBLAH" so it has this chrome-extension prefix although it clearly shuold NOT.
```hml
<img width="599" alt="screen shot 2015-07-31 at 12 13 11" src="https://cloud.githubusercontent.com/assets/2641229/9005356/d6e94176-377d-11e5-8e3b-608a7196bb81.png">
```

**Comment by simov** [comment]
@novellizator try using [jbinary](https://www.npmjs.com/package/jbinary) instead.
