### ISSUE TITLE
"forever" option is useless in node 0.12.*

### ISSUE THREAD

**Issue by calibr** [request/request#1709]
because it's creates new agents every request, for example:
```js
var request = Request.forever({
  maxSockets: 2
});

var r1 = request("http://google.com", function() {});
var r2 = request("http://google.com", function() {});

console.log(r1.agent === r2.agent); //prints false, but should be true
```
Problem is here https://github.com/request/request/blob/master/request.js#L486 .

This can be fixed by replacing this line by something like this:
```js
self.agentClass = self.httpModule.Agent;
self.agentOptions.keepAlive = true;
```

Such behaviour makes sockets not reusable, because creates new pool(agent) every http request.

**Comment by simov** [comment]
Generally speaking the `forever` should not be used in anything higher than node 0.10 (as stated in the docs), see https://github.com/request/request/pull/1671 for details. Your fix proposal looks good :+1:
