### ISSUE TITLE
Is there any time information for each request?

### ISSUE THREAD

**Issue by mike442144** [request/request#1710]
I wanna get time span between request and response. Is there any lib based on `request` could do this, or does `request` have API could do this?

Thanks first.

**Comment by simov** [comment]
> time - If true, the request-response cycle (including all redirects) is timed at millisecond resolution, and the result provided on the response's elapsedTime property.

Found at the bottom of the [options section](https://github.com/request/request#requestoptions-callback), is this what you are looking for?

**Comment by mike442144** [comment]
@simov It is what I want, thanks a lot.
