### ISSUE TITLE
HPE_INVALID_CONSTANT: Add error hint that it might be TCP or other non-HTTP endpoint

### ISSUE THREAD

**Issue by plato-cambrian** [request/request#1713]
I encountered this error today: https://github.com/EventStore/EventStore/issues/574
The code appears to indicate that something unexpected was found trying to parse data from a connection as an HTTP response.
Turned out I was making a POST request to a port with Eventstore's TCP listener instead of the correct HTTP port. I didn't know request would even _try_ connecting to non-http endpoints, so it took me some help to understand and diagnose.

I understand now that includes responses that don't begin with "HTTP", but my first google searches led me to believe that the HTTP server was running but had a problem sending responses.

I'd like to add a hint if parsing fails on the first byte.
Does the error come via request or node's `http` library?
Is there an appropriate place in the request codebase to attach extra info to the error?

---

Actual error:
`[Error: Parse Error] bytesParsed: 0, code: 'HPE_INVALID_CONSTANT'`  

My suggestion:
`[Error: Parse Error] bytesParsed: 0, code: 'HPE_INVALID_CONSTANT', message: 'Failed at first byte, is this an HTTP response?'`
#1706 is also seeing this error (they are talking to youtube via a proxy server, so possibly one of those sent bad responses?)

Here is a repro for making a request to a TCP server:

``` js
require('net')
.createServer(handler)
.listen(9958, 'localhost');
function handler(connection){
  connection.write('go away');
  connection.pipe(connection);
  connection.end();
}

require('request')
.get({ uri: 'http://localhost:9958' }, callback);

function callback(err, res, body){
  console.log(arguments);
  process.exit();
}
```

**Comment by gregoryyoung** [comment]
What happens if you accidentally connect to port 53? Or perhaps 23?

**Comment by simov** [comment]
@plato-cambrian  `HPE_INVALID_CONSTANT` meaning _**H**TTP **P**arse **E**rror - Invalid Constant_ should be enough to understand that the response is malformed. Of course if you know what the **HPE** acronym stands for.

If the Node's HTTP Parser thinks that the data chunk is invalid, that implies that the server is non HTTP compatible one.

As @trevnorris suggests [here](https://github.com/joyent/node/issues/8514#issuecomment-58556129) you can parse the raw response data by yourself in such cases.

**Comment by plato-cambrian** [comment]
Thanks for the further information. My guess was "HTTP Protocol Error."

I opened the issue here because (to me) `request` is a convenience layer and noob-friendly wrapper on top of node's lower level `http`, so `request` would be an appropriate place to remind noobs that:
> "HPE_INVALID_CONSTANT not only occurs when you connect to an HTTP endpoint that sends broken responses, but also when you connect to a non-HTTP socket endpoint."

What do you guys think? Are the benefits worth the costs?

**Comment by simov** [comment]
I'm totally getting your point. The text you are quoting basically says the same thing in two different ways, HTTP is on top of TCP so non compliant HTTP server means exactly that.

Now the `HPE_INVALID_CONSTANT` error is a bit cryptic I agree. Without the background info provided in this thread I would know what the **HPE** stands for.

So you can submit a PR with some better error message if you want, I'm not sure how this will blend with the current code base, but still the message should be something along the lines of:

```
HTTP Parse Error - Invalid or no HTTP headers to parse!
```

**Comment by Neylanio** [comment]
I used headers: { "Refer": "passed some url" }

it's done
