### ISSUE TITLE
Q doesn't enjoy POST requests, is okay with GET though.

### ISSUE THREAD

**Issue by Confuseh** [request/request#1714]
I am using Q promises.
Whenever I request with GET method deferred resolves just fine,
Whenever I request with POST, deffered doesn't resolve at all. 

Example where works: 
```
function fnGet() {
	defer = Q.defer();
	request("http://google.com/", function(err, res, body) {
		defer.resolve();
		return defer.promise;
	});
}

fnGet().then(function() {
	console.log("Got document!"); // Is triggered
});
```

Where doesnt:
```
function fnPost() {
	defer = Q.defer();
	request({url: "http://somesitethatacceptspost.com/form", form: {somekey:"value"}}, function(err, res, body) {
		defer.resolve();
		return defer.promise;
	});
}

fnPost().then(function() {
	console.log("Posted data!"); // Isn't.
});
```

**Comment by calibr** [comment]
To make post requests you need to set `method: "POST"` in options, or use `request.post` method. So this code works good for me:

```
var Q = require("q"),
    request = require("request");

function fnPost() {
  defer = Q.defer();
  request({
    method: "POST",
    url: "http://somesitethatacceptspost.com/form",
    form: {somekey:"value"}
  }, function(err, res, body) {
    defer.resolve();
  });
  return defer.promise;
}

fnPost().then(function() {
  console.log("Posted data!"); // prints "Posted data!"
});
```

**Comment by Confuseh** [comment]
Hm.. I'll certaintly will try that, just found it weird that with `request.post` just... doesnt work

**Comment by simov** [comment]
@Confuseh It should work with `request.post` as well. Also note that you can use `bluebird` (see [usage](https://github.com/request/request/blob/master/tests/test-promise.js)) or the [request-promise](https://github.com/request/request-promise) module.

**Comment by LoicMahieu** [comment]
I don't think `fnGet` ever works. Promise is never returned by `fnGet`. Returning promise in the request callback is useless.

Working sample:
```js
var request = require('request');
var Q = require('q');

function fetch() {
  defer = Q.defer();

  request({
    url: 'http://httpbin.org/post',
    form: {somekey:"value"}
  }, function(err, res, body) {
    defer.resolve();
  });
  
  return defer.promise;
}

fetch().then(function () {
  console.log('Yeah');
});
```
