### ISSUE TITLE
Getting errors when doing a request in Windows

### ISSUE THREAD

**Issue by npgarcia** [request/request#1718]
I am trying to get a bunch of links in an array, and of each link doing a request to server to verify that I have a 200 status code:

```js
links.forEach(function(link){
    link.getAttribute("href").then(function(text){
        request.get(text, function (err, res, body){
            expect(res.statusCode).to.equal(200,"No response 200 from page "+text);
        });
    });
});
```

This works perfectly in OSx but when running in Windows I get:

```
at Request._callback (C:\[omitting for security reasons].js:85:26)
      at Socket.socketOnEnd [as onend] (http.js:1573:9)
      at _stream_readable.js:944:16
```

**Comment by LoicMahieu** [comment]
Do you have a example of `text` value that make the request fail ?

**Comment by npgarcia** [comment]
It is an url like http://www.google.com

**Comment by npgarcia** [comment]
Update:
It seems that is only happening when Jenkins fires the test execution.
I don't have the same problem when running directly in windows.
