### ISSUE TITLE
How can I ensure my request URL isn't encoded?

### ISSUE THREAD

**Issue by AlexChesters** [request/request#1724]
I want to make a request from a string. I don't want it encoded whatsoever, I'd like request to make a request to the string I provide without modifying it whatsoever. Is this possible?

**Comment by simov** [comment]
Your URL string is parsed using the [url](https://iojs.org/api/url.html) module. You can pass such object to request:

```js
var u = url.parse('string')
// modify some properties of u
// then pass it to request
request({uri:u})
```

A short code example that reproduces the behavior you expect may be helpful as well.

**Comment by simov** [comment]
@AlexChesters this may help you https://github.com/request/request/issues/1678#issuecomment-121914470

**Comment by mrlove** [comment]
I am faced with the exact same situation.

I do call request like:

```
request({
  url: model.url,
  method: model.method,
  strictSSL: false
})
```

it works the most time, but at one url it just encodes and the server answers with something like:
The requested URL "&#47;********" , is invalid.

I can not figure out why... Can someone help me out with this issue?

**Comment by mrlove** [comment]
Fixed. Thanks.
