### ISSUE TITLE
How to make Request with kerberos "Negotiate" Auth header?

### ISSUE THREAD

**Issue by rrkkumar** [request/request#1725]
We are request module and to connect to external web API. We use IISNode and Kerberos. It is a typical double hop issue. We have set KCD between the node server and the external rest api sever. Not sure what Auth headers to use.

**Comment by simov** [comment]
This might help you https://github.com/request/request/issues/997

**Comment by rustyconover** [comment]
See my last PR: https://github.com/request/request/pull/1966
