### ISSUE TITLE
Response body on errors is undefined?

### ISSUE THREAD

**Issue by jamiewinder** [request/request#1728]
Not sure if this is be design, but if I send a request and get an error status code back (4xx), then how can I get access to the response body? e.g.
```
request.get({ url: "http://url.that/will/404", json: true} function(error, response, body) {
   console.log(body); // logs 'undefined'
});
```
I have a service which returns JSON-encoded errors objects, but these seem to be ignored on any non-success result?

**Comment by jamiewinder** [comment]
Sorry, looks like this was my fault!

**Comment by RobertWarrenGilmore** [comment]
I am currently having this same issue. How did you fix it?

**Comment by jasonmendes** [comment]
@RobertWarrenGilmore @jamiewinder Same problem here now - how did you fix it?

**Comment by jamiewinder** [comment]
@jasonmendes @RobertWarrenGilmore - Sorry, I don't recall! I think I was doing something wrong elsewhere. I've just checked over my code again and I'm not doing anything special there, it looks like the code I posted.

**Comment by jasonmendes** [comment]
Thanks for checking! I'm having a weird issue where I run over a Promise'd
Array and request each endpoint. The first run works fine, but then after
that I get socket hang up errors or an undefined body + response. It's
weird...

**Comment by RobertWarrenGilmore** [comment]
@jamiewinder, sorry, but I don't recall how I got around this. This might be related to a problem that I had where IE and Edge don't handle 401 very well, so I ended up just not using 401 anywhere in my REST API.

**Comment by jasonmendes** [comment]
Thanks @RobertWarrenGilmore -- I actually found that I needed to use `forever: true` in the options for the API I was working with! :)
