### ISSUE TITLE
Is it possible to pipe between net.Socket and request.get (or post, put etc.)?

### ISSUE THREAD

**Issue by fansgit** [request/request#1729]

**Comment by mmalecki** [comment]
@fansgit yes, it is.

```js
net.createConnection({ host: 'localhost', port: 3337 })
  .pipe(request.post('http://localhost:3338/'));
```

Will pipe from a socket on port 3337 to a POST request to a HTTP server on port 3338.

**Comment by fansgit** [comment]
The actual pipes I expect are `socket data` | `request body` and `request body` | `socket data`? Does it work?

**Comment by fansgit** [comment]
@mmaleck I tested your example and found the pipe unexpectedly replaced `socket data` to not just `request.post body` but the full `request`. Would you mind re-opening this issue?
