### ISSUE TITLE
using request.get response in the "pipe" URL

### ISSUE THREAD

**Issue by ildella** [request/request#1730]
Hi, I cannot find a way to create a flow of get().pipe() that allow me to compose the  request in pipe() with some data I get in the original get(). 
It seem that

```js
request
  .get(someUrl)
  .on('response', function(response) {
     // get data from the response to update someNewUrl
  })
  .pipe(request
    .get(someNewUrl)
```

someNewUrl is binded at the beginning, even if I pass a funcion, is evaluated at "build time" not after the first GET has computed the "on response" part. 

Is probably my fault but I cannot find a proper way to create dynamically generated flows, so I am forced to code a custom flow logic with  

```js
//       if (response1.statusCode == 200) {
```

but one of the point of Requests should be build composable flow, right? 

Sorry to ask here but I couldn't find any other place where to ask some questions. 
Thanks.

**Comment by calibr** [comment]
`someNewUrl` is binded at the beginning because Request is asynchronous. In your code you create two simultaneous requests, one pipes to another(someUrl -> someNewUrl), if you need to obtain `someNewUrl` from response object, use something like this:

```js
request
  .get(someUrl)
  .on("response", function(res) {
    // ... getting someNewUrl from res ...

    res.pipe(request.post(someNewUrl));
  });
```
