### ISSUE TITLE
<CookieJar> has no method 'setCookie'

### ISSUE THREAD

**Issue by ildella** [request/request#1731]
I've tried the very basic code: 

var j = request.jar();
var cookie = request.cookie('key1=value1');
var url = 'http://www.google.com';
j.setCookie(cookie, url);

And the output (with node 0.10)

j.setCookie(cookie, url);
  ^
TypeError: Object #<CookieJar> has no method 'setCookie'

What could it be? Thanks.

**Comment by lalitkapoor** [comment]
@ildella What version of request are you using?

I just tried the following with the latest version

```javascript
var request = require('request')

var jar = request.jar()
var cookie = request.cookie('key1=value1')
var url = 'http://www.google.com'

jar.setCookie(cookie, url)
console.log(jar.getCookies(url))
```

output
```
[ Cookie="key1=value1; Path=/; hostOnly=true; aAge=1ms; cAge=2ms" ]
```

**Comment by ildella** [comment]
2.57.0

I upgraded  to 2.60.0 and it works, thanks.

**Comment by MariSelvanDev** [comment]
How to extend the age of cookie?
