### ISSUE TITLE
Question about perfs and using string as the body param

### ISSUE THREAD

**Issue by michelsalib** [request/request#1732]
Hello,

It might be a newbie question, but my team team recently faced performance issues (~50ms loss) when using the body param as a string. We tracked down the time loss to be around this: https://github.com/request/request/blob/master/request.js#L436

We decided to apply a workaround by not using the body param, and instead hook to call [.end](https://nodejs.org/api/http.html#http_request_end_data_encoding_callback) native function with a plain string. The goal was to avoid this Buffer transformation that did not seam to provided any added value.

My questions are the following:
1. Does anyone face this issue, or knows what is going wrong?
2. Is there any recommendation, best practices?
3. Would it make sense for me to send a PR avoiding useless Buffer transformation?

**Comment by simov** [comment]
That's interesting, the tests are passing without that line, and these lines seems to be [covered](https://codecov.io/github/request/request/request.js?ref=e168bc6e932cca15a2f608b43c17ca6294d4db82#l-434) as well.

Feel free to submit a PR about it, just remove the entire condition, seems to be unneeded idd.

**Comment by michelsalib** [comment]
Thanks @simov I have opened the PR.
