### ISSUE TITLE
request pipe not work with specific image URL

### ISSUE THREAD

**Issue by nvcken** [request/request#1734]
image url    "http://efaucets.resultspage.com/thumb.php?aspect=true&s=220&f=http%3a%2f%2fwww.efaucets.com%2fimages%2fDeltaFaucet%2f58045-RB.jpg",
```
  request.head(url, function(err, res, body){
    if(err) callback(err);
    else {
      request(url).pipe(fs.createWriteStream(dest)).on('close', callback);
    }
  });
```
Got an error image file
If I use raw http module to download image, It works.
What wrong here ?
I tried with both lastest and older (2.58.0) version

**Comment by simov** [comment]
You probably have to set the `encoding` option:

```js
request(url, {encoding:null}).pipe(fs.createWriteStream(dest)).on('close', callback);
```

You can read about it in the docs.

**Comment by nvcken** [comment]
I have tried ```encoding```

**Comment by simov** [comment]
Ok, what exactly is the error then?

> Got an error image file

I thought your file get mangled because of the wrong encoding.

**Comment by nvcken** [comment]
The file is saved. But only 127 bytes.
Content of file is 
```
<?xml version='1.0' encoding='UTF-8'?><Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message></Error>
```

**Comment by nvcken** [comment]
Url header show
```
  'transfer-encoding': 'chunked',
```
Is this a clue?

**Comment by simov** [comment]
The example from your first comment works:

```js
var fs = require('fs')
var request = require('request') // 2.60
var url = 'http://efaucets.resultspage.com/thumb.php?aspect=true&s=220&f=http%3a%2f%2fwww.efaucets.com%2fimages%2fDeltaFaucet%2f58045-RB.jpg'
var dest = 'file.jpg'
function job (callback) {
  request.head(url, function(err, res, body){
    if(err) callback(err);
    else {
      request(url).pipe(fs.createWriteStream(dest)).on('close', callback);
    }
  });
}
job(function () {
  console.log('DONE!')
})
```

Just copy/paste it in a file and run it.

**Comment by nvcken** [comment]
I run it on my machine , it do not work.
My node version v0.12.4
Which is your node version?

**Comment by nvcken** [comment]
Ok, I run it away standalone (away from framework). It works.
I will try more work to find out error.
Thanks for help

**Comment by nvcken** [comment]
It seem the incomplete file writed before callback.
It may cause by ```'transfer-encoding': 'chunked'``` and has no ```content-length``` header
Because after callback , I process thumbnail of image, but seem this moment it has not completely download yet - got an incorrect image file.
So if after callback I dont do anything else , image downloaded right.
Then it is also explained about standalone run code work fine.

How can I ensure pipe complete file write then callback in this situation?

**Comment by nvcken** [comment]
I figures it out. I got error at another code process. No matter of request.
Thanks again
