### ISSUE TITLE
Empty body is returned for a connection with transfer-encoding: chunked and no content-length

### ISSUE THREAD

**Issue by javgh** [request/request#1735]
While making a request to the server at metaexchange.info, I'm getting a zero-length body returned:

```
var request = require('request');

var url = 'https://metaexchange.info/api/1/submitAddress';
var data = 'arg1=1';
request.post({url: url, data: data}, function(err, res, body) {
    console.log(res.headers);
    console.log(res.body);
    console.log('length: ' + res.body.length);
});
```

Output:
```
{ server: 'Mono-HTTPAPI/1.0',
  date: 'Tue, 18 Aug 2015 16:18:21 GMT',
  'content-length': '0',
  connection: 'close' }

length: 0
```

A similar request implemented with needle:
```
var needle = require('needle');

var url = 'https://metaexchange.info/api/1/submitAddress';
var data = 'arg1=1';
needle.post(url, data, function(err, res) {
    console.log(res.headers);
    console.log(res.body);
});
```

Output:
```
{ 'access-control-allow-origin': '*',
  'content-type': 'application/json',
  server: 'Mono-HTTPAPI/1.0',
  date: 'Tue, 18 Aug 2015 16:19:12 GMT',
  connection: 'close',
  'transfer-encoding': 'chunked' }
{ message: 'Missing parameter', error: 'MissingParameter' }
```

The line `{ message: 'Missing parameter', error: 'MissingParameter' }` is the payload I'm expecting to see.

Is there some option I'm missing or am I otherwise not using the API correctly?

**Comment by nvcken** [comment]
It looks like the API you calling expects request post data as multipart/form-data.
You should try it

**Comment by calibr** [comment]
it seems metaexchange.info server sensitive to `content-length` header case. Request lib send it as `content-length: 6`, Needle: `Content-Length: 6`.

you can overwrite Content-Length header:

```js
var url = 'https://metaexchange.info/api/1/submitAddress';
var data = 'arg1=1';
request.post({
  url: url,
  body: data,
  headers: {
    "Content-Length": 6
  }
}, function(err, res, body) {
  console.log(res.headers);
  console.log(body);
  console.log('length: ' + body.length);
});
```

It's not a Request issue, because header names are case-insensitive(according to RFC).

**Comment by javgh** [comment]
Aw, nice troubleshooting, that's indeed the problem! I'll file a bug with the server component. Thank you!

**Comment by wildbunny** [comment]
Ahhhh, good find! I'd been wondering where those Missing parameter error logs where coming from! I'll get that fixed in the next build :)

**Comment by simov** [comment]
Yep, a very common issue we got here - the relevant bits of the [spec](https://tools.ietf.org/html/rfc7230#section-3.2).

**Comment by wildbunny** [comment]
This has now been fixed :)
