### ISSUE TITLE
HTTPS requests are changed to `http` with port 443 with browserify

### ISSUE THREAD

**Issue by nicola** [request/request#1737]
I have this code here:

```
request.get('https://rww.io', function(err, body, res){ 
  throw err
})
```

when I run with `node` everything is fine, however, when I browserify this and run it in the browser I get this:

```
Fetch API cannot load http://rww.io:443/. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://127.0.0.1:8000' is therefore not allowed access.
127.0.0.1/:1 Uncaught (in promise) TypeError: Failed to fetch
    at TypeError (native)
```

In fact the website does not accept `http://rww.io:443`, but it does for `https://rww.io`.
Why does request change my URL?

Thanks!

**Comment by midgethoen** [comment]
+1 I am having the same issue

**Comment by mallendeo** [comment]
+1 same here

**Comment by simov** [comment]
We don't have such error message in request: `Fetch API cannot load...`, probably something else is changing your code.
