### ISSUE TITLE
Tough cookie requirement for cookie jar

### ISSUE THREAD

**Issue by 18nleung** [request/request#1740]
For a basic implementation of cookies, it doesn't seem as if `tough-cookie` is necessary.  My authentication is still preserved if I create a new request in the callback of a post request in which I authenticate.  To activate cookies, all I had to do was write `request = require('request').defaults({jar: true})`.

The `README.md` mentions that `tough-cookie` is required, so if an update to `request` rendered it obsolete or something it would be helpful if the `README` was updated too.

Was `request` updated?  Or am I implementing request in a non-traditional way?

**Comment by LoicMahieu** [comment]
I merged PR #884 but it was a mistake. `tough-cookie` is builtin and required by `request` for a while. There is no need for user to install it manually. So I revert the PR in #1750. Sorry for confusion.
