### ISSUE TITLE
Use Request.post with iconv-lite

### ISSUE THREAD

**Issue by DingGGu** [request/request#1741]
Hello, I tried to use request with iconv-lite,
but i've got some problems.

I know `Iconv-lite` encode method throws a `Buffer`

Here is some Korean Text `테스트` `(UTF-8)`
I want to covert `EUC-KR`.

``` javascript
var str = "테스트";
var sms = iconv.encode(new Buffer(str), 'euc-kr');
request.post({
    uri: 'http://some_http_server/',
    form: { // Encoding of form data should be EUC-KR.
        "sms": sms,
        "date": "0"
    }
}, function (err, res, body) {
    if (err) {
        callback(err);
    } else {
        console.log(body);
        callback(null);
    }
});
```

but `Request` does not send a `EUC-KR` encoding strings.
I know NodeJS. when change to string type that has only `UTF-8` encoding

I don't understand what should i do. because my skill is not good.
somebody help with me?

**Comment by simov** [comment]
You can try with the `iconv.extendNodeEncodings()` method - not perfect, but it might work:

```js
var iconv = require('iconv-lite')
iconv.extendNodeEncodings()

var str = "테스트"

var sms = iconv.encode(str, 'euc-kr')
console.log(sms.toString('utf8'))
console.log(sms.toString('euc-kr'))
```

```bash
�׽�Ʈ
테스트
```

**Comment by DingGGu** [comment]
@simov unfortunately, it doesn't work well.

Request Target Server get only `EUC-KR` encoding strings.
I tried to both those solutions but strings is not displayed: `占쌓쏙옙트` not `테스트`
