### ISSUE TITLE
multipart.js

### ISSUE THREAD

**Issue by linlingyu** [request/request#1742]
Multipart.prototype.build;
add(preamble) and add('--' + self.boundary + '--')
how to remove them with options?

**Comment by simov** [comment]
You can configure the boundary like this:
```js
request({headers:{'content-type':'multipart/[type]; boundary=[your boundary here]'}})
```

**Comment by linlingyu** [comment]
first, thank owner to answer my question~

```javascript
request({
    method: 'POST',
    uri: 'http://localhost/phpinfo.php',
    multipart: [{
        body: 'hello world~!'
    }],
    headers: {
        'content-type': 'multipart/text; boundary=m'
    }
}, function(err, response, body) {
    console.log(body);
});
```
result:

```
--m

hello world~!
--m--
```

but the string `'--m'` and `'--m--'` is not my wishes to send to web server, when web server public API get this，it will return error, so , have any way to clean the string?

**Comment by simov** [comment]
You probably don't have to use multipart then. There is no `multipart/text` content type to my knowledge. Use the `form` option instead.
