### ISSUE TITLE
Setting a Cookie with a Get Request

### ISSUE THREAD

**Issue by Blackglade** [request/request#1744]
Maybe I'm just doing this wrong, but I'm trying to set a cookie for a GetRequest and I'm doing something simple like this,

```javascript
var request = require('request');
request
  .cookie('key1=val1; Path=/; Domain=website.com;')
  .cookie('key2=val2; Path=/; Domain=website.com;')
  .cookie('key3=val3; Path=/; Domain=website.com;')
 .get('website.com/image.png')
  .on('error', function(err){console.log(err)})
  .pipe(fs.createWriteStream('test.png'));
```
I keep getting a TypeError of undefined is not a function on the 2nd .cookie() line. I'm pretty sure I'm not implementing this correctly.

**Comment by LoicMahieu** [comment]
You can not chain method `cookie`. [`request.cookie`](https://github.com/request/request/blob/f1537d6efa4106da5da0f6880d0f91681fc3616e/index.js#L79) return the result of [`Cookie.parse()`](https://github.com/SalesforceEng/tough-cookie#cookieparseheader).

Your example become:
```js
var request = require('request');
request
  .cookie('key1=val1; Path=/; Domain=website.com;')
request
  .cookie('key2=val2; Path=/; Domain=website.com;')
request
  .cookie('key3=val3; Path=/; Domain=website.com;')
request
 .get('website.com/image.png')
  .on('error', function(err){console.log(err)})
  .pipe(fs.createWriteStream('test.png'));
```

Chaining would be great in fact...
