### ISSUE TITLE
What's the idea behind this coding style in index.js?

### ISSUE THREAD

**Issue by behrangsa** [request/request#1745]
Why rather than

```javascript
// Exports
request.Request = require('./request')
request.initParams = initParams

// Backwards compatibility for request.debug
Object.defineProperty(request, 'debug', {
  enumerable : true,
  get : function() {
    return request.Request.debug
  },
  set : function(debug) {
    request.Request.debug = debug
  }
})

module.exports = request
```

You have written this section as such:

```javascript
// Exports
module.exports = request
request.Request = require('./request')
request.initParams = initParams

// Backwards compatibility for request.debug
Object.defineProperty(request, 'debug', {
  enumerable : true,
  get : function() {
    return request.Request.debug
  },
  set : function(debug) {
    request.Request.debug = debug
  }
})
```

Basically why assign `request` to `module.exports` before it is fully constructed/initialized?

**Comment by shakeelmohamed** [comment]
> Basically why assign request to module.exports before it is fully constructed/initialized?

My 2 cents as an outsider: it's done this was for logical separation between internal/external code.

The `module.exports = request` line is basically saying: "make `module.exports` point to whatever `request` points to". So, the moving `module.exports = request` to the end of the file would have the same effect.

**Comment by behrangsa** [comment]
Sorry but I have to disagree. There's nothing in that code snippet that is internal. There's the `request` object that is manipulated and then exported. So it doesn't make sense to have the export line in the middle of the file, rather than at its end.

**Comment by simov** [comment]
@shakeelmohamed have a good point, that's most likely the case.

@behrangsa I have to disagree that *the export line **is** in the middle of the file*, also there is a comment on top of that block.

**Comment by behrangsa** [comment]
@simov I think you take my use of the word "middle" **too** literally. I mean it is not at the top of the file (i.e. after `require` statements) and it is not at the end of the file (i.e. the last statement in the file).

> @shakeelmohamed have a good point, that's most likely the case.

But is it?

Here's the code snippet:

```javascript
// Exports

module.exports = request
request.Request = require('./request')
request.initParams = initParams

// Backwards compatibility for request.debug
Object.defineProperty(request, 'debug', {
  enumerable : true,
  get : function() {
    return request.Request.debug
  },
  set : function(debug) {
    request.Request.debug = debug
  }
})
```

The only thing that is exported is the `request` object. Yet it is assigned to `module.exports` before its initialization is complete.

@shakeelmohamed says:

> it's done this way for logical separation between internal/external code

Almost all of the "internal" code is written before `module.exports = request`. Then there's about 15 lines that comes after it. Correct me if I am wrong, but this doesn't sound right. What am I missing here? What am I not seeing here that you guys are?

To me the more logical and conventional way of writing this chunk of code would be this:

```javascript
// Exports
request.Request = require('./request')
request.initParams = initParams

// Backwards compatibility for request.debug
Object.defineProperty(request, 'debug', {
  enumerable : true,
  get : function() {
    return request.Request.debug
  },
  set : function(debug) {
    request.Request.debug = debug
  }
})

module.exports = request
```

But judging by you and @shakeelmohamed's comments I infer that at best this is done so because you think it makes the code more readable/logical (to which I disagree), and not for a technical reason that changes the outcome of the code.

Cheers,
Behrang

**Comment by behrangsa** [comment]
@nylen @seanstrom Could you please clarify? Looks like this chunk of code is written by you fellows.

**Comment by simov** [comment]
@behrangsa it doesn't really matter where you put the `export` statement, it's a matter of style preference:

```js
// public API
// documented
// for end users
request()
request.get()
request.post()

module.exports = request

// private API
// non documented
// for developers
request.Request
request.initParams
```

**Comment by behrangsa** [comment]
Thanks for clarification @simov. I guess now I can sleep well tonight! :smiley:

**Comment by seanstrom** [comment]
@behrangsa I would also mention that even when we're exporting before the bottom of the file, Node will evaluate the whole file when importing it. Which means the reference to request will be fully initialized and module.exports will point to that.

**Comment by behrangsa** [comment]
@seanstrom I know that. But I personally prefer my export statement to be either the first statement after require statements or the last statement in the file. Just a personal preference.
