### ISSUE TITLE
How can we use request lib in Browser?

### ISSUE THREAD

**Issue by thangchung** [request/request#1748]
I tried a lot of things to use the request lib inside the browser using JSPM. But something wrong happened, it always threw an exception like 

<pre><code>Node tls module not supported in browsers</code></pre>

How can I make it work or work around to overcome this issue?

I have posted a question at [Node tls module not supported in browsers](http://stackoverflow.com/questions/32138320/node-tls-module-not-supported-in-browsers)

**Comment by simov** [comment]
Try with `browserify` or `webpack`.

**Comment by dandv** [comment]
@simov: request doesn't work with webpack out of the box either, but there are [some workarounds](https://github.com/request/request/issues/1920).
