### ISSUE TITLE
How to handle cookies?

### ISSUE THREAD

**Issue by brunano21** [request/request#1749]
Hello, again!

I have basically the following cookie:
    { 
    name: 'JSESSIONID',
    domain: 'mydomain',
    secure: false,
    path: '/',
    value: '0000AP8HRGxRDsY5sZLlnQU8d-U:-1',
    httpOnly: false 
    }

But, how can I include it into my request?

Any suggestion would be great!
Thanks

**Comment by LoicMahieu** [comment]
There is a lot of example about how using cookies with request :
- https://github.com/request/request#requestcookie
- https://github.com/request/request#examples
- https://github.com/request/request/blob/3733c61be8ce278d0ac0e9ca6405d9079aee8181/tests/test-cookies.js#L15

You can find the documentation about `though-cookie`: https://github.com/SalesforceEng/tough-cookie#properties

```js
var request = require('request');

var j = request.jar();
j.setCookie('a=b', 'http://httpbin.org');

request.get('http://httpbin.org/get', {
  json: true,
  jar: j
}, function (err, res) {
  console.log(res.body.headers);
  // { Accept: 'application/json',
  // Cookie: 'a=b',
  // Host: 'httpbin.org' }
});
```
