### ISSUE TITLE
Empty body

### ISSUE THREAD

**Issue by ksahin** [request/request#1751]
I gave request a try, and I have some strange behavior here : 

```javascript
var request = require('request');
var cheerio = require('cheerio');

// var https = require('https');
// https.globalAgent.options.secureProtocol = 'TLSv1_method';

console.log('Starting');

var URL = 'https://boutique.laposte.fr/'


request(URL, function(error, response, body) {
	if (!error && response.statusCode == 200) {
		console.log('Succes, server respond with body : ', body);
	} else {
		console.log('Error');
	}
})

```
And the ouput : 
````
Starting
Succes, server respond with body :
```
The body is empty, I don't know if there's an SSL related issue here. 

Thank you

**Comment by simov** [comment]
You should pass the `user-agent` header (also you may need to store the cookies):

```js
request(URL, {
  headers:{'user-agent':'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.157 Safari/537.36'},
  jar:request.jar()
}, function(error, response, body) {
  debugger
    if (!error && response.statusCode == 200) {
        console.log('Succes, server respond with body : ', body);
    } else {
        console.log('Error');
    }
})
```

Just open up your browser's Developer Tools and take a look at the Request/Responses under the Network tab.

**Comment by eranbrill** [comment]
@simov  we also came across this behaviour, but with an ASP .net server, is this issue node related?
how come some API's work without and some require UA ?

**Comment by simov** [comment]
That's totally related to the server you are connecting to. If the server expects certain headers you have to pass them. You can either use the [request.defaults](https://github.com/request/request#requestdefaultsoptions) method, or wrap request with your own application logic.

**Comment by eranbrill** [comment]
Thanks,
Just Curios , how you identified this server requires userAgent?

**Comment by simov** [comment]
Used my Chrome browser, opened up the Developer Tools, and navigated to the Networking tab. Then navigated to that URL and checked out the request headers. After that it's a matter of trial and error :)
