### ISSUE TITLE
Support for FORM based authentication

### ISSUE THREAD

**Issue by jamsden** [request/request#1753]
The jazz.net and many other applications use FORM based authentication and expect the client to be a browser that displays the form, collects the user's credentials and POSTs to an authentication redirect with the j_security_check query string. 

It would be helpful if request.js supported FORM based authentication. Ideally this would be done by parsing the HTML returned in the response that initiates the FORM based challenge and determining that this is a FORM that is intended to POST with the j_security_check query. Such parsing could be difficult and unreliable. The Jazz platform works around this issue with a header extension: x-com-ibm-team-repository-web-auth-msg with value authrequired to indicate the server has initiated a FORM based authentication challenge. Clients can examine this header on an HTTP response with status code 200 and know they should POST the user's credentials in order to complete the original request.

Since x-com-ibm-team-repository-web-auth-msg is an unregistered, non-standard header, it would not be appropriate to code this directly into request.js to support FORM based authentication. However, the request.js options could be extended to include properties that specify the header name and value that indicates a FORM based challenge. Clients could then configure the request object to detect and resolve FORM based challenges for their particular server if it provides such headers.

Is this something that could be considered as an extension to request.js? If so, I'd be happy to code it up.

**Comment by simov** [comment]
Hi, @jamsden, I just registered on jazz.net and used this code to log in:

```js
var jar = request.jar()
// login
request.post('https://jazz.net/auth/login', {
  form:{
    j_username:'...',
    j_password:'...',
    redirectPage:'https://jazz.net/'
  },
  followAllRedirects:true,
  jar:jar
}, function (err, res, body) {
  if (err) console.log(err)
  console.log(res.statusCode)
  // get the navbar, just to check if the user is logged in
  request.get('https://jazz.net/servlet/navbar', {
    qs:{
      pathname:'/'
    },
    jar:jar
  }, function (err, res, body) {
    if (err) console.log(err)
    console.log(res.statusCode)
    console.log(/My Stuff/.test(body))
  })
})
```

With the first request I'm logging in. Notice the `followAllRedirects` option, that should be set to follow redirects after POST request. Also note that I'm setting up a `jar` object to keep the cookies returned from the web site.

In the second request I'm getting the navbar, which is loaded via AJAX call in the browser. Again I'm passing the stored cookie with the `jar` option. If the login is successful you have a *My Stuff* link rendered into the header, next to your user name.

Let me know if that helps.

**Comment by jamsden** [comment]
This is using proactive FORM based authentication which isn't supported by some server implementations (e.g., Tomcat). A more general approach is to respond to authentication challenges. This can be done by detecting the challenge and responding with a POST to do FORM authentication - but the request client should expect to get another challenge on any subsequent HTTP request. It is possible to wrap request to do this, but it would be useful if it was directly built in.
