### ISSUE TITLE
Add ability to send non-JSON body, and receive a parsed JSON response

### ISSUE THREAD

**Issue by shakeelmohamed** [request/request#1754]
I want a way to send a non-JSON body, but receive a JSON body response.
Is there a better way to do this?

What I'm doing this now is intercepting the data before calling a callback explicitly

```javascript
var request = require("request");
// callback is some function passed to my code
var callback = function(err, resp, body) {};

var options = {
    json: false, // added for verbosity
    body: "some string"
};
request.post(options, function(err, resp, body) {
    if (typeof body === "string") {
        body = JSON.parse(body);
        resp.body = body;
    }
    callback(err, resp, body);
});
```

I'd like to be able to do something like this (note the new `jsonResponse` property)

```javascript
var request = require("request");
// callback is some function passed to my code
var callback = function(err, resp, body) {};

var options = {
    json: false, // added for verbosity
    jsonResponse: true,
    body: "some string"
};
request.post(options, callback);
```

**Comment by simov** [comment]
You can pass anything you want in the body, and expect JSON response by setting `json` to `true`:
```js
request.post('https://...', {body:'whatever', json:true}, function (err, res, body) {})
```

**Comment by shakeelmohamed** [comment]
@simov This is true. I don't want to pass the Content-Type header though

**Comment by simov** [comment]
Just set the `content-type` header to something else. Also using the `form` or the `formData` option sets the correct `content-type` header for you.

**Comment by shakeelmohamed** [comment]
Ah this worked! I had to set the `content-type` to `application/x-www-form-urlencoded`

Thanks @simov!
