### ISSUE TITLE
How to pipe bytes to a request dynamically?

### ISSUE THREAD

**Issue by mykinator** [request/request#1756]
I have a Node server that accepts a multi-part POST, and I want to pipe the POST parts to an open request as soon as the server receives them.

Currently this is done thusly:
1. Receive multi-part POST body part
2. Save all POST body parts to file
3. fs.createReadStream(file).pipe(request)

I want to be able to do this:
1. Receive multi-part POST body part
2. pipe the body part to request immediately

Is this possible with the existing syntax? Thanks!

**Comment by simov** [comment]
That should be possible, you just have to pipe the incoming request to a new one, check out this [comment](https://github.com/request/request/issues/1664#issuecomment-117721025) for more details. You just have to set the appropriate headers and HTTP method for the new request.
