### ISSUE TITLE
Change request body after pipe to response

### ISSUE THREAD

**Issue by carlosvillu** [request/request#1757]
Hi,

I´m trying something like the following:

```javascript
app.all('*', (req, resp) => {
 const url = `${req.protocol}://some.ip.addr:80${req.originalUrl}`;
 req
   .pipe(request(url))
   .pipe(resp);
});
```

And it works perfectly. But I don't know how to proceed next. What I need to do now is to change the body as follows:

```
</body>

with

<script />
</body>
```
Any suggestions ?!

**Comment by simov** [comment]
You can buffer the whole body, modify it, and set it as a body of the new request, or pipe the incoming request to transform stream, that modifies the body as it arrives, then pipe it to the new request.

**Comment by carlosvillu** [comment]
Hi @simov ,

Thx for your answer. I was also thinking that piping the request at a TransformStream must be the right solution. And I was working on something like this:

```javascript
class TransformBody extends Transform{
  _transform(chunck, encoding, cb) {
    this.push(chunck.toString().toLowerCase());
    cb();
  }
};
```

And then,

```javascript
app.all('*', (req, resp) => {
  let body;
  const url = `${req.protocol}://195.77.179.104:80${req.originalUrl}`;
  const method = req.method.toLowerCase();
  log.info({method: req.method}, url);

  req
    .pipe(request(url))
    .pipe(new TransformBody()) 
    .pipe(resp);
});
```

But that didn´t work. I get a binary chunk in my `_transform` method and it's impossible to change it. That is, I don't get the body; instead, I get some sort of  instance or http.IncommingMessage.

Another thing that I tried was piping from the  `request` call directly:

```javascript
  req
    .pipe(request(url).pipe(new TransformBody()))   
    .pipe(resp);
```

But this didn't work either :( ... I got the body correctly in my `_transform` function, but the pipe to the resp object is broken.

Any ideas ?!

Thx a lot.

**Comment by simov** [comment]
What exactly you are trying to modify in the body? Isn't it easier to just buffer to body in those cases and modify it?

**Comment by YarGnawh** [comment]
@carlosvillu  i tried your snippet and it does transform the response to uppercase, but the response loses all http response headers. is there a way to keep it?
