### ISSUE TITLE
Login with request

### ISSUE THREAD

**Issue by anagas** [request/request#1762]
I am trying to login with this code but i get always the same Error message it seems like that my forms is wrong. 

I am able to Login with Postman and an another Application(Angularjs,http) without any errors.

```js
var request = require('request');

var options = {
    method: 'POST',
    url: 'https://hostname:8443/EnterpriseController',
    params: {a: 1},
    form: {
        "actionType": "authenticateUser",
        "reqObj": "[null,username,password,null,1]"
    },
    headers: {
        'Content-Type': 'application/x-www-form-urlencoded;charset=UTF-8'

    },
    withCredentials: true,
    rejectUnauthorized: false
};

request(options,
    function (error, response, body) {
        if (error){
            console.log("There was an error:", error);
        } else {
            console.log("Request posted successfully!", body);
        }
    }
);
```

Error Message:

```
body: ')]}\',\n{"login_err": true, "resp": [null,null,null,1]\n}\n' } ')]}\',\n{"login_err": true, "resp": [null,null,null,1]\n}\n'
```
Thanks

**Comment by anagas** [comment]
Nobody has an idea?

**Comment by simov** [comment]
Does postman have some sort of a log output? In this post it here, that might help.

**Comment by anagas** [comment]
This is what i get back as body:

)]}',
{"xsrf": [null,"security_token","xToken"]
, "resp": [null,[null,null,null,null,[[null,"Content Sources",null,null,[[null,"Web Crawl",null,null,[[null,"Start and Block URLs","startURLs"]
,[null,"Case-Insensitive Patterns","caseInsensitivePatterns"]
,[null,"Proxy Servers","crawlerProxies"]
,[null,"HTTP Headers","httpHeaders",["User Agent Name","Domain Checking on Cookies","Additional HTTP Headers for Crawler"]
]
,[null,"Duplicate Hosts","duphosts",["Duplicate Hosts","Configure Infinite Space Detection"]
]
,[null,"Coverage Tuning","crawlCoverage"]
,[null,"Crawl Schedule","crawlSchedule",["Select a Crawl Mode","Configure Backoff retries and Remove from Index Information"]
]
,[null,"Host Load Schedule","crawlLoads",["Maximum Number of URLs to Crawl","Maximum File Sizes to Download (in MBs)","ACL Size Limit","Web Server Host Load"]
]
,[null,"Freshness Tuning","freshnessHints",["Crawl Frequently","Crawl Infrequently","Always Force Recrawl","Recrawl URL Patterns"]
]
,[null,"Secure Crawl",null,null,[[null,"Crawler Access","crawlerAccess",["HTTP Basic/NTLM Authentication","Enable Kerberos Crawling","Password Protected Pdf Files"]
]
,[null,"Forms Authentication","ssoSites"]
]
]
]
]
,[]
,[null,"Connector Managers","viewConnectorManagers"]
,[null,"Connectors","viewConnectors"]
,[null,"Feeds","viewFeeds"]
,[null,"Databases","viewDatabases"]
,[null,"Google Apps","googleAppsFederation"]
,[null,"OneBox Modules","oneboxAdmin"]
,[]
,[null,"Diagnostics",null,null,[[null,"Crawl Status","crawlStatus"]
,[null,"Real-time Diagnostics","realtimeDiagnostics",["Fetch HTTP Headers for URL","View Crawl and Indexing Activity","Run Packet Capture (tcpdump)"]
]
,[null,"Crawl Queue","listCrawlQueues"]
]
]
]
]
,[null,"Index",null,null,[[null,"Index Settings","indexSettings",["Index Limits","Wildcard Indexing Settings","Metadata Indexing Configurations"]
]
,[null,"Document Dates","searchDateCreate"]
,[null,"Entity Recognition","entityRecognition",null,[[null,"Composite Entities","entityRecognitionComposite"]
,[null,"Blacklist","entityRecognitionBlacklist"]
,[null,"Entity Diagnostics","entityRecognitionDiagnostics"]
,[null,"Adjustments","entityRecognitionAdvanced"]
]
]
,[null,"Alerts","alerts"]
,[null,"Collections","viewCollections"]
,[null,"Composite Collections","compositeCollections"]
,[]
,[null,"Diagnostics",null,null,[[null,"Index Diagnostics","contentDiagnostics"]
,[null,"Content Statistics","contentTypeStats"]
,[null,"Export URLs","exportAllUrls"]
]
]
,[]
,[null,"Reset Index","resetCrawl"]
]
]
,[null,"Search",null,null,[[null,"Search Features",null,null,[[null,"Front Ends","viewFrontends",null,[[null,"Output Format","frontOutputFormat",["Page Layout Helper","XSLT Stylesheet Editor","Language Options"]
]
,[null,"KeyMatch","frontKeymatchView"]
,[null,"KeyMatch","frontKeymatchEdit"]
,[null,"KeyMatch","frontKeymatchCreate"]
,[null,"KeyMatch","frontKeymatchImport"]
,[null,"Related Queries","frontSynonymsView"]
,[null,"Related Queries","frontSynonymsEdit"]
,[null,"Related Queries","frontSynonymsCreate"]
,[null,"Related Queries","frontSynonymsImport"]
,[null,"Filters","frontFilters",["Domain Filter","Language Filter","File Type Filter","Meta Tag Filter","Query Expansion Policy","Query Expansion Policy for Meta Tags","Result Biasing Policy","Maximum expansions per wildcard term","Consider words with * as wildcards by default"]
]
,[null,"Remove URLs","frontRemoveURLs"]
,[null,"OneBox Modules","frontOneBoxModules"]
]
]
,[null,"Query Settings","queryExpView",["Configure Query Expansion","Contextual Synonyms Expansion Settings","MetaTag Query Expansion Settings","Query Parameters","Snippets Generation","Link Results","Spelling","Click-Jacking Defense","Corpus Estimates In Secure Search Results","Expand Position Type Queries"]
]
,[null,"Document Preview Module","documentPreviewAdmin"]
,[null,"Result Biasing","viewScoringPolicies",["Source Biasing","Date Biasing","Metadata And Entity Biasing"]
]
,[null,"Suggestions","manageSuggestions"]
,[null,"Dynamic Navigation","dynNav"]
,[null,"Language Bundles","languageBundles"]
,[null,"User Results","userAddedResults"]
,[null,"Expert Search","expertsearchconfig"]
]
]
,[]
,[null,"Secure Search",null,null,[[null,"Access Control","cache"]
,[null,"Head Requestor Deny Rules","denyRules"]
,[null,"Policy ACLs","policyACLs"]
,[null,"Universal Login","universalLogin"]
,[null,"Universal Login Auth Mechanisms","authForms",null,[[null,"Cookie","authForms"]
,[null,"HTTP","authBasic"]
,[null,"Client Certificate","authClient"]
,[null,"Kerberos","authKerberos"]
,[null,"SAML","authSaml"]
,[null,"Connectors","authConn"]
,[null,"LDAP","authLdap"]
]
]
,[null,"Universal Login Form Customization","universalLoginConfigHandler"]
,[null,"Flexible Authorization","flexAuthz",["Flexible Authorization","Authorization Parameters"]
]
,[null,"Trusted Applications","secureApi"]
]
]
,[]
,[null,"Diagnostics",null,null,[[null,"Search Status","frontServingStatus"]
,[null,"Real-time Diagnostics","searchRealtimeDiagnostics",["Run Packet Capture (tcpdump)","Serve-Time Profile"]
]
]
]
]
]
,[null,"Reports",null,null,[[null,"Serving Logs","customerLogs"]
,[null,"Search Reports","listReports"]
,[null,"Search Logs","listLogs"]
]
]
,[null,"GSA Unification",null,null,[[null,"Host Configuration","federationHostConfig"]
]
]
,[null,"GSA^n",null,null,[[null,"Configuration","gsanConfig"]
]
]
,[null,"Administration",null,null,[[null,"System Settings","systemSettings",["Email Notification","Default Search URL","Cookie Domain","HTTP (i.e. non SSL) Admin Console and Version Manager","Daily Status Report"]
]
,[null,"Network Settings","networkSettings"]
,[null,"User Accounts","userAccounts"]
,[null,"Login Terms","loginTermsSettings"]
,[null,"Change Password","changePassword"]
,[null,"SNMP Configuration","snmpConfig"]
,[null,"Certificate Authorities","certAuthority"]
,[null,"DNS Override","dnsOverride"]
,[null,"SSL Settings","sslSettings"]
,[null,"LDAP Setup","ldapSetup"]
,[null,"License","licenseView"]
,[null,"Import/Export","importExport"]
,[null,"Event Log","eventLog"]
,[]
,[null,"System Status","systemStatus"]
,[null,"Shutdown","shutdown"]
,[]
,[null,"Remote Support","remoteSupport"]
,[null,"Support Scripts","supportScripts"]
]
]
]
]
]
, "warnings": [null,null,null,1,0,"no-multibox","T4-N7DNRXZN56JC6",0,0,0,0,0,null,null,null,null,1]}

**Comment by simov** [comment]
Wow, what is this? Can't help you. Certainly not a request issue. I'm going to close this issue shortly if no one else responds to it.

**Comment by qar** [comment]
@anagas Have you tried to enable cookies ?

**Comment by anagas** [comment]
@qar No, but now with Cookies its works...thanks:) I had not try it because with Angularjs its works without the cookie:/ Thanks! You saved me alot of time..xD

**Comment by qar** [comment]
:beers:
