### ISSUE TITLE
`json` setting doesn't have effect in `on('data')` callback 

### ISSUE THREAD

**Issue by gitaarik** [request/request#1765]
As an example:

    request.get({
        url: url,
        json: true
    }, function(error, response, data) {
        console.log('regular callback:');
        console.log(data);
    }).on('data', function(data) {
        console.log('on(data) callback:');
        console.log(data);
    })

The `data` at the regular callback is an array, unpacked from the JSON response. The `data` at the `on(data)` callback is the JSON response as a string.

**Comment by pyhedgehog** [comment]
As far as I understand on('data') callback called for partial data chunks. JSON can be parsed for complete body only.
So, from my point of view this is correct behaviour.

**Comment by gitaarik** [comment]
`on('data')` is for partial data chunks? Haven't been able to find that in the documentation, could you point it out?

**Comment by simov** [comment]
Yep, you can pipe request to some other stream, and do something with the JSON response on the fly. @gitaarik [here](https://nodejs.org/api/stream.html#stream_event_data)
