### ISSUE TITLE
Socket hang indefinitely when using formData

### ISSUE THREAD

**Issue by simonprev** [request/request#1769]
This is a follow up of the issue #1544 .

I created a "minimum viable repo" to reproduce the issue :smile: https://github.com/simonprev/ad-gear-request-hang

The repo uses a file but it hangs everytime I uses the formData.

The error message: `{ [Error: socket hang up] code: 'ECONNRESET' }`

**Comment by simov** [comment]
@simonprev are they provide some sort of a developer account registration? I'm not seeing it, and I certainly don't have a user name and password.
