### ISSUE TITLE
Getting incomplete response data

### ISSUE THREAD

**Issue by raeesaa** [request/request#1770]
Hi,

I have been using request since past 1 year and my experience with it has been great so far. I recently added request to a new application and I have been getting following exception when trying to parse JSON data received from http call made:

```
SyntaxError: Unexpected end of input
    at Object.parse (native)
    at Request._callback (/home/Codes/xxxxxx/lib/aggregate.js:351:32)
    at Request.self.callback (/home/Codes/xxxxxx/node_modules/request/request.js:372:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/home/Codes/xxxxx/node_modules/request/request.js:1317:14)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/home/Codes/xxxxx/node_modules/request/request.js:1265:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:448:13)
```

I tried logging response body received and found that reponse body is truncated. I am getting incomplete response body in callback of request.

Here are my codes:

``` fs
request({
        url: collectionUrl,
        timeout: 60000
      }, function(error, response, body) {
        if (!error && response.statusCode == 200) {
          try {
            var resData = JSON.parse(body.toString('utf-8'));
          }
          catch(err) {
            console.log(body);
            console.log(err);
            throw err;
          }
      }
});


```

Thanks,
Raeesaa

**Comment by simov** [comment]
Hi, @raeesaa, how can I reproduce the bug? Give me something that I can test with.

**Comment by Mirdrack** [comment]
Hi!
I have a similar problem, Im trying to make an scrapper but after get the resources to be downloaded
I make loop to call a function where i download one file.

This is my function:
```javascript
dowloadResource: function (uri, boardName, surl, filename, callback) {

		// We gonna save the files so we setup the required libraries
		var request = require('request');
		var fs = require('fs');

		// We check for the directories and we create them if they dont exists
		var boardDirectory = './files/' + boardName
		var surlDirectory = './files/' + boardName + '/' + surl;
		if ( !fs.existsSync(boardDirectory) ) {		    
		    fs.mkdirSync(boardDirectory);
		}
		else {
		    if( !fs.existsSync(surlDirectory) ) {
		    	fs.mkdirSync(surlDirectory);
		    }
		}

		if( !fs.existsSync(filename) )
		{
			// We download the file
			console.log('=== Dowloading::' + uri );
			request(uri)
				.pipe(fs.createWriteStream(filename))
				.on('close', function () {
					console.log(filename + ' downloaded.');	
				})
				.on('error', function (err) {
					console.log(err)
				});
		}
}
```
Actually im downloading images, it works when are there less than 20 images(aprox) but when there are more I get some of them incompleted, mabye is a similar problem  or maybe Im doing a lot of requests at the same time, it would be nice if somebody can give me a suggestion to differ my requests.

Thanks in advance

**Comment by raeesaa** [comment]
@simov My codes are confidential and I fear I'll be able to share the web services being called from the application.

However, I managed to come up with a work around which I am not sure is the best possible thing. What I am doing is whenever I get truncated response for any API call, I am making request to same API again. I have configured this retrying thing to happen till some maximum retry limit say "5" and if it still does not work my script throws error. And most of the times, the request sent to same API for second time returns complete response. This thing worked for me because I am making HTTP requests from a standalone script that runs in background, I don't think this would be the appropriate solution if we are using request in server request handlers.

**Comment by raeesaa** [comment]
@simov And my code makes around 40 - 120 requests in a loop if that thing can help.

**Comment by simov** [comment]
@raeesaa that makes sense. The server can close the connection at any time, that's per specification. Once you start flooding it with many requests it will simply cut you off. Brute force doesn't work in network programming.

**Comment by raeesaa** [comment]
@simov Ok. I'll continue keeping retry codes in my application unless I find a better solution.

**Comment by Mirdrack** [comment]
The problem is on the multiple request at the same time
I made a python script and i ran it through node and works fine(no probem with a batch of 200 requests)
The trick is do one request at time
Thanks for your answers

**Comment by raeesaa** [comment]
@Mirdrack I make one request at a time. The request to next API is not made unless first one is completed so I am not sure why I get this issue frequently.

**Comment by simov** [comment]
@raeesaa show us your looping logic. 

@Mirdrack not necessarily one request at a time, but you certainly want to fine tune the amount of requests. You can use libraries such as [async](https://github.com/caolan/async) to limit the parallelism to a reasonable degree. Then you can use the [http.Agent](https://nodejs.org/api/http.html#http_class_http_agent) to reuse the underlying TCP connections instead of creating new ones each time.

**Comment by raeesaa** [comment]
@simov My logic looks something like: 

```
var offset = 0,
  rows = 200;

async.doWhilst(function(callback) {
  records = [];
  var collectionUrl = url + '&offset=' + offset + '&rows=' + rows;
  
  request({
    url: collectionUrl,
    timeout: 60000
  }, function(error, response, body) {
    if (!error && response.statusCode == 200) {

      var resData = JSON.parse(body.toString('utf-8'));
      records = resData['message']['items'];

      //Do something with records

      offset = offset + rows;
      callback(null);


    } else {
      if (!error) {
        //Handle 404, 500, 503 responses
        callback(null)
      } else {
        callback(error)
      }
    }
  });

}, function() {
  return records.length != 0;
}, function(err) {
  //Done
});
```

**Comment by simov** [comment]
Your code seems to be sequential indeed. However you can still try to reuse the same TCP socket:

```js
// declare this outside of your looping logic
var agent = new http.Agent({keepAlive:true, maxSockets:1})
```

Then pass it to request `agent:agent`.

This code will force request to reuse the same TCP socket for all of your requests, and since they are sequential you'll actually benefit from having one persistent socket.

Also try to limit your result set to something smaller. Are you sure you really need 200 records at a time? I don't know how your data looks like, but that's a pretty big number anyway.

**Comment by raeesaa** [comment]
@simov Thank you. I'll give `http.Agent` a try.

And about result set, 200 records are manageable. The API return JSON documents and size of documents is not that big. And I had also tried changing this number to 50 when I started getting truncated response but that did not help either.

**Comment by gauravtiwari5050** [comment]
@simov We are also facing the same issue where response is truncated.
Our response payloads are roughly in the range 30-50kb.

@raeesaa Could you let us know how you resolved this.

**Comment by leonard-sxy** [comment]
I encountered this problem also today.

interval:do_http_post:: Failed sending: Unexpected end of input when trying to JSON.parse the response body.

Seems it happens rarely, tried 1 hour to reproduce, but didn't successfully make it.

**Comment by Kequc** [comment]
I'm downloading a truetype font and it's only returning the first half of the file (18KB of 31KB). Here is something reproducible, it's a very simple example.

    "use strict";
    var request = require('request');
    var url = require('url');

    // app is expressjs instance
    app.use('/ext', (req, res) => {

        // google font url
        let uri = url.parse("https://fonts.gstatic.com/s/alegreyasans/v3/KYNzioYhDai7mTMnx_gDgkXX4kpEMIkMuCYjxR86fn4.ttf");

        // request options
        let options = {
            uri: uri,
            encoding: null,
            gzip: true
        };

        // proxy
        req.pipe(request(options)).pipe(res);
        
    });

I hope this helps.

**Comment by si-harps** [comment]
Thanks @Kequc - your are a life saver. It turns out that because i was receiving a gzip'd encoded response - i also have to set the request 'gzip' option to true. Once updated, all content seemed to be coming through as expected

**Comment by ebbmo** [comment]
Thanks @simov for mentioning it:

> The server can close the connection at any time

I have had a similar issue today where one (out of 6 parallel) request from a 3rd party server was cut off mid-air...
We fixed by comparing the header information with the actual response body and retrying it after 1, 5 and 10 seconds like so:
```
const RETRY_DELAYS = [
  1000, // first after 1 second
  5000, // next after 5 seconds
  10000, // next after 10 seconds
];

<...>

if (response.headers['content-length'] !== body.length &&
    retry < RETRY_DELAYS.length) {
    console.log('[Execute] Will retry due to connection being cut in', RETRY_DELAYS[retry], 'from url', url);`

    // set timeout to try again
    setTimeout(
      _call, RETRY_DELAYS[retry], url, callback, retry + 1
    );
}
```

I was expecting request to be the error source, but it wasn't. :)

**Comment by NorthernMan54** [comment]
I was having a similar issue when the response.body was a large json object, i.e. > 28K, and was receiving this error when parsing the json response

SyntaxError: Unexpected end of input

After trying with curl, and getting a complete response, found that the issue was caused by the socket closing early.   To fix the issue I added to the headers "connection": "keep-alive"

ie

`    request({
        method: 'GET',
        url: 'http://' + host + ':' + port + '/accessories',
        timeout: 10000,
        json: true,
        headers: {
            "Content-Type": "Application/json",
            "connection": "keep-alive",
        },
    }, function(err, response, body) {`

**Comment by maddo7** [comment]
Is there a real solution to this? I'm also having this issue with requestjs.
Adding connection 'keep-alive' did not have any effect.
When running the exact same requests on the exact same environment with PHP and curl there are no issues at all.

**Comment by baoshan** [comment]
@maddo7 have you tried the `gzip: true` option also?

**Comment by eugene2005** [comment]
Same here. When I use pipe with the request I am getting incomplete result. 'keep-alive' and gzip: true are not helping.

**Comment by xileftenurb** [comment]
The issue may be not linked to request.
I have the same problem since this morning but I found out the body is truncated event without using request.
My request length is capped at 64k. I don't know why. It started after I updated my Debian server from Jessie to Stretch.

If anybody have an idea how to solve the problem, it would really help. I have some site down because of this bug.

**Comment by Mike-Neto** [comment]
I managed to fix this by passing both sugested gzip and keep alive settings and also tranfered encoding.

my request looks like this:
`responseValue = await get(URL + URLParameters, { json: true, gzip: true, headers: {"connection": "keep-alive", "transfer-encoding": "chunked"} });`

**Comment by bedsDev** [comment]
I have the similar problem when I request json format, but the response is incomplete and I cannot parse the response. Is a slouation?

**Comment by bedsDev** [comment]
@simov suggestion is working for me
`
// declare this outside of your looping logic`
`var agent = new http.Agent({keepAlive:true, maxSockets:1})
`

**Comment by bedsDev** [comment]
it still not working well when a large JSON was responded.
`sageGet(urll: string): Promise<string> {        
        let getOptions: request.Options = {
            url: urll,
            jar: this.cookieJar,
            agent: this.agent,
            
            headers: {
                
                gzip: true,
                // Accept: "application/json;vnd.sage=sdata",
                // "content-type": "application/json;vnd.sage=sdata",
                'User-Agent': "request"
            },
            auth: {
                user: this.user,
                pass: this.pass
            }

        }

        return new Promise<string>((resolve, reject) => {
            request.get(getOptions)
                .on('response', (response) => {
                    if (response.statusCode === 200) {
                        // console.log(`get response!! ${urll}`)
                        
                        console.log("\n\n-----------------------response")
                        console.log(response)
                        console.log("\n\n-----------------------response.toJSON()")
                        console.log(response.toJSON())

                        console.log("\n\n-----------------------Headers")
                        console.log(`response.headers["content-length"]`);
                        console.log(response.headers["content-length"]);




                        response.on("data", (data) => {
                            let dataBuffer:Buffer = <Buffer>data;

                            let dataBin = dataBuffer.toString("binary");
                            console.log()
                            console.log("data.length", dataBin.length)
                            
                            console.log("\n-----------------data")
                            // console.log(dataBin);

                            console.log("\n-----------------data.toString()")
                            resolve(dataBin);
                        })

                        // resolve(response.body);
                    } else {
                        reject('${urll} the requestion is not successful');
                    }

                })

        });
    }`

the conent-length != data.length

Does anyone have a soluation?

**Comment by snow4** [comment]
I was also facing the same problem but when I mapped the response then it was showing all data. The problem can be there will be whole data but it might not be showing whole.

**Comment by vijaychowthri** [comment]
class newPost {

    postData(inpData){
        console.log('---
        var request = require('request');
        
        let postData=JSON.stringify(inpData);
        var url = 'https://something.com/xyz';

        let options = {
            url: url,
            method: 'POST',
            headers: {
                'Accept': 'application/json',
                'Accept-Charset': 'UTF-8',
                'Content-Type': 'application/json'
            },
        
            strictSSL: false,
            body:postData
        };

        function post(options) {
            var defer = protractor.promise.defer();
            request(options, function(error, response, body) {
               
                if (error || response.statusCode > 200) {
                    defer.reject({
                        error : error,
                        response : response
                        
                    });
                } else {
                    defer.fulfill(response.statusCode);
                    expect(response.statusCode).toEqual(200);
                    console.log('----------------------------------------------');
                    console.log('error:', error); // Print the error if one occurred
                    console.log('statusCode:', response && response.statusCode);
              
                }

            })
            return defer.promise;
        }
          
        function setupCommon() {
            return post(options);
        }
         
        var flow = protractor.promise.controlFlow();
        flow.execute(setupCommon);
              
        }

}

module.exports = new newPost();

**Comment by wkgcass** [comment]
I also run into with this issue. I noticed it's first raised in Sept 2015, so, has there been any commit solved this issue?
