### ISSUE TITLE
301 Redirects don't appear in request.redirects array

### ISSUE THREAD

**Issue by djtregear** [request/request#1773]
Hi

Is there any reason why 301 redirects do not appear within  res.request.redirects array.  I can access any 302 redirects, that happened during request resolution, but it's ignoring the 301's and I need to access them.

Any ideas?

Thanks

David

**Comment by calibr** [comment]
`res.request.redirects` is always undefined for me, but I can get both 301 and 302 redirects from `res.request._redirect.redirects`, for example:

```js
request.get("http://localhost:8003", function(err, res, body) {
  console.log(res.request._redirect.redirects);
});
```

**Comment by djtregear** [comment]
Thanks calibr, that's exactly what I needed.
