### ISSUE TITLE
Doc - error event vs. error callback

### ISSUE THREAD

**Issue by tomruggs** [request/request#1779]
The doc does not mention the difference between the error event and callback on error.  It would be nice if there was a blurb about how the two differ and when the callback would be called but no event would be emitted.  For instance if the URL or options used contain an invalid entry.

For a bad URL you get both en error event and a callback with an error value:

``` js
request('http://0.0.0.0/asdf', function(error, response) {
  console.log('error callback');
}).on('error', function(error) {
  console.log('error event');
})

Result:
error callback
error event
```

But for a malformed only the callback fires:

``` js
request('i like pizza', function(error, response) {
  console.log('error callback');
}).on('error', function(error) {
  console.log('error event');
});

Result:
error callback
```

**Comment by simov** [comment]
Hi, @tomruggs, probably this thread might help you: https://github.com/request/request/pull/1558

**Comment by Fh-sadelson** [comment]
I agree this is confusing. I think the documentation needs to be updated to clearly show that the callback is required even when handling the event.

From the docs:

> To easily handle errors when streaming requests, listen to the error event before piping:
> ```javascript
> request
>   .get('http://mysite.com/doodle.png')
>   .on('error', function(err) {
>     console.log(err)
>   })
>   .pipe(fs.createWriteStream('doodle.png'))
> ```

This does not tell us that we need to always have a callback to handle certain errors.

Maybe write it this way instead:

> To easily handle errors when streaming requests, listen to the error event before piping. 
> **Warning**: You must also include a callback to catch certain errors which occur during initialization. These will not emit an event, so the callback is the only way to handle them.
> ```javascript
> request
>   .get('http://mysite.com/doodle.png',function(err){
>     if(err){ console.log(err); }
>   })
>   .on('error', function(err) {
>     console.log(err)
>   })
>   .pipe(fs.createWriteStream('doodle.png'))
> ```

**Comment by mnebuerquo** [comment]
I agree this is confusing. I think the documentation needs to be updated to clearly show that the callback is required even when handling the event.

From the docs:

> To easily handle errors when streaming requests, listen to the error event before piping:
> ```javascript
> request
>   .get('http://mysite.com/doodle.png')
>   .on('error', function(err) {
>     console.log(err)
>   })
>   .pipe(fs.createWriteStream('doodle.png'))
> ```

This does not tell us that we need to always have a callback to handle certain errors.

Maybe write it this way instead:

> To easily handle errors when streaming requests, listen to the error event before piping. 
> **Warning**: You must also include a callback to catch certain errors which occur during initialization. These will not emit an event, so the callback is the only way to handle them.
> ```javascript
> request
>   .get('http://mysite.com/doodle.png',function(err){
>     if(err){ console.log(err); }
>   })
>   .on('error', function(err) {
>     console.log(err)
>   })
>   .pipe(fs.createWriteStream('doodle.png'))
> ```

(To those of you who get notifications on this thread, I accidentally posted this while logged in with the wrong account, so it is deleted and reposted. Sorry about the double notification.)
