### ISSUE TITLE
Content-Type header shoudn't be set on GET

### ISSUE THREAD

**Issue by thecadams** [request/request#1786]
https://github.com/request/request/commit/5225289165a0fb060c30e5a71f69704c3450103f always sets `Conent-Type` for requests with `json:true` but this shouldn't happen for GET requests.

It's breaking our servers that see the Content-Type header and blindly go looking for a body.

We can work around it by downgrading but wanted to call your attention to it.

**Comment by simov** [comment]
Fixed in #1785 I'll release it tomorrow.

**Comment by thecadams** [comment]
Super fast turnaround - cheers!
