### ISSUE TITLE
Request#destroy does not destroy the underlying socket

### ISSUE THREAD

**Issue by konradreiche** [request/request#1793]
After initiating a stream like this:

``` javascript
var streamRequest = request(this.url)
      .on('data', (chunk) => this.onData(chunk));
```

Data chunks are received as observed in the callback `onData`, however, calling

``` javascript
streamRequest.end()
streamRequest.destroy()
```

does not close the connection properly. I am still getting data chunks in. It is only through this code here the connection is actually closed:

``` javascript
var streamRequest = request(this.url)
      .on('data', (chunk) => this.onData(chunk))
      .on('socket', (socket) => this.socket = socket);

this.socket.end();
this.socket.destroy();
```

Is this a bug or wrong use of the API?

**Comment by simov** [comment]
An alternative solution would be to pass your own [http.Agent](https://nodejs.org/api/http.html#http_class_http_agent) to the request and `.destory()` that instead.
