### ISSUE TITLE
Is request used for testing REST APIs?

### ISSUE THREAD

**Issue by nareshbhatia** [request/request#1794]
It seems that [SuperTest](https://github.com/visionmedia/supertest) is the most popular library for testing REST APIs. Given the strengths of *request*, I was wondering if anyone uses it for testing. Is there an overlap with the functionality of SuperTest/SuperAgent? Are the two libraries complementory?

P.S. Please let me know if there is a request forum where I should be posting this question.

**Comment by mmalecki** [comment]
We use `request` for testing our (not necessarily REST) HTTP APIs at npm. I'd imagine there's a lot of people doing it.

I'm not aware of any other forum, other contributors might be.

I'll close this now as it's not an issue, but feel free to continue the discussion here.

**Comment by simov** [comment]
@nareshbhatia you can configure [Purest](https://github.com/simov/purest) and use it to easily make requests to your REST API (it's built on top of request). Then you can use any assertion library, I personally use [should](https://github.com/shouldjs/should.js):

```js
describe('facebook', function () {
  it('get user', function (done) {
    facebook.query()
      .get('me')
      .auth(user.facebook.token)
      .request(function (err, res, body) {
        res.statusCode.should.equal(200)
        body.id.should.be.type('string')
        done()
      })
  })
})
```

**Comment by nareshbhatia** [comment]
@mmalecki, @simov, thanks for your insights. I will experiment using both suggestions.

Others, please feel free to chime in.
