### ISSUE TITLE
"Socket Hung Up" ECONNRESET error with many https requests

### ISSUE THREAD

**Issue by jeffkile** [request/request#1795]
Steps to reproduce:
Run this simple https server: https://gist.github.com/jeffkile/b93349282c77f345f502 then run this client https://gist.github.com/jeffkile/3bf35e6c8bec4b160ca5 TWICE to make 1000 get requests to the server. The second time you run the client a portion of the requests will fail with the Socket Hung Up error message.

This is reproducible on both node 0.12.7 and node 4.1.

If you specify your own `agent` with `{maxSockets: 10, keepAlive: false}` then it works.

Is there a bug in request or https or node that is causing this problem? Or does the request documentation need to be updated to tell users they need to specify one of these options? Or is there something subtle in the way connections work that I don’t understand?

**Comment by calibr** [comment]
I guess that's some sort of OS limitations. I expirienced same errors as you using your example and also server sometimes got segmentations faults. But after I set `net.core.somaxconn = 2048` in sysctl.conf it seems that errors disappeared. So I think you need make some tunings in your system to make it working, and also look at system log it may contain some log lines about issue.
I tested it on Ubuntu 12.04, node 0.12.7 and 4.1

**Comment by schmatz** [comment]
I am having this problem on 4.1 but not 0.12.7. Just switching the version on my application causes this behavior to occur. I will debug and post updates here.
