### ISSUE TITLE
How to get response raw body?

### ISSUE THREAD

**Issue by leefsmp** [request/request#1796]
Hi 

How do I get the response as raw body with your lib? 

What I'm looking for is the same result than when using an xhr with xhr.responseType = 'arraybuffer'; ?

I've been browsing the doc but can't find a way.

Thanks in advance.

**Comment by chaselal** [comment]
You can get the response body from the third parameter of the request method's callback parameter. E.g. require('http://www.google.com', function(error, response, body) { console.log(body); });

**Comment by leefsmp** [comment]
Thanks, what I was looking for is to set encoding: null, so the returned body is the raw data.

**Comment by neothemachine** [comment]
I had the same problem. It's not very obvious and hard to find in the docs.

**Comment by dilidili** [comment]
hi cause the request({...}) will return a readable stream, so you can get the raw body as such way
`
	request({
		url: `http://suggestion.baidu.com/su?wd=${body.q}`,
		method: 'GET',
	}).on('data', (chunk) => {
		console.log(iconv.convert(chunk).toString())
	})
`

**Comment by dilidili** [comment]
hi cause the request({...}) will return a readable stream, so you can get the raw body as this way:

```
	request({
		url: "http://suggestion.baidu.com/su",
		method: 'GET',
	}).on('data', (chunk) => {
		console.log(iconv.convert(chunk).toString())
	})
```

the chunk the stream emit is just plain a Buffer in Node.js API
