### ISSUE TITLE
response pull stream is not working

### ISSUE THREAD

**Issue by bayareagreg** [request/request#1804]
Hi 
according to the README, this type of construct
```js
 .on('response', function(response) {
    // unmodified http.IncomingMessage object
    response.on(...)
    })
  })
```
will give me access to unmodified httpIncomingMessage object. Which implements a readable stream. 
However, when I try to do something like 
```js
    resp.on('response', function(response)
    {
        response.on('readable', function()
        {
            var data = response.read(1000);
```      
this gets called but data is always null

Noticed that doing
```js
    resp.on('response', function(response)
    {
        response.on('data', function(data)
        {
```
does indeed give me the data, but this is a "push" stream which is not acceptable to me. I need to be able to use a "pull" stream, where my code decides when to get the data from the stream and how much of it, etc.
Please help
Thanks
Greg

**Comment by simov** [comment]
This version of request uses the old Streams implementation.
