### ISSUE TITLE
'Tunnel connection failed: 403 Forbidden'  issue in my project at pythonaywhere.com

### ISSUE THREAD

**Issue by RohithKP** [request/request#1810]
(flask)12:13 ~/mysite $ python tweet.py
Traceback (most recent call last):
  File "tweet.py", line 63, in <module>
    tweet()
  File "tweet.py", line 38, in tweet
    r = requests.get(url, headers=headers)
  File "/home/RohithKP/.virtualenvs/flask/local/lib/python2.7/site-packages/requests/api.py", line 69, in get
    return request('get', url, params=params, **kwargs)
  File "/home/RohithKP/.virtualenvs/flask/local/lib/python2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/home/RohithKP/.virtualenvs/flask/local/lib/python2.7/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/RohithKP/.virtualenvs/flask/local/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/home/RohithKP/.virtualenvs/flask/local/lib/python2.7/site-packages/requests/adapters.py", line 424, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='affiliate-api.flipkart.net', port=443): Max retries exceeded with url: /affiliate/offe
rs/v1/dotd/json (Caused by ProxyError('Cannot connect to proxy.', error('Tunnel connection failed: 403 Forbidden',)))

I have same problem while executing this line. " r = requests.get(url, headers=headers) " .As you can see, I am using https connection to call the flipkart api, and that causes the problem.But i dont know how to resolve this.

**Comment by RohithKP** [comment]
I think the issue may not be with request module. Pythonanywhere.com may be restricting my access to the flipkart api,because its not in their white listed sites. A similar issue can be found on their forum here >> https://www.pythonanywhere.com/forums/topic/1905/ .

**Comment by ghost** [comment]
> I think the issue may not be with request module. Pythonanywhere.com may be restricting my access to the flipkart api,because its not in their white listed sites. A similar issue can be found on their forum here >> https://www.pythonanywhere.com/forums/topic/1905/ .

Dont you know how can i circumvent the ban?

**Comment by RohithKP** [comment]
> > I think the issue may not be with request module. Pythonanywhere.com may be restricting my access to the flipkart api,because its not in their white listed sites. A similar issue can be found on their forum here >> https://www.pythonanywhere.com/forums/topic/1905/ .
> 
> Dont you know how can i circumvent the ban?

Try requesting them to add it to whitelisted sites.

**Comment by ghost** [comment]
> Try requesting them to add it to whitelisted sites.

I'm writing a file downloader, and... I don't know what host i'll use. I need Python Requests to support every host. So what can i do?

**Comment by gulomovotabek** [comment]
do you know?
what api is https://pypi.org/project/covid/?
