### ISSUE TITLE
ntlm-authentication module

### ISSUE THREAD

**Issue by mozammilwy** [request/request#1815]
can you please tell me any module which is doing ntlm authentication and also using request module.

**Comment by simov** [comment]
Not sure if that combination exists, although it's possible. There are other modules in NPM however that deal with NTLM, like [ntlm](https://github.com/tcr/node-ntlm).

**Comment by mepdr** [comment]
I found https://github.com/SamDecrock/node-http-ntlm
However I'd use request, is there any update?

**Comment by Huachao** [comment]
@mozammilwy I found you closed it just now, I have a question that do you finally find a.way to use ntlm together with request
