### ISSUE TITLE
Inconsistency in response.uri when using browserify

### ISSUE THREAD

**Issue by pietercolpaert** [request/request#1816]
## Problem

When redirects happen, response.request.uri correctly retrieves the URI of the last HTTP request, only when used through node. When it's used through browserify in the browser, response.request.uri gets the first requested URI.
### 1. Command line works

``` bash
>npm install request
> node
var request = require('request'); request.get('http://irail.be', function (err, response) {console.log("Now should contain https in the uri: ",response.request.uri.href);});
```
### 2. Browser doesn't work:

Check out this require bin (use the dev tools console to see the result, where this time, no https redirect was detected by require as it automatically was solved by the browser):

http://requirebin.com/?gist=4c1ffeebbbfae2e8a408
## Possible fix

Check if the request was done by a browser and set the uri.href to what the browser returns instead of the requested URL?

**Comment by pietercolpaert** [comment]
This is probably because the browser itself performs the redirects automatically, instead of request. Any idea how we could fix this?

**Comment by simov** [comment]
Short, self contained code example that's enough to reproduce the bug would be great. We also have a [browser tests](https://github.com/request/request/tree/master/tests/browser), that's another good place to add a simple failing test. Then figuring out a patch would be much easier.

**Comment by pietercolpaert** [comment]
@simov thanks for your reply! Very simple way to test this:

### 1. Command line works
```bash
>npm install request
> node
var request = require('request'); request.get('http://irail.be', function (err, response) {console.log("Now should contain https in the uri: ",response.request.uri.href);});
```

### 2. Browser doesn't work:

Check out this require bin (use the dev tools console to see the result, where this time, no https redirect was detected by require as it automatically was solved by the browser):

http://requirebin.com/?gist=4c1ffeebbbfae2e8a408
