### ISSUE TITLE
Proposal - `Request#readResponseBody`

### ISSUE THREAD

**Issue by pvoisin** [request/request#1817]
There's a cool piece of code [here](https://github.com/request/request/blob/master/request.js#L1016:L1065) that one could benefit from if it were extracted and exposed as a function of `Request#prototype`... :)

If I find some time to do it I'll definitely enjoy contributing. In the meantime I'm just dropping those lines for any feedback.

**Comment by simov** [comment]
I agree :+1:

**Comment by pvoisin** [comment]
What about [that](https://github.com/request/request/pull/1818)?

**Comment by simov** [comment]
Closed via #1818
