### ISSUE TITLE
Not getting any response using POST

### ISSUE THREAD

**Issue by alvarotrigo** [request/request#1822]
I'm using `post` and sometimes, depending on the server side, I get no response at all.
Not even an error. 

I can see how the string `===========================> Sending update actual time!!!!!` gets printed. The server side is receiving it and processing it, but then I get no response and `RESPONSE` doesn't even get printed. 

```javascript
router.post('/saveActualTime/', function(req, res,next) {
    var params = req.body;
    params['uuid'] = req.session.user.uuid;

    console.log("===========================> Sending update actual time!!!!!");
    request.post({
        uri:  res.locals.baseUrl + 'HaulierPortal/addgateevent',
        qs: params
    }, function (error, response, body) {
        console.log("RESPONSE");  //it doesn't reach this point.
        console.log(body);
        if (error || response.statusCode != 200) {
            console.log("error!");
            res.send({});
        }else{
            var data  = JSON.parse(body);
            res.json(data);
        }
    });
});
```

**Comment by simov** [comment]
That sounds strange idd, but how can I reproduce it?

**Comment by alvarotrigo** [comment]
It seems the problem was in the server side. The restful server was not responding at all (infinite loop or very slow processing) and there was no maximum execution time, so it never came back.

Web servers usually provide maximum execution times and I was not used of a request which never responds. 

Thanks anyway.
