### ISSUE TITLE
request usage scenario

### ISSUE THREAD

**Issue by mgenereu** [request/request#1823]
Initially I tried to use request (since it said it supported URL parsed objects) like this:
```javascript
var options = {
  url: {
    protocol: 'https:',
    hostname: 'api',
    port: '443',
    pathname: '/services/info',
    query: {
      id: 5000
    }
  },
  json: true
};
request(options, function (error, response, body) {
  // omited
};
```

Tracing the code, I found that doesn't work.  For the developers on my team that are also expecting this to work, I added this in our wrapper:
```javascript
if (request_options.url && request_options.url.query) {
  request_options.qs = request_options.url.query
  delete(request_options.url.query)
}
```

The options variable is actually generated from several functions but the above assignment is equivalent.  Would you have expected the options variable to work as is and would you like a patch?

**Comment by simov** [comment]
Request expects a valid [url.parse](https://nodejs.org/api/url.html#url_url_parse_urlstr_parsequerystring_slashesdenotehost)'d object:

```js
> url.parse('https://www.npmjs.com/search?q=http')
Url {
  protocol: 'https:',
  slashes: true,
  auth: null,
  host: 'www.npmjs.com',
  port: null,
  hostname: 'www.npmjs.com',
  hash: null,
  search: '?q=http',
  query: 'q=http',
  pathname: '/search',
  path: '/search?q=http',
  href: 'https://www.npmjs.com/search?q=http' }
```

Your example shows something else.

**Comment by mgenereu** [comment]
That's the output of a parse and shows the ugly string version of the query.  I use the version referenced in the documentation as accepted by the url.format command.

**Comment by simov** [comment]
Ok, but request expects the parsed one. If you use `url.format` then pass your URL as string, instead of object.

**Comment by mgenereu** [comment]
```
> url.parse('https://www.npmjs.com/search?q=http', true)
{ protocol: 'https:',
  slashes: true,
  auth: null,
  host: 'www.npmjs.com',
  port: null,
  hostname: 'www.npmjs.com',
  hash: null,
  search: '?q=http',
  query: { q: 'http' },
  pathname: '/search',
  path: '/search?q=http',
  href: 'https://www.npmjs.com/search?q=http' }
```

**Comment by simov** [comment]
Interesting, I've never used that option. In this case that's a bug on our end.

**Comment by mgenereu** [comment]
Meh.  Just a unpopular variation loved by us OO programmers.  :stuck_out_tongue_winking_eye:

**Comment by simov** [comment]
That's fine, so do you have some fix in mind? We're going to need a test case for this behavior too.

**Comment by mgenereu** [comment]
I would be happy to write the patch.  Used an issue to confirm it wouldn't be wasted time. Thanks.

**Comment by akarienta** [comment]
@mgenereu Thank you man, you saved my day.

**Comment by mgenereu** [comment]
No problem.  Thanks for the poke to remind me to write the patch.
