### ISSUE TITLE
EPROTO error on node 4

### ISSUE THREAD

**Issue by Janpot** [request/request#1826]
trying the following:

```js
var request = require('request');
request.get('http://blueshieldca.com', function (err, res, body) {
  console.log(err || body)
});
```

On node 0.12.7 (expected):

```
<HTML><HEAD>
<TITLE>Access Denied</TITLE>
</HEAD><BODY>
<H1>Access Denied</H1>
 
You don't have permission to access "http&#58;&#47;&#47;www&#46;blueshieldca&#46;com&#47;" on this server.<P>
Reference&#32;&#35;18&#46;46bdfad&#46;1444200729&#46;2a18e54d
</BODY>
</HTML>
```

On node 4.1.1:

```
{ [Error: write EPROTO]
  code: 'EPROTO',
  errno: 'EPROTO',
  syscall: 'write',
  address: undefined }
```

Similar problem on `'http://q-systems.com'`

**Comment by simov** [comment]
Probably related to this issue https://github.com/nodejs/node/issues/2244
If you find solution post it here, it will be very helpful.

BTW the server is redirecting you to `https://blueshieldca.com/` notice the **s** after `http` and the ending **/** you can use this URL instead.

**Comment by Janpot** [comment]
@simov :) sure, I know, This is just some issue I saw in my logs with some user input. Thought I'd escalate.

**Comment by calibr** [comment]
Both those sites use RC4-SHA, although it disabled by default you can override list of supported ciphers by `--tls-cipher-list` node option.

**Comment by Janpot** [comment]
@calibr That worked, thanks!
