### ISSUE TITLE
performence issue

### ISSUE THREAD

**Issue by backsapce** [request/request#1829]
thx to authors first.

in my project i use request to pull img from remote server.
but i fond it has hard performence problem.i request 40 img cost almost 30 second.so i try to implement a tiny request base on origin nodejs http agent.it just cost 600-700ms load img.i have not learn this package code already.so i just feedback this performence issue to author.i will try to figure out why request so low in my use.if needed,i will patch my benchmark data.

**Comment by simov** [comment]
Thanks for the feedback, any code examples to reproduce the issue would be helpful.
