### ISSUE TITLE
Get HTML after 'onload' ?

### ISSUE THREAD

**Issue by rahul-desai3** [request/request#1843]
The problem is that I am not able to get the email address (help@mesotheliomagroup.com) at the bottom on this website: http://www.mesotheliomagroup.com/

Here is my code so far (pretty basic):

```
var request = require('request');  // to grab the HTML from URL

request('http://www.mesotheliomagroup.com/', function (error, response, htmlString) {
	if (!error && response.statusCode == 200) {
		console.log(htmlString);
	}
});
```

How do I get this working?

**Comment by mikeal** [comment]
request is just an http client, so your code example is correct in how to get the html response from the server. if you want to parse the html and potentially javascript in the page that manipulates it you'll need to look at `zombiejs` http://zombie.js.org/ which uses request but is effectively a headless browser.
