### ISSUE TITLE
Documentation on ETIMEDOUT & connect not clear

### ISSUE THREAD

**Issue by nbcraft** [request/request#1848]
Hi,
First of all I'm not sure i should have opened an issue for this, but I haven't found any other way to ask this question.

Lately I've been running into these errors :

```
{ code: 'ETIMEDOUT', connect: false }
{ code: 'ETIMEDOUT', connect: true }
```

And I've been wondering whether the 'connect: true' indicated that this was a connection timeout (as the documentation seems to imply) or that a connection did occurred before the timeout (as my tests seem to indicate).

Here's what the documentation says :

> You can detect timeout errors by checking err.code for an 'ETIMEDOUT' value. Further, you can detect whether the timeout was a connection timeout by checking if the err.connect property is set to true.
> 
> ``` js
> // Set to `true` if the timeout was a connection timeout, `false` or `undefined` otherwise.
> console.log(err.connect === true);
> ```

And here is the code ([request.js(l.811)](https://github.com/request/request/blob/master/request.js#L811)) :

``` js
var connectTimeout = self.req.socket && self.req.socket.readable === false
self.abort()
var e = new Error('ETIMEDOUT')
e.code = 'ETIMEDOUT'
e.connect = connectTimeout
self.emit('error', e)
```

So it does seem that 'connect: true' means connection timeout.
But are you sure that a not-readable socket cannot occur even when a connection is established ?
And when I get 'connect: false', I don't know if I had a readable socket or if there was no socket at all, which can be really misleading.

What do you think ?
Thanks.

**Comment by kevinburke** [comment]
> are you sure that a not-readable socket cannot occur even when a connection is established ?

I wrote this code. No, to be honest, I'm not sure whether you can establish a connection and have a non-readable socket. It was the easiest property I could find to distinguish a failure to connect from a failure to get response headers in the specified amount of time.

Can you reliably reproduce the issue? My next step would be to dump the entire `self.req` object and see what's there.

**Comment by pkoretic** [comment]
This actually caught me now so just to share. If you point request to any non existing ip address, timeout from the request module is used and { code: 'ETIMEDOUT', connect: true } is fired after timeout.

If you point it to ip blocked that is under firewall, underlying socket timeout is used, and { code: 'ETIMEDOUT', connect: false } is fired after timeout.

I'm not sure what to expect but it made some confusion to me since as a user it's hard to see the difference since connection in both cases is not valid.

**Comment by youngrrrr** [comment]
@pkoretic - How did you discover this distinction based on the value returned by `connect`? I'm having ETIMEDOUT issues of my own and would really appreciate your feedback.

**Comment by RobGraham** [comment]
Bump. 
Can we get some updates on this old issue? How do i determine if a ETIMEDOUT was due to DNS resolution latency success/failure or if we established a connection with a dependency but never heard back within the timeout value defined?

**Comment by danmdinu** [comment]
Hi,

any news on this one?
