### ISSUE TITLE
removeRefererHeader docs

### ISSUE THREAD

**Issue by calibr** [request/request#1858]
in documentation:

>removeRefererHeader - removes the referer header when a redirect happens (default: false).

but actually it doesn't remove Referer, it just reuses its value from initial request(like browsers behave). I guess that need to do some corrections in docs about this option.

**Comment by simov** [comment]
Can you provide a short example or a failing test? Here is the [current test](https://github.com/request/request/blob/v2.65.0/tests/test-redirect.js#L351-L366) regarding that behavior.

**Comment by calibr** [comment]
ok, I'll do it soon

**Comment by simov** [comment]
Also note that today I submitted another PR attemting to fix the referer header behavior https://github.com/request/request/pull/1857

**Comment by calibr** [comment]
if add referer header in test you selected it fails:

```js
tape('should not have a referer when removeRefererHeader is true', function(t) {
  request.post({
    uri: s.url + '/temp',
    jar: jar,
    followAllRedirects: true,
    removeRefererHeader: true,
    headers: { cookie: 'foo=bar', referer: 'http://example.com' }
  }, function(err, res, body) {
    t.equal(err, null)
    t.equal(res.statusCode, 200)
    t.end()
  })
  .on('redirect', function() {
    t.equal(this.headers.referer, undefined)
  })
})
```

```
# should not have a referer when removeRefererHeader is true
not ok 77 should be equal
    operator: equal
    expected: |-
      undefined
    actual: |-
      'http://example.com'
```

so it hasn't removed the referer header as documentation says

**Comment by simov** [comment]
Right, now I see. As I understand it, the intention was probably to actually remove it. So instead of having:

```js
if (!self.removeRefererHeader) {
  request.setHeader('referer', uriPrev.href)
}
```

It should be:

```js
if (self.removeRefererHeader) {
  request.removeHeader('referer')
} else {
  request.setHeader('referer', uriPrev.href)
}
```

Of course the test should be fixed too. What do you think?

**Comment by calibr** [comment]
I think that current version of `removeRefererHeader=true` provides the way to process Referer as browsers do it, just preserve Referer from initial request, and in my opinion it's a reasonable behaviour. so I don't think that this behaviour should be changed, because some library users may occur broken if they use this option to behave in redirects like a browser. Probably it should be only a correction in the docs to describe this option more clearly.

**Comment by simov** [comment]
Yep, I think the current implementation is good. We just need additional test for the case when you manually set the referer header in the initial request. I think I'm going to add one tomorrow.

As for the docs, I'm open for suggestions:

> removeRefererHeader - removes the referer header when a redirect happens (default: false). **Note:** referer header set in the initial request is preserved during redirect.

**Comment by calibr** [comment]
:+1:

little suggestion:
>removeRefererHeader - removes the referer header when a redirect happens (default: false). **Note:** if true, referer header set in the initial request is preserved during redirect chain.

(added "if true" and "chain")

**Comment by simov** [comment]
Fixed in https://github.com/request/request/pull/1860
