### ISSUE TITLE
Limit the amount of data request can receive

### ISSUE THREAD

**Issue by sradu** [request/request#1859]
We're ran into an issue where someone passed a 250MB file through request causing node to memleak and die.

It would be great to have a limit that say something like: after you read more than 2MB die somehow.

**Comment by simov** [comment]
Use the event handlers instead of the callback and implement that logic yourself:

```js
// pseudo code
var req = request('http://get-something-large')
var length = 0
req.on('data', function (chunk) {
  length += chunk.length
  if (lenght > 250MB) req.abort()
})
```

The callback handler tries to buffer the entire response body in memory, so it's important to remove your callback handler function.

**Comment by sradu** [comment]
It would be great if there would be an easier way. What I'm trying to do is find the final destination for tracking links (eg bit.ly, affiliate links, etc). This final URL might be hidden behind 5-6 redirects and doesn't work with HEAD.

I'm NOT trying to download files. In fact worst case scenario I want to parse a bit of HTML.

But this means someone can send me a link which takes me to a 250MB file and DoS my whole server. I

**Comment by simov** [comment]
Check out this issue then https://github.com/request/request/issues/1851
