### ISSUE TITLE
No body unless callback is passed as argument

### ISSUE THREAD

**Issue by agustik** [request/request#1863]
I'm using request in Swift/Ceph client

I need to be able to pipe response into file if 'binary/octet-stream' and then call a callback 

I'm using the events, and if I don't send function into request as second param no body is returned
```
var req = request(params);
req.on('complete', function (response, body){
   // no body
});
```

```
// passing function as second parameter
var req = request(params, function (){});
req.on('complete', function (response, body){
   // body available
});
```

package.json tells me   "version": "2.65.0",

**Comment by simov** [comment]
Request buffers the response body in memory only when a callback function is present. Otherwise the data just flows through it.

**Comment by agustik** [comment]
Thanks!
