### ISSUE TITLE
url.parse exception within redirect.js

### ISSUE THREAD

**Issue by cubesapp** [request/request#1864]
I am getting the following exception when calling request(URL,function(err,res,body){});

```
URIError: URI malformed at decodeURIComponent (native) at Url.parse (url.js:185:19) at Object.urlParse [as parse] (url.js:101:5) at Redirect.onResponse (/myproject/node_modules/request/lib/redirect.js:104:21) at Request.onRequestResponse (/myproject/node_modules/request/request.js:944:22) at ClientRequest.emit (events.js:95:17) at HTTPParser.parserOnIncomingClient [as onIncoming] (http.js:1692:21) at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:121:23) at Socket.socketOnData [as ondata] (http.js:1587:20) at TCP.onread (net.js:527:27)
```

The URL has multiple redirects.

Unfortunately, I don't know the exact URL, since we are processing 1000s of URLs at a time, and couldn't narrow it down.

Made the follow change to the redirect.js module for line 104:

``` js
try {
    request.uri = url.parse(redirectTo)
} catch(err) {
    return false;
}
```

Thoughts?

**Comment by simov** [comment]
Obviously the parsing fails due to malformed URI, probably it's a good idea to have a try/catch block there. It's probably a redirect to absolute URL that's malformed, because we're resolving the relative ones on line 100.

**Comment by cubesapp** [comment]
Created pull request #1873
