### ISSUE TITLE
Har support - mimeType and charset

### ISSUE THREAD

**Issue by sod** [request/request#1872]
Chrome 46, Debugger tools Har export.

I tried to repeat a request via har data.

My har file has: `req.postData.mimeType === 'application/x-www-form-urlencoded; charset=UTF-8'` but the switch `switch (data.postData.mimeType) {` in https://github.com/request/request/blob/master/lib/har.js#L63 does not expect to have the `; charset=UTF-8` in here.

The request itself works. But if I modify the postData, it is not recognised as no switch/case matches.

**Comment by simov** [comment]
@sod check out this PR https://github.com/request/request/pull/1876
