### ISSUE TITLE
FormData Stream => Random ECONNRESET

### ISSUE THREAD

**Issue by sdnetwork** [request/request#1878]
hi,

i use request to upload file and i have remarked that sometimes i get an ECONNRESET on client response.

this is a little exemple to reproduce the problem easly : 
CLIENT

``` js
    var http = require('http');
    var request = require('request');
    var fs = require('fs');

    function sendfile() {
    var formData = {
    id: 'my_value',
    data: fs.createReadStream('./package.json')
    }
    request.post({url:'http://127.0.0.1:9090', formData: formData}, function optionalCallback(err, httpResponse, body) {
        if (err) 
            return console.error('upload failed:', err);
        console.log('good');
    });
    }   

    setInterval(sendfile, 1000);
```

SERVER

``` js
     var http = require('http');
     http.createServer(function (req, res) {        
         res.writeHead(200, { 'Content-Type': 'text/plain' });
         res.end();
     }).listen(9090);
```

with this exemple, i get often this error in client response SOCKET ERROR =>
 read ECONNRESET Error: read ECONNRESET.
if i don't send the stream in the post request, the problem never happens.

this is the log with NODE_DEBUG=http (on client)

```
    HTTP 8276: sockets 127.0.0.1:9090: 1
    HTTP 8276: write ret = false
    HTTP 8276: write ret = false
    HTTP 8276: write ret = false
    HTTP 8276: write ret = false
    HTTP 8276: write ret = true
    HTTP 8276: write ret = true
    HTTP 8276: outgoing message end.
    HTTP 8276: SOCKET ERROR: read ECONNRESET Error: read ECONNRESET
        at exports._errnoException (util.js:874:11)
       at TCP.onread (net.js:544:26)
     upload failed: { [Error: read ECONNRESET] code: 'ECONNRESET', errno: 'ECONNRESET
     ', syscall: 'read' }
    HTTP 8276: CLIENT socket onClose
    HTTP 8276: removeSocket 127.0.0.1:9090: destroyed: true
    HTTP 8276: HTTP socket close
```

I'm on windows, i have try with nodejs  0.12.2 4.1.0 and 4.2.1 and the last request module 2.65.0

**Comment by duizendnegen** [comment]
:+1:

**Comment by simov** [comment]
Works on my end, I can't reproduce it using your code. Not a problem with request I believe.

**Comment by duizendnegen** [comment]
I have similar issues, doing 6 requests and only in very rare cases do they pass, others hit an ECONNRESET.

**Comment by sdnetwork** [comment]
@simov it is very strange that you can't reproduce the behaviour on my machine it occurs every time with this exemple (one error for 50 success), i will try tomorrow on a linux platform.

have you some tips to find where is the problem ? (node_debug ...).

**Comment by sdnetwork** [comment]
I can't reproduce on mac osx platform ! strange

**Comment by duizendnegen** [comment]
@sdnetwork I am
