### ISSUE TITLE
Content-Length header may not be in defaultProxyHeaderWhiteList 

### ISSUE THREAD

**Issue by yaxia** [request/request#1886]
In [RFC 7231](https://www.ietf.org/rfc/rfc7231.txt), section 4.3.6, it says: 

> A payload within a CONNECT request message has no defined semantics;sending a payload body on a CONNECT request might cause some existing implementations to reject the request.

So it is better not have a body in the CONNECT request. From [RFC 7230](https://www.ietf.org/rfc/rfc7230.txt), section 3.3.2: 

> A user agent SHOULD NOT send a Content-Length header field when the request message does not contain a payload body and the method semantics do not anticipate such a body.

since the payload body is not in the request, the `content-length` should not be set.

Therefore, the `content-length` header should not be in the proxy header white list by default.

**Comment by simov** [comment]
TBH that's a bit abstract for me, can you provider a failing test case in `tests/test-tunnel.js`?

**Comment by mirobers** [comment]
This is an issue we saw with a particular proxy server. The proxy server was failing when it received a CONNECT request with a Content-Length but no payload. The HTTP spec seems to indicate that the CONNECT is actually malformed (by containing Content-Length but no payload). So we're wondering if Content-Length should be removed from the default whitelist. Is there ever value to having Content-Length in a CONNECT request?

This is the line in question: https://github.com/request/request/blob/master/lib/tunnel.js#L15

**Comment by simov** [comment]
> Is there ever value to having Content-Length in a CONNECT request?

No idea, but given that the CONNECT request has no defined body semantics, that's probably a bug on our end.

@mirobers and @yaxia feel free to submit PR to remove the `content-length` from the whitelist. I don't think we even need a test for that. I'll make sure that the PR is properly titled and have links to the appropriate threads, so the reasons for this decision will be available here.

/cc @isaacs

**Comment by mirobers** [comment]
Thank you! We'll also remove transfer-encoding for the same reason.
