### ISSUE TITLE
Callback not call after lose connection with internet

### ISSUE THREAD

**Issue by britishd** [request/request#1888]
Trying to catch error when connection is missing, but i have not seen any error from callback. 

``` javascript
request(options, function(error, response, body) {
            if (error) {
                console.log(error);
            }
            if (!error && response.statusCode == 200) {
                var data = JSON.parse(body);
                deferred.resolve(data);
            }
        })
```

**Comment by wdhorton** [comment]
If you try setting a 'timeout' attribute in the options object, then it should throw an error if you can't connect to the server. The behavior is documented in the README [here](https://github.com/request/request/blob/c289759d10ebd76ff4138e81b39c81badde6e274/README.md#timeouts).
