### ISSUE TITLE
No response headers in response object

### ISSUE THREAD

**Issue by ir-fuel** [request/request#1890]
Hi

The code I wrote uses `request-promise`, but I think the issue is in `request` itself (or in my code), so I put it here.

This is what I do:

```
const options = {
    method:'GET',
    uri:BaseUrl+path,
    resolveWithFullResponse :true
  }


rp(options).then(function(response) {
    console.log(response.headers)
```

Result is `{}`

However when I look in the Chrome developer tools I see:
```
HTTP/1.1 200 OK
X-Powered-By: Express
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET,POST,PUT,DELETE,OPTIONS
Access-Control-Allow-Headers: X-Requested-With,Content-Type,authorization
authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6Impvc2tlIiwiZW1haWwiOiJqb3Jpc0Bhc3R1cy5iZSIsInBhc3N3b3JkSGFzaCI6IiQyYSQxMCQwN0JYOTdGMmR3YXd6VFdoLnEvUEZPWXJhYUVOMlN5NjlobkZEWUplRnExNTVtTTluUVByVyIsImlhdCI6MTQ0Njc1NTEwMywiZXhwIjoxNDQ2NzY1OTAzfQ.SdcXC69nkRxfIn1DbHx-F9_xzW-kC6kvwn26uaNkrJI
Date: Thu, 05 Nov 2015 20:25:03 GMT
Connection: keep-alive
Content-Length: 160
```

Where did all those headers go? 

I am calling this in client-side javascript (using webpack).

Thanks!

**Comment by simov** [comment]
Open issue in the [request-promise](https://github.com/request/request-promise) issue tracker instead.

**Comment by jrnail23** [comment]
This should be re-opened

I'm experiencing the same problem right now, and I'm not using request-promise.

Just using request directly (es6):

```javascript
import request from 'request'

request({
    method: 'GET',
    json: true,
    uri: 'http://localhost:9006/members'
  })
    .on('response', res => {
      console.log(res.statusCode)
      console.log(res.headers)
    })
```

Here are the raw response headers received from my API, (when called from DHC):

```
X-Powered-By: Express
Content-Type: application/json; charset=utf-8
Content-Length: 390
ETag: W/"186-WNgZ5jX8cc8PCX+6dY5Ihw"
Date: Wed, 25 Nov 2015 23:26:12 GMT
Connection: keep-alive
```

but when making that same request using request, I only get this header:
```
content-type: "application/json; charset=utf-8"
```

**Comment by ir-fuel** [comment]
I replaced my lib with another one (`axios`) and the problem remained. After some messing around I found out it was a CORS problem. I had to add this to the response headers on the server:

`Access-Control-Expose-Headers`  with value = a comma separated list of the headers I wanted to receive in the response.

Once I added this everything worked

**Comment by jrnail23** [comment]
@ir-fuel. thanks for the tip.  I'll give that a try!
