### ISSUE TITLE
Websocket support

### ISSUE THREAD

**Issue by Polve** [request/request#1892]
Is it possible to use this library as websocket or sockjs provider for other libs like https://github.com/jmesnil/stomp-websocket ?

That would be useful because sometimes it's needed to pass cookies while opening the websocket to correctly handle the authentication, and that's not possible with libraries like sockjs-client

**Comment by simov** [comment]
What exactly do you mean by using this library as a provider? You can make the initial request using this module and then connect to your websocket server.

**Comment by Polve** [comment]
you can open the stomp library this way:
stompClient = Stomp.over(new SockJS(url));
but in node this not allows you to specify the cookies for the connection, so the request is made without authentication.

What I'm looking for is a way to have a "websocket object" obtained with a request in which I can specify all the headers (and hence the cookies) that can be passed to Stomp.over().

Please forgive me if the request does not make sense, but I'm really stuck in findind some way to accomplish this seemingly simple operation in node and I think that your library can be of help.

**Comment by neuroscr** [comment]
You might be looking for https://github.com/websockets/ws

**Comment by Polve** [comment]
With that library I can't send cookies to the webserver while opening the websocket

**Comment by neuroscr** [comment]
Try a redirect, set the cookie and redirect to the real websocket
