### ISSUE TITLE
Support for stale-while-revalidate and stale-if-error HTTP headers

### ISSUE THREAD

**Issue by debnath** [request/request#1896]
Hey guys.  My use case requires more flexibility for our HTTP caching, and I found these 2 handy headers (stale-while-revalidate and stale-if-error) defined in this RFC:

https://tools.ietf.org/html/rfc5861#page-3

I was thinking of working on this and submitting a PR to this request repo.   I was wondering if this is something you guys would consider?  If it's something that would be an outright rejection I will instead just make it a separate NPM module. :)

Thanks.

**Comment by simov** [comment]
If you can isolate your new logic into separate module under the lib folder that would be great. Also this new logic should be enabled via options key explicitly.

The other way around is to consume request in your own module and implement it there. Either way I would be interested to see the implementation.

**Comment by cyberthom** [comment]
I needed this exact use case and have forked `lru-cache` in order to support it:
https://github.com/cyberthom/stale-lru-cache

You could do something like this to cache responses from `request`:
```javascript
var LRU = require('stale-lru-cache');
var cache = LRU(100);

var url = 'http://www.google.com/';
var key = url;
cache.wrap(key, function (callback) {
    request(url, function (error, response, body) {
        if (error) return callback(error);
        if (response.statusCode >= 400) return callback(new Error('Response error'));
        callback(null, body, response.headers['cache-control']);
    });
}, function (error, value) {
    // Do something with value
});
```
