### ISSUE TITLE
Implement optional additional socket settings control

### ISSUE THREAD

**Issue by mkozjak** [request/request#1908]
We should be able to configure TCP_KEEPIDLE, TCP_KEEPINTVL and TCP_KEEPCNT for use cases where the socket on the sending side is prepared, but the data is never sent, so we cannot see why the connection is hanging once the net.setKeepAlive() is used.

net-keepalive package has this implemented. https://www.npmjs.com/package/net-keepalive

**Comment by pkoretic** [comment]
@simov anything on this one?
we just recently hit a problem with this, and decided to make our request wrapper with net-keepalive  to handle it
this is very common in firewall secured servers

**Comment by simov** [comment]
Wrapping it up is probably the way to go, though you can still share your implementation here.

**Comment by pkoretic** [comment]
we did promise version since we are working only with promises/generators
https://www.npmjs.com/package/request-timeout-keepalive
