### ISSUE TITLE
npm install request creates sshpk as a node_modules even though not in package.json 

### ISSUE THREAD

**Issue by ssbiswal1987** [request/request#1909]
request@2.66.0 

Has a node_modules sshpk. This is not available in package.json however it gets dowloaded.

Not sure why. Can this be fixed please?

**Comment by simov** [comment]
Read about how npm3 download modules.

**Comment by ssbiswal1987** [comment]
I have used npm 4.2.2 and the problem is we do a npm shrinkwrap and this called extrateneous error.

**Comment by ssbiswal1987** [comment]
Sorry, but could you be kind enough to explain why?

**Comment by simov** [comment]
Which version of npm do you use?

```bash
$ npm -v
```

**Comment by ssbiswal1987** [comment]
I had 2.14.7

**Comment by simov** [comment]
`sshpk` is a dependency of one of our dependencies, no idea how is this end up being directly in the node_modules folder, but certainly not a problem of request.

Can you try with request 2.65 just in case, because I just published 2.66 and I want to clear that possibility?

**Comment by ssbiswal1987** [comment]
We were using 2.65.0 and we never had sshpk landing up in the node_modules folder.

It just happens with 2.66.0

**Comment by ssbiswal1987** [comment]
Tried again with 2.65.0. All is good with it.

**Comment by simov** [comment]
Request 2.66 depends on the latest version of the [http-signature](https://github.com/joyent/node-http-signature) module, which in turn sets the `sshpk` module as `peerDependency`. So, you can ask them why is this needed.

**Comment by ssbiswal1987** [comment]
Looks like someone has already complained.

https://github.com/joyent/node-http-signature/issues/51

**Comment by simov** [comment]
Yep, most probably. The real question is why was a peer dependency needed in the first place.

**Comment by ssbiswal1987** [comment]
Yeah . The strange thing is , I installed node 5.1.0 and npm 3.3.2 and there it works fine with request@2.66.0 and npm shrinkwrap.

**Comment by simov** [comment]
npm 3.x doesn't install peer deps by default.

**Comment by suprememoocow** [comment]
I raised #1910 without seeing this had already been reported.

As a workaround for now, I've added sshpk as a direct dependency of the module we're trying to shrinkwrap until we have a better solution.

**Comment by simov** [comment]
Yep, once they resolve the issue I'll bump the version here as well.

**Comment by garrows** [comment]
Seems to only be happening with npm v2.x.x. npm v3.4.0 seems unaffected. 

Here is my reproduction steps. 
```
mkdir /tmp/shrinkwrap-test
cd /tmp/shrinkwrap-test/
npm init -y
npm install --save request
```
Gives these warnings
```
npm WARN peerDependencies The peer dependency sshpk@^1.4.6 included from http-signature will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
```
```
npm shrinkwrap
```
Gives this error
```
npm ERR! Darwin 15.0.0
npm ERR! argv "node" "/Users/glen/.nvm/v0.10.40/bin/npm" "shrinkwrap"
npm ERR! node v0.10.40
npm ERR! npm  v2.14.3

npm ERR! Problems were encountered
npm ERR! Please correct and try again.
npm ERR! extraneous: sshpk@1.7.0 /private/tmp/shrinkwrap-test/node_modules/request/node_modules/sshpk
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /private/tmp/shrinkwrap-test/npm-debug.log
```

Reproduced with the following versions
```
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7

npm ERR! node v0.10.40
npm ERR! npm  v2.14.3

npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
```

**Comment by simov** [comment]
request@2.67.0 is published on NPM :tada:

**Comment by ssbiswal1987** [comment]
Thank you.

**Comment by IgorAufricht** [comment]
Thank you for the fast update.

:+1:
