### ISSUE TITLE
Bad function name

### ISSUE THREAD

**Issue by jrgleason** [request/request#1911]
I am having issues with proxies so I am going back through the code and I noticed this in request.js

    function setContentLength () {
       ...
       var protocol = self.proxy && !self.tunnel ? self.proxy.protocol : self.uri.protocol
         , defaultModules = {'http:':http, 'https:':https}
         , httpModules = self.httpModules || {}

      self.httpModule = httpModules[protocol] || defaultModules[protocol]

      if (!self.httpModule) {
        return self.emit('error', new Error('Invalid protocol: ' + protocol))
      }
      ...
    }

This to me is doing far more than just setting content length and could easily cause confusion.

**Comment by simov** [comment]
It's actually not the way you see it:

![highlight](https://cloud.githubusercontent.com/assets/1694112/11256166/fe77a0b2-8e52-11e5-9596-461ea8dc9398.png)

Bracket highlighting might help in this case.

**Comment by jrgleason** [comment]
Ahhh ok I was just looking in github the project wasn't downloaded.
