### ISSUE TITLE
Chrome w/401 error, Authentication Required Popup

### ISSUE THREAD

**Issue by wodrich** [request/request#1912]
I implemented the code (attached below) to route restful calls to another server where they get processed.  It works terrific by the way, until the other server throws a 401 error.   Firefox correctly processes subsequent javascript, sees the 401 and brings the user back to our login page.  Chrome pops up an "Authentication Required" box asking for a UserName and password.  While the pop-up is there, the GET calls show as pending in the Chrome debugger and then finally show as 401 errors when I cancel the popup.      

Do I need to do something special to pass 401 errors to Chrome and prevent this popup from happening?

```js
app.use('/rest', function(req, res) {
  var request = require('request');
  var url = backendConfiguration.servicesBaseUrl + '/rest'+ req.url;
  var r = request(url);
  req.pipe(r).pipe(res);
});
```

**Comment by simov** [comment]
```js
var r = request(url, {auth: {user: 'username', pass: 'password'}});
```

**Comment by wodrich** [comment]
Thanks @simov , but I am already passing Basic auth via the req.  In this case the other Server has rejected those credentials (because they are expired) and throws a 401 error.  I want to pass that 401 to some javascript which will take the user to another page (not show a popup to the user).  Again, this is fine with Firefox but not Chrome.

**Comment by wodrich** [comment]
app.use('/rest', function(req, res) {
  var r = request(url)
    .on('response', function(response) { })
    .on('error', function(response) {
            console.log("crikey error!");
            response.statusCode = 406;
          })
    .pipe(res);
});

Hi again.  So I have tried several different things and the above code seems to do exactly what I need, I can catch the error response and change the error code.  Unfortunately I lose all the benefits of the data in my original request.  The headers,  any form data, auth properties, etc.  With my original "req.pipe(r).pipe(res)" I didn't have to do anything at all.   I don't have to manually copy all of that out of the request I hope?  Perhaps I am missing something?

**Comment by wodrich** [comment]
I went with the chained approach and copied all the stuff I needed from the original request (it took awhile to figure out what I needed).   Closing this issue and attaching the code I used in case it can be of use to anyone else.   

app.use('/rest', function (req, res)
{
  var url = backendConfiguration.servicesBaseUrl + '/rest' + req.url;
  var options = {
    url: url,
    method: req.method,
    json: true,
    body: req.body,
    headers: {
      'Authorization' : req.headers.authorization,
      'Accept': "application/json",
      'Content-Type': "application/json"
    }
  };

  var r = request(url, options)
    .on('response', function (response)
        {
          if (response.statusCode === 200)
          {
          }
          if (response.statusCode === 401)
          {
            console.log("401 error received");
            res.statusCode = 470;
            res.end(response.text);
          }
        })
    .on('error', function (response)
        {
          console.log("error received: " +  response.text + " code: " + response.statusCode );
          if (response.statusCode === 401)
          {
            res.statusCode = 470;
            res.end(response.text);
          }
        })
    .pipe(res);
});
