### ISSUE TITLE
DNS lookup isn't cancelled when timeout is reached

### ISSUE THREAD

**Issue by DuBistKomisch** [request/request#1914]
Hi,

I've run into a situation where if our Linux device is configured with an invalid static IP (e.g. customer makes a typo in the configuration), DNS lookup takes 40 seconds then times out and `request` fails with the appropriate error (`ENOTFOUND` on `getaddrinfo` syscall).

This is an issue in our pre-startup script, since passing `timeout: 5000` makes the callback return the error after 5 seconds, but internally the DNS lookup doesn't seem to be cancelled, because node doesn't exit until 40 seconds after the request is made even though none of our code is left running.

My current workaround is to call `process.kill(process.pid)` on a timeout error, so the device doesn't sit doing nothing for 35 seconds.

**Comment by simov** [comment]
I think that's an issue with Node core, as request doesn't do anything DNS related in its code base.

**Comment by DuBistKomisch** [comment]
Yeah, I looked over the code a bit and it looks like on timeout it just calls `http.ClientRequest.abort`, so the issue is internal to Node. I'll test it on several versions and take it up with them, thanks.

**Comment by kevinburke** [comment]
I'm not sure there's much that can be done here... as far as I can tell, node core uses the `getaddrinfo` syscall on Linux/Unix machines, which doesn't expose a timeout as part of its interface. Maybe it can be killed halfway through? or node could just give up on it? 

either way you'll probably have more luck setting a timeout in `/etc/resolv.conf` on the machine.

**Comment by DuBistKomisch** [comment]
I've dived into the Node source and it looks like the inability to cancel the DNS lookup on a connecting socket is lamented in [a comment in `lib/net.js`](https://github.com/nodejs/node/blob/20285ad17755187ece16b8a5effeaa87f5407da2/lib/net.js#L971). `dns.lookup` in `lib/dns.js` itself just calls down to native code, which seems to be [this part of libuv](https://github.com/nodejs/node/blob/6fff47ffacfe663efeb0d31ebd700a65bf5521ba/deps/uv/src/unix/getaddrinfo.c), which in turn chucks the `getaddrinfo` call into another thread, as mentioned in the [public API](http://docs.libuv.org/en/v1.x/threadpool.html). But the public API also says that [you can't cancel executing work](http://docs.libuv.org/en/v1.x/request.html#c.uv_cancel). From my understanding it may be a limitation of the design of libuv, or least not be easy to change.

So yeah, looks like `/etc/resolve.conf` may be our best bet.

I also ran into some [Node documentation](https://nodejs.org/api/dns.html#dns_dns_lookup) which also references the worker thread pool, which explains the degraded file I/O performance we were also seeing with this issue, for reference.

**Comment by simov** [comment]
Just by looking at the [Implementation considerations](https://nodejs.org/api/dns.html#dns_implementation_considerations) you can probably use `dns.resolve` instead and if it succeeds pass that IP to request. Starting from some iojs version onward (no idea which one exactly) the underlying socket honors the IP address passed as a hostname and it doesn't try to resolve it further, hence it won't stuck on `dns.lookup`.

So, if you are using newer version than node 0.12 that might work.

**Comment by simov** [comment]
Whoops actually `dns.reverse` in your case.

**Comment by DuBistKomisch** [comment]
Hmm, wrapping request with `dns.resolve` sounds like it'd work. :thumbsup:

Unfortunately we're still on Node 0.12... I've been putting off upgrading to 4/5 because I'll have to migrate all our native extensions to nan 2.

Regardless, I'll test these solutions out on Monday. Thanks for all the input.
