### ISSUE TITLE
Column convert string with "e" to numeric

### ISSUE THREAD

**Issue by AminaG** [request/request#1918]
When I have this data in the field:
29e1

It is converting it to: 290.

I didn't want it. I want it as string: "29e1"

How to solve it?

**Comment by AminaG** [comment]
I tried to solve it by reading the parser.js and connection.js but didn't found. I thought maybe it because you using parseFloat, but no.

**Comment by simov** [comment]
Are you sure you posted your answer in the correct issue tracker?

**Comment by AminaG** [comment]
Sorry. It's related to node mysql
