### ISSUE TITLE
Version dependency issue for 0.10.

### ISSUE THREAD

**Issue by ErisDS** [request/request#1921]
In the package.json, request indicates it has support for engines `"node": ">=0.8.0"`

However, it depends on hawk `3.1.0`, which states it has support for engines `"node": ">=0.10.32"`

Hawk 3.1.0 depends on boom `^2.8.x`

Because (I think) of the combo of the caret and the x in `^2.8.x` boom, on certain versions of 0.10, 3.0.0 is installed instead of 2.8.0. 

Although boom `2.8.0` had the same engines as request `"node": ">=0.8.0"`, boom `3.0.0 `has been upgraded to only support node `4.0.0` and uses the new `const` syntax.

I was able to reproduce this for node 0.10.13 and there is a similar issue open for 0.10.5: https://github.com/request/request/issues/1452. I realise these are very old versions, but it seems to me that support has been dropped accidentally due to changes inside dependencies.

I have raised this issue against hawk as well: https://github.com/hueniverse/hawk/issues/157

**Comment by ErisDS** [comment]
Hawk@3.1.2 has been released with `boom@2.x.x`, which should resolve this. I can submit a PR but I think greenkeeper is going to do that automatically?

**Comment by simov** [comment]
Yep, greenkeeper does that https://github.com/request/request/pull/1891#issuecomment-154328694
I personally don't think that we are ready to drop everything below 4.0 here yet.

**Comment by ErisDS** [comment]
@simov, I'm not talking about dropping anything below 4.0? Hawk 3.1.2 is a maintenance release which fixes support for several older versions of 0.10, for which request has been broken for around 20 days. 

Thankfully because of the tilde in the request package.json, it automatically picks up this fix and is no longer broken, so nothing is needed to be done.

**Comment by simov** [comment]
Yep, I though I'm missing something but I was too sleepy at that time. Hopefully greenkeeper will notify us if they bump the minor version at some point - like 3.2.0 or something like that.
