### ISSUE TITLE
SSL Error: Hostname/IP doesn't match certificate's altnames

### ISSUE THREAD

**Issue by szakaly** [request/request#1926]
Hy!

I wan't to use your request repo for my project.

My task is, i need to pull a request (with my node.js server; with custom headers and JSON body datas) to an other website / server, where using Self-Signed-Certificate Handshaking...

I worked all day, but i can't fix some issues. Here is my progression and my code:
(I export from Mozilla firefox and google chrome too the certificate and import to ca, where you can see. I get this error message: [Error: Hostname/IP doesn't match certificate's altnames: "Host: hman.aut.bme.hu. is not cert's CN: hman.aut.bme.hu:10080"]
  reason: 'Host: hman.aut.bme.hu. is not cert\'s CN: hman.aut.bme.hu:10080', ...

var options = {
          method: 'POST',
          url: rows[0].joinURL,                                  //"https://hman.aut.bme.hu:10080/api/data/"
          agentOptions: {

```
         ca: fs.readFileSync('./views/ssl/hman.aut.bme.hu-10080.crt'),
         passphrase: 'password'
      },
      headers: {
         'Content-type': 'application/json',
         'Authorization': rows[0].authCookie  //thats no Cookie, just the name is bad, thats a Basic ...=
      },
      body: kuldes
   };
```

request(options, callback);

Please, if you have any ideaa, i need the fix this project in my University.
Thank you for your help in advance.

Best regards, 

Csaba Szakály

**Comment by strictlyd** [comment]
Please refer to #1777.

**Comment by alex-shamshurin** [comment]
Same issue here
I set this for server environment, but seems that axios do not see that.

```
import https from 'https'

axios.defaults.httpsAgent = new https.Agent({
  rejectUnauthorized: false,
})
```
