### ISSUE TITLE
using behind a proxy is not well documented. 

### ISSUE THREAD

**Issue by Afshintm** [request/request#1928]
Hi, 
Can someone please give a clear example of using request behind a corporate proxy and how to pass username ans password if require ?

It would be much appreciated :)

**Comment by NNM11** [comment]
+1.
I saw the global_tunneling (https://www.npmjs.com/package/global-tunnel) described using auto_config to set proxy for the request module as:
process.env.http_proxy = 'http://10.0.0.1:3129';
globalTunnel.initialize();

It mentioned the request module used 'global-tunnel' if the environment variable http_proxy is set.
Please explain how this is used in the request module. 
Thx,
