### ISSUE TITLE
Test case suite fails on Node 4.2.2

### ISSUE THREAD

**Issue by corporatepiyush** [request/request#1929]
> request@2.67.1 test /Users/redpanda/work/github/request
> npm run lint && npm run test-ci && npm run test-browser

> request@2.67.1 lint /Users/redpanda/work/github/request
> eslint lib/ *.js tests/ && echo Lint passed.

Lint passed.

> request@2.67.1 test-ci /Users/redpanda/work/github/request
> taper tests/test-*.js

ok test-agent.js .................. 20/20
ok test-agentOptions.js ............. 4/4
ok test-baseUrl.js ................ 63/63
ok test-basic-auth.js ............. 32/32
ok test-bearer-auth.js ............ 17/17
ok test-body.js ................... 19/19
ok test-cookies.js ................ 25/25
ok test-defaults.js ............... 54/54
ok test-digest-auth.js ............ 15/15
ok test-emptyBody.js ................ 9/9
ok test-errors.js ................. 11/11
ok test-event-forwarding.js ......... 4/4
ok test-follow-all-303.js ........... 3/3
ok test-follow-all.js ............... 3/3
ok test-form-data-error.js .......... 1/1
ok test-form-data.js .............. 64/64
ok test-form-urlencoded.js ........ 28/28
ok test-form.js ................... 19/19
ok test-gzip.js ................... 24/24
ok test-har.js .................... 24/24
ok test-hawk.js ..................... 3/3
ok test-headers.js ................ 25/25
ok test-http-signature.js ........... 4/4
ok test-httpModule.js ............. 50/50
ok test-https.js .................. 20/20
ok test-isUrl.js .................. 17/17
ok test-json-request.js ........... 28/28
ok test-localAddress.js ............. 7/7
ok test-multipart-encoding.js ..... 70/70
ok test-multipart.js ............ 148/148
ok test-node-debug.js ............. 20/20
ok test-oauth.js .................. 41/41
ok test-onelineproxy.js ............. 3/3
ok test-option-reuse.js ........... 10/10
ok test-params.js ................. 12/12
ok test-piped-redirect.js ........... 2/2
ok test-pipes.js .................. 35/35
ok test-pool.js ................... 16/16
ok test-promise.js .................. 3/3
ok test-proxy-connect.js ............ 5/5
ok test-proxy.js ................ 104/104
ok test-qs.js ..................... 24/24
ok test-redirect-auth.js .......... 18/18
ok test-redirect-complex.js ....... 40/40
ok test-redirect.js ............... 87/87
ok test-rfc3986.js ................ 44/44
not ok test-timeout.js ............ 17/19
# setup
# should timeout
ok 1 should not be equal
ok 2 Error ETIMEDOUT or ESOCKETTIMEDOUT
# should set connect to false
ok 3 should not be equal
ok 4 Error ETIMEDOUT or ESOCKETTIMEDOUT
ok 5 Read Timeout Error should set 'connect' property to false
# should timeout with events
ok 6 should be equal
ok 7 should not be equal
ok 8 Error ETIMEDOUT or ESOCKETTIMEDOUT
# should not timeout
ok 9 should be equal
ok 10 should be equal
# no timeout
ok 11 should be equal
ok 12 should be equal
# negative timeout
ok 13 should not be equal
ok 14 Error ETIMEDOUT or ESOCKETTIMEDOUT
# float timeout
ok 15 should not be equal
ok 16 Error ETIMEDOUT or ESOCKETTIMEDOUT
# connect timeout
ok 17 should not be equal
not ok 18 Error ETIMEDOUT or ESOCKETTIMEDOUT
    operator: ok
    expected: true
    actual:   false
    at: checkErrCode (/Users/redpanda/work/github/request/tests/test-timeout.js:5:5)
  ...
not ok 19 Connect Timeout Error should set 'connect' property to true
    operator: ok
    expected: true
    actual:   false
    at: Request._callback (/Users/redpanda/work/github/request/tests/test-timeout.js:136:9)
  ...
# cleanup

Assert: "Error ETIMEDOUT or ESOCKETTIMEDOUT", 
	 found: false 
	wanted: true
	checkErrCode (/Users/redpanda/work/github/request/tests/test-timeout.js:5:5)
Assert: "Connect Timeout Error should set 'connect' property to true", 
	 found: false 
	wanted: true
	Request._callback (/Users/redpanda/work/github/request/tests/test-timeout.js:136:9)

ok test-timing.js ................... 7/7
ok test-toJSON.js ................... 7/7
ok test-tunnel.js ................. 26/26
ok test-unix.js ..................... 6/6
total ......................... 1388/1391

not ok

npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "test-ci"
npm ERR! node v4.2.2
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE
npm ERR! request@2.67.1 test-ci: `taper tests/test-*.js`
npm ERR! Exit status 3
npm ERR! 
npm ERR! Failed at the request@2.67.1 test-ci script 'taper tests/test-*.js'.
npm ERR! This is most likely a problem with the request package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     taper tests/test-*.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls request
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/redpanda/work/github/request/npm-debug.log
npm ERR! Test failed.  See above for more details.

**Comment by simov** [comment]
Yep, the timeout tests are not reliable, they pass on my workstation for example, but they are disabled on TravisCI.
