### ISSUE TITLE
Error: socket hang up in Node 4.2.1 (but not 0.12)

### ISSUE THREAD

**Issue by callumacrae** [request/request#1934]
Hello!

I'm trying to debug this issue: https://github.com/blakmatrix/node-zendesk/issues/110

Having looked into it a bit, it looks like it is a bug in `request`—the only alternative could be that the API I'm making requests to is rejecting the useragent with `node/4.2.1` in and not the one with `node/0.12` in.

`request` is being passed the same data in both versions of Node, and is being called multiple times. It never fails on the first time it is called, it usually fails between the third and sixth times—it's being passed only slightly different data (page numbers), but sporadically fails.

This is some sample data that sometimes succeeds and sometimes fails:

```
{ stores:
   { defaults:
      Literal {
        type: 'literal',
        store: [Object],
        mtimes: {},
        readOnly: true,
        loadFrom: null,
        logicalSeparator: ':' } },
  sources: [],
  headers:
   { 'Content-Type': 'application/json',
     Accept: 'application/json',
     'User-Agent': 'node-zendesk/1.1.5 (node/4.2.1)',
     Authorization: 'Basic [redacted]' },
  uri: 'https://[redacted].zendesk.com/api/v2/search.json?page=3&query=checkout-failure',
  method: 'GET' }
```

And request is being given the following defaults:

```
{ jar: RequestJar { _jar: CookieJar { store: { idx: {} } } },
  encoding: null,
  timeout: 240000,
  proxy: null,
  secureOptions: 134217728 }
```

The following error is (eventually) thrown:

```
Error: socket hang up
    at createHangUpError (_http_client.js:203:15)
    at TLSSocket.socketOnEnd (_http_client.js:288:23)
    at emitNone (events.js:72:20)
    at TLSSocket.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:903:12)
    at doNTCallback2 (node.js:439:9)
    at process._tickCallback (node.js:353:17)
```

What could be causing this? Is this a bug in request, or is there something wrong with how we're calling it?

I'm too far deep into a library I am unfamiliar with to make a stripped down test case. If necessary, I can make one—wanted to check it wasn't something obvious before investing the time, first, though.

Here is where request is initiated: https://github.com/blakmatrix/node-zendesk/blob/master/lib/client/client.js#L35-L41  
Here is where it is called: https://github.com/blakmatrix/node-zendesk/blob/master/lib/client/client.js#L100-L102

Help would be much appreciated, thanks!

**Comment by fiznool** [comment]
@callumacrae did you try running request in [debug mode](https://github.com/request/request/blob/master/README.md#debugging)? You could then compare the data when using node 0.12 and node 4 to see if there is any discrepancy.

**Comment by dungbx** [comment]
Hi guys. I have same problem here.
I tried to compare data between request on node 0.12.9 and 4.2.3, they are all the same.
It might be because of the http module itself.

**Comment by mogadanez** [comment]
Same error after exact 2 minutes of waiting response.

**Comment by erikzrekz** [comment]
I don't have much to add other than I can confirm that I'm getting the same error after making requests in node 4.

**Comment by erikzrekz** [comment]
@simov hate to bug you, but do you have any insight into what could be happening here?

**Comment by fiznool** [comment]
We've also run into the same issue, but we've reproduced with just the raw http library. So I don't really think this is anything to do with request.

Its a totally bonkers bug and the only thing I can think of is that zendesk's back end has an issue somewhere.

**Comment by erikzrekz** [comment]
@fiznool okay, hmm. Do you think it's worth connecting with someone at Zendesk?

**Comment by callumacrae** [comment]
I can't see it being an issue with Zendesk if it's specific to a version of node. Maybe worth opening an issue on the node repo?

**Comment by fiznool** [comment]
@erikzrekz we already got in touch with them, and they directed us to open an issue on their node repo. That's the issue mentioned above.

**Comment by fiznool** [comment]
@callumacrae agreed, this probably isn't the best place to be discussing this since I don;t think it has anything to do with request.

**Comment by fiznool** [comment]
Please refer to https://github.com/blakmatrix/node-zendesk/issues/110#issuecomment-171275768, the solution is to add `forever: true` to the request options.

**Comment by Shawn-ye** [comment]
Did you use a keepAlive socket? If the server requires a keep-alive connection , and your headers doesn't include the keep-alive option and it will return an socket hang up error.
and the most important is , In node 0.12, setting 'Connection': 'Keep-Alive' property in http option will work. But in node 4.0 or above, if you would like to use keep-alive connection, you have to create an agent and set its keepAlive property to true. So,in this situation, the same code will work on 0.12 but won't work anymore on 4.0.
I hope this will help you .

**Comment by yogeshtas** [comment]
I have same problem while creating new object in s3.

**Comment by lfreneda** [comment]
same problem here, tips?
