### ISSUE TITLE
request error

### ISSUE THREAD

**Issue by andresetevejob** [request/request#1936]
Hi all, I have an error with request : Error: connect ECONNREFUSED. I don't know what that mean

**Comment by martinpucala** [comment]
maybe the server refused the connection?

**Comment by rujmah** [comment]
This is Node.js error. See https://nodejs.org/api/errors.html#errors_econnrefused_connection_refused

It means the connection has been refused to the end point (server) you are trying to access. Most likely you need to check the connection (`curl http://[server address]`) and not an issue with Request npm.
