### ISSUE TITLE
Some errors thrown by Node's `lib/net` during socket setup are impossible to handle

### ISSUE THREAD

**Issue by JordanMilne** [request/request#1946]
For example, the port range exception:

https://github.com/nodejs/node/blob/6fff47ffacfe663efeb0d31ebd700a65bf5521ba/lib/net.js#L924

I'm able to catch it fine when I use `http` directly:

``` node
try{
  http.get("http://localhost:999999999999/")
} catch(err) {
  console.log("Gotcha!", err.message)
};
// Gotcha! port should be >= 0 and < 65536: 999999999999
```

but when I use `request` I can't catch it either through a `try/catch` or by doing `.on('error', handler)`. I always get a stack trace:

``` node
try{
  request.get("http://localhost:999999999999/", function() {
    console.log("BAR!");
  }).on('error', function() {
    console.log("FOO!");
  })
} catch(err){
  console.log("Gotcha!", err.message)
}
> RangeError: port should be >= 0 and < 65536: 999999999999
    at lookupAndConnect (net.js:927:13)
    at Socket.connect (net.js:904:5)
    at Agent.exports.connect.exports.createConnection (net.js:63:35)
    at Agent.createSocket (_http_agent.js:174:16)
    at Agent.addRequest (_http_agent.js:143:23)
    at new ClientRequest (_http_client.js:133:16)
    at Object.exports.request (http.js:31:10)
    at Request.start (..../node_modules/request/request.js:746:30)
    at Request.end (..../node_modules/request/request.js:1357:10)
    at end (..../node_modules/request/request.js:574:14)
```

Not sure what's the right thing to do here. Catch the errors in `end()` and stuff them into the error callback if we have one, re-raising if we don't?

**Comment by simov** [comment]
You can't catch the error because this code is executed on [process.nextTick](https://nodejs.org/api/process.html#process_process_nexttick_callback_arg) in request. You can start the request explicitly by calling the `end` method:

```js
try{
  var req = request.get("http://localhost:999999999999/", function() {
    console.log("BAR!");
  })
  req.on('error', function() {
    console.log("FOO!");
  })
  req.end()
} catch(err){
  console.log("Gotcha!", err.message)
}
```

**Comment by JordanMilne** [comment]
Is there any way to handle them without having to start the request to start in the same tick?

**Comment by simov** [comment]
No, these are synchronous errors.
