### ISSUE TITLE
Middle-of-response timeouts

### ISSUE THREAD

**Issue by SEAPUNK** [request/request#1947]
One thing I have been having a problem with is that some of the requests I make never finish -- they just hang midway. I would like request to be able to time out a request if no new data is sent within x time.

Reproduction:

```javascript
'use strict'
let request = require('request')
let http = require('http')

console.log('creating server')

let srv = new http.Server()
srv.on('request', function(request, response){
  response.setTimeout(1, function(){
    // do nothing, so the response doesn't time out
  })
  response.write('this is a ')
  // response.write('complete request')
  // response.end()
})
srv.listen(24888)

console.time('request')
console.log('creating request')
request('http://localhost:24888', function(err, response, body){
  console.timeEnd('request')
  console.log('got response')
  console.log(err)
  console.log(body)
})

process.on('SIGINT', function(){
  console.log('stopping request')
  console.timeEnd('request')
  process.exit()
})
```

When I run the code for a few minutes:

```
creating server
creating request
^Cstopping request
request: 307429.949ms
```

**Comment by kevinburke** [comment]
In theory https://github.com/kevinburke/request/blob/master/request.js#L814 should be setting a timeout on the socket, which is outside of Javascript-land. The socket will detect if no  data has been sent in a given interval and return an ETIMEDOUT error.

**Comment by kevinburke** [comment]
er, oh, you might need to set a timeout on the request to trigger that logic...

**Comment by SEAPUNK** [comment]
@kevinburke Yeah, I _just now_ found that. For some reason, I kept thinking that the timeout had a default value of ~30 seconds.

**Comment by SEAPUNK** [comment]
Yeah, I found where I misread it:

```
Note that if the underlying TCP connection cannot be established, the OS-wide TCP connection timeout will overrule the timeout option (the default in Linux can be anywhere from 20-120 seconds).
```
