### ISSUE TITLE
Safari: Empty Bearer Authorization header causes error in Safari (Desktop/iOS)

### ISSUE THREAD

**Issue by nemosupremo** [request/request#1951]
Currently, I have a default request object setup with the following options:

``` js
var options = {
  baseUrl: window.location.protocol + baseUrl,
  json: true,
  simple: false,
  resolveWithFullResponse: true,
  auth: {
    bearer: function() {
      if (AdminStore == null) {
        AdminStore = require("stores/admin");
      }
      return AdminStore.getToken();
    }
  }
};
```

When the user is not logged in, `getToken()` will return `null`. When this happens request auth code [will opt to send an empty Bearer token](https://github.com/request/request/blob/master/lib/auth.js#L45).

`auth.js`

``` js
if (sendImmediately || typeof sendImmediately === 'undefined') {
    if (typeof bearer === 'function') {
      bearer = bearer()
    }
    var authHeader = 'Bearer ' + (bearer || '')
   self.sentAuth = true
   return authHeader
 }
```

This results in the Authorization header being set to `Authorization: Bearer`. For some reason Desktop Safari 9.0.1 and iOS Safari 9.1 don't like this, and when you try to set the header you get `DOM Exception 12: An invalid or illegal string was specified.` If I return a garbage string in `Bearer`, such as "abc", the error does not occur. (Possibly related: https://forum.ionicframework.com/t/solved-ios9-fails-with-setrequestheader-native-with-custom-headers-in-http-service/32399/8)

In any case, it seems to me the best option would be not set the header at all if the `bearer` function returns null.

**Comment by nemothekid** [comment]
This error can reproduced in the Safari console:

```js
> var xhr = new XMLHttpRequest();
  xhr.open("GET", "/", true); 
  xhr.setRequestHeader("authorization", "Bearer notarealtoken");
< undefined
> var xhr = new XMLHttpRequest();
  xhr.open("GET", "/", true); 
  xhr.setRequestHeader("authorization", "Bearer ");
< Error: SyntaxError: DOM Exception 12
```

**Comment by simov** [comment]
Just make the `if (AdminStore == null)` outside of the `options` object and set the `auth` key only if needed.

**Comment by nemothekid** [comment]
In this case, the options I'm passing here are being passed to the `defaults` function, which I am then exporting the wrapper as a module -- so the routine in question only gets called once. 

```js
var options = {
  baseUrl: window.location.protocol + baseUrl,
  json: true,
  simple: false,
  resolveWithFullResponse: true,
  auth: {
    bearer: function() {
      if (AdminStore == null) {
        AdminStore = require("stores/admin");
      }
      return AdminStore.getToken() || "invalid_token";
    }
  }
};

module.exports = require('request-promise').defaults(options);
```

It wouldn't be useful to set it outside of options, because if the user authenticates during the course of the session, then the wrapper won't be aware of it.

I can provide a PR of the change I'm describing.
