### ISSUE TITLE
Event "complete" triggered twice of a request.

### ISSUE THREAD

**Issue by XuJinNet** [request/request#1957]
```javascript
request(url, options)
            .on('error',  function (error) {
                ......
            }).on('response',  function(options, response) {
                    ......
                    this.readResponseBody(response);
                    this.on('complete', function (response, body) {
                        ......
                    });
           });
```
In this code, the "complete" callback function wil be invoked twice.

**Comment by simov** [comment]
Internally the `readResponseBody` method is called only when there is a callback function. You get the complete event multiple times because you are calling this method manually.

**Comment by XuJinNet** [comment]
OK, thanks.  i shoud use this.once('complete', funtion() ......) instead of this.on(......).
