### ISSUE TITLE
Testcase failure for PhantomJS2.0

### ISSUE THREAD

**Issue by salamani** [request/request#1974]
Hi,
I am having issue of PhantomJS crashing while running the testcases.
The  PhantomJS2.0 has been ported for ppc64le machine and working correctly.
Strongloop should migrate to 2.0.0 because the breakpad code is removed from 2.0.0. Since this is a very complex code to port, 1.9.8 can not be ported to ppc64le easily.

The log while running testcase for npm test is as follow:
 request@2.67.1 test /root/ravi/new_test/request
 npm run lint && npm run test-ci && npm run test-browser

 request@2.67.1 lint /root/ravi/new_test/request
 eslint lib/ *.js tests/ && echo Lint passed.

Lint passed.

 request@2.67.1 test-ci /root/ravi/new_test/request
 taper tests/test-*.js

ok test-agent.js .................. 20/20
ok test-agentOptions.js ............. 4/4
ok test-baseUrl.js ................ 63/63
ok test-basic-auth.js ............. 32/32
ok test-bearer-auth.js ............ 17/17
ok test-body.js ................... 19/19
ok test-cookies.js ................ 25/25
ok test-defaults.js ............... 54/54
ok test-digest-auth.js ............ 15/15
ok test-emptyBody.js ................ 9/9
ok test-errors.js ................. 11/11
ok test-event-forwarding.js ......... 4/4
ok test-follow-all-303.js ........... 3/3
ok test-follow-all.js ............... 3/3
ok test-form-data-error.js .......... 2/2
ok test-form-data.js .............. 64/64
ok test-form-urlencoded.js ........ 28/28
ok test-form.js ................... 19/19
ok test-gzip.js ................... 24/24
ok test-har.js .................... 24/24
ok test-hawk.js ..................... 3/3
ok test-headers.js ................ 25/25
ok test-http-signature.js ........... 4/4
ok test-httpModule.js ............. 50/50
ok test-https.js .................. 20/20
ok test-isUrl.js .................. 17/17
ok test-json-request.js ........... 28/28
ok test-localAddress.js ............. 7/7
ok test-multipart-encoding.js ..... 70/70
ok test-multipart.js ............ 148/148
ok test-node-debug.js ............. 20/20
ok test-oauth.js .................. 41/41
ok test-onelineproxy.js ............. 3/3
ok test-option-reuse.js ........... 10/10
ok test-params.js ................. 12/12
ok test-piped-redirect.js ........... 2/2
ok test-pipes.js .................. 35/35
ok test-pool.js ................... 16/16
ok test-promise.js .................. 3/3
ok test-proxy-connect.js ............ 5/5
ok test-proxy.js ................ 104/104
ok test-qs.js ..................... 24/24
ok test-redirect-auth.js .......... 18/18
ok test-redirect-complex.js ....... 40/40
ok test-redirect.js ............... 87/87
ok test-rfc3986.js ................ 44/44
ok test-timeout.js ................ 19/19
ok test-timing.js ................... 7/7
ok test-toJSON.js ................... 7/7
ok test-tunnel.js ................. 26/26
ok test-unix.js ..................... 6/6
total ......................... 1392/1392

ok

> request@2.67.1 test-browser /root/ravi/new_test/request
> node tests/browser/start.js

Started https server for karma tests on port 6767
18 12 2015 15:01:04.605:ERROR [launcher]: PhantomJS crashed.

PhantomJS 2.0.0 (Linux 0.0.0): Executed 0 of 0 DISCONNECTED (10.439 secs / 0 secs)
/root/ravi/new_test/request/tests/browser/start.js:33
      throw new Error('Karma exited with status code ' + c)
      ^

Error: Karma exited with status code 1
    at ChildProcess.<anonymous> (/root/ravi/new_test/request/tests/browser/start.js:33:13)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)

npm ERR! Linux 4.2.0-16-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "test-browser"
npm ERR! node v4.2.3
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE
npm ERR! request@2.67.1 test-browser: `node tests/browser/start.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the request@2.67.1 test-browser script 'node tests/browser/start.js'.
npm ERR! This is most likely a problem with the request package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node tests/browser/start.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls request
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/ravi/new_test/request/npm-debug.log
npm ERR! Test failed.  See above for more details.

Can any please help me in contributing to this issue

Regards,
Salamani

**Comment by simov** [comment]
Fixed in master https://github.com/request/request/commit/3e63b907d9f1cab9ac51ca673b6922c1dc24503c
