### ISSUE TITLE
lost cookies in request.post

### ISSUE THREAD

**Issue by Skye347** [request/request#1994]
i request a web page with cookies successfully,
then i request.post another one and find that there is no cookies in request packet.why was that?what have i missed?

**Comment by chenchaoyi** [comment]
There are different reasons, but rarely the request.js itself.

Did you set the `jar` option to true?

> Cookies are disabled by default (else, they would be used in subsequent requests). To enable cookies, set jar to true (either in defaults or options).
> ```
var request = request.defaults({jar: true})
request('http://www.google.com', function () {
  request('http://images.google.com')
})
```

**Comment by Skye347** [comment]
yeah..I think so.Here is my code:
```
var request=require('request').defaults({jar:true});
var j=request.jar();
var cookie_obj=request.cookie(cookie_string);
j.setCookie(...,function(err,cookie){
    var options={.....,jar:j,....};
    request.post(options,....);
})
```

**Comment by Skye347** [comment]
You're right.Thanks for your help.I got the domain wrong.
