### ISSUE TITLE
errorno contains no status code but a string

### ISSUE THREAD

**Issue by HansHammel** [request/request#1995]
```
ERROR { [Error: getaddrinfo ENOTFOUND www.google.d www.google.d:80]
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'www.google.d',
  host: 'www.google.d',
  port: 80 }
```

**Comment by SimonSchick** [comment]
Not a bug.

https://nodejs.org/dist/latest-v5.x/docs/api/errors.html#errors_error_code

**Comment by HansHammel** [comment]
so it is the other way round, error.code is very wrong. btw this isn't very dry.

**Comment by SimonSchick** [comment]
Probably backwards compatibility.

Either way, this is not a request problem.

**Comment by HansHammel** [comment]
Well, but it definitely is a bug. There are HTTP status codes that exist for good reasons and should be present on the error object in a request library...

**Comment by SimonSchick** [comment]
It's not a bug, there is not HTTP status code for a failed DNS lookup.
That's a different protocol.
