### ISSUE TITLE
Do not use util._extend

### ISSUE THREAD

**Issue by ChALkeR** [request/request#1997]
Used at:
 * [/lib/har.js#L121](https://github.com/request/request/blob/v2.67.1/lib/har.js#L121),
 * [/request.js#L126](https://github.com/request/request/blob/v2.67.1/request.js#L126).

See nodejs/node#4593.

**Comment by simov** [comment]
:+1: thanks for the heads up, we already depend on [extend](https://www.npmjs.com/package/extend) so it won't be a problem
