### ISSUE TITLE
Returns Not Found in body

### ISSUE THREAD

**Issue by webchaz** [request/request#2002]
I'm using request to get a url, very simple like this:

``` js
request({
  url: 'http://domain.com',
  method: "GET",
  jar: j
}, function(error, response, body) { 
  console.log(response);
  console.log(error);
  console.log(body);
});
```

I can access the url in the browser no problem, however the body using request returns 'Not Found'  It's an internal URL, otherwise I would post here.

Any ideas why this isn't able to get the full contents? Curl does the same thing (Not Found).   The page it's getting is run via nginx with node upstreams.

**Comment by SimonSchick** [comment]
Have you tried changing the user agent?

**Comment by partycoder** [comment]
`response.statusCode`
