### ISSUE TITLE
Content-Type header missing when passing BASIC Authentication

### ISSUE THREAD

**Issue by pedgarcia** [request/request#2010]
I am using request to interact with TestRail API. Since it uses basic authentication I am setting the headers as follows:

```
var mainHeaders = {
      'Authorization':'Basic ' + new Buffer(config.userName + ":" + config.APIKEY).toString("base64"),
      'Content-type': 'application/json'
  };
```

but the TestRail API rejects saying Content-Type header is missing. Checking the response from the server I can see the client request header was:

```
{
  "Authorization": "Basic <my authentication data>",
  "accept": "application/json",
  "referer": "http://xxxxx.testrail.net/index.php?/api/v2/get_cases/1&suite_id=1"
}
```

So I am assuming the Content-Type header is being **removed** somehow. 

Is there any reason the Content-Type header could be removed from the request header object? The header above is all I set.

It might not be request problem, but I am current lost. Any help is appreciated?

Thanks

Paulo

**Comment by pedgarcia** [comment]
Since the body is empty, I wasn't passing anything. After I added an dummy JSON object, the content-type was passed over.

Is it possible that the body content dictates what Content-Type is, overriding what I define ? Is that something request is doing ?

Thanks

**Comment by SimonSchick** [comment]
Tested on latest node&request:

```javascript
'use strict';

const request = require('request');

request({
	url: 'http://requestb.in/13pfrx01',
	headers: {
		'Authorization':'Basic ' + new Buffer('test:test').toString("base64"),
		'Content-Type': 'application/json'
	}
});
```

It works fine, the website receives the header correctly with no body specified.
Does the test rails server treat headers case sensitive?

Did you specify `json: true` in the request options?
