### ISSUE TITLE
Question: fire and forget

### ISSUE THREAD

**Issue by remy** [request/request#2011]
Is it possible to use request to run a `POST`, but not want to worry about the response?

In particular, I have a CLI that's posting a beacon/analytics to a server, so it's important the request has been sent, but waiting for the response is not required - and currently waiting is adding a minor latency to the CLI's exit time (which I'm looking to reduce).

Is this possible with request?

**Comment by timseverien** [comment]
The core http module allows you to `.abort()` a request, basically closing everything on your end. Most server-side configurations finish whatever program is creating the response, as killing that program is too risky as that program may be reading/writing files. However, you may want to test this thoroughly.

AFAIK, request doesn’t allow you to abort requests, but you can set a timeout to achieve something similar, but it’s not pretty.

A third options is to wait for a response, but skip reading it, which will save you *some* overhead. Request reads the response internally, so I’m not sure if you can skip that. With the core http module, you certainly can.

```js
const request = http.request(options, function(res) {
    request.abort();
});
```

**Comment by zeusdeux** [comment]
> and currently waiting is adding a minor latency to the CLI's exit time (which I'm looking to reduce).

By this, do you mean latency added by waiting for the `response` callback to fire?

If so, I don't think anything can be done about it as `http.request` [always fires the `response` event](https://github.com/nodejs/node/blob/master/lib/_http_client.js#L425) even when there are no listeners. So, all that event emitter code is run even though there are no callbacks registered for `response` and that latency currently cannot be gotten rid of from what I know of `http.request` in node.

**Comment by lourd** [comment]
This goes even lower level, it's inherent to the TCP protocol. UDP is designed as a fire and forget protocol.

**Comment by remy** [comment]
Thanks all - useful responses. I need to think about whether I want to switch to UDP or maybe launch my TCP request earlier to hide the latency in other work.

Cheers!
