### ISSUE TITLE
Callback of request full of data?

### ISSUE THREAD

**Issue by waynejuckts** [request/request#2013]
Hey there, 
is it for sure that the callback of the request(x,callback) has the whole content within the body? Or is ist possible that the callback comes several times and respresents partial parts of the whole page? Who can i than detect the end of the page? Or is it save request with whole content all the way? 

thanks a lot

**Comment by SimonSchick** [comment]
The callback will always be called with the full body.

**Comment by waynejuckts** [comment]
perfekt, thanks man!
