### ISSUE TITLE
Signature Version 4 Signing Process

### ISSUE THREAD

**Issue by mirkods** [request/request#2029]
Hi everyone,
I'm using your awesome module to invoke a lambda function on AWS but i saw that the `aws` option still support the aws-sign2 instead of the lambda service supports only aws-sign4 as describe in its docs 

http://docs.aws.amazon.com/lambda/latest/dg/API_Reference.html

How many chances there are to add the support to aws-sign4?

Mirko

**Comment by simov** [comment]
I'm not that familiar with AWS, but it shouldn't be that hard fixing it. Feel free to hack around I'll gladly review a PR about it. Here is the [aws-sign](https://github.com/request/aws-sign) module and here is the [related portion](https://github.com/request/request/blob/master/request.js#L1225-L1257) of that code in request. We don't have tests for that so probably a few tests would be needed before applying any new changes.

**Comment by mirkods** [comment]
Ok thanks for the quick response, I'm going to realize the PR. 
My PR will be merged if it works? 
I wanna add an additional parameter to specify which signature version must be used, is good for you?
for example:

```javascript
{
    aws: {
        key: 'YOUR_KEY',
        secret: 'YOUR_SECRET',
        sign_version: '4'   // default is 2
    }
}
```

**Comment by simov** [comment]
Yep, but we definitely need tests, if you can add some in `tests/test-aws.js` that would be great.

**Comment by mirkods** [comment]
@simov  pull request completed https://github.com/request/request/pull/2031

**Comment by simov** [comment]
Yep, I saw that, can you remove the changes from the changelog file, those are generated on release. Also I want to see only the new module package.json, I understand that this may have something to do with npm --save but still, it will be easier to review if you have only the relevant line changed.

After that I'm going to take a closer look at it. Thanks for taking the time to write tests for it, it was much needed :+1:

**Comment by mirkods** [comment]
@simov completed the changes. 
I don't know why on the changelog there is one diff again because the file is exactly the same of master

**Comment by simov** [comment]
Let's keep the conversation in the PR thread.

**Comment by mirkods** [comment]
Fixed

**Comment by lukas-gitl** [comment]
Wish that was in the docs... Would have saved me some time digging through the issues...
