### ISSUE TITLE
Can not download a specific file; but it works fine with wget, curl or firefox

### ISSUE THREAD

**Issue by Skywalker13** [request/request#2030]
works:
```bash
wget http://curl.haxx.se/download/curl-7.40.0.tar.gz
```

empty file and no error:
```js
 const fs = require ('fs');
 const request = require ('request');
 
 request
   .get('http://curl.haxx.se/download/curl-7.40.0.tar.gz')
   .on('error', function(err) {
     console.log(err)
   })
   .pipe(fs.createWriteStream('curl.tar.gz'));
```

Tested with request 2.67.0
node 4 and 5 on Debian Stretch amd64

Note that I've not this problem with many other URLs.

**Comment by Skywalker13** [comment]
Capture with wireshark
[curl.pcapng.zip](https://github.com/request/request/files/102318/curl.pcapng.zip)

**Comment by Skywalker13** [comment]
Output with request-debug (nothing interesting):
```
REQUEST { uri: 'http://curl.haxx.se/download/curl-7.40.0.tar.gz',
  method: 'GET',
  callback: undefined }
REQUEST make request http://curl.haxx.se/download/curl-7.40.0.tar.gz
{ request: 
   { debugId: 1,
     uri: 'http://curl.haxx.se/download/curl-7.40.0.tar.gz',
     method: 'GET',
     headers: { host: 'curl.haxx.se' } } }
```

**Comment by silverwind** [comment]
Looks like a node bug, I filed https://github.com/nodejs/node/issues/4844.

**Comment by simov** [comment]
@silverwind is this fixed/published in the latest release?

**Comment by silverwind** [comment]
No release with it yet, it's in the [6.0.0 nightly builds](https://nodejs.org/download/nightly/), but should make it into 5.5.1, see https://github.com/nodejs/node/pull/4337.

**Comment by silverwind** [comment]
FYI: The fix is slated for tomorrow's 5.5.1 release.

**Comment by Skywalker13** [comment]
Great news! thanks

**Comment by silverwind** [comment]
Ah, looks like it was backed out of 5.5.1 but will be in 5.6.0. You can use [nightly](https://nodejs.org/download/nightly/) until then!

**Comment by Skywalker13** [comment]
:-(

**Comment by SamLebarbare** [comment]
:-1: @silverwind pleasssssseeee

**Comment by silverwind** [comment]
Wasn't my decision unfortunately :cry:

**Comment by SamLebarbare** [comment]
@Skywalker13  is waiting for a :gift:
thx @silverwind you just win this :hammer: of power! +10ATK  !
We check the :moon: alignment before using 6.0.0 :night_with_stars: builds

**Comment by simov** [comment]
![damn](https://cloud.githubusercontent.com/assets/1694112/12916339/40139a44-cf3a-11e5-8a4d-63ef5846a82d.jpg)

**Comment by Skywalker13** [comment]
nodejs 5.6.0 is out (and not 5.5.1), but it doesn't work (of course).

**Comment by silverwind** [comment]
Yeah, I'm confused myself. Anyway, the fix will be in the next release, regardless of version number.

**Comment by SamLebarbare** [comment]
:clap:

**Comment by partycoder** [comment]
run:
```
NODE_DEBUG="*" node asdf.js
```

**Comment by mAiNiNfEcTiOn** [comment]
@Skywalker13 have you tried this:

```javascript
 const fs = require ('fs');
 const request = require ('request');

 request
   .get('http://curl.haxx.se/download/curl-7.40.0.tar.gz', { headers: { 'Connection': 'keep-alive' } })
   .on('error', function(err) {
     console.log(err)
   })
   .pipe(fs.createWriteStream('curl.tar.gz'));
```

?

**Comment by silverwind** [comment]
FYI, the fix will be in [5.7.0](https://github.com/nodejs/node/pull/5295), currently targeting next Tuesday.

**Comment by Skywalker13** [comment]
@mAiNiNfEcTiOn: hi, thx but the problem is only the h2c upgrade

**Comment by mAiNiNfEcTiOn** [comment]
@Skywalker13 ok, 'cause I got a similar issue, but the only way I solved it was adding the 'keep-alive' header otherwise it wouldn't trigger the callback either :)

**Comment by silverwind** [comment]
5.7.0 RC1 is out with this fix: https://nodejs.org/download/rc/v5.7.0-rc.1/

**Comment by silverwind** [comment]
And 5.7.0 is out, give it a go!

**Comment by Skywalker13** [comment]
It works fine, thanks!

**Comment by ajhsu** [comment]
Just want to make sure -- it's still broken in node v4.x, right?
If so, seems like I need to upgrade to node v5 to solve this problem.
