### ISSUE TITLE
.put results in an empty file

### ISSUE THREAD

**Issue by coldib** [request/request#2038]
Using the following code I end up with a created file on a webdav server with the size of 0Byte.
```javascript
	request
	.get('http://www.spielwiki.de/images/d/d9/Test.png')
	.pipe(request
	  .put('https://path.to.webdav.server/remote.php/webdav/mail2webdav/test.png')
	  .auth('user', 'pass', false))
```

Any ideas what I am doing wrong?

Thank you!

**Comment by coldib** [comment]
When I change the third parameter of auth to true everything is working as expected.

    .auth('user', 'pass', false))

**Comment by simov** [comment]
See the documentation about `sendImmediately`
