### ISSUE TITLE
Request path contains unescaped characters

### ISSUE THREAD

**Issue by dsaumyajit007** [request/request#2046]
I am trying to make a simple GET request to a website : https://www.crunchbase.com/location/belgrade/2a22cd01619e1ff39394303b255670cb?utm_source=crunchbase_tc_river&utm_medium=export&utm_campaign=dataset

I get an error such as this :
```
throw new TypeError('Request path contains unescaped characters.');
    ^

TypeError: Request path contains unescaped characters.
    at new ClientRequest (_http_client.js:53:11)
    at TunnelingAgent.exports.request (http.js:31:10)
    at TunnelingAgent.createSocket (/usr/lib/nodejs/tunnel-agent/index.js:117:25)
    at TunnelingAgent.createSecureSocket [as createSocket] (/usr/lib/nodejs/tunnel-agent/index.js:184:41)
    at TunnelingAgent.addRequest (/usr/lib/nodejs/tunnel-agent/index.js:80:8)
    at new ClientRequest (_http_client.js:137:16)
    at Object.exports.request (http.js:31:10)
    at Object.exports.request (https.js:181:15)
    at Request.start (/usr/lib/nodejs/request/index.js:607:30)
    at Request.end (/usr/lib/nodejs/request/index.js:1235:28)
```
Is there any fix to check if the url is compatible to be sent in the request function as a paramater ? I am using request@2.51.0 and node v5.5.0

**Comment by SimonSchick** [comment]
Works fine when I do it, using same versions as you:

```'use strict';

const request = require('request');

request(
	'https://www.crunchbase.com/location/belgrade/2a22cd01619e1ff39394303b255670cb?utm_source=crunchbase_tc_river&utm_medium=export&utm_campaign=dataset',
	(error, response, body) => {
		if (error) {
			return console.error(error);
		}
		return console.log(body.substr(0, 128) + '...');
	}
);
```

Can you post your code?

**Comment by SimonSchick** [comment]
I looked into the actual error.
This error can only occur when you snuck a whitespace into the url, I tried to to this but request always seems to escape those correctly.
You'll have to post a snippet, or try a newer version (yours is quite old) and see if the error persists.

**Comment by dsaumyajit007** [comment]
I work behind a proxy server. Your code does not seem to work behind a proxy. I am pasting my code below. Could you please tell me whether this is the correct way of sending a request while working behind a proxy server.

`'use strict';

const request = require('request');


var get_config = function(site_url){
	var config = {
		url : ((site_url)),
		proxy : 'http://<proxy host>:<proxy port>'
	};
	
	return config;
};
request(
	get_config('https://www.crunchbase.com/location/belgrade/2a22cd01619e1ff39394303b255670cb?utm_source=crunchbase_tc_river&utm_medium=export&utm_campaign=dataset'),
    (error, response, body) => {
        if (error) {
            return console.error(error);
        }
        return console.log(body.substr(0, 128) + '...');
    }
);`

Also an interesting observation is that when I am replacing "https" with "http", the request is working properly.

**Comment by SimonSchick** [comment]
Your proxy doesn't support https then?

**Comment by SimonSchick** [comment]
From what I can tell, internally there is some redirect happening, but the redirect seems to have a malformed/bad URL that contains whitespaces, that ticks off this error.

If it is a public proxy, could you please post the info?
If not, please add a breakpoint at "/usr/lib/nodejs/request/index.js:607" and inspect the passed url via any debugger.

**Comment by sudheesh001** [comment]
Hey @dsaumyajit007 

This looks fine and works perfectly with `google.com`, result after your code snippet.
```js
const request = require('request');


var get_config = function(site_url){
    var config = {
        url : ((site_url)),
        proxy : 'http://proxyurl:proxyport'
    };

    return config;
};
request(
    get_config('https://www.crunchbase.com/location/belgrade/2a22cd01619e1ff39394303b255670cb')
    , (function (error, response, body) {
    	console.log(response.statusCode);
    	console.error(error);
        return console.log(body.substr(0, 128) + '...');
    })
);
```
For `google.com`
```
200
null
<!doctype html><html itemscope="" itemtype="http://schema.org/WebPage" lang="en-IN"><head><meta content="text/html; charset=UTF-...
```

**Comment by SimonSchick** [comment]
@sudheesh001 Please note that you might be using a different proxy.
Lets wait for him.

**Comment by dsaumyajit007** [comment]
I have a very basic doubt : I am running Node js on Ubuntu 14.04 and on running
`node --version` 
I get v5.5.0 . Is this the most stable release because somewhere I saw that the releases are 0.x.x . Am i using the right version of Node?

**Comment by SimonSchick** [comment]
Yes, the 0.x releases are from before the iojs/nodejs merge.
v5.5.0 is stable.

I still believe it's just your proxy being weird.

**Comment by dsaumyajit007** [comment]
Ok. Any reason why the link works on repacing "https" with "http" ? It fixes this issue somehow

**Comment by SimonSchick** [comment]
https://github.com/request/request/issues/2046#issuecomment-177941023

**Comment by dsaumyajit007** [comment]
Ok Its magically working now. :+1: 
I just reinstalled nodejs and the request package. Thanks for all the help @sudheesh001 @SimonSchick

**Comment by SashaDesigN** [comment]
I reinstall request module but it fails after few days to this error agian

**Comment by ish3lan** [comment]
I had the same problem, wonder if people complaining here have another language activated in their keyboards? I do have arabic/english. this might takes us somewhere while investigating

**Comment by sgb-io** [comment]
I am experiencing this issue on windows (ethernet to home network) but not on macOS (wifi to same network). The `http` trick does not work for me.

**Comment by TsPuujee** [comment]
`axios.get(encodeURI(url)).then( data => {
})`

**Comment by yangquanxyz** [comment]
在kubernetes环境使用request发送get请求，url中携带中文参数时会发生这个错误，在其他环境则不会
