### ISSUE TITLE
SUPPORT: CHANGELOG.md, package.json, npmjs.com and tags appear out of sync with semver

### ISSUE THREAD

**Issue by Martii** [request/request#2053]
This is a little confusing when we do dependency updates as of late and I've just noticed this...

* [`c54be10`/package.json#L10](https://github.com/request/request/blob/c54be10eb11f4514ec29f97f83206520401ec5c1/package.json#L10) states version 2.68.1
* [npmjs.com](https://www.npmjs.com/package/request) states version 2.69.0 *(`$ npm --depth 0 outdated` as well)*
* [`c54be10`/CHANGELOG.md](https://github.com/request/request/blob/c54be10eb11f4514ec29f97f83206520401ec5c1/CHANGELOG.md) states version 2.68.0
* [GH Releases tag](https://github.com/request/request/releases) currently states [version 2.69.1](https://github.com/request/request/releases/tag/v2.69.1)

What changed in 2.69.0 on npmjs.com and why are all of these completely out of sync across the board?  I do read the CHANGELOG.md to better understand this project and its changes.

I don't [see a branch with 2.69.0](https://github.com/request/request/branches/all) either. 

Did I miss something with my deer in the headlights look with this? Is there a stable versus unstable release structure here? Apologies if it is obvious to others but I am definitely confused here.

TIA

Cc: @mikeal

**Comment by simov** [comment]
Fixed.

**Comment by Martii** [comment]
Thanks. :)
