### ISSUE TITLE
Can we add typescript support for this?

### ISSUE THREAD

**Issue by jvincilione** [request/request#2059]
I found a d.ts file over at Definitely Typed: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/request/request.d.ts

**Comment by simov** [comment]
Probably the best approach would be to use some wrapper around request. Adding anything TS related here, even tests, probably won't happen.

**Comment by emzero** [comment]
@simov There's no need to add any tests at all. It's just a `d.ts` file with the declaration (signatures and type data) of the functions.

**Comment by insyri** [comment]
You can solve this by just doing:
```bash
npm i @types/request
```
Unless I don't understand what the issue is.
