### ISSUE TITLE
toString failed - buffer size issue for big files (maxBufferSize)

### ISSUE THREAD

**Issue by theraaz** [request/request#2067]
I'm requesting a big file with 150K records but it throws 'toString failed' error. https://github.com/nodejs/node/issues/3175 says it's because of maxBufferSize. Request works well for 200 records but its an external api and the requirement is to get all records at once.[no pagination there :( ]
Is there any way to set buffersize for this request?

EDIT:

    request("http://www.site-containing-big-data/api",
			function (error, response, body) {
                console.log('got something to show');
				if(!error && response.statusCode == 200) {
					resolve(body);
				}else if(error){
					reject(error);
				}
			});

but nothing shows in console other than `toString failed` message

**Comment by aprilandjan** [comment]
Maybe you can set the response encoding to binary data, otherwise request will try to transform the response data to string and this might fail.
