### ISSUE TITLE
Connections not closing- keepAlive?

### ISSUE THREAD

**Issue by tejasmanohar** [request/request#2072]
It seems that my requests are holding open connections even after the callback fires. I've done some research on the Node `http` module, and it seems, by default, the setting is to `keepAlive` -> http://stackoverflow.com/questions/6658761/how-to-destroy-a-node-js-http-request-connection-nicely. How would I achieve

```
var request = http.get(options, 
        function(res) {
            console.log(res.statusCode);
          }
);
request.shouldKeepAlive = false
```

^ what one would do with this using node's native `http` module w/ `request`. Also, if you have any other tips here, as per why the connection doesn't seem to close, that'd be great, as it's been a tough one to debug.

PS: I've also tried passing in `headers: { connection: 'close' }` as opts to _request#post_.

**Comment by tejasmanohar** [comment]
nvm

**Comment by jshamley** [comment]
Sorry to revive an old issue but how did you figure this out @tejasmanohar? Thanks!

**Comment by tejasmanohar** [comment]
not sure, sorry :(

**Comment by tejasmanohar** [comment]
i hate when this happens haha. next time i should post in the comment before closing :P
