### ISSUE TITLE
Filename is automatically turn into basename for formData POST request  

### ISSUE THREAD

**Issue by ThibaultFriedrich** [request/request#2081]
I am trying to use request to upload a file a server. It works very well for simple upload but I would like to choose a specific filename in the http request. And `request` seems to cut the complete filename and send only the basename in the http request.

```javascript
var formData = {
        custom_file : {
            value: fs.createReadStream('data.txt'), 
            options: {filename:'/../../titi.txt', contentType:'text/txt'}
        }
    };
    var r = request.post({url:hostname+':'+port+'/upload', formData: formData}, function(err, httpResponse, body){
        if(err){
            console.log('erreur '+err);
            return;
        } else if(httpResponse.statusCode != 200){
            console.log('http response '+httpResponse.statusCode);
            return;
        }
        fs.readFile(pathname, function(err, buf2){
            if(err){
                console.log(err);
            } else if(md5(buf) != md5(buf2)){
                console.log('bug during upload');
            } else {
                console.log('file uploaded');
                fs.unlinkSync(pathname);
            }
        });
    });
```

And in wireshark : `form-data;name="custom_file";filename="titi.txt" `. 

Is it feature or is it a bug ?

**Comment by simov** [comment]
[form-data](https://github.com/form-data/form-data/blob/master/lib/form_data.js#L204)

**Comment by ThibaultFriedrich** [comment]
Ok I understand better but it doesn't help me because I need to specify a path. Is there a way to change this behavior ?

**Comment by simov** [comment]
You can build multipart body by yourself using the `multipart` option. Similar question [here](https://github.com/form-data/form-data/issues/149#issuecomment-152722510).

**Comment by ThibaultFriedrich** [comment]
Ok Thx a lot. I'm gonna do this. And good luck for the future. Your module is really very simple and powerful !

**Comment by simov** [comment]
:+1:

**Comment by peebles** [comment]
Well the problem with this is that sending multipart: generates a content-type of multipart/related for the message, and busboy (for one) does not support multipart/related.  Busboy wants a multipart/form-data.
