### ISSUE TITLE
Event equivalent of callback

### ISSUE THREAD

**Issue by tjconcept** [request/request#2082]
Given this code:

``` js
request('http://google.com', function( err, res ){
  if (err)
    return console.error(err);

  console.log(res);
});
```

What is the equivalent events, to get the same result? Say I wanted to pipe a file:

``` js
var r = request('http://google.com')
  .on('error', console.error)
  .on('response', console.log);

fs.createReadStream('some-file').pipe(r);
```

It doesn't seem like `response` is actually the same in the last example, and from the documentation I wouldn't guess either.

**Comment by simov** [comment]
You can still have a callback when uploading a file:

```js
var r = request('http://google.com', function( err, res ){
  if (err)
    return console.error(err);
  console.log(res);
})
fs.createReadStream('some-file').pipe(r)
```

If you want to stream the response then you should listen for the `finish` event of the write stream:

```js
var f = fs.createWriteStream()
f.on('finish', function () {})
r.pipe(f)
```

**Comment by tjconcept** [comment]
Still seems like something is different.. For instance, the `accept: application/json` header does not get appended with `json: true`.
