### ISSUE TITLE
Redirect LOOP with specific URLs

### ISSUE THREAD

**Issue by patricknn** [request/request#2087]
This is simple

I'm creating a crawler using the request module and for some urls that have strange characters like this one, I get a redirect loop

Here it is the example:

http://www.casasbahia.com.br/Moveis/EscritorioHomeOffice/EstacoesdeTrabalho/Mesa-para-Computador-2ultivisao-–-Branco-25231.html

If you open in your browser you get a 200 response after a single 301 redirect but if you try to get using the request module I get a infinite 301

This is not a cookie problem, this is a character encoding issue.

It looks like that the url to be redirected is not being decoded or encoded properly

**Comment by patricknn** [comment]
I found a solution:

The issue is really the strange character called EN DASH 

I'm using the http module and making the redirect by my self to control the URL to redirect.

So, first I decode the URL in utf-8 using the iconv module
then I encode the URL 
then I replace the code of the mandatory characters like / : ? & =

and then I make the request and everything runs perfectly

Here it is some code
`var sNewUrl = iconv.decode(res.headers['location'], 'utf-8');`
`sNewUrl = encodeURIComponent(sNewUrl);`
`sNewUrl = sNewUrl.replace(/\%2F/g,"/");`
`sNewUrl = sNewUrl.replace(/\%3A/g,":");`
`sNewUrl = sNewUrl.replace(/\%3F/g,"?");`
`sNewUrl = sNewUrl.replace(/\%3D/g,"=");`
`sNewUrl = sNewUrl.replace(/\%26/g,"&");`

Probably there is a better way to do it.

solving this issue in the request module will save me to do this terrible thing.

**Comment by alejandro-medina** [comment]
Same problem here with a URL which contains the **"EN DASH"** character

I'm trying to request the headers of the next image: 

https://plugintheme.net/wp-content/uploads/2018/09/AffiliateWP-–-Multi-Level-Affiliates-by-Click-Studio.jpg

But it ends up with response as undefined.

An example of my code: 
```javascript
let url = "https://plugintheme.net/wp-content/uploads/2018/09/AffiliateWP-–-Multi-Level-Affiliates-by-Click-Studio.jpg";
request.head(url, (err, response, body) => {

    let extension = res.headers['content-type']; // --> Here the error: "Cannot read property headers of undefined"

});
```
