### ISSUE TITLE
Does "request" have browser support?

### ISSUE THREAD

**Issue by dciccale** [request/request#2090]
I am sorry for asking this here, I couldn't find any information on this and have read other issues and still not clear.

Just want to know how compatible is `request` with the browser using browserify?

**Comment by marclr** [comment]
+1, I'm also interested on this

**Comment by simov** [comment]
Yep, it is compatible with browserify, though probably it's not the best option. Try using some lighter client instead. Currently request have lost of dependencies, so your js blob may end up being too big.

**Comment by SebastienDaniel** [comment]
Wow, I'm happy I found this little issue.

I just pulled in **request** and bundled it with browserify, the resulting bundle is whopping **1.8 MB** of javascript.
Even with brutal minification, it's still at **948 KB**, I'm not even sure this level of compression has left the code functional, it was just to get an idea.

So yeah, as @simov said, client-side, you might want to opt for something more light-weight.

**Comment by simov** [comment]
Yep, something lighter is in the works for request too, though not fully ready yet.

**Comment by dciccale** [comment]
thanks for the update.

@simov where is that lighter version being developed?

**Comment by simov** [comment]
I was just writing about the current issue that prevents it from being build with Browserify https://github.com/request/request/issues/1982

**Comment by sparcut** [comment]
@simov Where is support at, at the moment? As a suggestion, but be worth adding this topic to the README. I'm trying to choose a good http client for some browser code, I've always used request for node apps etc. though wasn't sure if request was usable/stable in the browser, for example [axios](https://github.com/axios/axios) clearly states its support for both node and browser.
