### ISSUE TITLE
Browserified output is too big

### ISSUE THREAD

**Issue by moon0326** [request/request#2094]
Hi,

By reading other issues, it looks like to me that this package can be used in a browser.

When I browserify this package, the output filesize is 1.8MB. Is this normal or am I doing something wrong?

How can I reduce the filesize?

**Comment by mikeal** [comment]
We've had plans to fix this in the next major release for quite some time.

If we break out more of the features into other modules we can easily exclude those modules from the browserify bundle.

**Comment by simov** [comment]
Yep, and my approach in @request/core turned out to be all wrong because browserify parses the files as string. So I'm thinking about even more dramatic architectural change, but we'll see :)

**Comment by moon0326** [comment]
Thank you @mikeal  and @simov. I'm glad to hear that it will be improved in the future. I've been using browser-request package, but the package has stopped developing for years now.

**Comment by IamFive** [comment]
Hello, is this feature implement now? it's still very big for version 2.75.0
