### ISSUE TITLE
Digest auth and POST fails

### ISSUE THREAD

**Issue by JanKoppe** [request/request#2098]
Hello,

I'm trying to do a POST request using Digest authentification. It seems to hang indefinitely though. I've included some basic test code which points to a publicly available test server. https://gist.github.com/JanKoppe/f7b3bd5a260a56104468

Trying to make the same request with `curl` works just fine: 

`curl --digest -u "opencast_system_account:CHANGE_ME" -H "X-Requested-Auth: Digest" http://octestallinone.virtuos.uos.de:8080/capture-admin/agents/test --verbose -d "state=idle"`

If i only do a GET Request, it behaves completely fine. I think this is some weird bug, or I could not find the bug in my code for the last 2 hours.

Edit:

Using `require-debug` produces the following log: 

```
% node opencast-interface.js
{ request: 
   { debugId: 1,
     uri: 'http://testallinone.usask.ca:8080/capture-admin/agents/test',
     method: 'POST',
     headers: 
      { 'X-Requested-Auth': 'Digest',
        host: 'testallinone.usask.ca:8080',
        'content-type': 'multipart/form-data; boundary=--------------------------145223707669380450993529',
        'content-length': 164 } } }

```

**Comment by simov** [comment]
Are you sure you want to post a multipart body? Try using the `form` option instead of `formData`.

**Comment by JanKoppe** [comment]
This seems to work, thanks. But, shouldn't it also work with a multipart body? Further on, I'll need to POST large files, also using digest auth. As far as I understand it, I would need to use multipart then, right?

**Comment by simov** [comment]
Multipart is required for binary files. It should work for multipart bodies if your server expects them.

**Comment by JanKoppe** [comment]
I'll try that, as soon as I get to it. seems to make sense. Thank you for your help.
