### ISSUE TITLE
how to make sub function for get and post in request module?

### ISSUE THREAD

**Issue by nikunjsobhashana** [request/request#2103]
var request = function(options,callback){
    this.get = function(options,callback){

```
}
this.post = function(options,form,callback){
}
```

}

i need a function like we have request(), request.get(), request.post() etc. so i can easily use then

i need something like the above code anyone help me ?
thanks in advance

**Comment by nikunjsobhashana** [comment]
if possible than give me here

**Comment by simov** [comment]
Hey @nikunjsobhashana I'm leaving all issues without answer open. It's just that you'll probably get your question answered quicker if you ask on StackOverflow using the proper tags. Request is very popular module so you'll probably receive a bunch of answers in no time.

**Comment by nikunjsobhashana** [comment]
okay no problem
