### ISSUE TITLE
Getting upload progress

### ISSUE THREAD

**Issue by Akshay-Thakare** [request/request#2105]
I am trying to get upload progress using a request object. Could anyone suggest how to go about doing the same for an image upload. 

I tried using request-progress module but it gets called only twice once at the start and once at the end of upload below is the code for the same.

```
var progress = require('request-progress');
progress(request_object).on('progress', function(state){
console.log('progress', state);
});
```

NOTE : I am working with `google-api-nodejs-client` so I only have a request object to get upload progress from.

**Comment by Akshay-Thakare** [comment]
Already tried StackOverflow. No solution yet.

**Comment by jimtang9527** [comment]
request-progress for file download progress. not upload progress.
my way
`
var fileStream = fs.createReadStream(xxx)
var formData = { 
        'file': {
            value: fileStream
        }
    }
request.post({
        url: xxx,
        formData: formData
    }, function(err, httpResponse, body) {
     
})
fileStream.on('data', function(data) {
   var blockLength = data.length
   //TODO progress is here
})
`

**Comment by Akshay-Thakare** [comment]
@jimtang9527 I resolved the issue a few weeks back. My answer is on StackOverflow. Just missed out closing this one, Thanks for you answer :)

**Comment by TheLox95** [comment]
@Akshay-Thakare Hi. Where is the link to your answer in StackOverflow? I'm doing the same thing, but I could not figure out

**Comment by bcjordan** [comment]
@TheLox95 @alandoyle95 possibly this: https://stackoverflow.com/a/18344484/136134

**Comment by bcjordan** [comment]
Ah, just saw you'd reacted to the question asking where the StackOverflow answer was, so figured you were looking for it at the time as well :). Apologies for the bother!

**Comment by alandoyle95** [comment]
ohhh so i did lol
