### ISSUE TITLE
What's the proper way to kill a pipe()?

### ISSUE THREAD

**Issue by mykinator** [request/request#2106]
I have server code which serves as a download proxy:

`request(streamingDownload)`
`.on('error', function(error) {`
`// do something
`})
`.pipe(res);`

Occasionally, the server receives an error event after having started to pipe the response to the client; therefore, I'd like to terminate the connection to the client to let the client know the response has gone bad -- it's too late to res.send a status code at this point since piping has already begun.

What's the best practice for doing that using this module?

**Comment by fr-kshibata** [comment]
right now im doing something like this ,
```
	request
		.get(url, function(err,response,body){
			if(err) callback(err,null);
			else if(!err && body){
				callback(null,'success: '+response);
			}
		})
		.auth(user,pass,true)
		.on('error',function(err){
			callback(err,null);
		})
		.pipe(stream);

```

It looks ugly I know, but I raised an issue for this already, #2153

**Comment by r4j4h** [comment]
I was trying to do something similar and found the nonstandard `requestStreamInstance.abort()` to work for this purpose.
