### ISSUE TITLE
way to modify response data while pipe?

### ISSUE THREAD

**Issue by wdfsinap** [request/request#2107]
I want to know how to change the stream value while pipe?

**Comment by newbreedofgeek** [comment]
AFAIK pipe will stream data back, but you can tap into the stream by listening to the 'data' event.

e.g. The below code pipes the original request to a another url and then you can tap into the response by listening to the data event.
```
req.pipe(request('new_url')).on('data', function(data) {
   console.log(data.toString());
});
```

You could them modify and pipe back if you want, read this (it may help) - it uses a handler to intercept responses.

[https://community.apigee.com/questions/13411/how-can-we-store-log-or-modify-response-when-strea.html](https://community.apigee.com/questions/13411/how-can-we-store-log-or-modify-response-when-strea.html)
