### ISSUE TITLE
Make some of the dependencies optional

### ISSUE THREAD

**Issue by baderbuddy** [request/request#2108]
Could we make a change to the dependencies, any component that's not always used make it an optional dependency, like the oauth1 dependency or Hawk, etc. These are all dependencies that I would think would only be needed if reaching the appropriate IDs, making them optional would allow consuming components to not include them, making applications smaller, as well as avoid the need for them, which would increase the ability to use Request inside organizations that are restricting certain npm components.

**Comment by simov** [comment]
Take a look at https://github.com/request/core  it's a work in progress though https://github.com/request/request/issues/1982
