### ISSUE TITLE
PHP will not receive correctly when set option "json" to "true"

### ISSUE THREAD

**Issue by wilsoncook** [request/request#2111]
see this request:

``` js
request({
    url:'http://localhost/test.php', 
    method:'post',
    form:{UserId:60,title:'test1',messsage:'test1'},
    json:true, 
    proxy: 'http://127.0.0.1:8888'
}, function(err, res, body){console.log(body);});
```

the raw header & content will be:
![image](https://cloud.githubusercontent.com/assets/1631659/13516339/3af36d60-e1f4-11e5-812b-b126fe73aa46.png)
so the body content was wrapped by double quotes, and then the php side will receive like this:
![image](https://cloud.githubusercontent.com/assets/1631659/13516367/7d641aa0-e1f4-11e5-9dd3-a803d9b4a314.png)
anyway, the content-type will not set as "application/json" like the `README` said.
i wondered why adding double quotes, thanks!

**Comment by IvanGaravito** [comment]
Maybe this can help you: http://blog.modulus.io/node.js-tutorial-how-to-use-request-module

**Comment by avihaym** [comment]
Sending over HTTP, everything is a string. It's up to your server to decide that "1" should be 1.

**Comment by mikeal** [comment]
You're using two features at the same time that conflict with each other :)

The `form` option is for sending form encoded bodies. The `json` option if for json bodies **AND** for setting headers to receive JSON content types.

you should do this instead:

```javascript
request.post({json: {UserId:60,title:'test1',messsage:'test1'}}, (err, resp, body) => console.log(body))
```

**Comment by lbossle** [comment]
@wilsoncook did @mikeal's answer solve your problem? If it did, I believe this issue should be closed.
