### ISSUE TITLE
Post JSON & followAllRedirects ends with GET method

### ISSUE THREAD

**Issue by jbdemonte** [request/request#2118]
I'm trying to consume a staging web service using https protocol.
The POST receive a 301 redirect, which I tried to make request following silently using (followAllRedirects).
curl hasn't any problem with that
      
      * Connected to api.staging.eu.xxx.com (x.x.x.x) port 443 (#0)
      * TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
      * Server certificate: *.staging.eu.xxx.com
      * Server certificate: RapidSSL SHA256 CA - G3
      * Server certificate: GeoTrust Global CA
      > POST /api/v1/employees/ HTTP/1.1
      > Host: api.staging.eu.xxx.com
      > User-Agent: curl/7.43.0
      > Content-type: application/json
      > Accept: application/json
      > X-API-KEY: xxxxxxxxx
      > Content-Length: 502

request fails there, because of redirect.js

To debug it and get it working to be sure, I just removed the following lines:

      if (self.followAllRedirects && request.method !== 'HEAD'
        && response.statusCode !== 401 && response.statusCode !== 307) {
        // request.method = 'GET'                                     // <= removed to debug
      }
      // request.method = 'GET' // Force all redirects to use GET || commented out fixes #215
      delete request.src
      delete request.req
      delete request._started
      if (response.statusCode !== 401 && response.statusCode !== 307) {
        // Remove parameters from the previous response, unless this is the second request
        // for a server that requires digest authentication.
        // delete request.body                                        // <= removed to debug
        delete request._form
        if (request.headers) {
          // request.removeHeader('host')                             // <= removed to debug
          // request.removeHeader('content-type')                     // <= removed to debug
          // request.removeHeader('content-length')                   // <= removed to debug

I saw a few issues which seems refer to the redirect (#556, #215...), but I'm absolutely not an expert of SSL &  http redirection, so, not sure about what should be done or not

**Comment by jbdemonte** [comment]
Update: My fault about the comment on curl, it won't follow it by default
And to complete the description, I was forgetting a ending / in the uri, which make the server response to be a 301.

**Comment by gabmontes** [comment]
I saw a similar issue using version 2.69.0. After making a POST request and getting back a 304, the next request is a GET.

To get the method used, just added a debug line to `Request.prototype.start`:

```javascript
  debug('make request', self.uri.href)
  debug('with method', self.method) // line added
```

Below is a (sanitized) log of such a request:

```
REQUEST { uri:
   Url {
     protocol: 'http:',
     slashes: true,
     auth: null,
     host: 'my-host.com',
     port: '',
     hostname: 'my-host.com',
     hash: null,
     search: null,
     query: null,
     pathname: '/path',
     path: '/path',
     href: 'http://my-host.com/path' },
  method: 'POST',
  headers:
   { 'User-Agent': 'node-soap/0.12.6',
     Accept: 'text/html,application/xhtml+xml,application/xml,text/xml;q=0.9,*/*;q=0.8',
     'Accept-Encoding': 'none',
     'Accept-Charset': 'utf-8',
     Connection: 'close',
     Host: 'my-host.com',
     'Content-Length': 608,
     'Content-Type': 'text/xml; charset=utf-8',
     SOAPAction: '""' },
  followAllRedirects: true,
  callback: [Function] }
REQUEST make request http://my-host.com/path
REQUEST with method POST
REQUEST onRequestResponse http://my-host.com/path 302 { location: 'https://my-host.com/path',
  server: 'BigIP',
  connection: 'close',
  'content-length': '0' }
REQUEST redirect https://my-host.com/path
REQUEST redirect to https://my-host.com/path
REQUEST {}
REQUEST response end https://my-host.com/path 302 { location: 'https://my-host.com/path',
  server: 'BigIP',
  connection: 'close',
  'content-length': '0' }
REQUEST make request https://my-host.com/path
REQUEST with method GET
REQUEST onRequestResponse https://my-host.com/path 200 { server: 'Apache-Coyote/1.1',
  'content-type': 'text/html;charset=utf-8',
  'transfer-encoding': 'chunked',
  date: 'Mon, 21 Mar 2016 17:21:30 GMT',
  connection: 'close',
  'set-cookie': [ 'MYCOOKIE=2720256522.20480.0000; path=/' ] }
REQUEST reading response's body
REQUEST finish init function https://my-host.com/path
REQUEST response end https://my-host.com/path 200 { server: 'Apache-Coyote/1.1',
  'content-type': 'text/html;charset=utf-8',
  'transfer-encoding': 'chunked',
  date: 'Mon, 21 Mar 2016 17:21:30 GMT',
  connection: 'close',
  'set-cookie': [ 'MYCOOKIE=2720256522.20480.0000; path=/' ] }
REQUEST end event https://my-host.com/path
REQUEST has body https://my-host.com/path 42912
REQUEST emitting complete https://my-host.com/path
```

Can someone advise if this is the expected behavior? I guess not but...

**Comment by itheof** [comment]
Same here. I think we should have a way to tell request to keep the original method.
Any client-side workaround would be really appreciated meanwhile.

**Comment by kirrg001** [comment]
I am experiencing the same issue. It always redirects to `GET` instead of the original HTTP method.
