### ISSUE TITLE
Some base error occurred, does request package only used in server?

### ISSUE THREAD

**Issue by WenXuanYuan** [request/request#2121]
ERROR in ./~/forever-agent/index.js
Module not found: Error: Cannot resolve module 'net' in /Users/wen/Documents/SDE/Olege/olege-web/node_modules/forever-agent
 @ ./~/forever-agent/index.js 6:10-24

ERROR in ./~/forever-agent/index.js
Module not found: Error: Cannot resolve module 'tls' in /Users/wen/Documents/SDE/Olege/olege-web/node_modules/forever-agent
 @ ./~/forever-agent/index.js 7:10-24

ERROR in ./~/tunnel-agent/index.js
Module not found: Error: Cannot resolve module 'net' in /Users/wen/Documents/SDE/Olege/olege-web/node_modules/tunnel-agent
 @ ./~/tunnel-agent/index.js 3:10-24

ERROR in ./~/tunnel-agent/index.js
Module not found: Error: Cannot resolve module 'tls' in /Users/wen/Documents/SDE/Olege/olege-web/node_modules/tunnel-agent
 @ ./~/tunnel-agent/index.js 4:10-24

ERROR in ./~/tough-cookie/lib/cookie.js
Module not found: Error: Cannot resolve module 'net' in /Users/wen/Documents/SDE/Olege/olege-web/node_modules/tough-cookie/lib
 @ ./~/tough-cookie/lib/cookie.js 32:10-24

ERROR in ./~/request/lib/har.js
Module not found: Error: Cannot resolve module 'fs' in /Users/wen/Documents/SDE/Olege/olege-web/node_modules/request/lib
 @ ./~/request/lib/har.js 3:9-22

I am a fresher , I need your help.

**Comment by MykleNero** [comment]
Did you ever find a solution for this?

**Comment by WenXuanYuan** [comment]
@MykleNero I used another package in front-end.
