### ISSUE TITLE
Error: define cannot be used indirect

### ISSUE THREAD

**Issue by leaky** [request/request#2127]
I'm receiving this error in the latest version (2.69.0 on npmjs.com). This bug has been highlighted previously in https://github.com/request/request/issues/1920 but looks like the issue has never officially been patched.

A simple `import request from 'request'` is all takes to trigger the error in my application.

Downgrading to v2.65.0 has fixed the issue but this certainly is not a 'fix'.

**Comment by chippy99** [comment]
I have exactly the same problem
