### ISSUE TITLE
Query strings auto-encoding and OData APIs

### ISSUE THREAD

**Issue by jviotti** [request/request#2129]
Let's say I have an OData API that responds to the following query:

```
https://app.io/Products?$filter=Name ne 'Milk'
```

I compose the request like this:

``` js
const request = require('request');

request({
  method: 'GET',
  url: 'https://app.io/Products',
  qs: {
    $filter: 'Name ne \'Milk\''
  }
}, function(error, response) {
  if (error) {
    throw error;
  }
});
```

`request` will send a GET request to `https://app.io/Products?%24filter=Name%20ne%20%27Milk%27` (you can check `response.request.uri.path`).

Notice the dollar sign from `$filter` is escaped to `%24`, causing my request to not match the intended route and fail.

This behaviour comes from `querystring`:

``` sh
$ node
> var querystring = require('querystring');
> querystring.stringify({ $filter: 'Name ne \'Milk\'' });
'%24filter=Name%20ne%20\'Milk\''
```

I understand this the default behaviour from a NodeJS built-in library, but it causes a lot of pain when using OData query strings. 

Have you encountered such behaviour before? Is there a way to disable the automatic encoding from query strings?

What I'm currently doing is passing the query string manually to `url` instead of using the handy `qs` object, although its far from ideal, and I have to scan the current url for existing query strings to append correctly.

**Comment by DavidBenko** [comment]
I have a similar issue with OData urls that look like:
```
https://app.io/Products('12345')
````

which turns into:

```
https://app.io/Products%28%2712345%27%29
```

**Comment by simov** [comment]
It seems that you have to build the querystring somehow and append it to the `url` option instead of using the `qs` option:

```js
url: 'http://outofindex.com?$filter=Name ne \'Milk\''
```

Same for POST request, use `body` instead of `form`:

```js
body: '$filter=Name ne \'Milk\''
```

Let me know if that works for you.

**Comment by taygrave** [comment]
Note, I got around this by using `decodeURIComponent` like so: 

```
  let odata = querystring.stringify({
    '$select': 'name',
    '$filter': '( archived eq false )',
    '$orderby': 'name asc'
  })

  odata = decodeURIComponent(odata)
```

the first time odata is: 
`%24select=name&%24filter=(%20archived%20eq%20false%20)&%24orderby=name%20asc`

and after the decoding: 
`$select=name&$filter=( archived eq false )&$orderby=name asc`
