### ISSUE TITLE
How to create webhook for github repo using php 

### ISSUE THREAD

**Issue by varunsridharan** [request/request#2139]
Hi,

I am trying to create webhook for github using github api. i am using php as my workcode

i am using the below libs
1. CodeIgniter
2. https://github.com/thephpleague/oauth2-client   [Github OAuth]

This is my post parameters 

``` php
$CreateHook = array(
            "name" => "web",
            "active" => true,
            "events" => array("push"),
            "config" => array(
                "url" => "http://example.com/webhook",
                "content_type" => "json"
            )
        );
```

**Comment by peeyushsrj** [comment]
Not relevant. Should be closed!?
