### ISSUE TITLE
streaming multiple responses from request to http.ServerResponse 

### ISSUE THREAD

**Issue by msreekm** [request/request#2143]
Is it possible to stream responses from multiple requests to http server response?

something like-
router.get('/streamingApi',(req,res)=> {
  request('http://localhost:3000/first').pipe(res);
  request('http://localhost:3000/second').pipe(res);
  request('http://localhost:3000/third').pipe(res);
}

I want to return the stream to browser as it arrives, but when I run the above, only the first one pipes and then the connection closes. any suggestions?

**Comment by WillAvudim** [comment]
Hi @msreekm, have you managed to find the resolution to response streaming? Or going raw http(s) is the only viable option?
