### ISSUE TITLE
Memory Leaks With Large Request

### ISSUE THREAD

**Issue by ghprod** [request/request#2145]
Hi, 

I'm running large request with queue manager (bull) more than 8k URL, and after few minute my memory gets busted, from node inspector I know that `network request` take the big portion

![image](https://cloud.githubusercontent.com/assets/1922652/14066164/01a22f70-f46d-11e5-8607-5f54746cfce3.png)

So do you have any idea to prevent this? I mean, I want that after request completed, then it's disappeared from memory

btw I'm using request promise and this is my piece of my code

``` js
var adsListingQueue = Queue('adsListingQueue', config.redis.port, config.redis.host)

adsListingQueue.process(config.concurrency.getAdsListing, function (job, done) {
    var url = urijs(program.url)

    var page = job.data.page

    if (page > 1) {
        url.addQuery({
            page: page
        })
    }

    rp({
        uri: url.toString(),
        headers : {
            'User-Agent': randomUserAgent()
        },
        transform: function (body) {
            return cheerio.load(body)
        }
    })
        .then(function ($) {
            // just simple parsing with cheerio

            done()
        })
        .catch(function (err) {
            done(err)
        })
})

_.each(_.range(1, 500), function (item) {
    adsListingQueue.add({page: item})
})
```

Thanks

**Comment by seren** [comment]
Perhaps related to https://github.com/request/request/pull/2051 ?
