### ISSUE TITLE
Security issue with hawk

### ISSUE THREAD

**Issue by LeZuse** [request/request#2148]
Please see https://nodesecurity.io/advisories/77

Your `master` already has `hawk: ~3.1.3` since https://github.com/request/request/commit/ebb2c3b63113d9e7225aacf6a636242c44eae385

I suggest locking version to `>=3.1.3 < 4.0.0 || >=4.1.1` and publishing new patch version on npm

**Comment by simov** [comment]
It's already that way, just not published yet.

**Comment by LeZuse** [comment]
@simov Is there any date I can expect the new version to be published? Thanks

**Comment by simov** [comment]
I'm going to publish a new version soon.

Why is the `~3.1.3` range not working for your? It covers `>=3.1.3 < 4.0.0`.

We're not going to move to `>4.x` any time soon. Not to mention that the vulnerability doesn't affect request anyway. But even if that happens at some point it will depend on the `latest` version of hawk.
