### ISSUE TITLE
ability to side-step helper.safeStringify() for form data

### ISSUE THREAD

**Issue by ccjon** [request/request#2151]
In every case I have tried, I cannot seem to bypass the encoding of the body of a PUT. Even with the content-type header set as www-url-encoded, AFAIK there isn't a requirement that the body be encoded in any way unless it exceeds certain size limits, nor that services have to decode the body of a PUT. It can just be raw. Something akin to 

cUrl https://rawdataservice.biz -d @./filename -X PUT 

It looks to me like all forms are run thru safeStringify in the helper and I can't find a way to just send raw form data.

**Comment by simov** [comment]
Use the `body` option instead, or try using `qsParseOptions` and/or `qsStringifyOptions`, see [here](https://github.com/request/request#requestoptions-callback).

**Comment by ccjon** [comment]
Thanks for the reply. I've tried the body option since that seems most apropo: this is the body I am setting not a url query string.... but am still confused by the behaviour: as I console.log("s---->"+body), I get 
s---->login[sis_user_id]=somevalue
... but in the request-debug output I see
body: '\'login[sis_user_id]=somevalue\'' 
... the outside quotes I take as formatted output decoration from request-debug
but from whence the internal escaped single quotes?  (no need to reply in olde English) 

Thank again
