### ISSUE TITLE
Gets stuck without any error when there is a content length mismatch

### ISSUE THREAD

**Issue by amanaryan** [request/request#2156]
When we specify the content length in the header and the content length of the POST form data is different it doesn't throw an error , it just gets stuck . The HTTP call is made when the program is terminated using CTRL+C.

**Comment by EddieOne** [comment]
Set a timeout and it will through an error.

**Comment by amanaryan** [comment]
It only shows Timeout error ,I believe The error should be descriptive like content length mismatch.

**Comment by EddieOne** [comment]
Maybe a special content length mismatch error. However, without a timeout this is the expected behavior. The content length tells the request when to stop waiting for data.
