### ISSUE TITLE
Cookies

### ISSUE THREAD

**Issue by ghost** [request/request#2157]
I don't understand why so much text, functions and trouble for cookies and "jars" in the README. Can't you simply set 'Cookie' : '...' in request headers?

**Comment by agreco** [comment]
I have to agree. Is there a way to specify 'cookie' in the request headers?

**Comment by duzun** [comment]
I see no issue with this!

```js
request({
    url: 'http://example.com/',
    headers: {
       Cookie: "PHPSESSID=d90a76cl82inv4l1ekbdgiql10"
    }
})
```
