### ISSUE TITLE
Send OPTIONS request?

### ISSUE THREAD

**Issue by chovy** [request/request#2170]
I have to mimic an Ajax call which sends an OPTIONS request before it does a GET request.

Is there anyway to force `request()` do to this? When I tried making two requests manually it doesn't work as expect -- I'm assuming because its taking too long, but not sure.

I was hoping for some flag like `do_options_request: true` I can set when I do a GET request.

**Comment by simov** [comment]
Wrap request with your own function and check if it's a GET request, then do OPTIONS before GET.

**Comment by chovy** [comment]
that's what i'm doing. `doRequest('OPTIONS').then(doRequest.bind(this, 'GET'));`

But the problem is the results are not as expected.

**Comment by simov** [comment]
That's a bit vague actually. How can I reproduce it? Is it a problem with your code or with request?

**Comment by chovy** [comment]
I'm not sure to be honest. It seems to be too slow to work. The options request is taking too long.
