### ISSUE TITLE
Request does not support 'deflate' encoding.

### ISSUE THREAD

**Issue by czardoz** [request/request#2171]
This request results in the raw response being dumped to the console:
```javascript
var req = require('request');

req({
    url: 'http://httpbin.org/deflate',
    method: 'GET',
    headers: {},
    followAllRedirects: false,
    followRedirect: true,
    jar: true,
    timeout: 15000,
    gzip: true,
    rejectUnauthorized: false,
    strictSSL: true
}, function (err, res, body) {
    if (err) {
        console.error(err.stack || err);
    }
    console.log(body);
});
```

The expected behavior is that `body` contains the decoded response.

**Comment by czardoz** [comment]
Changing the gzip handling to 
```javascript
      if (contentEncoding === 'gzip') {
        responseContent = zlib.createGunzip()
        response.pipe(responseContent)
      } else if (contentEncoding === 'deflate') {
        responseContent = zlib.createInflate()
        response.pipe(responseContent)
      }
```
in [request.js](https://github.com/request/request/blob/5a8ddc8102a0897ca1aacf222576258ad87105c1/request.js#L928) ensures that deflate responses work.

I'm willing to submit a PR for this change, but are there any other considerations here?

**Comment by simov** [comment]
That's weird, I though we support it already. I'm wondering if the `gzip` option would be appropriate in this case though.

**Comment by czardoz** [comment]
True, `gzip` is probably not the right option. But I don't think it is nice to add a new option for every new encoding that comes up either.

One solution is to use the `gzip` option, since `deflate` and `gzip` [are related](https://tools.ietf.org/html/rfc1951). Not sure if this is backwards compatible though.

Another option is to include `deflate` as a new option, this will lead to a bit of code duplication, and too many options, I think. 

I'm okay with either of the above options though (or any that I might not have thought of) :)

**Comment by simov** [comment]
Yep let's keep it under `gzip` for now. I have a better approach for handling the options [here](https://github.com/request/core/blob/master/lib/options/gzip.js).

Don't forget to add a test in the `test-gzip` file.

**Comment by czardoz** [comment]
Done!
