### ISSUE TITLE
Authentication with Github Personal access tokens

### ISSUE THREAD

**Issue by TDub2881** [request/request#2185]
Hi I am trying to access the Github API with a personal access token rather than username/password (I don't want my login in the script).

Here is what I tried so far:

``` js
request({
    url: githubUrl,
    method: 'POST',
    json:true,
    rejectUnauthorized: false,
    qs:{access_token:'token'}, // This is the attempt of just adding the token as a url parameter, which works in Postman but not here
    body: {
  "message": "commit message",
  "committer": {
    "name": "user",
    "email": "user@company.com"
  },
  "content": getBase64(body), 
  "sha": getSha(content), 
},
}, function(error, response, body){
    if(error) {
        console.log(error);
    } else {
        console.log(response.statusCode, body);
    }
}).auth(null, null, true, 'token'); // attempt at using the bearerToken
```

The result is always a 404 (not found), which is the same thing that github returns if I try it via Postman without the Token. The file is there and it is accessible via the API (verified using Postman).

Am I using the correct way to pass along the token?

**Comment by simov** [comment]
```js
request({auth: {bearer: '[the-token]'}})
```
remove `.auth(null, null, true, 'token')`

**Comment by TDub2881** [comment]
Thanks simov, unfortunately it still produces the same result. If i enter an incorrect token however, it will tell me 'Bad Credentials', which makes me think that the authentication is being submitted to github correctly, but Github for some reason still doesn't let me access the object. On the other hand it works fine in Postman, so if github accepts the token coming from Postman, why not from request?

**Comment by vogdb** [comment]
Hi! Sorry to bump the old thread. This is what worked for me:
```js
request({auth: {
  user: 'your-token-goes-here',
  pass: 'x-oauth-basic',
  sendImmediately: true
}})
```
