### ISSUE TITLE
multiple proxy

### ISSUE THREAD

**Issue by komarevtsevdn** [request/request#2189]
hi, i am using request and set proxy within request.default
for each query i create:
var proxy = request.defaults({'proxy': value }) 
because i need change proxy after each query.
but sometime i see { [Error: tunneling socket could not be established, cause=connect ETIMEDOUT xxx] code: 'ECONNRESET' }  xxx - ip proxy
where is a problem?

**Comment by czardoz** [comment]
Your proxy is closing the connection. This can be due to a lot of reasons, such as opening too many connections at the same time, etc. It really depends on your network configuration.

**Comment by komarevtsevdn** [comment]
also i think, that problem because have too many opening proxy, but how i can disconnect proxy after query?
