### ISSUE TITLE
Release 2.72.1 is not available from npmjs

### ISSUE THREAD

**Issue by shpros** [request/request#2190]
According to [releases](https://github.com/request/request/releases) and [package.json](https://github.com/request/request/blob/master/package.json#L10), there is supposed to be a 2.72.1 release, but I am unable to retrieve it from the npmjs registry.

My package.json contains:
```
  "dependencies": {
    ...
    "request": "2.72.1"
  },
```

Here is the error I am getting during `npm install`:
```
npm ERR! No compatible version found: request@2.72.1
npm ERR! Valid install targets:
npm ERR! 2.72.0, 2.71.0, 2.70.0, 2.69.0, ..., 0.9.5, 0.9.1, 0.9.0, 0.8.3
```

Also, https://www.npmjs.com/package/request says:
> **2.72.0** is the latest of 109 releases

I have cleaned my npm cache.

**Comment by sdnetwork** [comment]
yes the last is 2.67.0, wait ;)

**Comment by simov** [comment]
We are currently releasing only minor versions 2.**xx**.0

**Comment by shpros** [comment]
OK, thanks! I will use 2.72.0 then.
