### ISSUE TITLE
Is there a way to re-issue same request again

### ISSUE THREAD

**Issue by parky128** [request/request#2192]
I am using Express to proxy requests to a separate API server which is protected by OAuth 2 access tokens. When a token expires, the server will return a 401 which I am now handling in my router middleware to then go and refresh the access token associated with the clients session (I am using `express-session`).

Here is my code:

**router.js**

`app.use('/api', require('./routes.js'));`

**routes.js**

``` javascript
    var express = require('express'),
      router = express.Router(),
      routesController = require('./routes.controller.js');

    router.route('/*')
      .get(routesController.fetch);
```

**routes.controller.js**

``` javascript
module.exports.fetch = function(req, res, next) {
      var options = helpers.buildAPIRequestOptions(req);
      request(options, function(err, response, body){
        if(response.statusCode === 401) {
          authController.refreshToken(req, res, next);
        } else {
          res.status(response.statusCode).send(body);
        }
      });
    };

```

**authController**

``` javascript
module.exports.refreshToken = function(req, res, next) {
      var formData = {
          grant_type: 'refresh_token',
          refresh_token: req.session.refreshToken,
          scope: 'PRODUCTION'
        },
        headers = {
          'Authorization' : 'Basic ' + consts.CLIENT_KEY_SECRET_BASE64_DEV
        };
      request.post({url:consts.ACCESS_TOKEN_REQUEST_URL_DEV, form:formData, headers: headers, rejectUnauthorized: false}, function(err, response, body){
        var responseBody = JSON.parse(body);
        if (response.statusCode === 200) {

          req.session.accessToken = responseBody.access_token;
          req.session.refreshToken = responseBody.refresh_token;
          next();
          //How to recall the same request issued from fetch controller function after this point?
        } else {
          console.log('SOMETHING ELSE HAPPENED!');
        }
      });
    };
```

After updating the token, I would like to re-issue the original API request that I am triggering using the `request` module in my fetch controller.

I'm a bit stumped how I actually go about doing this, is there an elegant way to achieve this?

**Comment by simov** [comment]
You have to change your functions so that you call the original request after refreshing the token, how exactly is up to you.

**Comment by parky128** [comment]
Sure ok, I understand that something needs to change, I just can't picture in my mind how it would work - I have a question on [SO](http://stackoverflow.com/questions/36883413/calling-same-request-again-in-node-express) to try and get some further advice from the community

**Comment by simov** [comment]
You have all the needed parts in your code working. Here is what you can do:

1. copy/paste the fetch code so that it is executed after the token have been refreshed
2. make sure it works as expected
3. now figure out how to DRY your code
4. repeat 1-3 each time when you are stuck with your implementation

**Comment by parky128** [comment]
Ok, I thought I was asking a sensible question, clearly not, hopefully I'll get some more friendly responses elsewhere.

**Comment by simov** [comment]
Yep StackOverflow is the way to go for general questions, though I don't think *unfriendly* is the correct term to use for my response. In fact the points that I outlined above is what I usually do when I'm stuck with my own code.

**Comment by parky128** [comment]
Ok I apologise just frustration on my part! Thanks for the pointers
