### ISSUE TITLE
404 error does not cause callback to fail

### ISSUE THREAD

**Issue by benrondeau** [request/request#2196]
Not sure how the error handling works for the callback function, but when I get a 404 returned from a request, the first parameter (which is `error` in the documentation) is `null`, which then makes the request look successful. Example code:

```javascript
request({
        url: 'https://example.com/',
        method: 'POST',
        json : true,
        body : {"content" : 1},
        headers:{
            'Authorization' : 'token '
    }, function(error, response){
        if(error) {
            // Return error message
        } else {
            // Success
        }
    });
```

Result:
```javascript
error == null
response == {"statusCode":404, "body" : "Not found"}
```

Thoughts?

**Comment by simov** [comment]
Currently request does not handle the HTTP errors. You can wrap the callback and add your own logic there.

**Comment by benrondeau** [comment]
Does request recognize HTTP errors? If not, what is the purpose of the error parameter in the callback function?

**Comment by simov** [comment]
Currently the error parameter is used for runtime errors only.

**Comment by simov** [comment]
```js
var wrap = (callback) => (err, res, body) => {
  if (res.statusCode >= 400 && res.statusCode < 600) {
    callback(body, res, body)
  }
  else {
    callback(null, res, body)
  }
}
```

**Comment by 4141done** [comment]
Just got hit by this and it cost me a ton of time.  One one expect that the error parameter be returned on a bad status code.  Would you accept a PR to explicitly call this out in the README?  It's not apparent anywhere currently.

**Comment by benrondeau** [comment]
@4141done Yeah - I expected there to be some error logic for http codes (400's and 500's at least) but it wasn't documented somewhere that this was not supported. I wonder how many people are relying on this not realizing it is not supported!

**Comment by pantchox** [comment]
this should be mentioned in the docs(!)

**Comment by pantchox** [comment]
not related to the fact i <3 it
