### ISSUE TITLE
Document the properties added to the http.IncomingMessage

### ISSUE THREAD

**Issue by demurgos** [request/request#2198]
Hi,
I am currently helping to maintain the [Typings](https://github.com/typings/typings) definitions for the `request` package.

I noticed that `request` adds the following properties to the response object: `request`, `toJSON`, `caseless`, `body`, `read` so the result object is no longer a "pure" `http.IncomingMessage`.

**Why are these properties not documented ?**

Are they deprecated ? Is it just something forgotten in the doc ? (but I checked your tests and I did not found anything about these properties). Basically, are these properties reliable or should we keep them hidden ?

**Comment by simov** [comment]
Good question. Unfortunately there is a ton of state attached here and there in request and no one really knows what the initial plan was, or whether there was one in the first place. So these are just state vars for the most part, that are not meant to be used outside of the module, probably without `toJSON` because that's used for serialization, I guess :)

**Comment by Demurgos** [comment]
Then it should at least document `toJSON` and explain that it is safe to use `JSON.stringify` on this response.

**Comment by simov** [comment]
Feel free to update the docs and submit a PR about it :+1: 

Here is what's been said about [response.toJSON](https://github.com/request/request/blob/v2.72.0/request.js#L98-L106).

I guess [caseless](https://github.com/request/caseless) can be used too, in case you know that it's there. So I'm assuming that there are people out there that depend on it.

**Comment by demurgos** [comment]
I almost finished refactoring the documentation, it helped me to spot some other issues (ie. `elapsedTime` is an other property added to the response (but not always), the `auth` option is not consistent, etc.)
The README.md became huge with the time, so I separated it in smaller "guides" files and an `api.md` file with a full overview with the API and clearly stating every option with its type and default value.

I'll submit a PR as soon as possible.

**Comment by simov** [comment]
Sounds great! It will be interesting for me to see it. However huge changes require more time to review and merge.

Also note that we have a separate [repository](https://github.com/request/request.github.io) for documentation that we plan to use in future. It's hosted at http://request.js.org

**Comment by demurgos** [comment]
Oh, this is great !
Thank you for pointing me to this, I think that it better suits this documentation repository then.
It's still a work in progress, but you can take a look at [my refactor-doc branch](https://github.com/demurgos/request/tree/refactor-doc/doc).
I finished my first iteration on the options (in `doc/api.md`), I left some blanks when I wasn't sure about the types or default values, the description is mostly unchanged. What I would like is to clearly define the interfaces, not only the main `options` but also for the `AuthOptions`, `OAuthOptions`, etc. (for the moment it's spread across the whole `README.md`)

**Comment by simov** [comment]
I'll take a look at it. BTW I recently pushed something similar about the rewrite I'm working on [here](https://github.com/request/interface). I think everything from the legacy request docs, from the new rewrite, and from [request-promise](https://github.com/request/request-promise) should be placed in `request.js.org`.
So we should keep that in mind when organizing the categories and the markdown files in that repository.
As for the legacy auth, oauth etc options - I can help you with that.

**Comment by simov** [comment]
@demurgos I like how you have divided the readme into pieces. I have only one concern about the API docs, generally sorting the options alphabetically is a great idea, but we need to support grouping them semantically as well. This probably can be achieved via GitBook plugin and some basic JSON data structure.

**Comment by demurgos** [comment]
Yes, I noticed that you still grouped the features thematically in the new interface repository. I'll restore the original organization.

I moved my changes to a fork of `request.github.io` and started to actually document the missing properties/methods on `IncomingMessage`. So I'll close this issue to open a new one on the repo for the doc.

**Comment by simov** [comment]
Sounds good! I'll figure out something about the GitBook plugin, a little jQuery will do :) I really want to have the alphabetical order for the options as well. Unless you are familiar with the module that ordering is better.

**Comment by demurgos** [comment]
I was also considering this sort of solution, but I'm not really sure if that's that necessary.
After all, either you don't know the API and the thematic classification more helpful or you know the API and search some details (and then its pretty easy anyway to search the page).

[Here is a reordered version](https://github.com/demurgos/request.github.io/blob/legacy-doc/docs/api/interfaces/request-options.md#qsparseoptions).
I'm pretty satisfied with this structure (name, type [, default] & description) to describe the options but I'm still experimenting for the presentation of the package API. Using a website with directories really helps in organizing the API and has some benefits: ie. the anchor links work great for the options.

**Comment by simov** [comment]
I like it. The problem is I changed the directory structure today :) Just copy all of your directories and files into docs/request-legacy. We'll figure out the navigation later. Folders `next` and `promises` can be removed in your case.

**Comment by demurgos** [comment]
Ok, thank you for you feedback :)
