### ISSUE TITLE
Request using stream hangs for some reason...

### ISSUE THREAD

**Issue by happilymarrieddad** [request/request#2202]
Here is the error I'm getting. It may be I'm just using stream wrong.

```
gulp-0 1462381814900 - Origin: Worker (PID 29984)
gulp-0    [Error] Error: socket hang up
gulp-0   at createHangUpError (_http_client.js:250:15)
gulp-0   at Socket.socketOnEnd (_http_client.js:342:23)
gulp-0   at emitNone (events.js:85:20)
gulp-0   at Socket.emit (events.js:179:7)
gulp-0   at endReadableNT (_stream_readable.js:913:12)
gulp-0   at _combinedTickCallback (internal/process/next_tick.js:74:11)
gulp-0   at process._tickDomainCallback (internal/process/next_tick.js:122:9)
gulp-0 1462381814908 - Worker 2 exited - Exit code: 1
gulp-0    >> Worker PID: 431
gulp-0 1462381815711 - Worker 2 was respawned
```

Here is the stream

``` js
var stream = fs.createReadStream(fullFilePath)
    .on('error',function(err) {
        console.log('Unable to post file to mysql server... ERROR: ',err)
    })
    .on('end',function() {
        setTimeout(function(){
            insertData()
        },2000)
    })
    .pipe(
        request.post('http://'+process.env.DB_HOST+':8080/mysql/carrier_confirmation-'+req.params.order_id+'.pdf')
    )
```

**Comment by adnanrahic** [comment]
I am facing the same issue. Gulp worked flawlessly up until yesterday when I say this for the first time. Strange thing is I havent touched my gulpfile since I wrote it a 2 weeks ago. Here is the error:

> Error: socket hang up
    at createHangUpError (_http_client.js:250:15)
    at Socket.socketOnEnd (_http_client.js:342:23)
    at emitNone (events.js:85:20)
    at Socket.emit (events.js:179:7)
    at endReadableNT (_stream_readable.js:913:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)



However, I am not using streams. Which leads me to believe this issue is not gulp related.

**Comment by simov** [comment]
The socket may hang up for many reasons. Like for example when the server terminates the connection unexpectedly.

**Comment by soichih** [comment]
I was having a similar issue. For *my* case, the cause was on the server side. express 4 stopped supporting `req.on('close'..)` event. I couldn't use 'close' either because it get fired before my streaming actually ends.. I had to use 'close' event from the pipe() which finally worked. FYI
