### ISSUE TITLE
`request.defaults({ ... }).delete` appears to be missing

### ISSUE THREAD

**Issue by ncalexan** [request/request#2209]
I see code trying to pass it through at https://github.com/request/request/blob/2ef974a823eca5601d0e17eece4212c8bc8d01cc/index.js#L106, but locally (with version 2.71.0) I only have `request.defaults({ ... }).del`.  Is this intentional and the documentation should be updated?  Or is something else happening?

**Comment by ncalexan** [comment]
Without any true investigation, I wonder if https://github.com/request/request/blob/2ef974a823eca5601d0e17eece4212c8bc8d01cc/index.js#L73 is the issue?  Is there a difference between `.del` and `[delete]`?

**Comment by simov** [comment]
Hi @ncalexan can you try with version 2.72? The `delete` method was added in that version.
