### ISSUE TITLE
[FOSSA] **UNLICENSED_DEPENDENCY:** npm+domelementtype$1.0.0

### ISSUE THREAD

**Issue by anuccio1** [request/request#2211]
[FOSSA](http://fossa.io) has found an issue in this repo:

**UNLICENSED_DEPENDENCY:** npm+domelementtype$1.0.0

Generated by [FOSSA](http://fossa.io) on 05/11/2016

Reported by FOSSA user: alex

**Comment by dr-dimitru** [comment]
@anuccio1 ?
