### ISSUE TITLE
Error: no auth mechanism defined

### ISSUE THREAD

**Issue by IgorDePaula** [request/request#2227]
The module do not authentic user not by documentation, not by this solution

http://stackoverflow.com/questions/34370212/node-js-form-http-authentication-with-request-module-fails...

All form fails

**Comment by padgyx** [comment]
I encountered the same error on AWS lambda function when use this module:

Error: no auth mechanism defined

**Comment by alukach** [comment]
i had this problem. For me, it turned out that due to an internal bug I was passing `undefined` values for `pass` and `user`

**Comment by aluck-Tiffany** [comment]
When I met this problem, I realised from these comments  and source my local env file. Then it worked.
Hope useful for others like me.

**Comment by IgorDePaula** [comment]
@aluck-Tiffany local env file?
