### ISSUE TITLE
Application crashes a few kb before finishing a large download

### ISSUE THREAD

**Issue by ev8dev** [request/request#2228]
NW crashes just a few kb before the download is finished when trying to download a large file . I've tested this with a 228mb mp4 file using NW 0.15.0 32-bit and request 2.72.0. This problem also occured in NW 0.12.\* 32-bit with an older request version. This issue seems to occur in Windows XP 32-bit 100% of the time and I've managed to get the same result in Windows 7 randomly.

I've created a reproduction environement:
_URL removed_

I highly suggest downloading the video manually from _URL removed_ and changing the download URL in index.html to your localhost (eg. http://localhost/large-file.mp4) since this greatly speeds up the process of downloading the file and thus, testing.

**Comment by pushad** [comment]
This issue effects me too on Windows XP 32 bit.
I am using NW 0.12 and request library.

**Comment by ev8dev** [comment]
This problem seems not to occur on NW.js 0.14.7 anymore and can be closed.
