### ISSUE TITLE
Question about injecting headers in ALL requests

### ISSUE THREAD

**Issue by vapits** [request/request#2232]
Hi there and thx for this awesome module.

I haven't use it a lot and I was wondering,
Instead of adding the headers in every request by hand like the docs.

ex.
```
var options = {
  url: myuRL,
  headers: {
    'header1': 'headerVal'
  }
}

request(options ,callback);
```

Is it possible with a middleware or something to inject the headers in ALL requests?

I tried by creating this middleware:

```
var cache = require('../cache')
const addHeaders = function (req, res, next) {
  req.header('Authorization', cache.token);
  next();
};
module.exports = addHeaders;
```

It works on all request except those done with the `request` module.

I'd love some help on this thx.

**Comment by analog-nico** [comment]
You may use the `.defaults(...)` feature to set the headers:

``` js
var requestWithHeaders = request.defaults({
  headers: {
    'header1': 'headerVal'
  }
});
```

`requestWithHeaders` behaves like `request` only that the headers are already set:

``` js
var options = {
  url: myuRL
}

requestWithHeaders(options ,callback);
```

**Comment by vapits** [comment]
Oh sorry for leaving it open for so long, my bad. Thx for your help I was actually solved it the same way.

Thx

**Comment by analog-nico** [comment]
No problem. You are welcome!
