### ISSUE TITLE
unexpected error with limited stack trace

### ISSUE THREAD

**Issue by Ykid** [request/request#2244]
The issue happens when calling

``` javacript
request('url');
```

I didn't provide a callback function but when the request timeouted, it throws error.

``` javascript
Error: connect ETIMEDOUT
    at errnoException (net.js:901:11)
    at Object.afterConnect [as oncomplete] (net.js:892:19)
```

It is hard to trace where the error happens. 

Is this issue expected ? ( i.e. callback needs to be always provided to handle errors ? )
request verion `request@2.72.0`

**Comment by kazaff** [comment]
yes, that's be expect. the callback have first argument is err object.

but , in my env, some exception do not catch in callback,  i do not know why
