### ISSUE TITLE
request options (jar) clarification

### ISSUE THREAD

**Issue by christofferkho** [request/request#2247]
From README.md, on request(options, callback):

> jar - If true, remember cookies for future use (or define your custom cookie jar; see examples section)

var j = request.jar() is also used to create a custom jar.
and we can set cookies in the jar by using j.setCookie(cookie, url).

I'd just like to ask for clarification. Is the jar used for sending cookies to a server, storing cookies obtained from the server or both?

As far as the README.md explains, it's only for storing cookies obtained from the server.

**Comment by dandart** [comment]
Seems to work for both for me...
