### ISSUE TITLE
Add Force ipv6 option similar to curl

### ISSUE THREAD

**Issue by laplaceon** [request/request#2258]
The request module seems to be only making requests using ipv4. In curl I can add a -6 flag to use ipv6.

**Comment by nodesocket** [comment]
Also curious if ipv6 is supported? Is there an option `ipv6: true`?

**Comment by Somrlik** [comment]
Encountered this while testing an app. The server was running on `[::1]:666` and when `request`ing `localhost:666`, `request` would not connect to `[::1]` but always to `127.0.0.1`. Might be an error with `hosts` configuration on my machine, but IPv6 option would be nice nonetheless.

**Comment by alirayaneh** [comment]
is there any way to use request as curl -6 flag ?
