### ISSUE TITLE
How do I call this Request module from AWS Lambda function?

### ISSUE THREAD

**Issue by kennethchapman99** [request/request#2264]
Sorry - am a REAL noob here - but trying to deploy a Lambda function for an Alexa skill -- but cannot get 
request module figured out....   I do a 'require' like I do for HTTPS, like this:

var request = require('request'); 

and get an error when I actually call the Request library:
"errorMessage": "Cannot find module 'request'",

How do I include Request into my AWS Lambda function?

**Comment by DavidTPate** [comment]
Make sure that you zip up your `node_modules` with your Lambda function as Lambda doesn't have the `request` module by default and doesn't run `npm install`

**Comment by kennethchapman99** [comment]
Thanks for quick reply - wow!
So I'm writing my Lambda function in the AWS console - editing the code inline...  does this mean then that I create a local directory with my function code like this?:

/KenFunction.zip
    /node_modules/ 
   kenfunction.js

**Comment by kennethchapman99** [comment]
dam, my whitespace was stripped...

basically i'm asking:  do I just zip up node_modules and my function.js file and upload to lamda console?

**Comment by kennethchapman99** [comment]
So I did this:
put my lambda code into file 'kenfunction.js'
performed `npm install `
zipped up kenfunction.js AND `node modules`
Uploaded this ZIP to AWS Lambda console

When I go to test the function i no longer get error: '

Now I get an error:
"errorMessage": "Cannot find module 'index'"
(I cannot for the life of my find any reference to index.js or require('index') in `node_modules`

Sorry... am SURE this is easy stuff, but stuck

**Comment by ilrein** [comment]
It's not a request issue, it's lack of knowledge with using AWS Lambda. Try renaming kenfunction.js to index.js

**Comment by DavidTPate** [comment]
Your issue now @kennethchapman99 is that you didn't update the handler for the Lambda function. The default value is `index.handler` meaning load the file `index.js` and use the `handler` value that is exported from it to run the function. See the documentation that [AWS provides](http://docs.aws.amazon.com/lambda/latest/dg/nodejs-prog-model-handler.html) for details about how you setup a Lambda function. They have a good step by step guide for how to do it.

**Comment by kennethchapman99** [comment]
Ahhh!!!   Ok, everything clicked now - thank you!!

**Comment by DavidTPate** [comment]
Sweet, if you are good now @kennethchapman99 you could close this issue.

**Comment by ahhh** [comment]
Hey all! I'de like to reopen this as I am actually experiencing an error when 'requiring' the requests library using Node3.4 in an AWS Lambda function.
```
Unable to import module 'MyCode': Error at Function.Module._resolveFilename (module.js:325:15) at Function.Module._load (module.js:276:25) at Module.require (module.js:353:17) at require (internal/module.js:12:17) at Object.<anonymous> (/var/task/MyCode.js:20:15) at Module._compile (module.js:409:26) at Object.Module._extensions..js (module
Unable to import module 'MyCode': Error
at Function.Module._resolveFilename (module.js:325:15)
at Function.Module._load (module.js:276:25)
at Module.require (module.js:353:17)
at require (internal/module.js:12:17) 
^^ This is the line that I define: "var request = require('request');"
at Object.<anonymous> (/var/task/MyCode.js:20:15)
at Module._compile (module.js:409:26)
at Object.Module._extensions..js (module.js:416:10)
at Module.load (module.js:343:32)
at Function.Module._load (module.js:300:12)
at Module.require (module.js:353:17)
```

**Comment by eduardonunesp** [comment]
The problem with my setup was because the zip wasn't configured for recursive, so de node_modules going empty. Don't forget to zip as `zip -r pack.zip *`

**Comment by colemullen** [comment]
@ahhh did you ever figure your problem out?

**Comment by rafaeleyng** [comment]
Where are you folks uploading this zip file to? I can't find this option anywhere.

**Comment by NealWalters** [comment]
@rafaeleyng - Here is where you upload the zip. 
Sample Image: [](https://imgur.com/a/3kper)

Or you can upload with a command like this: 
aws lambda update-function-code --function-name YourFuncName --zip-file fileb://yourfile.zip

**Comment by rafaeleyng** [comment]
Thanks @NealWalters! I ended up finding it later, and now I'm using Serverless Framework, that abstracts this away.
