### ISSUE TITLE
Inspect request defaults

### ISSUE THREAD

**Issue by lgomez** [request/request#2265]
Is it possible to inspect the defaults set through request.defaults() after setting them and, if so, can someone share how? I haven't been able to figure it out.

Thank you,

**Comment by DiglidiDudeNG** [comment]
AFAIK, there isn't a way to do so. It seems to be within the local scope of the wrapper returned with `request.defaults({...})`.

**Comment by lgomez** [comment]
Hm.. That's what I thought. Unfortunate.

Thanks for the reply.
