### ISSUE TITLE
Unable to find 'elapsedTime' attribute

### ISSUE THREAD

**Issue by thomasvn** [request/request#2268]
I need to be able to use the response times of my http requests so I made this test function to reproduce my issue

```js
TestFunction(function(err, res, body) {});

function TestFunction (callback) {
    var options = {
        'url' : 'https://google.com',
        'time' : true,
    };
    request(options, function (error, response, body) {
        console.log(response.elapsedTime);
        return callback(error, response, body);
    });
}
```

It's telling me that the elapsedTime attribute is undefined.

I can't seem to find it when I sifted through the response itself either.

Anybody have an idea of how I can access it? It's said to be available in the docs!

**Comment by thomasvn** [comment]
@mikeal @simov 

Would either of you happen to know/remember off the top of your heads?

**Comment by mikeal** [comment]
hrm... do we only set that when someone passes a timeout?

**Comment by mikeal** [comment]
oh, nm, just read the docs, i didn't even know this was a feature :)

**Comment by thomasvn** [comment]
My workaround to this issue:

```js
TestFunction(function(err, res, body) {});

function TestFunction (callback) {
    var options = {
        'url' : 'https://google.com',
        'time' : true,
    };

    var start = new Date();

    request(options, function (error, response, body) {
        console.log("Response Time: " + (new Date() - start) + "ms");
        return callback(error, response, body);
    });
}
```
