### ISSUE TITLE
ETIMEDOUT after a lot requests

### ISSUE THREAD

**Issue by mscherer82** [request/request#2274]
my app is doing a lot http requests. After a while (> 2000 requests) I get ETIMEDOUT on each request. Restarting node fixes this.
My target system is windows, node 4.3.1.

**Comment by samuela** [comment]
I'm seeing something similar. It's quite difficult to debug. I have a bit of code:

```javascript
request({
  method: method,
  uri: uri,
  headers: headers
}, function(error, response, body) {
  if (error)
    ...
  else
    ...
});
```

The callback is not being called with the ETIMEDOUT error. Instead the call itself to `request` fails.

I'm running on AWS linux.

**Comment by RyotaSugawara** [comment]
Hi, I'm faceing same ETIMEDOUT error in a lot of http requests.

In node v0.10.x, keepAlive is default setting at http.Agent. But in v4.x, http.Agent default keepAlive option has changed to false.
I think that this is a cause.

In my case, It has been fixed if I use `request#defaults` like this.
```js
const request = require('request').defaults({
  forever: true
});
```

**Comment by mdumrauf** [comment]
Any news on this? None of the provided alternatives worked for me. It keeps throwing ETIMEDOUT randomly after some requests. Sometimes it's after 300 and some other times after 35k.

**Comment by kazaff** [comment]
@samuela hi, i do not quite understand your mean that " Instead the call itself to request fails.", i found that, the ETIMEDOUT error do not call the callback, i use the "process.on('uncaughtException', callback)" to catch the error.

**Comment by kazaff** [comment]
@RyotaSugawara  your mean is set the keep alive to true?

**Comment by jainayush1993** [comment]
I am facing the same issue. Suddenly all the requests start timing out ETIMEDOUT.

**Comment by cuongsimplypost** [comment]
I am facing the same issue. Request return error ETIMEDOUT but using postman successfully
