### ISSUE TITLE
All events?

### ISSUE THREAD

**Issue by wzup** [request/request#2277]
Any chance to get a list of all events?

How to read data from `response`? You do not explain it. Suddenly in your docs `on('data'` appears and without any explanation as well. I suppose there are gazillion events you just do not cover in docs. How may we know them?

**Comment by simov** [comment]
The response is an instance of [http.IncomingMessage](https://nodejs.org/dist/latest-v6.x/docs/api/http.html#http_class_http_incomingmessage) which in turn implements [stream.Readable](https://nodejs.org/dist/latest-v6.x/docs/api/stream.html#stream_class_stream_readable) which in turn emits `data` event.
