### ISSUE TITLE
ssl3_check_cert_and_algorithm:dh key too small

### ISSUE THREAD

**Issue by mmumshad** [request/request#2283]
When I try a basic authentication, I get the below error. Any advise?

`request.get('https://host/api').auth('admin', 'password', false);`

`Error: write EPROTO 101057795:error:14082174:SSL routines:ssl3_check_cert_and_algorithm:dh key too small:openssl\ssl\s3_clnt.c:3617`

**Comment by iNode** [comment]
This is an error from underlying OpenSSL library and it's not relevant to request library.
Can you properly reconfigure algorithms on server side?

**Comment by mmumshad** [comment]
yup reconfigured server and it works fine now. Had to change cipher keys on server side.
