### ISSUE TITLE
IPv6 address misinterpreted

### ISSUE THREAD

**Issue by c0b** [request/request#2292]
there are already a couple of IPv6 related issues filed, #1705 #1944 but all are different with this new one:

my server is binding on IPv6 address `[::]`, means same as IPv4's `0.0.0.0`; in dual stack OSes (like Linux), this resulted being able to handle both IPv4 and IPv6 clients, but this request package is handling IPv6 address wrong, see this example:

I use nc to simulate an http server listening on IPv6 any address [::] port 3000; this listening address and port can be confirmed with `lsof`

``` console
➸ nc -l6 -p 3000
...

➸ lsof -nPp 26678        # from another shell, find out the pid of nc is 26678
...
nc      26678  user    3u  IPv6 391972      0t0     TCP *:3000 (LISTEN)
```

then make a curl call of this server, with IPv6 address, like `curl -v [::1]:3000/any-url` the nc side can echo what is actually sent in the request:

``` console
➸ nc -l6 -p 3000
GET /any-url HTTP/1.1
Host: [::1]:3000
User-Agent: curl/7.47.0
Accept: */*

```

The `Host: [::1]:3000` is sent by curl as a http client, which is correct;

however, with the request as the http client, this is actually sent on wire:

``` console
POST /any-url HTTP/1.1
host: ::1:3000
accept: application/json
content-type: application/json
content-length: 307
Connection: close

```

by request call code is

``` javascript
request.post(
    { url: 'http://[::1]:3000/any-url',
      json: { a: 2, ... } },
    (err, resp, body) => console.log(err, resp, body));
```

the `host: ::1:3000` part is wrong, IPv6 address should be enclosed in bracket.

BTW: I tested other nodejs http client as well, like this one http://restify.com/#jsonclient

``` console
➸ node
> var restify = require('restify');
undefined
> var client = restify.createJsonClient({ url: 'http://[::1]:3000/tasks' });
undefined
> client.post('/abc', {a: 2}, (err, req, res, obj) => console.log(err, req, res, obj));

```

then the nc server side got correct result:

``` console
POST /abc HTTP/1.1
accept: application/json
content-type: application/json
user-agent: restify/4.1.1 (x64-linux; v8/5.0.71.52; OpenSSL/1.0.2h) node/6.2.2
date: Wed, 20 Jul 2016 22:27:07 GMT
content-length: 7
content-md5: qrRX4OwkT0d+4MCXuUonKA==
Host: [::1]:3000
Connection: keep-alive

{"a":2}
```

**Comment by JamesMGreene** [comment]
I ran into this today when my internal requests got rejected by Apache due to an invalid `Host` header for an IPv6 loopback address, e.g. `Host: ::1`.

**Comment by JamesMGreene** [comment]
Submitted a PR to fix this.
