### ISSUE TITLE
Making an HTTP request to a named pipe on Windows

### ISSUE THREAD

**Issue by httpdigest** [request/request#2296]
Node.js provides opening a listening socket on a named pipe, both on Windows and on Linux.
See:
- https://nodejs.org/api/http.html#http_server_listen_path_callback
- https://nodejs.org/api/net.html#net_server_listen_path_backlog_callback

For this, I use the express module to open a listening socket like so:

``` JavaScript
var express = require('express');
var path = require('path');
var app = express();
app.get("/:id", function(req, res) {
  console.log(req.params.id);
});
var pipe = path.join('\\\\?\\pipe', process.cwd(), 'myctl');
app.listen(pipe, function() {
  console.log("Listening...");
});
```

This seems to work as sysinternal's processexplorer tells that the Node process is indeed opening handles to that named pipe.

However, it does not seem like the request module supports making HTTP requests to a named pipe:

``` JavaScript
var pipe = path.join('\\\\?\\pipe', process.cwd(), 'myctl');
var request = require('request');
request.get(pipe);
```

(gives "Invalid URI" error).

whereas using net.socket the following works (results in the /:id route being taken on the server):

``` JavaScript
var pipe = path.join('\\\\?\\pipe', process.cwd(), 'myctl');
var sock = require('net').Socket();
sock.connect({path: pipe}, function() {
  sock.write("GET /1\r\n\r\n");
  sock.end();
});
```

Another question I have is: Is it possible to provide an already configured net.socket to the request module, or does request always try to open its own socket?

**Comment by httpdigest** [comment]
Bump.

**Comment by rbeeger** [comment]
At least on windows 10 it seems to already work, if some precautions are taken.
When creating the pipe on the listening side, you need to make sure the pipe name does not contain any colons, because those are used as separators on the calling side. So on the listening side you'll have

```js
pipe = pipe.replace(/:/g, '')
``` 

On the calling side you need to do that too and also convert all `\` to `/`:

```js
pipe = pipe.replace(/\\/g, '/')
``` 
Then you can use it like a Unix Domain Socket https://github.com/request/request#unix-domain-sockets

```js
request.get(`http://unix:${pipe}:<your api path>`)
```

In your case `<your api path>` would be just the id like `/1` as used in the socket example.

**Comment by darkguy2008** [comment]
@rbeeger how did you get it to work? can you provide some sample code? In my case, this doesn't seem to work:
```
http.createServer((req, res) => {
                console.log(req);
                res.writeHead(200, { 'Content-Type': 'text/plain' });
                res.write('Hello World!');
                res.end();
            }).listen('\\\\.\\pipe\\t1', () => {
                console.log('API initialized');
                next();
            });
```
All it returns is 404, or some empty result.

**Comment by rbeeger** [comment]
You can use the same on both sides. You don't need to use backslashes on windows to define a pipe. So

```js
let pipe = '//?/pipe/t1'
``` 

On the server side 
```js
... .listen(pipe, () => ... )
``` 
On the client

```js
await request({
    url: `http://unix:${pipe}:/some/api/endpoint`,
    method: 'GET'
  })
```
