### ISSUE TITLE
Can not set custom headers when post with form data

### ISSUE THREAD

**Issue by zhuchuji** [request/request#2299]
I found that when using:
     request({
                    url: "xxxx", 
                    method: "POST", 
                    formData: xxxx, 
                    headers: { "Content-Type": "application/json"},
       }, function(error, response, body) {
                   // handle response here
       });
The content type is still "multipart/form-data", can not be set.

**Comment by KpjComp** [comment]
Your either using formData that does mulltipart's, or your not.
If you don't need multipart, then use form instead, not formData.

**Comment by HarshaVardhanPVK** [comment]
When I am trying to do similar type of request, I am getting error as "The exception message is 'The incoming message has an unexpected message format 'Raw'. The expected message formats for the operation are 'Xml', 'Json'."

Please help me around...

**Comment by HarshaVardhanPVK** [comment]
request({
url: "xxxxx", 
method: "POST", 
body: formData, 
 json: true,
headers: { "Content-Type": "application/json"},
}, function(err, response, body) {
if (err)
resolve({"message": err});
else
resolve({"message": JSON.stringify(body)});
});


Worked for me, give a try...

May fix your issue also...

**Comment by zhuchuji** [comment]
@KpjComp you didn't get the point of the problem. The header will change to 'application/x-www-form-urlencoded' if use key 'form'. My problem is when you make such request, you can not set custom headers

**Comment by zhuchuji** [comment]
@HarshaVardhanPVK I use the key 'formBody' in request and finally set the custom header 'Content-Type' to value 'application/json'. Your solution bring exceptions for me. But thank you anyway.
