### ISSUE TITLE
Timeout for request through https-proxy

### ISSUE THREAD

**Issue by ershov-konst** [request/request#2301]
I'm trying make request through proxy. It's my code.

    var proxyList = [
       'http://username:pass@hostname:65233',
       'https://username:pass@hostname:65233'
    ];
    
    var ADDRESS = 'https://google.com';
    var TIMEOUT = 5*1000;
    
    var rp = require('request-promise');
    var url = require('url');
    
    
    function check(proxyUrl){
       rp({
          method: 'GET',
          uri: ADDRESS,
          proxy: proxyUrl,
          timeout: TIMEOUT,
          tunnel: true
       })
          .then(function(){
             console.log('good - ' + proxyUrl);
          })
          .catch(function(e){
             console.error(e);
          });
    }
    
    proxyList.forEach(function(proxyData){
       check(proxyData)
    });

http proxy works well, but on https i receive timeout
curl commands works well on http and https

    curl --proxy http://username:pass@hostname:65233 https://google.com
    curl --proxy https://username:pass@hostname:65233 https://google.com

How i can make request through https proxy?

**Comment by primewang** [comment]
How make request through https proxy?

**Comment by primewang** [comment]
@ershov-konst
