### ISSUE TITLE
Support user/pass within environment

### ISSUE THREAD

**Issue by timmjd** [request/request#2303]
Current implementation seems to ignore authentication that is attached to proxy environment:

```
export http_proxy=http://user:pass@foo.proxy:8080
export https_proxy=https://user:pass@foo.proxy:8080
```

**Comment by mlarcher** [comment]
I have the same issue. Any one could tell if this is a bug or just not implemented ?

**Comment by wsrast** [comment]
Same issue here. The proxy authentication syntax doesn't appear to function.
