### ISSUE TITLE
Error: Invalid URI "/"

### ISSUE THREAD

**Issue by dcsan** [request/request#2318]
I find this package to be really pedantic about options. 
can someone point out what might be the error in the below?

```
error [Error: Invalid URI "/"]

options { 
  uri: 'https://tracker.dashbot.io/track',
  json: true,
  qs: 
   { platform: 'generic',
     v: '0.6.0',
     apiKey: 'xxxxx',
     type: 'outgoing' },
  method: 'POST',
  href: '',
  pathname: '/' 
}
```

**Comment by joshkergan** [comment]
I got a response `{ success: true }` using the exact options you specified. I'm not sure what your error is caused by, but it does not seem to be related to request.

Here's my test code for reference
```javascript
'use strict';
var options = {
        uri: 'https://tracker.dashbot.io/track',
        json: true,
        qs: {
            platform: 'generic',
            v: '0.6.0',
            apiKey: 'Y0J3dAqe2j7NBDXpyUQaChFt4d5GzjACHU0NixOO',
            type: 'outgoing'
        },
        method: 'POST',
        href: '',
        pathname: '/'
    },
    request = require('request');

request(options, function (err, resp, body) {
    console.log(err, resp, body);
});
```

**Comment by dcsan** [comment]
thanks for checking. 
I tried a lot of different options and I think `json: true` should be the actual object to be passed as JSON `json: dataObject`? rather than using the body option. 

I also used request-promise package instead - which I think just wraps this?

```
    rp({
      uri: url,
      method: 'POST',
      json: message
    })
```

the above worked

maybe having `pathname: '/' ` was confusing or conflicting with the `qs` option?

**Comment by Kostanos** [comment]
Have the same issue here. In my case I just forwarding the POST request to internal service:

```
  var options = {
    url: 'http://myService/',
    headers: {
      Authorization: 'Bearer ???????',
    },
  }
  req.body.customerId = myCustomerId;
  request.post(options, {form: req.body}, function(err, resp, body){
    if (err){
      console.error(err);
    } else {
    }
  });
```

**Comment by engemasa** [comment]
I'm experiencing a similar issue. The response I'm getting is `[Error: Invalid URI "/"]`. Eventually I'm trying to get the `strictSSL = false` (or true per environment).

Here is my request:

```
var creds = {username : 'username', password: 'somepassword'};
request.post({ url: creds.appURL + '/endpoint/in/api' }, { json: creds}, function(error, response, body) {
    if(error) {
        console.log('ERROR:', error);
    } else {
        console.log(response, body);
    }
}
```

**Comment by DylanAlloy** [comment]
This is occuring for me as well for some mysterious reason. I can see using the request object & options that there is no 'URI' key with "/" in it. I'm not sure of what the issue is but I'll come back here if I find out.

**Comment by olygamy** [comment]
me too :( +1

**Comment by anagrius** [comment]
to too

**Comment by woniesong92** [comment]
+1

**Comment by platoniusen** [comment]
+1

**Comment by snowkidind** [comment]
+1

**Comment by yaoazhen** [comment]
+1

**Comment by classix-do** [comment]
I had the same problem, when writing a grunt download task. It turned out that I would sometimes get the request url as string `"http://..."` and sometimes as a string wrapped inside an array `["http://..."]`, which made the error difficult to spot by simply printing the request url.
I only noticed it after debugging the argument parsing of the `request()`-function.

Hope it helps.

**Comment by autumnfjeld** [comment]
+1

**Comment by thucnc** [comment]
I got the same issue 
```
Uncaught Error: Invalid URI "/"
at Request.init (node_modules/request/request.js:443:31)
at new Request (node_modules/request/request.js:283:8)
at request (node_modules/request/index.js:50:10)
```

**Comment by maxgardner** [comment]
I ran into this issue as well. I was able to resolve it by consolidating all of the options I was trying to set into one object.

**What didn't work**
```
request.post({
      uri: form_url,
      jar: true
}, {
      form: {
        // form data
      }
    }, (err, res, body) => {
        // handle response
  }
});
```

**What did**
```
request.post(uri, {
      jar: true,
      form: {
        // form data
      }
    }, (err, res, body) => {
        // handle response
  }
});
```
The form data is considered an option, so it should live in the options object. It looks like the function still takes a string parameter as the first argument for the URI, but you can omit that and add it to your options object instead if you'd prefer — both ways worked for me. Just be sure you're passing only one options object in.

I hope this helps anyone else who finds themselves here.

**Comment by dcsan** [comment]
@maxgardner thanks for the info! This ticket keeps pinging me with 'me toos' for the last couple of years...

**Comment by Fusseldieb** [comment]
The solution from @maxgardner worked like a charm. 

If you're using brackets to put your url, don't close it and open another after it just to put your header options, form data or stuff, those must all be inside the first brackets.

I moved everything together like @maxgardner did and it worked.

This issue can be closed.

**Comment by dcsan** [comment]
keep. either docs or code should change based on notes above.
