### ISSUE TITLE
form data encoding issue when posting form

### ISSUE THREAD

**Issue by haseebstella** [request/request#2324]
Hi,

I am having form urlencoding issue when posting data with special characters to a server. The server uses a specific charset "windows-1252" and is unable to decode those special characters when other charset is used.

is there a way in request npm package to specify a charset during request preparation to be used for encoding ?

**Comment by gaoshijun1993** [comment]
I have the same issue...

**Comment by Paul-DS** [comment]
In my case, I succeed to make it work using the `encoding` option:

```
request.get(
    "YOUR-URL",
    { encoding: 'latin1' },
    (err, response, body) => console.log(body)
);
```
