### ISSUE TITLE
Cannot see requests in the developer console

### ISSUE THREAD

**Issue by dukedougal** [request/request#2325]
I am using 

chrome "52.0.2743.82"

electron "1.3.2"

And none of the network request show in the network tab of the developer console.

I can't figure out how to see the network traffic.

Any suggestions?

thanks!

**Comment by czardoz** [comment]
@dukedougal set `NODE_DEBUG=request` in your terminal before starting Electron

**Comment by maximerenaux** [comment]
hello @czardoz, 

I have the same problem in a "decompiled/unzipped" electron project. I would like to see the request in   network tab to save it as HAR but I don't find the solution. 

Where can I set NODE_DEBUG=request? 

thanks
