### ISSUE TITLE
content-type text/html for images

### ISSUE THREAD

**Issue by khanhankkhan** [request/request#2336]
Hi,
sometimes a server mistakenly returns ' text/HTML'  in the header for the content type of their image URLs.  I've noticed that when this occurs the buffer data downloaded by request appears to be invalid.  below is an endpoint that will run on nodeJS with an example URL where the content type is text/HTML instead of what it should be, an image:

```
app.get('/api/test', function(req,res)
  {
    var type    = '';
    var img_buf   = Buffer('');
    var request = require('request');
    request.get("http://images.bergdorfgoodman.com/ca/2/product_assets/Y/2/S/N/K/BGY2SNK_mu.jpg").
    on('data', function(data)
    {
      img_buf = Buffer.concat([img_buf,data]); 
    }).
    on('end',function(w)
    {
      var Canvas = require('canvas');
      var Image  = Canvas.Image;
      var img = new Image;
      console.log(type);
      console.log('img_buffer done downloading...');
      img.onload = function()
      {
        console.log('i loaded');
        res.send('done');
      };
      img.onerror = function(e)
      {
        console.log('error:'+e);
      }
      img.src = img_buf;
    }).
    on('response', function(response) 
    {
      type = response.headers['content-type'];
    }).
    on('error',function(error)
    {
      console.log('error: '+error+' with:'+image_urls[index]);
    });

  });
```

**Comment by khanhankkhan** [comment]
The server hosting the image matters - if you assign the img.src to the url (instead of buffer data), then draw to a canvas and try to get the image data, you get a 'tainted canvas'

example url:
http://images.bergdorfgoodman.com/ca/1/product_assets/J/9/1/5/5/BGJ9155_mu.jpg

javascript console logs:

Uncaught SecurityError: Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported.

Maybe that helps. Don't know if request can 'untaint' a canvas, but it might be good to have a robust warning in the response mentioning the canvas is 'tainted' (if request could determine the image is tainted while returning the image)

**Comment by tanmau5** [comment]
Hey, I am having the same exact problem but not being able to fix it.
