### ISSUE TITLE
Update "hawk" in order to fix "boom" unmet dependency warning

### ISSUE THREAD

**Issue by mickaeltr** [request/request#2338]
Hello,

When installing "request", I get the following warnings:

```
npm WARN unmet dependency …/node_modules/request/node_modules/hawk requires boom@'2.x.x' but will load
npm WARN unmet dependency …/node_modules/boom,
npm WARN unmet dependency which is version 3.2.2

npm WARN unmet dependency …/node_modules/request/node_modules/hawk/node_modules/cryptiles requires boom@'2.x.x' but will load
npm WARN unmet dependency …/node_modules/boom,
npm WARN unmet dependency which is version 3.2.2
```

`request` currently depends on `hawk ~3.1.3`. It seems that updating to `hawk ~5` would fix these warnings.

Thanks

**Comment by wtgtybhertgeghgtwtg** [comment]
It seems that `hawk ~5` requires at least node v4.  Wouldn't that mean that `request` would have to bump the minimum required node version to v4 for something like this to happen?

**Comment by JSteunou** [comment]
should be closed

**Comment by mickaeltr** [comment]
I am closing it as it is outdated.

**Comment by JSteunou** [comment]
@mickaeltr : I was searching for all "Hawk" related issues, 99% of them can be closed :) I started by commenting this one but then was too lazy to continue :D
