### ISSUE TITLE
request doesn't follow 301 redirects using proxy

### ISSUE THREAD

**Issue by morfies** [request/request#2344]
Hi, I have two urls:
`http://tbphoto3.bababian.com/upload7/fuguirenshen/201606/001169212894_m.jpg` which is 301 redirected
and `http://t.shuaishou.com/Get/168062675` which is 302 redirected.

But when I request to get the two with 

``` js
request.defaults({
  proxy: 'my-proxy-address'
})
```

only 302 redirect is returned successfully with final content.

**Comment by scotttrinh** [comment]
Are these `GET` requests? What is the response from the 301 redirect?

**Comment by keksas** [comment]
For me this happened with a POST request. Nginx was configured to do 301 redirects to  upgrade from http to https.  Relevant response headers:
```
{
    'content-type': 'text/html'
    'location': 'https://api.foo.com'
}
```
Response body matches content-type header:
```
<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx</center>
</body>
</html>
```
