### ISSUE TITLE
Cookie not in this host's domain. Cookie:facebook.com Request:null

### ISSUE THREAD

**Issue by JamesTheHacker** [request/request#2345]
I'm looping through a JSON array of cookies and adding them like so:

    let cookies = [];
    cookies.push(new ToughCookie.Cookie({
        key: cookie.name,
        domain: '.facebook.com',
        value: cookie.value,
        secure: cookie.secure || false,
        path: cookie.path,
        httpOnly: cookie.httpOnly || false,
        extensions: extensions
    }));

I later set them like so (using request.cookieJar):

    cookieJar.setCookie(cookie, '.facebook.com', (err, cookie) => {
        if(err) {
            reject(new Error(err));
            return;
        }
    })

When making a request I am getting the following error:

    Unhandled rejection Error: Error: Cookie not in this host's domain. Cookie:facebook.com Request:null

The documentation is not very good on how to set this up. I could get this to work by removing the `domain`, and using `https://facebook.com` when setting the cookie. But, this is useless as this means other requests can not be made to endpoints such as `upload.facebook.com`.

The cookies all contain `domain=.facebook.com`.

How do I set the cookies and add them to the cookie jar properly so that they work across subdomains.

**Comment by JamesTheHacker** [comment]
Problem solved here https://github.com/SalesforceEng/tough-cookie/issues/26

**Comment by Nisthar** [comment]
@JamesTheHacker whats the solution?
