### ISSUE TITLE
empty post data with example from doc

### ISSUE THREAD

**Issue by piotr-s-brainhub** [request/request#2356]
One of the most essential features of such a library is ability to just send post data.

According to documentation (https://www.npmjs.com/package/request) I tried:
`request.post('http://service.com/upload', {form:{key:'value'}})`
and I obtain empty post data on the server.

On the other hand such a code works:
`request.post('http://service.com/upload', {json:{key:'value'}})`
but in the docs there is nowhere a similar example.

**Comment by scotttrinh** [comment]
This works as expected:

```js
var request = require('request');
request('http://httpbin.org/post', { form: { key: 'value' } }, function(err, res, body) { console.log(body); });
```

httpbin.org/post echos back the post request, and it gives me this in the body:

```
{
  "args": {}, 
  "data": "", 
  "files": {}, 
  "form": {
    "key": "value"
  }, 
  "headers": {
    "Content-Length": "9", 
    "Content-Type": "application/x-www-form-urlencoded", 
    "Host": "httpbin.org"
  }, 
  "json": null, 
  "origin": "4.14.28.78", 
  "url": "http://httpbin.org/post"
}
```

Is it possible that your server is expecting `application/json` instead of `application/x-www-form-urlencoded`?

**Comment by piotr-s-brainhub** [comment]
I use Express and the following code on the server:
```
 router.post('/', (req, res) => {
    console.log(req.body);
})
```

With request('...', { form: {key: 'value'}}) I obtain an empty object `{}` as request body.

**Comment by simov** [comment]
The express middleware is called body-parser.

**Comment by simov** [comment]
[Here](https://github.com/expressjs/body-parser#bodyparserurlencodedoptions)
