### ISSUE TITLE
Random ETIMEDOUT

### ISSUE THREAD

**Issue by devlo** [request/request#2358]
I am getting ETIMEDOUT in communication between servers, timeout is set to 5 seconds and request is retried 3 times. Sometimes it timeouts once, sometimes it timeouts 2 out of 3 retries and sometimes it will timeout 3 times (all 3 retries). This is not fault of the destination server because I've tested same route from different application written in Go at the same time and i get response in 2ms, no timeouts.

**Comment by pyhedgehog** [comment]
To make you issue meaningful I recommend you to add at least your platform/OS, OS version, Node version, request version.

**Comment by devlo** [comment]
@pyhedgehog 

Then stranger you should get through all issues that mention ETIMEDOUT in this module, there is a lot of it and people get it on different platforms and different versions of node and request. So writing details you mention will not make it necessary more meaningful than it is now. 

But hey here it goes anyway:

OS: Debian 3.16.7-ckt20-1+deb8u1 
request: newest (2.74.1) 
node: newest (6.4.0)
