### ISSUE TITLE
Rename asXXX methods in BaseRequest

### ISSUE THREAD

**Issue by JMVM** [request/request#2359]
Hi there,

Please could you rename **asXXX** methods in **BaseRequest** related to send request? For example, **asString()**

It's confusing, looking like returning **request as string**, instead of **response as string** as having a look method code.

Thanks

**Comment by JMVM** [comment]
I meant Java version.

Created thread in https://github.com/Mashape/unirest-java/issues/168

So please close this one.

**Comment by simov** [comment]
You can close it too :)
