### ISSUE TITLE
bug fix for formData (TypeError: The header content contains invalid characters)

### ISSUE THREAD

**Issue by gravsten** [request/request#2367]
The latest version of request leaves off the function `clone` in the headers if `formData` is used:

```
headers: { host: 'target.com',
    'content-type': 'multipart/form-data; boundary=--------------------------597199664407293581467286',
    clone: [Function],
    'content-length': 394 };
```

As a result, the request fails with "TypeError: The header content contains invalid characters".

A proper solution would be not to store a function in the headers, but I can't be bothered so my quick fix is this (at and around line 736, in diff style):

```
      // We have a method named auth, which is completely different from the http.request
      // auth option.  If we don't remove it, we're gonna have a bad time.
      var reqOptions = copy(self)
      delete reqOptions.auth
+      delete reqOptions.headers.clone;

      debug('make request', self.uri.href)
```

**Comment by TennyZhuang** [comment]
perhaps you can encodeURI it?

**Comment by khiettran** [comment]
@TennyZhuang it works. Thanks
