### ISSUE TITLE
PUT request creates a 0 bytes file without the specified contents for digest-auth servers

### ISSUE THREAD

**Issue by anoopemacs** [request/request#2375]
https://runkit.com/anoopemacs/request-omnifocus

File does get created at specified url -> `https://sync6.omnigroup.com/anoop/${filename}.cc`
but has no content

Trying the same with cURL works fine:
   `curl --digest -u anoop:password 'https://sync6.omnigroup.com/anoop/${filename}.txt' -X PUT -T "/Users/anoop/delete/<some local file>.txt"`

**Comment by anoopemacs** [comment]
Digest Authentication is working properly during a GET request
but during a PUT request it is failing

**Comment by anoopemacs** [comment]
Wireshark shows a Media Type file attachment for the first PUT request 
(before a 401 is received from digest type server)

The second PUT request doesnt contain any Media Type section

**Comment by WowMuchName** [comment]
I was trying to upload a file to nextcloud's webdav and had exactly the same problem.
Setting auth.sendImmediatelly to true fixed it. Here is what *seems* (!) to happen under the hood (source: request-debug's output):

With sendImmediatelly = **false**:

request does a PUT
server requests auth
request does the request with auth provided but **without** the body **if** the body is a stream.


With sendImmediatelly = **true**

request sends the PUT with auth and the body


This is true if you pipe but also if you provide a stream.

`request({
  auth: {sendImmediatelly: false}
  body: aStream
})`
=> 0 byte file

`aStream.pipe(request({
  auth: {sendImmediatelly: false}
})`
=> 0 byte file

`request({
  auth: {sendImmediatelly: false}
  body: aBufferOrString
})`
=> **works fine !!**

Setting sendImmediatelly: true makes examples 1 and 2 also work.

Personally I would like it if the documentation was updated in regards to raw-bodies. For *body* it just states that it can be a string, buffer or readStream. It should also mention some of the caveats that apply. Debugging such things using wireshark or other tools is very time intensive.

**Comment by mbohgard** [comment]
This is my exact problem. Been pulling my hair out for the last couple of days because of this. I need to be able to pipe patch/post requests with digest auth (and sendImmediately: false) but the body from the client isn't provided to the server.
