### ISSUE TITLE
tough-cookie@2.2.2 deprecated due to ReDOS vulnerability

### ISSUE THREAD

**Issue by louy2** [request/request#2376]
Received this npm warning today installing Elm.

    npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie 

Reference: https://nodesecurity.io/advisories/130

**Comment by louy2** [comment]
Elm is using an old version. Moving this issue to Elm.

**Comment by worc** [comment]
link to the elm issue: https://github.com/elm-lang/elm-platform/issues/166
