### ISSUE TITLE
Support query string encoding?

### ISSUE THREAD

**Issue by Huachao** [request/request#2383]
Do we support query string encoding?

**Comment by scotttrinh** [comment]
Yes. See the README.

**Comment by Huachao** [comment]
@scotttrinh sorry I didn't found the related words in README

**Comment by scotttrinh** [comment]
Search for `querystring` as all one word.

**Comment by victorbucutea** [comment]
I still can't find any `querystring` in the README

**Comment by scotttrinh** [comment]
![screen shot 2017-07-18 at 9 55 40 am](https://user-images.githubusercontent.com/1682194/28320729-4fed5894-6b9f-11e7-8aee-2b64b21e1647.png)

Maybe this section isn't answering your question?
