### ISSUE TITLE
always error "Error: socket hang up" when download image.

### ISSUE THREAD

**Issue by breaklee** [request/request#2384]
url is below.

http://image.zdnet.co.kr/techplanet/2016/images/skplanet.jpg

is there any solutions to fix?

**Comment by scotttrinh** [comment]
Looks like this is an issue with the server, as it fails with `httpie` and `curl`, too. Maybe they have some User Agent sniffing going on that filters out non-web browser traffic?

**Comment by axelpale** [comment]
Please close this issue because it is not about the `request` module.

    $ curl http://image.zdnet.co.kr/techplanet/2016/images/skplanet.jpg
    curl: (52) Empty reply from server
