### ISSUE TITLE
Unable to set "Authorization" header in options?

### ISSUE THREAD

**Issue by adityamertia** [request/request#2386]
Hi,

I am unable to send Authorization header in the request. 

var options = {
        url: uri,
        qs: ...... //Query string data
        method: 'GET',
        headers: {
            'Authorization': "ABCD",
        }
    };

Dont see this in document as well. How to send such a request that needs Authorization header to exist?

Thanks
Aditya

**Comment by Spetastian** [comment]
What kind of authorization is it? Basic?

**Comment by BenSower** [comment]
Can you provide the actual piece of code used to send your request?

Does the problem persist when using this example: 
https://github.com/request/request#custom-http-headers ?

**Comment by adityamertia** [comment]
The code i was using is as below:

===============================================================
var request = require('request');
var fs = require('fs');
var configurationFile = 'config.json';
var configuration = JSON.parse(
    fs.readFileSync(configurationFile)
);
exports.getGoals = function(event, context){
    require('request').debug = true;
    var options = {
        url: configuration.apimap.getGoals.uri,
        qs: event.params.querystring, //Query string data
        method: 'GET',
        headers: {
            'Authorization': configuration.shared.secret,
            'tokenIdentifier': configuration.shared.secret
        },
        auth: {
            'bearer': configuration.shared.secret
        }
    };
     request(options, callback);     
     function callback(error, response, body) {
        if (!error && response.statusCode == 200) {
               context.succeed(JSON.parse(body));
        }
     }
};
=====================================================

Under options i was initially sending Authorization in header and then tried sending same value in auth object also, but didnt work. Found some similar issues reported @http://stackoverflow.com/questions/27944086/nodejs-request-module-doesnt-send-authorization-header

Thanks
Aditya

**Comment by BenSower** [comment]
Thank you for your code, but to come back to the question of @Spetastian: What kind of authorization are you working with? Is it basic username + password? For this, the 'auth' field is designed and can be used as for example described here: http://stackoverflow.com/a/15988737/2856218

If you use something like Oauth, you have to follow the proper structure of the header. In your example, it looks like you mixed both.
The proper form for Oauth (or similar) headers is usually something like this:

`'Authorization' : 'Bearer ' + authToken`
Note the space between "Bearer" and the authToken.

**Comment by adityamertia** [comment]
So our backend APIs expect a shared secret key (No username password auth) for authentication and we pass it in "Authorization" header. I initially tried with and this is what i want
var options = {
         url: configuration.apimap.getGoals.uri,
         qs: event.params.querystring, //Query string data
         method: 'GET',
         headers: {
                'Authorization': configuration.shared.secret
         } 
};

But this did not work. Any pointers to this?

**Comment by scotttrinh** [comment]
What do you mean by "did not work"? When you inspect the request on the server-side, do you see the authorization header you're expecting to see?

By the way, you can format code in GitHub using "backticks" (\`) for \`inline-formating\`: `inline formatting` and three backticks:

\`\`\`
Like this
\`\`\`

shows up like:

```
Like this
```

**Comment by adunkman** [comment]
I was just caught by a similar issue — it appears that the `Authentication` custom HTTP header isn’t passed through to the request, and is instead replaced by values set in `auth` settings [as described in the README](https://github.com/request/request#http-authentication) (even if no `auth` settings are supplied).
