### ISSUE TITLE
Digest authentication should uppercase HTTP method

### ISSUE THREAD

**Issue by dbellavista** [request/request#2388]
When computing the ha2 part of the challenge (https://github.com/request/request/blob/master/lib/auth.js#L95) method is used as is, while the RFC specifies that HTTP method must be uppercase.

The problem is when you try to authenticate like this:

```
request({
   method: 'get',
   uri: 'http://test.com/asd',
   auth: { user: 'user', pass: 'pass', sendImmediately: false }
})
```

While the GET is correctly performed despite the method case, the authentication will fail because the challenge is computed with the string `get` on the client size and `GET` on server side.

**Comment by masu1402** [comment]
Yep, still an issue. Was solved by setting method in request as uppercase. Should probably be mentioned in the HTTP Authentication examples so that other users don't get stuck as I did.

**Comment by saikojosh** [comment]
Came across this same issue. The module should coerce the method to uppercase as soon as it's supplied. Would solve these sorts of silly bugs.
