### ISSUE TITLE
How to read same key headers from a response?

### ISSUE THREAD

**Issue by miguelalche** [request/request#2389]
Hello! 
First of all thanks for this amazing module! 

Here is the issue: 

After a get request I want to read two header fields called with the same key: 'set-cookie' 
I know this by inspecting the response headers in chrome's debugger.

The problem is that, when using this module, in the response headers only one appears since -I believe -it's an object already processed which doesnt allow to have same key fields.

So how do I get hold of two response headers with the same key?

Thanks! 

PD:  if I inspect the jar with getCookies() i get an empty array so that's not a solution. Which is also weird since before (that is, when the page I was crawling returned just one cookie for each key in the header) it worked fine and gave me an array with length > 0.

**Comment by deamme** [comment]
I think I got the same problem but where I want to post data with same field names instead.

**Comment by gowthamgts** [comment]
@miguelalche I too had the same problem lately. I wanted to get the cookies set by the `set-cookies` header, and struggled with it.
