### ISSUE TITLE
Wrong percent-encoding for reserved URI character

### ISSUE THREAD

**Issue by gecko17** [request/request#2390]
As defined in the RFC (https://tools.ietf.org/html/rfc3986#section-2.2) the character Apostrophe "'" is a reserved character and therfore should not be percent-encoded when sending a http request.
I went into an issue sending a request with the following path: **/api/Things('1234')**
because It was encoded into **/api/Things(%271234%27)** which cannot be handled by the backend.

As you see the paranthesis are not encoded because they are a reserved character. So encoding the Apostrophe is definetly a bug.

Btw the http.request method does not percent-encode the Apostrophe.

**Comment by bryant-st** [comment]
I just ran into this as well. the `request` module is using node's `url` module to parse the input url. if you pass in an object for the uri/url parameter, it won't do that. So you can parse the url on your end and then replace the encoded apostrophes
```
    uri = require('url').parse url
    uri.pathname = uri.pathname.replace '%27', "'"
    uri.path = uri.path.replace '%27', "'"
    uri.href = uri.href.replace '%27', "'"
    request {uri: uri}, (err, resp, body) ->
```
