### ISSUE TITLE
does it support http2 ? 

### ISSUE THREAD

**Issue by nnIIInnjA** [request/request#2396]
i tried using it with http2, it's giving error "cannot set deprecated header: connection"

**Comment by mikeal** [comment]
Node.js core does not *yet* support HTTP2 and so request cannot support it yet.

**Comment by dr-dimitru** [comment]
is it supported on my end. And it is not related to node.js, it's only nginx feature.

in `/etc/nginx/sites-availble/default`:
```nginx
server {
  listen 443 default_server ssl http2;
  listen [::]:443 default_server ssl http2;
  server_name _;

  ssl_certificate <cert>;
  ssl_certificate_key <cert_key>;
  ssl_trusted_certificate <pem_chain>;
}
```

**Comment by ChrisCinelli** [comment]
`node-spdy` support HTTP2.

**Comment by nnIIInnjA** [comment]
if node doesn't work with http2 then why there's a package http2 on npm i wonder.

**Comment by dolanmiu** [comment]
Any update on this? I would like request to talk to a http2 server

**Comment by mikeal** [comment]
experimental support is landing soon in core. once we have that we'll start looking at how request can best use http2.
