### ISSUE TITLE
crypto not usable (warning from dependency)

### ISSUE THREAD

**Issue by w01fgang** [request/request#2406]
When I use `request` for https protocol I get this warning:

```
console.warn node_modules/node-uuid/uuid.js:48
      [SECURITY] node-uuid: crypto not usable, falling back to insecure Math.random()
```

It seems that node-uuid is slows down his [maintain](https://github.com/bigcompany/hook.io/issues/120). Can we switch to [fork](https://github.com/defunctzombie/node-uuid)? Which seems still maintained.

**Comment by logicoder** [comment]
Very annoying with test suites.

**Comment by doublesharp** [comment]
The `node-uuid` module is deprecated, `uuid` is recommended instead (as @w01fgang suggests).

> npm WARN deprecated node-uuid@1.4.7: use uuid module instead

**Comment by doublesharp** [comment]
I was going to do a pull request and then noticed that the change has already been made in the repo and was upgrade to `uuid@3.0` yesterday in commit https://github.com/request/request/commit/39350edecf29a4996225974908a175f8a7759b76 by @simov. Hopefully available soon.

**Comment by simov** [comment]
Already published :+1:
