### ISSUE TITLE
x-www-form-urlencoded API call issue

### ISSUE THREAD

**Issue by dgt009** [request/request#2409]
```
 var dataToSend = {
          key: "value",
          key1: "value1"
        };

request.post({
        url: 'http://localhost:9092/services/reports/generateReport',
        form: dataToSend
    }, function optionalCallback(err, httpResponse, body) {
        if (err) {
            return console.error('upload failed:', err);
        }
    }).on('end', function (response) {
        console.log('success log'); 
        res.download('public/uploads/report.pdf');
    }).on('error', function (response) {
        console.log('Error downloading report file');
    }).pipe(fs.createWriteStream('public/uploads/report.pdf'));
```

Above code was working absolutely fine before 20 days, and now I am trying to run the same code, but it doesn't work ( doesn't even shows any error).

**output is always "success log" . even If I write some wrong URL then also it shows "success log"**

Web service is working fine, I have verified it with an external REST client.

Problem here is:
1) It doesn't care what URL I write, will go into 'end' part without giving any 'error'.
2) how to debug it? doesn't show any error

Note:  recently there was an update in request package, could that be a problem ?

**Comment by dgt009** [comment]
I didn't want to create a generate one new issue, 
but I believe something is wrong with **request.post()** . I tried running sample code, which works fine. But doesn't work with post request.

```
request('http://www.google.com', function (error, response, body) {
  if (!error && response.statusCode == 200) {
    console.log(body) // Show the HTML for the Google homepage. 
  }
})
```

I was just about to push this code in Production and got this error. please I don't want to move to another rest HTTP-client

**Comment by jschulenklopper** [comment]
@dgt009, I believe I encountered the same problem with `request.post()` - the posted form data didn't come through correctly on the other end.

I solved it by `request({url: url, body: data, json: true, method: "post"}, function (error, res, body) {})`, so encoding the properties of the request as a `options` argument.
