### ISSUE TITLE
Does't work with forever flag (keep alive)

### ISSUE THREAD

**Issue by L1vet** [request/request#2411]
var fs = require('fs');
var request = require('request');

var options = {
        url:'https://csgosell.com/phpLoaders/getInventory/getInventory.php',
        encoding : 'utf8',
        gzip : true,
        forever: true,
        headers: {
            'Host': 'csgosell.com',
            'Connection': 'keep-alive',
            'Content-Length': '58',
            'Cache-Control': 'max-age=0',
            'Accept': '_/_',
            'Origin': 'https://csgosell.com',
            'X-Requested-With': 'XMLHttpRequest',
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36',
            'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8',
            'Referer': 'https://csgosell.com/',
            'Accept-Encoding': 'gzip, deflate, br',
            'Accept-Language': 'ru-RU,ru;q=0.8,en-US;q=0.6,en;q=0.4',
            'Cookie': 'my-cookies from browser'

```
    },
    form: {
        stage:'bot',
        steamId:76561198284997423,
        hasBonus:false,
        coins:0
    }
};



request.post(options, 
    function(error, response, body){
        console.log(response.statusCode);
        if (!error) {
            fs.writeFileSync('csgosell.html', body);
        }
        else{
          console.log(error);
        }
     }
);
```

chrome request:
https://i.stack.imgur.com/zKQo5.png
Request with request.js:
https://i.stack.imgur.com/yH9U3.png

In any case I get a 200 status, but in one case(chrome) I get html, in another case I get '�SE�l�' or ' ' with options.gzip true.

Also doesn't  works with spdy agent

var spdy = require('spdy');

var agent = spdy.createAgent({
  host: 'csgosell.com',
  port: 443,
  spdy: {
    ssl: true,
  }

}).once('error', function (err) {
  this.emit(err);
});

options.agent = agent;

**Comment by ChrisCinelli** [comment]
Is this still a problem ?
