### ISSUE TITLE
Revoked SSL certificates do not throw error

### ISSUE THREAD

**Issue by Weyland** [request/request#2413]
```
    request({ url: 'https://revoked.badssl.com' }, (error) => {
        console.error(error);
    });
```

Not quite sure if this is the right place but I've been testing the errors this library throws when going through the list at https://badssl.com

I've found that most errors are thrown except when a certificate has been revoked e.g. https://revoked.badssl.com/

Is this something that can be fixed in the library or is this a problem with NodeJS itself. I'm currently using 6.8.0.

**Comment by NoahCarnahan** [comment]
This issue in the node repo helps explain the behavior: https://github.com/nodejs/node/issues/16338

**Comment by Weyland** [comment]
Thanks!
