### ISSUE TITLE
How to disable retry when request timeout

### ISSUE THREAD

**Issue by sirhoe** [request/request#2421]
Hi,

I am doing a POST to a server who has very poor processing and sometimes it takes more than a minute to complete. Currently I see from the logs the POST will retry and usually succeed at the third time. Due to business requirement, I do not want the timeout to be retried at all if it was a timeout.

I check the documentation and it doesn't mention any option for retry, and some of the issues pointing that this package do not do retry at all. I am getting confused so I want to ask if this module do retry on timeout? and if Yes, how can I disable it?

**Comment by razvanilin** [comment]
This issue is driving me crazy too. Even though I set the timeout with the `RestangularConfigurer` the request is retried after 2 minutes
```
.factory('InitRestangular', function(Restangular) {
  return Restangular.withConfig(function(RestangularConfigurer) {
    RestangularConfigurer.setRestangularFields({
      timeout: 3600000
    });
  });
})
.factory('Init', function(InitRestangular) {
  return InitRestangular.service('init');
})
```

**Comment by hassaananjum** [comment]
This is a frustrating issue for me too, even though I have set the timeout to 3600000 using the 'timeout' option while providing options to the request, the module still sends a second request after 120 seconds. Is there any way to prevent retry?

**Comment by markstos** [comment]
@sirhoe @hassaananjum @razvanilin How are you certain that this module is retrying after two minutes and not some other module which calls this one? Please write a unit test for the test suite that confirms that this module retries after two minutes.
