### ISSUE TITLE
response missing trailing newline.

### ISSUE THREAD

**Issue by jdalton** [request/request#2434]
In Request 2.75.0, though I've seen it with `https.get` too, and Node 6.8.0:

``` js
const url = 'https://cdn.jsdelivr.net/g/fuse@2.5.0,immutable.js@3.8.1,react@15.3.2(react.min.js+react-dom.min.js)';

request(url, (error, resp, body) => console.log(body.endsWith('\n')));
// => should log true, but logs false
```

If you [download the file](https://cdn.jsdelivr.net/g/fuse@2.5.0,immutable.js@3.8.1,react@15.3.2%28react.min.js+react-dom.min.js%29) _(save as foo.js)_ and inspect it:

``` js
fs.readFileSync('foo.js', 'utf8').endsWith('\n');
// => true
```

Related to https://github.com/mozilla/srihash.org/issues/152.

**Comment by jdalton** [comment]
It looks like [got](https://www.npmjs.com/package/got) avoids the issue:
```js
var got = require('got');

got('https://cdn.jsdelivr.net/g/fuse@2.5.0,immutable.js@3.8.1,react@15.3.2(react.min.js+react-dom.min.js)')
  .then(response => console.log(response.body.endsWith('\n')));
```

**Comment by mscdex** [comment]
FWIW I just downloaded the body using curl and when inspecting the resulting file it still ends on `\r\n\r`, so it doesn't seem to be a node/`request` issue?

**Comment by jdalton** [comment]
@mscdex 
See the repro in my first comment and the other repros of it working with other libs.

**Comment by mscdex** [comment]
The reason for the difference is that the server is truncating the last `\n` for non-gzipped/deflated responses. cURL, `request`, and `https` do not send `accept-encoding: gzip,deflate` by default.

**Comment by jdalton** [comment]
Thanks for digging into it @mscdex!

While it couldn't hurt to post an issue to jsdeliver, and I will, it may still be something for `request` to tackle since it worked seamlessly with the other packages.

**Comment by mscdex** [comment]
Well, you can already set `gzip: true` in options passed to `request`.

**Comment by jdalton** [comment]
Since others handle it seamlessly and it means downloading less maybe the default setting should be revisited.
