### ISSUE TITLE
Hawk Dependency Vulnerability - Regular Expression Denial of Service 

### ISSUE THREAD

**Issue by krzyszt** [request/request#2436]
Is there  a chance to update hawk dependency to version 4.1.1 or greater?

Specifically crafted long headers or uris can cause a minor denial of service when using hawk versions less than 4.1.1. as per

https://nodesecurity.io/advisories/77

**Comment by simov** [comment]
3.1.3 that we are using is patched:

```
Patched: >=3.1.3 < 4.0.0 || >=4.1.1
```

**Comment by wtgtybhertgeghgtwtg** [comment]
Now that `request` [only supports `node >= 4`](https://github.com/request/request/commit/01aefdd87cdd9cc44af6828c55fe5ef9c7e205d7), can `hawk` be updated?

**Comment by sahas-** [comment]
Can we get this upgraded pls?

<img width="670" alt="screen shot 2017-01-18 at 8 27 33 pm" src="https://cloud.githubusercontent.com/assets/10361685/22091517/c764669a-ddbc-11e6-9e19-0f1f3d99db53.png">
