### ISSUE TITLE
request.get always ECONNRESET on windows

### ISSUE THREAD

**Issue by Qquanwei** [request/request#2449]
request version: 2.8.0
system: windows10
node: v6.1.0

my code 
```
const request = require("request");
const fs = require("fs");

request.get("http://10.8.8.8/example.exe").pipe(fs.createWriteStream("./example.exe")).on("finish",function(){
   console.log("done");
}).on("error",console.log);
```

this example.exe download but not completed. download interrupted when throw ECONNREST

**Comment by Qquanwei** [comment]
![image](https://cloud.githubusercontent.com/assets/9263655/19993696/8b26308e-a282-11e6-8a60-6cfbc635d2ac.png)

**Comment by Qquanwei** [comment]
![image](https://cloud.githubusercontent.com/assets/9263655/19993715/a9997aa8-a282-11e6-8e93-68d37cd02f2e.png)

**Comment by mrosenberg** [comment]
I'm getting a similar error on an Ubuntu 14.04.5 LTS VM running on Virtual Box.
Node 4.3.0
Request v2.78.0
```
Error: read ECONNRESET
    at exports._errnoException (util.js:870:11)
    at TLSWrap.onread (net.js:544:26)
```

Debug shows the proper response and all looks like it should work but ECONNRESET is still being triggered.

**Comment by mrosenberg** [comment]
I was able to fix this issue this afternoon.

`    require( 'https' ).globalAgent.keepAlive = true;
`

**Comment by Qquanwei** [comment]
great , thanks

**Comment by sunyoboy** [comment]
var hostHeaderName = self.originalHostHeaderName || 'host’
self.setHeader(hostHeaderName, self.uri.hostname)
	改为
	    var hostHeaderName = self.originalHostHeaderName || 'Host’
self.setHeader(hostHeaderName, self.uri.hostname)
