### ISSUE TITLE
Problem with caching

### ISSUE THREAD

**Issue by richizo** [request/request#2451]
I'm currently facing with a problem between callings of my method:
```
function mymethod() {
  var request = require("request");
  var req = request.defaults({jar: true});
  ...
}
```
I would like that every new call, a totally new request was made.

I guess there is not a manner to create a new *Request* object to avoid caching. So I'm using the following technique to solve the problem (using [decache](https://github.com/dwyl/decache/) module):

```
function mymethod() {
  // avoid caching of required data
  decache("request");

  var request = require("request");
  var req = request.defaults({jar: true});
  ...
}
```

I think using object orientation could solve that problem. Something like:

```
  var Request = require("request");
  var req = new Request();
  req.post();
  ...
```

**Comment by ZJONSSON** [comment]
To create a completely separate session for each request, just instantiate a new cookie jar each time, i.e.:

```js
function mymethod() {
  var request = require('request');
  var jar = request.jar();
  var req = request({ jar: jar, url: 'https://...'})
```

**Comment by richizo** [comment]
Great, @ZJONSSON! It works! Thanks!
