### ISSUE TITLE
307 Redirect should clear authorization headers

### ISSUE THREAD

**Issue by ryanmurakami** [request/request#2455]
It looks like there is code specifically excluding 307 redirects from removing authorization headers. The current behavior of curl is to remove the authentication headers on 307, so it seems like this behavior should match and the 307 exclusion removed. 

https://github.com/request/request/blob/master/lib/redirect.js#L128

Does anyone know why `request` is excluding 307's from this behavior?

I can submit a PR to fix this if this is in error or no longer needed.

**Comment by Awnage** [comment]
Sorry to resurrect an old unresolved ticket, but I am curious as well. It would have seemed that ticket #450 would have caught this, but instead code was committed that specifically ignored header 307. A new ticket #2606 seems to share a similar concern, but at least making it optional. Does anyone know

> Does anyone know why `request` is excluding 307's from this behavior?

**Comment by Awnage** [comment]
My solution to this was to modify the headers
```
    options.followRedirect = (res) => {
      //request library can't properly handle 307 to aws so lets trick the library
      if (res.statusCode===307 && res.headers.location.indexOf('amazonaws')>0){
        res.statusCode=303;
      }
      return true;
    }
   //...
   request.get(options)
```
Not satisfying, but it works.
