### ISSUE TITLE
provide a way to cap the size of the response?

### ISSUE THREAD

**Issue by fantasticsid** [request/request#2470]
It would be great if there's a way to cap the size of HTTP response.

I'm using https://github.com/jshemas/openGraphScraper for scraping open graph tags which uses request, however if the HTTP response is large (think of hundred megabytes of binary file), then it downloads the whole file only to realize that is can not parse the result.

If there's a limit on the response then it would solve the problem.

Thanks!

**Comment by Cactusbone** [comment]
you can use stream mode, listen to `response` event, check size header (if present), then use `data` and `end` event to build buffer yourself, and stops when it's too big

**Comment by nwhatt** [comment]
It would be much easier to implement across an application that uses the `defaults` wrapper if it was baked into Request. In the interest of simplicity, all a developer really cares about is how big the response should be allowed to get. 

It looks like in the past people have hit node string limitations with large responses: 
https://github.com/request/request/issues/2067
https://github.com/nodejs/node/issues/3175

Some ideas: 
1. Intelligent default to prevent hitting a node buffer limit (or maybe not, seems easy enough to debug)  
1. Don't prevent people from using stream mode to handle massive responses 
1. Allow a simple "Max Size" property to passed to the options

**Comment by josephrocca** [comment]
This would be useful for me too. I'm not sure on the internals of `request` but if there's a simple way to implement an option which allows users to cap response size (return error if greater than some size), that'd be very handy.

**Comment by nwhatt** [comment]
This is how I implement a length check today: 

```js
  onDataLengthCheck: function (limit) {
    var bufferLength = 0;
    return function (chunk) {
      bufferLength += chunk.length;
      if (bufferLength > limit) {
        this.abort();
        var error = new Error(`Response was too large - aborted after ${limit} bytes.`);
        this.emit('error', error);
      }
    };
  }

request.post(...).on('data', onDataLengthCheck(10000));
```

**Comment by josephrocca** [comment]
Thanks! Yours is much cleaner than mine:

```
function getFile(url, callback) {
  let output = "";
  let tooBig = false;
  let r = request.get(url)
    .on('error', callback)
    .on('data', function(chunk) {
      if(output.length > 1000000) {
        tooBig = true;
        r.abort();
      } else {
        output += chunk.toString("utf8");
      }
    })
    .on('end', function() {
      if(tooBig) {
        console.log(`${url} was too big`);
        callback("too big", null);
      } else {
        console.log(`${url} download complete`);
        callback(null, output);
      }
    })
}
```
