### ISSUE TITLE
never get callback in some request

### ISSUE THREAD

**Issue by mike442144** [request/request#2475]
I have about 10 million requests in a project, but I could never get response for some request.Here is my code: 

```
let options = {timeout:15000,encoding:null,gzip:true,time:true,headers:{}};
options.uri = "xxxxx";
options.proxy="xxxxxx";
debug("Requesting: %s", options.uri);
request(options, (err,res) => {
    debug("Requested: %s", options.uri);
    if(err) 
	return reject(err);

    resolve();
});
```
I simplify the code for guys to better understand, let's call n("string") as "number of string" in log, then the problem is n("Requesting")>n("Requested")

What's your advice?

**Comment by mike442144** [comment]
In case of misunderstanding, for instance, I have called request(), say 1k times, but got 9997 responses. Does anybody have same problem?

**Comment by derekseymour** [comment]
Same thing with us on the latest release.

**Comment by mike442144** [comment]
@derekseymour Hi, do you use proxy in your code? I'm not sure if it is a proxy issue.

**Comment by mike442144** [comment]
@derekseymour I've found the problem, it is a bug in tunnel-agent, I'm now working on it. I'll tell you if done.

**Comment by Kegsay** [comment]
I have also noticed this, I'm running 2.75.0

Server-side logs show that a 200 OK response is indeed being sent back, but nothing is logged in the client application. The first thing the client does is log the response, so I'm fairly confident this isn't an application fail on my end. These requests are typically quick (load balancer logs suggest it took 33ms to from recv req -> fully send response) so I don't think timeouts are being hit. The one noticeable point here is that I sent 2 requests at virtually the same time: so I'm wondering if `request` has a race condition which can cause the callback to never be invoked.

Sadly, this is a spectacular failure mode and has serious consequences for us, as we queue up requests and rely on requests either succeeding/failing/timing out in request. I can no longer trust `request` to do this now.

**Comment by mike442144** [comment]
@Kegsay I have this kind of problem only in the scenario of using proxy. There is no race condition for concurrent because in `request` all requests are sent and an Agent will handle the queue if `maxSocket` isn't infinite. In default http.Agent, maxSocket is infinite, so if you use the default one which means you do not specify the agent option or using proxy, all the requests will be sent. 

What I wonder is the timeout feature so I read the source code about timeout and found nothing incorrect. Timeout event would have happened on socket regardless of HTTP error in theory. Do you have any idea? @mscdex @simov

**Comment by mscdex** [comment]
@mike442144 I don't know anything about the proxy support.

**Comment by mike442144** [comment]
@mscdex @simov @koichik Okay, I check the test cases, and in timeout cases, there is no timeout case about proxy or tunnel-agent. Should we add cases to cover it?

**Comment by Kegsay** [comment]
@mike442144 `request` won't fire timeouts if it thinks the request succeeded. I suspect that `request` got the response and then for some reason decided not to invoke the callback. I speculate it's a race condition due to the fact that I sent 2 and the responses according to load balancer logs were transmitted at the same millisecond.

**Comment by mike442144** [comment]
@Kegsay Maybe you are right, I'll continue checking.

**Comment by dish615** [comment]
any progress on this? I'm having the same issue with particular websites I'm making a get request to.

**Comment by mike442144** [comment]
@dish615 Do you use proxy?

**Comment by mike442144** [comment]
I've found the bug, it is in tunnel-agent. So if you are using proxy and your target website protocol is https, you would have the same problem. Below is the detail of the bug:

1. TCP connection established from client, which is your process, to the proxy server. TCP status is `ESTABLISHED` and the **socket** fireup a 'connect' event.
2. Client send a http request whose method is `CONNECT` to proxy server, but **never got a response**

According to the nodejs manual, a tcp socket connection will be timed out before established by the operating system, but a http request never.So when you call reuqest() in request.js with proxy, request.js got a socket only tunnel-agent have a http connection with proxy. See the code below:

```javascript
// in tunnel-agent.js
connectReq.once('connect', onConnect)
//...
function onConnect(){
    pending.request.onSocket(socket) // pending.request is an instance of ClientRequest
}

// in _http_client.js
function onSocket(socket){
    req.emit('socket',socket); // request.js got the 'socket' event.
}

// in request.js
self.req.on('socket', function(socket) {
    var setReqTimeout = function() {
        self.req.setTimeout(timeout, function () {
        if (self.req) {
          self.abort()
          var e = new Error('ESOCKETTIMEDOUT')
          e.code = 'ESOCKETTIMEDOUT'
          e.connect = false
          self.emit('error', e)
        }
      })
    }
}
```

If tunnel-agent could not get a response for a 'connect' request, obviously request.js cannot get the `socket` event, which resulted in no timeout timer set to the underlying socket. That's the root cause, it is deep but solution is quite simple:

```javascript
connectReq.setTimeout(options.timeout || 15000, function(){
    connectReq.abort();
});
```

That's all. I'll open a PR to the tunnel-agent.js.
@simov

**Comment by mike442144** [comment]
@simov What are you going to do?

**Comment by lneveu** [comment]
Same issue here! Thanks @mike442144 for your PR 👍

**Comment by mike442144** [comment]
@lneveu You're welcome.

**Comment by yodeyer** [comment]
Hello,

Any news concerning this issue? 
We have the same issue in production (socket not being closed), and I would prefer not to use a fork.
Is there anything we can do to help ?

**Comment by mike442144** [comment]
@yodeyer pls refer to #2440

**Comment by mike442144** [comment]
not resolved, let's keep it open. refer to #2440 for more details.
