### ISSUE TITLE
How to nock with proxy?

### ISSUE THREAD

**Issue by slota** [request/request#2476]
This is more of a question, I'm not sure if this has been solved.

I was unable to get nock to work when on a proxy... I tried using the NO_PROXY on the environmental variables and this did not work. I finally got it working by setting     
```
process.env = ""
```
Is there a better way to get this working?
Thank you

**Comment by rickschubert** [comment]
Hi @slota ! I created a package called [nock-proxy](https://github.com/rickschubert/nock-proxy) which does just that. With this simple proxy server you can mock network requests "in real life", i.e. for web browsing like in end-to-end tests or other scenarios.
