### ISSUE TITLE
Very large response bodies

### ISSUE THREAD

**Issue by nodesocket** [request/request#2479]
How are very large response bodies handled? A response body that is 50 megabytes, does it fill up 50 megabytes of memory each request? Is there anyway to limit the response body size in `request` _(i.e. return an error after a given body size is exceeded)_?

Is it possible to discard the response body *(pipe to /dev/null equivalent)*. I.E. only care about response headers and response status code.

**Comment by mmalecki** [comment]
@nodesocket 
> How are very large response bodies handled? A response body that is 50 megabytes, does it fill up 50 megabytes of memory each request?

Long story short, large response bodies are handled in the same way any response body is - if you provide a callback, whole request body is stuck into a `Buffer` object. In that case, if a response body is 50 MB, that buffer will take up 50 MB of memory. You can, however, use streams to avoid allocating a huge buffer at once: `request('http://example.com').pipe(fs.createWriteStream('foo'))`.


> Is there anyway to limit the response body size in request (i.e. return an error after a given body size is exceeded)?

I don't believe `request` supports that as is, but you might want to look into the [`Range` header](https://tools.ietf.org/html/rfc7233) and/or writing a writable stream that throws/rejects any further bytes if certain length is exceeded.

> Is it possible to discard the response body (pipe to /dev/null equivalent). I.E. only care about response headers and response status code.

I think the [`ReadableStream#resume` method](https://nodejs.org/dist/latest-v6.x/docs/api/stream.html#stream_readable_resume) should do it: `request('http://example.com').resume()`.

I'll close this issue, but feel free to ask further questions here!

**Comment by nodesocket** [comment]
Can you provide an example of discarding the respons body *(like piping to /dev/null)* using `.resume()`? I'm not following. Assume I currently have:

````javascript
request(params, (error, response) => {
    if(error) {
        console.error(error);
    }

    console.log(response);
});
````

**Comment by mmalecki** [comment]
@nodesocket sure, it's just `request('http://foo.com').resume()` (without the `(err, res)` callback - otherwise the body will be buffered).

**Comment by mmalecki** [comment]
(Then, for errors, provide a `error` listener:

```js
request('http://foo.com')
  .on('error', err => console.error(err))
  .resume()
```
)

**Comment by nodesocket** [comment]
Thanks, one more question. How then do I get the response headers and statusCode?

**Comment by mmalecki** [comment]
@nodesocket oh, heh, sorry about that, haven't had enough :coffee: today! You could:

```js
request('http://foo.com')
  .on('error', err => console.error(err))
  .on('response', res => {
    console.log(res.statusCode, res.headers)
    res.resume()
  })
```

**Comment by nodesocket** [comment]
One last question, using this method and passing in `time: true`, I noticed that the property `elapsedTime` is not returned in `res`. Is it possible to get timing without the body?

**Comment by nodesocket** [comment]
@mmalecki any ideas if `time: true` should work if using:

````
request({
    uri: 'http://foo.com',
    time: true
})
  .on('error', (err) => console.error(err))
  .on('response', (res) => {
    console.log(res.statusCode, res.headers, res.elapsedTime);
    res.resume();
  });
````

**Comment by nodesocket** [comment]
@mmalecki sorry to resurrect an issue from the dead, but using:

```javascript
request({ uri: 'http://foo.com' })
    .on('error', (error) => {
        // error handling here
    })
    .on('response', (response) => {
        console.log(response.statusCode);
        response. resume();
    });
```

What is the purpose of `response.resume()`? Should I be using `response.destroy()` instead?
