### ISSUE TITLE
Fix Deprecation warning

### ISSUE THREAD

**Issue by MichaelTSS** [request/request#2493]
Hello,

I've noticed a WARN message when installing dependencies of this module
`npm WARN deprecated node-uuid@1.4.7: use uuid module instead`

Thanks for the great work!

Michael

**Comment by dege88** [comment]
Should be fixed in https://github.com/request/request/pull/2467

**Comment by revelt** [comment]
#2467 didn't fix that

**Comment by revelt** [comment]
This issue can be closed, `node-uuid` is not in `package.json` anymore.

**Comment by manico** [comment]
Does anyone get uuid is not a function from request lib?
I'm using uuid in my project also, and request cannot seem to work when this is the case.
