### ISSUE TITLE
the length of  request body is larger then content-length 

### ISSUE THREAD

**Issue by godissp** [request/request#2498]
when  i use request to transmit a post request，the content-length in origin header is 2007，but the body‘s length transformed by request module is 2410. as a result , the content of body has been cutted off.i think the content-length should be reseted.
`
Request.prototype.form = function (form) {
  var self = this
  if (form) {
    if (!/^application\/x-www-form-urlencoded\b/.test(self.getHeader('content-type'))) {
      self.setHeader('content-type', 'application/x-www-form-urlencoded')
    }
    self.body = (typeof form === 'string')
      ? self._qs.rfc3986(form.toString('utf8'))
      : self._qs.stringify(form).toString('utf8')
    //i think the content-length should be reseted
    self.headers['content-length'] = self.body.length
    return self
  }
  // create form-data object
  self._form = new FormData()
  self._form.on('error', function(err) {
    err.message = 'form-data: ' + err.message
    self.emit('error', err)
    self.abort()
  })
  return self._form
}
`

**Comment by ChronSyn** [comment]
Can you provide an example of what the content looks like before you pass it off to Request, and what it looks like after being passed through Request and if possible, what code you're using to make the request.
