### ISSUE TITLE
Support NO_PROXY wildcards

### ISSUE THREAD

**Issue by jd-carroll** [request/request#2500]
We have a full external proxy, but all internal traffic is handled separately and does not need a proxy.

The current implementation requires all subdomains to be listed in the `process.env.NO_PROXY`:
```
            "env": {
                "NODE_DEBUG": "request http",
                "HTTP_PROXY": "http://proxy.company.com:8080",
                "HTTPS_PROXY": "http://proxy.company.com:8080",
                "NO_PROXY": "subdomain-1.company.com,subdomain-2.company.com,..."
            },
```

Ideally it would be nice to allow wildcards in the `NO_PROXY` configuration to allow something simpler, such as:
```
            "env": {
                "NODE_DEBUG": "request http",
                "HTTP_PROXY": "http://proxy.company.com:8080",
                "HTTPS_PROXY": "http://proxy.company.com:8080",
                "NO_PROXY": "*.company.com"
            },
```

I think the implementation would be relatively straight forward and would only require changes to how the [hostname is matched against the noProxyZones](https://github.com/request/request/blob/master/lib/getProxyFromURI.js#L26)

If people are open to this idea, I can put together a PR...

**Comment by jd-carroll** [comment]
Figured out that this functionality is supported.

Instead of having this:
```
"NO_PROXY": "*.example.com,localhost"
```
Just do this:
```
"NO_PROXY": ".example.com,localhost"
```

**Comment by lstrawth** [comment]
what if we want to do something like "web-*.example.com" or "*web.example.com"?

we are hitting a number of issues where we need that
