### ISSUE TITLE
Make HTTPS call from request module

### ISSUE THREAD

**Issue by tomalex0** [request/request#2505]
I'm trying to make `https` call using `request` module, below is current  existing options
and i have `pfx` file and `password`.

```
strictSSL: false,
rejectUnauthorized: false,
agent: false
```

Can somebody help me out  about what all need to be set as true and  do i need to export `cert` files.

If possible please share `openssl`  command for this.

I tried exporting `cert` and made `strictSSL and rejectUnauthorized true`, but end up seeing  error like 

` message: 'Error: unable to verify the first certificate'`

Node Version is  `6.9.2`

**Comment by rpgeeganage** [comment]
Did you try by setting
`process.env['NODE_TLS_REJECT_UNAUTHORIZED'] = '0'`

**Comment by tomalex0** [comment]
@rpgeeganage  this is not a preferred way.

Full error stack
```
{ Error: unable to verify the first certificate
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:1085:38)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:185:7)
    at TLSSocket._finishInit (_tls_wrap.js:603:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:433:38) code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE' } 'error'

```

**Comment by Tynael** [comment]
I have encountered this issue too. Did you find a workaround @tomalex0 ?

**Comment by turnerniles** [comment]
Any update on this?

**Comment by CMorton737** [comment]
I have come across this issue as well.

**Comment by CMorton737** [comment]
For a workaround, disable the requirement that SSL certificates must be valid and bypass altogether. Add "strictSSL: false" as such:
```
{  
   url: "",
   method: "POST",
   headers: {
        "Content-Type": "application/json"},
   json: {},
   strictSSL: false
}
```

**Comment by KamyarGhajar** [comment]
My server is in a private network (no Internet access) and it should work there and I signed the certificate and trust it with own CA...I get the `UNABLE_TO_VERIFY_LEAF_SIGNATURE` error even when I add the ca.pem file to the options.agentOptions.ca. What should I do to fix this error obviously without disabling the strictSSL option or any other unsafe options?

**Comment by jacksongabbard** [comment]
In my case, an SSL certificate I generated with LetsEncrypt works fine with node https library or with the request library. However, using the same cert off port 443 (which works fine from the Golang components of my system and works fine in Chrome) completely chokes Node's https library and the request library, both with the same error. I'm still trying to understand what's going wrong here, but for at least this case, these root CA hacks seem not to work.

**Comment by AdrianDroid** [comment]
no one to follow so close it and pretend it never happen ?

**Comment by mayankrajchauhan** [comment]
I was getting same error. Fixed by marking strictSSL as false, below code worked for me.
var client = new RestClient({
        connection: {
            pfx: fs.readFileSync(certFile),
            passphrase: certPassword,
            strictSSL: false,
            rejectUnauthorized: false,
            agent: false
        }
    });

I am using node rest client architecture for my API.

Hope this might help anyone looking for similar fix

**Comment by sunnysharma03** [comment]
Try this:
var request = require("request").defaults({rejectUnauthorized:false});
