### ISSUE TITLE
is it possible to read response body or status of errored request

### ISSUE THREAD

**Issue by r3wt** [request/request#2506]
My api returns status 400 for missing required fields, 403 for login failure. i need to read either the response body, which is json containing status code and error message, or retrieve the status code if that is not possible. i couldn't find any info about it in the documentation.

**Comment by umutm** [comment]
You can get the body or HTTP status with a simple request:

```
request({url: url}, function (error, response, body) {
   console.log(body);
   console.log(response.statusCode);
});
```
