### ISSUE TITLE
Multiple request to the same url if not timeout specified and the server takes a bit

### ISSUE THREAD

**Issue by elioscordo** [request/request#2507]
Hi, thanks for the lib.
Looks like a proxy developed with this lib triggers multiple requests to the same url when the server hangs.

With the timeout specified it is impossible to produce the bug.
Is this possible?
thanks!

**Comment by and1gio** [comment]
I have same problem.

**I made test..**
* set delay to server response
* sent request to that server using nodejs / request **(only 1 request)**

**result: server got 2 requests**
* first one - instantly
* second one - after some time
