### ISSUE TITLE
Error: connect ETIMEDOUT 202.x.x.x:80

### ISSUE THREAD

**Issue by xang555** [request/request#2511]
hi everyone please help me understand this error and fix it

when i used  requestjs   Request to web site http:// www.example.com . i had response like this : 

```
{ Error: connect ETIMEDOUT 202.x.x.x:80
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1087:14)
  code: 'ETIMEDOUT',
  errno: 'ETIMEDOUT',
  syscall: 'connect',
  address: '202.x.x.x',
  port: 80 }

```
but when i go to website in the browser it is work! but  must wait  few minutes

why and how to do that ?

thank you.

**Comment by csvan** [comment]
Having the same issue - request does not seem to honor browser proxy settings.
