### ISSUE TITLE
Encoding problem

### ISSUE THREAD

**Issue by Glutch** [request/request#2516]
Trying to send formData as ISO-8859-1

```
const options = {
  url: 'http://hello.com',
  encoding: 'ISO-8859-1',
  formData: {}
```

Getting `throw new Error('Unknown encoding: ${enc}');`

Is ISO-8859-1 not supported? Is there anything i can do?

**Comment by dege88** [comment]
https://stackoverflow.com/questions/14551608/list-of-encodings-that-node-js-supports
