### ISSUE TITLE
Request with #

### ISSUE THREAD

**Issue by TonySchu** [request/request#2519]
Hi,

is it possible to make a GET request with an URL like this? 
`var url = "https://www.google.de/#q=npm+request"`
Because of the "#" I will be always redirected to the root.

**Comment by georoot** [comment]
not exactly, The reson is the what comes after `#` is parsed in the browser and never reaches the server. If you really want to add your query like `https://www.google.de/#q=npm+request` you would have to use javascript to get the parameter and make an ajax call to server.

**Comment by Yaseenahmed402** [comment]
try to encode # like this %23

**Comment by TonySchu** [comment]
I tried, but this is not working.
Is it working for you?

**Comment by tommymcdonald** [comment]
@TonySchu Have you tried changing the query to "https://www.google.de/search?q=npm+request"? Here is an article that explains how google makes search queries from their homepage: https://news.ycombinator.com/item?id=13354368

**Comment by TonySchu** [comment]
Hi Tommy,
thanks, this is working. But this is just a special solution for google.com, right?
I think this will not work in general, so it may be a good thing for the next update.

**Comment by dege88** [comment]
@TonySchu the parts of the url after # are processed in javascript, request only donload the source of the page, you can process it by hand yourself or you can use a browser simulator library like https://github.com/casperjs/casperjs/ (that use https://github.com/ariya/phantomjs on the background)
