### ISSUE TITLE
empty array element in form being --- changed.

### ISSUE THREAD

**Issue by bingomanatee** [request/request#252]
when I pass the following form into request (put), 

REQUEST form: { name: 'Bob',
  username: 'foo',
  password: 'boo',
  email: 'foo@bar.com',
  roles: [],
  deleted: false }

the request that is returned to express.js is the following. Note that 'roles: []' has been rendered as '': ''

req: { query: {},
  trailers: {},
  connection: 
   { _httpMessage: [Object],
     _connectQueueSize: 0,
     _pendingWriteReqs: 0,
     errorEmitted: false,
     onend: [Object],
     writable: true,
     _events: [Object],
     _idleTimeout: 120000,
     server: [Object],
     readable: true,
     destroyed: false,
     _flags: 0,
     _idlePrev: [Object],
     _idleStart: Fri, 11 May 2012 15:06:40 GMT,
     _handle: [Object],
     ondrain: [Object],
     ondata: [Object],
     _idleNext: [Object],
     bytesWritten: 0,
     bytesRead: 322,
     allowHalfOpen: true },
  upgrade: false,
  body: 
   { '': '',
     deleted: 'false',
     name: 'Bob',
     password: 'boo',
     email: 'foo@bar.com',
     username: 'foo' },
  httpVersionMajor: 1,
  httpVersionMinor: 1,
  params: [ [length]: 0 ],
  _events: { end: [Object], data: [Object] },
  method: 'PUT',
  res: 
   { _headerNames: [Object],
     _hasBody: true,
     connection: [Object],
     writable: true,
     writeHead: [Object],
     _events: [Object],
     useChunkedEncodingByDefault: true,
     _trailer: '',
     chunkedEncoding: false,
     end: [Object],
     shouldKeepAlive: true,
     finished: false,
     outputEncodings: [Object],
     app: [Object],
     _last: false,
     output: [Object],
     req: [Circular],
     _headers: [Object],
     socket: [Object] },
  readable: false,
  session: 
   { lastAccess: 1336748800954,
     cookie: [Object],
     [req]: [Circular],
     [id]: 'WzX8rVqk8FmYcsdgIKgGqvOm./oTwQ1XBj9W+yiaq7I7M7SE+5MAd9rjGuLtk+zKtivQ' },
  complete: true,
  sessionStore: { hash: [Object], sessions: [Object], generate: [Object] },
  _decoder: 
   { charLength: 0,
     charBuffer: <Buffer fd 7f 00 00>,
     encoding: 'utf8',
     charReceived: 0 },
  sessionID: 'WzX8rVqk8FmYcsdgIKgGqvOm./oTwQ1XBj9W+yiaq7I7M7SE+5MAd9rjGuLtk+zKtivQ',
  originalUrl: '/members',
  httpVersion: '1.1',
  cookies: { 'connect.sid': 'WzX8rVqk8FmYcsdgIKgGqvOm./oTwQ1XBj9W+yiaq7I7M7SE+5MAd9rjGuLtk+zKtivQ' },
  headers: 
   { connection: 'keep-alive',
     cookie: 'connect.sid=WzX8rVqk8FmYcsdgIKgGqvOm.%2FoTwQ1XBj9W%2Byiaq7I7M7SE%2B5MAd9rjGuLtk%2BzKtivQ',
     host: 'localhost:3001',
     'content-length': '69',
     'content-type': 'application/x-www-form-urlencoded; charset=utf-8' },
  next: 
   { [Function: next]
     [length]: 1,
     [name]: 'next',
     [arguments]: [Object],
     [prototype]: [Object],
     [caller]: [Object] },
  _route_index: 0,
  app: 
   { router: [Getter],
     _events: [Object],
     _handle: [Object],
     routes: [Object],
     errorHandlers: [Object],
     route: '/',
     allowHalfOpen: true,
     _locals: [Object],
     dynamicViewHelpers: {},
     redirects: {},
     httpAllowHalfOpen: false,
     settings: [Object],
     connections: 1,
     stack: [Object],
     __usedRouter: true,
     isCallbacks: {},
     cache: {} },
  client: 
   { _httpMessage: [Object],
     _connectQueueSize: 0,
     _pendingWriteReqs: 0,
     errorEmitted: false,
     onend: [Object],
     writable: true,
     _events: [Object],
     _idleTimeout: 120000,
     server: [Object],
     readable: true,
     destroyed: false,
     _flags: 0,
     _idlePrev: [Object],
     _idleStart: Fri, 11 May 2012 15:06:40 GMT,
     _handle: [Object],
     ondrain: [Object],
     ondata: [Object],
     _idleNext: [Object],
     bytesWritten: 0,
     bytesRead: 322,
     allowHalfOpen: true },
  statusCode: null,
  url: '/members',
  route: 
   { regexp: /^\/members\/?$/i,
     callbacks: [Object],
     params: [Object],
     method: 'put',
     keys: [Object],
     path: '/members' },
  socket: 
   { _httpMessage: [Object],
     _connectQueueSize: 0,
     _pendingWriteReqs: 0,
     errorEmitted: false,
     onend: [Object],
     writable: true,
     _events: [Object],
     _idleTimeout: 120000,
     server: [Object],
     readable: true,
     destroyed: false,
     _flags: 0,
     _idlePrev: [Object],
     _idleStart: Fri, 11 May 2012 15:06:40 GMT,
     _handle: [Object],
     ondrain: [Object],
     ondata: [Object],
     _idleNext: [Object],
     bytesWritten: 0,
     bytesRead: 322,
     allowHalfOpen: true } }

**Comment by 2blane** [comment]
There is a solution to this, you just probably can't use url-form-encoded.
Related: #2740
