### ISSUE TITLE
QUESTION: How can i use only pipe method from request instead of retrieving all content of response?

### ISSUE THREAD

**Issue by voxsoftware** [request/request#2520]
I want pipe a request of 3GB to my server response, without retrieving all content.
How can i use only pipe method from request instead of retrieving all content of response?

**Comment by pixtron** [comment]
make sure you don't supply a callback, else the request body will be buffered. If content-length is > 256MB you will run into https://github.com/nodejs/node/issues/3175 as soon as the request ends.

Without callback you can handle the error and complete events like this:
```
var req = request({
  uri: 'https://example.org/your3gigfile',
  method: 'GET',
  qs: {}
});

req.on('error', function(err) {
});

req.on('complete', function(response) {
});

req.pipe(res);
```

**Comment by FredKSchott** [comment]
@pixtron thanks for answering!
