### ISSUE TITLE
[Timeouts] err.connect is undefined. How to detect timeout type?

### ISSUE THREAD

**Issue by wzup** [request/request#2521]
> you can detect whether the timeout was a connection timeout by checking if the err.connect property is set to true

 [here](https://github.com/request/request#timeouts)

![etimedout - google chrome 2017-01-24 12 04 07](https://cloud.githubusercontent.com/assets/3880497/22233742/6f26d2c2-e22d-11e6-8676-fbee4c94314f.png)

But I don't have `err.connect` prop im my error object. It is `undefined`:

![etimedout - 2017-01-24 12 12 39](https://cloud.githubusercontent.com/assets/3880497/22233860/886b8966-e22e-11e6-8fac-677ee5d79d86.png)

How to detect timeout type?

**Comment by stevieoj** [comment]
forcing a timeout error with the code below

request.get('https://github.com', {timeout: 00001}, (err, res, body) => {
    console.log(JSON.stringify({Error: err}));
    console.log(body);
});

The error object properties well defines how timeout error types can be distinguished

{"Error":{"code":"ETIMEDOUT","connect":true}}

**Comment by shraddha1704** [comment]
err.connect returns a boolean value when you send a "timeout" property in request options.
