### ISSUE TITLE
How to Detect Valid http link?

### ISSUE THREAD

**Issue by Ryu945** [request/request#2525]
How to detect valid http link?

Enter something like ``...`` crashes the module.

**Comment by rtezera1** [comment]
That weird! I tried entering `...`, but it didn't crash the module, rather it threw an error `[Error: Invalid URI "..."]`. You can use a regex like `/^(https?:\/\/)?([\da-z\.-]+)\.([a-z\.]{2,6})([\/\w \.-]*)*\/?$/` to validate a url, if you want to filter out the input right off the bat.
