### ISSUE TITLE
Removal of Authorization header on redirects

### ISSUE THREAD

**Issue by dkundel** [request/request#2527]
Hi everyone!

It appears like that the change that was pushed in #1184 isn't part of the code base anymore? I'm having trouble with some code that fails because of the forwarding of the header. 

Is there a reason why this has been removed?

Cheers,
Dominik

**Comment by FredKSchott** [comment]
The tests that were added to cover this behavior are still passing, can you include a failing test or reproduction case that we can run to reproduce?
