### ISSUE TITLE
PKCS #12 certificate throws handshake failure error

### ISSUE THREAD

**Issue by li0nsar3c00l** [request/request#2528]
I exported a PKCS 12 certificate from firefox and wanted to use it in my nodejs application. In my browser everything is working fine. Error message is the following:

> { Error: write EPROTO 101057795:error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure:openssl\ssl\s3_pkt.c:1487:SSL alert number 40
> 101057795:error:1409E0E5:SSL routines:ssl3_write_bytes:ssl handshake failure:openssl\ssl\s3_pkt.c:656:
>     at exports._errnoException (util.js:1022:11)
>     at WriteWrap.afterWrite [as oncomplete] (net.js:804:14) code: 'EPROTO', errno: 'EPROTO', syscall: 'write' }

I'm using the following code, proxy is the same as in firefox as well.
```
function test() {
var request = require('request');
    var path = require('path');
    var fs = require('fs');

    var pfxFilePath = path.resolve(__dirname, '../ssl/' + F.config['cert']);
    var prox = F.config.proxy;
    var pass = F.config['cert.password'];

    var options = {
        url: baseurl,
        headers: {
            'User-Agent': 'request',
        },
        proxy: prox,
        agentOptions: {
            //cert: fs.readFileSync(certFile),
            //key: fs.readFileSync(keyFile),

            // Or use `pfx` property replacing `cert` and `key` when using private key, certificate and CA certs in PFX or PKCS12 format:
            pfx: fs.readFileSync(pfxFilePath),
            passphrase: pass,
            ciphers: "ALL",
            requestCert: true,
        }
    };

    function callback(error, response, body) {
        if (!error && response.statusCode == 200) {
            var info = JSON.parse(body);
            console.log(info.datecreated + " created");
            self.view("view", body);
        }
        else {
            console.log(error);
        }
    }

    request(options, callback);
}
```

**Comment by li0nsar3c00l** [comment]
as soon as you move pfx and passphrase properties to options, instead of agentOptions, its working! I guess this is something, that should be fixed or at least have the docs updated.

**Comment by mossblaser** [comment]
I can confirm this is also the case for the 'key' and 'cert' options. If these are placed in `agentOptions` they are ignored. If placed in the main options dictionary, things work.

Is this a bug in the implementation or in the documentation? (i.e. should I expect a future version of requests to break if I put the key/cert options in the top-level object?
