### ISSUE TITLE
SSL: socket hang up at TLSSocket.onHangUp with ECONNRESET code

### ISSUE THREAD

**Issue by mayagithub87** [request/request#2529]
Hi everyone I'm using last version of every module I use in nodejs, when I was putting https to serve with a self signed certificate and the options
   `requestCert: true,
    rejectUnauthorized: true` 
weren't there it worked all fine. But when I generate a CA, server and client keys and certificates and put the options above it all crashed with the error socket hang up at TLSSocket.onHangUp with ECONNRESET code.
Here is the code I'm using:
Server
`
var options = {
    key: fs.readFileSync('./trusted/last/server-key.pem'),
    cert: fs.readFileSync('./trusted/last/server-crt.pem'),
    ca: fs.readFileSync('./trusted/last/ca-crt.pem'),
    requestCert: true,
    rejectUnauthorized: true
};

var server = https.createServer(options, app);
server.listen(port);
server.on('error', onError);
server.on('listening', onListening);
`
Client
`
request({
            url: config.t2vserver + '/oauth/token',
            method: 'POST',
            headers: {
                'Content-Type': 'application/x-www-form-urlencoded'
                //,'Connection': 'keep-alive'
            },
            auth: {
                user: config.clientName,
                pass: config.clientApiKey
            },
            body: 'grant_type=client_credentials'
            , key: fs.readFileSync('./trusted/client1-key.pem'),
            cert: fs.readFileSync('./trusted/client1-crt.pem'),
            ca: fs.readFileSync('./trusted/ca-crt.pem')
            //, gzip: true
            ,timeout: 60000
        }, function (error, response, body) {
            if (body) {
                var json = JSON.parse(body);
                console.log("Access Token:", json.access_token);
                token = json.access_token;
                request({
                    headers: {
                        'Content-Type': 'application/json'
                    },
                    url: config.t2vserver + '/v1/access',
                    method: 'POST',
                    auth: {
                        'bearer': token
                    },
                    body: '{"token": "' + token + '", "service":"' + config.services + '"}'
                }, function (error, response, body) {
                    console.log(body);
                    res.send(body);
                });
            } else {
                console.log(error);
                res.send(error.message);
            }
        });
`
Hope you could help me please.

**Comment by dogancelik** [comment]
Related: #1934
