### ISSUE TITLE
Getting Specific part of body

### ISSUE THREAD

**Issue by sameernerd** [request/request#2530]
How to get access to specific element in the whole html returned by body ?

**Comment by dege88** [comment]
You can use regular expressions or tools like https://github.com/cheeriojs/cheerio that provide you with a jquery-like way to access specific parts of DOM

**Comment by sameernerd** [comment]
Thanks dege88.I figured it out but when I am parsing body from the request() method it is not parsing body line by line. Some divs from the page are mixed here and there,
Any Solution for that Sir !?!
