### ISSUE TITLE
Help: AWS Version 2 Signing Example

### ISSUE THREAD

**Issue by tobwiens** [request/request#2531]
Hello,

I just discovered this project and thank you very much! It is a great project! 

I wrote my first get request after 1 minute discovering your project, great! Now I got stuck on AWS signing version 2. 

Maybe one could add an example for better understanding: Here is my code:

```
request({
        url: 'https://mws.amazonservices.com/ListOrders/2017-03-01/\
?AWSAccessKeyId=ACCESSKEYID\
&Action=ListCustomers\
&DateRangeEnd=2017-01-30T00%3A06%3A07.000Z\
&DateRangeStart=2017-01-01T00%3A06%3A07.000Z\
&DateRangeType=AssociatedDate\
&MWSAuthToken=TOKEN\
&MarketplaceId=MKTPLCID\
&SellerId=ID\
&SignatureMethod=HmacSHA256\
&SignatureVersion=2\
&Timestamp=2017-02-08T20%3A10%3A02Z\
&Version=2014-03-01', 
aws: {
  key : '`YOUR_KEY',
  secret: 'YOUR_SECRET'
} 
} , 
function (error, res, body) {
            if (error)
                cb(error);
            else
                cb(null, {
                    status: res.statusCode,
                    length: body.length,
                    latency: Date.now() - start,
                    body: body,
                });
        });
```

AWS RESPONDS: 
Parameter Signature cannot be empty.

I tried with and without:  &SignatureMethod=HmacSHA256 and &SignatureVersion=2 and expected that the SIGNATURE would be added automatically, since it should be generated. 

When I add &Signature and leave it empty, then it obviously still complains that it is empty. I looked through the code and couldn't find answers. 

Thank you so much for your help.

**Comment by FredKSchott** [comment]
If you have a support request or question please submit them to one of this resources:

* StackOverflow: http://stackoverflow.com/questions/tagged/request+node.js using the tags `node.js` & `request`
* Gitter community: https://gitter.im/request/request?utm_source=newissue
* Also have a look at the Readme for more information on how to get support:
  https://github.com/request/request/blob/master/README.md

Issues on GitHub are only related to problems of request itself and we cannot answer
support questions here.
