### ISSUE TITLE
module not find

### ISSUE THREAD

**Issue by sunriseshow** [request/request#2532]
net ,fs, tls  not found

![image](https://cloud.githubusercontent.com/assets/8856011/22768812/6ca15722-eebf-11e6-83a1-bccce15cfb50.png)

why????????

**Comment by crostine** [comment]
it would help the world and yourself if you post a step by step guide to reproduce, or even the context at which this occurs.

**Comment by fabienheureux** [comment]
Maybe dig this issue could help you (I encounter the same on using webpack)
https://github.com/request/request/issues/1529

**Comment by FredKSchott** [comment]
Closing as duplicate of #1529
(If you believe that this isn't a duplicate, please create a new issue with more information.)
