### ISSUE TITLE
How to "overwrite" the redirect_uri

### ISSUE THREAD

**Issue by FabioSilvaBRZ** [request/request#2537]
**Hi, guys.**

I am behind a reverse proxy and I have to alter the `redirect_uri` (for a callback in a OAuth process) so the callback can be done in the proxy's address and port.
**How can I do that?**

**Comment by mikeal** [comment]
You should just disable forwarding so that you get the 3xx response. Then you can read the header, mutate it, and create a new request to the right url.

**Comment by FabioSilvaBRZ** [comment]
hey, thanks for the fast answer, @mikeal 

I am not sure I can do it "easily"...
I am working with a framework I would like not to go "hard coding" around.
Is there a way to do it using parameters???
If yes, where is it?

**Comment by FabioSilvaBRZ** [comment]
Closing the issue: the application had a configuration to address the problem.
Anyway, thanks for the support.
