### ISSUE TITLE
Any plan for the function to profile application remote calls via request.js?

### ISSUE THREAD

**Issue by hypheng** [request/request#2538]
For example, give the rank of max time consumed by remote calls via request.js. Providing uri, counts.

**Comment by mike442144** [comment]
I guess `time` option is what you want.

**Comment by FredKSchott** [comment]
Yup, the `time` option will be merged in the next few days, and will be released in the next release. You can follow along here: https://github.com/request/request/pull/2452

Until then, see `elapsedTime` and `responseStartTime` properties.
