### ISSUE TITLE
Image Resizing

### ISSUE THREAD

**Issue by gregory-h** [request/request#2543]
Social properties have different size limitations for posts, profile photos, profile headers etc. Rather than forcing user to pick images of a specfic size depending on context it may be more convenient to have the infrastructure automatically resize images appropriately for the context. 

Filestack appears to have ability to resize images at upload; not sure if this would accommodate the various scenarios. Atlernatively could create an image resizer lib server side using something like imageMagic, and invoke server side with appropriate scaling parameters based on the context (twitter post, twitter profile edit, facebook post, facebook profile edit etc)

**Comment by FredKSchott** [comment]
If you have a support request or question please submit them to one of this resources:

* StackOverflow: http://stackoverflow.com/questions/tagged/request+node.js using the tags `node.js` & `request`
* Gitter community: https://gitter.im/request/request?utm_source=newissue
* Also have a look at the Readme for more information on how to get support:
  https://github.com/request/request/blob/master/README.md

Issues on GitHub are only related to problems of request itself and we cannot answer
support questions here.
