### ISSUE TITLE
how to optimize speed performance when downloading content from a large set of urls?

### ISSUE THREAD

**Issue by gregorleban** [request/request#2544]
Hi,
I have over 1 million URLs from which I want to repeatedly download content. I'm currently simply calling 
```request(url, ...)``` for each ```url``` that I have and I'm achieving some solid performance (about 5MB/s of downloaded content). Since I'm on 1Gb network I'm wondering what I can do to achieve even better performance. Are there any settings that you would suggest changing from the defaults? From what i've seen, the defaults already set maxSockets = Infinite.
I'm using node 7.5.0. on Windows. Move running this on Linux help?

**Comment by FredKSchott** [comment]
If you have a support request or question please submit them to one of this resources:

* StackOverflow: http://stackoverflow.com/questions/tagged/request+node.js using the tags `node.js` & `request`
* Gitter community: https://gitter.im/request/request?utm_source=newissue
* Also have a look at the Readme for more information on how to get support:
  https://github.com/request/request/blob/master/README.md

Issues on GitHub are only related to problems of request itself and we cannot answer
support questions here.
