### ISSUE TITLE
it always get status 404 in some urls

### ISSUE THREAD

**Issue by diamont1001** [request/request#2545]
It always get status 404 in some urls by request.

for example:
[http://xhpfm.mobile.zhongguowangshi.com/v300/newshare/1410821](http://xhpfm.mobile.zhongguowangshi.com/v300/newshare/1410821)

```js
request('http://xhpfm.mobile.zhongguowangshi.com/v300/newshare/1410821', (error, response) => {
      if (!error) {
        resolve();
      } else {
        console.log(response.statusCode); // 404
    });
```

**Comment by FredKSchott** [comment]
Can reproduce here: https://runkit.com/58aa1aa57ba62e0014b4752d/58aa1aa57ba62e0014b4752e/branches/master

**Comment by mike442144** [comment]
Obviously, this is not the issue of request. Please check the difference between packet sent by request and the browser to see if something wrong.

**Comment by FredKSchott** [comment]
@mike442144 why do you say obviously? When I curl that URL I get a `200` with HTML response body.

**Comment by diamont1001** [comment]
@FredKSchott yes, i get a `200` by curl or axios.

**Comment by mike442144** [comment]
@FredKschott @diamont1001 It's obviously obvious! Because the `404` code is a website related issue rather than request. Some sites will block you don't have a normal browser info. Please check request header difference.

**Comment by FredKSchott** [comment]
@mike442144 sorry I'm not following. What website-related/header-related issue specifically is causing curl to return a 200 and request to return a 404?

**Comment by mike442144** [comment]
@FredKSchott it really depends on the website, in this question, you should add User-Agent to get `200`. I know it's kind of weird, but that what the developers do!

**Comment by taoyuan** [comment]
@mike442144 @Feldhacker I have the same issue. 

`curl` and `axios` with default options is ok. `request` with default options returns 404. And this should not be caused by the header.

By the way, the request method is `GET`

**Comment by gillesdemey** [comment]
I can confirm that this is related to the `user-agent` header or some other form of gate keeping.

`curl http://xhpfm.mobile.zhongguowangshi.com/v300/newshare/1410821` 

returns a 502

`curl -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/603.2.1 (KHTML, like Gecko) Version/10.1.1 Safari/603.2.1' http://xhpfm.mobile.zhongguowangshi.com/v300/newshare/1410821` 

works just fine
