### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by EgidioCaprino** [request/request#2549]
Hi,

I'm using this library but I think it throws an `AssertionError`. I cannot be sure because I have no entry point reference in the stack trace.

```
assert.js:85
  throw new assert.AssertionError({
  ^
AssertionError: 5586 == 0
    at ClientRequest.onConnect (/home/egidio/Documents/giles-client/node_modules/tunnel-agent/index.js:159:14)
    at Object.onceWrapper (events.js:291:19)
    at emitThree (events.js:116:13)
    at ClientRequest.emit (events.js:195:7)
    at Socket.socketOnData (_http_client.js:443:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:189:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:551:20)
```

My script is called `index.js`.

When doing the request I'm handling errors in this way:

```
request.post('http://sample.com', {
    form: formData,
    proxy: 'http://' + self.url
}, function (error, response) {
    if (error) {
        reject(error);
    } else {
        if (response.statusCode < 400) {
            console.info(response);
        }
        fulfill();
    }
}).on('error', function (error) {
    reject(error);
});
```

I've also tried to put the `request.post` method in a try-catch block but didn't work.

Can you please help me?

Thank you,
Egidio

**Comment by FredKSchott** [comment]
See https://github.com/request/tunnel-agent/blob/master/index.js#L159

For some reason the head length is not zero. Can you add a `console.log(head)` statement before `/home/egidio/Documents/giles-client/node_modules/tunnel-agent/index.js:159` and try re-running to see what head actually is?

**Comment by mmmulani** [comment]
I ran into the same problem, this is what head was:
```
3c 68 74 6d 6c 3e 3c 68 65 61 64 3e 3c 74 69 74 6c 65 3e 34 30 34 20 46 69 6c 65 20 4e 6f 74 20 46 6f 75 6e 64 3c 2f 74 69 74 6c 65 3e 3c 2f 68 65 61 ..
```

it looks like a 404 response

**Comment by kevinstubbs** [comment]
I was having this issue as well until I switched to using HTTPS capable proxies.
https://github.com/request/tunnel-agent/issues/20
