### ISSUE TITLE
Multiple request at same time

### ISSUE THREAD

**Issue by trzyrazyzero** [request/request#2552]
Hello,
i want to send multiple request at same time.
```javascript
var sendRequest = function() {
	request(options, function(error, response, body) {
		if (!error && response.statusCode == 200) {
			console.log(body, response.elapsedTime);
		};
	});
};
for (var i = 0; i < 50; i++) {
	sendRequest();
};
```
And it sending request after each some delay, why?

**Comment by FredKSchott** [comment]
You are probably limited by your connection pool, see the pool option in the readme:

> A maxSockets property can also be provided on the pool object to set the max number of sockets for all agents created (ex: pool: {maxSockets: Infinity}).

**Comment by mirkods** [comment]
@FredKSchott the maxSockets default value is the default value of node, correct? so for version greater of 4 should be Infinity, right?
