### ISSUE TITLE
[support request] How can I use request to fill form and submit it on other page?

### ISSUE THREAD

**Issue by henrix343** [request/request#2554]
For example on other page there is form with input name 'username', input name 'password' and submit button. It is doable with request?

**Comment by FredKSchott** [comment]
If you have a support request or question please submit them to one of this resources:

* StackOverflow: http://stackoverflow.com/questions/tagged/request+node.js using the tags `node.js` & `request`
* Gitter community: https://gitter.im/request/request?utm_source=newissue
* Also have a look at the Readme for more information on how to get support:
  https://github.com/request/request/blob/master/README.md

Issues on GitHub are only related to problems of request itself and we cannot answer
support questions here.

**Comment by henrix343** [comment]
"Issues on GitHub are only related to problems of request itself and we cannot answer
support questions here." got it, thanks.
