### ISSUE TITLE
PR Backlog Cleanup

### ISSUE THREAD

**Issue by FredKSchott** [request/request#2556]
There are a lot of open PRs for the repo with unresolved problems (broken tests, merge conflicts,  last rebased 1+ years ago). I'd like to contribute more time to this repo, but its hard to know which of these PRs have authors that are still interested in merging/responding. Reaching out to each author and walking them through fixing up their PRs individually is time consuming and not something I could reasonably get through myself.

I'd like to automate this by suggesting the following: We close all PRs opened over 3 months ago with the following comment:

> This PR has been closed as "Abandoned" as a part of an automated cleanup. `@AUTHOR` if this is a mistake and you are still interested in merging this PR, please do the following:
> 1. Rebase your changes onto the `master` branch (even if there are no merge conflicts, we want to make sure your change is under the most recent tests).
> 3. Push your updated branch to Github to update this PR.
> 4. Make sure this PR's Travis tests are still passing. (Run `npm test` locally if tests are still failing).
> 5. Comment here to let us know that you've updated the PR and are still interested in getting it merged. Somebody from the project will respond and work with you to review.
>
> Thank you for your understanding. If you have any questions, feel free to respond here and I'll be happy to answer them.

I can commit to working with each author who responds. For anyone who doesn't respond, we can add a follow up comment in a few weeks/months asking anyone who's interested to take over with their own PR.

/cc @mikeal @simov (and anyone else who is interested in helping maintain request going forward) wdyt?

**Comment by simov** [comment]
Sounds great! Just don't close all of them at once because you'll be swarmed with lots of responses at once.

**Comment by FredKSchott** [comment]
![i like to live dangerously](http://s2.quickmeme.com/img/08/085260da739d5f8723a626ab23a0da4623be9458998bfc91b38c57cdffec16d4.jpg)

**Comment by FredKSchott** [comment]
Cleanup complete. Hopefully authors are still interested in merging and we get some good responses in those PRs 🤞
