### ISSUE TITLE
options.uri error POST request

### ISSUE THREAD

**Issue by estradamarkie** [request/request#2557]
Trying to post a simple object through nodejs using `request http` module, every time I try to send my data to my API it showing this `options.uri is a required argument` yet I provided a URL end point where to `POST` the data.

   ```
 var url = 'http://omcloud.azurewebsite.net/api/Test';
    request.post(url,
                { json: { "Definition": "Test"} },
                function (error, response, body) {
                    if (!error && response.statusCode == 200) {
                        console.log(body)
                    }
                }
            );
```
Can someone shed a light what's wrong with the code above?

**Comment by FredKSchott** [comment]
Try this: https://runkit.com/58aa1aa57ba62e0014b4752d/58acce671ddfde00130bedec/branches/master
```
var url = 'http://omcloud.azurewebsite.net/api/Test';
 request.post(url,
             { json: { "Definition": "Test"} },
             function (err, response, body) {
                     console.log(err, response, body);
             }
         );
```

We should make the README code snippet more flexible, right now it only logs anything if the response is successful and is silent otherwise.

**Comment by estradamarkie** [comment]
Sorry don't quite get it,  an error says on that link `getaddrinfo ENOTFOUND` yet even with the correct URL still showing the same stuff.

**Comment by estradamarkie** [comment]
tried putting the right URL and still showing the same error.

Tried no luck
```
request.post({
                url: url,
                json: { "Definition": "Test" }
            }
```

**Comment by FredKSchott** [comment]
Issue is with the website and not request
```
$ curl -X POST http://omcloud.azurewebsite.net/api/Test
curl: (6) Could not resolve host: omcloud.azurewebsite.net
```

**Comment by estradamarkie** [comment]
yeah thanks, looks like the endpoint is broken.
