### ISSUE TITLE
request.abort() should clear timeoutTimer

### ISSUE THREAD

**Issue by alexguan** [request/request#256]
When sending request to a slow server with a short timeout value, before the server returns back anything, calling request.abort does not clear timeoutTimer. The ETIMEDOUT error will still be reported.

e.g.

``` javascript
var r = request.get('http://slowserver', request.defaults({ timeout : 10000 } ));

r.on('error', function (error) {
  //We should not see ETIMEDOUT error here
  console.log(error);
});

r.pipe(...);

process.nextTick(function () {
  r.abort();
});
```

**Comment by furstenheim** [comment]
Getting same issue with node 7 and request 2.81.0

**Comment by furstenheim-geoblink** [comment]
Maybe this issue is related to this issue in Node? https://github.com/nodejs/node/pull/20077
which was fixed in Node 13
