### ISSUE TITLE
use with setTimeout not working

### ISSUE THREAD

**Issue by zxqian1991** [request/request#2567]
i use request to download a picture,it always works well util i use setTimeout, the problem looks like this

```javascript
const request = require("request");
const fs = require("fs");
let wt1 = fs.createWriteStream("ge.jpg");
let url = "http://127.0.0.1:8888/test.jpg";
request(url).on('response', (res) => {
        setTimeout(() => {
            res.pipe(wt1);
        })
        // process.nextTick(() => {
        //     res.pipe(wt1);
        // })
        // setImmediate(() => {
        //     console.log("我将开始")
        //     res.pipe(wt1);
        // })
    })
```
as i try with the `nextTick` Func and `setImmediate` Func, only `nextTick` works。
i do not know the reason. can anyone explain it?

**Comment by robeerob** [comment]
Try changing line 5 to this:
`request(url).on('res', (res) => {`

**Comment by zxqian1991** [comment]
I'm sorry to reply so long ago. I use timeout to test whether it can work with asynchronous operation,such as  detecting whether the file exists or creating a new  file. it seems that with the nodejs native interface the asynchronous operation can work, but here not work.

**Comment by robeerob** [comment]
Ok. If I understand you correctly, this issue can then be closed?

**Comment by zxqian1991** [comment]
ok,thank you
