### ISSUE TITLE
callback not being called

### ISSUE THREAD

**Issue by bsculley** [request/request#2568]
Apparently the callback function is not being called, since the "tok" variable is not being set to anything.   Also, it isn't waiting 5 seconds.  Is the callback asynchronous? 

This is running is a node-red node on Raspberry Pi/Debian.

```
        var options = {
            url: 'http://localhost:1880/auth/token',
            method:'POST',
            headers: {
                'Accept': '*/*',
                'Content-Type': 'application/x-www-form-urlencoded'
            },
            form: {'client_id': 'node-red-admin',
                'grant_type': 'password',
                'scope': '*',
                'username': 'admin',
                'password': 'password'
            },
            timeout:5000
        };

        var tok;
        request(options, function (error, response, body) {
            if (!error && response.statusCode == 200) 
                tok= JSON.parse(body);
            else
                tok= response;
        });

```

**Comment by jhand2** [comment]
The request function is asynchronous which means that it won't be called until the HTTP response has been received. This means that code after the request function call will likely execute before the callback does (which is why there is  callback).

**Comment by bsculley** [comment]
Ok, thanks.  I thought that might be the issue, but what mechanism is there to wait for the response before continuing?

 

I looked for some way to do this but didn’t find it.  

 

Bob

**Comment by joelebeau** [comment]
Anything that you would like to do that relies on the asynchronous call would need to be done within the callback. For example, something like this

   ```
     var options = {
            url: 'http://localhost:1880/auth/token',
            method:'POST',
            headers: {
                'Accept': '*/*',
                'Content-Type': 'application/x-www-form-urlencoded'
            },
            form: {'client_id': 'node-red-admin',
                'grant_type': 'password',
                'scope': '*',
                'username': 'admin',
                'password': 'password'
            },
            timeout:5000
        };

        request(options, function (error, response, body) {
            var tok;
            if (!error && response.statusCode == 200) 
                tok= JSON.parse(body);
            else
                tok= response;
                /* Do something with tok here */
        });

```

I would advise Googling around and doing some reading about callbacks and/or higher order functions as they're fairly pervasive in Javascript.

**Comment by bsculley** [comment]
Thanks for the guidance.  I finally figured out how to make it work.

 

Oh, for interactive debugging!

**Comment by craftpip** [comment]
Great library!
just for my clearance, is the callback function called after the request has timeout. 
if yes what will be the error message.
