### ISSUE TITLE
qs encoding works incorrectly

### ISSUE THREAD

**Issue by wotgl** [request/request#2570]
### Summary
I tried to send query parameters without encoding (i.e. single quote should be ```'``` instead of ```%27```). Used for this object-parameter ```qs``` with ```qsStringifyOptions = {encode: false}```, but the out request  came with encoding

![image](https://cloud.githubusercontent.com/assets/7968712/23562891/587305c8-0055-11e7-97bc-dd3b0006a24c.png)

Looked at the source code
request/request.js
```
1166: var qs = self._qs.stringify(base)

1172: self.uri = url.parse(self.uri.href.split('?')[0] + '?' + qs)
```

On 1166 line everything is OK, the qs returns without encoding:
```
title=AAAAAAAAAA'&qs1=BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB%20://ас'"д
```
But on 1172 line data is transmitted in the url.parse(), this method encoded all input data:
```
// it`s self.uri object
Url {
  protocol: 'https:',
  slashes: true,
  auth: null,
  host: 'ru.wikipedia.org:443',
  port: '443',
  hostname: 'ru.wikipedia.org',
  hash: null,
  search: '?title=AAAAAAAAAA%27&qs1=BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB%20://ас%27%22д',
  query: 'title=AAAAAAAAAA%27&qs1=BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB%20://ас%27%22д',
  pathname: '/w/index.php',
  path: '/w/index.php?title=AAAAAAAAAA%27&qs1=BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB%20://ас%27%22д',
  href: 'https://ru.wikipedia.org:443/w/index.php?title=AAAAAAAAAA%27&qs1=BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB%20://ас%27%22д' }
```

Am I doing something wrong or is it still a bug?

### Simplest Example to Reproduce

```js
request({
  method: 'GET',
  url: 'http://example.com', // a public URL that we can hit to reproduce, if possible
  qs: {
    qs1: "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB%20://ас'\"д"
  },
  qsStringifyOptions: {
    encode: false
  }
},
```

### Possible Solution
Need to check qsStringifyOptions

| software         | version
| ---------------- | -------
| request          | ^2.79.0
| node             | v6.10.0
| npm              | 3.10.10
| Operating System | Ubuntu 16.04 x64

**Comment by mikeal** [comment]
@simov are we using the Node.js core qs library of the "querystring" library for this?

**Comment by simov** [comment]
@mikeal by default we are using `qs`

**Comment by mikeal** [comment]
thanks @simov, we've bounced back and forth a lot about which querystring lib to use. i'm sort of at a loss about which one we should default to at this point :man_shrugging:

**Comment by wotgl** [comment]
any news? :)

**Comment by wotgl** [comment]
@mikeal I tried to fix this problem
To check used ```npm test```, but ran into another problem
Cloned version from github (no change) does not pass local tests

Errors:
![image](https://cloud.githubusercontent.com/assets/7968712/23654391/77d5c178-0341-11e7-8843-7d16c915b0d8.png)
![image](https://cloud.githubusercontent.com/assets/7968712/23654393/7b447002-0341-11e7-9b52-6b12f87d31e6.png)

In the end, passed tests
```
total ......................... 1357/1392
```

What could be the problem?

**Comment by FredKSchott** [comment]
@wotgl thanks for investigating this. Before getting too deep into the solution, can I ask why you want to make a request with an unencoded query string value? I can't think of a situation that would support/require this.

Also because @mikeal asked, our querystring stringifying is actually doing the right thing here. It's url.parse that then takes that qs string and encodes it anyway.

See here for a background on why url.parse() behaves this way: https://github.com/nodejs/node/issues/2113

**Comment by ahmdsolmn** [comment]
@FredKSchott A possible situation is using an api (gnip api in my case) that needs a strict body structure.
For example, In gnip (a data streaming api) I POST "rules" which are strings that might contain parentheses so they are converted to %28 so my request is rejected from the api. 

If this PR is merged I could send my "rules" (strings) exactly as I want.

**Comment by simov** [comment]
@wotgl @ahmdsolmn use the [RFC 1738](https://github.com/ljharb/qs#rfc-3986-and-rfc-1738-space-encoding) encoding like this:

```js
request({
  method: 'GET',
  url: 'http://requestb.in/ozrs6koz',
  qs: {
    qs1: "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB%20://ас'\"д"
  },
  qsStringifyOptions: {
    format : 'RFC1738'
  },
  callback: (err, res, body) => {}
})
```

**Comment by ahmdsolmn** [comment]
@simov this doesn't solve the issue

**Comment by bitoth** [comment]
Hey, i have the same problem and @simov this solution dosnt work for me.
@FredKSchott u ask for an example. I currently work with an webservice, whicht use | (pipe) as OR operator like:

?(host_name=*google.com*|host_alias=*goog.le*)&format=json

And this service isnt able to interpret the url with an %7C as |
