### ISSUE TITLE
EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval'

### ISSUE THREAD

**Issue by ivankravets** [request/request#2572]
See  Stack Traces

- https://github.com/platformio/platformio-atom-ide/issues/249

The problem is linked to the latest 2.80 release.

**Comment by epoberezkin** [comment]
I think I know how to fix it.

**Comment by epoberezkin** [comment]
https://github.com/ahmadnassri/har-validator/pull/89 should resolve the issue

**Comment by ivankravets** [comment]
Thanks, @epoberezkin! 👍 

 I've just released the hotfix of @PlatformIO IDE and fixed to the v2.79 of `request`.

**Comment by ahmadnassri** [comment]
updated and PR to bump version opened!

**Comment by epoberezkin** [comment]
@ivankravets can you check now please? har-validator should have version 4.2.1
