### ISSUE TITLE
EventEmitter leak in 2.80

### ISSUE THREAD

**Issue by jabr** [request/request#2575]
After upgrading to 2.80, I was getting this error in production:

`MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 connect listeners added. Use emitter.setMaxListeners() to increase limit`

The node.js processes quickly grew to 1-2 GB of resident memory (normally 300 MB) and then CPU load started spiking.

Rolled back to 2.79 and the issue went away.

**Comment by mikeal** [comment]
It's in one of these:

https://github.com/request/request/commit/60f6a00327f3a174bcd5af68ab61cfacf7360c8e
https://github.com/request/request/commit/c7c9431f1fadaf4b700e82218c3df9e0f2e96646

These are the only commits that add event listeners between those two releases.

**Comment by mikeal** [comment]
I think I found it https://github.com/request/request/commit/60f6a00327f3a174bcd5af68ab61cfacf7360c8e#commitcomment-21154407

@FredKSchott @nicjansma do you wanna take a look?

**Comment by jabr** [comment]
That looks like the issue. The application makes heavy use of keep-alive connections.

**Comment by mikeal** [comment]
I'm wondering if the best course of action is to just remove this feature. It doesn't actually work during keep-alive and keep-alive is entirely transparent to the user so the timings object just wont' have this information sometimes and it isn't entirely predictable when they will have it.

**Comment by jabr** [comment]
Or it could check if the socket is already connected and just set the `connect` time to the `socket` time.

**Comment by mikeal** [comment]
> Or it could check if the socket is already connected and just set the connect time to the socket time.

That's probably worse. People will make really bad assumptions about that.

**Comment by nicjansma** [comment]
See https://github.com/request/request/pull/2566 for an updated PR that works for keep-alive.

Do you think it's sufficient to change the `.on` to `.once`?

**Comment by mikeal** [comment]
@nicjansma no, that won't work.

The problem isn't that it isn't being cleaned up after being called it's that it is probably *never* called.

**Comment by mikeal** [comment]
@nicjansma one thing you'll need to consider is that socket level metrics simply aren't applicable in the keep-alive scenario and that being in keep-alive isn't always predictable by your consumers.

**Comment by nicjansma** [comment]
@mikeal Ah, that makes sense.  I can update the handling to ensure the listener is removed, and validate that the socket object isn't kept alive.

Yep, I understand the concerns about the Keep-Alive scenario.  In that case, the connect time will be set to the dns time (which will be set to the socket time which will be set to the start time) if any of the phases don't occur.  This roughly matches the [ResourceTiming](https://www.w3.org/TR/resource-timing/) processing model.

**Comment by mikeal** [comment]
you probably do want to use once, but you also probably want to set a property for when connect has already been fired so that you can avoid adding the handler again.

**Comment by mikeal** [comment]
@nicjansma ping me when the PR gets updated :)

**Comment by nicjansma** [comment]
@mikeal Absolutely, working on it!

**Comment by nicjansma** [comment]
@mikeal https://github.com/request/request/pull/2566/commits/6c891da010f97b0dba4b862f5daf6448bdefa874

**Comment by Huachao** [comment]
@mikeal @nicjansma will a newer version be published for this patch?

**Comment by jabr** [comment]
Thank you all for jumping on that so quickly. And it's not really my place, but I would strongly recommend pushing a patch release to npm.
