### ISSUE TITLE
Move to standardjs code style

### ISSUE THREAD

**Issue by mikeal** [request/request#2577]
Look, it was cute to have my own code style for the first 6 years but this is just making it weird to contribute to now. I'm +1 for moving to standardjs. I'm -1 for moving to anything else, cause I just don't wanna have an argument about it :)

**Comment by simov** [comment]
StandardJS is pretty close to what we have anyway. :+1: from me

**Comment by ahmadnassri** [comment]
thanks to "Insomnia Driven Development ™" ;)

**Comment by FredKSchott** [comment]
I remember trying to build the original `.eslintrc` to match my best guess at what was the "intended" style at the time. I'm still amazed eslint could handle it.

Oh, and a begrudging +1 from me. Because the only thing that beats my love for semicolons is my dislike for code style arguments :)
