### ISSUE TITLE
Any way to get server IP address from response?

### ISSUE THREAD

**Issue by tomrf** [request/request#2586]
Is there any practical way of getting the remote server IP address from the response object?

I'm looking for something akin to curls PRIMARY_IP info field, which gives the actual IP address of the server that handled the request.

I've been digging through the response object but I'm unable to find any way to access anything other than the hostname from the URL object or headers.

Any help or suggestion on how to solve this would be much appreciated, as it is currently the only thing holding me back from replacing curl.

**Comment by rtezera1** [comment]
This[stackoverflow answer](http://stackoverflow.com/questions/8107856/how-to-determine-a-users-ip-address-in-node) might help resolve your issue.
