### ISSUE TITLE
Inconsistency in 'time' documentation

### ISSUE THREAD

**Issue by tomrf** [request/request#2587]
Running request v2.80.0 with "time: true", the timing members do not match those in the documentation.

According to the documentation, there should be a 'timingPhases' object, this does not exist.

The 'timings' object contains { socket, connect, response, end, dns, tcp, firstByte, download, total } which is a mixture of what the documentation details between the 'timings' and 'timingPhases' objects.

Why am I seeing this inconsistency between documented objects and actual returned objects in my project?

**Comment by FredKSchott** [comment]
@nicjansma any ideas?

**Comment by nicjansma** [comment]
@tomrf @FredKSchott The `timingPhases` object was added in v2.81.0 via https://github.com/request/request/pull/2566

**Comment by pmanthen** [comment]
I still don't see `timings` or `timingPhases` in v2.81.0

**Comment by pmanthen** [comment]
My bad- my project was actually using 2.75.0. I see timingPhases in 2.81.0
