### ISSUE TITLE
Get Status line from a response

### ISSUE THREAD

**Issue by miketran78727** [request/request#2591]
Is there a way to get the status line from response?  In Java, I can use ````https://hc.apache.org/httpcomponents-core-ga/httpcore/apidocs/org/apache/http/StatusLine.html```` to get HTTP-Version, Status-Code and Reason-Phrase. I do not see status line in Request's response object.

**Comment by wotgl** [comment]
@miketran78727 hi!
try this
```
let callback = function(error, response, body) {
  console.log(response.statusCode, response.statusMessage, response.httpVersion);
}
request(options, callback);
```
