### ISSUE TITLE
while logging using winston, its failing fs.stat is not function

### ISSUE THREAD

**Issue by KalpanaPagariya** [request/request#2597]
Hi I am trying to us winston for server side logging. But it works only when I log in the file where server is getting started. But it fails when use in the application, throwing below error:

Uncaught TypeError: fs.stat is not a function
    at checkFile (http://localhost:8080/public/bundle.js:111765:8)
    at exports.File.File._createStream (http://localhost:8080/public/bundle.js:111785:5)
    at exports.File.File.open (http://localhost:8080/public/bundle.js:111611:17)
    at exports.File.File.log (http://localhost:8080/public/bundle.js:111406:10)
    at transportLog (http://localhost:8080/public/bundle.js:110546:15)
    at http://localhost:8080/public/bundle.js:45155:13
    at _each (http://localhost:8080/public/bundle.js:45055:9)
    at Object.async.each (http://localhost:8080/public/bundle.js:45154:9)
    at exports.Logger.Logger.log (http://localhost:8080/public/bundle.js:110558:9)
    at exports.Logger.target.(anonymous function) [as info] (http://localhost:8080/public/bundle.js:14508:18)

**My webpack.config.js**

var path = require('path');
var webpack = require('webpack');
var ExtractTextPlugin = require("extract-text-webpack-plugin");

module.exports = {
  devtool: 'source-map',
 
  entry: [
  //  'webpack-dev-server/client?http://localhost:8080/', // WebpackDevServer host and port
  //   'webpack/hot/only-dev-server', // "only" prevents reload on syntax errors
    './src/com/avaya/components/index'],
  output: {
    filename: 'bundle.js',
    path: path.join(__dirname, '/public'),
    publicPath: 'http://localhost:8080/public/'
  },
  
  module: {
    loaders: [
      { test: /\.js$/, loaders: ['babel-loader'] ,  exclude: /node_modules/},
     {
        test: /\.css$/,
        use: ExtractTextPlugin.extract({
            fallback: 'style-loader',
            use: [ 
              { loader: 'css-loader', options: { minimize: true } } 
            ]
        })
      },
      {
        test: /\.json$/,
        loader: 'json-loader'
      },
       {
        test: /\.(png|jpg|)$/,
        loader: 'url-loader?limit=200000'
      },
      {
        test: /\.(jpg|png)$/,
      loader: "url-loader?mimetype=image/png"
      },
        {
          test: /\.(woff|woff2)$/,
          // Inline small woff files and output them below font/.
          // Set mimetype just in case.
          loader: 'url-loader',
          options: {
            name: 'fonts/[hash].[ext]',
            limit: 5000,
            mimetype: 'application/font-woff'
          },
         // include: PATHS.fonts
        },
        {
          test: /\.ttf$|\.eot$|\.svg$/,
          loader: 'file-loader',
          options: {
            name: 'fonts/[hash].[ext]'
          },
          //include: PATHS.fonts
        },
        
     
        
    ]
  },
node: {
    console: true,
    fs: 'empty',
    net: 'empty',
    tls: 'empty',
    process:true
  },
  
  plugins: [
   new ExtractTextPlugin('style.css'),
   new webpack.DefinePlugin({
      'process.browser': true
    })
   //new webpack.HotModuleReplacementPlugin()
   
 ]

};

**server.js**

var path = require('path');
var express = require('express');
var webpack = require('webpack');
var config = require('./webpack.config.dev');

var app = express();
var compiler = webpack(config);

var express = require("express");
var app = express();

app.use(require('webpack-dev-middleware')(compiler, {
  noInfo: true,
  publicPath: config.output.publicPath
}));

app.use(express.static(__dirname))

app.get('*', function(req, res) {

  res.sendFile(path.join(__dirname, '/index.html'));
});

app.listen(8080, 'localhost', function(err) {

  if (err) {
    console.log(err);
    return;
  }
logger.debug("inside out");
  console.log('Listening at http://localhost:8080');
});

**Logger.js**

var winston = require('winston');
winston.emitErrs = true;

var logger = new winston.Logger({
    transports: [
        new winston.transports.File({
            level: 'info',
            filename: './all-logs.log',
            handleExceptions: true,
            json: true,
            maxsize: 5242880, //5MB
            maxFiles: 5,
            colorize: false
        }),
        new winston.transports.Console({
            level: 'debug',
            handleExceptions: true,
            json: false,
            colorize: true
        })
    ],
    exitOnError: false
});

module.exports = logger;

**my index.js app file:**
 var LOGGER = require("../../../../logger");
LOGGER.info('Hello distributed log files!');

Can you please help me?

**Comment by moffsugita** [comment]
TypeError: fs.stat is not a function
