### ISSUE TITLE
getting balnk data in response

### ISSUE THREAD

**Issue by sanjsdev** [request/request#2599]
i tried with this below code getting blank data in repsone (request with OAuth1.0) .fyi credentials are correct i cheked with postman tool i'm getting response there. any Suggestions how to do it.
request.post(url, {
     oauth: {
       consumer_key:'con_key',
       consumer_secret:'con_sec',
       token:'token_key',
       token_secret:'token_secret    
     },
     body:{ // parameters for request here },
     json: true
},function (err, res, body) {
     console.log(body)//getting blank
});

Thanks.

**Comment by mikeal** [comment]
check the response code.

**Comment by sanjsdev** [comment]
hi @mikeal can you please mention clearly what needs to be checked in response code. there is lot of data if print "**res**" .

**Comment by mikeal** [comment]
`res.statusCode`

**Comment by sanjsdev** [comment]
it's returning **403** @mikeal

**Comment by mikeal** [comment]
That's the problem then, the server would return a 200 response if it liked the request.

https://en.wikipedia.org/wiki/HTTP_403

You probably need some kind of authentication step first, depends on the site.

**Comment by JuergenSimon** [comment]
We have this problem as well. We make a request to a service that basically provides a batch function. You post one request containing three sub-requests. Two of those work and respond with 200, the third fails with 403. This turns the batch request into a 403, but the data for the first two operations is returned. I can see this in postman, but using request.js we only get garbage. Please fix.
