### ISSUE TITLE
Servers that respond with "Upgrade: h2c" makes 'the world end' (Node v4)

### ISSUE THREAD

**Issue by iamjochem** [request/request#2601]
### Summary
This issue describes something that is not a problem in your lib (the cause is a bug in Node) but I thought you might like to know (more?) about this issue so that you can possibly decide to document it (maybe it will save a few other people from banging their heads again the wall!)

### Simplest Example to Reproduce
```js
var request       = require('request');

request .get('http://www.grozette.com/images/pdf/industrie/industriecopackingnew.jpg')
        .on ('error', console.error)
        .on ('response', function(response) {
            console.log(response.statusCode)
            console.log(response.headers['content-type'])
        })

```

### More Involved Example to Reproduce (using Promise.map)
```js
var bb            = require('bluebird'); // assuming v3.5.0
var request       = require('request');

// promisified deps
var requestP      = bb.promisify(request.defaults({ jar : true }), { multiArgs : true });

var files = [
      { src: 'https://www.google.nl/logos/doodles/2017/first-day-of-spring-2017-northern-hemisphere-5171021979058176.2-s.png' }, // 200
      { src: 'file:///C:/some/path/to/a/file.png' }, // Error
      { src: 'http://www.grozette.com/images/pdf/industrie/industriecopackingnew.jpg' }, // death by Upgrade header
      { src: 'http://www.example.com/some/fake.jpg' } // 404
];

function download_image(img)
{
    return requestP(img.src, { encoding : null }).spread(function(resp) {
        console.log('req RESP', resp.statusCode, img.src);

        return bb.resolve(true);
    }).catch(function(e) {
        console.log('req ERR', e, img.src);

        return bb.resolve(true);
    }).finally(function() { 
        console.log('req FINALLY', img.src); 
    });
}


function download_images(images)
{
    return bb.map(images, download_image, { concurrency : 1 });
}

download_images(files)
    .then   (function()  { console.log('MAP DONE');     })
    .catch  (function(e) { console.log('MAP ERR', e);   })
    .finally(function()  { console.log('MAP FINALLY');  })
    ;
```

### Expected Behavior
I expect to see a response or error output, and in the case of the promise-based code I additionally expect to see the "FINALLY" output in all cases.

### Current Behavior
I see nothing (in the case of the single request example) and do not see the "FINALLY" (in the case of the promise-based example) 

### Possible Solution
The solution is upgrading to node v6+, the problem stems from [this node bug](https://github.com/nodejs/node/issues/4844) (which is [fixed here](https://github.com/nodejs/node/pull/4337))

### Context
this drove me mad, no errors, no output, promise-chain broken, process just "ends" (without so much as an error exit code) :-)

### Your Environment

| software         | version
| ---------------- | -------
| request          | v2.81.0
| node             | v4.x
| npm              | v2.x
| Operating System | MacOS / Ubuntu

----

thanks for reading & thanks for the lib!

**Comment by umutm** [comment]
The Nodejs developers hadn't wanted to add the fix to the old versions and the solution is definitely upgrading Nodejs.
