### ISSUE TITLE
Have problem with response body when trying to request to server

### ISSUE THREAD

**Issue by odarino** [request/request#2612]
Hi, When trying to request to server, I have problem with my body response, [here](http://imgur.com/9D0Eo5W) , 
I've tried to set ``` 'Content-Type': 'text/plain; charset=utf-8' ``` , but it seems not work, What should I do ?

**Comment by yomr** [comment]
The content type returned looks like `gzip`. You can pass the `gzip = true` option in your request. That should handle this case.
Something like 
`request.get({url: url, gzip: true}, function (error    , response, body) {
//handle response
}`

**Comment by odarino** [comment]
thank you, it works fine !

**Comment by yomr** [comment]
Great! Can this issue be closed in that case?
