### ISSUE TITLE
Missing definition of 'transport_method' in OAuthOptions of @types/request 

### ISSUE THREAD

**Issue by dvishniakov** [request/request#2616]
Version 0.0.42 doesn't have definition of this parameter which is mentioned in readme.md.
Which result in this message from tsc: error TS2339: Property 'transport_method' does not exist on type 'OAuthOptions'.

Unfortunately the link which is mentioned in the package's readme returns 404 (https://www.github.com/DefinitelyTyped/DefinitelyTyped/tree/master/request) so I can't open an issue there.

**Comment by FredKSchott** [comment]
Sorry, we don't maintain TS definitions. You'll want to create your fix here: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/request/index.d.ts
