### ISSUE TITLE
Data is still emitted after abort if gzip is enabled

### ISSUE THREAD

**Issue by jacktuck** [request/request#2620]
## Reproduce with the following
>request@2.81.0
> node@v7.7.3
```
var request = require('request')
var debug = require('debug')

var req = request.get({
  url: 'https://google.com',
  gzip: true
})

var debug = require('debug')('test')

var ran = 0
req.on('data', (data) => {
  debug('GOT DATA')

  debug('IS ABORTED', req._aborted)

  if (++ran === 1) req.abort()
})

req.on('abort', () => debug('GOT ABORT!'))

req.on('end', () => debug('GOT END'))
```

### GZIP enabled
>  test GOT DATA +0ms
  test IS ABORTED undefined +1ms
  test GOT ABORT! +1ms
  test GOT DATA +0ms
  test IS ABORTED true +0ms
  test GOT DATA +1ms
  test IS ABORTED true +0ms
  test GOT DATA +0ms
  test IS ABORTED true +0ms
  test GOT DATA +0ms
  test IS ABORTED true +0ms
  test GOT DATA +0ms
  test IS ABORTED true +0ms
  test GOT DATA +0ms
  test IS ABORTED true +0ms
  test GOT DATA +1ms
  test IS ABORTED true +0ms
  test GOT DATA +0ms
  test IS ABORTED true +0ms
  test GOT DATA +0ms
  test IS ABORTED true +0ms
  test GOT DATA +0ms
  test IS ABORTED true +0ms
  test GOT DATA +0ms
  test IS ABORTED true +0ms
  test GOT DATA +0ms
  test IS ABORTED true +0ms
  test GOT DATA +1ms
  test IS ABORTED true +0ms
  test GOT DATA +0ms
  test IS ABORTED true +0ms
  test GOT DATA +0ms
  test IS ABORTED true +0ms
  test GOT DATA +0ms
  test IS ABORTED true +0ms
  test GOT DATA +0ms
  test IS ABORTED true +0ms
  test GOT DATA +0ms
  test IS ABORTED true +0ms
  test GOT DATA +0ms
  test IS ABORTED true +0ms
  test GOT DATA +0ms
  test IS ABORTED true +0ms
  test GOT DATA +1ms
  test IS ABORTED true +0ms
  test GOT END +1ms

### GZIP disabled
>  test GOT DATA +0ms
  test IS ABORTED undefined +1ms
  test GOT ABORT! +1ms
  test GOT END +1ms

**Comment by yourfavorite** [comment]
Is there a workaround for this issue?

**Comment by jacktuck** [comment]
@yourfavorite I haven't found enough time to look into it, only workaround i found was to, well, not gzip haha.
