### ISSUE TITLE
OAuth 1.0 Support for HMAC-SHA256

### ISSUE THREAD

**Issue by kylelaverty** [request/request#2627]
### Summary
I would like to ass OAuth support for HMAC-SHA256 added. Currently request only supports HMAC-SHA1 and RSA-SHA1.

### Current Behavior
Currently using HMAC-SHA256 causes the following exception to be thrown:  Signature method not supported: HMAC-SHA256

This should be a supported workflow such that this additional signature method can be used without any errors following the existing process.

### Context
I am trying to integrate with an OAuth 1.0a one-leg provider who can optionally support HMAC-SHA256. They recommend that any integrating partner move towards that since they intend to stop supporting HMAC-SHA1 in the future.

### References
There is an open issue in the oauth-sign repo, [Issue 13](https://github.com/request/oauth-sign/issues/13), that looks like it might solve this issue.

**Comment by simov** [comment]
Published in version 0.9.0 https://github.com/request/oauth-sign/issues/13
