### ISSUE TITLE
How to parse multipart response? Is feature available or when do i it expect to be available

### ISSUE THREAD

**Issue by Koka5** [request/request#2633]
### Simplest Example to Reproduce
> I am checking this resource to create a server that returns multipart response.
https://blog.miguelgrinberg.com/post/video-streaming-with-flask

```js
console.log('sending ...'); // prints
request({
  method: 'GET',
  url: 'http://localhost:3000'
}, function(){
  console.log('sent..!') // never prints
});
```

### Expected Behavior
I was expecting that `sent..!` would be printed. and some how i could parse the response.

### Current Behavior
the callback never called

### Context
I just want to do some experiments on parsing multipart response in nodejs

| software         | version
| ---------------- | -------
| request          | 2.81.0
| node             | 7.8.0
| npm              | 4.2.0
| Operating System | macOS 10.12.4

**Comment by joeflateau** [comment]
@Koka5 did you ever figure out how to parse multipart responses w/ request?
