### ISSUE TITLE
Error: connect ECONNREFUSED 127.0.0.1:80  for request nodejs module

### ISSUE THREAD

**Issue by tandacedric** [request/request#2634]
{ [Error: connect ECONNREFUSED 127.0.0.1:80]
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 80 }
I have this issue when i  make request with  nodejs request module without network enable or ip adress

```js
request({
  url: 'http://localhost/path/',
  json:true,
 jar : request.jar()
function(error,body,response){
  console.log(error);
 console.log(response);
//  do  something here
}
 
},
```

### Your Environment

| software         | version
| ---------------- | -------
| request          |
| node             |
| npm              |
| Operating System | window 10

**Comment by rodolfobeletatti** [comment]
Do you really have a server in 127.0.0.1 on port 80?
