### ISSUE TITLE
SHA1 has been compromised

### ISSUE THREAD

**Issue by JacksonGL** [request/request#2640]
Report of a potential security vulnerability: by default, this package uses SHA-1 ([code location](https://github.com/request/request/blob/b12a6245d9acdb1e13c6486d427801e123fdafae/lib/oauth.js#L70)) for authentication, which has been compromised ([link](https://security.googleblog.com/2017/02/announcing-first-sha1-collision.html?utm_source=feedburner&utm_medium=feed&utm_campaign=Feed%3A+GoogleOnlineSecurityBlog+%28Google+Online+Security+Blog%29)) two months ago.

**Comment by mikeal** [comment]
Per spec, do all other implementation have to support another hashing algorithm?

**Comment by JacksonGL** [comment]
No, that's why its an opportunity to make this package safer than the other implementations. Plus SHA-1 may be deprecated in the near future if the practical attack is revealed.

**Comment by mikeal** [comment]
@JacksonGL my concern is that updating it would make it incompatible with those other implementations. if they don't support other hashing standards then we're breaking compatibility with those servers.

That said, we should add option support for another hashing algorithm ASAP. At some point in the future we can consider a breaking change that would modify the default algorithm.

**Comment by JacksonGL** [comment]
Yes. It would be great to add such an optional support.

**Comment by jstaelens** [comment]
I would be fine with a major version bump to make SHA256 the default.  I expect most places to move away from SHA-1 and may be forced to by security audit tools.  Or find a different library.

**Comment by mikeal** [comment]
I had a conversation with @hueniverse (author of OAuth) about this and the threat is a little exaggerated in this specific use case.

At this point I don't think it's reasonable to change the default. I'm all for adding the option though.

**Comment by shankarkrupa** [comment]
Nexus.IQ reports this as an issue sonatype-2017-0655 preventing it from deploying in highly secured environments. Please consider reopening the issue.

**Comment by ananthakumar25** [comment]
As part of security analysis from Sonatype Nexus.IQ , this is an severe issue as it reports "The request package is vulnerable to Weak Authentication Algorithm. The function **function in oauth.js uses SHA-1** for authentication which is no longer considered cryptographically secure." -  This is preventing the code promotion to higher environment.


Could you please consider reopening this issue?

**Comment by mikeal** [comment]
`request` is deprecated and is no longer shipping new releases.

**Comment by ananthakumar25** [comment]
> `request` is deprecated and is no longer shipping new releases.

Do you have any alternate packages or versions to use?

**Comment by cyclone14** [comment]
check out issue #3143
