### ISSUE TITLE
vue-strap navbar.vue throws error

### ISSUE THREAD

**Issue by jackharter** [request/request#2646]
Does vue-strap navbar.vue even work? 

* ./utils/NodeList.js in ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./src/components/navigation.vue

Thanks.

johnh

### Simplest Example to Reproduce

```js
request({
  method: 'GET',
  url: 'http://example.com', // a public URL that we can hit to reproduce, if possible
  more: { 'options': 'here' }
},
```

### Your Environment

| software         | version
| ---------------- | -------
| request          |
| node             |
| npm              |
| Operating System |

**Comment by rodolfobeletatti** [comment]
I did not understand your question
