### ISSUE TITLE
When will 2.81.2 be released?

### ISSUE THREAD

**Issue by ir-fuel** [request/request#2652]
The current version of `request` depends on:
` "har-validator": "~4.2.0", `

While the newest version depends on
` "har-validator": "~5.0.2" `

`har-validator` 4.X depends on 
` "ajv": "^4.9.1" `

while version 5 depends on
` "ajv": "^5.0.1" `

The problem is that `ajv` 4.9.x generates errors when used in conjunction with webpack. This problem is solved in 5.X. 

https://github.com/epoberezkin/ajv/issues/453
https://github.com/epoberezkin/ajv/issues/436

https://github.com/epoberezkin/ajv/issues/117#issuecomment-288023794

**Comment by epoberezkin** [comment]
@ir-fuel I am afraid it will not be not sufficient. Unless I am missing something har-validator 5.x still depends on ajv 4.x; this PR https://github.com/ahmadnassri/har-validator/pull/93 needs to be merged to upgrade har-validator. Request has to be updated too after that.

**Comment by ahmadnassri** [comment]
`har-validator` has been updated to [`v5.0.3`](https://github.com/ahmadnassri/har-validator/releases/tag/v5.0.3)

**Comment by epoberezkin** [comment]
thank you @ahmadnassri

**Comment by tesserakt** [comment]
Ahh this has not been pushed to NPM.

**Comment by epoberezkin** [comment]
can it be released please?

**Comment by RichardLitt** [comment]
Related to 2654.

**Comment by godspeedelbow** [comment]
+1 We're getting a lot of warnings in `webpack` and `webpack-dev-server` and releasing 2.81.2 fixes all of that.

**Comment by pelotom** [comment]
Anybody home?

**Comment by godspeedelbow** [comment]
2.82.0 is released with har-validator@5.x
