### ISSUE TITLE
body is empty string

### ISSUE THREAD

**Issue by kozer** [request/request#2657]
Hello to every body!
I am trying to make a request as follows 

```
var request = require("request");
var options = { method: 'GET', url: 'https://www.blackhatworld.com/seo/100-scrapebox-proxies.297574/' };
request(options, function (error, response, body) {
if (error) throw new Error(error);
console.log(body);
});
```

But all i get is empty body. I tried with other node js lib(axios) and with curl and all seems ok, i receive the body as i should. Do you know how to solve this issue? Is this a bug?

**Comment by kozer** [comment]
Setting User-Agent solved it.Closing issue.

**Comment by shayanzd20** [comment]
> Setting User-Agent solved it.Closing issue.

hello buddy 
how did you solve it with user agent?
