### ISSUE TITLE
Add an option to keep querystring on redirection

### ISSUE THREAD

**Issue by dsimoes** [request/request#2668]
### Summary

When following redirects, add an option to append to the redirected location the QueryString passed in options. 

### Context

When requesting an URL with certain parameters and the webserver returns 301 to a new location, it happens that the webserver does not include the query string parameters from the original request.

With an option we could configure request to call the new location appending the original query string parameters.

**Comment by Exide** [comment]
This would solve a problem I am encountering as well.

I'm working with a web service that uses an API key query parameter for authorization. Some of the resources available act like head and tail accessors on a linked list. When you send a request it redirects to the appropriate item. Currently the API key is dropped during the redirect which results in an HTTP 401.
