### ISSUE TITLE
hit "Error: Parse Error" with 204 No Content response

### ISSUE THREAD

**Issue by skygragon** [request/request#2669]
As explained in title, just send a simple `request(opt, cb)` and cb will get 'Error: Parse Error': 

```
REQUEST onRequestResponse https://xxxxx 204 { server: 'nginx',
  date: 'Fri, 26 May 2017 04:12:50 GMT',
  'content-type': 'application/json',
  connection: 'close',
  vary: 'Accept, Cookie',
  'x-frame-options': 'SAMEORIGIN',
  allow: 'GET, POST, PUT, DELETE, HEAD, OPTIONS' }
REQUEST reading response's body
REQUEST finish init function https://xxxxx
====>{"bytesParsed":227,"code":"HPE_INVALID_CONSTANT"}
```

| software         | version
| ---------------- | -------
| request          | 2.74.0
| node             | v7.10.0
| npm              |4.6.1
| Operating System | Mac

**Comment by codeuniquely** [comment]
Same

Request 2.81.0
Node v6.10.3
npm 5.4.2
macOS Sierra 10.12.6

{ Error: Parse Error
    at Error (native)
    at Socket.socketOnData (_http_client.js:362:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:547:20)
  bytesParsed: 428,
  code: 'HPE_INVALID_CONSTANT',
  response: undefined }

**Comment by chupindo** [comment]
This error may occurs in case of server sends 204 status code on response, but response body is not empty.
I found this bug for one of my service backend, fixed problem with non-empty response body on 204 status code, and after that the client error described above was fixed.
@skygragon @codeuniquely I hope it helps.

**Comment by skygragon** [comment]
Yes, it fixes my problem.

**Comment by negroscuro** [comment]
To fix this by using a response body empty... how do you do that?
msg.payload is the response body, right? which value has to be set in order to consider it empty? 
""
null
{}
I tried all these and I keep getting the "json parse error"... even doing:
delete msg.payload
I also checked response headers, since cnotent-type couldnt be "application/json", so I also tried to empty it or delete it without success.
