### ISSUE TITLE
request should provide a custom util.promisified() version

### ISSUE THREAD

**Issue by addaleax** [request/request#2673]
Code like

```js
request('https://example.com', (error, response, body) => {
  ...
});
```

can’t be promisified through the usual [`util.promisify()`](https://nodejs.org/api/util.html#util_util_promisify_original) function in Node 8.x because it goes beyond the standard `(error, result) => …` callback pattern. It should be pretty easy to fix that by providing a [custom implementation](https://nodejs.org/api/util.html#util_custom_promisified_functions) that gives e.g. a Promise for a `{response, body}` object.

I know there’s `request-promise`, and I can’t really tell how much of `request` this affects, but it would be awesome if a library that is this popular had even just very simple support for it.

**Comment by danielgindi** [comment]
A-hemmm...
