### ISSUE TITLE
request get ESOCKETTIMEDOUT

### ISSUE THREAD

**Issue by Fov6363** [request/request#2676]
env:
```
node version v7.10.0
uname -a
Linux iZ2zebqg2v1h2g7jmo9endZ 3.10.0-514.6.2.el7.x86_64 #1 SMP Thu Feb 23 03:04:39 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
request package version: "request": "^2.74.0"
```
and use express:4.13.4,
I find some log:
```
{ Error: ESOCKETTIMEDOUT
       at ClientRequest.<anonymous> (/data1/baas_server/baas_x37/node_modules/request/request.js:819:19)
       at Object.onceWrapper (events.js:293:19)
       at emitNone (events.js:86:13)
       at ClientRequest.emit (events.js:188:7)
       at Socket.emitTimeout (_http_client.js:679:10)
       at Object.onceWrapper (events.js:293:19)
       at emitNone (events.js:86:13)
       at Socket.emit (events.js:188:7)
       at Socket._onTimeout (net.js:352:8)
       at ontimeout (timers.js:386:14)
       at tryOnTimeout (timers.js:250:5)
       at Timer.listOnTimeout (timers.js:214:5) code: 'ESOCKETTIMEDOUT', connect: false }
```
I look the source code,get a lot annotation:
```
 var setReqTimeout = function() {
      // This timeout sets the amount of time to wait *between* bytes sent
      // from the server once connected.
      //
      // In particular, it's useful for erroring if the server fails to send
      // data halfway through streaming a response.
      self.req.setTimeout(timeout, function () {
        if (self.req) {
          self.abort()
          var e = new Error('ESOCKETTIMEDOUT')
          e.code = 'ESOCKETTIMEDOUT'
          e.connect = false
          self.emit('error', e)
        }
      })
    }
```
so i want to why the reason and how to fix the bug;
and i don't know how to trigger it,i only find it in log or find request is error;
thanks;

**Comment by liujb** [comment]
@Fov6363  I have the same problem, have you fixed?

**Comment by Fov6363** [comment]
@liujb I update redis conf, set the timeout 0

**Comment by liujb** [comment]
I have solve the problem, It's not about the request. Nginx's problem.

**Comment by hktalent** [comment]
me too
```
node ProxyServer.js
start: 0.0.0.0:8080
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: ESOCKETTIMEDOUT
    at ClientRequest.<anonymous> (/Users/safe/myhktools/node_modules/request/request.js:819:19)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:105:13)
    at ClientRequest.emit (events.js:207:7)
    at Socket.emitTimeout (_http_client.js:722:34)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:105:13)
    at Socket.emit (events.js:207:7)
    at Socket._onTimeout (net.js:402:8)
    at ontimeout (timers.js:469:11)
```

**Comment by Aaayang** [comment]
I found this because the server used the proxy

**Comment by qieguo2016** [comment]
@liujb Hello, you said it is Nginx's problem. How do you fix this problem?

**Comment by bi-kai** [comment]
ESOCKETTIMEDOUT is connection timeouts or read timeouts?
200 request/sec, comes up with servial this error.

**Comment by cancerberoSgx** [comment]
I found if there are too many async requests, then this exception happens in linux. The workaround I've found is doing this: 

setting this options: 
```
agent: false, pool: {maxSockets: 100}
```
Now the timeout can be lying so you might need to increase it.

**Comment by LucusXu** [comment]
I got this error, sometimes with another error.

```
Error: read ECONNRESET
at exports._errnoException (util.js:1034:11)
at TLSWrap.onread (net.js:580:26)
```

**Comment by yousefissa** [comment]
Is anyone still having this issue? I'm sending a lot of requests at once and am having it.

**Comment by greenais** [comment]
The same is here - with single put request to node express -based worker.
No proxy, no streaming, just single request which starts several async promises dealing with DB on worker side.

Suggested agent: false, pool: {maxSockets: 100} in request options didn't help.

Any suggestions from mantainers?

**Comment by deluo** [comment]
`agent: false, pool: {maxSockets: 100}`
 After I set above options errors reduce from 55 to 8.
And then I set **maxSockets:200**  . **only one error left**
I don't know the reason but it does work

**Comment by anosulchik** [comment]
It happens to me with `request 2.88.0`, we occasionally get ESOCKETTIMEDOUT for those requests which were sent out from our app and were processed on receiving part with 200 status code. It looks like a bug somewhere in between request or https modules. Again, request lib throws exception to https request that is processed with 200 http status code? Any ideas are welcome. The problem is easily reproducible on our side (about every 200's request fails) so if you guys interested I can provide more details.

P.S. We did a workaround by implementing retries for failed requests.

**Comment by MumiaIrrequieta** [comment]
Hi,
The documentation says there are "connection timeouts and read timeouts".
Is there a way to set each of them separately?

I'm having a connection timeout sometimes due to an unidentified network issue, and I would like to timeout as fast as I can to be able to retry the request without having to wait for the full timeout that is considering the time to receive the answer.
Thanks.

**Comment by hktalent** [comment]
fix to:
```
EventEmitter = require('events').EventEmitter
EventEmitter.prototype._maxListeners = n_maxLs;
var _fnNull = function(e){if(program && program.verbose)console.log(e)};
process.on('uncaughtException', _fnNull);
process.on('unhandledRejection', _fnNull);

EventEmitter.defaultMaxListeners = n_maxLs;
process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";
process.env.NODE_TLS_REJECT_UNAUTHORIZED = 0;
```
@MumiaIrrequieta @anosulchik @deluo

**Comment by MumiaIrrequieta** [comment]
> fix to:
> 
> ```
> EventEmitter = require('events').EventEmitter
> EventEmitter.prototype._maxListeners = n_maxLs;
> var _fnNull = function(e){if(program && program.verbose)console.log(e)};
> process.on('uncaughtException', _fnNull);
> process.on('unhandledRejection', _fnNull);
> 
> EventEmitter.defaultMaxListeners = n_maxLs;
> process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";
> process.env.NODE_TLS_REJECT_UNAUTHORIZED = 0;
> ```
> @MumiaIrrequieta @anosulchik @deluo

How does this helps setting separate timeouts?
What's the difference between the last couple of lines?

**Comment by anosulchik** [comment]
It doesn't look like a fix for ESOCKETTIMEDOUT for me either. @hktalent can you give more info on this please?

**Comment by SirLancelot-OG** [comment]
Also having this issue. I send out thousands of requests every minute; after about 1 week of running all the connections just immediately start responding with `ESOCKETTIMEDOUT`.

**Comment by firasdib** [comment]
@SirLancelot-OG did you solve it?

**Comment by SirLancelot-OG** [comment]
I poll data every minute, looks like there were some APIs sporadically slowing down and causing the total request to run over a minute which stacked up and led to timeouts. Didn't have the proper logging in place.

Have now moved to using websockets for my data!

**Comment by brion-fuller** [comment]
I get this issue with every request consistently.  I will make a request and the request does pipe and complete.  But if timeout is 10 seconds, I will allows get an 'ESOCKETTIMEDOUT' after 10 seconds of a single request.

**Comment by lucaswxp** [comment]
Anyone fixed this?

**Comment by weiweian90** [comment]
> I have solve the problem, It's not about the request. Nginx's problem.

how to solve the Nginx's problem

**Comment by krestivo-kdinfotech** [comment]
We are having this and it is failing builds... what is this mysterious mystical nginx fix??

**Comment by vigneshkindia** [comment]
facing this issue recently. anyone can help ?
