### ISSUE TITLE
Is request perform return cached data by default?

### ISSUE THREAD

**Issue by romelo** [request/request#2679]
hello, i have this api i'm developing for a bot.
The principle is, a request on the api link return a random question.
There isn't problem with browser because like expected, always have different result.

However, request, after the first fetch, always return the same result. Knowing that the probability of that to happen is very small, my preoccupation is, is it a request issue or cached default behavior ? is there a way to fix that ?

below is used request code

```js
request('https://weloobe.com/quizzcoin/api/get_question?level=easy', (error, response, body) => {
  if (!error && response.statusCode == 200) { }
})

**Comment by dege88** [comment]
As I wrote you also on gitter the problem is the server-side caching, use the cache-control header in your requests
```
const request = require('request');

let count = 0;
let interval = setInterval(() => {
    request({
        url: 'https://weloobe.com/quizzcoin/api/get_question?level=easy',
        headers: {
            'cache-control': 'no-cache'
        }
    }, (error, response, body) => {
        if(!error && response.statusCode == 200){
            console.log(body);
            if(count === 5){
                process.exit();
            }
        }
    });
    count++;
    if(count === 5){
        clearInterval(interval);
    }
}, 2000);
```

**Comment by romelo** [comment]
yeah, as i also wrote on gitter, the alternative solutions i found was to add an optional param with a random value that result to a different url each time. however solution with cache-control is more preferable.

thanks, then close the issue
