### ISSUE TITLE
Set multipart/form-data request encoding

### ISSUE THREAD

**Issue by snajjar** [request/request#2680]
Hello,

Thank you all for the awesome lib.

Here's the problem: currently, any multipart/form-data POST request will reset content-type to:
"multipart/form-data; boundary=((THE BOUNDARY))" and will use utf-8 as the form charset (without specifying the charset in the content type field).

So, 2 questions here:
1) How can i manage to post my form (multipart/form-data, with files) with a charset encoding that is NOT set to UTF-8 ? (I don't own/control the server).
2) Why not giving a "charset" options, that would encode all strings from the form to the specified charset (based on iconv-lite or something), then do the POST request with the appropriate charset header ?

**Comment by simov** [comment]
Use the `headers` option for that:

```js
headers: {'content-type': 'multipart/form-data; boundary=xxx; ...'}
```

**Comment by snajjar** [comment]
How to get the boundary in that scenario ? Isn't the header overwritten by request?

**Comment by jdalrymple** [comment]
Line 1226 is where it is overwritten

```javascript
 if (form) {
    this.setHeader('content-type', 'application/x-www-form-urlencoded; charset=utf-8')
    this.body = (typeof form === 'string') ? form.toString('utf8') : qs.stringify(form).toString('utf8')
    return this
  }
```
