### ISSUE TITLE
"Enabling" javascript

### ISSUE THREAD

**Issue by Glutch** [request/request#2681]
I'm crawling a site which requires javascript to be able to read any information on it.
Is this possible with request? Or some other package?

Or is selenium etc the only solution here?

**Comment by nyuszika7h** [comment]
This is not something `request` can handle. You can use something like `phantomjs`.

**Comment by tanqhnguyen** [comment]
This is not really request's domain. You can use a headless browser to do that. One option apart from phantomjs is [Headless chrome](https://developers.google.com/web/updates/2017/04/headless-chrome)
