### ISSUE TITLE
request with .php url cant seem to be executed

### ISSUE THREAD

**Issue by xueyongg** [request/request#2686]
var url = http://ibibles.net/quote.php?niv-john/1:1-2
request({
            url: url,
            timeout: 2000,
            followAllRedirects: true,
            headers: {
                Host: 'ibibles.net'
            }
        },
        function (error, response, body) {
            console.log(error);
            console.log(response);
            console.log(body);
 });

the request does not seem to be called. Please help! what is wrong? I don't even get an error message

**Comment by RolfKoenders** [comment]
Works perfectly fine. 
```javascript
var request = require("request");
var url = "http://ibibles.net/quote.php?niv-john/1:1-2";
request({
    url: url,
    timeout: 2000,
    followAllRedirects: true,
    headers: {
        Host: 'ibibles.net'
    }
},
function (error, response, body) {
    console.log(body);
});
```
Body is containing the HTML.
