### ISSUE TITLE
request timeout is ignored when try to get an unreach url through a proxy

### ISSUE THREAD

**Issue by barenko** [request/request#2690]
### Summary
request timeout is ignored when try to get an unreach url through a proxy.

### Simplest Example to Reproduce
Use request to get any unreach url with a small timeout:
```js
request({ 
  timeout: 100,
  url: 'https://github.com' }, (err, res) => console.log(err, res) ),
```

Set your proxy (github.com must be unreach through this proxy):
```
export HTTP_PROXY=<your proxy here>
export HTTPS_PROXY=<your proxy here>
``` 
Run the code. You will note that the console will responds only after SO timeout (around 120s)

### Expected Behavior

The code should throws a timeout error after 100ms

### Current Behavior

The code throws a timeout error after 120 seconds

### Your Environment

| software         | version
| ---------------- | -------
| request          | 2.81.0
| node             | 6.10.1
| npm              | 3.10.10
| Operating System | Linux Mint 18

**Comment by sakshamsaxena** [comment]
Does this happen occasionally or always in this case ?

**Comment by barenko** [comment]
This always happen. But only if the address can't be reached through the
proxy.

**Comment by shimba-boomba** [comment]
Any ideas how to solve this issue?

**Comment by etamponi** [comment]
This is happening to me too
