### ISSUE TITLE
Invalid JSON input 

### ISSUE THREAD

**Issue by SanchiSinghal** [request/request#2691]
### Summary

Running the below code gives o/p - Invalid JSON input
### Simplest Example to Reproduce
var request = require("request");

request({
	  method: "POST",
	  url: "http://localhost:5281/api/register",
	  form: {
	  	user: "abc",
	    host: "hcl-IdeaPad-Z585",
	    password: "xyz"
	  }
}, function(error, response, body) {
    console.log(body);
});
on localhost a server is already running at port 5280 and to access its api it's on port 5281.

 json seems to be correct 

### Your Environment

| software         | version
| ---------------- | -------
| request          | 2.81.0
| node             | v7.7.1
| npm              | 4.1.2
| Operating System | ubuntu 14.04

**Comment by RolfKoenders** [comment]
Could you elaborate a bit more? I have just tried your example against a simple restify server and the server receives the form data with no problem? Using the version specified in the issue.

**Comment by SanchiSinghal** [comment]
It worked.I passed a more property i.e json:true .

**Comment by RolfKoenders** [comment]
@SanchiSinghal Could you update the issue by marking it as closed if its resolved and how you fixed it? Thanks

**Comment by SanchiSinghal** [comment]
Fixed it by adding Json : true in the request object 

request({
method: "POST",
url: "http://localhost:5281/api/register",
form: {
user: "abc",
host: "hcl-IdeaPad-Z585",
password: "xyz"
},
**json:true**
}, function(error, response, body) {
console.log(body);
});
