### ISSUE TITLE
Violates streams flowing-mode contract, losing `data` callbacks

### ISSUE THREAD

**Issue by rkaw92** [request/request#2696]
Hi,
This library is currently causing me some trouble due to an idiosyncrasy in streams handling. This is essentially the same as #2565 and #2567 - the `response` stream begins in flowing mode, even though it is expected of Readable Streams in the Node.js world to start as "non-flowing":
https://nodejs.org/api/stream.html#stream_two_modes

I am passing the Response object to some other part of code via a Promise, and it effectively causes a part of the data to be lost, because `data` events are fired too soon, before the first listener is registered.

Additionally, since `response` emulates a ReadableStream (or so the README leads the user to believe), one would expect `response.pause()` to stop the flow and mitigate the quirk. Alas, it does nothing - on the other hand, a `Request.prototype.pause` is implemented which does the same thing, but is outside the readable stream.

An effort should be taken to make the response object's stream API adhere to what the user normally expects of Readable Streams.

The root cause of this behaviour is probably this line: https://github.com/request/request/blob/b12a6245d9acdb1e13c6486d427801e123fdafae/request.js#L1082

It looks like it proxies `data` events - only doing this immediately switches the underlying stream into flowing mode.

Another questionable operation in the code is https://github.com/request/request/blob/b12a6245d9acdb1e13c6486d427801e123fdafae/request.js#L1114 - even if we fix the flowing-mode issue, it will be of no use if the response registers a `data` handler on itself. As an aside, registering event handlers on `this` is considered an anti-pattern, and this is one case where it can be seen.

**Comment by zicai** [comment]
same problem +1

**Comment by jdthorpe** [comment]
I suspect this issue may arrise from [these lines](https://github.com/request/request/blob/b12a6245d9acdb1e13c6486d427801e123fdafae/request.js#L1074-L1083).   Specifically, according to the [NodeJS docs](https://nodejs.org/api/stream.html#stream_event_data) listening to the `'data'` event coerces the stream to enter flowing mode: 

> The 'data' event is emitted whenever the stream is relinquishing ownership of a chunk of data to a consumer. This may occur whenever the stream is switched in flowing mode by calling readable.pipe(), readable.resume(), **or by attaching a listener callback to the 'data' event**
