### ISSUE TITLE
Cookie not added to cookieJar because of silent error

### ISSUE THREAD

**Issue by plouc** [request/request#2704]
### Summary

It should be convenient to be able to customize `RequestJar.setCookie()` options, I wanted to debug why a cookie wasn't collected, and that was apparently because of the following error:

```
Error: Cookie has domain set to a public suffix
    at CookieJar.setCookie (/projects/veggies/node_modules/tough-cookie/lib/cookie.js:933:13)
    at CookieJar.setCookieSync (/projects/veggies/node_modules/tough-cookie/lib/cookie.js:1305:18)
    at RequestJar.setCookie (/projects/veggies/node_modules/request/lib/cookies.js:28:20)
```
I had to manually change the way cookies are parsed to actually understand why the cookie were ignored:

```javascript
// /projects/veggies/node_modules/request/request.js l. 979
targetCookieJar.setCookie(cookie, self.uri.href, {ignoreError: false})
```

### Expected Behavior

Error is raised when I want to.

### Current Behavior

Cookie is not set in cookie jar and I have no clue on why it's not.

### Possible Solution

Add ability to pass option to not ignore errors.

### Context

I'm trying to get response cookies for a lib I'm writing to help testing APIs using cucumber js, https://github.com/ekino/veggies.

### My Environment

| software         | version
| ---------------- | -------
| request          | 2.81.0
| node             | 7.6.0
| yarn              | 0.24.5
| Operating System | OSX 10.12.2

**Comment by plouc** [comment]
I've found a workaround to fix my current issue, however it does not change the fact errors should be enabled.

Also accessing internal implementation should be avoided.

```javascript
cookieJar = request.jar()
cookieJar._jar.rejectPublicSuffixes = false
```

**Comment by mantagen** [comment]
Thanks for this @plouc, your workaround has fixed one of my problems

**Comment by kopax** [comment]
What is `request` in your code sample @plouc please?
