### ISSUE TITLE
Follow Meta Refresh redirects?

### ISSUE THREAD

**Issue by ThatAnton** [request/request#2720]
Is there a way for request to follow Meta Refresh redirects? When requesting http://domain.com/url-1 which has a meta tag of `<meta http-equiv="refresh" content="0; url=http://domain.com/url-2">` the ideal solution would be that request ends on /url-2 without having to capture the initial response, check the body for a Meta Refresh redirect and then firing off a second request for that Meta Refresh url.

Related to [#92](https://github.com/request/request/issues/92)

**Comment by mfrye** [comment]
👍  Just ran into this one too. Seems like parsing the body with a regex might be solution? Cheerio would be cool, but probably overkill. Idk...

**Comment by ozzi-** [comment]
If you are using bash:
```
equiv=$(curl $yourURL -sS | grep -i "http-equiv")
shopt -s nocasematch
regexp='\<meta http-equiv=\"*refresh\"* content=\"*[0-9]*\"*;\s*url=([a-zA-Z0-9\/\.\?=#&.]*)'

if [[ $equiv =~ $regexp ]]; then
  echo "${BASH_REMATCH[1]}"
else
  echo "Couldn't parse equiv url"
  exit 3
fi
```
