### ISSUE TITLE
Listening an event-stream

### ISSUE THREAD

**Issue by tutabeier** [request/request#2727]
Hi all,

I need to consume an API which will sent me some events through SSE. I've tried to use the EventStream library to do it, but since the API only responde via POST method, I was unable to use it.

Since then I've been trying to use `request` to do ti, but with no luck. I didn't understand how I can do a POST to the API and keep the connection open listening the events.

Is there any way to do it?

**Comment by stephenemslie** [comment]
Any update on this? @tutabeier did you ever find a good solution?

**Comment by tutabeier** [comment]
It's been a while, @stephenemslie, but if I remember correctly we just used the Node's HTTP module.
