### ISSUE TITLE
handling a bad statusCode in a stream causing Error: write after end

### ISSUE THREAD

**Issue by bencmbrook** [request/request#2730]
Couldn't find anything about bailing out of a response in the event of a bad `statusCode`.

I have an express web server that's sits between an API server and the client, so I'm piping responses from the API server, through the web server, and down to the client. I want to have `statusCode` error handling. #863 seems similar, but I don't have access to the `req0` object to call `end` on. Node seems to have this `end` [function as well](https://nodejs.org/api/http.html#http_request_end_data_encoding_callback).

```js
module.exports = function(req, res) {
  request.get(options)
  .on('response', apiRes => {
    if (apiRes.statusCode >= 400) {
      console.error("API request failed with code " + apiRes.statusCode);
      // this causes the Error: write after end
      return res.status(500).send();
    }
  })
  .on('error', err => {
    console.error(err);
    return res.status(500).send();
  })
  .pipe(res);
};
```

So, is there a recommended way of bailing out of a stream in the event of a bad status code?

**Comment by nickgrealy** [comment]
I had the same issue: I was attempting to download images, but `401 Unauthorized` responses didn't trigger the `.no('error', ...)` (which meant I ended up downloading a HTML page instead of the image).

I used the following code to handle non-`200 OK` error paths using `Promises`. **N.B.** the file download still  completes, and needs to be "cleaned up":

Hopefully someone else knows a better way to do this? Potentially using the OOTB [`Promises`](https://github.com/request/request/#promises--asyncawait)?

```Javascript
var cachedFile = '...';
var eventHandler = request.get(options2);

// handle the http promise...
var waitForHttp = new Promise(function(resolve, reject) {
    eventHandler.on('response', function(res2) {
        if (res2.statusCode === 200) {
            return resolve(res2);
        }
        return reject(res2);
    });
});
waitForHttp.catch(function() {
    // incorrect status code, delete any locally cached file...
    if (fs.existsSync(cachedFile)) {
        fs.unlink(cachedFile, function(err6) {
            // handle error...
        });
    }
});

// handle the file stream promise...
var waitForStream = new Promise(function(resolve, reject) {
    eventHandler.on('error', reject);
    eventHandler.pipe(fs.createWriteStream(cachedFile)).on('finish', resolve);
});
waitForStream.catch(function() {
    // download failed, delete any locally cached file...
    if (fs.existsSync(cachedFile)) {
        fs.unlink(cachedFile, function(err5) {
            // handle error...
        });
    }
});
Promise.all([waitForHttp, waitForStream]).then(function() {
    // both promises completed successfully...
}, function(response) {
    var statusCode = response.statusCode;
    // one(/both) promise failed...
});
```

**Comment by et** [comment]
@bencmbrook - I like your solution. I was wondering if you were able to get the body of the response though.
