### ISSUE TITLE
How to resolve socket hang up error in node.js

### ISSUE THREAD

**Issue by Traveller198** [request/request#2731]
The following is my code,when i run node sample.js it continously showing the error
  socket hang up
Can anyone suggest help.Thanks.

var qs=require('querystring');
    var http=require('https');

var options = {
"method": "post",
"hostname" : "xxx",
"port" : null,
"path" : "/xxx",
"headers" : {   
    "authorization" : "xxx",
    "content-type" : "application/x-www-form-urlencoded",
    "cache-controller" : "no-cache",
    "postman-token" : "xxx"
}
};

var myToken = "";
var req = http.request(options, function(res){
var chunks = [];
res.on("data", function(chunk) {
    chunks.push(chunk);
});
res.on("end", function(){
     var body = Buffer.concat(chunks);
    myToken = body.toString();
    req.write(qs.stringify({glba:'otheruse',dppa:'none'
}));
req.end();
 });
});

**Comment by papakai** [comment]
Searching also for this possibiliy, subscribing. In the meanwhile I try to figure a way out. Will update here, if I am able to find it.
