### ISSUE TITLE
Unable to parse JSON with some special characters

### ISSUE THREAD

**Issue by mayankdevapplift** [request/request#2735]
I am creating a gist using the API but I am getting the below error response.

{"message":"Problems parsing JSON","documentation_url":"https://developer.github.com/v3/gists/#create-a-gist"}

{
	"public": true,
	"description": "Production",
	"files": {
		".md": {
			"content": " * [add tree dots and update e2e (#2426)](http://github.com/applift/datalift-management/commit/ce7387291cb892f5a8a2a0d563a2e7fdbaff5a05) (Salih Şenol Çakarcı) "
		}
	}
}

After I remove Ş and Ç character it works fine

**Comment by rweszbenner** [comment]
Same problem here, because portuguese has "ç" character.
