### ISSUE TITLE
how to pass params in request.get?

### ISSUE THREAD

**Issue by chenby** [request/request#2736]
how to pass params in request.get?
why can't pass params like jquery?
$.get("xxx.com", { name:"Donald", remarks:"Ducktown" });

**Comment by t3chguy** [comment]
You append them to the url:

`xxx.com?name=Donald&remarks=Ducktown`

**Comment by chenby** [comment]
But,  if i have a params like object, and i must parse it as string.

**Comment by AlesMenzel** [comment]
@chenby 
You can pass them as the query string (qs) parameters:

```
request.get('xxx.com', {qs: {
    name: 'Donald',
    remarks: 'Ducktown'
}}, (err, res, body) => {
   ...
})
```
