### ISSUE TITLE
Wrong encoding on POST with options

### ISSUE THREAD

**Issue by dhasilva** [request/request#2739]
### Summary
When trying to send a POST request with an accented character in the URL it gets reencoded, but only when there is a non-empty `options` object. In the example, I'm trying to send a POST request to `http://localhost:3000/é`, where `é` gets converted to `Ã©`.

### Simplest Example to Reproduce
The backend server:
```js
let express = require('express');
let app = express();
app.post('/:id', function(req, res){
    let id = req.params.id;
    console.log(id);
    res.send(id);
});
app.listen(3000);
```
The request:
```js
let request = require('request');
require('request-debug')(request);
let url='http://localhost:3000/é';
let options1 = {
    body: { test: 0 },
    json: true
};
let options2 = {
    body: JSON.stringify({ test: 0 })
};
let options3 = {
    body: JSON.stringify({ test: 0 }),
    json: false
};
let options4 = {};
request.post(url, options1, function(error, response) {
    console.log(response.body);
});
```

### Expected Behavior
All requests should be logged and returned as `é` by the server.

### Current Behavior
Only `options4` and not using `options` at all returns `é`, where `options1`, `options2` and `options3` return `Ã©`.

### Possible Solution
It seems that when the options are being handled the URL gets reencoded. For this specific transformation to happen, the URL seems to be recognized as `latin-1` before.

### Context
I'm using it to test all the routes in the backend of an app and accented characters can be used in user's ids, resulting in routes like `/user/mário/phone`. The app itself sends the request correctly, this problem only happens when using this request library.

### Your Environment

| software         | version
| ---------------- | -------
| request          | 2.81.0
| node             | 7.10.0
| npm              | 4.2.0
| Operating System | Linux Mint 18.1

**Comment by pandashuai** [comment]
+1
