### ISSUE TITLE
Plans for a new NPM release?

### ISSUE THREAD

**Issue by aschrijver** [request/request#2742]
This project has not been published to NPM since March 2017. Important things have been fixed (personally I need https://github.com/request/request/issues/2483).

Is a new release planned? If not, what is blocking it? If yes, when?

Thanks,

Arnold.

**Comment by NicolasPelletier** [comment]
For me, it is #2751 that I would like to see out there. 

My security team argues that there is a known vulnerability in qs 6.4 so having a new version of request available with #2751 baked in would go a long way to help me release my product.

Thanks.

**Comment by mikeal** [comment]
v2.82.0

**Comment by NicolasPelletier** [comment]
13 minutes between ask and receive ! This is fantastic. Thanks @mikeal .
