### ISSUE TITLE
do not support squid？

### ISSUE THREAD

**Issue by primewang** [request/request#2743]
i use squid create proxy，use curl，wget connect web is ok，but use request  is fail ，report notconnect 😂

use request:
var getRes = function (url) {
    return new Promise((resolve, reject) => {
        request(url, { timeout: 3000 }, function (error, response, body) {
            if (error) {
                reject(error);
            } else {
                resolve(body);
            }
        })
    }).catch(function (error) {
        var err_msg = 'remote server error'
        if (error.code === 'ETIMEDOUT') {
            err_msg = "remote server timeout"
        }
        throw new ApiError(ApiError.Error511SomeError, '', err_msg)
    })
};

getRes('https://api.weixin.qq.com/cgi-bin/token')

export HTTP_PROXY=<your proxy here>
export HTTPS_PROXY=<your proxy here>

The code throws a timeout error
but use curl or wget is ok

software | version
request | 2.81.0
node | v7.6.0
npm | 4.1.2
Operating System | centos 7

**Comment by biofool** [comment]
Squid as installed has 2 ridiculous fatal errors (mime.conf is missing and icons folder is missing)
1) mime.conf (there's a copy in lighttpd since I don't see one in the squid source I downloaded)

cd /usr/local/etc/
cp lighttpd/conf.d/mime.conf squid
then add the icons folder from squid
