### ISSUE TITLE
Callback never called for specific URL

### ISSUE THREAD

**Issue by escopecz** [request/request#2744]
I [tried to ask](https://gitter.im/request/request?at=599345fbbc4647297487ae33) on Gitter in case this is a user error and not a bug, but didn't get any response. I hope I get one here.

### Summary
 The callback is never being called when I try to send the request to this specific url: `https://openmartech.net`

The callback is called for any other URL I try. Just not for this one I need.

### Simplest Example to Reproduce

```js
const request = require('request');
request('https://openmartech.net', (err, response) => {
    console.log('>>>>>>callback called<<<<<<<'); // this is never called
});
```

### Expected Behavior
I expect if I call this script like `node script.js` it will write `>>>>>>callback called<<<<<<<` to the console. It does not.

### Current Behavior
The callback function is never called for this specific URL and its subdomains, subdirectories.

This is the output if I set `request.debug = true;`:
```
REQUEST { uri: 'https://openmartech.net', callback: [Function] }
REQUEST make request https://openmartech.net/
REQUEST onRequestResponse https://openmartech.net/ 301 { date: 'Tue, 15 Aug 2017 19:04:33 GMT',
  server: 'Apache',
  location: 'https://www.openmartech.net/',
  'content-length': '236',
  connection: 'close',
  'content-type': 'text/html; charset=iso-8859-1' }
REQUEST redirect https://www.openmartech.net/
REQUEST redirect to https://www.openmartech.net/
REQUEST {}
REQUEST response end https://www.openmartech.net/ 301 { date: 'Tue, 15 Aug 2017 19:04:33 GMT',
  server: 'Apache',
  location: 'https://www.openmartech.net/',
  'content-length': '236',
  connection: 'close',
  'content-type': 'text/html; charset=iso-8859-1' }
REQUEST make request https://www.openmartech.net/
```

### Your Environment

| software         | version
| ---------------- | -------
| request          | 2.81.0
| node             | 4.3.2
| npm              | 2.14.12
| Operating System | MacOS, Ubuntu

**Comment by zdravko61** [comment]
+1

**Comment by escopecz** [comment]
Any news here? I provided simple code to replicate the issue and I can provide more URLs causing this issue. It's really serious bug.

**Comment by zyvas** [comment]
+1

**Comment by adamreisnz** [comment]
I also seem to be running into a similar issue. No matter what I do, the callback doesn't get called.
