### ISSUE TITLE
how use system http_proxy in request 

### ISSUE THREAD

**Issue by primewang** [request/request#2746]
request({
  url: 'https://api.weixin.qq.com/cgi-bin/token', 
  function (error, response, body){
     console.log(response)
 }
}

in ~/.bash_profile set 
export HTTP_PROXY= A_ip:port
export HTTPS_PROXY=A_ip:port

The code throws a timeout error ,request not use HTTPS_PROXY
but use curl , wget , git  is ok

software | version
request | 2.81.0
node | v7.6.0
npm | 4.1.2
Operating System | centos 7

**Comment by norbix7** [comment]
It will work unless recursive DNS works for local request. 
What if it doesn't ?
