### ISSUE TITLE
Cannot upload multiple files without "[]"

### ISSUE THREAD

**Issue by apoot9999** [request/request#2757]
### Summary
I tried to upload multiple files using requestjs but only the last file in the array was uploaded unless I added "[]" after the key.

### Simplest Example to Reproduce

```js
var formData = {
  attachments: [
    fs.createReadStream(__dirname + '/attachment1.jpg'),
    fs.createReadStream(__dirname + '/attachment2.jpg')
  ]
};
request.post({url:'http://service.com/upload', formData: formData}, function optionalCallback(err, httpResponse, body) {
  if (err) {
    return console.error('upload failed:', err);
  }
  console.log('Upload successful!  Server responded with:', body);
});
```

### Expected Behavior
Server should receive two files.

### Current Behavior
Only the last file in the array was uploaded.

### Possible Solution
Now I could only change the key from "attachments" to "attachments[]" to avoid this problem. But I think this is a bug because the doc says it is ok to use "attachment" as the key to upload multiple files.

| software         | version
| ---------------- | -------
| request          | 2.81.0
| node             | 6.11.2
| npm              | 3.10.10
| Operating System | macOS

**Comment by alanfortlink** [comment]
Can I work with this issue?

**Comment by apoot9999** [comment]
Of course.

**Comment by SumeshDubey** [comment]
Even I'm getting the same issue. Is this resolved

**Comment by jeremy-j-ackso** [comment]
I ended up having to use the "advanced method" in https://github.com/request/request#forms.

```
var r = request.post('http://service.com/upload', function optionalCallback(err, httpResponse, body) {...})
var form = r.form();
form.append('file[]', fs.createReadStream(__dirname + '/file1.jpg'));
form.append('file[]', fs.createReadStream(__dirname + '/file2.jpg'));
r();
```

Would be nice to just be able to pass an Array or something.
