### ISSUE TITLE
agent: false without pool: false uses globalAgent?

### ISSUE THREAD

**Issue by jayflo** [request/request#2758]
### Summary

It looks common to get the `ESOCKETTIMEDOUT` error and some solutions say to use `agent: false`.  This might lead one to believe that a new agent is being created *per request* as noted in the Node.js docs: https://nodejs.org/dist/latest-v6.x/docs/api/http.html#http_class_http_agent

### Expected Behavior

`agent: false` should create a new agent instance for each request?

### Current Behavior

1. If the `pool` option is unset then the `globalPool` is used: https://github.com/request/request/blob/master/request.js#L172
2. This means the `agent` is set to the return value of `self.getNewAgent()`: https://github.com/request/request/blob/master/request.js#L487
3. Which is the `globalAgent`: https://github.com/request/request/blob/master/request.js#L687

### Possible Solution

Not saying this is a bug, but perhaps I didn't understand the options.  The docs say:

> pool - an object describing which agents to use for the request. If this option is omitted the request will use the global agent (as long as your options allow for it). Otherwise, request will search the pool for your custom agent. If no custom agent is found, a new agent will be created and added to the pool. Note: pool is used only when the agent option is not specified.

In this case `agent` is specified but I am not sure what "as long as your options allow for it" means.  Assuming the issue brought up here is accurate, solutions could be:

1. Be explicit in the documentation that `agent: false` does not mean `pool: false`
2. If `agent: false` and `pool` is unset, then default `pool` to `false` and document it.

### Context

Possibly related to `ESOCKETTIMEDOUT` errors.

---

If the above looks accurate and a PR is desired, please let me know and I can certainly create one.

**Comment by umutm** [comment]
It'll definitely be great if the usage of agent, pool and maxSockets are documented clearly.
