### ISSUE TITLE
Sending "Connection: Close" header when using https proxy with NTLM auth

### ISSUE THREAD

**Issue by jit06** [request/request#2766]
### Summary

My Company is using Squid as an https proxy together with a NTLMv2 authentication. I use px (https://github.com/genotrance/px) to handle the NTLM part. Basicaly, px creates a local proxy responsible for NTLM authentication.
But when I use Bower or Npm which use this "request" module, the connection is closed by the proxy, whereas the same GET request works fine with Firefox (using px as proxy too).

### Simplest Example to Reproduce
- Use a Squid proxy with NTLM authentication
- Install px and set the proxy host in the ini file
- launch "px --debug"
- try to install something with bower : "bower install jquery"

### Expected Behavior

Bower, which uses this request module, should download any package flawlessly

### Current Behavior

Bower fail to download packages. Example with jquery :  
bower not-cached    https://github.com/jquery/jquery-dist.git#*
bower resolve       https://github.com/jquery/jquery-dist.git#*
bower download      https://github.com/jquery/jquery-dist/archive/3.2.1.tar.gz
bower retry         Download of https://github.com/jquery/jquery-dist/archive/3.2.1.tar.gz failed with **ECONNRESET**, retrying in 1.5s

### Possible Solution

With some analysis of px logs, it seems that the request module send the http header "Connection: Close" while asking the proxy to connect to the target url. So with such a header in the request, the squid proxy simply close the connection as asked.

By forcing the Connection header to "Keep-Alive", the problem disapear.
For example, I added the line "self.headers['Connection'] = 'Keep-Alive'" right after "self.headers = self.headers ? copy(self.headers) : {}" in request.js, Request.prototype.init

But this is quite an ugly fix, and it would be interesting to find out why a connection close is issued.

### Context

My company (pretty big) use a proxy with authentication for all HTTP and HTTPS queries. We use Npm and Bower in automated build as well as on our developpement machines.
For now, we did the above modification.

### Your Environment

| software         | version
| ---------------- | -------
| request          | 2.67.0
| node             | 6.11.3
| npm              | 3.10.10
| Operating System | Windows 8.1 Version 6.3 (Build 9600)
| px                 | 0.2.1

**Comment by DuBistKomisch** [comment]
I have the same problem using cntlm and squid. Here's some traffic between cntlm and squid dumped using tcpdump:

request:
```
CONNECT api.vivi.io:443 HTTP/1.1
host: api.vivi.io:443
Connection: close
Proxy-Connection: keep-alive
Proxy-Authorization: NTLM TlRMTVNTUAABAAAABbIIogYABgAkAAAABAAEACAAAABWSVZJU0FNRE9N
Content-Length: 0

HTTP/1.1 407 Proxy Authentication Required
Server: squid/3.5.23
Mime-Version: 1.0
Date: Mon, 30 Oct 2017 11:52:14 GMT
Content-Type: text/html;charset=utf-8
Content-Length: 3655
X-Squid-Error: ERR_CACHE_ACCESS_DENIED 0
Vary: Accept-Language
Content-Language: en
X-Cache: MISS from vivi-mini-ubuntu
X-Cache-Lookup: NONE from vivi-mini-ubuntu:3128
Via: 1.1 vivi-mini-ubuntu (squid/3.5.23)
Connection: close
```

curl:
```
CONNECT api.vivi.io:443 HTTP/1.1
Host: api.vivi.io:443
User-Agent: curl/7.38.0
Proxy-Connection: keep-alive
Proxy-Authorization: NTLM TlRMTVNTUAABAAAABbIIogYABgAkAAAABAAEACAAAABWSVZJU0FNRE9N
Content-Length: 0

HTTP/1.1 407 Proxy Authentication Required
Server: squid/3.5.23
Mime-Version: 1.0
Date: Mon, 30 Oct 2017 11:53:54 GMT
Content-Type: text/html;charset=utf-8
Content-Length: 3663
X-Squid-Error: ERR_CACHE_ACCESS_DENIED 0
Vary: Accept-Language
Content-Language: en
Proxy-Authenticate: NTLM TlRMTVNTUAACAAAADAAMADgAAAAFgomiwqg984UkmjMAAAAAAAAAAGwAbABEAAAABgEAAAAAAA9TAEEATQBEAE8ATQACAAwAUwBBAE0ARABPAE0AAQAeAFYASQBWAEkALQBNAEkATgBJAC0AVQBCAFUATgBUAAQAAgAAAAMAIAB2AGkAdgBpAC0AbQBpAG4AaQAtAHUAYgB1AG4AdAB1AAcACAAMIpbCdVHTAQAAAAA=
X-Cache: MISS from vivi-mini-ubuntu
X-Cache-Lookup: NONE from vivi-mini-ubuntu:3128
Via: 1.1 vivi-mini-ubuntu (squid/3.5.23)
Connection: keep-alive
```

As you can see the only difference is the `Connection: close` header present from request, and squid responds with no NTLM challenge, closing the connection. Strangely it works if I use basic directly with squid, despite the header, so perhaps this is a bug in squid. I also can't understand why `Connection: close` would be sent when opening a tunnel though.
