### ISSUE TITLE
Error object contains certificate in text

### ISSUE THREAD

**Issue by tsouk** [request/request#2768]
### Simplest Example to Reproduce

```js
const auth = {
   "cert": "THESE ARE THE CONTENTS OF THE CERT",
   "key": "THESE ARE THE CONTENTS OF THE KEY",
   "ca": "THESE ARE THE CONTENTS OF THE CA",
};

const options = {
  url: 'https://www.aurl.that/doesntexist/really',
  cert: auth.cert,
  key: auth.key,
};

request(options)
.catch((err) => {
  console.log(err);
});
```

### Expected Behavior
The error object should not include the cert, key or ca information, unless there is a very good reason why these should be part of the error (and I can't thing of one) they should be silenced, as error objects generally are supposed to be caught and thrown in different layers. Error objects are also supposed to be logged. I understand that a solution is to only take the secure info from the error object and log these, leaving the insecure. But I still don't understand why the error object needs to contain the whole cert/ket/ca. 

### Current Behavior
When making an SSL request, with a cert/ca/key, any error object returned contains the cert/ca/key information.

### Possible Solution
Take out any sensitive information from the options object of the error object, 

### Your Environment

| software         | version
| ---------------- | -------
| request          | 2.81.0
| node             | v6.11.3
| npm              | 5.4.2
| Operating System | Centos7

**Comment by benjaminkay93** [comment]
This is still a thing, it even prints out the private keys, which could lead to them being dumbed in log files for anyone to just scoop up and impersonate you :/
