### ISSUE TITLE
HTTP Digest Authentication over POST

### ISSUE THREAD

**Issue by KingRial** [request/request#2777]
### Summary
I am 
unable to use Digest Authentication over a simple POST request

### Simplest Example to Reproduce
```javascript
request.post({
        url: 'URL to digest server',
        auth: {
          user: 'username',
          pass: 'password',
          sendImmediately: false
        },
        form: { lvalue: value }
      }, ( oError , oResponse , sBody) => {
... whatever you neeed ....
      });
```
### Expected Behavior
I expect to see two requests: the first should fail with error 401 and the second should be able to handle the original request

### Current Behavior
For some reasons I haven't understood the "sendImmediately" set to false is ignored.

When the request is launched, the method "basic" of "auth.js" is called twice; the first is using the "sendImmediately" option to "false"; the second one is set to "true".
The second internal call to the method seems to be the problem; it seems it doesn't receive the arguments set by the user.

### Possible Solution
I had to force "sendImmediately" to "false" before the following line: https://github.com/request/request/blob/master/lib/auth.js#L29 to see the library work correctly with HTTP Digetst

### Your Environment
| software         | version
| ---------------- | -------
| request          | ^2.81.0
| node             | 6.10.0
| npm              | 3.10.10
| Operating System | Windows 10

**Comment by emilian** [comment]
I can't get digest authentication to work with PUT/POST either. Tried the method above but still not working. It seems like the PUT request is sent without the authorization header so it fails right away.

**Comment by KingRial** [comment]
I am still using the previous workaround with POST methods.
Usually you also need to enable the "Cookies" to let the digest authentication work correctly

```
...
const request = require('request');
const cookies = request.jar();
request.defaults({
  jar: cookies
});
...
```

and then use the "jar" also in the request post configuration:

```
...
request.post({
        url: 'URL to digest server',
        auth: {
          user: 'username',
          pass: 'password',
          sendImmediately: false
        },
        jar: cookies,
        form: { lvalue: value }
      }, ( oError , oResponse , sBody) => {
... whatever you neeed ....
      });
...
```

**Comment by emilian** [comment]
I still wasn't able to make it work with the request library, even after setting up the cookies. The authorization header just wasn't being sent at all. 

In the end, I went with a lower-level library that implements post from this link:

https://github.com/vinger4/node-http-digest-client

I only needed to upload a file to a WebDAV server using digest, so the library above worked for me.
