### ISSUE TITLE
Please update tough-cookie to 2.3.3

### ISSUE THREAD

**Issue by HowWeRollingham** [request/request#2780]
### Summary

Dependency`tough-cookie@2.3.2` (and lower) contains a [REDOS vulnerability](https://nodesecurity.io/advisories/525) which causes pipelines to fail

### Possible Solution

Update package.json to require `tough-cookie@2.3.3`

**Comment by HowWeRollingham** [comment]
Fixed by #2776

**Comment by mikeal** [comment]
fixed.
