### ISSUE TITLE
Query string encoded incorrectly

### ISSUE THREAD

**Issue by xPaw** [request/request#2797]
v2.83.1.

I am not sure how to fix this issue, but it seems to boil down to `request` not encoding the query string correctly. I tested this with expressjs and requestb.in.

I was testing these 2 urls:
```
http://localhost:9002/unicodeq/?q=ıoı-test
http://localhost:9002/unicodeq/?q=русский-текст-test
```

But on the server they are received as
```
q: 1o1-test (converted from latin letters to ascii)
q: @CAA:89-B5:AB-test
```

The request code is rather basic:
```js
		request.get({
			url: uri,
			maxRedirects: 5,
			timeout: 5000,
			headers: {
				"User-Agent": "Mozilla/5.0"
			}
		});
```

How would I fix this issue so that the URL is requested correctly?

**Comment by voz** [comment]
@xPaw putting unicode query params as part of the `qs` object seems to do the trick.

In your example

```js
request.get({
     url: 'http://localhost:9002/unicodeq',
     maxRedirects: 5,
     timeout: 5000,
     headers: {
       "User-Agent": "Mozilla/5.0"
     },
     qs: {
       q: 'русский-текст-test'
     }
  });
```

**Comment by xPaw** [comment]
@voz I'm requesting user provided urls, seems rather unnecessary for me to parse the url when `request` itself should be doing it anyway.

**Comment by voz** [comment]
@xPaw I agree, that's just a workaround that worked for me in a similar case.

**Comment by xPaw** [comment]
Stale bot damn it.
