### ISSUE TITLE
Cannot pipe s3 object readstream to PUT request

### ISSUE THREAD

**Issue by rash805115** [request/request#2800]
[StackOverflow Link](https://stackoverflow.com/questions/42877791/cannot-pipe-s3-object-readstream-to-put-request).
Reason for asking it here is because I suspect there might be a bug while piping an external read-stream to `put/post` methods. The boundary of multipart data may not be set properly.

I have a simple scenario. I need to read an object from S3 and pipe its output to `PUT` request. Here is my `client.js` code using request module.
```javascript
// client.js
let AWS = require('aws-sdk')
let request = require('request')

let bucket = 'my_bucket'
let filename = 'path/to/file.zip'

let host = 'localhost'
let port = 8080

let s3 = new AWS.S3({
  . . .
})

let readStream = s3.getObject({
  Bucket: bucket,
  Key: filename
}).createReadStream()

let formData = {
  applicationType: 'my_app_type',
  applicationName: 'my_app_name',
  upload: {
    value: readStream,
    options: {
      filename: 'my_file_name.zip',
      contentType: 'application/zip'
    }
  }
}

request.put({
  url: 'http://' + host + ':' + port + '/bootstrap',
  formData: formData
}, function (error, response, body) {
  if (error) throw error
  console.log(body)
})
```

And, here is my `server.js` code.
```javascript
// server.js
let http = require('http')
let Busboy = require('busboy')
let events = require('events')
let fs = require('fs')

let host = 'localhost'
let port = 8080

let compressedCodeLocation = './code.zip'

let handleRequest = function (request, response) {
  let eventEmitter = new events.EventEmitter()
  let inputStreamWriter = fs.createWriteStream(compressedCodeLocation)
  inputStreamWriter.on('finish', function () {
    eventEmitter.emit('input.stream.saved')
  })
  let busboy = new Busboy({
    headers: request.headers
  })

  busboy.on('file', function (field, file) {
    file.pipe(inputStreamWriter)
  })
  busboy.on('field', function (field, val) {
    console.log(field + ': ' + val)
  })
  eventEmitter.on('input.stream.saved', function () {
    let stats = fs.statSync(compressedCodeLocation)
    response.statusCode = 200
    response.end(JSON.stringify(stats))
  })

  request.pipe(busboy)
}

let server = http.createServer(handleRequest)
server.listen(port, host, function () {
  console.log('Server started on ' + host + ':' + port)
})

let handleShutdown = function () {
  server.close(function () {
    console.log('Server stopped on ' + host + ':' + port)
  })
}
process.on('SIGTERM', handleShutdown)
process.on('SIGINT', handleShutdown)
```

I am getting this error:

    File [upload] got 58 bytes
    events.js:160
          throw er; // Unhandled 'error' event
          ^
    
    Error: Unexpected end of multipart data
        at /pots/cnc/node_modules/dicer/lib/Dicer.js:62:28
        at _combinedTickCallback (internal/process/next_tick.js:67:7)
        at process._tickCallback (internal/process/next_tick.js:98:9)

The funny thing is, if I save the file locally first and then `createReadStream` for that local file, it works:

    let formData = {
      ...
      upload: {
        value: fs.createReadStream(localPath + "/" + filename),
        options: {
          ...
        }
      }
    };

**Comment by rash805115** [comment]
I got answers to my [StackOverflow Question](https://stackoverflow.com/questions/42877791/cannot-pipe-s3-object-readstream-to-put-request), but I am not sure of the reasoning behind why it works. Can someone provide an explanation?

**Comment by davidlanger** [comment]
I had a smiliar problem. It worked for me once I added `knownLength` to the `options`: 

```
upload: {
    value: readStream,
    options: {
      filename: 'my_file_name.zip',
      contentType: 'application/zip'
      knownLength: 423424
    }
  }
```

You can get the file size for example by using the headObject func:
```
return s3.headObject({ Key: key, Bucket: bucket })
		.promise()
		.then(res => res.ContentLength);
```

I explained it to me that for multipart requests you need the size in advance. Somehow form-data (https://github.com/form-data/form-data) automatically detects the size it needs to send when using fs.createReadStream. That does not work for streams from s3, thus you need to supply it yourself

**Comment by rash805115** [comment]
Very cool. Closing this issue now.

**Comment by Ncifra** [comment]
Hey @davidlanger 
I have the same problem, but from a stream that gets returned as a Decipher from a pipe(). So is there any way to get the length from that stream?  Because all the solutions I am seeing so far seem to revolve around S3 and Azure, which have their own methods for such a thing.

Thank you

**Comment by davidlanger** [comment]
@Ncifra I have no experience at all with Decipher + Streams, but I would imagine that deciphering results in a certain ratio, say you have 10 character ciphered, then you might have 2 deciphered, so you could calculate your size beforehand. But that means that you need to know the size of the file you are deciphering. Bug again, this is just a guess, it might also be that deciphering is not linear to the input length.

Another possible solution would be to use the http header [`Transfer-Encoding: chunked`](
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Transfer-Encoding).

**Comment by Ncifra** [comment]
> Another possible solution would be to use the http header Transfer-Encoding: chunked.

Unfortunately, at least with request, it throws an ECONNRESET error,  while the receiving API doesn't seem to respond at all. Without the header, multer on the receiving API throws the "Part terminated early due to unexpected end of multipart data".

Either way, I have opened an issue on form-data about this: https://github.com/form-data/form-data/issues/409. Feel free to check it out as you have a more thorough idea to the state of the code.

Thanks again.
