### ISSUE TITLE
Nodejs Hangs up on Receiving 202 statusCode and retries automatically after 2 mins

### ISSUE THREAD

**Issue by appunni-dishq** [request/request#2810]
### Context
I am creating a nodejs client server for my angular app. Request is sent to process large data, while data is being processed we send back 202 status Code. I use same handler Callback for all requests which basically Emails me request log details on call back and options are as follows . It is working for many requests which doesn't send back 202 but only 200. But at this particular request the nodejs server itself stops responding to further requests. From main server logs we know that the request from nodejs server is going through but response is not handled at nodejs. And whole nodejs is stuck up and no further requests to the nodejs server are entertained. I have to restart server for everything to work again. And there are no error in logs available. For some reason nodejs server sends a request 2 min after first request which got 202, and that gets resolved to 200 as processing is over by then. This part of retry is not programmed by me but for some reason done by request Library itself

```
var options = {
    url: process.env.REQUEST_URL,
    method: "GET",
    json: true,

    headers: {
        "Content-Type": "application/json",
        'Accept': 'application/json',
        "Authorization": "Token " + process.env.TOKEN
    }
};
```
```
request(options, handleResponse.bind({res, options}));
```
```
function handleResponse(error, response, body) {
    if (error || parseInt(response.statusCode) > 399) {
        Email(error, response, body, this.options);
        this.res.status(response.statusCode).json({"response": "Error", "message": "Something bad happened"});
    } else {
        this.res.status(response.statusCode).json(body).end();
    }
}
```

| software         | version
| ---------------- | -------
| request          | 2.83.0
| node             | v8.4.0
| npm              | v5.3.0
| Operating System | 16.04 LTS

**Comment by romanlab** [comment]
I have a similar issue where the whole process hangs. It's a process that loops over urls and GETs them. At some point, the process hangs. I added a 10 minutes timeout but no response comes in. I also have a `setTimeout` with a log message elsewhere to make sure the event loop isn't stuck and it stops logging at the same time as the request hangs.
