### ISSUE TITLE
Crash on sending HTML data

### ISSUE THREAD

**Issue by wilkerHop** [request/request#2816]
### Summary

I have an API that returns a random HTML img tag, but when I consume it with Request, the app crashes at `{app}/node_modules/express/lib/response.js:999` 
### Simplest Example to Reproduce

```js
app.get('/test/1', (req, res) => {
	request('https://memestore.herokuapp.com/memes/random/tag', (error, response, body) => {
		if (error) return console.log('error:', error); // Print the error if one occurred
		console.log('body:', body); // Print the HTML 
		res.render('index',body)
	});
})
```
### Context

I'm trying to get the img tag the API provides and send it to an ejs view. The api also have a route that gives and random object with the image link, but I think it's better to use the already made tag.
### Environment

| software         | version
| ---------------- | -------
| request          |TypeError: Cannot create property '_locals' on string '`<img class="img-responsive" src="http://www.profissionaldeecommerce.com.br/wp-content/uploads/2016/03/mkt-meme-1.jpg">`'
| node             | v6.11.4
| npm              | 3.5.2
| Operating System | Ubuntu 17.10

**Comment by slidenerd** [comment]
```
return new Promise((resolve, reject) => {
            request(options, (error, response, body) => {
                if (response.statusCode === 200 && !error) {
                    resolve(body)
                }
                else {
                    reject(error)
                }
            })
        })
```

Is this crashing as well?
