### ISSUE TITLE
Url will always be encoded

### ISSUE THREAD

**Issue by maunier** [request/request#2818]
I have a url like this: http://qipu.qiyi.domain/query/templateQuery?template_name=get_live_videos&param=order_field:order_all&format=QIPU_ENTITY&size=11

The ':' in 'param' will be encoded, can provide a config options to disable the encode?

**Comment by cqq626** [comment]
My url contains the symbol '|' and I do not want it encoded into '%7C' too.

**Comment by maunier** [comment]
@cqq626 
request({
    url:...
    qsStringifyOptions: {
       encode: false
    }
})

**Comment by xeagl3x** [comment]
I cannot seem to get this to work. Using 2.83.0. 

Here is what I am using for the options
`var connectOpts = {
        "url": "https://somedomain.com/page?$f=job('a')",

        "headers": {
            "Content-Type": "application/json",
            "Accept": "application/json"
        },
        "auth": {
            "user": "theuser",
            "pass": "thepass",
            "sendImmediately": false
        },
        "qsStringifyOptions": {
            "encode": false
        },
        "useQuerystring": true
    };`

**Comment by stkrzysiak** [comment]
@xeagl3x The encode option is for the query string, in your snippet I don't see a query string piece, so this would explain why it doesn't work.
