### ISSUE TITLE
toString() Failed (Buffer)

### ISSUE THREAD

**Issue by iamcharles777** [request/request#2826]
buffer.js:513
    throw new Error('"toString()" failed');
    ^

Error: "toString()" failed
    at Buffer.toString (buffer.js:513:11)
    at Request.<anonymous> (/root/dan-phillips-web/node_modules/request/request.js:1137:39)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/root/dan-phillips-web/node_modules/request/request.js:1085:12)
    at IncomingMessage.g (events.js:291:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by lassmann** [comment]
I am having the same issue here. I am trying to make a post where one input has another request.
    const rp = require('request-promise');
    const options = {
    'url': 'http://urltomakepost.com',
    'headers': {
    'Content-Type': 'application/json',
    }
}
    options['formData'] = {
        media: {
            value: rp.get(fileUrl),
            options: {
                filename: 'preview.mp4'
            }
        }
    };

    return rp.post(options)
        .then(response => {
            console.log(resonse);
        })
        .catch(error => console.log(error));

watching on port 3000
buffer.js:556
  if (encoding === undefined) return buf.utf8Slice(start, end);
                                         ^

Error: "toString()" failed
    at stringSlice (buffer.js:556:42)
    at Buffer.toString (buffer.js:633:10)
    at Request.<anonymous> (/home/ubuntu/filemanager/aws-file-manager/node_modules/request/request.js:1137:39)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.source.emit (/home/ubuntu/filemanager/aws-file-manager/node_modules/delayed-stream/lib/delayed_stream.js:30:21)
    at IncomingMessage.<anonymous> (/home/ubuntu/filemanager/aws-file-manager/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
error: Forever detected script exited with code: 1

**Comment by jjcad** [comment]
I'm on v2.83.0 and getting pretty much the same error. We're using `request` via [couchdb-nano](https://github.com/apache/couchdb-nano) and it is definitely a pretty big block of json.

```
Error: "toString()" failed
    at stringSlice (buffer.js:556:42)
    at Buffer.toString (buffer.js:633:10)
    at Request.<anonymous> (/opt/back-end-arkenstone/node_modules/request/request.js:1137:39)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/opt/back-end-arkenstone/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1055:12)
buffer.js:556
  if (encoding === undefined) return buf.utf8Slice(start, end);
```

**Comment by isaacweathers** [comment]
Anyone found a fix or work around for this?

**Comment by dlarr** [comment]
Hello I am having same issue, and no fix yet.

I am receiving that big buffer with size = 20024104 

Trying to process it line by line as it comes from a flat file.

```js
const es = require('event-stream');
const stream = require('stream');

// 1st create a stream 
let bufferStream = new stream.PassThrough();
bufferStream.end(myBuffer);

// 2- split it by end of files
// 3- parse each lines
bufferStream                     
	.pipe(es.split())                  <==== CRASHES HERE 
	.pipe(es.mapSync(function(line){

			// pause the readstream
			bufferStream.pause();

			// DO SOME PROCESSING OF THIS LINE

			// resume the readstream,
			bufferStream.resume();

		}).on('error', function(err){
			console.log('Error while reading file.' + err);
		}).on('end', function(){
			console.log('end event !');
		}).on('close', function(){
			console.log('close event !');
		})
	);
```

**Comment by dlarr** [comment]
Other method, same result, 

This time I logged buffer size and kMaxLength : 

```js
 var buffer = require('buffer');
 console.log('buffer.kMaxLength = ',  buffer.kMaxLength); // => 2147483647
 console.log('hexaviaFile.buffer.byteLength = ',  hexaviaFile.buffer.byteLength); // => 413567671
```

Here is the new method providing exact same error : 
```js
const s = fs.createReadStream(hexaviaFile.buffer)
                .pipe(es.split())
                .pipe(es.mapSync(function(line){

                        // pause the readstream
                        s.pause();

                        //  DO SOME PROCESSING OF THIS LINE

                        // resume the readstream
                        s.resume();

                    }).on('error', function(err){
                        console.log(err)
                    }).on('end', function(){
                        console.log('End event');
                    }).on('close', function(){
                        console.log('Close event');
                    })
                );
```

I am just trying to read this buffer line by line, syncrhounsly... If anyone has a solution... (I Will post on stack for this.)

**Comment by eagleeye** [comment]
fix of this landed in Node 10.0.0 - https://github.com/nodejs/node/commit/63eb267c34198c4bece62cb6432bb2bceb399de6
- at least we will have meaningful error when upgrade to Node 10

**Comment by jorbriib** [comment]
In the current version (recommended for most users) 8.11.2 is fixed this error.

**Comment by dlarr** [comment]
Hello, I found a way to overcome this. I am splitting the incomming buffer in chunks and then pipe the stream with the splitter : 

```js

class Splitter extends Transform {
    constructor(options){
        super(options);
        this.splitSize = options.splitSize;
        this.buffer = Buffer.alloc(0);
        this.continueThis = true;
    }
    stopIt() {
        this.continueThis = false;
    }

    _transform(chunk, encoding, cb){

        this.buffer = Buffer.concat([this.buffer, chunk]);

        while ((this.buffer.length > this.splitSize || this.buffer.length === 1) && this.continueThis){
            try {
                let chunk = this.buffer.slice(0, this.splitSize);

                this.push(chunk);
                this.buffer = this.buffer.slice(this.splitSize);
                if (this.buffer[0] === 26){
                    console.log('EOF : ' + this.buffer[0]);
                }
            } catch (err) {
                console.log('ERR OCCURED => ', err);
                break;
            }
        }
        console.log('WHILE FINISHED');
        cb();
    }
}
```

The to read your stuff simply do

```js
let bufferStream = new stream.PassThrough();
bufferStream.end(hugeBuffer);
let splitter = new Splitter({splitSize : 170}); // In my case I have 170 length lines, so I want to process them line by line
let lineNr = 0;
bufferStream
      .pipe(splitter)
      .on('data', async function(line){

          line = line.toString().trim();

          splitter.pause(); // pause stream so you can perform long time processing
          lineNr++;
          
         if (lineNr === 1){
              // DO stuff with 1st line
              
         } else {
              splitter.stopIt(); // Break the stream and stop reading so we just read 1st line
         }

         splitter.resume() // resumestream so you can process next chunk
    }).on('error', function(err){
            console.log('Error while reading file.' + err);
            // whatever
     }).on('end', async function(){
           console.log('end event');

           // Stream has ended, do whatever...
           
    });

```

**Comment by andeanfog** [comment]
Buffers can be larger than the largest string possible in JavaScript.
When you convert a buffer to a string, the operation can throw that exception.

The maximum size is of a string is `process.binding('buffer').kStringMaxLength`, about 1 GB.
Don't use strings larger than 1 GB.
