### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by ypanyukov** [request/request#2828]
v 2.83.0

{
  "message": "Maximum call stack size exceeded",
  "stack": "RangeError: Maximum call stack size exceeded\n    at Url.parse (url.js:101:37)\n    at Object.urlParse [as parse] (url.js:97:13)\n    at Request.init (/app/node_modules/request/request.js:237:20)\n    at new Request (/app/node_modules/request/request.js:128:8)\n    at request (/app/node_modules/request/index.js:53:10)\n    at /app/node_modules/request/index.js:100:12\n    at /app/node_modules/request/index.js:100:12\n    at /app/node_modules/request/index.js:100:12\n    at /app/node_modules/request/index.js:100:12\n    at /app/node_modules/request/index.js:100:12\n    at /app/node_modules/request/index.js:100:12\n    at /app/node_modules/request/index.js:100:12\n    at /app/node_modules/request/index.js:100:12\n    at /app/node_modules/request/index.js:100:12\n    at /app/node_modules/request/index.js:100:12\n    at /app/node_modules/request/index.js:100:12\n    at /app/node_modules/request/index.js:100:12\n    at /app/node_modules/request/index.js:100:12\n    at /app/node_modules/request/index.js:100:12\n    at /app/node_modules/request/index.js:100:12\n    at /app/node_modules/request/index.js:100:12\n    at /app/node_modules/request/index.js:100:12",
  "level": "error",
  "timestamp": "2017-12-11 16:37:26"
}

**Comment by bobohuochai** [comment]
I was occured the same problem and solved it. 
The reason is using reqeust.defaults method to a variable like 'baseRequest'. And using 'baseRequest' in every reqeust .Notice ,the variable 'baseRequest' is the same one even through in different reqeusts.
So **the variable 'baseRequest' are deeply nested**.  
The solution is using a method to replace the variable 'baseRequest'

**Comment by netpoetica** [comment]
Can you elaborate on this @ypanyukov - what does the request look like, request method, etc - some details may help :)

**Comment by gingerP** [comment]
Hi, @netpoetica.
I reproduced a similar error with request@2.88.0:
```
RangeError: Maximum call stack size exceeded
    at Request.init (/home/vinni/workspace/qutrek/request-call-stack/node_modules/request/request.js:237:20)
    at new Request (/home/vinni/workspace/qutrek/request-call-stack/node_modules/request/request.js:128:8)
    at request (/home/vinni/workspace/qutrek/request-call-stack/node_modules/request/index.js:53:10)
    at /home/vinni/workspace/qutrek/request-call-stack/node_modules/request/index.js:61:12
    at /home/vinni/workspace/qutrek/request-call-stack/node_modules/request/index.js:100:12
    at /home/vinni/workspace/qutrek/request-call-stack/node_modules/request/index.js:100:12
    at /home/vinni/workspace/qutrek/request-call-stack/node_modules/request/index.js:100:12
    at /home/vinni/workspace/qutrek/request-call-stack/node_modules/request/index.js:100:12
    at /home/vinni/workspace/qutrek/request-call-stack/node_modules/request/index.js:100:12
    at /home/vinni/workspace/qutrek/request-call-stack/node_modules/request/index.js:100:12
```
with the following code:
```
'use strict';

const net = require('net');
let request = require('request');

const server = net.createServer((sock) => {
    sock.end('Hello world\n');
});
server.listen(0, () => {
    const port = server.address().port;
    console.log('Listening on port ' + port);
    runTest(port).catch((error) => {
        console.error(error);
        process.exit(0);
    });
});

async function runTest (port) {
    let index = 0;
    while (index < 5000) {
        console.log('Request #' + index);
        await get(port);
        index++;
    }
}

function get (port) {
    return new Promise((resolve, reject) => {
        request = request.defaults();
        request.post('http://127.0.0.1:' + port, (error, httpResponse, body) => {
            resolve(body);
        })
    });
}
```
This is due to the fact that we call defaults method on request wrapper and after that we reassign local request variable. So the following request.defaults method call to add one more nested call for request.post. 
Hope this helps.
