### ISSUE TITLE
Webpack bundle includes every feature whether it's used or not

### ISSUE THREAD

**Issue by markbjerke** [request/request#2834]
This makes the library ill suited for universal javascript.  There are many features that blow up the size of the bundle that should be opt-in.  There should be a core for the library that could be bundled for the browser leaving off features such as HAR for example.

**Comment by Silviu-Marian** [comment]
Try https://www.npmjs.com/package/browser-request

**Comment by KayHS** [comment]
@markbjerke Did you ever find a solution to this?
