### ISSUE TITLE
persistent jar between session with to/fromJSON()

### ISSUE THREAD

**Issue by gravsten** [request/request#2838]
I need to store the cookies between two sessions.
For this, all it takes is adding the following to lib/cookies.js:

```
RequestJar.prototype.toJSON = function () {
  var self = this
  return self._jar.toJSON()
}
RequestJar.prototype.fromJSON = function () {
  var self = this
  return self._jar.fromJSON()
}
```

I hope this is agreeable to you and that such change can be merged into the official distribution.

**Comment by andrewsosa** [comment]
I'm interested in similar functionality. I'd like to be able to store a Cookie Jar in my express-session, which ideally would be as simple as saying:

```javascript
req.session.jar = request.jar();
```

And then using those cookies persistently via:

```javascript
request.get(url, { jar: req.session.jar }, myCallback); 
```
