### ISSUE TITLE
no_proxy environment variable ignored

### ISSUE THREAD

**Issue by JPinlac** [request/request#2849]
no_proxy environment variable ignored for localhost

With http_proxy and https_proxy env set, and no_proxy set. Requests are still made through the proxy. 

Not using any options, just a simple request 
```
request.get("http://localhost:8000", function(err, res, body) {
   //code
});
```

**Comment by JPinlac** [comment]
I found a work around.
```
request.get({
  uri: "http://localhost:8000", 
  proxy: ""}, 
function(err, res, body) {
   //code
});
```

**Comment by danjo519** [comment]
If any dev sees this, or if anyone ends up here from Google:

I was having a similar error with my `no_proxy` environment variable.

It seems, based on looking at the source for `request/lib/getProxyFromURI.js` that it only supports `no_proxy` that does not use wildcard asterisks.

Changing my environment variable to just dot fixed this.
e.g. `*.example.com` to `.example.com`.
