### ISSUE TITLE
Unwanted behavior of request on some linux distros.

### ISSUE THREAD

**Issue by zer09** [request/request#2851]
### Summary
So far this issue is reproducible on Ubuntu and Fedora 27.

The problem is that when you send another instance of ```request``` inside the callback of a previous ```request```, the second request is somewhat swallowed or hiding somewhere and will just come up if there is another instance of request is send.
And this also will prevent the use of promise chaining.

I already post it on SO [Unable to send request from request callback](https://stackoverflow.com/questions/48135641/unable-to-send-request-from-request-callbackl).

### Simple Example to Reproduce
I did a sample project https://github.com/zer09/request_test
It include the express server and a electron app.
There is the 3 menus to test "Get Request", "Post Request", "Post Promise Request".
The result can be seen on console.

### Expected Behavior
You should see the result of the second request.

### Current Behavior
The second request is somewhat swallowed.

### Possible Solution
Hmmm, sorry, I don't have any idea for now, I don't have depth understanding how request works at the moment, basically I just starting studying JS since last year.

### Context
Actually this works on MS Windows (tested on vm) but using on Fedora the problem exists. If you create app using electron, then possibly this wont work on some distro of linux.

### Your Environment

| software         | version
| ---------------- | -------
| request          | 2.83.0
| node             | 8.9.3
| npm              | 5.6.0
| express         | 4.15.5
| Operating System | Fedora 27

**Comment by VladimirPal** [comment]
I observe same behaviour

**Comment by zer09** [comment]
@VladimirPal on what OS did you tested it?

Thanks

**Comment by ckyleda** [comment]
I see this behaviour on Antergos (Essentially Arch Linux).

Could someone also verify this for me?

Use a standard request call inside the promise (not a request-promise call) and see if that callback ever triggers - for me, it does not.
