### ISSUE TITLE
Deprecated dependency

### ISSUE THREAD

**Issue by cassiopagnoncelli** [request/request#2862]
NPM fires a deprecation warning upon installing,

      npm WARN deprecated node-uuid@1.4.8: Use uuid module instead

I guess replacing `node-uuid` with `uuid` should seamlessly solve the issue.

**Comment by AlbertHambardzumyan** [comment]
@cassiopagnoncelli Are you on v2.83.0 ?

**Comment by cassiopagnoncelli** [comment]
I was using @latest by 10 days ago
