### ISSUE TITLE
Request with method: HEAD returns body in response

### ISSUE THREAD

**Issue by rejhgadellaa** [request/request#2863]
### Summary
I'm trying to get the headers for a url without waiting for the entire body. It seems I should be able to do that by setting the "method" option to "HEAD":

### Simplest Example to Reproduce
```
var requestOpts = {
    url: "http://www.google.com",
    method: "HEAD",
};
request.get(requestOpts, function (error, response, body) {
    console.log(error, response);
});
```

### Expected Behavior
According to the spec of HTTP methods, HEAD should get the headers, not the body:

> Same as GET but returns only HTTP headers and no document body
> https://www.w3schools.com/tags/ref_httpmethods.asp

### Current Behavior
The response object contains a `body` property that contains (in this examples' case) html output.

### Possible Solution
N/A

### Context
I'm trying to figure out what the 'final' redirect url is for an Icecast stream. The problem is that if I use GET the request keeps going because it's a never-ending radio stream:
http://playerservices.streamtheworld.com/api/livestream-redirect/VERONICA.mp3

### Your Environment

| software         | version
| ---------------- | -------
| request          | ^2.83.0
| node             | 8.2.1
| npm              | 5.6.0
| Operating System | Windows 10 x64

**Comment by plroebuck** [comment]
Maybe don't use the shorthand method `request.get` as it probably hardcodes the method.

```
var requestOpts = {
  url: "http://www.google.com",
  method: "HEAD"
};
request(requestOpts, function (error, response, body) {
  if (error !== null) {
    console.error(error);
    return;
  }
  console.log('headers:', response.headers);
  return;
});
```
