### ISSUE TITLE
multiple cookies, but only one got sent

### ISSUE THREAD

**Issue by angelochen960** [request/request#2869]
Hi,

trying to send a request with some cookies:

```
var request = require('request');

var j = request.jar();
var cookie = request.cookie("key1=val1;key2=val2")
j.setCookie(cookie, 'http://127.0.0.1:3000');

request( { url: 'http://127.0.0.1:3000/', jar: j }, function (error, response, body) {
});
```
in the server side, was expecting cookie header to be : key1=val1; key2=val2, but what turned out is only key1=val1

how to make the key2=val2 appear too? Thanks

**Comment by Rubatharisan** [comment]
What was the solution?
`
var request = require('request');

var j = request.jar();
var cookie = request.cookie("key1=val1");
var cookie2 = request.cookie("key2=val2");
j.setCookie(cookie, 'http://127.0.0.1:3000');
j.setCookie(cookie2, 'http://127.0.0.1:3000');

request( { url: 'http://127.0.0.1:3000/', jar: j }, function (error, response, body) {});
` 

?

**Comment by mactive** [comment]
me to
