### ISSUE TITLE
put stream fails with larger files >64kB

### ISSUE THREAD

**Issue by m67hoff** [request/request#2870]
this is hopefully not an issue,  just a "understanding" problem on my side.  
BTW:  I first asked at https://stackoverflow.com/questions/48776919/node-js-request-module-put-stream-fails-with-larger-files-64kb  but probably its better here.

 I use a small node.js express server to test/simulate a file upload download server with HTTP put/get:
```
app.use(express.static(SERVER_DIR))
app.put('/put/:filename', (req, res) => {
  req.pipe(fs.createWriteStream( SERVER_DIR + req.params.filename));
  res.send('OK')
})
```
the above server works fine if tested with (shell) curl put/get:
```
curl "http://localhost:8765/put/" -T 100MB.file
curl "http://localhost:8765/100MB.file" -o 100MB.get
```
(tested up to 1GB - check if uploaded /downloaded files are equal with cmp)

My problem ist to upload (put) the files with a node.js client using the request module:
```
fs.createReadStream(filename).pipe(request.put(SERVER_URL+'put/'+filename))
```

this upload works fine with small files > 64kB but it fails for larger. uploading file with 65400Byte is working / file with 65450Byte is not working - it stops after 65410Byte / EOF error.

**How can I change this limit ?**

BTW: download (get) with the node.js request client app:
`
request(SERVER_URL+filename).pipe(fs.createWriteStream(filename))  
`
works with large 1GB files.

**Comment by MPNull** [comment]
Same with:
`request('http://google.com/doodle.png').pipe(fs.createWriteStream('doodle.png'))`
If file size is >64.39KB I get only part of the file up to 64.39KB only.
