### ISSUE TITLE
Piping with gzip leads to inconsistent response

### ISSUE THREAD

**Issue by kbrandwijk** [request/request#2887]
If I use request with `gzip: true` and pipe it directly to the response, that response does not contain the `Content-Encoding` header. Also, the `Content-Length` header is set to the length of the compressed data, but the data is sent uncompressed. This causes my client to read a partial response.

I would expect either one of the two:
- Data is piped uncompressed, and headers are set accordingly
- Data is piped compressed, with the right headers (preferred)

**Comment by kbrandwijk** [comment]
Any feedback on this? It's quite a blocker...

**Comment by iernie** [comment]
I think I'm having the same issue

**Comment by kbrandwijk** [comment]
Stale bot, I believe this is not fixed yet...

**Comment by chuyik** [comment]
I found a way to prevent sending incorrect `Content-Length` header to client, that is to wrap the response with `PassThrough`.

```js
const stream = request({
    url,
    gzip: true,
    encoding: null
})
const pass = new PassThrough()
ctx.body = stream.pipe(pass)
```

If you want to keep some headers, you might want to use [mimic-response](https://github.com/sindresorhus/mimic-response) library to mock a response.
