### ISSUE TITLE
Regression: Hawk update broke compatibility with Node 6.10

### ISSUE THREAD

**Issue by constb** [request/request#2891]
For some reason that I don't quite understand, npm in Node6 completely ignores the fact that `sntp` package.json has `"node": ">=8.9.0"` in it and installs this very version as a dependency of updated `hawk`. 30 minutes ago you updated `request` and my app has completely gone out of production with `SyntaxError: exports.time = async function (options = {} ) {`

The problem is, I don't install `request` directly, it is installed as a dependency of another package I have no control over. And it requires `"request": "^2.53.0"`. Also I cannot change node version, since 6.10 is the latest available in AWS Lambda.

I really have no idea how to fix this on my end. Please help…

**Comment by hutchy2570** [comment]
This has happened to us also.  We're using Jest, which pulls in this module, so as of an hour ago all our builds are now broken.  We're also working with AWS Lambda so have to target Node 6.

Given how many other people are likely in the same situation this could break a lot of things!

**Comment by aivus** [comment]
Same for us.
Builds: https://travis-ci.org/website-scraper/node-website-scraper/builds/352227289?utm_source=github_status&utm_medium=notification

**Comment by mdluo** [comment]
Same error for firebase cloud functions

```sh
Detailed stack trace: /user_code/node_modules/request/node_modules/sntp/lib/index.js:19
exports.time = async function (options = {}) {
                     ^^^^^^^^

SyntaxError: Unexpected token function
```

Fixed by locking version at `"request": "2.83.0"`.

**Comment by mickhansen** [comment]
https://github.com/request/request/pull/2880

**Comment by cpu220** [comment]
+1

**Comment by lironzluf** [comment]
+1
Getting this too

**Comment by Nubzor** [comment]
+1

Try to add request 2.38.0 to your devDependencies - should help.

**Comment by balazs4** [comment]
same here, installing `jest@21` with `yarn@1.3.2` => broken CI

**Comment by xu3u4** [comment]
![image](https://user-images.githubusercontent.com/6767433/37278124-a88b6bd4-2621-11e8-9d38-23503717f3fd.png)
Same here.

**Comment by ranlandau** [comment]
We are failing deployment to production with all of our services.
The quick fix is massive work.

Any word from @simov ??

**Comment by constb** [comment]
I made a workaround using `npm shrinkwrap`. I added file next to `package.json` under the name of `npm-shrinkwrap.json`:

```
{
  "dependencies": {
    "some-package": {
      "version": "2.0.0",
      "from": "some-package@^2.0.0",
      "dependencies": {
        "request": {
          "version": "2.83.0",
          "from": "request@^2.53.0"
        }
      }
    },
    "other-package": {
      "version": "1.0.2",
      "from": "other-package@^1.0.2",
      "dependencies": {
        "request": {
          "version": "2.83.0",
          "from": "request@^2.83.0"
        }
      }
    }
  }
}
```

Now `npm install` puts previous `request` version in node_modules.

Then I had to patch `node_modules/serverless-webpack/lib/packagers/npm.js` to include `npm-shrinkwrap.json` into the build instead of `package-lock.json`. Now after deploy I have working lambdas.

Hopefully this will be fixed soon…

**Comment by kenken17** [comment]
Same here...

**Comment by AgeeHuang** [comment]
+1...

**Comment by yutackall** [comment]
+1

**Comment by iagafonov** [comment]
+1 =(

**Comment by washswat** [comment]
+1

**Comment by ranlandau** [comment]
+10000000000000000000000000000000000000000000

**Comment by ozamarripa** [comment]
+1

**Comment by simov** [comment]
I've reverted the update to Hawk 7.x and hopefully this is going to fix the issue, because right now the tests on TravisCI are failing for Node >= v8 for some reason, the tests for Node < v8 are failing because of sntp dev dep, and locally the test are failing for yet another reason .. Anyway will publish a new version shortly.

**Comment by hashar** [comment]
In case it can help, the dependency chain we had:

OK: nodemw@0.11.0 -> request@2.83.0 -> hawk@6.0.2 -> sntp@2.1.0

FAIL: nodemw@0.11.0 -> request@2.84.0 -> hawk@7.0.7 -> sntp@3.0.1

Thank you @simov !!!

**Comment by fott1** [comment]
Request version `2.83.0` fixed it, for now.

**Comment by simov** [comment]
v2.85.0 is published

**Comment by balazs4** [comment]
Thank you for the quick response/fix. It works again. :+1: :100:
Maybe you could consider to introduce such a `breaking change` as a `major` update instead of a `minor`?
I guess it would be less 'stressy' for all of us. :sweat_smile:

**Comment by androidfanatic** [comment]
+1, fixed now. Thanks.

**Comment by lironzluf** [comment]
+1
Can confirm it's fixed

**Comment by Rakk4403** [comment]
+1 Good

**Comment by jamescodesthings** [comment]
+1 Circle is happy with us now. Ty.

**Comment by simov** [comment]
The first goal would be to get our tests working again. I guess that's the reason why this got merged in without anyone noticing it. 

Then `hawk` should not be updated to > v7 anytime soon, because of the breaking change for **Node < 8.9.0**. It was excluded from Greenkeeper long time ago, exactly because of the constant breaking changes: https://github.com/request/request/blob/v2.85.0/package.json#L82-L87 it was for Node < v4 at that time

For reasons why we won't/can't bump the major version here, you can read @mikeal's comments about it in this issue tracker.

Thanks for your patience! :+1:

**Comment by txiaocao** [comment]
+1

**Comment by simov** [comment]
see https://github.com/request/request/pull/2943
