### ISSUE TITLE
header field "host" includes port 80

### ISSUE THREAD

**Issue by zhaotian2470** [request/request#2894]
As the following code:
[https://github.com/request/request/blob/bbb3a0bbbe173342de8462a2171765a39681b248/request.js#L294](https://github.com/request/request/blob/bbb3a0bbbe173342de8462a2171765a39681b248/request.js#L294) 
If URI is "http://myhost:80/path", header field "host" will be set as "myhost:80".
Is it correct?

Note: before commit ff6d6c6e7a3b2c36618b5d1db662e10c929696e3, "host" header field will be set as "myhost"

**Comment by paambaati** [comment]
Recently, most clients (including curl) and browsers have started to drop the `:80` & `:443` port suffixes in the Host header, and include it only when it is neither of the two. Dropping the port prefix for known services is still RFC-compliant; see http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.23

Examples of other projects stripping the port suffix —

1. Ruby - https://github.com/ruby/ruby/blob/d46336e71731aa64d71d4573b2741b7de43ec340/lib/net/http/generic_request.rb#L18
2. waterlink/rack-reverse-proxy#3
3. twilio/twilio-node#151
4. https://github.com/bokeh/bokeh/pull/3513
5. https://github.com/websocket-client/websocket-client/pull/248
6. https://stackoverflow.com/a/19169664

Related `request` issue — https://github.com/request/request/issues/515

**Comment by paambaati** [comment]
@zhaotian2470 This can be closed now, as v2.88.1 fixes this.
