### ISSUE TITLE
Timeout is not working as expected

### ISSUE THREAD

**Issue by khanna91** [request/request#2895]
Hi, 

I'm currently using request version 2.34.0 and its working as expected with respect to timeout.

But when I upgraded the package to 2.83, it never respects the timeout period mentioned. Then I upgraded the package to the latest version, 2.85.0 and in this sometimes it's getting timed out stipulated time (desired behaviour) but sometimes it's not.

Can anybody help me?

I'm setting timeout period to be 1 sec, if the API doesn't respond under 1 sec, I need to trigger the timeout flow

**Comment by osxpinot** [comment]
There are some other posts about this same issue. Additionally, there are issues with timeouts involving HTTP proxies as well. In one instance the sockets timed out but never got killed and the app was not able open anymore sockets. People have submitted pull reports, but they've never been merged. I would recommend look at a different HTTP client library at this point.

**Comment by Woor** [comment]
Any recommendations or forks @osxpinot ?

**Comment by osxpinot** [comment]
I would try JCMais/node-libcurl

**Comment by ferfabricio** [comment]
@khanna91 I have a similar issue when I'm trying to set the timeout with a string.
 I was setting the options with:
```
{
  timeout: '1000'
}
```
And timeout not work properly.
When I change to a Integer (in my case this configuration came from process.env) the timeout was respected.

**Comment by terrosdesigns** [comment]
Hi,

Any update on this issue ? 

Timeout option is still not taken into account on post requests.
