### ISSUE TITLE
request many times for download image,some request had no respones

### ISSUE THREAD

**Issue by li-biao** [request/request#2897]
### Simplest Example to Reproduce

```js
testDownFile(index){
            let request = require("request");
            request({  
                url: "https://img.feihutv.cn//im/files/2018-03-24/15218624462684375cf9056b58154457b3c2dc3fd169d",  
                encoding:null  
            }, (err, response, body) => {
                console.log("err",index,err,response);  
             }).on('response', function(response) {
                // unmodified http.IncomingMessage object
                let totalData = response.headers['content-length'];
                let receiveData = 0;
                response.on('data', function(data) {
                  // compressed data as it is received
                  receiveData+=data.length;
                  let pcent = Number(receiveData)*100/Number(totalData);
                  console.log("index="+index,pcent);
                })
              })
        }

for(let i=1;i<=3;i++){
              this.testDownFile(i);
          }
```

![qq 20180324170257](https://user-images.githubusercontent.com/26321292/37862288-5ae92bc4-2f85-11e8-921d-1dc306a8271b.png)
![qq 20180324170304](https://user-images.githubusercontent.com/26321292/37862290-5d6a1318-2f85-11e8-9ffb-84c794e4c94d.png)
![qq 20180324170311](https://user-images.githubusercontent.com/26321292/37862291-60576ea4-2f85-11e8-9d31-c12145073c03.png)

when index=2 down over ,Until now,it's no any console.log,please help me 
### Your Environment

| software         | version
| ---------------- | -------
| request          |
| node             | v6.10.2
| npm              | 3.10.10
| Operating System | win32

**Comment by knoxcard** [comment]
**npm install image-downloader**

` require('image-downloader').image({
                url: url,
                dest: app.nconf.get('static:folder') + '/images/dispensaries/' + disp_rec.id +'.jpg'
              }).then(ret => {
})
`

**Comment by knoxcard** [comment]
Your hitting the target server too fast with that for loop.  You need to implement setTimeout() to delay the loop.
