### ISSUE TITLE
node request socket hang up when using a Transform Stream instead of a Readable Stream

### ISSUE THREAD

**Issue by Gcaufy** [request/request#2899]
### Summary
I need to do some replacement in the stream, so I use https://github.com/eugeneware/replacestream,
replaceStream returns a Transform Stream.

### Simplest Example to Reproduce
```js
const replaceStream = require('replacestream');

var formData = {
  my_field: 'my_value',
  my_file: fs.createReadStream(__dirname + '/unicycle.jpg').pipe(replaceStream(/a/g, 'b'))
};
request.post({url:'http://service.com/upload', formData: formData}, function(err, res, body) {});
```

### Current Behavior
Getting error 'scoket hang up'

```
[13:57:42] ERR! Error: socket hang up
[13:57:42] ERR!     at createHangUpError (_http_client.js:331:15)
[13:57:42] ERR!     at Socket.socketOnEnd (_http_client.js:423:23)
[13:57:42] ERR!     at emitNone (events.js:111:20)
[13:57:42] ERR!     at Socket.emit (events.js:208:7)
[13:57:42] ERR!     at endReadableNT (_stream_readable.js:1055:12)
[13:57:42] ERR!     at _combinedTickCallback (internal/process/next_tick.js:138:11)
[13:57:42] ERR!     at process._tickCallback (internal/process/next_tick.js:180:9)
```

### Your Environment

| software         | version
| ---------------- | -------
| request          | v2.85.0
| node             | v8.9.4
| npm              |
| Operating System | MacOS

**Comment by mjy78** [comment]
Under the hood request uses the form-data library to infer information about the form fields. In particular in can infer the file size and content type from fs (file system) streams, but not necessarily all streams (ie. in your case a transform stream).

You can pass in manually the file options as such...
```
var formData = {
  my_field: 'my_value',
  my_file: {
    value: fs.createReadStream(__dirname + '/unicycle.jpg').pipe(replaceStream(/a/g, 'b')),
    options: { filename: 'unicycle.jpg', contentType: 'image/jpg', knownLength: 123 }
};
```

The catch is you'd need to be able to determine the known length of the file after you've run it through your transform stream.

An easier solution might be just to pipe the file from your transform stream to a temp location on disk, then create a regular file headstream to pass into your request call.

**Comment by Gcaufy** [comment]
I found this in https://github.com/form-data/form-data

> Form-Data can recognize and fetch all the required information from common types of streams (fs.readStream, http.response and mikeal's request), for some other types of streams you'd need to provide "file"-related information manually:

I solved this issue by using file contents and other file  related info instead of a stream.

**Comment by YarGnawh** [comment]
@Gcaufy  i'm also using the `replacestream` package. does your response lose all the http response header?

**Comment by Gcaufy** [comment]
@YarGnawh you were saying `replacestream` works for you?
