### ISSUE TITLE
Can't request via localAdress and proxy simultaneously

### ISSUE THREAD

**Issue by mrspartak** [request/request#2901]
### Summary
I have many interfaces on server, need to make requests via them and also using proxy, because proxy server has request limit per IP. Linux's curl works fine, but I can't make request via 'request'

### Simplest Example to Reproduce

```js
request.get('https://api.ipify.org?format=json', {
	json: true,
	timeout: 4000
}, (error, response, body) => {
	console.log('1:', body)
})

request.get('https://api.ipify.org?format=json', {
	json: true,
	localAddress: 'my second local IP',
	timeout: 4000
}, (error, response, body) => {
	console.log('2:', body)
})

request.get('https://api.ipify.org?format=json', {
	json: true,
	proxy: 'proxy IP',
	timeout: 4000
}, (error, response, body) => {
	console.log('3:', body)
})

request.get('https://api.ipify.org?format=json', {
	json: true,
	localAddress: 'my second local IP',
	proxy: 'proxy IP',
	timeout: 4000
}, (error, response, body) => {
	console.log('4:', body)
})
```

### Expected Behavior
My main IP is banned, so I expect to see logs from 1, 2 and 4. But I get only from 1 and 2. 4th don't work, because localAdress is not applied.

curl --interface 'second interface' -x 'proxy IP' website
This works fine

| software         | version
| ---------------- | -------
| request          | 2.85.0
| node             | 9.2.0
| npm              | 5.8.0
| Operating System | Ubuntu 14.04.5

**Comment by mrspartak** [comment]
Also it is work this way
`
const http = require('http')
var req = http.request({
	host: 'proxy ip',
	port:  'proxy port',
	localAddress: 'my second local IP',
	timeout: 4000,
	method: 'GET',
	path: 'https://api.ipify.org?format=json'
}, (res) => {
	res.on('data', (data) => {
		console.log('5:', data.toString())
	})
})
req.end();
`

**Comment by MattRh** [comment]
Have same issue

**Comment by MattRh** [comment]
After dome investigation, I found that this happens because `localAddress` is not set for tunnel here https://github.com/request/request/blob/master/lib/tunnel.js#L71
