### ISSUE TITLE
Question：how all options use function,so use this.*

### ISSUE THREAD

**Issue by hktalent** [request/request#2902]
'''
var baseRequest = request.defaults({
  headers: {'x-token': 'my-token'}
})

Question：how all options use function,so use this.*, this.uri, this.url

so:

var baseRequest = request.defaults(function()
{
      var h = this. headers;
      h["referer"] = this.url;
});

all options suport function and Object

thanks
'''

**Comment by hktalent** [comment]
@vyushin 
```
const request = require('request');

const defaultOptions = function(args) {
// how get url, here?
this.uri?
this.url
thanks 

  console.log(args); // Some arguments
  console.log(this); // There is "request"
  return {
    method: 'GET',
    timeout: 4000,
    json: true
  }
};

const r = request.defaults( defaultOptions.bind(request)('some arguments') );

r('https://api.ipify.org?format=json', null, (error, response, body) => {
  console.log(body);
});
```

**Comment by vyushin** [comment]
@hktalent, what URL do you want to get in default options? You have to fill default options yourself. `request` hasn't a URL by default. So, if you have to do it yourself then you know what you had wrote in default options, isn't it?
