### ISSUE TITLE
Suggestion: Add default User-Agent/Accept header when send request

### ISSUE THREAD

**Issue by isayme** [request/request#2906]
It will be great if we have default user-agent header, then we can mark the request source.

And I would expect (with request version 2.85.1):
```
User-Agent: request/2.85.1
Accept: */*
```

**Comment by isayme** [comment]
issue #2738 will be solved if we have the default headers~

**Comment by SimonSchimmels** [comment]
Are there plans to implement a default User-Agent header?

**Comment by landons-migo** [comment]
While it might seem like a good feature, that would break a bunch of other implementations. It’s generally a bad idea to automatically add headers—doing so would hurt a lot more people than it would help.
