### ISSUE TITLE
why not support response headers has content-encoding: br??

### ISSUE THREAD

**Issue by dmwin72015** [request/request#2907]
if response headers   has content-encoding: br,
response body can't   JSON.parse

**Comment by plroebuck** [comment]
Don't think you provided enough information for anyone to help you. Are you having this problem in browser or node app? Browser-wise, you checked [compatibility](https://caniuse.com/#feat=brotli)? If it's your client code making the call, perhaps use [shrink-ray](https://www.npmjs.com/package/shrink-ray). See also Desaulniers "[Better than Gzip Compression with Brotli](https://hacks.mozilla.org/2015/11/better-than-gzip-compression-with-brotli/)" article.

**Comment by dege88** [comment]
Duplicate of https://github.com/request/request/issues/2866

**Comment by paramsinghvc** [comment]
Its a valid issue, why is it closed. The dup issue also has not provided a valid solution.

**Comment by mikeal** [comment]
request is in maintenance mode and we’re not accepting any new features. for what it’s worth, I did implement this in `bent`.
