### ISSUE TITLE
Error not reported when connection aborted whilst downloading file 

### ISSUE THREAD

**Issue by logidelic** [request/request#2918]
### Summary
When using request to download a large file and stream to disk, if the connection is aborted (due to some sort of network or server error), request never emits an error event.

### Simplest Example to Reproduce

```
var file = fs.createWriteStream(OUT_FNAME);
file.on('error', function(err) {
    console.log('ERROR');
    console.log(err);
});
file.on('finish', function() {
    console.log('FINISHED!');
});

request.get({url:DOWNLOAD_URL, timeout:30000})
.on('error', function(err) {
    console.log('ERROR');
    console.log(err);
})
.pipe(file);
```

Output is `FINISHED!`. The error logs are never displayed.

### Expected Behavior
In the github documentation for request it states:

> To easily handle errors when streaming requests, listen to the error event before piping:
> ```
> request
>   .get('http://mysite.com/doodle.png')
>   .on('error', function(err) {
>     console.log(err)
>   })
>   .pipe(fs.createWriteStream('doodle.png'))
> ```

This doesn't work (no error reported) in my test cases.

### Your Environment

| software         | version
| ---------------- | -------
| request          |2.85.0
| node             |8.2.1
| electron             |1.8.4
| Operating System |Ubuntu 17

**Comment by kybarg** [comment]
Same with me. stream shuts down unfinished without error reporting

**Comment by logidelic** [comment]
After posting this report I did a lot of investigation to try to figure out what was going on. Finally, I implemented my own request using `http.request` but ran into the same issue!

I'll let you read up yourself but I think this happens (in `http.request`) for "historic" reasons. In any case, you can detect the situation there by listening for the `end` event and then checking to see if `res.complete` is false (if so, the download aborted before completion), as in:

```
var req = http.request(..., function(res) {
    if(res.statusCode === 200 || res.statusCode === ...) {
        res.on('end', function() {
            if(!res.complete) {
                console.log('Incomplete download!!!')
            }
        });
    }
});
```

I haven't looked at the `request` module's source but I'll have to guess that it is just inheriting the same issue. My (strong) opinion is that regardless of `http.request`'s foibles, the request module should abstract this away and report it as a normal error. I'm not going to argue about it though, since I've worked around it by implementing my own. :)
