### ISSUE TITLE
About  response.statusCode

### ISSUE THREAD

**Issue by jianghuadongstar** [request/request#2920]
### Simplest Example to Reproduce

```js
var request = require('request');
request('http://www.baidu.com', function (error, response, body) {
    console.log(response.statusCode)// 200
})
```

### Expected Behavior

I get 200, but it should be 307.

### Your Environment

| software         | version
| ---------------- | -------
| request          |2.85.0
| node             |6.9.5
| npm              |3.10.10
| Operating System | MacBook Pro (13-inch, 2016, Two Thunderbolt 3 ports)

**Comment by yegodz** [comment]
@jianghuadongstar I get 200 when I run the request from the command line - using curl. Why do you expect to get 307?

`
$> curl -I http://www.baidu.com
HTTP/1.1 200 OK
Server: bfe/1.0.8.18
Date: Wed, 02 May 2018 20:29:57 GMT
Content-Type: text/html
Content-Length: 277
Last-Modified: Mon, 13 Jun 2016 02:50:23 GMT
Connection: Keep-Alive
ETag: "575e1f6f-115"
Cache-Control: private, no-cache, no-store, proxy-revalidate, no-transform
Pragma: no-cache
Accept-Ranges: bytes

`
