### ISSUE TITLE
Still cant solve GTA--autoDriving---problem

### ISSUE THREAD

**Issue by briancheung560** [request/request#2928]
Dear all,
   While i practise the tutorial about GTA by my Mac10.16 Anaconda---
Intro and Screen reading - Python plays Grand Theft Auto V p.1   

with following code:
import numpy as np
from PIL import ImageGrab
import cv2
while(True):
    printscreen_pil =  ImageGrab.grab(bbox=(0,40,40,40))##800,640))
    printscreen_numpy =   np.array(printscreen_pil.getdata(),dtype='uint8').reshape((printscreen_pil.size[1],printscreen_pil.size[0],3)) 
    
    cv2.imshow('window',printscreen_numpy)
    if cv2.waitKey(25) & 0xFF == ord('q'):
        cv2.destroyAllWindows()
        break
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
Problem 1:  
If i dont change 
printscreen_pil =  ImageGrab.grab(bbox=(0,40,800,640))   to  
printscreen_pil =  ImageGrab.grab(bbox=(0,40,40,40))
  It raises the Error---- ValueError : cannot reshape array of size 1920000 into shape (600,800,3)
 But i change ,the display window is too small.. 
How should i fix the code? 
  ( i have searched all websites but still cant find.)
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
Problem 2:  
import numpy as np
from PIL import ImageGrab
import cv2
while(True):
    printscreen_pil =  ImageGrab.grab(bbox=(0,40,40,40))
    printscreen_numpy =   np.array(printscreen_pil.getdata(),dtype='uint8').reshape((printscreen_pil.size[1],printscreen_pil.size[0],3)) 
    
    cv2.imshow('window',printscreen_numpy)
    if cv2.waitKey(25) & 0xFF == ord('q'):
        cv2.destroyAllWindows()
        break
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
Even above problem passed, it raises another problem

  It raises the Error---- error: /Users/travis/build/skvark/opencv-python/opencv/modules/highgui/src/window.cpp:331: error: (-215) size.width>0 && size.height>0 in function imshow 

i have searched all websites but still only few about that error and no exact solution code, How should i fix the code?
Thanks

**Comment by Adrion** [comment]
Wrong project ?
