### ISSUE TITLE
Getting body undefined during call external url

### ISSUE THREAD

**Issue by harshbaba** [request/request#2932]
Hello Team,
I have created a middle ware to call external api in express.

Problem
My problem is that when i am calling url2 then i am getting body, but at the time of url1 calling i am getting undefined.
While when i am hitting these url's in browser then both showing data.
Please Help.

JS
app.get('/trainStatus2/:trainNo', function(req, res) {
        function getDaysOfRunString(days){
            return days;
        }
        let url = "";
        let url2 = "";
            
        Request.get(url, (error, response, body) => {
                if(error) {
                    return console.dir(error);
                }
            console.log(body);
        });

    }); 

Thanks
Harsh

**Comment by klabelkholosh** [comment]
+1
