### ISSUE TITLE
HPE errors

### ISSUE THREAD

**Issue by AeonPragma** [request/request#2935]
### Issue and example to reproduce
Downloading files, request produces HPE errors with empty response body on some cases where instead there is no fatal error to justificate it. In the following cases, request is run as:
```js
var request = require('request');
var Req = {};
        Req.url = data.url;
        Req.headers = { 
            'User-Agent': "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:59.0) Gecko/20100101 Firefox/59.0",
            "Referer": "google.com",
            "Accept-Language":"it-IT,it;q=0.8",
            "Accept":'text/html, application/xhtml+xml, application/xml;q=0.9, */*;q=0.8',
            'Accept-Encoding': 'identity'
        };
        Req.timeout = 120000;
        request(Req, function (error, response, body) {...}
```
and it produces:
HPE_UNEXPECTED_CONTENT_LENGTH on url http://www.promoimpresaonline.it/download.asp?ln=&idtema=1&idtemacat=1&file=Informazioni/Files/47790/contrattial2015.xml where the header content-length is duplicated, but since both have the same length, the error may be ignored.
HPE_INVALID_CONSTANT on url http://www.canalelunense.eu/index.php/pubblicazione-ai-sensi-della-legge-190-2012/item/download/218_eceaf864291919ca7d9b26bcabfdd880 , which perfectly works on browsers and its raw header seems perfectly fine.
Adding, as suggested in #2761, http-parser-js in my script, before request require and use, did not solve the issue.
### Expected Behavior
Is expected from request to behave as with normal headers, downloading succesfully the file
### Your Environment
| software         | version
| ---------------- | -------
| request          | 2.85.0
| node             | 8.10.0
| Operating System | Windows 10

**Comment by plroebuck** [comment]
WOMM using [alternative HTTP parser](https://www.npmjs.com/package/http-parser-js)...
```js
process.binding('http_parser').HTTPParser =
  require('http-parser-js').HTTPParser;
const request = require('request');

const urls = [
  'http://www.promoimpresaonline.it/download.asp?ln=&idtema=1&idtemacat=1&file=Informazioni/Files/47790/contrattial2015.xml',
  'http://www.canalelunense.eu/index.php/pubblicazione-ai-sensi-della-legge-190-2012/item/download/218_eceaf864291919ca7d9b26bcabfdd880'
];

const options = {
  encoding: 'utf8',
  headers: {
    'accept': 'text/html, application/xhtml+xml, application/xml;q=0.9, */*;q=0.8',
    'accept-encoding': 'identity',
    'accept-language': 'it-IT,it;q=0.8',
    'referer': 'google.com',
    'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:59.0) Gecko/20100101 Firefox/59.0'
  },
  timeout: 120000
};

urls.forEach(url => {
  request.get(url, options, function (error, response, body) {
    console.log('=======', url, '\n');

    if (error) {
      return console.error('error:', error);
    }

    console.log('Status:', response.statusCode, response.statusMessage);
    if (response.headers['content-disposition']) {
      console.log('Content-Disposition:',
                  response.headers['content-disposition']);
    }
    console.log('Content-Encoding:',
                response.headers['content-encoding'] || 'identity');
    console.log('Content-Length:', response.headers['content-length']);
    console.log('Content-Type:', response.headers['content-type']);
    console.log('\n', body, '\n');
  });
});
```

* macOS 10.13.6
* node v10.15.0
* http-parser-js@0.5.0
* request@2.88.0
