### ISSUE TITLE
Body  is more than a "\""

### ISSUE THREAD

**Issue by SunGg12138** [request/request#2937]
```javascript
var options = {
      method: 'POST',
      url: '***',
      headers: {
        'Content-Type': 'text/plain'
      },
      json: true,
      body: "1798612312"
}
```

body will be turned into '"1798612312"'

**Comment by Qamar-93** [comment]
try to send the body as an object just like: {value: "1798612312"} and use JSON.stringify when sending and JSON.parse when receiving the value in the back-end

**Comment by SunGg12138** [comment]
It's the Oauth2.0, and it must be like this
