### ISSUE TITLE
test-gzip now failing when using node 10.1

### ISSUE THREAD

**Issue by gareth-robinson** [request/request#2940]
### Summary
When running the CI tests against node 10.1. a number of the tests cause deprecation warnings, but the test-gzip fails test 'do not try to pipe responses with no body'
```javascript
{ Error: socket hang up
    at createHangUpError (_http_client.js:313:15)
    at Socket.socketOnEnd (_http_client.js:409:23)
    at Socket.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1086:12)
    at process._tickCallback (internal/process/next_tick.js:63:19) code: 'ECONNRESET' }
```

### Simplest Example to Reproduce
As above, just run CI tests against node 10.1
```javascript
node_modules/.bin/taper tests/test-gzip.js
```

### Possible Solution
The particular failing test in test-gzip creates a test server and then tries getting 105, 204 and 304 responses for it in order to test empty responses (lines 270-295 in test-gzip.js). If I comment out the '105' part of the test it passes.
The reason the 105 test fails appears to be as a result of this issue/fix in node
https://github.com/nodejs/node/issues/9282
https://github.com/nodejs/node/pull/18033
I think as a result of the change, Informational responses leave the response open for another response to be written later - so doing 
```javascript
res.writeHead(105, ...
res.end()
```
no longer leaves the response in the right state.

### Context
Means that any pull request submitted will not get a green build.

**Comment by gareth-robinson** [comment]
Looks like this is already being looked at, with this commit: https://github.com/request/request/pull/2942/commits/0c5db42fcd0890eab966f335a1bc8c858255b962 ("Skip status code 105 on Node > v10").
So I'll close this issue once that's merged in!

**Comment by simov** [comment]
Yep, I just skipped it. There is a change in how 105 status code is handled in Node v10, but I'm not sure why exactly it was throwing an error.

**Comment by gareth-robinson** [comment]
I think if you write an informational response using res.writeHead it clears req.res 
https://github.com/nodejs/node/blob/master/lib/_http_client.js#L527
but if you then call res.end after that without actually sending a real response, it hits this line
https://github.com/nodejs/node/blob/master/lib/_http_client.js#L420
and emits the hand up error.
So the error message isn't really correct - it wasn't a socket hangup, it was just ending the response without actually sending anything.
