### ISSUE TITLE
feature request : ignore undefined when sending JSON data

### ISSUE THREAD

**Issue by xileftenurb** [request/request#2948]
### Summary
when sending json data, if any field is undefined, request return with the error `cannot read property 'name' of undefined`

### Simplest Example to Reproduce

```js
request.post("url", {json : true, formData : {
    aStringField : "data",
    aUndefinedField : undefined
}}, function(err, res, body) {}),
```

I would like the undefined value to be simply ignored OR 
I would at least prefer a clearer error message, telling the key of the undefined value so it can be found.

I spend so much time figuring out why this error happen. I have multiple field in my json witch can be left out, and I would like to be able to create my data object like so : 

```js
data = {
    fieldA : foo, //foo can be undefined or not.
    fieldB : bar //bar can be undefined or not
}
```

but I need to do : 
```js
data = {}
if(foo) {data.fieldA = foo};
if(bar) {data.fieldB = bar};
```
instead. more long, less clear.

### Your Environment

| software         | version
| ---------------- | -------
| request          |2.85
| node             |10.1
| npm              |5.6
| Operating System |Windows 10

**Comment by bisho1995** [comment]
Yes, I went through the source code and apparently there is no check for the value field. Then it tries to treat it as an object and that is where an error is being thrown. There is a check for options field though.

![image](https://user-images.githubusercontent.com/12195877/43280440-809ac778-912e-11e8-8d7e-b0469011c1e4.png)

Just adding this one line in the source code throws an error which is enough I guess to inform the user and prevent the code from crashing.
