### ISSUE TITLE
Trying to use request with node.js  and promisses

### ISSUE THREAD

**Issue by danmmelo** [request/request#2961]
Hi Guys,

I am new in node.js. I am trying to create a request to an IBM api using promises...and i have the sample of how to do this using curl...could you guys give an hint of how to do in node.js...i've tried thus below....

curl -X POST -H "X-Auth-Token:APIKEY" -H "Content-Type: application/vnd.kafka.binary.v1+json" kafka-rest endpoint/topics/topic name -d 

'
{
  "records": [
    {
      "value": "A base 64 encoded value string"
    }
  ]
}
'

function initialize() {
    // Setting URL and headers for request
    var options = {
        url: 'https://www.endpoint.com/endpoint/topics/topicname',
        headers: {
            'X-Auth-Token': 'APIKEY',
	    'Content-Type': 'application/vnd.kafka.binary.v1+json'	
        }
    };
    // Return new promise 
    return new Promise(function(resolve, reject) {
     // Do async job
        request.post(options, function(err, resp, body) {
            if (err) {
                reject(err);
            } else {
                resolve(JSON.parse(body));
            }
        })
    })
}

**Comment by nishant-jain** [comment]
The code snippet looks fine. What's the issue that you're getting?

**Comment by gkatsanos** [comment]
@danmmelo when you're posting snippets, please use backticks (` ` ) to format your code properly.

> ```js
> <your code here>
> ```

so your code is readable. You can also create Repl links http://repl.it/ (choose "Node" in the language list) where someone could run your code immediately and see what's wrong/debug it.
