### ISSUE TITLE
Uploading file returns as successful, but no file is uploaded to destination folder

### ISSUE THREAD

**Issue by chrsmrtn81** [request/request#2962]
Hi all! I've started a project using Electron and need a way to upload files to a server, which I've been trying to use Request for. I've taken an example from the NPM page and modified it to test on my localhost, as below, and it seems to work because I get a success message in the console, but the file is never moved..??

```
const fs = require('fs');
const request = require('request');

var uploadURL = 'http://localhost:80/sandbox/img';

var req = request.post(uploadURL, function (err, resp, body) {
    if (err) {
        console.log(err);
    } else {
        console.log(body);
    }
});

var form = req.form();

form.append('upload', fs.createReadStream("C:/nodejs/dave/assets/img/brand_logos/logo.jpg"), {
    filename: "logo.jpg",
    contentType: 'image/jpeg'
});
```

The message I get in my console is as follows...

```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>301 Moved Permanently</title>
</head><body>
<h1>Moved Permanently</h1>
<p>The document has moved <a href="http://localhost/sandbox/img/">here</a>.</p>
<hr>
<address>Apache/2.4.27 (Win64) PHP/7.0.23 Server at localhost Port 80</address>
</body></html>
```

I'm fairly new to JavaScript and feel I might be missing something pretty silly perhaps, any advice would be really welcome though.

**Comment by gkatsanos** [comment]
1. According to the multipart example of the documentation, the first argument of request.post is an object that includes the formUrl and the formData

```js
request.post({url:'http://service.com/upload', formData: formData}, function optionalCallback(err, httpResponse, body) {
  if (err) {
    return console.error('upload failed:', err);
  }
  console.log('Upload successful!  Server responded with:', body);
}); 
```

2. Are you sure the sandbox/img has the necessary permissions / is writeable by the Node process? Can you experiment with giving more permissions to the folder ? 

I'm not sure what the problem is just a quick guess from what I can see here.
