### ISSUE TITLE
Request with method HEAD return error HPE_INVALID_CONSTANT

### ISSUE THREAD

**Issue by loustak** [request/request#2970]
This code:
```js
request.head('http://google.com', function(error, res, body) {
    console.log(error);
});
```

show:
```js
{ Error: Parse Error
at Socket.socketOnData (_http_client.js:440:20)
at emitOne (events.js:116:13)
at Socket.emit (events.js:211:7)
at addChunk (_stream_readable.js:263:12)
at readableAddChunk (_stream_readable.js:250:11)
at Socket.Readable.push (_stream_readable.js:208:10)
at TCP.onread (net.js:597:20) bytesParsed: 340, code: 'HPE_INVALID_CONSTANT' } 
 ```
I was excepting error to be null in this case.

Using request 6.1.0 and node 8.11.3.

**Comment by TheRusskiy** [comment]
can confirm that :-/

**Comment by TheRusskiy** [comment]
Actually in my case our server was sending HTTP response that nodejs itself failed to parse.
So @loustak try other libs like `axios` to see if they work, there's a chance that nodejs itself is at fault.

**Comment by codenirvana** [comment]
@loustak I recently came across this same issue.

@TheRusskiy is correct. If your server is responding with message body, It will blow up Node's [HTTP Parser](https://github.com/nodejs/http-parser).

The reason for this is, according to [RFC 7231](https://tools.ietf.org/html/rfc7231#section-4.3.2):

> The HEAD method is identical to GET except that the server MUST NOT send a message body in the response (i.e., the response terminates at the end of the header section).
