### ISSUE TITLE
Review http-signature dependency (licensing and authorship issues)

### ISSUE THREAD

**Issue by honzajavorek** [request/request#2971]
The `http-signature` package depends on `node-sshpk` package, which depends on `bcrypt-pbkdf`, which has unclear licensing and authorship. My concerns are explained in https://github.com/joyent/node-sshpk/issues/37#issuecomment-401051047 This problem spreads through `request` transitively and affects a large portion of the ecosystem.

**Comment by mikeal** [comment]
Is there a properly licensed replacement?

**Comment by honzajavorek** [comment]
The issue has been resolved by releasing `bcrypt-pbkdf@1.0.2` a few hours ago. Since it is a patch version, it propagates to new installs up the dependency tree. Details [here](https://github.com/joyent/node-sshpk/issues/37#issuecomment-401216983). Thank you!
