### ISSUE TITLE
Is this project still actively maintained? (help wanted?)

### ISSUE THREAD

**Issue by gkatsanos** [request/request#2978]
With open issues reaching the 700 mark, I'm wondering if you guys need help maintaining?

**Comment by mikeal** [comment]
Yes :)

At this point, none of the maintainers seem to have time to keep up with even the active pull requests.

This has been the case or me for quite a while but it seems all the maintainers I added a while back have reached the same point.

The project still has a very liberal contribution agreement and I'm still committed to giving commit and publish rights to anyone putting in the work :)

**Comment by Hamper** [comment]
Can anyone update some child projects like https://github.com/request/tunnel-agent ? This project have some errors and pull requests with fixes, but none of the developers even read issues and pull requests in subprojects for more than 1.5 years.
