### ISSUE TITLE
-

### ISSUE THREAD

**Issue by jkamdjou** [request/request#2983]
### Simplest Example to Reproduce

```js
request({
  method: 'GET',
  url: 'http://example.com', // a public URL that we can hit to reproduce, if possible
  more: { 'options': 'here' }
},
```

### Your Environment

| software         | version
| ---------------- | -------
| request          |
| node             |
| npm              |
| Operating System |

**Comment by jd-carroll** [comment]
@jkamdjou please update or close this issue
