### ISSUE TITLE
How to close http connection from client side?

### ISSUE THREAD

**Issue by icewitch** [request/request#2988]
### Summary

Write a service based on Node js, sending restapi commands based on GET and POST periodically in parallel. And it seems the current library solution for ajax, like superAgent and request, there is no way to close the connection from client in node.js. since the connection is not closed, the server will be messed up when binded to 150 connections.  In superAgent, the problem occurs so I turn to request with http pool, but it doesn't help too. Do we have a solution in node.js to close http connection from client side?

### Simplest Example to Reproduce

```js
// First solution: superAgent 
	this.request = require('superagent');
// Second solution: request
	this.request = require('request');
	var http = require('http');
	var pool = new http.Agent(); //Your pool/agent
	http.request({hostname:"10.61.45.152", port:8080, path:'/api', agent:pool});
	//http.request({port:8080, path:'/api', agent:pool});
	pool.maxSockets=70
```

### Your Environment

| software         | version
| ---------------- | -------
| request          |
| node             |
| npm              |
| Operating System |

**Comment by codenirvana** [comment]
@icewitch have you tried with `Connection: close` header?
This indicates that the server is going to close the connection after the current request/response is complete.
