### ISSUE TITLE
https request with https proxy error

### ISSUE THREAD

**Issue by Hamper** [request/request#3002]
### Summary
I get `Hostname/IP does not match certificate's altnames` error when try to connect to https site with https proxy

### Simplest Example to Reproduce
```js
request({
  method: 'GET',
  url: 'https://example.com',
  proxy: 'https://proxy.example'
},
```

### Expected Behavior
Succesful responce from url.

### Current Behavior
`Hostname/IP does not match certificate's altnames` error 

### Possible Solution
https://github.com/request/tunnel-agent/pull/42

### Context
Connecting throw https proxy

### Your Environment
| software         | version
| ---------------- | -------
| request          | 2.87.0
| node             | v10.8
| npm              | 6.3.0
| Operating System | Calculate linux

**Comment by Hamper** [comment]
@mikeal or anyone, can you check issues and pull requests for tunnel-agent, and possibly update it? It can fix many of proxy related issues

**Comment by mikeal** [comment]
I can't this week, maybe next week, @reconbot might have some time.

**Comment by bencmbrook** [comment]
I'm getting this same bug. It seems to be comparing the TLS cert alt names against the hostname in the `url`, and not in the `proxy`. This is the case when tunnel mode is off (`tunnel: false`), but I imagine it shouldn't be.

Any progress on this? Does @Hamper's PR fix this?
