### ISSUE TITLE
DeprecationWarning: Custom inspection function on Objects via .inspect() is deprecated

### ISSUE THREAD

**Issue by NastyZ98** [request/request#3003]
EDIT: After some research it look like that the problem come from one of your dependencies: **'tough-cookie'**, you actually using version [2.3.3](https://github.com/salesforce/tough-cookie/blob/v2.3.3/lib/cookie.js#L665) that do not provide [util.inspect.custom](https://github.com/salesforce/tough-cookie/blob/master/lib/cookie.js#L760) symbol

### Summary
Hi, first of all excuse my english. This isn't a bug but a warning.
When you want to debug a cookie using console log created with `request.cookie()` NodeJS return you the following :

**_(node:3091) [DEP0079] DeprecationWarning: Custom inspection function on Objects via .inspect() is deprecated_**

### Example to Reproduce
```js
const request = required('request');

const cookie = request.cookie('key=1');
console.log(cookie);
```

### Possible Solution
request relies on custom inspect() functions to make debug output readable, but looks like Node.js 10.x no longer support that.
I don't know the architecture of request project to make a pull request but I think the possible solution is to replace actual inspect by this one:
[util.inspect.custom](https://nodejs.org/api/util.html#util_custom_inspection_functions_on_objects) for custom inspect methods 

Thing is, symbols are only available in Node >=6 and I don't know which version request target.

### My Environment

| software         | version
| ---------------- | -------
| request          | ^2.87.0
| node             | v10.7.0
| npm              | 6.3.0
| Operating System | macOS 10.13.6 (17G65)

**Comment by SneakyFish5** [comment]
So to fix this all one needs to do is update `tough-cookie`?

**Comment by NastyZ98** [comment]
@SneakyFish5 Exactly this is all you have to do ! 😄

**Comment by SneakyFish5** [comment]
Are you sure request is using 2.3.3? Package.json says `~2.4.3`

**Comment by NastyZ98** [comment]
@SneakyFish5 Yes it has been updated at the same time I opened the issue 😄 
I close it then.
