### ISSUE TITLE
memory leak when using {time: true}

### ISSUE THREAD

**Issue by gajus** [request/request#3006]
### Summary

Memory is leaking when using `{time: true}` configuration.

Example [heapsnapshot.zip](https://github.com/request/request/files/2280581/heapsnapshot.zip)

### Simplest Example to Reproduce

```js
request({
  method: 'GET',
  url: 'http://example.com',
  time: true
});

```

### Expected Behavior

No memory leak.

### Current Behavior

Memory is accumulating.

### Your Environment

| software         | version
| ---------------- | -------
| request          | 2.88.0
| node             | v10.7.0
| npm              | v6.2.0
| Operating System | OSX

**Comment by erikkri** [comment]
Have you seen if this is tied to specific versions of request?
