### ISSUE TITLE
Does not build valid POST bodies when multipart/related boundary values are double-quoted

### ISSUE THREAD

**Issue by ernestedavis** [request/request#3014]
### Summary
When POSTing a multipart/related body with the content-type header boundary value enclosed in double quotes, `request` writes the double-quote characters into the document boundary, in violation of [7.2.1 Multipart: The common syntax](https://www.w3.org/Protocols/rfc1341/7_2_Multipart.html).

### Simplest Example to Reproduce

1) Set up a simple `express`/`formidable` server:
```js
const express = require('express');
const app = express();
const formidable = require('formidable');
const util = require('util');

app.listen(3000, () => console.log('Example app listening on port 3000!'));

app.post('/', (req, res, next) => {
    console.log("POST:req.headers:\n", req.headers);

    new formidable.IncomingForm().parse(req, (err, fields, files) => {
        if (err) {
            console.error(err);
            next(err);
        } else {
            res.send('POST & form.parse() succeeded.\n');
        }
    });

});
```

2) Send a `multipart/related` POST to the server:
```js
const request = require('request');

const options = {
    method: 'POST',
    url: 'http://localhost:3000',
    headers: {
        'Content-Type': 'multipart/related; boundary="--MIME_boundary"'
    },
    multipart: [
        {
            'Content-Type': 'text/plain',
            body: 'body goes here'
        }
    ]
};

request(options, (error, response, body) => {
    console.log('error:', error);
    console.log('statusCode:', response && response.statusCode);
    console.log('body:', body);
});
```

3) Output from the server showing the error from `formidable`:
```
POST:req.headers:
 { 'content-type': 'multipart/related; boundary="--MIME_boundary"',
  host: 'localhost:3000',
  'content-length': '86',
  connection: 'close' }
Error: MultipartParser.end(): stream ended unexpectedly: state = START_BOUNDARY
    at MultipartParser.end (/home/edavis/git/ernestedavis/request-demo/formidable/node_modules/formidable/lib/multipart_parser.js:326:12)
    at IncomingMessage.<anonymous> (/home/edavis/git/ernestedavis/request-demo/formidable/node_modules/formidable/lib/incoming_form.js:132:30)
    at emitNone (events.js:106:13)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

### Expected Behavior
`request` should produce a document body in this form:
```
$ nc -l 127.0.0.1 3000
POST / HTTP/1.1
Content-Type: multipart/related; boundary="--MIME_boundary"
host: localhost:3000

----MIME_boundary
Content-Type: text/plain

body goes here
----MIME_boundary--

```

### Current Behavior
`request` actually produces a document in this form:
```
$ nc -l 127.0.0.1 3000
POST / HTTP/1.1
Content-Type: multipart/related; boundary="--MIME_boundary"
host: localhost:3000

--"--MIME_boundary"
Content-Type: text/plain

body goes here
--"--MIME_boundary"--

```

### Possible Solution
PR #3015

### Context
We are consuming POST requests from another vendor and building POSTs to other services in our stack using `request`. The POSTs from the vendor have boundary values enclosed in double quotes. We think this is a case we have to accomodate because it is valid to enclose header value strings in double quotes per [RFC1341](https://www.w3.org/Protocols/rfc1341/4_Content-Type.html) / [RFC822](https://www.w3.org/Protocols/rfc822/3_Lexical.html#z2).

Neither of the libraries our services use to consume multipart content, `formidable` nor `multiparty`,  handle non-compliant boundaries of the form `--"--MIME_boundary"`, nor have we been able to find any library which will do so. 

So we are are in a situation where we can process incoming requests from the outside vendor with `formidable` with no problem, but when we re-POST with `request` to the next service in the stack the next consumer cannot parse the request because the boundaries are invalid.

### Your Environment

| software         | version
| ---------------- | -------
| request          | 2.88.0
| node             | v8.11.2
| npm              | 5.6.0
| [formidable](https://www.npmjs.com/package/formidable)   | 1.2.1
| [multiparty](https://www.npmjs.com/package/multiparty) | 4.2.1
| Operating System | Ubuntu 16.04.5  LTS

**Comment by djom20** [comment]
Hi I have a issue similar to this one, where I trying to upload a spreadsheet with Content-Type as multipart/form-data and boundary but without double-quoted and `request` just throw me the 199 code error, so I don't know why happen this and the error don't show any information useful.


![image](https://user-images.githubusercontent.com/1834808/47246224-446e5e00-d3c2-11e8-94ae-d73ccd09a36b.png)
