### ISSUE TITLE
Http request  getaddrinfo ENOTFOUND at GetAddrInfoReqWrap.onlookup (dns.js:92:26)

### ISSUE THREAD

**Issue by praveensutar** [request/request#3021]
### Summary

The request  module fail to validate the invalid http or https URL request. 
### Simplest Example to Reproduce

Example: Using following request this error occures
 http://aaa.....com the 

ERROR:
error: { Error: getaddrinfo ENOTFOUND te.....com te.....com:443
    at errnoException (dns.js:50:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'te.....com',
  host: 'te.....com',
  port: 443 }
statusCode: undefined

```js
var request = require('request');
  request('http://te...com/../', function (error, response, body) {
  console.log('error:', error); // Print the error if one occurred
  console.log('statusCode:', response && response.statusCode); // Print the response status code if a response was received
});

```

### Expected Behavior

The request need to validate the URL pattern properly to avoid the error
### Your Environment

| software         | version
| ---------------- | -------
| request          | 2.88.0
| node             | 8.9.3
| npm              | 5.6.0
| Operating System | Ubuntu 16.04

**Comment by zhangxiang958** [comment]
@jchris @voodootikigod @mikeal @tobowers Anyone know how to fixed this bug? or know what lead to this bug? i'm also had this bug in my server. 

Any help will be appreciated!

**Comment by debelop13** [comment]
I have the same error!
A big problem for me

**Comment by AdletAzhibek** [comment]
any solutions? i gave the same problem

**Comment by AdletAzhibek** [comment]
any solutions? i have the same problem

**Comment by srlowe** [comment]
I'm seeing something similar.  Possibly related to: https://github.com/586837r/node-red-contrib-alexa-remote2/issues/69

**Comment by ronlaniado** [comment]
> any solutions? i have the same problem

Not sure if you're still looking for a solution, but I solved my issue by using the pooling option.
