### ISSUE TITLE
Difference between /meta/disconnect and /meta/unsubscribe call of Bayeux

### ISSUE THREAD

**Issue by Pratibha24** [request/request#3022]
Hi,

@sbordet
For the salesforce streaming we have used CometD Bayeux client and once we are done we just call the bayeux.disconnect() and stops the client. If we do not call the unsubscribe , is there any harm over here?

What exactly is the purpose of disconnect and unsubscribe here?

Thanks,
Pratibha

**Comment by Pratibha24** [comment]
Oh is it? I found some streaming related stuff here, so posted my question here. can we move it to some other project ?
By the way, any answer for my question?

**Comment by sbordet** [comment]
You make a CometD specific question on this project that I only saw because you mentioned me.
Make the same question in the CometD project and you will get your answer.

**Comment by Pratibha24** [comment]
I have added my question to right project , hence closing it.
