### ISSUE TITLE
Possible to bypass CORS?

### ISSUE THREAD

**Issue by Sebastian-Nielsen** [request/request#3025]
Is it possible to bypass CORS ? If so, how? - using this module of course.

I have not been able to find just one example on this matter. If possible, please supply me with an example.

**Comment by shivmitra** [comment]
@Sebastian-Nielsen Did you find any solution for this?

**Comment by subatomicglue** [comment]
Also need to know the answer for this.

Passing in 
```
let common_options = {
  headers: {
    "Access-Control-Allow-Origin": "*",
    "Access-Control-Allow-Methods": "GET, POST, PUT, DELETE, PATCH, OPTIONS",
    "Access-Control-Allow-Headers": "X-Requested-With, content-type, Authorization"
  }
};
```
To `request.post(url, common_options, (e,r,b)=>{})` still doesn't work, on `localhost`, running `webpack-dev-server` to serve/pack the code, and trying to make some `https` calls to `zoom.com`
