### ISSUE TITLE
Timeout handling broken with bad proxy.

### ISSUE THREAD

**Issue by SergeyFromHell** [request/request#3027]
When use proxy that just accepts connections and never sends data back, request just waits forever.
```js
const request = require('request');
const net = require('net');

net.createServer((socket) => {
    // do nothing
}).listen(25252,() => {
    let t = Date.now();
    request.get({
        url: 'https://www.google.com',
        proxy: 'http://127.0.0.1:25252',
        timeout: 5000,
    },(error,response,body) => {
        // never called!
        console.log('T',Date.now() - t);
        error ? console.log(error) : console.log('RESPONSE');
        process.exit(0);
    });   
});
```
### Expected Behavior
Some TIMEDOUT error should occur after 5 seconds.

### Current Behavior
Nothing happens, callback never called.

### Possible Solution
Request should timeout in any case regardless network problems, bad proxies or responding servers, system socket timeouts etc. I know I can use external timeout, but that will lead to socket leak (.abort() method does not close sockets).

### Context
I use free proxy lists and cannot control bad proxies behaviour.

### Your Environment
| software         | version
| ---------------- | -------
| request          | 2.87.0
| node             | 10.9.0
| npm              | 6.2.0
| Operating System | Ubuntu 18.04.1 LTS

**Comment by SethWen** [comment]
Haved you solved the problem? I have encountered the same problem. 
1. When I set a bad proxy , the `timeout` option is invalid. 
2. The request will abort after about 130 seconds, however.

**Comment by SergeyYermak** [comment]
Same, trying to figure out a workaround...

**Comment by SethWen** [comment]
I have figured it out. If your destination is a `https` url, you can put a `tunnel=false` option.
If you want to know the reason, you can go to the document [here](https://www.npmjs.com/package/request) and read the `tunnel` option segment.

**Comment by dattran92** [comment]
I have the same problem but setting tunnel=false seems doesn't work for me.

**Comment by swandive0209** [comment]
any updates? the `tunnel=false` option does not work for me
