### ISSUE TITLE
Callback never executed for certain URLs

### ISSUE THREAD

**Issue by ejoebstl** [request/request#3038]
### Summary
By coincidence, I noticed a URL that leads to `request` hanging. 

### Simplest Example to Reproduce

```js
var x = request({uri: 'http://m.eet.com/content/images/ebnonline/superhero-534120_640_1499288028.jpg'}, function (error, response, body) {
  console.log('Hello'); // Callback is never executed
});
```

### Expected Behavior
The callback should be executed in any situation. 

### Current Behavior
The callback is not executed, ever. I've waited for several hours. 

### Context
I was trying to download the image above. 

### Your Environment
| software         | version
| ---------------- | -------
| request          | 2.88.0
| node             | 6.10.3
| npm              | 3.10.10
| Operating System | Linux archlinux 4.18.9-arch1-1-ARCH, Debian 4.9.82-1

**Comment by falconscript** [comment]
I have to echo this. Neither the timeout or the callback are being fired for many random requests.

This is a pretty gamebreaking bug for me that wasn't happening before a few months ago

**Comment by kevinkassimo** [comment]
The sample url given is served under http2. Seems not yet supported by request

**Comment by ejoebstl** [comment]
Thanks for figuring that out! Maybe it could throw in that case? 

Silent erros are super-hard to debug.

**Comment by falconscript** [comment]
This issue does not occur in request version 2.87.0 for me, only 2.88.0. I've been able to avoid the issue this way.

The problem must be caused by whatever was changed for this specific update of v2.87.0->v2.88.0 then.

**Comment by kevinkassimo** [comment]
@falconscript interesting. I diffed the two versions, seems mostly just dependencies upgrades.

**Comment by ejoebstl** [comment]
Yes, HTTP 2 was not responsible. The following URL triggers the same behavior and is definitely HTTP 1.1:

`http://www.ti.com/corp/docs/landing/cc430/graphics/cc430block.gif`

**Comment by ejoebstl** [comment]
For the URL reported in the previous post, the issue was that the webserver would not return a response with a certain form (for a reason I don't know). 

The issue was resolved by passing an appropriate timeout to `request`.

**Comment by ejoebstl** [comment]
Here is another specimen: 

```
https://www.kansascity.com/sports/high-school/article153097349.html 
```

**Comment by ejoebstl** [comment]
No, @stale, this is still relevant.

**Comment by vigneshkindia** [comment]
doesnt request fallback to http1.1 when the server offers both http2 and http1.1 ? i am facing a hard time figuring this out. any help will be much appreciated .
