### ISSUE TITLE
maintenance of request/request-promise & request/promise-core

### ISSUE THREAD

**Issue by gurpreetatwal** [request/request#3045]
### Summary
It seems like [request/request-promise](https://github.com/request/request-promise) and [request/promise-core](https://github.com/request/promise-core) aren't being actively maintained. I created a PR (request/promise-core#3) about a year ago but @analog-nico seems to have kind of dropped off the grid. :(

Two questions:
1. could one of the maintainers here take a look at that pull request?
2. is help needed with maintenance on those repos?

**Comment by analog-nico** [comment]
Hey @gurpreetatwal I am sorry for that. It is indeed an unfortunate situation. Although I would like to continue maintaining the libraries I hardly find the time as my startup keeps me busy.

I am happy to hand the project over to a new maintainer. If we can’t find anyone, however, I am still all for this project and want to come back to it.

**Comment by gurpreetatwal** [comment]
Oh no worries, glad to hear that your startup is doing well! :smile: 

I'd love to help with maintenance if that's okay with you? We could just split time on maintenance of the repos. I think most of the issues are support requests anyway

**Comment by karlbecker** [comment]
Just wanted to mention that perhaps [Open Collective](https://opencollective.com) or [TideLift](https://tidelift.com) could help with funding something like request-promise, too, for whoever would want to take it over. cc @tidelift

**Comment by gurpreetatwal** [comment]
bump :grimacing:
