### ISSUE TITLE
can't catch internet disconnection event while downloading big files

### ISSUE THREAD

**Issue by Dengue** [request/request#3058]
Hello,
I have to download a big file from remote server, but my connection is not stable. Actually it can disconnect after 10 minutes and then autoatically reconnect. As the result of such reconnection downloading proccess stops and I can't catch any errors or events programatically.
Here is exmaple of code that I use:

`const request = require('request')
request({
  uri: `${pathToRemoteFile}`,
  encoding: null
}).on('error', err => console.log(err))
.pipe(fs.createWriteStream(`${pathToStoreFileLocally}`))
.on('finish', () => { console.log('yeah, successfully downloaded') })
.on('error', err => console.log(err))`

So for example if I need to download 500MB file, and I have already downloaded for example 100MB and suddenly I lost internet connection so the file will not be downloaded anymore and no errors will raise.

Maybe I missed something?

**Comment by zahi111** [comment]
Same..
