### ISSUE TITLE
Error fired when using character like č

### ISSUE THREAD

**Issue by dj-marko** [request/request#3065]
Summary

Simplest Example to Reproduce
Example: Using following request this error occurs
```
 const url = http://localhost:4000/č;
    request(url, (error, response, body) => {
        console.log(error);
        if(error) {
            // res.json('Error on our side, please try later');
        }
        else {
            // res.json(body);
        }
    });
```
ERROR:
```
 Error: socket hang up
    at createHangUpError (_http_client.js:331:15)
    at Socket.socketOnEnd (_http_client.js:423:23)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9) code: 'ECONNRESET' }
null
```
**Expected Behavior**
The request went fine

**Current Behavior**
Request get error and doesn't fire.

**Possible Solution**
encodeURI on request url  solves the issue, this post is more like question is this expected behaviour of library and what is most desirable way of solving issue?

**Context**
Trying to make two very simple applications communicating
**Your Environment**
Local dev environment based on Node Express library

software | version
request | 2.88.0
node | v8.11.1
npm | 5.6.0
Operating System | macOS Mojave

**Comment by dege88** [comment]
You need to first encode the request url with something like: https://www.w3schools.com/jsref/jsref_encodeURI.asp or https://nodejs.org/api/querystring.html
