### ISSUE TITLE
GET have default body

### ISSUE THREAD

**Issue by QiandaoLakeYY** [request/request#3083]
### Simplest Example to Reproduce

```js
request({
  method: 'GET',
  url: 'http://example.com?name=test'
},
```

### Context
When I use get func like above, the framework will set default body as '{}' and set content-length, 
But some framework like echo in go, it will read query params from body when the content-length is not 0. 
So it will lead echo cannot get my query params.
How to solve it ? and why the framework set a default body like '{}'

### Your Environment

| software         | version
| ---------------- | -------
| request          | lasted
| node             | v8.10.0
| npm              | v5.6.0
| Operating System |

**Comment by ultimate-tester** [comment]
Duplicate of #3080
