### ISSUE TITLE
Digest authentication fails against MusicBrainz API

### ISSUE THREAD

**Issue by Borewit** [request/request#3093]
### Summary
Digest authentication against [MusicBrainz API](https://musicbrainz.org/doc/Development/XML_Web_Service/Version_2#Authentication) fails.

Related and maybe the same cause: #3072

### Simplest Example to Reproduce

```JavaScript
/**
 * Related API doc: https://musicbrainz.org/doc/Development/XML_Web_Service/Version_2#ISRC_submission
 */
public async _request_post(entity: 'recording', xmlMetadata: XmlMetadata): Promise<any> {

    return new Promise<void>((resolve, reject) => {

      request.post({
        url: `'http://musicbrainz.org/ws/2/${entity}/`, // Use HTTPS for production!!!
        body: xmlMetadata,
        headers: {
          'Content-Type': 'application/xml',
          'User-Agent': user_agent
        },
        qs: {
          // fmt: 'json', // This seems to confuse the MusicBrainz API
          client: 'WhatMusic/0.0.1'
        },
        // proxy: 'http://localhost:8888', // Redirect to Fiddler
      }, (error, response) =>  {
        if (error) {
          reject(error);
        } else {
          if (response.statusCode === HttpStatus.OK) {
            resolve(response.body);
          } else {
            reject( new Error('MusicBrainz API error'));
          }
        }
      }).auth(this.config.username, this.config.password, false)

    });
  }
```

### Expected Behavior
Expect the digest authentication to work.

### Current Behavior
Receive a 401 (UNAUTHORIZED) from MusicBrainz, with following message:

> Your credentials could not be verified. Either you supplied the wrong credentials (e.g., bad password), or your client doesn't understand how to supply the credentials required.

Header generated by request:
```
authorization: Digest username="Borewit", realm="musicbrainz.org", nonce="6CCUtvEQ6RGDfthcSlGD+w==", uri="http://musicbrainz.org/ws/2/recording/?client=WhatMusic-0.0.3", qop=auth, response="1eb1140de19a680210127f847a7803a7", nc=00000001, cnonce="0994fcf97892413987ed7c83f8a2e131", algorithm=MD5, opaque="QCiUtvEQ6RGDfthcSlGD+w=="
```
### Possible Solution
I compared the differences with a successful CURL using Fiddler, and noticed the `uri` field in the HTTP 

For comparison I tried to to the same thing with CURL:
``` bash
curl --digest -u Borewit:$MBPASSWD -A "WhatMusic/0.0.1 ( borewit@hidden.com )" -v -X POST --header "Content-Type:application/xml" -d @metadata.xml http://musicbrainz.org/ws/2/recording/?client=WhatMusic-0.0.3
```

I noticed CURL used a relative path for the uri: `uri="/ws/2/recording/?client=WhatMusic-0.0.3"`

I updated the code so a relative path is passed to the digest authentication and it worked.

### Your Environment

| software         | version
| ---------------- | -------
| request          | 2.88.1
| node             | 10.13.0
| npm              | 6.4.1
| Operating System | Windows 10

**Comment by muscleman** [comment]
yep, i got a issue where i only get success about 60% of the time.

https://github.com/muscleman/Wallet-Thingy

**Comment by muscleman** [comment]
looks like it's not fixed.

`  getbalance   { StatusCodeError: 401 - "<html><head><title>Unauthorized Access</title></head><body><h1>401 Unauthorized</h1></body></html>"
    at new StatusCodeError (/home/gruserver/cryptonote-nodejs-pool/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/home/gruserver/cryptonote-nodejs-pool/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/home/gruserver/cryptonote-nodejs-pool/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/home/gruserver/cryptonote-nodejs-pool/node_modules/request/request.js:185:22)
    at Request.emit (events.js:182:13)
    at Request.<anonymous> (/home/gruserver/cryptonote-nodejs-pool/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:182:13)
    at IncomingMessage.<anonymous> (/home/gruserver/cryptonote-nodejs-pool/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:273:13)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1094:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

  name: 'StatusCodeError',
  statusCode: 401,
  message:
   '401 - "<html><head><title>Unauthorized Access</title></head><body><h1>401 Unauthorized</h1></body></html>"',
  error:
   '<html><head><title>Unauthorized Access</title></head><body><h1>401 Unauthorized</h1></body></html>',
  options:
   { uri: 'http://127.0.0.1:19996/json_rpc',
     method: 'POST',
     encoding: 'utf8',
     headers: { 'Content-Type': 'application/json' },
     json:
      { id: '1',
        jsonrpc: '2.0',
        method: 'getbalance',
        params: {},
        auth: [Object],
        agent: [Agent],
        forever: true },
     callback: [Function: RP$callback],
     transform: undefined,
     simple: true,
     resolveWithFullResponse: false,
     transform2xxOnly: false },
  response:
   IncomingMessage {
     _readableState:
      ReadableState {
        objectMode: false,
        highWaterMark: 16384,
        buffer: BufferList { head: null, tail: null, length: 0 },
        length: 0,
        pipes: null,
        pipesCount: 0,
        flowing: true,
        ended: true,
        endEmitted: true,
        reading: false,
        sync: true,
        needReadable: false,
        emittedReadable: false,
        readableListening: false,
        resumeScheduled: false,
        emitClose: true,
        destroyed: false,
        defaultEncoding: 'utf8',
        awaitDrain: 0,
        readingMore: true,
        decoder: [StringDecoder],
        encoding: 'utf8' },
     readable: false,
     _events:
      [Object: null prototype] {
        end: [Array],
        close: [Array],
        data: [Function],
        error: [Function] },
     _eventsCount: 4,
     _maxListeners: undefined,
     socket:
      Socket {
        connecting: false,
        _hadError: false,
        _handle: [TCP],
        _parent: null,
        _host: null,
        _readableState: [ReadableState],
        readable: true,
        _events: [Object],
        _eventsCount: 7,
        _maxListeners: undefined,
        _writableState: [WritableState],
        writable: false,
        allowHalfOpen: false,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: null,
        _server: null,
        parser: null,
        _httpMessage: [ClientRequest],
        [Symbol(asyncId)]: 188,
        [Symbol(lastWriteQueueSize)]: 0,
        [Symbol(timeout)]: null,
        [Symbol(kBytesRead)]: 0,
        [Symbol(kBytesWritten)]: 0 },
     connection:
      Socket {
        connecting: false,
        _hadError: false,
        _handle: [TCP],
        _parent: null,
        _host: null,
        _readableState: [ReadableState],
        readable: true,
        _events: [Object],
        _eventsCount: 7,
        _maxListeners: undefined,
        _writableState: [WritableState],
        writable: false,
        allowHalfOpen: false,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: null,
        _server: null,
        parser: null,
        _httpMessage: [ClientRequest],
        [Symbol(asyncId)]: 188,
        [Symbol(lastWriteQueueSize)]: 0,
        [Symbol(timeout)]: null,
        [Symbol(kBytesRead)]: 0,
        [Symbol(kBytesWritten)]: 0 },
     httpVersionMajor: 1,
     httpVersionMinor: 1,
     httpVersion: '1.1',
     complete: true,
     headers:
      { server: 'Epee-based',
        'content-length': '98',
        'content-type': 'text/html',
        'last-modified': 'Thu, 07 Feb 2019 01:13:45 GMT',
        'accept-ranges': 'bytes',
        connection: 'close',
        'www-authenticate':
         'Digest qop="auth",algorithm=MD5,realm="monero-rpc",nonce="sxVzYbeBOW4VSkFqF6f4iA==",stale=false, Digest qop="auth",algorithm=MD5-sess,realm="monero-rpc",nonce="sxVzYbeBOW4VSkFqF6f4iA==",stale=false' },
     rawHeaders:
      [ 'Server',
        'Epee-based',
        'Content-Length',
        '98',
        'Content-Type',
        'text/html',
        'Last-Modified',
        'Thu, 07 Feb 2019 01:13:45 GMT',
        'Accept-Ranges',
        'bytes',
        'Connection',
        'close',
        'WWW-authenticate',
        'Digest qop="auth",algorithm=MD5,realm="monero-rpc",nonce="sxVzYbeBOW4VSkFqF6f4iA==",stale=false',
        'WWW-authenticate',
        'Digest qop="auth",algorithm=MD5-sess,realm="monero-rpc",nonce="sxVzYbeBOW4VSkFqF6f4iA==",stale=false' ],
     trailers: {},
     rawTrailers: [],
     aborted: false,
     upgrade: false,
     url: '',
     method: null,
     statusCode: 401,
     statusMessage: 'Unauthorized',
     client:
      Socket {
        connecting: false,
        _hadError: false,
        _handle: [TCP],
        _parent: null,
        _host: null,
        _readableState: [ReadableState],
        readable: true,
        _events: [Object],
        _eventsCount: 7,
        _maxListeners: undefined,
        _writableState: [WritableState],
        writable: false,

        allowHalfOpen: false,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: null,
        _server: null,
        parser: null,
        _httpMessage: [ClientRequest],
        [Symbol(asyncId)]: 188,
        [Symbol(lastWriteQueueSize)]: 0,
        [Symbol(timeout)]: null,
        [Symbol(kBytesRead)]: 0,
        [Symbol(kBytesWritten)]: 0 },
     _consuming: false,
     _dumped: false,
     req:
      ClientRequest {
        _events: [Object],
        _eventsCount: 5,
        _maxListeners: undefined,
        output: [],
        outputEncodings: [],
        outputCallbacks: [],
        outputSize: 0,
        writable: true,
        _last: true,
        chunkedEncoding: false,
        shouldKeepAlive: false,
        useChunkedEncodingByDefault: true,
        sendDate: false,
        _removedConnection: false,
        _removedContLen: false,
        _removedTE: false,
        _contentLength: null,
        _hasBody: true,
        _trailer: '',
        finished: true,
        _headerSent: true,
        socket: [Socket],
        connection: [Socket],
        _header:
         'POST /json_rpc HTTP/1.1\r\nContent-Type: application/json\r\nhost: 127.0.0.1:19996\r\naccept: application/json\r\ncontent-length: 391\r\nConnection: close\r\n\r\n',
        _onPendingData: [Function: noopPendingOutput],
        agent: [Agent],
        socketPath: undefined,
        timeout: undefined,
        method: 'POST',
        path: '/json_rpc',
        _ended: true,
        res: [Circular],
        aborted: undefined,
        timeoutCb: null,
        upgradeOrConnect: false,
        parser: null,
        maxHeadersCount: null,
        [Symbol(isCorked)]: false,
        [Symbol(outHeadersKey)]: [Object] },
     request:
      Request {
        _events: [Object],
        _eventsCount: 5,
        _maxListeners: undefined,
        uri: [Url],
        method: 'POST',
        encoding: 'utf8',
        headers: [Object],
        readable: true,
        writable: true,
        explicitMethod: true,
        _qs: [Querystring],
        _auth: [Auth],
        _oauth: [OAuth],
        _multipart: [Multipart],
        _redirect: [Redirect],
        _tunnel: [Tunnel],
        _rp_resolve: [Function],
        _rp_reject: [Function],
        _rp_promise: [Promise],
        _rp_callbackOrig: undefined,
        callback: [Function],
        _rp_options: [Object],
        setHeader: [Function],
        hasHeader: [Function],
        getHeader: [Function],
        removeHeader: [Function],
        localAddress: undefined,
        pool: {},
        dests: [],
        __isRequestRequest: true,
        _callback: [Function: RP$callback],
        proxy: null,
        tunnel: false,
        setHost: true,
        originalCookieHeader: undefined,
        _disableCookies: true,
        _jar: undefined,
        port: '19996',
        host: '127.0.0.1',
        path: '/json_rpc',
        _json: true,
        body:
         '{"id":"1","jsonrpc":"2.0","method":"getbalance","params":{},"auth":{"user":"test","password":"1234","sendImmediately":false},"agent":{"_events":{},"_eventsCount":1,"defaultPort":80,"protocol":"http:","options":{"maxSockets":1,"keepAlive":true,"path":null},"requests":{},"sockets":{},"freeSockets":{},"keepAliveMsecs":1000,"keepAlive":true,"maxSockets":1,"maxFreeSockets":256},"forever":true}',
        httpModule: [Object],
        agentClass: [Function],
        agent: [Agent],
        _started: true,
        href: 'http://127.0.0.1:19996/json_rpc',
        req: [ClientRequest],
        ntick: true,
        response: [Circular],
        originalHost: '127.0.0.1:19996',
        originalHostHeaderName: 'host',
        responseContent: [Circular],
        _destdata: true,
        _ended: true,
        _callbackCalled: true },
     toJSON: [Function: responseToJSON],
     caseless: Caseless { dict: [Object] },
     body:
      '<html><head><title>Unauthorized Access</title></head><body><h1>401 Unauthorized</h1></body></html>' } }
`

**Comment by Stono** [comment]
https://github.com/request/request/issues/2388
