### ISSUE TITLE
TypeError: request.post is not a function

### ISSUE THREAD

**Issue by kwright02** [request/request#3095]
### Summary
I've installed request via nom and have a const request = require("request"); at the top of my file but when I run my program it says that request.post isn't a function

### Simplest Example to Reproduce
Install latest built and try to make a post request

```js
request.post('http://' + config.devices.port["2002"] + ":3000/api/mysql", {
      json: request.body.data,
      method: "POST"
    }, (error, response, body) => {
      if(error){
        console.error(error);
        console.log(" <- Process return (REJECTED) from " + config.devices.port["2002"] + ":30301/api/mysql");
        res.send("Failed to pass process mysql to " + config.devices.port["2002"] + ":30301/api/mysql");
        return;
      }
      console.log(" <- Process return (ACCEPTED) from " + config.devices.port["2002"] + ":30301/api/mysql");
      res.send("Passed process mysql to " + config.devices.port["2002"] + ":30301/api/mysql\nWaiting for response delivery....");
      return;
    });
```

### Expected Behavior
It is expected that request.post _is_ infant a function/method

### Current Behavior
Currently node doesn't think that request.post is a method

### Possible Solution
Not Sure
### Context
I have two instances of node running on two different devices, each listening for a post request from the other, this is to create a two player game on to local machines using http requests

### Your Environment
Both devices are raspberry pi one is a 3b the other is a 1a both running raspbian stretch (latest)

**Comment by AndrewBuiltThis** [comment]
I'm able to reproduce. It appears that the request.post method has some issues in its scope.

**Comment by aakanksha-sib** [comment]
Hi,
I am still facing the same error. Is there any update ?

**Comment by computerFriend** [comment]
I am experiencing the same problem

**Comment by computerFriend** [comment]
Hi, I think I might know the issue here: Because you are referencing request.body.data, I am assuming you have defined a "request" somewhere else in your code -- which means that the npm module, 'request', is being overwritten by the request object you have defined.

if you import the module with another name, this may solve your problem, e.g.,

`const requestModule = require('request')`
...
`requestModule.post('http://' + config.devices.port["2002"] + ":3000/api/mysql", { `
...

**Comment by Mustafa-Hayati** [comment]
I have the same issue. It works for request.get but not for request.post.

**Comment by ducnguyenhuy-agilityio** [comment]
> Hi, I think I might know the issue here: Because you are referencing request.body.data, I am assuming you have defined a "request" somewhere else in your code -- which means that the npm module, 'request', is being overwritten by the request object you have defined.
> 
> if you import the module with another name, this may solve your problem, e.g.,
> 
> `const requestModule = require('request')`
> ...
> `requestModule.post('http://' + config.devices.port["2002"] + ":3000/api/mysql", { `
> ...

I used the autosuggestion in code editor and it was auto-required **request** const and this issue occurred
