### ISSUE TITLE
Multipart/form-data returns 400 bad request with https

### ISSUE THREAD

**Issue by popod** [request/request#3098]
### Summary

My application send a `multipart/form-data` POST query containing a `zip` file and a `json` object to my server.

With the application running in debug mode, all works fin, but when I run it in production (this is an `Electron` app), I've this error:

I receive a 400 bad request error ! But it seems that on the server side all works fine (the server run `express` and I use `multer` to handle the form-date parameters).

### Simplest Example to Reproduce

```js
import request from 'request'
import fs from 'fs'

request.post({
      url: 'https://xxx.mydomain.com/some/url',
      multipart: {
        chunked: false,
        data: [{
          'Content-Disposition': 'form-data; name="prop"',
          'Content-Type': 'application/json',
          body: JSON.stringify({
            date: new Date(),
            test: 'hell0',
            valid: true
          })
        }, {
          'Content-Disposition': 'form-data; name="fileToUpload"; filename="fileToUpload.zip"',
          'Content-Type': 'application/zip',
          body: fs.createReadStream('./fileToUpload.zip')
        }]
      },
      headers: {
        'Content-Type': 'multipart/form-data',
        'User-Agent': 'some-user-agent',
        'Cookie': 'sessionId=xxxxxxxxxx'
      }
    }, function optionalCallback (err, httpResponse, body) {
      if (err) {
        // why the 400 code is not an error ?
        console.error('upload failed:', err)
      }

      // here I get a statusCode = 400 and a body = '' when running this in production.
      console.log(httpResponse.statusCode, body)

      if (httpResponse.statusCode !== 200) {
        console.log('ok')
      }

      console.log('Upload successful! Server responded with:', body)
    })
```

I am doing something wrong ? What could be the problem ?

And second question: why the 400 code is not an error ?

### Environment

| software         | version
| ---------------- | -------
| request          | 2.88.0
| node             | 10.14.2
| npm              | 6.5.0
| Operating System | macOS Mojave

**Comment by impactcolor** [comment]
@popod did you ever find a solution for this?  I'm experiencing similar error.

**Comment by popod** [comment]
@impactcolor I've not found any solutions.. I use `got` now : https://github.com/sindresorhus/got
