### ISSUE TITLE
Cookies management

### ISSUE THREAD

**Issue by nonyy** [request/request#3099]
So I created let's say mailer class that needs to have cookie jar separate for each class instance. 

Like 

class Mailer {
    constructor() {
        this.jar = new jar();    
}
}

Then in each method I want to use this jar and use the request magic to do it. My question is it possible? Sadly API docs look kind of wrong when it comes down to cookies.

**Comment by Sesamestrong** [comment]
`request.defaults(options)` returns an object that works exactly like `request` does, but it has the options that you specify by default.
```node
class Mailer {
  constructor(){
    this.jar=request.jar()
    this.request=request.defaults({jar:this.jar});
    //Rest of constructor goes here
  }
  exampleMethod(name){
    this.request.get("https://example.com/"+name,callback);//Automatically uses this.jar
  }
}
```
The API docs are right; I have used cookie jars (specifically multiple instances of them) in the past and they work as described. You can find more info about `request.defaults()` [here](https://github.com/request/request#convenience-methods).
