### ISSUE TITLE
Proxy Timeout

### ISSUE THREAD

**Issue by CharlieJ1911** [request/request#3100]
Hey,

Any reason why `timeout` doesn't seem to function? I'm trying to test proxies from an array, I set the timeout variable but doesn't do anything.

```js
				request(
					'https://api.ipify.org?format=json',
					{
						proxy: 'http://' + value,
						headers: { Connection: 'close' },
						timeout: 10000
					},```

Thanks

**Comment by CharlieJ1911** [comment]
**Update:**
So if I turn `tunnel` to `false` it goes through?

Does that make any difference in regards to the proxy working or not?

**Comment by DalerAkhmetov** [comment]
Hi.
I also need to pass timeout for proxy. More accurate I need to pass timeout to TunnelingAgent options to constraint time for waiting tunnel's socket initialization.
When tunnel agent is being created in "Tunnel.prototype.setup" function, tunnel creator "tunnelFn" receives tunnelOptions created by "constructTunnelOptions". Are there reasons why constructTunnelOptions doesn't  define timeout in tunnelOptions.proxy?

**Comment by it-fm** [comment]
same problem here, you can try to manually cancel the request using
 ```
let requestSent = request(options, callback)
setTimeout(() => {
       console.log("cancel")
       requestSent.abort()
}, 3000);
```

**Comment by DalerAkhmetov** [comment]
@it-fm, thank you.

**Comment by linbodong** [comment]
@it-fm ,thanks

**Comment by arrowing** [comment]
+1
