### ISSUE TITLE
Upload stream and get response body

### ISSUE THREAD

**Issue by murat-mehmet** [request/request#3108]
### Summary
Getting empty body response when uploading a file stream

### Simplest Example to Reproduce
```js
request.post({
            url: url,
            headers: {
                 'Content-Type': 'image/jpeg',
                 'Accept': 'application/json, text/plain, */*'
            },
            body: fs.createReadStream(filePath)
        }, (error: any, response: Response, body: any) => {
                console.log(body);
        });       
});
```

### Expected Behavior
Should get response correctly

### Current Behavior
body is empty string

NOTE: I tried to listen through fiddler and added following to options:
```js
...
proxy: 'http://localhost:8888',
rejectUnauthorized: false
...
```
Then body was returned successfully. I don't know why...

### Your Environment
| software         | version
| ---------------- | -------
| request          | 2.88.0
| node             | 9.11.2
| npm              | 5.6.0
| Operating System | Win 10

**Comment by imakan** [comment]
do  you resolve it?

**Comment by murat-mehmet** [comment]
nope

**Comment by ignasposka** [comment]
I am stuck on the same problem, @murat-mehmet did you find any workaround on this? If not, maybe you could suggest any more ways to send application/octet-stream with node js to an API?
