### ISSUE TITLE
abort() not working in React Native

### ISSUE THREAD

**Issue by zpalmtree** [request/request#3110]
### Summary
In react-native, aborting a request fails, due to `undefined is not a function (evaluating 'self.req.abort()')`

The same code, in a node environment, works perfectly.

### Simplest Example to Reproduce

```js
let bufferLength = 0;

const req = request({
    body: { blockCount: 20, startHeight: 208297 },
    json: true,
    method: 'POST',
    timeout: 10 * 1000,
    url: 'https://blockapi.turtlepay.io/getwalletsyncdata',
}, (error, response, body) => {
    if (error) {
        console.log(error);
    }

    console.log(body);
});

req.on('data', (chunk) => {
    bufferLength += chunk.length;

    if (bufferLength > 1024 * 1024) {
        req.abort();
        throw new Error('response too large');
    }
});
```

### Expected Behavior
A request can be aborted.

### Current Behavior
Aborting a request throws.

### Context
Request works perfectly fine for everything else in React Native - It was only when I went to implement aborting requests when they are too large that I ran into this. If there's an alternative way to abort the request to work around this, that's fine by me.

I believe this may be related to https://github.com/request/request/issues/2315 or https://github.com/request/request/pull/1955

### Your Environment

| software         | version
| ---------------- | -------
| request          | 2.88.0
| Operating System | Android
| React Native | 0.57

**Comment by zpalmtree** [comment]
Hmm, looks like `self` isn't defined in react-native? https://github.com/bitinn/node-fetch/pull/545/files

**Comment by Angelk90** [comment]
@zpalmtree:

It was requested request its a progetto in react-native its snack.expo.io ottengo il seguente problema:

Device: (1052: 881) Unable to resolve module 'module: //net.js'
   Evaluating module: //net.js
   Evaluating module: //request.js
   Evaluating module: //App.js.js
   Loading module: //App.js

Link: https://snack.expo.io/ry9W5Kr64

**Comment by Angelk90** [comment]
@zpalmtree:

If I use request on a react-native project on snack.expo.io I get the following problem:

Device: (1052: 881) Unable to resolve module 'module: //net.js'
   Evaluating module: //net.js
   Evaluating module: //request.js
   Evaluating module: //App.js.js
   Loading module: //App.js

Link: https://snack.expo.io/ry9W5Kr64

**Comment by mi-mazouz** [comment]
any updade?

**Comment by Angelk90** [comment]
any update?
