### ISSUE TITLE
res.set is not a function

### ISSUE THREAD

**Issue by lilan123** [request/request#3111]
error res.set is not a function. Please see below code

    request(URL, option, function (error, response, body) {         
        if (error) {
          res.writeHead(500);
          res.end(error);
        }else{   
          res.set(response.headers); // error
          res.writeHead(response.statusCode);
          res.end(body);
          
        }
    });

**Comment by zpalmtree** [comment]
`res` isn't assigned anywhere. Did you mean to use `response`?
