### ISSUE TITLE
Https request with a proxy ,poll:false timeout

### ISSUE THREAD

**Issue by xiaomingplus** [request/request#3118]
### Summary

When I request a https url with proxy,and set option `pool`:`false`,request module is not working,but if the url is a http url,it worked,or if I don't set option `pool`:`false`,it also worked.

### Simplest Example to Reproduce

```js
const request = require("request");
request(
  "https://www.google.com",
  {
    pool:false,
    proxy: "http://127.0.0.1:1087"
  },
  function(err, res, body) {
    if (err) {
      console.log("err", err);
      return;
    }
    console.log("body", body);
  }
);
```

### Expected Behavior

https request with proxy,and `poll`:`false` worked well.

### Current Behavior

Timeout.

### Your Environment

| software         | version
| ---------------- | -------
| request          | 2.88.0
| node             |v8.12.0
| npm              |6.4.1
| Operating System | mac os

**Comment by nodeplusplus** [comment]
In my case (Node v10.x), without `pool: false` my request will throw error
`RequestError: Error: tunneling socket could not be established, statusCode=400`

**Comment by cnscorpions** [comment]
request with proxy not work at all. :(
