### ISSUE TITLE
Support passing NO_PROXY in proxy settings

### ISSUE THREAD

**Issue by flotwig** [request/request#3122]
### Summary

Currently, the only way to specify a proxy exclusion list for `request` is to set `process.env.NO_PROXY` before making a request. It would be nice to be able to pass `noProxy` along with the `proxy` option for use in cases where the `NO_PROXY` environment variable is not set but we still want to use the proxy bypass functionality.

### Expected Behavior

```js
request({
  uri: someUrl,
  proxy: 'http://some-proxy.com',
  noProxy: 'localhost,127.0.0.1,some-site.com'
}); // only uses `proxy` if `someUrl` does not match `noProxy`
```

### Context

Just trying to pass requests through to a user-defined proxy that doesn't come from environment variables.

**Comment by paztis** [comment]
It might be very useful. Perhaps Tarn will accept to support the no-proxy option in npmrc if this option is available on request.

**Comment by paztis** [comment]
I've created a PR for this with the strict minimum change here #3158 
A **noProxy** option is available in the settings and only affect the **proxy** option. 
It has no effect over env var (HTTP_PROXY, HTTPS_PROXY, NO_PROXY). It only clears the **proxy** option in case the url it is part of the **noProxy** value

**Comment by paztis** [comment]
Any news about it ? Is there any support for request lib ?

**Comment by flotwig** [comment]
@paztis this repository is unmaintained, see #3142

**Comment by paztis** [comment]
Understand. I'm a bit disappointed as yarn is still using request, and without this enhancement yarn will never support as npm the noProxy option...
