### ISSUE TITLE
rangeerror array buffer allocation failed at request.js 1135:30

### ISSUE THREAD

**Issue by Kyaw-Zin-Thant** [request/request#3150]
### Simplest Example to Reproduce

```js
request({
  method: 'GET',
  url: 'http://example.com', // a public URL that we can hit to reproduce, if possible
  more: { 'options': 'here' }
},
```

### Your Environment

| software         | version
| ---------------- | -------
| request          |
| node             |
| npm              |
| Operating System |

**Comment by quadeinc** [comment]
Can you please explain it more
