### ISSUE TITLE
Unhandled promise rejection happens when `StatusCodeError 4XX` thrown.

### ISSUE THREAD

**Issue by Rubinhuang9239** [request/request#3154]
### Summary
Unhandled promise rejection happens when `StatusCodeError` thrown.
```
UnhandledPromiseRejectionWarning: StatusCodeError: 4xx
```

### Simplest Example to Reproduce

```TypeScript
const downloadFile = async (url) => {
  return new Promise((resolve, reject) => {
    
    const writeStream = fs.createWriteStream("./download_folder");
    writeStream.on("error", err => {
      reject(err);
    });
    writeStream.on("finish", () => {
      console.log("File downloaded!");
      resolve();
    });

    request.get(url)
    .on("response", res => {
      if(res.statusCode !== 200){ // possible to get 404
        reject(res.statusCode); 
      }
      res.pipe(writeStream);
    })
    .on("error", err => {
      reject(err);
    });
  });
};

try{
    downloadFile([url that response 404]);
}
catch(err){
    console.log(err);
}

```

### Current Behavior
Console complains:
```
(node:25095) UnhandledPromiseRejectionWarning: RequestError: 404
(node:25095) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which
```

### Environment
| software         | version
| ---------------- | -------
| request          | 2.88.1
| node             | 10.15.0
| npm              | 6.9.0
| Operating System | MacOS

Note:
I'm working with typescript
I believe that's some unhandled reject happened within the package, and I'm not able to handle it in the callback functions. I'm totally ok with handle `statusCodeError` within the response logic.

I'm also using `request-promise-native` in the same time, I'm using request here since `.pipe` is not encouraged to use with `request-promise` and `request-promise-native`.

Relate to https://github.com/request/request/issues/2992

**Comment by HanwenZheng** [comment]
Got the same error from a docker environment but worked just fine in all other environments while developing FE.
