### ISSUE TITLE
Multiple requests in a loop

### ISSUE THREAD

**Issue by termitek12** [request/request#3167]
When I have few requests, they are working fine all the time. But when **multiple requests in a loop** are used and _bandwidth of a connection is low_ - node (v8.10) simply freeze. Is there anything to resolve this issue? I have checked the issues and there are few that can be related - but non of them are a resolve for this issue.

https://github.com/request/request/issues/2323
https://github.com/request/request/issues/1272
https://github.com/request/request/issues/443
https://github.com/request/request/issues/311

I have read this in a main page: https://github.com/request/request#requestdefaultsoptions

> "pool - an object describing which agents to use for the request. If this option is omitted the request will use the global agent (as long as your options allow for it). Otherwise, request will search the pool for your custom agent. If no custom agent is found, a new agent will be created and added to the pool. Note: pool is used only when the agent option is not specified.
> 
> A maxSockets property can also be provided on the pool object to set the max number of sockets for all agents created (ex: pool: {maxSockets: Infinity}). Note that if you are sending multiple requests in a loop and creating multiple new pool objects, maxSockets will not work as intended. To work around this, either use request.defaults with your pool options or create the pool object with the maxSockets property outside of the loop."

But I can't make it to work. Should I use **request.defaults(options)**?

```
const baseRequest = request.defaults({
  pool: {maxSockets: Infinity}
})

const = linksLength = 1000;

for (i=0, i <linksLength, i++) {
   baseRequest(link, function(err, resp, body) {
   //etc.
   };
}
```

**Comment by x1957** [comment]
Do you solve the problem?
