### ISSUE TITLE
HTTPS request with self-signed certificates in browser (reactjs app)

### ISSUE THREAD

**Issue by flrkli** [request/request#3171]
I've tried a lot and I've even researched more on the topic on how to make an https request to a site with a self-signed certificate from my singlepage reactjs app (running in the browser). 
My current understanding is that it won't work from the browser except I am adding the certificate manually to the browser's certificate store. Though what I'd like to have is that I can do a request and either ignore the security or pass the certificate directly with it. So something like this:
``` 
var options = {
      url: 'https://10.0.61.1:5000/info',
      strictSSL: false,
      rejectUnauthorized: false
  };
  request.get(options).on('response', function(response) {
    console.log(response.statusCode) 
    console.log(response.headers['content-type']) 
  })
```
I found a lot of posts which say you need to set rejectUnauthorized to false and many other possible options but as I understood it this would just work in node.js. 

Do you know any solution to my problem? Is it possible? If yes, how ;)?

**Comment by jiangbo2015** [comment]
```
request({
url: 'https://abc',
strictSSL: false
})
```
