### ISSUE TITLE
Should request-specific hacks be removed from node core?

### ISSUE THREAD

**Issue by elliot-nelson** [request/request#3176]
### Summary

Today node core contains hacks specifically to support `request`; this code runs when using "new pipelines" (not `request().pipe()`, but rather, `stream.pipeline(request(), ...)`).

Lines in question:

https://github.com/nodejs/node/blob/master/lib/internal/streams/end-of-stream.js#L70-L72
https://github.com/nodejs/node/blob/master/lib/internal/streams/end-of-stream.js#L77-L78
https://github.com/nodejs/node/blob/master/lib/internal/streams/end-of-stream.js#L93

It seems to me, these lines probably don't belong in node core; that's especially true if `request` is intended to slowly fade away over the next 5-10 years.

### Possible issues

In an attempt to determine what problems removing these lines would cause, I took request's `tests/test-pipes.js` unit tests and replaced all the pipes with new-style pipes (that is: I replaced all `a.pipe(b)` with `stream.pipeline(a, b)`).  Running both against edge node and against locally-compiled node with the lines above removed produces the same results.

### Next steps

If you can think of a test case (or an existing production usage) that would _fail_ if those lines were removed, then I would want to add that unit test to `request` so it could be included in nodejs/citgm (and add a comment in node core referring to that test).

If we can't find a test case or existing production usage that would change, then it seems relatively safe to just remove the lines.

### Your Environment

| software         | version
| ---------------- | -------
| request          | 2.88.0
| node             | 10.15.3 & 12.5.0 (baseline), 13-pre (compiled for testing)
| npm              | 6.4.1
| Operating System | macos

**Comment by mikeal** [comment]
This is more of a question for Node.js Core than request. As a project, we don’t really care, but as a platform Node.js cares a lot about breaking running apps. Hopefully deprecating the project will reduce the number of projects that depend on request over time, but given how widely request is already adopted I doubt Core will decide to break that many applications.
