### ISSUE TITLE
SSL problem with Debian Buster

### ISSUE THREAD

**Issue by TA2k** [request/request#3191]
On Debian Buster I get following error when I try to access a https via normal get request.
```
{"errno":"EPROTO","code":"EPROTO","syscall":"write"}
Request error:Error: write EPROTO 140710724777792:error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1536:SSL alert number 40
```

request.get({
	url: "https://warnung.bund.de/bbk.mowas/gefahrendurchsagen.json",
	followAllRedirects: true
	}, (err, resp, body) => {}});

if you change  /etc/ssl/openssl.cnf it will solve the problem locally:
[system_default_sect]
MinProtocol = TLSv1.2
CipherString = DEFAULT@SECLEVEL=2
to:
[system_default_sect]
MinProtocol = TLSv1.2
CipherString = DEFAULT@SECLEVEL=1

**Comment by kibertoad** [comment]
This is unlikely to be a problem with request. What is likely to be happening is certificates on your server are not secure.
