### ISSUE TITLE
memory leak while getting proxy error

### ISSUE THREAD

**Issue by SFx2018** [request/request#3214]
Hello, I'm sending a lot of proxy requests (using this library) per hour, and I tested many different versions of nodejs/request and I noticed that memory leak its only happening while getting this error: 
``Error: tunneling socket could not be established, statusCode=407``

My proxy provider is sometimes full and I can't do more reuqests thats why I'm getting this message.

When I'm using same proxy w/o error my node proccess can work even 7 days without getting any memory leak, but when this error is appearing my process slowly getting more 'heavy' .

How can I fix it? (restarting process of course helps for next a few hours)
I want to remind that using same code with same proxy (but without getting this error) is not triggering any memory leak.

**Comment by Rem486** [comment]
Hello, do you solve the problem?

**Comment by oorel4** [comment]
I have same issue
