### ISSUE TITLE
Simple request fails with request, succeeds with curl; what's the difference?

### ISSUE THREAD

**Issue by joelclimbsthings** [request/request#3231]
### Summary
I've tried to [post on stackoverflow](https://stackoverflow.com/questions/58885849/very-simple-api-request-fails-with-request-js-works-with-curl/58886006?noredirect=1#comment104096386_58886006) for this issue, but haven't received any useful responses and it seems like a very simple question. 

I have a very simple curl request to the Squarespace API that works fine:

`curl "https://api.squarespace.com/1.0/commerce/orders?modifiedAfter=2019-11-01T12:00:00Z&modifiedBefore=2019-11-15T12:00:00Z" \
  -H "Authorization: Bearer abcde" `

I've tried to implement this same request using requestjs but receive a cryptic error. 

```js
const response = await request({
     method: 'GET',
     uri:
        'https://api.squarespace.com/1.0/commerce/orders?modifiedAfter=2019-11-01T12:00:00Z&modifiedBefore=2019-11-15T12:00:00Z',
     headers: {
        Authorization: 'Bearer abcde'
     }
  });
```

Not that I'm actually using request-promise-native with async/await, but I've tried with standard request as well with the same result. 

### Simplest Example to Reproduce
Request above

### Expected Behavior
Receive order information

### Current Behavior
Receive error response (seemingly consistent with behavior as if authorization header wasn't intact, but as far as I can tell it is)

### Your Environment

| software         | version
| ---------------- | -------
| request          | 2.88.0
| node             |  12.3.1
| npm              | 
| Operating System | ubuntu

**Comment by Dygerati** [comment]
I should add that I just tried the same request using `node-fetch` and it works fine as well, virtually the same interface/params as request. I am already using request in many other places in my project and I'd really like to understand what's failing here. 

Much appreciated.
