### ISSUE TITLE
request can't seem to parse the body of https://www.yahoo.com/

### ISSUE THREAD

**Issue by m4bwav** [request/request#3234]
### Simplest Example to Reproduce
`use request('https://www.yahoo.com/', callback);`

and the response body doesn't seem to have normal text.  It just seems to have has garbled noise.

No options, just a callback.

### Expected Behavior
some kind of html structure or text

### Current Behavior
a bunch of garbage text and symbols

### Context
People who use my package are complaining about the yahoo response.

### Your Environment
windows, but i'm not sure it matters.

| software         | version
| ---------------- | -------
| request          |2.88
| node             | v10.16.0
| npm              |6.9.0
| Operating System | windows 10

**Comment by VladyslavLukyanenko** [comment]
Something to do with the encoding, set the correct header.

**Comment by m4bwav** [comment]
> 
> 
> Something to do with the encoding, set the correct header.

Why does this particular site require a particular header?  Do browsers detect the encoding and request does not?

**Comment by VladyslavLukyanenko** [comment]
> > Something to do with the encoding, set the correct header.
> 
> Why does this particular site require a particular header? Do browsers detect the encoding and request does not?

Exactly.
```
const request = require('request');
request({
    uri: 'https://www.yahoo.com/',
    headers: {
        'accept-language': 'es-ES,es;q=0.9,ru;q=0.8',
        'accept-encoding': 'br',
        'accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9'
    }
}, function(error, response, body) {
    console.log(body);
});```
Worked for me

**Comment by m4bwav** [comment]
Ok, fair enough.  It would be cool if there was an option for that.  Thanks!
