### ISSUE TITLE
POST cant't work  good

### ISSUE THREAD

**Issue by lq8080** [request/request#3251]
this library is really nice , but when I use post to submit some data，it response nothing. I’m tried  many way to request.
 
I'm trying to use Node to make a simulated login. The next request requires the cookie returned by the previous request. I don't understand the usage of cookieJar. I wonder if I can automatically save and pass cookies like the Python Request Library?

Looking forward to your reply.

**Comment by hong4rc** [comment]
You can use `const yourRequest = request.defaults({jar: true})`

Then you use `yourRequest` instead of normal `request`

![image](https://user-images.githubusercontent.com/19208123/75094786-dabb2100-55c0-11ea-847c-014b3c13ab89.png)
