### ISSUE TITLE
Cant set cookies from previous request

### ISSUE THREAD

**Issue by mastercho** [request/request#3253]
### Summary
I'm trying to set cookies which i get from another request with getCookies() but every time i try to set cookies with setCookies() im getting:
 ```
TypeError: str.trim is not a function (Request-Promise/Tough-Cookie)

```
### Simplest Example to Reproduce
So this is a request where i have to set cookies which i get from recent request and variable looks like this
`[{"domain":"domain.com","path":"/","secure":true,"expires":"2018-06-19T15:36:04.000Z","key":"key1","value":"val1","httpOnly":false,"hostOnly":true},{"domain":"domain.com","path":"/","secure":true,"expires":"2018-06-19T15:36:04.000Z","key":"key2","value":"val2","httpOnly":false,"hostOnly":true}]
`
And this is the reuqest where im getting error
```
var request = require('request');

var jar = request.jar();

jar.setCookie(cookies, ".domain.com");



request({
	uri: "https://www.domain.com/",
	method: "GET",
	headers: {
'Accept': 'application/json, text/javascript, */*; q=0.01',
'Accept-Encoding': 'gzip, deflate, br',
'Accept-Language': 'bg,en-US;q=0.9,en;q=0.8,tr;q=0.7',
'Content-Type': 'application/json',
'Referer': 'https://www.google.com/',
'Sec-Fetch-Mode': 'cors',
'Sec-Fetch-Site': 'same-origin',
'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.79 Safari/537.36',
'X-Requested-With': 'XMLHttpRequest'	},
	timeout: 10000,
	followRedirect: true,
	maxRedirects: 10,
    jar:jar
    gzip: true
}, function(error, response, body) {
	console.log("Error" + error);
	console.log("Response: " + response);
	console.log("Body: " + body);
});
	
```

### Expected Behavior
I would be thankful if someone can help with this. Tried with toString() but getting cookie like

` {
               creation: "2019-12-27T16:53:57.964Z"
               hostOnly: true
               lastAccessed: "2019-12-27T16:53:57.964Z"
               path: "/"
               pathIsDefault: true
               value: "[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object]" 
           }`

**Comment by hong4rc** [comment]
Input for `jar.setCookie` is a cookie, not an array cookie.

Try this:

```js
cookies.forEach(cookie=> jar.setCookie(cookie, ".domain.com"))
// instead of
jar.setCookie(cookies, ".domain.com");
```

Related: [tough-cookie#setcookie](https://www.npmjs.com/package/tough-cookie#setcookiecookieorstring-currenturl-options-cberrcookie)
