### ISSUE TITLE
How to solve ESOCKETTIMEDOUT exception?

### ISSUE THREAD

**Issue by dexLeen** [request/request#3258]
### Summary
I have a special timeout issue, can someone help me check it? 
### Simplest Example to Reproduce
```js
request({
                method: 'GET',
                url: 'https://127.0.0.1:8866/v1/search/products-listings?in_stock=true%2Cfalse&locale=en_gb',
                headers: {'Content-Type': 'application/json'},
                json: true,
                timeout: 10000,
            }, function(err, response, body) {
                if (err) {
                    return reject(new Error('url:' + url + ' method:' + method + ' error: ' + err.message));
                }
            });
```

### Expected Behavior
Here I set a wrong request address. The expected result is that a timeout exception is thrown after 10 seconds. (The protocol header should be http instead of https)

### Current Behavior
```
{
"code": "Internal",
"message": "caused by Error: url:https://127.0.0.1:8866/v1/search/products-listings?in_stock=true%2Cfalse&locale=en_gb method:GET error: ESOCKETTIMEDOUT"
}
```
This request took at least 20 seconds, which means that it takes at least 20 seconds for me to get exception information.

### Possible Solution
I don't know how to solve this issue. Can somebody help me to check?

### Your Environment

| software         | version
| ---------------- | -------
| request          | ^2.88.0
| node             | v12.8.0
| npm              | 6.9.0
| Operating System | Ubuntu 16.04

**Comment by andeanfog** [comment]
Correct me if I am wrong but the last time I checked, `ESOCKETTIMEDOUT` and `ETIMEDOUT` refer to different protocols.

- `ETIMEDOUT` refers to an *HTTP* timeout.
- `ESOCKETTIMEDOUT` refers to a *TCP* timeout.

The `timeout` option for `request` controls the HTTP timeout behavior.
The error you are getting is a TCP timeout.
