### ISSUE TITLE
there is vulnerability in request package

### ISSUE THREAD

**Issue by qibobo** [request/request#3262]
The request package is vulnerable to Weak Authentication Algorithm. The `function` function in `oauth.js` uses SHA-1 for authentication which is no longer considered cryptographically secure. With enough resources an attacker might be able to crack the authentication mechanism and cause security attacks.

**Comment by csvan** [comment]
Request is deprecated so this will most likely not be fixed. https://github.com/request/request/issues/3142

**Comment by TheJavaGuy** [comment]
@qibobo On which function you mean exactly? `OAuth.prototype.buildBodyHash`?

**Comment by vinu-vrize** [comment]
Yes @TheJavaGuy, is there any solution for this

**Comment by csvan** [comment]
@vv619-perf don't use request

**Comment by vinu-vrize** [comment]
@csvan its not a direct dependency, it is being added as an indirectly dependent by other packages so won't be able to remove it completely. Security scan reported it at a very late stage and we won't be able to remove the request completely at this point in time. This is reported as an **insecure cipher** vulnerability, is there any way we can update it as a patch.
