### ISSUE TITLE
 Package install failed,angular new project creating

### ISSUE THREAD

**Issue by ribinshad** [request/request#3271]
when try to create new project there is an error
 Installing packages...npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules\watchpack\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules\webpack-dev-server\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! Unexpected end of JSON input while parsing near '...":"^4.1.2","nyc":"^11'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ribi\AppData\Roaming\npm-cache\_logs\2020-02-20T10_14_57_945Z-debug.log
× Package install failed, see above.
The Schematic workflow failed. See above.

i uninstall and reinstalled angular but no changes..
and cleared the cache force ly but no changes
[2020-02-20T10_14_57_945Z-debug.log](https://github.com/request/request/files/4230128/2020-02-20T10_14_57_945Z-debug.log)

**Comment by Edo78** [comment]
Just passing by ... did you noticed the error message you reported?
```
npm ERR! Unexpected end of JSON input while parsing near '...":"^4.1.2","nyc":"^11'
```
It looks like your `package.json` is not a valid json file.
Try to share it
