### ISSUE TITLE
same issue

### ISSUE THREAD

**Issue by ghost** [request/request#3272]
### Simplest Example to Reproduce

```js
request({
  method: 'GET',
  url: 'http://example.com', // a public URL that we can hit to reproduce, if possible
  more: { 'options': 'here' }
},
```

### Your Environment

| software         | version
| ---------------- | -------
| request          |
| node             |
| npm              |
| Operating System |

**Comment by hong4rc** [comment]
Please edit instead of creating new issue. Thank you
