### ISSUE TITLE
npm request has been deprecated

### ISSUE THREAD

**Issue by bc2019ghanshyam** [request/request#3283]
### Simplest Example to Reproduce

```js
request({
  method: 'GET',
  url: 'http://example.com', // a public URL that we can hit to reproduce, if possible
  more: { 'options': 'here' }
},
```

### Your Environment

| software         | version
| ---------------- | -------
| request          |
| node             |
| npm              |
| Operating System |

**Comment by csvan** [comment]
https://github.com/request/request/issues/3142
