### ISSUE TITLE
Please solve I don't really understands what is happening

### ISSUE THREAD

**Issue by Nelvinom** [request/request#3290]
### Simplest Example to Reproduce

```js
request({
  method: 'GET',
  url: 'http://example.com', // a public URL that we can hit to reproduce, if possible
  more: { 'options': 'here' }
},
```

### Your Environment

| software         | version
| ---------------- | -------
| request          |
| node             |
| npm              |
| Operating System |

**Comment by mkonikov** [comment]
Try unplugging and plugging back in.

**Comment by Nelvinom** [comment]
> Try unplugging and plugging back in.

Thank you
