### ISSUE TITLE
Installing Firebase Tools

### ISSUE THREAD

**Issue by harsh242** [request/request#3291]
I am trying to install firebase tools for deploying my site using 
npm install -g firebase-tools.
and I am getting a deprecated warning along with this link
https://github.com/request/request/issues/3142
Been stuck since 2 hours

**Comment by mkonikov** [comment]
A deprecated warning would not stop the install. The issue is likely elsewhere in your code or dependencies.

**Comment by harsh242** [comment]
Okay I figured it out

**Comment by nouman-cloud** [comment]
@harsh242 hey buddy how did u fix this error ???? i exp this same issue

**Comment by harsh242** [comment]
I had problems with my NPM, I tried reinstalling node but it did not work so I shifted to Yarn- Package Manager and it solved the issue. since then I am using the Yarn Package Manager.

**Comment by harsh242** [comment]
Request has been deprecated, alternative libraries are [here](https://github.com/request/request/issues/3143).
Preferred library is Axios

**Comment by nouman-cloud** [comment]
thanks buddy ❤️
