### ISSUE TITLE
issue in setting up environment for react native app

### ISSUE THREAD

**Issue by yuvi-dot-in** [request/request#3298]
C:\Users\ELCOT\Desktop\react\shopping native>npm install expo-cli --global
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
[..................] | fetchMetadata: WARN deprecated request@2.88.2: request has been deprecated, see https://github.c

**Comment by mkonikov** [comment]
For issues related to `expo-cli` file them here -> https://github.com/expo/expo-cli/issues

Either way, a warning message will not affect install.
