### ISSUE TITLE
Getting Error while trying to install protractor using command  'npm install -g protractor'

### ISSUE THREAD

**Issue by MeghanaGowdaM** [request/request#3299]
I tried to install Protractor using the command  'npm install -g protractor'

But i am getting the following Warning Error message

npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
C:\Users\machinename\AppData\Roaming\npm\protractor -> C:\Users\machinename\AppData\Roaming\npm\node_modules\protractor\bin\protractor
C:\Users\machinename\AppData\Roaming\npm\webdriver-manager -> C:\Users\machinename\AppData\Roaming\npm\node_modules\protractor\bin\webdriver-manager
+ protractor@5.4.4

**Comment by mkonikov** [comment]
That is a simple warning not an error.

You can always file an issue with the `protractor` repo if you'd like -> https://github.com/angular/protractor/issues
