### ISSUE TITLE
Does anyone know how to fix request has been deprecated message?

### ISSUE THREAD

**Issue by smavery1s** [request/request#3300]
After downloading node.js I've attempted to to globally install to my computers server. I typed
npm install -g less into terminal (MacOS) but received the following error deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
check permissions missing write access to /usr/local/lib/node_modules

Does anyone know how to fix this. I'm new to this. Any help is apprieciated.
Thanks in advanced.

**Comment by mkonikov** [comment]
Fix it by replacing `request` with another dependency of your choice.

More info here -> https://github.com/request/request/issues/3142
