### ISSUE TITLE
node js not working!! Error comes when npm install --global firebase-tools.

### ISSUE THREAD

**Issue by MrKhattak** [request/request#3304]
- 
Please look at this cmd and guide me what to do here
- 
![Capture](https://user-images.githubusercontent.com/56967180/81526194-65b1e900-9370-11ea-8836-83448d902a20.PNG)

### Simplest Example to Reproduce

```js
request({
  method: 'GET',
  url: 'http://example.com', // a public URL that we can hit to reproduce, if possible
  more: { 'options': 'here' }
},
```

### Your Environment

| software         | version
| ---------------- | -------
| request          |
| node             |
| npm              |
| Operating System |

**Comment by darkRaspberry** [comment]
Possible duplicate.
As Request is deprecated.
https://github.com/request/request/issues/3142
