### ISSUE TITLE
How to return the body of a request

### ISSUE THREAD

**Issue by chicofariasneto** [request/request#3307]
### Problem
I'm trying to make a request, and i would like to return a body to save in a const maybe. But when i return the value is undefined, i think i have to use async function, but i don't know how, can someone help me?

### Simplest Example to Reproduce

```js
const request = require('request');
request('http://www.google.com', function (error, response, body) {
    // i would like to return the body here
});
```

**Comment by JohanOu** [comment]
I have the same question，can you teach me？
