### ISSUE TITLE
Hostname/IP doesn't match certificates altnames

### ISSUE THREAD

**Issue by stephshelley** [request/request#331]
This request worked perfectly with earlier versions of node, but after updating to the latest it fails.

<pre><code>function testRequest() {
    var request = require('request');
    var url = "https://graph.facebook.com/zuck";
    request(url, function(error, response, body){
        if(error) { console.log(error); }
        else { console.log(body); };
    });

}</pre></code>

Now I'm getting the following error:

<b>[Error: Hostname/IP doesn't match certificate's altnames]</b>

Any clue how to fix this?

**Comment by jperry** [comment]
do you guys happen to know how to disable the hostname check on the node side?
