### ISSUE TITLE
I faced a problem on how to setup the Angular

### ISSUE THREAD

**Issue by Anoud-17** [request/request#3317]
anoudalqahtani@Anouds-MacBook-Pro Angular % npm install -g @angular/cli@1.6.5
npm WARN deprecated extract-text-webpack-plugin@3.0.2: Deprecated. Please use https://github.com/webpack-contrib/mini-css-extract-plugin
npm WARN deprecated chokidar@1.7.0: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated browserslist@2.11.3: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
npm WARN deprecated browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated request@2.81.0: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated hawk@3.1.3: This module moved to @hapi/hawk. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
npm WARN deprecated cryptiles@2.0.5: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated hoek@2.16.3: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated boom@2.10.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated sntp@1.0.9: This module moved to @hapi/sntp. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
/Users/anoudalqahtani/npm-global/bin/ng -> /Users/anoudalqahtani/npm-global/lib/node_modules/@angular/cli/bin/ng

> fsevents@1.2.13 install /Users/anoudalqahtani/npm-global/lib/node_modules/@angular/cli/node_modules/fsevents
> node install.js

  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
  SOLINK_MODULE(target) Release/fse.node

> node-sass@4.14.1 install /Users/anoudalqahtani/npm-global/lib/node_modules/@angular/cli/node_modules/node-sass
> node scripts/install.js

Cached binary found at /Users/anoudalqahtani/.npm/node-sass/4.14.1/darwin-x64-72_binding.node

> core-js@2.6.11 postinstall /Users/anoudalqahtani/npm-global/lib/node_modules/@angular/cli/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)

> ejs@2.7.4 postinstall /Users/anoudalqahtani/npm-global/lib/node_modules/@angular/cli/node_modules/ejs
> node ./postinstall.js

Thank you for installing EJS: built with the Jake JavaScript build tool (https://jakejs.com/)

> uglifyjs-webpack-plugin@0.4.6 postinstall /Users/anoudalqahtani/npm-global/lib/node_modules/@angular/cli/node_modules/webpack/node_modules/uglifyjs-webpack-plugin
> node lib/post_install.js

> node-sass@4.14.1 postinstall /Users/anoudalqahtani/npm-global/lib/node_modules/@angular/cli/node_modules/node-sass
> node scripts/build.js

Binary found at /Users/anoudalqahtani/npm-global/lib/node_modules/@angular/cli/node_modules/node-sass/vendor/darwin-x64-72/binding.node
Testing binary
Binary is fine
npm WARN notsup Unsupported engine for watchpack-chokidar2@2.0.0: wanted: {"node":"<8.10.0"} (current: {"node":"12.16.2","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: watchpack-chokidar2@2.0.0
npm WARN ajv-keywords@3.5.0 requires a peer of ajv@^6.9.1 but none is installed. You must install peer dependencies yourself.

+ @angular/cli@1.6.5
added 1156 packages from 673 contributors, removed 100 packages, updated 50 packages and moved 6 packages in 115.065s
anoudalqahtani@Anouds-MacBook-Pro Angular % npm install chokidar
+ chokidar@3.4.0
updated 1 package and audited 863 packages in 5.556s

33 packages are looking for funding
  run `npm fund` for details

found 6 vulnerabilities (5 moderate, 1 high)
  run `npm audit fix` to fix them, or `npm audit` for details
anoudalqahtani@Anouds-MacBook-Pro Angular % npm audit fix
up to date in 2.677s

33 packages are looking for funding
  run `npm fund` for details

fixed 0 of 6 vulnerabilities in 863 scanned packages
  6 vulnerabilities required manual review and could not be updated
------------

npm -v : 6.14.4
node -v : v12.16.2

**Comment by sarav1234** [comment]
You need to install chokidar3
npm i -D chokidar
