### ISSUE TITLE
when I try to install angular , I got below error. I have used so many commands to get rid out of this.

### ISSUE THREAD

**Issue by shilpaanthati6** [request/request#3318]
C:\Program Files\nodejs>npm install -g @angular/cli
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! code EEXIST
npm ERR! path C:\Users\XXXXX\AppData\Roaming\npm\node_modules\@angular\cli\bin\ng
npm ERR! dest C:\Users\XXXXX\AppData\Roaming\npm\ng
npm ERR! EEXIST: file already exists, cmd shim 'C:\Users\XXXXXX\AppData\Roaming\npm\node_modules\@angular\cli\bin\ng' -> 'C:\Users\XXXXXX\AppData\Roaming\npm\ng'
npm ERR! File exists: C:\Users\XXXXXX\AppData\Roaming\npm\ng
npm ERR! Remove the existing file and try again, or run npm
npm ERR! with --force to overwrite files recklessly.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\XXXXXX\AppData\Roaming\npm-cache\_logs\2020-06-26T18_27_50_041Z-debug.log

**Comment by quacksire** [comment]
Please read #3142, then refer to #3143
