### ISSUE TITLE
service.timings.socket > 60 seconds?

### ISSUE THREAD

**Issue by daviddean99** [request/request#3322]
I'm requesting an https site in a node v12.14.0 app via a proxy and intermittently seeing ~10% of requests taking more than 60 seconds to complete rather than the typical <500ms.

Looking at the debug logs, the majority of time is spent in service.timings.socket, e.g:

service.timings.dns = 0
service.timings.socket = 60,629.048
service.timings.lookup = 60,629.048
service.timings.connect = 60,629.048
service.timings.response = 60,717.822
service.timings.firstByte = 88.775
service.timings.download = 0.435

I assume this can't be a general network problem because the time spent waiting is in a socket allocation, i.e. nothing has yet been sent over the network because it hasn't yet been assigned a socket?

Or maybe I've misunderstood the timings and actually the library has sent a SYN but not received a response and therefore the socket isn't yet open? I'm not sure how the low-level networking works in a node.js app.

There is no explicit pool defined and maxSockets is not defined. I believe in node v12.14.0 the default value for agent.maxsockets is infinity?

numWorkers is set to 4.

Has anyone come across this before?

I don't know whether this is a node.js problem or something to do with the request library and how we have implemented it?

**Comment by GizmoMKD-zz** [comment]
i may have the same issue, 5-10% of the requests are ending with **ESOCKETTIMEDOUT** due to set read timeout in the client...

**Comment by sceik** [comment]
Hi @GizmoMKD @daviddean99,
i have the same identical problem.
Have you found out more? Or did you just change library? 

Thank you
