### ISSUE TITLE
when I try to install latest version of Angular (9) , I got below error.

### ISSUE THREAD

**Issue by shilpaanthati6** [request/request#3324]
I got check environment variables and added path,but of no use .Please help me out.

npm WARN deprecated request@2.88.2: request has been deprecated, see #3142
npm WARN rollback Rolling back safe-buffer@5.1.2 failed (this is probably harmless): EPERM: operation not permitted, lstat 'C:\Users\XXXXXX\AppData\Roaming\npm\node_modules@angular\cli\node_modules\string_decoder\node_modules'
npm ERR! code EEXIST
npm ERR! path C:\Users\XXXXXX\AppData\Roaming\npm\node_modules@angular\cli\bin\ng
npm ERR! dest C:\Users\XXXXXX\AppData\Roaming\npm\ng
npm ERR! EEXIST: file already exists, cmd shim 'C:\Users\XXXXXX\AppData\Roaming\npm\node_modules@angular\cli\bin\ng' -> 'C:\Users\XXXXX\AppData\Roaming\npm\ng'
npm ERR! File exists: C:\Users\XXXXXX\AppData\Roaming\npm\ng
npm ERR! Remove the existing file and try again, or run npm
npm ERR! with --force to overwrite files recklessly.

npm ERR! A complete log of this run can be found in:
npm ERR! C:\Users\XXXXXX\AppData\Roaming\npm-cache_logs\2020-07-09T17_28_14_402Z-debug.log

**Comment by Skareeg** [comment]
This does not have anything to do with Request. The warning for Request is a deprecation, a suggestion to not use it, as it is used by the Angular CLI. You will want to post this on the Github repo for Angular.

**Comment by shilpaanthati6** [comment]
If this a warning request ,but when i try( ng -v) to check angular got installed or not ,its showing me below error.

internal/modules/cjs/loader.js:969
  throw err;
  ^

Error: Cannot find module 'C:\Users\Sindhu\AppData\Roaming\npm\node_modules\@angular\cli\bin\ng'
[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:842:27)[39m
[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)[39m
[90m    at internal/main/run_main_module.js:17:47[39m {
  code: [32m'MODULE_NOT_FOUND'[39m,
  requireStack: []
}

**Comment by Skareeg** [comment]
You may want to open this issue on the Github project for the Angular project. This is the project for the Request library, not Angular. Problems with Angular cannot be fixed here.

**Comment by shilpaanthati6** [comment]
Hi Skareeg, 

I got cleared this issue from request library only . you should have mention below words  (You may want to open this issue on the Github project for the Angular project. This is the project for the Request library, not Angular. Problems with Angular cannot be fixed here.) from your first comment not after raising my question .

**Comment by shilpaanthati6** [comment]
issue got cleared.
