### ISSUE TITLE
Support of qsStringifyOptions.arrayFormat: 'comma'

### ISSUE THREAD

**Issue by dimafet001** [request/request#3326]
### Simplest Example to Reproduce
```js
request(url, {qs: {ids: [1,2,3]}, qsStringifyOptions: { arrayFormat: 'comma' }, encoding: null },
        function(err, response, body) {
            if (err) console.log(err)
      })
```

### Expected Behavior
It should call: ${url}?ids=1,2,3

### Current Behavior
It calls: ${url}?ids%5B0%5D=1&ids%5B1%5D=2&ids%5B2%5D=3', 
which stands for ${url}?ids[0]=1&ids[1]=2&ids[2]=3

### Possible Solution
Setting ids manually by joining a string

**Comment by shilpaanthati6** [comment]
I think o/p is displaying in the form of string . It should be converted in to array.
