### ISSUE TITLE
r

### ISSUE THREAD

**Issue by jaimenurbina** [request/request#3329]
### Simplest Example to Reproduce

```js
request({
  method: 'GET',
  url: 'http://example.com', // a public URL that we can hit to reproduce, if possible
  more: { 'options': 'here' }
},
```

### Your Environment

| software         | version
| ---------------- | -------
| request          |
| node             |
| npm              |
| Operating System |

**Comment by Tizioincognit0** [comment]
What is the sense of this empty issue?

**Comment by ghost** [comment]
> What is the sense of this empty issue?

@Tizioincognit0 maybe spam bots perhaps?
