### ISSUE TITLE
Vulnerability prototype pollution through har-validator

### ISSUE THREAD

**Issue by ebaynaud** [request/request#3330]
### Summary
  ✗ Prototype Pollution [High Severity][https://snyk.io/vuln/SNYK-JS-AJV-584908] in ajv@6.12.0
    introduced by request@2.88.2 > har-validator@5.1.3 > ajv@6.12.0
  This issue was fixed in versions: 6.12.3

### Solution
`yarn upgrade har-validator`
=> then new release 2.88.3 please

**Comment by SigurdMW** [comment]
👍

**Comment by skipper09** [comment]
👍

**Comment by ebaynaud** [comment]
Fixed in https://github.com/request/request/pull/3332

**Comment by TheJavaGuy** [comment]
This is [implemented](https://github.com/TheJavaGuy/request-master/pull/4) in [request-master](https://github.com/TheJavaGuy/request-master).
