### ISSUE TITLE
No info about 2.88.2 release

### ISSUE THREAD

**Issue by DanielRuf** [request/request#3333]
There is some 2.88.2 release on npmjs, but this is missing here. Also there is no tag with such a version.

Please provide additional information and push the relevant commits and tags.

![grafik](https://user-images.githubusercontent.com/827205/89506904-1abb3c80-d7cc-11ea-81d2-9da418b48edc.png)

**Comment by DanielRuf** [comment]
A `diff -u -r` between 2.88.0 and 2.88.2 (there is no 2.88.1) yields the following:

https://gist.github.com/DanielRuf/8f337f6a85f5e4def3a55d0d00f56ee9

**Comment by juanpicado** [comment]
Furthermore, the `package.json` still points to `"version": "2.88.1"`. But the latest was released to npmjs early this year`'2.88.2': '2020-02-11T16:35:36.122Z'` .

**Comment by DanielRuf** [comment]
I'm not sure but I guess 2.88.1 was released as 2.88.2 or they forgot to push all commits and tags.
