### ISSUE TITLE
not able to install NPM request...plz tell what to do?

### ISSUE THREAD

**Issue by ghost** [request/request#3335]
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm ERR! Unexpected end of JSON input while parsing near '...":{"fake":"~0.2.1","f'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\intel\AppData\Roaming\npm-cache\_logs\2020-08-14T08_42_42_604Z-debug.lo

**Comment by denkisikinoneko** [comment]
It's generally recommended you stay away from request as it's been deprecated.
[Here's why.](https://github.com/request/request/issues/3142)

May I ask, what are you trying to do here?

**Comment by TheJavaGuy** [comment]
@TavinSethi Your problem isn't request but **malformed package.json** file in your project! You're probably missing some symbol like `{` or `}`. This line in the output is the key to solve it `npm ERR! Unexpected end of JSON input while parsing near '...":{"fake":"~0.2.1","f'`.
