### ISSUE TITLE
npm WARN deprecated request@2.88.2: request has been deprecated

### ISSUE THREAD

**Issue by DeepakSingh92** [request/request#3337]
### Simplest Example to Reproduce

```js
request({
  method: 'GET',
  url: 'http://example.com', // a public URL that we can hit to reproduce, if possible
  more: { 'options': 'here' }
},
```

### Your Environment

| software         | version
| ---------------- | -------
| request          |
| node             |
| npm              |
| Operating System |

**Comment by MCSH** [comment]
Request *has been* deprecated. That's not an error.

https://github.com/request/request/issues/3142

**Comment by TheJavaGuy** [comment]
You can use https://github.com/TheJavaGuy/request-master
