### ISSUE TITLE
Timeout ignored for json request and streaming body

### ISSUE THREAD

**Issue by mochja** [request/request#3341]
### Summary

Expecting a request to timeout when JSON response could not be delivered before `timeout`, although timeout does not take place for streaming responses, with socket activity before `timeout`.

### Simplest Example to Reproduce

```js
var http = require('http');
var r = require('request');

const server = http.createServer(function(req, res) {
	res.writeHead(200, { 'Content-Type': 'text/plain' });
	res.write('"a')

	const delay = (end, cb) => setTimeout(() => {
		res.write('e')
		if (end) {
			res.end('"')
		}
		cb()
	}, 800)

	let n = 999999
	delay(false, function next() {
		n -= 1
		const end = n < 1
		delay(end, end ? () => (void 0) : next)
	})
});

server.listen('3000')

r({
	url: 'http://localhost:3000',
	json: true,
	timeout: 1000
}, (err, res) => {
	console.log(err, res)

	server.close()
})
```

### Expected Behavior

According to documentation, `timeout` option does not handle this case, but combined with `json` option set to `true`, I would expect timeout to apply here as well.

### Current Behavior

Such request can ran theoretically forever.

### Possible Solution

- Apply overall request timeout when `json` property is set to `true`.
- Introduce another timeout variable to handle response timeout. Including body.

### Context

I was just wondering if this would work as I was reading the documentation and thought this might be security issue.

### Your Environment

| software         | version
| ---------------- | -------
| request          | 2.88.2
| node             | 12.13.0
| npm              | 6.13.4
| Operating System | Mac OS 10.15.6 (19G2021)

**Comment by Verhov** [comment]
Have a similar issue https://github.com/bda-research/node-crawler/issues/371. Have you found any workaround?

**Comment by mike442144** [comment]
Hey, I read your code which keeps writing bytes to socket, in this case the socket connection is active and normally we cannot close or destroy an active connection that behavior is the same as working one. We close inactive one. Also this is not JSON-related issue, whatever document type you want what you do is downloading, and how can we close a downloading procedure. Finally, such request won't ran forever, you can always finish downloading some day unless the server would not like you to. And so, the content of the server is not what you want, add it to blacklist instead.
Feel free to discuss if any more question. hope it helps.
