### ISSUE TITLE
json: true with a JSON object causes ``str.replace is not a function`` error

### ISSUE THREAD

**Issue by erg** [request/request#3343]
```js
 const options = {
                method: 'POST',
                headers: { 'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8' },
                json: true,
                uri: this.config.peachPaymentsUrl + `v1/checkouts`,
                body: {
                    'authentication': {
                        'userId': this.config.peachPaymentsUsername,
                        'password': this.config.peachPaymentsPassword,
                        'entityId': this.config.peachPaymentsAdhocPaymentChannelId
                    },
                    'amount': mathHelper.getCentsAsRandsString(cents),
                    'currency': 'ZAR',
                    'description': 'Ekaya VIP',
                    'paymentType': 'DB' } //debit
            };

const response = await request(options);
```

Gives the error ``str.replace is not a function``, caused by the headers line ``json: true``.

What I did is to serialize the JSON object in the frontend instead of in the request library as in the following PR. However, the way the API reads, it's like I'm telling it that I'm passing a JSON object with ``json: true`` yet the backend will only accept a string, not JSON. This is unintuitive and wasting a lot of time for a lot of people.

PR that proposes a fix:
https://github.com/request/request/pull/3119/files

My fix looks something like this since str can be undefined or null. Your fix should take this into account.
```js
Querystring.prototype.rfc3986 = function (str) {
  if (!str) return ''
  if (typeof str !== 'string') str = JSON.stringify(str)
  return str.replace(/[!'()*]/g, function (c) {
    return '%' + c.charCodeAt(0).toString(16).toUpperCase()
  })
```

The issue was previously reported and never fixed. Please disable your stale-bot because it's closing real bug reports. Closing issues doesn't fix them.

Previous reports:
https://github.com/request/request/issues/1463
https://github.com/request/request-promise/issues/134

**Comment by luigimannoni** [comment]
Request is deprecated since 2019, there won't be any fixes any time soon or on the foreseeable future. Upgrade your request to other modern alternatives
