### ISSUE TITLE
Document how to enable logging

### ISSUE THREAD

**Issue by jimmyz** [request/request#335]
It appears that there is some logging built into the request library, but I can't figure out how to activate it. This would be very helpful for debugging HTTP calls.

**Comment by colllin** [comment]
@mikeal Is there an easy way to enable logging today?  I'd like to see a log of the final request URL, body, headers, etc., to make sure that I'm putting the information in the right places.  Then I could compare that information with the API docs I'm following and troubleshoot.  As of right now, I can't see exactly what's happening.

**Comment by tommymcdonald** [comment]
I'd like to request (ha) the same, I've been bothered by the lack of request logging lately and this would be a very much appreciated feature.
