### ISSUE TITLE
switch the Light on but not switch it off :(

### ISSUE THREAD

**Issue by LJ9210** [request/request#3353]
Hello,

yesterday i installed Hoobs on the Raspberry.All Shellys were also found but Shelly 1.0 which are set up to switch the Lights do not work correctly.I can switch the Light on but not switch it off via the App.

Everything works perfectly in the Shelly App

Shelly 2.5 in Shutter Mode work without problems.

is there a solution to this problem?

all Shellys are set up on the current update.

**Comment by lunibo** [comment]
Are you sure you are right here?

I think you're more likely to find a solution here: https://support.hoobs.org/
