### ISSUE TITLE
Error: write EPROTO 140329133451072...

### ISSUE THREAD

**Issue by termitek12** [request/request#3355]
It happened when I tried to access this page:
**https://pclab.pl/**

`Error: write EPROTO 140329133451072:error:1414D172:SSL routines:tls12_check_peer_sigalg:wrong signature type:../ssl/t1_lib.c:1145:`

I have no idea WTF is going one... and how to fix this.

Here is SO question - https://stackoverflow.com/questions/65447908/nodejs-request-problem-error-write-eproto
(if there is a fix i will update the question, if somebody ansver on SO, I will update the topic here)

**Comment by deen804** [comment]
adding this to the top solved this for me

`require("tls").DEFAULT_ECDH_CURVE = "auto";`

**Comment by termitek12** [comment]
@deencc4 yea thanks I found it here https://gist.github.com/laterbreh/5d7bdf03258152c95b8d#gistcomment-3628248
