### ISSUE TITLE
CORDOVA opted out of telemetry.

### ISSUE THREAD

**Issue by ZIKRYAZLAN** [request/request#3358]
### Simplest Example to Reproduce

```js
request({
  method: 'GET',
  url: 'http://example.com', // a public URL that we can hit to reproduce, if possible
  more: { 'options': 'here' }
},
```

### Your Environment

| software         | version
| ---------------- | -------
| request          |
| node             |
| npm              |
| Operating System |

**Comment by ZIKRYAZLAN** [comment]
To change this, run: cordova telemetry on.
10.0.0
HOW TO FIX THIS???

**Comment by luigimannoni** [comment]
You're in the wrong place, you need to raise an issue on Cordova's official bug tracker system: https://issues.apache.org/jira/projects/CB/issues/CB-11440?filter=allopenissues
