### ISSUE TITLE
Receiving data after abort

### ISSUE THREAD

**Issue by Grigore147** [request/request#336]
Hi,

I'm using the request as follows:

``` javascript
request({ url: url }).on('response', function(response) {
  // do some sync checks
  // if not ok then this.abort();
}).on('data', function(chunk) {
  // check chunk length ...
}).on('end', function() {
  //...
});
```

So if i aborted the request then the data event still emits once.

Is this expected thing? i can check the `this._aborted` on 'data' and ignore that chunk, but why that event is emitted?

**Comment by jacktuck** [comment]
Think this has regressed @mikeal 

If you have `gzip=true` you still get data emitted after an abort

request@2.81.0
node@v7.7.3

```
var request = require('request')
var debug = require('debug')

var req = request.get({
  url: 'https://google.com',
  gzip: true
})

var debug = require('debug')('test')

var ran = 0
req.on('data', (data) => {
  debug('GOT DATA')

  debug('IS ABORTED', req._aborted)

  if (++ran === 1) req.abort()
})

req.on('abort', () => debug('GOT ABORT!'))

req.on('end', () => debug('GOT END'))
```

>  test GOT DATA +0ms
  test IS ABORTED undefined +1ms
  test GOT ABORT! +1ms
  test GOT DATA +0ms
  test IS ABORTED true +0ms
  test GOT DATA +1ms
  test IS ABORTED true +0ms
  test GOT DATA +0ms
  test IS ABORTED true +0ms
  test GOT DATA +0ms
  test IS ABORTED true +0ms
  test GOT DATA +0ms
  test IS ABORTED true +0ms
  test GOT DATA +0ms
  test IS ABORTED true +0ms
  test GOT DATA +1ms
  test IS ABORTED true +0ms
  test GOT DATA +0ms
  test IS ABORTED true +0ms
  test GOT DATA +0ms
  test IS ABORTED true +0ms
  test GOT DATA +0ms
  test IS ABORTED true +0ms
  test GOT DATA +0ms
  test IS ABORTED true +0ms
  test GOT DATA +0ms
  test IS ABORTED true +0ms
  test GOT DATA +1ms
  test IS ABORTED true +0ms
  test GOT DATA +0ms
  test IS ABORTED true +0ms
  test GOT DATA +0ms
  test IS ABORTED true +0ms
  test GOT DATA +0ms
  test IS ABORTED true +0ms
  test GOT DATA +0ms
  test IS ABORTED true +0ms
  test GOT DATA +0ms
  test IS ABORTED true +0ms
  test GOT DATA +0ms
  test IS ABORTED true +0ms
  test GOT DATA +0ms
  test IS ABORTED true +0ms
  test GOT DATA +1ms
  test IS ABORTED true +0ms
  test GOT END +1ms

**Comment by jacktuck** [comment]
Is this expected?

**Comment by mikeal** [comment]
If it's only happening w/ gzip that's a different bug, but a valid one. Should be logged as a new bug though.

**Comment by jacktuck** [comment]
@mikeal Want me to make a new bug for it?

**Comment by mikeal** [comment]
@jacktuck yes please :)

**Comment by jacktuck** [comment]
No problem. Created it #2620
