### ISSUE TITLE
Deprecation warning on provider_lambdaHashingVersion will be equal to "20201221"

### ISSUE THREAD

**Issue by jeff-foo** [request/request#3362]
### Simplest Example to Reproduce

```js
request({
  method: 'GET',
  url: 'http://example.com', // a public URL that we can hit to reproduce, if possible
  more: { 'options': 'here' }
},
```

### Your Environment

| software         | version
| ---------------- | -------
| request          |
| node             |
| npm              |
| Operating System |

**Comment by jeff-foo** [comment]
I faced problem when deploy hello function and it displayed warning of provider LambdaHashingVersion will be equal to " 20201221" , What was that ???
Anyone can help me to solve this issue ?? Attached is the photo for your info.

![Screenshot - 23_1_2021 , 8_47_31 AM](https://user-images.githubusercontent.com/77233939/105563407-e7a83d80-5d58-11eb-9468-10c3c907ca72.png)

**Comment by luigimannoni** [comment]
You're in the wrong place, see the URL address after your error message which refers to a deprecation of a value on the serverless module.

Follow the link that your screen is outputting for more information

**Comment by jeff-foo** [comment]
Thank you
