### ISSUE TITLE
Where is the 2.88.2 version?

### ISSUE THREAD

**Issue by eugle** [request/request#3369]
Where is the 2.88.2 version?
How to solve this problem?

```
#16 2.367 npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
#16 2.664 npm WARN deprecated har-validator@5.1.5: this library is no longer supported
```

 There is only 2.88.1 in the tag list

![image](https://user-images.githubusercontent.com/24447931/111860418-3dc4e600-8982-11eb-915b-e268842ba213.png)

**Comment by benslv** [comment]
I think the solution to this problem is to switch to a different HTTP request client (like Fetch or Axios, perhaps)
