### ISSUE TITLE
JUST DAMN CLOSE ALL OF THE OPEN ISSUES

### ISSUE THREAD

**Issue by python-coding-404** [request/request#3415]
I know this is deprecated 
BUT JUST DAMN CLOSE ALL OF THE OPEN ISSUES
ITS SO DAMN EASY YOU CAN BUILD A BOT THAT CLOSES AND SEND DEPRECATION NOTICES TO OPEN ISSUSES
https://api.github.com/issues

**Comment by csvan** [comment]
Close your caps lock button.
