### ISSUE TITLE
Unable to capture "parse error"

### ISSUE THREAD

**Issue by pankajkgarg** [request/request#350]
I am trying to send a HEAD request to lot of urls, using request, and sometimes for some particular urls, the process dies, complaining of Unhandled 'error' events on  "Parse error".  The reported errror message is:

events.js:68
        throw arguments[1]; // Unhandled 'error' event

Error: Parse Error
    at Socket.socketOnData (http.js:1367:20)
    at TCP.onread (net.js:403:27)

To reproduce this error, look at  https://gist.github.com/3946623
I am using node version 0.8.12.

**Comment by bllevy** [comment]
Still getting this error with node v6.11.0.

**Comment by alesju** [comment]
Also getting this.

**Comment by Xunnamius** [comment]
Still getting this error randomly as of the latest node 8.x

**Comment by eicksl** [comment]
This seems to be happening in situations where the server doesn't support the request method and is not programmed to respond in any way, e.g. by sending a 405 Method Not Allowed response. If you're using a HEAD request, one possible workaround is to handle the error code ("HPE_INVALID_CONSTANT") by re-sending the request via GET.
