### ISSUE TITLE
add "charset=utf-8" to content-type "application/json"

### ISSUE THREAD

**Issue by thesmart** [request/request#383]
The `Request.prototype.json` function sets `Content-Type` headers to `application/json`.  utf-8 really should be the default imo, and this lead me to several hours of debugging hell to realize that the API I was working with rejects all but UTF-8 json.

I made these changes:

main.js, Line #803:

```
this.setHeader('content-type', 'application/json; charset=utf-8')
```

main.js, Line #807:

```
this.setHeader('content-type', 'application/json; charset=utf-8')
```

Is there anything wrong with this?  Any thoughts?

**Comment by xgqfrms-GitHub** [comment]
https://stackoverflow.com/questions/24528211/chrome-refuses-to-execute-an-ajax-script-due-to-wrong-mime-type


```sh
#  JSON

application/json

#  JSONP 

application/javascript
```

**Comment by ilatypov** [comment]
If the script HTML tag's charset attribute overrides the auto-detection and an extra URL parameter can manipulate a part of the response, then attackers can read the entire UTF-8 response by forcing the browser believe that they read a UTF-16 data.  http://blog.portswigger.net/2016/11/json-hijacking-for-modern-web.html

**Comment by sumit1317** [comment]
Hi,
I am using the following nodejs code generated via postman for one of my APIs, which is giving error as shown below. The api call is working fine from postman, but not from nodejs. 
There is an attachment of xml file in the request call.
Any help will be highly appreciated.

**Nodejs Code**
var fs = require("fs");
var request = require("request");
var options = { method: 'POST',
  url: 'https://uat.nlis.mla.com.au/soap/upload.aspx',
  headers: 
   { 'postman-token': 'cda8f580-50cc-0d76-08f3-61670fcf0b4b',
     'cache-control': 'no-cache',
     'content-type': 'multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW' },
  formData: 
   { '': 
      { value: 'fs.createReadStream("nlisMovement.xml")',
        options: { filename: 'nlisMovement.xml', contentType: null } } } };
request(options, function (error, response, body) {
  if (error) throw new Error(error);
  console.log(body);
});


**Error**
"<SOAP-ENV:Envelope xmlns:SOAP-ENV='http://schemas.xmlsoap.org/soap/envelope/'><SOAP-ENV:Body><SOAP-ENV:Fault><faultcode>SOAP-ENV:Client</faultcode><faultstring>Content-Type should be set to text/xml</faultstring><detail></detail></SOAP-ENV:Fault></SOAP-ENV:Body></SOAP-ENV:Envelope>"
