### ISSUE TITLE
Requesting a pictures results in a 0 byte file.

### ISSUE THREAD

**Issue by sbrinkmann** [request/request#405]
I tried to download a file with the following code snippet. The code snippet themselfes is the first example on the project landing page.

var request = require('request');
var fs = require('fs');

var staticUrl = "http://farm9.staticflickr.com/8358/8337105913_b41013426f_s.jpg";
request(staticUrl).pipe(fs.createWriteStream("/path/to/my/file.jpg"));

Even though the the static file is available on the url defined above, the created file on my harddisk has a filzesize of 0 bytes.

I run Ubuntu 12.04LTS and Node.JS v0.6.12

**Comment by jasan-s** [comment]
@joshtwist  can you share code of how you limited concurrent requests. I'm also getting empty image files
