### ISSUE TITLE
Need a way to not escape querystrings

### ISSUE THREAD

**Issue by blakevanlan** [request/request#409]
I am using the Bing Search REST API and the querystring parameters for "top" and "skip" are actually "$top" and "$skip". This causes a problem when using this library because all of the query strings are escaped prior to the request. Bing, of course, doesn't understand the parameters when they are escaped (when "$top" -> "%24top"). 

Pretty lame that Bing requires this but I think it could be a useful feature.

**Comment by jonathanwiesel** [comment]
I have a similar case, I'm doing a request like the following:

```js
var request = require('request');
request('http://test.com?name=mé')
```

That query parameter `mé` seems to be escaped I need to send the unescaped version. Is there a way?

**Comment by jonathanwiesel** [comment]
I've also tried the following but no luck:

```js
var request = require('request');
var url = require('url');

var hitMe = url.parse('http://test.com?name=mé');
request({uri: hitMe})
```

**Comment by jonathanwiesel** [comment]
Never mind, I finally found a way:

```js
var request = require('request');

var options = {
		uri : '/path',
		baseUrl: 'http://test.com',
		qs : { name : 'mé'} ,
        useQuerystring : true,
		qsStringifyOptions : {
			options: {
				encodeURIComponent : function (obj) {

	                var queryString = '';

	                for (var key in obj) {
		                queryString += '&' + key + '=' + obj[key];			
	                }

	                return queryString;
                }
			}
		}
};

request(options)
```

**Comment by simov** [comment]
Thanks for sharing your solution, @jonathanwiesel :+1:
