### ISSUE TITLE
Header key 'host' should be 'Host'

### ISSUE THREAD

**Issue by durango** [request/request#411]
Some servers, such as FedEx's API servers, actually care about this case sensitivity.

**Comment by obender** [comment]
Hi, 
We have same issue vs the content-length, Apache Tomcat HTTPD lib refses to accept the low capital header... content-length its' allowing  in Content-length only...

**Comment by mikeal** [comment]
The standard in Node.js is lowercase. In fact, core http automatically lowers headers in the server.

Apache Tomcat HTTPD is violating the HTTP spec which explicitly states that headers are caseless. We do a lot of work in `request` to ensure we are caseless, I even wrote this entire dependency just to deal with it https://www.npmjs.com/package/caseless :)

**Comment by noranana** [comment]
Apache Tomcat HTTPD is violating the HTTP spec????
