### ISSUE TITLE
Error: DEPTH_ZERO_SELF_SIGNED_CERT

### ISSUE THREAD

**Issue by maiko-rocha** [request/request#418]
I'm using self-signed test certificates in my apache2 server and when I call request I get the following error:

> Error: DEPTH_ZERO_SELF_SIGNED_CERT

I'm using the following code below to test it. Notice that I'm also using **[needle](https://github.com/tomas/needle)** and it works with the **rejectUnauthorized=true** option. I could not find an equivalent on **request** (I've tried **strictSSL=false** but I guess that's the default). I couldn't find any other samples related do the problem either.

``` javascript
var request = require('request'),
    needle = require('needle');

request('https://127.0.0.1', function (error, response, body) {
  if (!error && response.statusCode == 200) {
    console.log("REQUEST:"+body);
  } else {
    console.error("REQUEST: "+error)
  }
});

needle.get('https://127.0.0.1',{rejectUnauthorized:false},function (error, response, body) {
  if (!error && response.statusCode == 200) {
    console.log("NEEDLE:"+body);
  }
});
```

**Comment by jandrieu** [comment]
@seanstrom I'm still getting this error when trying to use self-signed certs. 

Thing is, rejectUnauthorized: false turns off all verification, right? Because it works even if I don't provide a PEM or key or list of accepable certs. I need to provide a cert (or key) and have the request engine support actually check the cert list.

**Comment by nylen** [comment]
Have a look at our HTTPS tests for an example of how to do this: https://github.com/request/request/blob/master/tests/test-https.js

**Comment by jandrieu** [comment]
Thanks, Nylen. That test helped clear up what we were doing wrong. We were using self-signed certs, rather than first creating a self-signed CA and then using that CA to sign the server cert. That's what I thought we were doing, but we weren't.

**Comment by Dzenly** [comment]
For those who wish to understand a principle.

https://nodejs.org/dist/v0.12.9/docs/api/tls.html#tls_tls_connect_options_callback

//process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";
var tls = require('tls');
var fs = require('fs');
var options = {
	host: 'localhost',
	ca: fs.readFileSync('trustedCert.pem'), // Certificate of the server which we trusted to.
	strictSSL: true
};

var cleartextStream = tls.connect(8000, options, function() {
	console.log('client connected',
		cleartextStream.authorized ? 'authorized' : 'unauthorized');
	process.stdin.pipe(cleartextStream);
	process.stdin.resume();
});

**Comment by AliShire** [comment]
really it sound all your problems is your client system has no SSL certificate configuration 
first configure your systems openSsl ands then add your request whether is get or post to process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0"; it would work inshaa Allah

**Comment by andig** [comment]
I'm back with this problem. I've got self-signed certificates working when doing `GET` requests. I'm stuck however with `POST` requests. All available options have already been set:

**request**

    { url: 'https://.../data.lua',
      rejectUnauthorized: false,
      strictSSL: false,
      method: 'POST',
      form:
       { sid: 'xxx',
         xhr: 1,
         no_sidrenew: '',
         device: '17',
         oldpage: '/net/home_auto_hkr_edit.lua',
         back_to_page: '/net/network.lua' } }

**process.env**

    { ...
      NODE_TLS_REJECT_UNAUTHORIZED: '0' }

Any idea what might be wrong here?

This is on node 4.4.5.

**Comment by saurabh1gupta** [comment]
Hi there,

I'm facing the similar issue but only in "POST" method while "GET" is working fine. Here are the detailed information:

**Test Code:**

`
var frisby = require('frisby');
process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";

var CONF = process.env['CONF'];
var config = require('../config/' + CONF);
var data = require('../tests_data/batch_data.json');

frisby.globalSetup({
  request: {
    strictSSL: false,
    rejectUnauthorized: false,
    headers: {'Authorization': 'token'},
    inspectOnFailure: true 
  }
});

frisby.create('Test#1: Sunny Day scenario')
  .post(config.api_url + data.api_endpoint, data.test_strace, {rejectUnauthorized: false},  {json: true})
  .inspectHeaders()
  .inspectRequest()
  .inspectJSON()
  .expectJSON(data.batch_test_response_1)
.toss();
`

**Execution Error:**
Error-1
`   Message:
     Error: Error parsing JSON string: Unexpected token D
	Given: Destination URL may be down or URL is invalid, Error: ESOCKETTIMEDOUT
   Stacktrace:
     Error: Error parsing JSON string: Unexpected token D
	Given: Destination URL may be down or URL is invalid, Error: ESOCKETTIMEDOUT
    at _jsonParse (/usr/src/app/frisby_api/node_modules/frisby/lib/frisby.js:1219:11)
    at null.<anonymous> (/usr/src/app/frisby_api/node_modules/frisby/lib/frisby.js:650:20)
    at null.<anonymous> (/usr/src/app/frisby_api/node_modules/frisby/lib/frisby.js:1074:43)
    at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)`

Error-2

`   Message:
     TypeError: Cannot read property 'headers' of undefined
   Stacktrace:
     TypeError: Cannot read property 'headers' of undefined
    at Frisby.<anonymous> (/usr/src/app/frisby_api/node_modules/frisby/lib/frisby.js:894:20)
    at Frisby.<anonymous> (/usr/src/app/frisby_api/node_modules/frisby/lib/frisby.js:940:8)
    at null.<anonymous> (/usr/src/app/frisby_api/node_modules/frisby/lib/frisby.js:1112:18)
    at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)`

What should be updated here to fix these issues?

Thanks

**Comment by mateomarin** [comment]
add this and it should solve it:

https.globalAgent.options.rejectUnauthorized = false;

**Comment by leetrout** [comment]
For other internet travelers: if you have the CA cert then set [`NODE_EXTRA_CA_CERTS`](https://nodejs.org/api/cli.html#node_extra_ca_certsfile)
