### ISSUE TITLE
robots.txt Handling

### ISSUE THREAD

**Issue by reezer** [request/request#419]
I am not sure whether it is an the scope of this project, but I can imagine that for many use cases of this libraries (like mine) out of the box robots.txt support would be something really nice to have.

**Comment by raeesaa** [comment]
Hi @mmalecki . The requests to the sites having robots.txt are returning 500 or 429 error in my case. Calling the same URL from browser opens webpage perfectly fine and therefore I guess such sites are considering HTTP requests made using `request` module as bots and blocking the access. Is there any way we can access content of such URLs?

@reezer was also addressing the same issue I guess.

Thanks

**Comment by simov** [comment]
@raeesaa the easiest way to find out is to inspect what headers the browser is sending when making the request, and then set them through the request's options.

**Comment by pedrocatre** [comment]
I was checking two URLs that were sending 429 status code when using the request library but not on the browser and added 'User-Agent': 'request' header and it started working. Thanks for the tip @simov!
