### ISSUE TITLE
How to know if JSON auto-parsing failed?

### ISSUE THREAD

**Issue by aseemk** [request/request#440]
Currently, request try-catches its JSON parsing:

https://github.com/mikeal/request/blob/v2.33.1/request.js#L879-L883

``` js
          if (self._json) {
            try {
              response.body = JSON.parse(response.body)
            } catch (e) {}
          }
```

As you mention in https://github.com/mikeal/request/issues/99#issuecomment-14016174, this was intentional, and I understand why.

But it has one problem: I as a caller have no way of knowing whether the JSON has been successfully parsed or not. Specifically, if the response is malformed JSON, `response.body` remains a string, but if it's valid JSON representing a string, `response.body` is also a string.

This isn't just a theoretical problem; I ran into this recently when an API server started returning malformed JSON (with a 200 error code, because it's a streaming API) due to an out-of-memory error.

What do you suggest? Thanks again for the help!

(Edited to fix and pin link.)

**Comment by curiouslybrown** [comment]
I've experimented with a lot of different approaches to this and concluded:

The only fool proof way to implement this would be to pass in an expected JSON schema. If the response doesn't validate against the schema, then error out.

**Comment by bblack** [comment]
> i think we might just want to consider it an error.

this seems like the obvious solution. if i open such a pull request, will it be accepted?
