### ISSUE TITLE
Authorization header shouldn't be forwarded across redirects

### ISSUE THREAD

**Issue by jbt** [request/request#450]
Authorization headers are getting preserved even after redirects to a different server, which breaks if the target of the redirect isn't expecting Authorization (e.g. Amazon S3 throws a 400 error).

Ideally the behaviour would be the same as in curl or requesting the URL in a browser

For example:

``` js
var app = require('express')();

app.get('*', function(req, res){
  res.redirect('http://aws-lightbox.s3.amazonaws.com/source/jquery.fancybox.css');
});

app.listen(5678)

require('request')('http://foo:bar@localhost:5678/', function(err,resp){
  console.log('Request', resp.statusCode);
});

require('child_process').exec('curl -L -w "%{http_code}" -o /dev/null http://foo:bar@localhost:5678/', function(err, resp){
  console.log('Curl', resp)
});
```

Outputs:

```
Request 400
Curl 200
```

This is currently breaking NPM with links to GitHub private repo tarballs using basic auth, as they redirect to S3

**Comment by mikofski** [comment]
This is still an issue for me, on Windows 7 and Ubuntu 14.04 LTS:

    $ curl -i -L -k -H "Authorization: token <token>" -H "Accept: application/octet-stream" https://api.github.com/repos/<user>/<repo>/releases/assets/<id>
    HTTP/1.1 302 Found
    Server: GitHub.com
    Date: Wed, 09 Sep 2015 20:11:17 GMT
    Content-Type: text/html;charset=utf-8
    Content-Length: 0
    Status: 302 Found
    X-RateLimit-Limit: 5000
    X-RateLimit-Remaining: 4995
    X-RateLimit-Reset: 1441832779
    location: https://s3.amazonaws.com/github-cloud/releases/<awsid>/<file-hash>?response-content-disposition=attachment; filename=<filename>&response-content-type=application/octet-stream&AWSAccessKeyId=<access-key-id>&Expires=<expires>&Signature=<signature>=
    X-XSS-Protection: 1; mode=block
    X-Frame-Options: deny
    Content-Security-Policy: default-src 'none'
    Access-Control-Allow-Credentials: true
    Access-Control-Expose-Headers: ETag, Link, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval
    Access-Control-Allow-Origin: *
    X-GitHub-Request-Id: <github:request:id>
    Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
    X-Content-Type-Options: nosniff
    Vary: Accept-Encoding
    X-Served-By: <served-by>

    HTTP/1.1 400 Bad Request
    x-amz-request-id: <amz-request-id>
    x-amz-id-2: <amz-id-2/stuff>
    Content-Type: application/xml
    Transfer-Encoding: chunked
    Date: Wed, 09 Sep 2015 20:11:18 GMT
    Connection: close
    Server: AmazonS3

    <?xml version="1.0" encoding="UTF-8"?>
    <Error>
      <Code>InvalidArgument</Code>
      <Message>
        Only one auth mechanism allowed;
        only the X-Amz-Algorithm query parameter,
        Signature query string parameter or the Authorization header should be specified
      </Message>
      <ArgumentName>Authorization</ArgumentName>
      <ArgumentValue>token </ArgumentValue>
      <RequestId></RequestId>
      <HostId></HostId>
    </Error>

what's the trick? do I have to use `wget`?

**Comment by mikofski** [comment]
Ah, but it does work in python requests. interesting.

    >>> import requests
    >>> headers = {"Authorization": "token <token>",
                   "Accept": "application/octet-stream"}
    >>> url = "https://api.github.com/repos/<user>/<repo>/releases/assets/<id>"
    >>> s = requests.get(url=url, headers=headers)
    >>> with open('<filename>', 'wb') as fp:
        fp.write(s.content)

**Comment by simov** [comment]
@mikofski a better approach would be to create a new issue, and reference all other issues there instead of spamming the same content in all threads. GitHub puts back reference links to them.

I removed your posts in the other 3 issues.

**Comment by mikofski** [comment]
@simov I am **very sorry**. Thanks for removing the other 3 issues. Should I open a new issue since this one is closed?

**Comment by simov** [comment]
Yep, open another one, and link to the other issue from there.
