### ISSUE TITLE
How to use" secureProtocol: 'SSLv3_method'"

### ISSUE THREAD

**Issue by umutm** [request/request#530]
For some HTTPS requests, I'm getting an error:

---

7068:error:140773F2:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert unexpected message:openssl\ssl\s23_clnt.c:658:

---

which is told to be fixed by using "secureProtocol: 'SSLv3_method'" option in the request (for node https) (via: http://stackoverflow.com/questions/11091974/ssl-error-in-nodejs).

Is it possible to use that option in node-request or customize which SSL connection version to use?

**Comment by calidion** [comment]
what is the replacement for SSLv3_method now?

**Comment by umutm** [comment]
Per request, you can define:
secureProtocol: "TLSv1_method"

or just not define it and, if I'm not wrong, it is again TLS.

**Comment by calidion** [comment]
just tried 'TLSv1_method', and it works.
thanks.
