### ISSUE TITLE
Incorrect charset at save to file

### ISSUE THREAD

**Issue by magnum-ferox** [request/request#546]
I want to save a page for later processing. Problem occurs if site in Cyrillic charset (windows-1251).

This code save html, but all cyrillic symbols transformed to �����

``` js
request('http://www.vesti.ru/', function(error, response, content) {
    if(!error && response.statusCode == 200) {
        fs.createWriteStream('D:/tools/#scripts/bgi.html').write(content);
    }
});
```

if set encoding {url: 'http://www.vesti.ru/', encoding: 'ascii'}
symbols transormed to trash: Dk lnoednb h qjsrepnb bbekh qoevh`k|m{e op`b`

OR write(content, 'ascii'); — also trash

however, next code saves with no errors!
request('http://www.vesti.ru/').pipe(fs.createWriteStream('D:/tools/#scripts/bgi.html'));

**Comment by TrejGun** [comment]
this is still an issue(

**Comment by munkk** [comment]
...

**Comment by iyangsheng** [comment]
@magnum-ferox Is it solved now?

**Comment by iyangsheng** [comment]
@munkk Is it solved now?

**Comment by munkk** [comment]
@iyangsheng no, it's still there. 
i've read just the other week that this package could help, but i didn't try it yet https://github.com/tomas/needle
