### ISSUE TITLE
oAuth querystring params with square-bracket characters

### ISSUE THREAD

**Issue by trevorwilliams** [request/request#553]
**Background:** Magento REST APIs use querystring parameters that have square brackets.

**Problem:** Unfortunately, Request throws "[TypeError: Cannot convert object to primitive value]" when using params with square bracket characters.

**Example:**

var queryString = {};
queryString['filter[1][attribute]'] = 'entity_id';
queryString['filter[1][neq]'] = '2';

request.get({
        url: configHelper.magento.urlRootApi + 'products',
        qs: queryString,
        oauth: oauth,
        json: true
    }, function(e, r, body) {

**Notes:**
1. These Magento APIs themselves have been tested and work on the same request using the Chrome Advanced REST client.
2. I've tried using encodeURIComponent on the queryString params before they go to Request, but I believe Request ends up double-encoding them.

**Comment by psyklopz** [comment]
I know I'm digging up the dead here, but I ran into the same issue.  I ended up forking the request project and hacking in @trevorwilliams' suggestion.  For those who may come after, you can see that commit here: https://github.com/psyklopz/request/commit/9abf4aaef2febe3f2da027c86ab4e7fe22ec170e

**Comment by psyklopz** [comment]
Perhaps some day it will make sense to correct how `qs` is collapsing filters down.  They end up being objects, which give "Object" when printed to a string.  So I can't imagine this ever works with any service using square brackets in the parameter list AND trying to generate an OAuth signature...

**Comment by mohantorrez** [comment]
@mikeal This issue still exist. Will this pull request https://github.com/psyklopz/request/commit/9abf4aaef2febe3f2da027c86ab4e7fe22ec170e
get merged?
