### ISSUE TITLE
Set 'total time' for request, like cURL's CURLINFO_TOTAL_TIME

### ISSUE THREAD

**Issue by geerlingguy** [request/request#557]
One feature that I'd really like to see is something like (in PHP) `curl_getinfo($ch, CURLINFO_TOTAL_TIME);`

This is an easy way to check how long the request took, so I can track latency/total time for a particular request.

Right now, I set a 'time' variable before making the request, and then calculate latency based on the amount of time that passed between the start time and the time the request completes.

However, this time value is not super accurate, especially if I perform many asynchronous requests.

**Comment by seanstrom** [comment]
We recently added this feature, check out the docs for the `time` property

**Comment by geerlingguy** [comment]
Nice! Thanks @seanstrom.
