### ISSUE TITLE
Please remove the default "global cookie jar" feature

### ISSUE THREAD

**Issue by dionoid** [request/request#571]
I love the Request package for Node.js, but it's default "global cookie jar" feature almost drove me insane. When using the Request package inside my node.js webserver (for making authenticated webservice-calls), globally storing cookies turned out to be a very bad idea because every internal request was sharing the same authentication-cookies.

Please turn off the "global cookie jar" feature by default, so developers are aware of the implications when they enable this feature. The jar-option in Request already works perfectly for conscious cookie-sharing between multiple requests.

**Comment by Royalgamer06** [comment]
Here is an idea:
```
const request = require("request");
const httprequest = {
    private: request.defaults({
        jar: false
    }),
    public: request.defaults({
        jar: true
    })
};
```
Usage:
```
httprequest.public.get("https://example.com/login", (err, res, data) => console.log(data.includes("Already logged in"))); // true, if logged in before
httprequest.private.get("https://example.com/login", (err, res, data) => console.log(data.includes("Already logged in"))); // false (always)
```
It's a bit like your browser's incognito/inprivate mode.
