### ISSUE TITLE
v2.25.1: globalPool not used when maxSockets are set.

### ISSUE THREAD

**Issue by nemtsov** [request/request#617]
If the `pool` is provided in v2.25.1, due to the added check in de8508e, the globalPool will not be used, unlike in the previous versions.

Here's a test:

```
function send(i, pool) {
  console.time(i)
  require('request')({
      url: 'http://localhost:3000/?delay=1000'
    , pool: pool
  }, function (err, res, body) {
    console.timeEnd(i)
  })
}

for (var pool, i = 0; i < 10; i++) {
  //pool = {maxSockets: 5}
  send(i, pool)
}
```

Due to the global pool, the requests will be chunked into two groups (of 5, the default pool size) 1000ms each; as expected.

```
0: 1098ms
1: 1018ms
2: 1019ms
3: 1020ms
4: 1019ms
5: 2019ms
6: 2021ms
7: 2022ms
8: 2022ms
9: 2023ms
```

If you uncomment the line with the `maxSockets`, I expect to the exactly the same behavior, but instead get:

```
0: 1096ms
1: 1019ms
2: 1020ms
3: 1020ms
4: 1021ms
5: 1021ms
6: 1022ms
7: 1021ms
8: 1022ms
9: 1022ms
```

I'd submit this as a PR, undoing de8508e, but I don't understand the motivation behind that commit enough to recommend that as a solution.

**Comment by tejasmanohar** [comment]
did this happen? curious to see before/after
