### ISSUE TITLE
How to handle ETIMEDOUT?

### ISSUE THREAD

**Issue by amitava82** [request/request#636]
If requested server is unreachable then node process dies with `Error: connect ETIMEDOUT`. How to handle the exception? Tried wrapping with `try{}catch()` but that did not work.

```
try{
  request.get('http://someserverthatisdown').pipe(res);
}catch(e){
  res.send();
}
```

**Comment by kevinburkeshyp** [comment]
might be crazy, but if I am reading this correctly, this means you have to catch errors from a request in two different places? once in the `err` callback, and then once by calling `.on('error')` and handling the emitted event.

**Comment by kevinburkeshyp** [comment]
looking in the tests, it seems like either method will catch timeouts..

**Comment by kazaff** [comment]
@amitava82 i do not understand, why use two different way to catch the err?  can you explain the point of your  solution. thanks

**Comment by amitava82** [comment]
@kazaff it's been over 3 years, I don't recall the details 😕

**Comment by kazaff** [comment]
@amitava82 fine, thanks for your reply~~

**Comment by iibarbari** [comment]
@amitava82 You can try to run killall node from terminal
