### ISSUE TITLE
Simplified Stream/Pipe Error Handling

### ISSUE THREAD

**Issue by protometa** [request/request#647]
Request is super simple to use, but it's not so simple to handle errors, especially when piping.

Normally error handling with pipes is very straightforward:

``` javascript
fs.createReadStream( 'file1.txt' )
.pipe( fs.createWriteStream( 'file2.txt' ))
.on( 'error', handleErr ) // <- all read/write/stream errors can be caught here
.on( 'close', proceed );
```

With request, that doesn't seem to be the case:

``` javascript
request( 'http://google.com/doodle.png' )
.pipe( fs.createWriteStream('doodle.png'))
.on( 'error', handleErr ) // <- many errors don't make it here
.on( 'close', proceed );
```

Callbacks are not necessary when producing streams as it's mixing two different asynchronous conventions, though the presence of a callback could indicate which one you intend to use.

Could stream events be used when a callback is not provided, or am I crazy?

**Comment by jtlapp** [comment]
I am also trying to figure out how to deal with 404 while piping. Checking the status code before setting up the pipe seems like the solution, but [these folks in SO](http://stackoverflow.com/questions/7222982/node-request-how-to-determine-if-an-error-occurred-during-the-request) (see the last two answers) report that if you do that, the first few bytes of data may not end up in the stream.

I'm hitting web servers that return 404 along with a response body, so I'm writing files that I then have to delete. I'm trying to be resource efficient.

I'm not yet aware of a reliable way to do this that is also efficient.

**Comment by jtlapp** [comment]
And I've already found a solution. I call HEAD on the URL in advance of the GET. This is a bit inefficient, but I have to do this anyway to keep from initiating downloads of files that are too big.

**Comment by jtlapp** [comment]
It looks you can have the best of all worlds using `.pause()` and `.resume()`:

http://stackoverflow.com/a/26163128/650894

**Comment by maicss** [comment]
https://stackoverflow.com/a/14972828/5061231

cannot use `await` on this operation?

```
const request = require('request-promise')
(async() => {
  await r = request('xxx.jpg')
  r.pipe(fs.createWriteStream('./xxx.jpg'))
  //  error : r.pipe is not a function
})()
```

**Comment by gentunian** [comment]
All this workarounds breaks the easy of use and read of streams. I don't understand why not 4xx and 5xx responses aren't treated as errors[0]. `request` should be heavily tightened to HTTP response standards as that is what they say it is: an HTTP client.

[0]: https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html (10.4 Client Error 4xx and 10.5 Server Error 5xx)

**Comment by loopmode** [comment]
Totally agree with @gentunian. It feels just wrong to have an `on('error')` which doesn't handle the errors, and e.g an `on('response')` to actually handle the errors.

Plus, for somebody just coming to this library, additional questions arise and cofuse me like "so..do I need to abort or cancel when I detect an error via statusCode, or is that already done?" etc

I'm coming from `axios`, which I happily used for years but found to have a specific shortcoming that is handled well by `request`, but there, at leat the error callback was reliable...

**Comment by Ncifra** [comment]
So according to the responses, to handle every error this should be the code:

```javascript
r.on("response", function (response) {
                                            if (response.statusCode === 200) {
                                                r.pipe(res)
                                                    .on("error", function (err) {
                                                       //error handling here
                                                    });
                                                r.resume();
                                            } else {
                                               //status "error" handling here
                                            }
                                        })
                                            .on("error", function (err) {
                                                       //error handling here
                                            })
```

?
