### ISSUE TITLE
Running request(...) with interval eventually causes ETIMEDOUT and EADDRINFO

### ISSUE THREAD

**Issue by MattiNieminen** [request/request#697]
I have an application which uses Request to fetch certain URIs at 10-20 second interval. Everything works perfectly for a few hours, but then requests start to fail saying either getaddrinfo EADDRINFO or ETIMEDOUT. After restarting the app everything works fine for few hours.

Could be problem in Node.js core according to this: http://stackoverflow.com/questions/15011239/node-js-app-begins-timing-out-etimedout-when-http-connecting-to-other-sites-af

Are there any workarounds? I tried setting require('http').globalAgent.maxSockets = 10000; in the beginning of my code, but it does not help or something rewrites it later on.

**Comment by vinnitu** [comment]
I have same touble but with other error combination
errno: 'ECONNRESET', syscall: 'read'
errno: 'ETIMEDOUT', syscall: 'connect'

What do you think about friends?
