### ISSUE TITLE
Large Junk of response body 'HPE_INVALID_CHUNK_SIZE' error

### ISSUE THREAD

**Issue by hustcer** [request/request#706]
I got a {"bytesParsed":44083,"code":"HPE_INVALID_CHUNK_SIZE"} error when request for large junk of data:
Try the following url:
http://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20yahoo.finance.industry%20where%20id%20in%20(select%20industry.id%20from%20yahoo.finance.sectors)&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys&callback=

and my code is:

``` javascript
exports.querySymbolList = function(callback){

    var qs = {};
    qs.format      = 'json';
    qs.callback    = '';
    qs.diagnostics = false;
    qs.q           = 'select * from yahoo.finance.industry where id in (select industry.id from yahoo.finance.sectors)';
    qs.env         = 'store://datatables.org/alltableswithkeys';

    request({url:conf.yahooYqlApi, qs:qs, json:true, timeout:conf.timeout}, function (e, r, dt) {
        if(e){ callback(e); return; }

        // w.info('Symbol List:'.em);
        // w.info(JSON.stringify(dt));

        var dir = conf.dataPath + 'yahoo/';
        fs.writeFile(dir + 'symbols.json', JSON.stringify(dt, null, 2), function (err) {
            if(err){ callback(err); return; }
            w.info(dir + 'symbols.json saved successfully!');
            callback(null);
        });
    });

}
```

Using:
  yahooYqlApi    : 'http://query.yahooapis.com/v1/public/yql'

It worked sometimes, but 'HPE_INVALID_CHUNK_SIZE' error occured quite often, I'm not quite sure whether it's a bug or not.

**Comment by jrgleason** [comment]
I am having this issue as well, how was it solved?

**Comment by paulrutter** [comment]
Amen to that:  how was this issue solved?
Still having the same issue with several external services like MailChimp and SailThru.
