### ISSUE TITLE
UNABLE_TO_VERIFY_LEAF_SIGNATURE

### ISSUE THREAD

**Issue by ralyodio** [request/request#722]
I'm seeing this in my logs, it appears to be an error with request, but I'm not sure why. All the other https queries I make work fine (different apis than this one).

```
https://api.bitfinex.com/v1//ticker/btcusd [Error: UNABLE_TO_VERIFY_LEAF_SIGNATURE]
```

When I make the request with curl, I get an error unless I pass it -ssl3 which I suspect is related.

**Comment by KamyarGhajar** [comment]
I have my own CA in a private network and I don't want to disable strictSSL option but I get this error, how can I fix this to trust my CA and my CA only.
