### ISSUE TITLE
Reloading Cookies

### ISSUE THREAD

**Issue by wishmedia** [request/request#760]
Is it possible to reload an entire cookie object in the event of the server going down? 

I can see the Object { store: { idx: { //Cookie } }; but If I try to use the object instead of loading it with request.jar(); it gives me: { store: { idx: { [Object] } } }

**Comment by Ratnesh-Github** [comment]
Hi, I am trying to do this ? Please tell me where am I wrong
j = request.jar();
request.get( jar : j ...);  // request call using j as cookie jar 
var k = JSON.stringify(j);  // storing j for storing in db. 
var kJar = JSON.parse(j, function(key, value){
   //converting date strings to objects. 
});

However when I use kJar now for making request, my session is lost. What should I done in this situation.

**Comment by icodeforlove** [comment]
i'm not sure if this is frowned upon but you can do this

```
var MemoryCookieStore = require('tough-cookie/lib/memstore').MemoryCookieStore;
MemoryCookieStore.prototype.toJSON = function () {
	return this.idx;
};
MemoryCookieStore.prototype.fromJSON = function (json) {
	return typeof json === 'string' ? JSON.parse(json) : json;
};
```

Then you can just run these operations directly on the store like this, to deserialize:

```
	var store = new MemoryCookieStore();
	store.fromJSON('...');
	var jar = request.jar(store);
```

as you can do this to serialize:

```
	store.toJSON();
```

**Comment by icodeforlove** [comment]
The proper way to do this is to interact with the store directly, unfortunately tough cookies api is pretty verbose. Heres some pseudo code on what you need to do (putCookie, and getAllCookies are async functions)

```
// restore cookies
var cookies = ['...', '...'].map(Cookie.parse);
Promise.each(cookies, store.putCookie);

// save cookies
var cookies = store.getAllCookies().map(cookie => cookie.toString());
JSON.stringify(cookies);
```
