### ISSUE TITLE
Node 0.11 and https proxy

### ISSUE THREAD

**Issue by ksato9700** [request/request#779]
Hi,

I tried to get an https URL with proxy option, and got the following error.

>  TypeError: Request path contains unescaped characters.

The error happens only with Node.js v0.11.x, and I guess this is due to an incompatible change made in 0.11.

I tried the HEAD version of mikeal/tunnel-agent and found it works well. So, it would be nice if you can put a new tag on the HEAD version and refer it from the package.json of request.

Thank you.

**Comment by miellaby** [comment]
Hi. For all people stuck with outdated request versions (such as cordova CLI and old libnpm, ripple emulator), you may patch the problematic node_modules\request\tunnel.js by adding these lines at the beginning of addRequest() in tunnel.js line ~73 :
```javascript
   // alternative method signature : addRequest(req, obj) with obj containing host and port strings as attributes
  if (typeof host == typeof {}) {
     port = host.uri.port;
     host = host.uri.host;
   }
````
