### ISSUE TITLE
"Cookie has domain set to a public suffix" as error

### ISSUE THREAD

**Issue by reezer** [request/request#792]
Some websites cause a "Cookie has domain set to a public suffix" as error for me. I am not sure why this is handled as error. Should it really be handled that way?

**Comment by areinmeyer** [comment]
I've noticed another scenario that's different than what's previously stated, but in the `getPublicSuffix` method that generates the same error.  If the website is an internal server that does not contain any suffix at all (http://validdomain:80/path), the method will return the error "Cookie has domain set to a public suffix".  

It appears that by setting the check of `if (parts.length > suffixLen)` to `if (parts.length >= suffixLen)` this allows the domain to be considered valid.

**Comment by kopax** [comment]
Hi, I am trying to request on http:///localhost:8080 and I haVe the same error. Is there a fix for this?

**Comment by cfrefah** [comment]
Also have the same issue.
