### ISSUE TITLE
Error: Cookie not in this host's domain.

### ISSUE THREAD

**Issue by breezewish** [request/request#794]
Such kind of tough-cookie errors should be ignored, however currently they cause errors and break normal requesting.

For example, assume `http://foo.bar.com` returns headers like `Set-Cookie: NAME=value; path=/; domain=hello.bar.com`. It is an invalid cookie.
With the newest `request` module, this request will fail. I do not think this is a correct behaviour. These errors should be ignored.

**Comment by jtara1** [comment]
what would be the default domain if domain wasn't specified in the response cookie string
```
> jar.setCookie(req.cookie('abcaaa=aaa'))
Cookie="abcaaa=aaa; Path=/; hostOnly=true; aAge=0ms; cAge=0ms"
> jar.getCookieString()
''
```
