### ISSUE TITLE
Pool, agent, maxSockets & documentation

### ISSUE THREAD

**Issue by thomas-riccardi** [request/request#848]
There is little to none documentation on `pool`, `agent` & `maxSockets`.

See #588, which points to #428, which is not great.

Indeed, the solution to set `pool.maxSockets` will bypass the use of `globalPool`:
https://github.com/mikeal/request/blob/bfea018c3eaf83b18d49001797096f990b59b446/request.js#L111

``` javascript
if (!self.pool && self.pool !== false) self.pool = globalPool
```

This is probably a bug: we do want to be able to use the `globalPool` _and_ still set some agent options like `maxSockets`. See #617.

The code seems to read `maxSockets` in addition to `pool.maxSockets`, and this would bypass the bug, but this option is not documented.

Also, if we want to pass other options to the agents, we cannot use `pool.*`

In fact we can pass other options to the agents with `agentOptions`, which is not documented either.

Finally, there is no documentation to describe the `pool` object like expected and constructed in getAgent() (see #588), and it seems it's only usable with a pool constructed by Request itself (accessible only via the response of a request): we probably can't expect users to construct the pool key used in getAgent().

So I propose this:
1/ Deprecate the use of `pool.maxSockets` because it collides with the pool object agent caching, and breaks globalPool usage (maybe add an explicit option to tell "use the Request global pool too?)
2/ Also deprecated `maxSockets`, document `agentOptions` instead which seems to be well suited for this.
3/ Either deprecate `pool` altogether, or document the key format for `pool`, or add a function to request to construct it (so that users don't have to know the internal format, that could change). Even better: add a function to directly construct a `pool`, and `pool` would be an opaque object to forward to request() (this would be similar to getAgent, just isolated).

Finally, some questsions:

1/ Why do we even have a pool of agents like that? Could we have some use-case examples where it is useful? (and put them in the README.md?)

See #476: they seem to try to have different `maxSockets` per domain, but it's not working since the code that adds the host & port to the key is only for node <= 0.4. I suppose it's because since node 0.6 the `http.Agent` can work with multiple domains, so that part was removed from the key, but the `http.Agent` `maxSockets` is global to the agent, not per domain, so this useful feature is lost.
https://github.com/mikeal/request/blob/bfea018c3eaf83b18d49001797096f990b59b446/request.js#L598-L604

2/ How do I force the usage of an externally built agent, like it's done with `http.Request`? See #565.
I can't find a way to pass the agent via `pool` since I must know the key, and the key is not the same depending on the requests (at the very least it is 'http' or 'https'). Maybe add the same api as http.request: just accept an `agent` option?

(And I've only gone through the first page of issues https://github.com/mikeal/request/search?q=agent+pool&type=Issues))

**Comment by louisameline** [comment]
+1, I have a hard time understanding what this is all about and how to fix my timeout errors.

**Comment by HugoPoi** [comment]
I loose a lot of time finding issue because of the caching behavior of `request.agentClass` options.
I use `socks5-https-client` agent and discover that the cache do not care about `agentOptions`.We need to add a WARN in a documentation about this.

https://gist.github.com/HugoPoi/ef4ce3d6be3e421768265333b301f248
