### ISSUE TITLE
[Error: socket hang up] code: 'ECONNRESET'

### ISSUE THREAD

**Issue by Nascotix** [request/request#849]
When trying to upload a raw body to a express server, I got:
[Error: socket hang up] code: 'ECONNRESET'

It seems that it's only when the server handle the request on the next tick, like:

```
app.use(function (req, res) {
  process.nextTick(function () {
    res.send('ok');
  });
});
```

Here's the gist that demonstrate it:
https://gist.github.com/LoicMahieu/9813646

First we thought it was related to the size's file but it seems to be random.

Don't know if it's really related to request. Any help?

**Comment by dar5hak** [comment]
More data: I'm trying to hit the [Telegram bot API](https://core.telegram.org/bots/api) via `request`. First, I send three parallel POST requests using `async.parallel()`, and if all three of them receive a certain response, I send a fourth request in `async.parallel()`'s main callback. This fourth request always gets a socket hang up error.

**Comment by simov** [comment]
@dar5hak try this one:

```js
// create agent
var http(s) = require('http(s)')
var agent = new http(s).Agent({keepAlive:true})
// then pass that agent to each one of your requests
request({
  agent:agent
})
```
