### ISSUE TITLE
Performance degrades when using request to make http calls to EC2 instance

### ISSUE THREAD

**Issue by sgerace** [request/request#856]
I originally asked this question (nodejitsu/node-http-proxy#614) due to some issues I was having with [nodejitsu/node-http-proxy](https://github.com/nodejitsu/node-http-proxy), however, during my testing, I discovered that it was affecting the request module as well, so I figured it might be worth posting my findings here as well to see if anyone might have encountered anything like this before.

Basically, I was trying to create a simple http-proxy for an EC2 instance; however, I realized that anything I put through http-proxy was being delayed considerably. I wanted to make sure it wasn't a node thing so I tried the same requests with http.get, and everything was fine. I then wanted to isolate http-proxy and to my surprise, when I made the get call with request, it also had considerably performance degradation. 

So here is where I'm at after messing with this over the weekend; I've placed the following server code up onto a public EC2 instance so you can test it yourself (to rule out the possibility of my internet being the problem):

``` javascript
var http = require('http');

var server = http.createServer(function (req, res) {
    res.end('Hello World');
}).listen(3000);

// This was added to test what others have reported as fixing the issue
server.on('connection', function (socket) {
    'use strict';
    console.log('server.on.connection - setNoDelay');
    socket.setNoDelay(true);
});
```

The public ip address of the server is 54.209.167.233

When I request http://54.209.167.233:3000/ in my browser (I'm using the [Advanced REST Client](https://chrome.google.com/webstore/detail/advanced-rest-client/hgmloofddffdnphfgcellkdfbfbjeloo?hl=en-US) for chrome), I consistently get a response between 60-120ms. 

If I run the following code, both cases respond for me in roughly the same amount of time (about 100ms each):

``` javascript
var http = require('http');

// Stream request
console.time('stream');
http.get("http://54.209.167.233:3000/", function(res) {
    var data = '';
    res.on('data', function (chunk) {
        data += chunk;
    });
    res.on('end', function (chunk) {
        console.log(data.toString());
        console.timeEnd('stream');
    });
});

// Pipe request
console.time('pipe');
http.get("http://54.209.167.233:3000/", function (res) {
    res.pipe(process.stdout);
    res.on('end', function (chunk) {
        console.log();
        console.timeEnd('pipe');
    });
});
```

However, if I run the following example, I get times in the 800-2000ms range:

``` javascript
var request = require('request');

// Get using request module
console.time('request');
request.get({
    url: 'http://54.209.167.233:3000/'
}, function (err, res, body) {
    console.log(body);
    console.timeEnd('request');
});
```

My original tests involved using [nodejitsu/node-http-proxy](https://github.com/nodejitsu/node-http-proxy), and if you are curious to see the same result there, you can run the following example, and then request the response from localhost (I also get times in the 800-2000ms range):

``` javascript
var http = require('http');
var httpProxy = require('http-proxy');

var proxy = httpProxy.createProxyServer();
proxy.on('proxyRes', function (res) {
    res.pipe(process.stdout);
    res.on('end', function (chunk) {
        console.log();
        console.timeEnd('proxy');
    });
});

// Proxy requests
http.createServer(function (req, res) {
    console.time('proxy');
    proxy.web(req, res, { target: 'http://54.209.167.233:3000/' });
}).listen(3000);
```

This is as simple as I can make the cases and still illustrate the problem. Clearly it has something to do with EC2, but the fact that the http requests come back in a reasonable amount of time makes me think that it also has something to do with the way request (and [nodejitsu/node-http-proxy](https://github.com/nodejitsu/node-http-proxy) for that matter) are handling requests at the node level.

**Comment by Kulikowski** [comment]
It is still issue for me, I get additional 200 ms for every proxied request, EC2 - Ubuntu 14.04. Is there any fix for it already?
