### ISSUE TITLE
setTimeout should be called on the 'socket' event

### ISSUE THREAD

**Issue by dineshjoshi** [request/request#858]
Refering to this location - https://github.com/request/request/blob/f1bb537ee2440bd664ea8c445ac3a2c6e31e9932/request.js#L676

The setTimeout starts the timer immediately. However, there are two issues - 
1. The http request doesn't even get to the global Agent's queue until request.end() is called.
2. Under high load the request might actually be queued behind several requests.

Under normal circumstances, that's fine. However, under high load when the node server is handling a lot of traffic, we don't want the time out timer to start until the request actually gets a socket. We want to measure the timeout from the point the request was actually made from the host until it came back. I will be happy to submit a patch for this.

**Comment by stevenvachon** [comment]
Has this been added? I too perceived `timeout` to begin when it receives a socket.
