### ISSUE TITLE
"Only one auth mechanism allowed" error where curl is successful instead

### ISSUE THREAD

**Issue by giacecco** [request/request#860]
If _curl_ is successful doing the following:

```
curl -L -u '***:***' -o file.gz 'https://datafeeds.networkrail.co.uk/ntrod/CifFileAuthenticate?type=CIF_ALL_FULL_DAILY&day=toc-full'
```

Why doing the same with _request_ makes the server return this error message: "Only one auth mechanism allowed; only the X-Amz-Algorithm query parameter, Signature query string parameter or the Authorization header should be specified"? 

```
var fs = require('fs'),
    request = require('request');
request('https://datafeeds.networkrail.co.uk/ntrod/CifFileAuthenticate?type=CIF_ALL_FULL_DAILY&day=toc-full', { 
    'auth': { 
        'user': '***',
        'password': '***',
        'sendImmediately': true,
    },
}).pipe(fs.createWriteStream('file.gz'));
```

In case it was useful, the '-L' option in _curl_ is necessary for it to succeed. 

Thanks!

Giacecco

**Comment by mikofski** [comment]
This is still an issue for me, on Windows 7 and Ubuntu 14.04 LTS:

    $ curl -i -L -k -H "Authorization: token <token>" -H "Accept: application/octet-stream" https://api.github.com/repos/<user>/<repo>/releases/assets/<id>
    HTTP/1.1 302 Found
    Server: GitHub.com
    Date: Wed, 09 Sep 2015 20:11:17 GMT
    Content-Type: text/html;charset=utf-8
    Content-Length: 0
    Status: 302 Found
    X-RateLimit-Limit: 5000
    X-RateLimit-Remaining: 4995
    X-RateLimit-Reset: 1441832779
    location: https://s3.amazonaws.com/github-cloud/releases/<awsid>/<file-hash>?response-content-disposition=attachment; filename=<filename>&response-content-type=application/octet-stream&AWSAccessKeyId=<access-key-id>&Expires=<expires>&Signature=<signature>=
    X-XSS-Protection: 1; mode=block
    X-Frame-Options: deny
    Content-Security-Policy: default-src 'none'
    Access-Control-Allow-Credentials: true
    Access-Control-Expose-Headers: ETag, Link, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval
    Access-Control-Allow-Origin: *
    X-GitHub-Request-Id: <github:request:id>
    Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
    X-Content-Type-Options: nosniff
    Vary: Accept-Encoding
    X-Served-By: <served-by>

    HTTP/1.1 400 Bad Request
    x-amz-request-id: <amz-request-id>
    x-amz-id-2: <amz-id-2/stuff>
    Content-Type: application/xml
    Transfer-Encoding: chunked
    Date: Wed, 09 Sep 2015 20:11:18 GMT
    Connection: close
    Server: AmazonS3

    <?xml version="1.0" encoding="UTF-8"?>
    <Error>
      <Code>InvalidArgument</Code>
      <Message>
        Only one auth mechanism allowed;
        only the X-Amz-Algorithm query parameter,
        Signature query string parameter or the Authorization header should be specified
      </Message>
      <ArgumentName>Authorization</ArgumentName>
      <ArgumentValue>token </ArgumentValue>
      <RequestId></RequestId>
      <HostId></HostId>
    </Error>

what is the trick? do I have to use `wget`?

**Comment by mikofski** [comment]
Ah, but it does work in python requests. interesting.

    >>> import requests
    >>> headers = {"Authorization": "token <token>",
                   "Accept": "application/octet-stream"}
    >>> url = "https://api.github.com/repos/<user>/<repo>/releases/assets/<id>"
    >>> s = requests.get(url=url, headers=headers)
    >>> with open('<filename>', 'wb') as fp:
        fp.write(s.content)
