### ISSUE TITLE
possible .setCookie() error

### ISSUE THREAD

**Issue by klierik** [request/request#864]
Hello there.
i try to use request and i need set Cookie like that: http://take.ms/6lQ83
So i do like this:

```
var j = request.jar();
var cookie = request.cookie("lang", "ru");
j.setCookie(cookie, "https://fx-trend.com/pamm_indexes/");
```

and i get error:

```
/Volumes/LaCie/http/dev/node.js/parser/node_modules/request/node_modules/tough-cookie/lib/cookie.js:336
  str = str.trim();
            ^
TypeError: Cannot call method 'trim' of undefined
    at Function.parse (/Volumes/LaCie/http/dev/node.js/parser/node_modules/request/node_modules/tough-cookie/lib/cookie.js:336:13)
    at CookieJar.setCookie (/Volumes/LaCie/http/dev/node.js/parser/node_modules/request/node_modules/tough-cookie/lib/cookie.js:833:21)
    at CookieJar.setCookieSync (/Volumes/LaCie/http/dev/node.js/parser/node_modules/request/node_modules/tough-cookie/lib/cookie.js:1077:18)
    at RequestJar.setCookie (/Volumes/LaCie/http/dev/node.js/parser/node_modules/request/lib/cookies.js:21:20)
    at Object.<anonymous> (/Volumes/LaCie/http/dev/node.js/parser/server.js:9:3)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
```

Can u tell me please - is that a bug or my mistake?

Thank you.

**Comment by shaikui** [comment]
hey I have 3 subsequent request first call will generate the cookies which should pass to 2nd and 3 rd call. so therefore I have enabled default option jar : true , 
which is leading me an issue if i am hitting from other browser or other instance it is treating as same user and returns the old response.

how can I pass cookies to 3 subsequent calls with out deafault jar : true 


'use strict';

const azureHelper 	= require('./azure.helper');
const request     	= require('request').defaults({j : true});// madatory for cookie carry
const environment 	= azureHelper.setAzureEnvironment();

/**
 * @name Private functions
 */

/**
 * @method
 * @name getTransandCsrf
 * Get Trans and Csrf
 */
 function getTransandCsrf(){
	let resp 		= {};
	let roEnv 		= process.env.roEnv;
	let url  		= roEnv + "/Account/Login.aspx";
	let userAgent 	= "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:46.0) Gecko/20100101 Firefox/46.0";

	return new Promise( (resolve, reject) => {
		request({
			 method: 'GET',
			 url : url,
			 headers: {
				'User-Agent': userAgent
             }
			},(error, response, body) =>{
				if(response.statusCode !== 200) reject(error);
				resp.cookies = (response.headers["set-cookie"]);
				//console.log(resp.cookies);
				resp = Object.assign(resp,azureHelper.csrfandTransId(body));

				//console.log(body);
				console.log(`Status code for 1: ${response.statusCode}`);
				resolve(resp);
		}) // request
	})
};

/**
 * @method
 * @name requestSingInAndSingUp
 * Sign In and Sign Up functionality
 * @param { Object } obj - Passing Object
 * @param { Object } env - Passing Object
 * @param { String } email - Passing email
 * @param { String } password - Passing password
 */
function requestSingInAndSingUp (obj,env,email,password){
	let transId 	= obj.transId;
	let csrfId 		= obj.csrfId;
	let app 		= env.getAppUrl();
    let tenant 		= env.getTenantId();
	let policy 		= env.getPolicy();
	let cookies     = obj.cookies;
    let url2 		= ("https://" + app + "/" + tenant + "/" + policy + "/SelfAsserted?tx=" + transId + "&p=" + policy);



    var options = {
        'request_type': 'RESPONSE',
        'signInName': email ,
        'password': password,
        'g-recaptcha-response-toms': '03AEHxwuy8mq_8jbEWU--XHGea2dF-p7F-oUmZhAgpr1Xt7XyyrzBQpJZJilwhJZPG3D-K_HldpTEEl_2Xi51xm4ICCg6-w66XfR5nE1-Cj39ytH6QZiY2yJUTy-1CJZ6qNfJBsO7EG2Kba7cSGhQgetkhAxJOBtI-FJt5WlRdjP6UHgId11rSVhSCS2kphf1Z-BO62Fu2Jm6jWxnbTiVceEVXuQTOEibtQnQ-n2ckOLI-i0GI1tFBAVi6Lu6NZkQII7m_00ZyJtSoik-1LCNNQ8GXmOxFnnVTnvm-vr3mk_RmNaLS9CT6eGlo0CfpK3DiVTLEArQDTuxY'
    };

	var cheaders = {
		  'User-Agent'  		:  'Mozilla/5.0 (Windows NT 10.0; WOW64; rv:46.0) Gecko/20100101 Firefox/46.0',
		  'Content-type' 		: 'application/x-www-form-urlencoded',
		  'Accept'       		: 'application/json, text/javascript, **/*//*; q=0.01',
		  'X-Requested-With' 	: 'XMLHttpRequest',
		  'X-CSRF-TOKEN' 		: csrfId,
		  'Cookie'              : cookies
		};

	 return new Promise( (resolve, reject) => {
	 	 request({
			url: url2,
			headers:cheaders,
			method: "POST",
		    form : options
		  }, function(error, response, body){
		  	if(response.statusCode !== 200) reject(error);
		  	console.log(`Status code for 2: ${response.statusCode}`);
			  resolve(body);
		});
	 });
};

/**
 * @method
 * @name confirmIdToken
 * Confirm Token id functionality
 * @param { Object } obj - Passing Object
 * @param { Object } env - Passing Object
 */
function confirmIdToken (obj,env){
	let transId 	= obj.transId;
	let csrfId 		= obj.csrfId;
	let app 		= env.getAppUrl();
    let tenant 		= env.getTenantId();
	let policy 		= env.getPolicy();
	let cookies     = obj.cookies;
	let url =("https://"+app+"/"+tenant+"/"+policy+"/api/CombinedSigninAndSignup/confirmed?csrf_token=" + csrfId + "&tx=" + transId + "&p=" + policy);

	return new Promise( (resolve, reject) => {
		request({
					method: 'GET',
					url : url,
					headers: {
					'User-Agent': "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:46.0) Gecko/20100101 Firefox/46.0",
					'Accept' 	: "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8",
					'Cookie' : cookies
					}
			},(error, response, body) =>{
				if(response.statusCode !== 200) reject(error);
				console.log(`Status code for 3: ${response.statusCode}`);
				let token = azureHelper.cropIdToken(body)
				resolve(token);
		
		}) // request
	});
}

/**
 * Creates a new Azure Public functions.
 * @class
 */
 function azureModule (){}

/**
 * @function getAuthenticationToken
 * Get Authentication token
 * @param { Object } req - Passing request object
 * @param { function } callback - Callback method
 */
 azureModule.prototype.getAuthenticationToken  =  function(req,callback){

 let _cookieAndIds = {};
	getTransandCsrf()
		.then((data)=>{
			_cookieAndIds = data;
			return requestSingInAndSingUp(_cookieAndIds,environment,req.body.email,req.body.password);
		}).then((data)=>{
			return confirmIdToken(_cookieAndIds,environment);
		}).then((data)=>{
			callback(data)
		}).catch((err) =>{
			callback(err);
		});
}

module.exports = new azureModule();
