### ISSUE TITLE
(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.

### ISSUE THREAD

**Issue by ttback** [request/request#870]
This seems to be related to issue #311

I am trying to expand shortened urls, a rather simple task, 	
````
request( { method: "HEAD", url: shortUrl, followAllRedirects: true },
	      function (error, response) {
		if (response)
	                console.log(response.request.href);
	       }).setMaxListeners(0);
```
But calling above multiple times will trigger error:
````
(node) warning: possible EventEmitter memory leak detected. 11 listeners added. 
Use emitter.setMaxListeners() to increase limit.
Trace
    at Socket.EventEmitter.addListener (events.js:160:15)
    at Socket.Readable.on (_stream_readable.js:689:33)
````
Is there any solution to this problem?

**Comment by Seojiwoong** [comment]
https://github.com/request/request/issues/870#issuecomment-45975720

**Comment by Seojiwoong** [comment]
https://github.com/request/request/issues/870

**Comment by seanstrom** [comment]
I think this behavior as been explained in https://github.com/request/request/issues/311#issuecomment-53656591

**Comment by seanstrom** [comment]
This is probably an issue for people still but this was the final response on https://github.com/request/request/issues/311#issuecomment-53656591
