### ISSUE TITLE
set encoding error

### ISSUE THREAD

**Issue by liaolei0826** [request/request#872]
at request.js  line 955
 if (self.encoding === null) {
            response.body = body
  } else {
            response.body = body.toString(self.encoding)
   }

if you  have not set encoding   self.encoding is undefined  and it will return  body.toString(undefined)

**Comment by lgreenlee** [comment]
It doesn't seem to do this, and results in a not very obvious exception when downloading very large binary files. It would be nice if the encoding was explicitly initialized to a default if undefined.
