### ISSUE TITLE
Object #<Object> has no method 'unpipe'

### ISSUE THREAD

**Issue by kirbysayshi** [request/request#874]
The request object has a `pipe`, but no unpipe! Would be nice for long lived streams.

**Comment by rehia** [comment]
It would be cool if there is a workaround.
@dogawaf did you find any ?
I want to write the exact same code
Thanks

**Comment by NathanRSmith** [comment]
A workaround would be to pipe to a transform stream and pipe/unpipe that.

```
var through = require('through2');

var r = request(url);
var tstream = through(function(chunk, enc, cb) { cb(null, chunk); });
r.pipe(tstream).pipe(new fs.createWriteStream(tmp));
r.on('response', function(response) {
  if (response.statusCode !== 200) {
    tstream.unpipe(writableStream);
    writableStream.end();
  }
});
```

**Comment by xieranmaya** [comment]
I've found that if the `error` event triggers, there will be no data coming out from the readable stream, so you just need to do something in the `on('end')` callback.

**Comment by mooop12** [comment]
3 years later, still no news?

**Comment by bradodarb** [comment]
@mikeal ... How can we get this pushed through?
