### ISSUE TITLE
SELF_SIGNED_CERT_IN_CHAIN with Charles Proxy

### ISSUE THREAD

**Issue by mrjcleaver** [request/request#883]
Using http://www.charlesproxy.com/documentation/using-charles/ssl-certificates/ with request...

I just thought I'd point out that I solved https://github.com/coolaj86/node-ssl-root-cas/issues/3, 

I was getting
````
ERR Error: SSL Error: SELF_SIGNED_CERT_IN_CHAIN
````

A solution on that ticket.

Perhaps this can be documented to save some other soul such searching :)

**Comment by jfeldstein** [comment]
How did you solve it??

**Comment by jfeldstein** [comment]
Ah, found it: https://github.com/coolaj86/node-ssl-root-cas/issues/3#issuecomment-41684616
