### ISSUE TITLE
promise?

### ISSUE THREAD

**Issue by ralyodio** [request/request#910]
Is there anyway to use a promise with request()?

I found this, but maybe there is something better.

https://coderwall.com/p/9cifuw

**Comment by Yimiprod** [comment]
Hi, hi have use bluebird in my project with request.
I try to retrive a zip file with request, but even after .spread() the file is not complet.
I do something like
```
request.getAsyn(url)
  .spread(function(res, body) {
    return fs.writeFileAsync(filename, body);
  })
  .then(function(file) {
    // Unzip functions
  });
```
But it's not working, the file is not complete, even trying to unzip it manually.

**Comment by analog-nico** [comment]
@Yimiprod did you try the same code without promises and just plain Request + callback? Maybe you need better options for the request itself.
