### ISSUE TITLE
Sending requests with content-length equal to zero raises an error

### ISSUE THREAD

**Issue by forw** [request/request#920]
In the request.js file there is a check:
if (length) {
    if (!self.hasHeader('content-length')) self.setHeader('content-length', length)
} else {
    throw new Error('Argument error, options.body.')
}
which prevents sending files with zero length. I understand this not very important issue, but still. Specification says "Any Content-Length greater than or equal to zero is a valid value." (http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html)

I faced with this restriction when using cradle which we use to save user files to CouchDB and some of files have zero length (CouchDB also accepts empty files), so the problem is caused only by the request module.

**Comment by kavehfa** [comment]
+1
