### ISSUE TITLE
Authorization: Bearer header with auth shouldn't require user & password

### ISSUE THREAD

**Issue by ryanseys** [request/request#923]
``` javascript
request({
  url: 'https://example.com',
  auth: {
    bearer: 'my token'
  }
}, function() { /* ... */ });
```

fails because `Error: auth() received invalid user or password`. If I have a token I want to specify instead of user and password, why do I also need to provide a user / password?

I realize I can just set an `Authorization` header but thought this was weird. Any thoughts?

**Comment by AttaMarwat879** [comment]
> @ryanseys I was receiving the same error and discovered it was because I was using version 2.34 which doesn't include the bearer feature. Upgrade to 2.36 and it should work as expected.

what to upgrade npm, node or something other ?
plz specify your answar i am also facing same problem

**Comment by usamyismy7** [comment]
I had this issue.
My problem was that i added surge secret to environment secret rather than repository secret. No need to update anything just add surge token to the repository secret. The error will resolve.
