### ISSUE TITLE
Incorrect cookie date handling with CookieJar (mangled expires dates)

### ISSUE THREAD

**Issue by Sironfoot** [request/request#948]
Consider the following code:

````javascript
var request = require('request');

var cookieJar = request.jar();
var loginUrl = 'https://www.boots.com/webapp/wcs/stores/servlet/LogonForm?storeId=10052&langId=-1&catalogId=11051&URL=http%3A%2F%2Fwww.boots.com%2F';

request.get({ url: loginUrl, jar: cookieJar }, function(err, res, body) {
    console.log(res.headers);
    console.log(cookieJar);
});
````

This code makes an HTTP GET request to the boots.com login page, and then spits out the response headers and the contents of the cookie jar.

If I examine the res headers, they look something like:

````
{
    server: 'IBM_HTTP_Server',
    pragma: 'No-cache',
    ....more headers (snip)...

    'set-cookie': 
    [
        'WCDC_CURRID=ABC123; Expires=Thu, 26-Jun-14 18:59:58 GMT; Path=/',
        ....more cookies (snip)....
    ]
}
````

Notice the expires date of the cookie "Thu, 26-Jun-14 18:59:58 GMT". Now examine the contents of the cookie jar:

````
{
_jar: 
   { store: 
      { idx: { 'www.boots.com': 
         { '/': 
            { 
              WCDC_CURRID: Cookie="WCDC_CURRID=ABC123; Expires=Mon, 26 Jun 142000 18:59:58 GMT; Path=/; hostOnly=true; aAge=416ms; cAge=416ms",
              ... more cookies (snip)....
````

Notice that the cookie expires date is "Mon, 26 Jun 142000 18:59:58 GMT", the year 142000? WTF!?

It's not just this one cookie either, all of them seem to have mangled dates. Some of them even look like this:

````
BP: Cookie="BP=; Expires=undefined, 0NaN undefined NaN 0NaN:0NaN:0NaN GMT; Domain=boots.com; Path=/; hostOnly=false; aAge=415ms; cAge=415ms"
````

Anything obvious I'm missing that's causing this? A bug with tough-cookie perhaps. I tried the Boots login page in Chrome browser and all the cookie expires dates seem to be interpreted correctly.

**Comment by lalitkapoor** [comment]
resolved by https://github.com/SalesforceEng/tough-cookie/pull/30
