### ISSUE TITLE
Contributor Call Next Week

### ISSUE THREAD

**Issue by mikeal** [request/request#982]
First of all, I'd like to thank every contributor to `request`. This project isn't maintainable by a single person and I've relied on you all a lot for help.

Similarly, I think that the work of "leading" the project, and the 3.0 effort, is also now more than I can handle on my own. It's about time to formalize some of the project management and spread out more of the responsibility and visibility of `request`.

I'd like to have a call next week on Tuesday to discuss how to move forward. I'll invite all of the existing collaborators, if you aren't interested cause you haven't been involved in a while feel free to ignore this. If you are interested in participating please give me your preferred email (for Google Hangouts) and the timezone you're in so I can try to find a good time.

Benjamin Atkin @benatkin 
Isaac Z. Schlueter @isaacs 
Jason Smith @jhs 
Brian White @mscdex 
Eran Hammer @hueniverse 
Marco Rogers @polotek 
James Nylen @nylen 
Andreas Lind @papandreou 
Maciej Małecki @mmalecki 
Jeremy Stashewsky @stash 
Lalit Kapoor @lalitkapoor 
Kevin Locke @kevinoid 
Loïc Mahieu @LoicMahieu

**Comment by lalitkapoor** [comment]
Hi Mikeal,

I’m in NYC (EST). This is my preferred email for Google Hangouts (redacted).

I’m happy to see this moving forward.

Cheers,
Lalit

-- 
Lalit Kapoor
Sent with Airmail

On July 29, 2014 at 3:00:55 PM, Mikeal Rogers (notifications@github.com) wrote:

First of all, I'd like to thank every contributor to request. This project isn't maintainable by a single person and I've relied on you all a lot for help.

Similarly, I think that the work of "leading" the project, and the 3.0 effort, is also now more than I can handle on my own. It's about time to formalize some of the project management and spread out more of the responsibility and visibility of request.

I'd like to have a call next week on Tuesday to discuss how to move forward. I'll invite all of the existing collaborators, if you aren't interested cause you haven't been involved in a while feel free to ignore this. If you are interested in participating please give me your preferred email (for Google Hangouts) and the timezone you're in so I can try to find a good time.

Benjamin Atkin @benatkin
Isaac Z. Schlueter @isaacs
Jason Smith @jhs
Brian White @mscdex
Eran Hammer @hueniverse
Marco Rogers @polotek
James Nylen @nylen
Andreas Lind @papandreou
Maciej Małecki @mmalecki
Jeremy Stashewsky @stash
Lalit Kapoor @lalitkapoor
Kevin Locke @kevinoid
Loïc Mahieu @LoicMahieu
