### ISSUE TITLE
auto parse application/json

### ISSUE THREAD

**Issue by timoxley** [request/request#99]
Is there a reason why request doesn't (or isn't) automatically JSON.parsing the body if it detects the application/json\* content-type header (or perhaps if the url ends in .json?  

my current json header is: 

`Content-Type: application/json; charset=utf-8`

eg:

``` javascript
 request('http://localhost:4000/datas.json'}, function(error, response, body) {
    console.log(typeof body) // = string! but the server returned JSON
}
```

``` javascript
request({url: 'http://localhost:4000/datas.json', json: true}, function(error, response, body) {
    console.log(typeof body) // = object. great, but the json:true could be inferred.
}
```

**Comment by magicdawn** [comment]
Yeah, [superagent](https://github.com/visionmedia/superagent) supports auto parse

**Comment by magicdawn** [comment]
And using a `form: { xxx }` & `json: true` will generate `content-type: application/x-www-form-urlencoded` request

I just do not understand, we use `form` / `formData` to get `urlencoded` / `multipart` content-type request, but why `json: true` will control the request header?

I think `json` just control the response, and parse the body as json, the request content-type  depends on`typeof options.body` is better.

- `string` -> `text/plain`
- `object` -> `application/json`

**Comment by magicdawn** [comment]
Anyway. switching to request-promise
