### ISSUE TITLE
handle an xlsx response

### ISSUE THREAD

**Issue by rcrooks** [request/request#994]
Not sure if this is an issue or just my lack of understanding. I'm using request in a proxy that gets authentication credentials for API calls, makes the call, and returns the response to the client. In one case, the API returns xlxs data, and when I returned that to the client, a XXXXX.xlsx file does download automatically, but it's corrupted in some way and can't be opened by Excel. I think it's some kind of encoding mismatch issue, but can't figure out what or how to solve it.

**Comment by anoopmd** [comment]
@nylen Thank You.

I have an endpoint that return excel report encoded in base64 format.
While making the request, passing encoding as null OR base64 worked for me.
