### ISSUE TITLE
Support for gss/spnego negotiation

### ISSUE THREAD

**Issue by wdavidw** [request/request#997]
I wish I could help more but for now, i dont know how to retrieve a kerberos ticket to wrap it in a spnego Negotiate header

**Comment by dmansfield** [comment]
I have gotten this working using the "kerberos" module mentioned above.  It's a http client that successfully authenticates using a krb5 credentials cache against a server protected with apache+mod_auth_kerb.  Here's the Gist:

https://gist.github.com/dmansfield/c75817dcacc2393da0a7
